/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ioproxy-rpc.h"

bool_t
xdr_int64 (XDR *xdrs, int64 *objp)
{
	register int32_t *buf;

	 if (!xdr_int64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uint64 (XDR *xdrs, uint64 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uint32 (XDR *xdrs, uint32 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int32 (XDR *xdrs, int32 *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ioppath (XDR *xdrs, ioppath *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fileid1 (XDR *xdrs, fileid1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uid1 (XDR *xdrs, uid1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gid1 (XDR *xdrs, gid1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_size1 (XDR *xdrs, size1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_offset1 (XDR *xdrs, offset1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mode1 (XDR *xdrs, mode1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_perm1 (XDR *xdrs, perm1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_count1 (XDR *xdrs, count1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_status1 (XDR *xdrs, status1 *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nametype (XDR *xdrs, nametype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_namelist (XDR *xdrs, namelist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct namenode), (xdrproc_t) xdr_namenode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_namenode (XDR *xdrs, namenode *objp)
{
	register int32_t *buf;

	 if (!xdr_nametype (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_namelist (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readdir_res (XDR *xdrs, readdir_res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_namelist (xdrs, &objp->readdir_res_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPOPEN1args (XDR *xdrs, IOPOPEN1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_mode1 (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPOPEN1res (XDR *xdrs, IOPOPEN1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_fileid1 (xdrs, &objp->IOPOPEN1res_u.fd))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPCLOSE1args (XDR *xdrs, IOPCLOSE1args *objp)
{
	register int32_t *buf;

	 if (!xdr_fileid1 (xdrs, &objp->fd))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPCLOSE1res (XDR *xdrs, IOPCLOSE1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPCLOSE1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPCREAT1args (XDR *xdrs, IOPCREAT1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_mode1 (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_perm1 (xdrs, &objp->perm))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPCREAT1res (XDR *xdrs, IOPCREAT1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_fileid1 (xdrs, &objp->IOPCREAT1res_u.fd))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPUNLINK1args (XDR *xdrs, IOPUNLINK1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPUNLINK1res (XDR *xdrs, IOPUNLINK1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPUNLINK1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPREAD1args (XDR *xdrs, IOPREAD1args *objp)
{
	register int32_t *buf;

	 if (!xdr_fileid1 (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_offset1 (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_count1 (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_res (XDR *xdrs, write_res *objp)
{
	register int32_t *buf;

	 if (!xdr_count1 (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPREAD1res (XDR *xdrs, IOPREAD1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_write_res (xdrs, &objp->IOPREAD1res_u.res))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPWRITE1args (XDR *xdrs, IOPWRITE1args *objp)
{
	register int32_t *buf;

	 if (!xdr_fileid1 (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_offset1 (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_count1 (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPWRITE1res (XDR *xdrs, IOPWRITE1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_count1 (xdrs, &objp->IOPWRITE1res_u.result))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPMKDIR1args (XDR *xdrs, IOPMKDIR1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_mode1 (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPMKDIR1res (XDR *xdrs, IOPMKDIR1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPMKDIR1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPOPENDIR1args (XDR *xdrs, IOPOPENDIR1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPOPENDIR1res (XDR *xdrs, IOPOPENDIR1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPOPENDIR1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPRMDIR1args (XDR *xdrs, IOPRMDIR1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPRMDIR1res (XDR *xdrs, IOPRMDIR1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPRMDIR1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPREADDIR1args (XDR *xdrs, IOPREADDIR1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPREADDIR1res (XDR *xdrs, IOPREADDIR1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_readdir_res (xdrs, &objp->IOPREADDIR1res_u.res))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPCLOSEDIR1args (XDR *xdrs, IOPCLOSEDIR1args *objp)
{
	register int32_t *buf;

	 if (!xdr_fileid1 (xdrs, &objp->fd))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPCLOSEDIR1res (XDR *xdrs, IOPCLOSEDIR1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPCLOSEDIR1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPRENAME1args (XDR *xdrs, IOPRENAME1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->pathin))
		 return FALSE;
	 if (!xdr_ioppath (xdrs, &objp->pathout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPRENAME1res (XDR *xdrs, IOPRENAME1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPRENAME1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPGETATTR1args (XDR *xdrs, IOPGETATTR1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPGETATTR1res (XDR *xdrs, IOPGETATTR1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_stat (xdrs, &objp->IOPGETATTR1res_u.buf))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPSETATTR1args (XDR *xdrs, IOPSETATTR1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_stat (xdrs, &objp->buf))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPSETATTR1res (XDR *xdrs, IOPSETATTR1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPSETATTR1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPSTATFS1args (XDR *xdrs, IOPSTATFS1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPSTATFS1res (XDR *xdrs, IOPSTATFS1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_statfs (xdrs, &objp->IOPSTATFS1res_u.buf))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPFLUSH1args (XDR *xdrs, IOPFLUSH1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPFLUSH1res (XDR *xdrs, IOPFLUSH1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPFLUSH1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPPRELOAD1args (XDR *xdrs, IOPPRELOAD1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPPRELOAD1res (XDR *xdrs, IOPPRELOAD1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_status1 (xdrs, &objp->IOPPRELOAD1res_u.errno))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_IOPSTATFSSERVER1args (XDR *xdrs, IOPSTATFSSERVER1args *objp)
{
	register int32_t *buf;

	 if (!xdr_ioppath (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IOPSTATFSSERVER1res (XDR *xdrs, IOPSTATFSSERVER1res *objp)
{
	register int32_t *buf;

	 if (!xdr_status1 (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_bytes (xdrs, (char **)&objp->IOPSTATFSSERVER1res_u.data.data_val, (u_int *) &objp->IOPSTATFSSERVER1res_u.data.data_len, ~0))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
