/* include/config.h.  Generated by configure.  */


/*
 * Types
 */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* 
 * #if (! defined (size_t))
 * typedef unsigned long size_t;
 * #endif
 */

/*
 * #if (! defined (ssize_t))
 * typedef long ssize_t;
 * #endif
 */
/*
 * #if (! defined (off_t))
 * typedef long long unsigned  int off_t;
 * #endif
 */


/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void


/*
 * Functions
 */

/* Define if you don't have vprintf but do have _doprnt.  */
/* #undef HAVE_DOPRNT */

/* Define if you have the vprintf function.  */
#define HAVE_VPRINTF 1

/* Define if you have the gethostname function.  */
#define HAVE_GETHOSTNAME 1

/* Define if you have the gettimeofday function.  */
#define HAVE_GETTIMEOFDAY 1

/* Define if you have the select function.  */
#define HAVE_SELECT 1

/* Define if you have the socket function.  */
#define HAVE_SOCKET 1

/* Define if you have the strdup function.  */
#define HAVE_STRDUP 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define if you have the memcmp function.  */
#define HAVE_MEMCMP 1

/* Define if you have the memmove function.  */
#define HAVE_MEMMOVE 1

/* Define if you have the memset function.  */
#define HAVE_MEMSET 1


/*
 * Headers
 */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define if you have <sys/wait.h> that is POSIX.1 compatible.  */
#define HAVE_SYS_WAIT_H 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if you have the <dirent.h> header file.  */
#define HAVE_DIRENT_H 1

/* Define if you have the <fcntl.h> header file.  */
#define HAVE_FCNTL_H 1

/* Define if you have the <limits.h> header file.  */
/* #undef HAVE_LIMITS_H */

/* Define if you have the <malloc.h> header file.  */
/* #undef HAVE_MALLOC_H */

/* Define if you have the <strings.h> header file.  */
#define HAVE_STRINGS_H 1

/* Define if you have the <string.h> header file.  */
#define HAVE_STRING_H 1

/* Define if you have the <sys/dir.h> header file.  */
/* #undef HAVE_SYS_DIR_H */

/* Define if you have the <sys/ioctl.h> header file.  */
#define HAVE_SYS_IOCTL_H 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the <pthread.h> header file.  */
#define HAVE_PTHREAD_H 1

/* Define if you have <netinet/in.h> header file.  */
#define HAVE_NETINET_IN_H 1

/* Define if you have <windows.h> header file.  */
/* #undef HAVE_WINDOWS_H */

/* Define if you have <rpc/rpc.h> header file.  */
#define HAVE_RPC_RPC_H 1

/* Define if you have <rpc/clnt.h> header file.  */
#define HAVE_RPC_CLNT_H 1

/* Define if you have <rpc/types.h> header file.  */
#define HAVE_RPC_TYPES_H 1

/* Define if you have <fcntl.h> header file.  */
#define HAVE_FCNTL_H 1


/*
 * Libraries
 */

/* Define if you have the pthread library (-lpthread).  */
#define HAVE_LIBPTHREAD 1

