
  /*
   *  Copyright 2020-2024 Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos
   *
   *  This file is part of Expand.
   *
   *  Expand is free software: you can redistribute it and/or modify
   *  it under the terms of the GNU Lesser General Public License as published by
   *  the Free Software Foundation, either version 3 of the License, or
   *  (at your option) any later version.
   *
   *  Expand is distributed in the hope that it will be useful,
   *  but WITHOUT ANY WARRANTY; without even the implied warranty of
   *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   *  GNU Lesser General Public License for more details.
   *
   *  You should have received a copy of the GNU Lesser General Public License
   *  along with Expand.  If not, see <http://www.gnu.org/licenses/>.
   *
   */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

//#include <memory.h> /* for memset */

#include "nfi/nfi_nfs3/nfs3.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
nfsproc3_null_3(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_getattr_3(fhandle3 *argp, getattr3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_GETATTR,
		(xdrproc_t) xdr_fhandle3, (caddr_t) argp,
		(xdrproc_t) xdr_getattr3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_setattr_3(setattr3args *argp, wccstat3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_SETATTR,
		(xdrproc_t) xdr_setattr3args, (caddr_t) argp,
		(xdrproc_t) xdr_wccstat3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_lookup_3(diropargs3 *argp, lookup3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_LOOKUP,
		(xdrproc_t) xdr_diropargs3, (caddr_t) argp,
		(xdrproc_t) xdr_lookup3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_access_3(access3args *argp, access3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_ACCESS,
		(xdrproc_t) xdr_access3args, (caddr_t) argp,
		(xdrproc_t) xdr_access3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_readlink_3(fhandle3 *argp, readlink3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_READLINK,
		(xdrproc_t) xdr_fhandle3, (caddr_t) argp,
		(xdrproc_t) xdr_readlink3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_read_3(read3args *argp, read3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_READ,
		(xdrproc_t) xdr_read3args, (caddr_t) argp,
		(xdrproc_t) xdr_read3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_write_3(write3args *argp, write3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_WRITE,
		(xdrproc_t) xdr_write3args, (caddr_t) argp,
		(xdrproc_t) xdr_write3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_create_3(create3args *argp, diropres3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_CREATE,
		(xdrproc_t) xdr_create3args, (caddr_t) argp,
		(xdrproc_t) xdr_diropres3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_mkdir_3(mkdir3args *argp, diropres3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_MKDIR,
		(xdrproc_t) xdr_mkdir3args, (caddr_t) argp,
		(xdrproc_t) xdr_diropres3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_symlink_3(symlink3args *argp, diropres3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_SYMLINK,
		(xdrproc_t) xdr_symlink3args, (caddr_t) argp,
		(xdrproc_t) xdr_diropres3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_mknod_3(mknod3args *argp, diropres3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_MKNOD,
		(xdrproc_t) xdr_mknod3args, (caddr_t) argp,
		(xdrproc_t) xdr_diropres3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_remove_3(diropargs3 *argp, wccstat3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_REMOVE,
		(xdrproc_t) xdr_diropargs3, (caddr_t) argp,
		(xdrproc_t) xdr_wccstat3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_rmdir_3(diropargs3 *argp, wccstat3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_RMDIR,
		(xdrproc_t) xdr_diropargs3, (caddr_t) argp,
		(xdrproc_t) xdr_wccstat3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_rename_3(rename3args *argp, rename3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_RENAME,
		(xdrproc_t) xdr_rename3args, (caddr_t) argp,
		(xdrproc_t) xdr_rename3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_link_3(link3args *argp, link3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_LINK,
		(xdrproc_t) xdr_link3args, (caddr_t) argp,
		(xdrproc_t) xdr_link3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_readdir_3(readdir3args *argp, readdir3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_READDIR,
		(xdrproc_t) xdr_readdir3args, (caddr_t) argp,
		(xdrproc_t) xdr_readdir3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_readdirplus_3(readdirplus3args *argp, readdirplus3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_READDIRPLUS,
		(xdrproc_t) xdr_readdirplus3args, (caddr_t) argp,
		(xdrproc_t) xdr_readdirplus3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_fsstat_3(fhandle3 *argp, fsstat3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_FSSTAT,
		(xdrproc_t) xdr_fhandle3, (caddr_t) argp,
		(xdrproc_t) xdr_fsstat3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_fsinfo_3(fhandle3 *argp, fsinfo3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_FSINFO,
		(xdrproc_t) xdr_fhandle3, (caddr_t) argp,
		(xdrproc_t) xdr_fsinfo3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_pathconf_3(fhandle3 *argp, pathconf3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_PATHCONF,
		(xdrproc_t) xdr_fhandle3, (caddr_t) argp,
		(xdrproc_t) xdr_pathconf3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nfsproc3_commit_3(commit3args *argp, commit3res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NFSPROC3_COMMIT,
		(xdrproc_t) xdr_commit3args, (caddr_t) argp,
		(xdrproc_t) xdr_commit3res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc3_null_3(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC3_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc3_mnt_3(nfspath3 *argp, mountres3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC3_MNT,
		(xdrproc_t) xdr_nfspath3, (caddr_t) argp,
		(xdrproc_t) xdr_mountres3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc3_dump_3(void *argp, mountlist3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC3_DUMP,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_mountlist3, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc3_umnt_3(nfspath3 *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC3_UMNT,
		(xdrproc_t) xdr_nfspath3, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc3_umntall_3(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC3_UMNTALL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc3_export_3(void *argp, exports3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC3_EXPORT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_exports3, (caddr_t) clnt_res,
		TIMEOUT));
}
