#ifndef _NFI_MPISERVER_ERR_H_
#define _NFI_MPISERVER_ERR_H_


 #ifdef  __cplusplus
    extern "C" {
 #endif

enum nfi_mpiServer_err
{
	MPISERVERERR_PARAM = 0,
	MPISERVERERR_MEMORY = 1,
	MPISERVERERR_URL = 2,
	MPISERVERERR_MNTCONNECTION = 3,
	MPISERVERERR_MOUNT = 4,
	MPISERVERERR_NFSCONNECTION = 5,		
	MPISERVERERR_GETATTR = 6,
	MPISERVERERR_LOOKUP = 7,
	MPISERVERERR_READ = 8,
	MPISERVERERR_WRITE = 9,
	MPISERVERERR_CREATE = 10,
	MPISERVERERR_REMOVE = 11,
	MPISERVERERR_MKDIR = 12,
	MPISERVERERR_READDIR = 13,
	MPISERVERERR_STATFS = 14,
	MPISERVERERR_NOTDIR = 15,
};

void mpiServer_err(int err);


 #ifdef  __cplusplus
     }
 #endif


#endif
