.TH "__dirstream" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__dirstream \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn_bypass\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char data[0] \fB__attribute__\fP ((aligned(__alignof__(void *))))"
.br
.ti -1c
.RI "char data[0] \fB__attribute__\fP ((aligned(__alignof__(void *))))"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.RI "File descriptor\&. "
.ti -1c
.RI "size_t \fBallocation\fP"
.br
.RI "Space allocated for the block\&. "
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "Total valid data in the block\&. "
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.RI "Current offset into the block\&. "
.ti -1c
.RI "off_t \fBfilepos\fP"
.br
.RI "Position of next entry to read\&. "
.ti -1c
.RI "char * \fBpath\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB95\fP of file \fBxpn_bypass\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "char data[0] __dirstream::__attribute__ ((aligned(__alignof__(void *))))"

.SS "char data[0] __dirstream::__attribute__ ((aligned(__alignof__(void *))))"

.SH "Field Documentation"
.PP 
.SS "size_t __dirstream::allocation"

.PP
Space allocated for the block\&. 
.PP
Definition at line \fB99\fP of file \fBxpn_bypass\&.h\fP\&.
.SS "int __dirstream::fd"

.PP
File descriptor\&. 
.PP
Definition at line \fB97\fP of file \fBxpn_bypass\&.h\fP\&.
.SS "off_t __dirstream::filepos"

.PP
Position of next entry to read\&. 
.PP
Definition at line \fB102\fP of file \fBxpn_bypass\&.h\fP\&.
.SS "size_t __dirstream::offset"

.PP
Current offset into the block\&. 
.PP
Definition at line \fB101\fP of file \fBxpn_bypass\&.h\fP\&.
.SS "char * __dirstream::path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB105\fP of file \fBxpn_bypass\&.h\fP\&.
.SS "size_t __dirstream::size"

.PP
Total valid data in the block\&. 
.PP
Definition at line \fB100\fP of file \fBxpn_bypass\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
