.TH "xpn Directory Reference" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBxpn_simple\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBxpn_lib\&.h\fP"
.br
.RI "Header file to 'TODO'\&. "
.in -1c
