.TH "xpn_client Directory Reference" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_client Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBnfi\fP"
.br
.ti -1c
.RI "directory \fBxpn\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBxpn_stdio\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.ti -1c
.RI "file \fBxpn_unistd\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.in -1c
