.TH "nfi Directory Reference" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcommon\fP"
.br
.ti -1c
.RI "directory \fBnfi_local\fP"
.br
.ti -1c
.RI "directory \fBnfi_mpi_server\fP"
.br
.ti -1c
.RI "directory \fBnfi_nfs\fP"
.br
.ti -1c
.RI "directory \fBnfi_nfs3\fP"
.br
.ti -1c
.RI "directory \fBnfi_tcp_server\fP"
.br
.in -1c
