.TH "xpn_simple Directory Reference" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_simple Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBpolicy\fP"
.br
.ti -1c
.RI "directory \fBxpncore\fP"
.br
.in -1c
