.TH "mpi_server Directory Reference" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpi_server Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsrc/mpi_server/config\&.h\fP"
.br
.ti -1c
.RI "file \fBmpi_server\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.ti -1c
.RI "file \fBmpi_server/mpi_server_comm\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.ti -1c
.RI "file \fBmpi_server_d2xpn\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.ti -1c
.RI "file \fBmpi_server_ops\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.ti -1c
.RI "file \fBmpi_server_params\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.in -1c
