.TH "utils Directory Reference" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcp\-local2xpn\&.c\fP"
.br
.ti -1c
.RI "file \fBcp\-xpn2local\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn\-cat\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn\-ls\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn\-mkdir\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn\-rm\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn\-rmdir\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn\-statfs\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn_cp\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn_ls\&.c\fP"
.br
.ti -1c
.RI "file \fBxpn_rebuild\&.c\fP"
.br
.ti -1c
.RI "file \fBxpncp\&.c\fP"
.br
.ti -1c
.RI "file \fBxpncp_m\&.c\fP"
.br
.ti -1c
.RI "file \fBxpncp_th\&.c\fP"
.br
.ti -1c
.RI "file \fBxpnwriter\&.c\fP"
.br
.in -1c
