.TH "nfi_mpi_server Directory Reference" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_mpi_server Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBxpn_client/nfi/nfi_mpi_server/mpi_server_comm\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.ti -1c
.RI "file \fBnfi_mpi_server\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.ti -1c
.RI "file \fBnfi_mpi_server_err\&.c\fP"
.br
.RI "File to 'TODO'\&. "
.in -1c
