.TH "all_system.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
all_system.h \- Header file to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'base_debug\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <semaphore\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKB\fP   (1024)"
.br
.ti -1c
.RI "#define \fBMB\fP   (\fBKB\fP * \fBKB\fP)"
.br
.ti -1c
.RI "#define \fBGB\fP   (\fBKB\fP * \fBKB\fP * \fBKB\fP)"
.br
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBLARGEFILE_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fBPATH_MAX\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_BUFFER_SIZE\fP   (1 * \fBMB\fP)"
.br
.ti -1c
.RI "#define \fBPROTOCOL_MAXLEN\fP   20"
.br
.ti -1c
.RI "#define \fBO_ACCMODE\fP   0003"
.br
.ti -1c
.RI "#define \fBO_RDONLY\fP   00"
.br
.ti -1c
.RI "#define \fBO_WRONLY\fP   01"
.br
.ti -1c
.RI "#define \fBO_RDWR\fP   02"
.br
.ti -1c
.RI "#define \fBO_CREAT\fP   0100  /* not \fBfcntl\fP */"
.br
.ti -1c
.RI "#define \fBO_EXCL\fP   0200   /* not \fBfcntl\fP */"
.br
.ti -1c
.RI "#define \fBO_NOCTTY\fP   0400 /* not \fBfcntl\fP */"
.br
.ti -1c
.RI "#define \fBO_TRUNC\fP   01000 /* not \fBfcntl\fP */"
.br
.ti -1c
.RI "#define \fBO_APPEND\fP   02000"
.br
.ti -1c
.RI "#define \fBO_NONBLOCK\fP   04000"
.br
.ti -1c
.RI "#define \fBO_NDELAY\fP   \fBO_NONBLOCK\fP"
.br
.ti -1c
.RI "#define \fBO_SYNC\fP   010000"
.br
.ti -1c
.RI "#define \fBO_FSYNC\fP   \fBO_SYNC\fP"
.br
.ti -1c
.RI "#define \fBO_ASYNC\fP   020000"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file to 'TODO'\&. 

Header file to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Copyright 2020-2023 Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBall_system\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define FALSE   0"

.PP
Definition at line \fB153\fP of file \fBall_system\&.h\fP\&.
.SS "#define GB   (\fBKB\fP * \fBKB\fP * \fBKB\fP)"

.PP
Definition at line \fB146\fP of file \fBall_system\&.h\fP\&.
.SS "#define KB   (1024)"

.PP
Definition at line \fB140\fP of file \fBall_system\&.h\fP\&.
.SS "#define LARGEFILE_SOURCE   1"

.PP
Definition at line \fB157\fP of file \fBall_system\&.h\fP\&.
.SS "#define MAX_BUFFER_SIZE   (1 * \fBMB\fP)"

.PP
Definition at line \fB173\fP of file \fBall_system\&.h\fP\&.
.SS "#define MB   (\fBKB\fP * \fBKB\fP)"

.PP
Definition at line \fB143\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_ACCMODE   0003"

.PP
Definition at line \fB179\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_APPEND   02000"

.PP
Definition at line \fB187\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_ASYNC   020000"

.PP
Definition at line \fB192\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_CREAT   0100  /* not \fBfcntl\fP */"

.PP
Definition at line \fB183\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_EXCL   0200   /* not \fBfcntl\fP */"

.PP
Definition at line \fB184\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_FSYNC   \fBO_SYNC\fP"

.PP
Definition at line \fB191\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_NDELAY   \fBO_NONBLOCK\fP"

.PP
Definition at line \fB189\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_NOCTTY   0400 /* not \fBfcntl\fP */"

.PP
Definition at line \fB185\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_NONBLOCK   04000"

.PP
Definition at line \fB188\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_RDONLY   00"

.PP
Definition at line \fB180\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_RDWR   02"

.PP
Definition at line \fB182\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_SYNC   010000"

.PP
Definition at line \fB190\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_TRUNC   01000 /* not \fBfcntl\fP */"

.PP
Definition at line \fB186\fP of file \fBall_system\&.h\fP\&.
.SS "#define O_WRONLY   01"

.PP
Definition at line \fB181\fP of file \fBall_system\&.h\fP\&.
.SS "#define PATH_MAX   1024"

.PP
Definition at line \fB169\fP of file \fBall_system\&.h\fP\&.
.SS "#define PROTOCOL_MAXLEN   20"

.PP
Definition at line \fB176\fP of file \fBall_system\&.h\fP\&.
.SS "#define TRUE   1"

.PP
Definition at line \fB150\fP of file \fBall_system\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
