.TH "arguments" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arguments
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBbuffer_size\fP"
.br
.ti -1c
.RI "struct stat \fBst\fP"
.br
.ti -1c
.RI "int \fBdo_stat\fP"
.br
.ti -1c
.RI "int \fBsilent\fP"
.br
.ti -1c
.RI "int \fBvery_silent\fP"
.br
.ti -1c
.RI "int \fBdebug\fP"
.br
.ti -1c
.RI "char * \fBsource\fP"
.br
.ti -1c
.RI "char * \fBdest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB158\fP of file \fBxpncp\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t arguments::buffer_size"

.PP
Definition at line \fB160\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.
.SS "int arguments::debug"

.PP
Definition at line \fB165\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.
.SS "char * arguments::dest"

.PP
Definition at line \fB167\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.
.SS "int arguments::do_stat"

.PP
Definition at line \fB162\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.
.SS "int arguments::silent"

.PP
Definition at line \fB163\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.
.SS "char * arguments::source"

.PP
Definition at line \fB166\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.
.SS "struct stat arguments::st"

.PP
Definition at line \fB161\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.
.SS "int arguments::very_silent"

.PP
Definition at line \fB164\fP of file \fBxpncp\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBparse_opt()\fP, \fBparse_opt()\fP, and \fBparse_opt()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
