.TH "buffer_st" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buffer_st
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ssize_t \fBbuffer_length\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB108\fP of file \fBxpncp_m\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "char * buffer_st::buffer"

.PP
Definition at line \fB111\fP of file \fBxpncp_m\&.c\fP\&.
.PP
Referenced by \fBwrite_func()\fP\&.
.SS "ssize_t buffer_st::buffer_length"

.PP
Definition at line \fB110\fP of file \fBxpncp_m\&.c\fP\&.
.PP
Referenced by \fBwrite_func()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
