.TH "commit3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commit3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfhandle3\fP \fBfile\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB896\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint32\fP commit3args::count"

.PP
Definition at line \fB900\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_commit3args()\fP\&.
.SS "\fBfhandle3\fP commit3args::file"

.PP
Definition at line \fB898\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_commit3args()\fP\&.
.SS "\fBuint64\fP commit3args::offset"

.PP
Definition at line \fB899\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_commit3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
