.TH "commit3resok" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commit3resok
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBwcc_data\fP \fBfile_wcc\fP"
.br
.ti -1c
.RI "\fBwriteverf3\fP \fBverf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB904\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBwcc_data\fP commit3resok::file_wcc"

.PP
Definition at line \fB906\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_commit3resok()\fP\&.
.SS "\fBwriteverf3\fP commit3resok::verf"

.PP
Definition at line \fB907\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_commit3resok()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
