.TH "cp-local2xpn.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cp-local2xpn.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/param\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/file\&.h>\fP
.br
\fC#include <sys/fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/errno\&.h>\fP
.br
\fC#include 'xpn\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKB\fP   1024"
.br
.ti -1c
.RI "#define \fBMB\fP   (\fBKB\fP * \fBKB\fP)"
.br
.ti -1c
.RI "#define \fBDATAM\fP   (256 * \fBKB\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATAM   (256 * \fBKB\fP)"

.PP
Definition at line \fB39\fP of file \fBcp\-local2xpn\&.c\fP\&.
.SS "#define KB   1024"

.PP
Definition at line \fB33\fP of file \fBcp\-local2xpn\&.c\fP\&.
.SS "#define MB   (\fBKB\fP * \fBKB\fP)"

.PP
Definition at line \fB37\fP of file \fBcp\-local2xpn\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB41\fP of file \fBcp\-local2xpn\&.c\fP\&.
.PP
References \fBclose()\fP, \fBDATAM\fP, \fBexit()\fP, \fBO_CREAT\fP, \fBO_RDWR\fP, \fBO_TRUNC\fP, \fBopen()\fP, \fBread()\fP, \fBsum\fP, \fBxpn_close()\fP, \fBxpn_destroy()\fP, \fBxpn_init()\fP, \fBxpn_open()\fP, and \fBxpn_write()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
