.TH "createhow3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
createhow3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcreatemode3\fP \fBmode\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBsattr3\fP \fBobj_attributes\fP"
.br
.ti -1c
.RI "   \fBcreateverf3\fP \fBverf\fP"
.br
.ti -1c
.RI "} \fBcreatehow3_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB615\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "union  { \&.\&.\&. }  createhow3::createhow3_u"

.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_createhow3()\fP\&.
.SS "\fBcreatemode3\fP createhow3::mode"

.PP
Definition at line \fB617\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_createhow3()\fP\&.
.SS "\fBsattr3\fP createhow3::obj_attributes"

.PP
Definition at line \fB620\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_createhow3()\fP\&.
.SS "\fBcreateverf3\fP createhow3::verf"

.PP
Definition at line \fB621\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_createhow3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
