.TH "create3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
create3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdiropargs3\fP \fBwhere\fP"
.br
.ti -1c
.RI "\fBcreatehow3\fP \fBhow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB626\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBcreatehow3\fP create3args::how"

.PP
Definition at line \fB629\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_create3args()\fP\&.
.SS "\fBdiropargs3\fP create3args::where"

.PP
Definition at line \fB628\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_create3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
