.TH "devicedata3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
devicedata3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsattr3\fP \fBdev_attributes\fP"
.br
.ti -1c
.RI "\fBspecdata3\fP \fBspec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB654\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBsattr3\fP devicedata3::dev_attributes"

.PP
Definition at line \fB656\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_devicedata3()\fP\&.
.SS "\fBspecdata3\fP devicedata3::spec"

.PP
Definition at line \fB657\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_devicedata3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
