.TH "diropargs3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diropargs3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfhandle3\fP \fBdir\fP"
.br
.ti -1c
.RI "\fBfilename3\fP \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB401\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBfhandle3\fP diropargs3::dir"

.PP
Definition at line \fB403\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, \fBnfs3_lookup()\fP, \fBnfs3_remove()\fP, and \fBxdr_diropargs3()\fP\&.
.SS "\fBfilename3\fP diropargs3::name"

.PP
Definition at line \fB404\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, \fBnfs3_lookup()\fP, \fBnfs3_remove()\fP, and \fBxdr_diropargs3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
