.TH "diropres3ok" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diropres3ok
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpost_op_fh3\fP \fBobj\fP"
.br
.ti -1c
.RI "\fBpost_op_attr\fP \fBobj_attributes\fP"
.br
.ti -1c
.RI "\fBwcc_data\fP \fBdir_wcc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB408\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBwcc_data\fP diropres3ok::dir_wcc"

.PP
Definition at line \fB412\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_diropres3ok()\fP\&.
.SS "\fBpost_op_fh3\fP diropres3ok::obj"

.PP
Definition at line \fB410\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_diropres3ok()\fP\&.
.SS "\fBpost_op_attr\fP diropres3ok::obj_attributes"

.PP
Definition at line \fB411\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_diropres3ok()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
