.TH "diropres3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diropres3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfsstat3\fP \fBstatus\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBdiropres3ok\fP \fBresok\fP"
.br
.ti -1c
.RI "   \fBwcc_data\fP \fBresfail\fP"
.br
.ti -1c
.RI "} \fBdiropres3_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB416\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "union  { \&.\&.\&. }  diropres3::diropres3_u"

.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_diropres3()\fP\&.
.SS "\fBwcc_data\fP diropres3::resfail"

.PP
Definition at line \fB422\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_diropres3()\fP\&.
.SS "\fBdiropres3ok\fP diropres3::resok"

.PP
Definition at line \fB421\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_diropres3()\fP\&.
.SS "\fBnfsstat3\fP diropres3::status"

.PP
Definition at line \fB418\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, and \fBxdr_diropres3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
