.TH "dtable_t" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtable_t \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dtable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_pointerDArray\fP \fBdtable\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "long \fBneltos\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "long \fBfree_list\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB76\fP of file \fBdtable\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "dtable_t::dtable"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB78\fP of file \fBdtable\&.h\fP\&.
.PP
Referenced by \fBdtable_delete()\fP, \fBdtable_get()\fP, and \fBdtable_insert()\fP\&.
.SS "dtable_t::free_list"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB80\fP of file \fBdtable\&.h\fP\&.
.PP
Referenced by \fBdtable_delete()\fP, and \fBdtable_insert()\fP\&.
.SS "dtable_t::neltos"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB79\fP of file \fBdtable\&.h\fP\&.
.PP
Referenced by \fBdtable_delete()\fP, \fBdtable_get()\fP, and \fBdtable_insert()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
