.TH "dtable.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtable.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'base/dtable\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdtable_insert\fP (\fBdtable_t\fP *dt, void *dt_info)"
.br
.RI "Insert element\&. "
.ti -1c
.RI "int \fBdtable_delete\fP (\fBdtable_t\fP *dt, int fd)"
.br
.RI "Remove element\&. "
.ti -1c
.RI "void * \fBdtable_get\fP (\fBdtable_t\fP *dt, int fd)"
.br
.RI "Get element\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBdtable\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int dtable_delete (\fBdtable_t\fP * dt, int fd)"

.PP
Remove element\&. Remove the element at 'fd' position into 'dt' dynamic table\&.
.PP
\fBParameters\fP
.RS 4
\fIdt\fP a dynamic table\&. 
.br
\fIfd\fP the element descriptor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true (1) if element is removed and error (-1) if a problem is found\&. 
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBdtable\&.c\fP\&.
.PP
References \fBDARRAY_GetNFromDarray\fP, \fBdtable_t::dtable\fP, \fBdtable_t::free_list\fP, \fBdtelto_t::myself\fP, \fBdtable_t::neltos\fP, and \fBdtelto_t::next_free\fP\&.
.SS "void * dtable_get (\fBdtable_t\fP * dt, int fd)"

.PP
Get element\&. Get the element at 'fd' position into 'dt' dynamic table\&.
.PP
\fBParameters\fP
.RS 4
\fIdt\fP a dynamic table\&. 
.br
\fIfd\fP the element descriptor\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB112\fP of file \fBdtable\&.c\fP\&.
.PP
References \fBDARRAY_GetNFromDarray\fP, \fBdtelto_t::dt_info\fP, \fBdtable_t::dtable\fP, and \fBdtable_t::neltos\fP\&.
.SS "int dtable_insert (\fBdtable_t\fP * dt, void * dt_info)"

.PP
Insert element\&. Insert the element 'dt_info' into 'dt' dynamic table\&.
.PP
\fBParameters\fP
.RS 4
\fIdt\fP a dynamic table\&. 
.br
\fIdt_info\fP the element to be inserted\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true (1) if element is inserted and error (-1) if a problem is found\&. 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBdtable\&.c\fP\&.
.PP
References \fBDARRAY_GetNFromDarray\fP, \fBDARRAY_InsEndDarray()\fP, \fBdtelto_t::dt_info\fP, \fBdtable_t::dtable\fP, \fBdtable_t::free_list\fP, \fBdtelto_t::myself\fP, \fBdtable_t::neltos\fP, and \fBdtelto_t::next_free\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
