.TH "dtelto_t" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtelto_t \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dtable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdt_info\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBnext_free\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBmyself\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB59\fP of file \fBdtable\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "dtelto_t::dt_info"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB61\fP of file \fBdtable\&.h\fP\&.
.PP
Referenced by \fBdtable_get()\fP, and \fBdtable_insert()\fP\&.
.SS "dtelto_t::myself"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB63\fP of file \fBdtable\&.h\fP\&.
.PP
Referenced by \fBdtable_delete()\fP, and \fBdtable_insert()\fP\&.
.SS "dtelto_t::next_free"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB62\fP of file \fBdtable\&.h\fP\&.
.PP
Referenced by \fBdtable_delete()\fP, and \fBdtable_insert()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
