.TH "entry3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entry3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint64\fP \fBfileid\fP"
.br
.ti -1c
.RI "\fBfilename3\fP \fBname\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBcookie\fP"
.br
.ti -1c
.RI "struct \fBentry3\fP * \fBnextentry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB736\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint64\fP entry3::cookie"

.PP
Definition at line \fB740\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_entry3()\fP\&.
.SS "\fBuint64\fP entry3::fileid"

.PP
Definition at line \fB738\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_entry3()\fP\&.
.SS "\fBfilename3\fP entry3::name"

.PP
Definition at line \fB739\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_entry3()\fP\&.
.SS "struct \fBentry3\fP* entry3::nextentry"

.PP
Definition at line \fB741\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_entry3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
