.TH "exportnode3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exportnode3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfs3_dirpath\fP \fBex_dir\fP"
.br
.ti -1c
.RI "\fBgroups3\fP \fBex_groups3\fP"
.br
.ti -1c
.RI "\fBexports3\fP \fBex_next\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB99\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBnfs3_dirpath\fP exportnode3::ex_dir"

.PP
Definition at line \fB101\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_exportnode3()\fP\&.
.SS "\fBgroups3\fP exportnode3::ex_groups3"

.PP
Definition at line \fB102\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_exportnode3()\fP\&.
.SS "\fBexports3\fP exportnode3::ex_next"

.PP
Definition at line \fB103\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_exportnode3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
