.TH "fhandle3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fhandle3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_int \fBfhandle3_len\fP"
.br
.ti -1c
.RI "char * \fBfhandle3_val\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "u_int fhandle3::fhandle3_len"

.PP
Definition at line \fB34\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, \fBnfs3_lookup()\fP, \fBnfs3_mount()\fP, \fBnfs3_read()\fP, \fBnfs3_remove()\fP, \fBnfs3_write()\fP, and \fBxdr_fhandle3()\fP\&.
.SS "char* fhandle3::fhandle3_val"

.PP
Definition at line \fB35\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, \fBnfs3_lookup()\fP, \fBnfs3_mount()\fP, \fBnfs3_read()\fP, \fBnfs3_remove()\fP, \fBnfs3_write()\fP, \fBprintfh3()\fP, and \fBxdr_fhandle3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
