.TH "filesystem.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filesystem.c
.SH SYNOPSIS
.br
.PP
\fC#include 'filesystem\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBaux_clear_dirs\fP (char *path)"
.br
.ti -1c
.RI "int \fBaux_get_dirs\fP (char *path, int n, char *s)"
.br
.ti -1c
.RI "void * \fBfilesystem_async_close\fP (void *arg)"
.br
.ti -1c
.RI "int \fBfilesystem_creat\fP (char *pathname, mode_t mode)"
.br
.RI "Create a file\&. "
.ti -1c
.RI "int \fBfilesystem_open\fP (char *pathname, int flags)"
.br
.RI "Open a file\&. "
.ti -1c
.RI "int \fBfilesystem_open2\fP (char *pathname, int flags, mode_t mode)"
.br
.RI "Open a file\&. "
.ti -1c
.RI "int \fBfilesystem_close\fP (int fd)"
.br
.RI "Close a file\&. "
.ti -1c
.RI "long \fBfilesystem_read\fP (int read_fd2, void *buffer, int buffer_size)"
.br
.RI "Read a file\&. "
.ti -1c
.RI "long \fBfilesystem_write\fP (int write_fd2, void *buffer, int num_bytes_to_write)"
.br
.RI "Write a file\&. "
.ti -1c
.RI "int \fBfilesystem_rename\fP (char *old_pathname, char *new_pathname)"
.br
.RI "Rename a file\&. "
.ti -1c
.RI "int \fBfilesystem_mkpath\fP (char *pathname)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBfilesystem_mkdir\fP (char *pathname, mode_t mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBfilesystem_rmdir\fP (char *pathname)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "DIR * \fBfilesystem_opendir\fP (char *pathname)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "struct dirent * \fBfilesystem_readdir\fP (DIR *dirp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBfilesystem_closedir\fP (DIR *dirp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "off_t \fBfilesystem_lseek\fP (int fd, off_t offset, int whence)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBfilesystem_unlink\fP (char *pathname)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBfilesystem_stat\fP (char *pathname, struct stat *sinfo)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int aux_clear_dirs (char * path)"

.PP
Definition at line \fB36\fP of file \fBfilesystem\&.c\fP\&.
.PP
Referenced by \fBaux_get_dirs()\fP\&.
.SS "int aux_get_dirs (char * path, int n, char * s)"

.PP
Definition at line \fB70\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBaux_clear_dirs()\fP, and \fBPATH_MAX\fP\&.
.PP
Referenced by \fBfilesystem_mkpath()\fP\&.
.SS "void * filesystem_async_close (void * arg)"

.PP
Definition at line \fB132\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBdebug_warning\fP, and \fBreal_posix_close\fP\&.
.PP
Referenced by \fBfilesystem_close()\fP\&.
.SS "int filesystem_close (int fd)"

.PP
Close a file\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB238\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, \fBfilesystem_async_close()\fP, and \fBreal_posix_close\fP\&.
.PP
Referenced by \fBmpi_server_op_close_ws()\fP, \fBmpi_server_op_creat_wos()\fP, \fBmpi_server_op_flush()\fP, \fBmpi_server_op_open_wos()\fP, \fBmpi_server_op_preload()\fP, \fBmpi_server_op_read_wos()\fP, \fBmpi_server_op_write_wos()\fP, \fBtcp_server_op_close_ws()\fP, \fBtcp_server_op_creat_wos()\fP, \fBtcp_server_op_flush()\fP, \fBtcp_server_op_open_wos()\fP, \fBtcp_server_op_preload()\fP, \fBtcp_server_op_read_wos()\fP, and \fBtcp_server_op_write_wos()\fP\&.
.SS "int filesystem_closedir (DIR * dirp)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirp\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB510\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_closedir\fP\&.
.PP
Referenced by \fBmpi_server_op_closedir()\fP, and \fBtcp_server_op_closedir()\fP\&.
.SS "int filesystem_creat (char * pathname, mode_t mode)"

.PP
Create a file\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB156\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_creat\fP\&.
.PP
Referenced by \fBmpi_server_op_creat_wos()\fP, \fBmpi_server_op_creat_ws()\fP, \fBmpi_server_op_preload()\fP, \fBtcp_server_op_creat_wos()\fP, \fBtcp_server_op_creat_ws()\fP, and \fBtcp_server_op_preload()\fP\&.
.SS "off_t filesystem_lseek (int fd, off_t offset, int whence)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.br
\fIwhence\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB536\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_lseek\fP\&.
.PP
Referenced by \fBmpi_server_op_flush()\fP, \fBmpi_server_op_preload()\fP, \fBmpi_server_op_read_wos()\fP, \fBmpi_server_op_read_ws()\fP, \fBmpi_server_op_write_wos()\fP, \fBmpi_server_op_write_ws()\fP, \fBtcp_server_op_flush()\fP, \fBtcp_server_op_preload()\fP, \fBtcp_server_op_read_wos()\fP, \fBtcp_server_op_read_ws()\fP, \fBtcp_server_op_write_wos()\fP, and \fBtcp_server_op_write_ws()\fP\&.
.SS "int filesystem_mkdir (char * pathname, mode_t mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB406\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_mkdir\fP\&.
.PP
Referenced by \fBmpi_server_op_mkdir()\fP, and \fBtcp_server_op_mkdir()\fP\&.
.SS "int filesystem_mkpath (char * pathname)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB383\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBaux_get_dirs()\fP, \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, \fBPATH_MAX\fP, and \fBreal_posix_mkdir\fP\&.
.PP
Referenced by \fBmpi_server_op_creat_wos()\fP, \fBmpi_server_op_creat_ws()\fP, \fBtcp_server_op_creat_wos()\fP, and \fBtcp_server_op_creat_ws()\fP\&.
.SS "int filesystem_open (char * pathname, int flags)"

.PP
Open a file\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB186\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_open\fP\&.
.PP
Referenced by \fBmpi_server_op_flush()\fP, \fBmpi_server_op_open_wos()\fP, \fBmpi_server_op_open_ws()\fP, \fBmpi_server_op_preload()\fP, \fBmpi_server_op_read_wos()\fP, \fBmpi_server_op_write_wos()\fP, \fBtcp_server_op_flush()\fP, \fBtcp_server_op_open_wos()\fP, \fBtcp_server_op_open_ws()\fP, \fBtcp_server_op_preload()\fP, \fBtcp_server_op_read_wos()\fP, and \fBtcp_server_op_write_wos()\fP\&.
.SS "int filesystem_open2 (char * pathname, int flags, mode_t mode)"

.PP
Open a file\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB212\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_open2\fP\&.
.SS "DIR * filesystem_opendir (char * name)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB458\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_opendir\fP\&.
.PP
Referenced by \fBmpi_server_op_opendir()\fP, and \fBtcp_server_op_opendir()\fP\&.
.SS "long filesystem_read (int read_fd2, void * buffer, int buffer_size)"

.PP
Read a file\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIread_fd2\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fIbuffer_size\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB282\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBdebug_error\fP, \fBdebug_warning\fP, and \fBreal_posix_read\fP\&.
.PP
Referenced by \fBmpi_server_op_flush()\fP, \fBmpi_server_op_preload()\fP, \fBmpi_server_op_read_wos()\fP, \fBmpi_server_op_read_ws()\fP, \fBtcp_server_op_flush()\fP, \fBtcp_server_op_preload()\fP, \fBtcp_server_op_read_wos()\fP, and \fBtcp_server_op_read_ws()\fP\&.
.SS "struct dirent * filesystem_readdir (DIR * dirp)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirp\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB484\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_readdir\fP\&.
.PP
Referenced by \fBmpi_server_op_readdir()\fP, and \fBtcp_server_op_readdir()\fP\&.
.SS "int filesystem_rename (char * old_pathname, char * new_pathname)"

.PP
Rename a file\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIold_pathname\fP 'TODO'\&. 
.br
\fInew_pathname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB353\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_rename\fP\&.
.PP
Referenced by \fBmpi_server_op_rename()\fP, and \fBtcp_server_op_rename()\fP\&.
.SS "int filesystem_rmdir (char * pathname)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB432\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_rmdir\fP\&.
.PP
Referenced by \fBmpi_server_op_rmdir()\fP, \fBmpi_server_op_rmdir_async()\fP, and \fBtcp_server_op_rmdir()\fP\&.
.SS "int filesystem_stat (char * pathname, struct stat * sinfo)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.br
\fIsinfo\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB588\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_stat\fP\&.
.PP
Referenced by \fBmpi_server_op_getattr()\fP, and \fBtcp_server_op_getattr()\fP\&.
.SS "int filesystem_unlink (char * pathname)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpathname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB562\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_warning\fP, and \fBreal_posix_unlink\fP\&.
.PP
Referenced by \fBmpi_server_op_rm()\fP, \fBmpi_server_op_rm_async()\fP, and \fBtcp_server_op_rm()\fP\&.
.SS "long filesystem_write (int write_fd2, void * buffer, int num_bytes_to_write)"

.PP
Write a file\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIwrite_fd2\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fInum_bytes_to_write\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB321\fP of file \fBfilesystem\&.c\fP\&.
.PP
References \fBdebug_error\fP, \fBdebug_warning\fP, and \fBreal_posix_write\fP\&.
.PP
Referenced by \fBmpi_server_op_flush()\fP, \fBmpi_server_op_preload()\fP, \fBmpi_server_op_write_wos()\fP, \fBmpi_server_op_write_ws()\fP, \fBtcp_server_op_flush()\fP, \fBtcp_server_op_preload()\fP, \fBtcp_server_op_write_wos()\fP, and \fBtcp_server_op_write_ws()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
