.TH "fsinfo3res" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsinfo3res
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfsstat3\fP \fBstatus\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBfsinfo3resok\fP \fBresok\fP"
.br
.ti -1c
.RI "   \fBpost_op_attr\fP \fBresfail\fP"
.br
.ti -1c
.RI "} \fBfsinfo3res_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB862\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "union  { \&.\&.\&. }  fsinfo3res::fsinfo3res_u"

.PP
Referenced by \fBxdr_fsinfo3res()\fP\&.
.SS "\fBpost_op_attr\fP fsinfo3res::resfail"

.PP
Definition at line \fB868\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_fsinfo3res()\fP\&.
.SS "\fBfsinfo3resok\fP fsinfo3res::resok"

.PP
Definition at line \fB867\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_fsinfo3res()\fP\&.
.SS "\fBnfsstat3\fP fsinfo3res::status"

.PP
Definition at line \fB864\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_fsinfo3res()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
