.TH "generic_fd" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generic_fd \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn_bypass\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBreal_fd\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBis_file\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB118\fP of file \fBxpn_bypass\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "generic_fd::is_file"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB122\fP of file \fBxpn_bypass\&.h\fP\&.
.PP
Referenced by \fBadd_xpn_file_to_fdstable()\fP, \fBfdsdirtable_put()\fP, \fBfdstable_realloc()\fP, \fBfdstable_remove()\fP, \fBread()\fP, and \fBwrite()\fP\&.
.SS "generic_fd::real_fd"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB121\fP of file \fBxpn_bypass\&.h\fP\&.
.PP
Referenced by \fB__fxstat()\fP, \fB__fxstat64()\fP, \fBadd_xpn_file_to_fdstable()\fP, \fBclose()\fP, \fBdup()\fP, \fBdup2()\fP, \fBfdsdirtable_getfd()\fP, \fBfdsdirtable_put()\fP, \fBfdstable_get()\fP, \fBfdstable_realloc()\fP, \fBfdstable_remove()\fP, \fBftruncate()\fP, \fBlseek()\fP, \fBlseek64()\fP, \fBread()\fP, and \fBwrite()\fP\&.
.SS "generic_fd::type"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB120\fP of file \fBxpn_bypass\&.h\fP\&.
.PP
Referenced by \fB__fxstat()\fP, \fB__fxstat64()\fP, \fBadd_xpn_file_to_fdstable()\fP, \fBclose()\fP, \fBdup()\fP, \fBdup2()\fP, \fBfchmod()\fP, \fBfcntl()\fP, \fBfdsdirtable_put()\fP, \fBfdstable_get()\fP, \fBfdstable_put()\fP, \fBfdstable_realloc()\fP, \fBfdstable_remove()\fP, \fBfsync()\fP, \fBftruncate()\fP, \fBlseek()\fP, \fBlseek64()\fP, \fBread()\fP, and \fBwrite()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
