.TH "getattr3res" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getattr3res
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfsstat3\fP \fBstatus\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBfattr3\fP \fBattributes\fP"
.br
.ti -1c
.RI "} \fBgetattr3res_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB437\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBfattr3\fP getattr3res::attributes"

.PP
Definition at line \fB442\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_getattr()\fP, and \fBxdr_getattr3res()\fP\&.
.SS "union  { \&.\&.\&. }  getattr3res::getattr3res_u"

.PP
Referenced by \fBnfs3_getattr()\fP, and \fBxdr_getattr3res()\fP\&.
.SS "\fBnfsstat3\fP getattr3res::status"

.PP
Definition at line \fB439\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_getattr()\fP, and \fBxdr_getattr3res()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
