.TH "groupnode3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
groupnode3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfs3_name\fP \fBgr_name\fP"
.br
.ti -1c
.RI "\fBgroups3\fP \fBgr_next\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB90\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBnfs3_name\fP groupnode3::gr_name"

.PP
Definition at line \fB92\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_groupnode3()\fP\&.
.SS "\fBgroups3\fP groupnode3::gr_next"

.PP
Definition at line \fB93\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_groupnode3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
