.TH "config.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_DIRENT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FCNTL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETHOSTNAME\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETTIMEOFDAY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBDL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBPTHREAD\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NETINET_IN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NETINET_TCP_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PTHREAD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_RPC_CLNT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_RPC_RPC_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_RPC_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SELECT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SOCKET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRDUP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRERROR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_IOCTL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_PARAM_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TIME_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_WAIT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'expand'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   'fgcarbal@inf\&.uc3m\&.es'"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   'Expand'"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   'Expand 2\&.0'"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   'expand'"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   '2\&.0'"
.br
.ti -1c
.RI "#define \fBSIZEOF_CHAR_P\fP   8"
.br
.ti -1c
.RI "#define \fBSIZEOF_PTRDIFF_T\fP   8"
.br
.ti -1c
.RI "#define \fBSIZEOF_SIZE_T\fP   8"
.br
.ti -1c
.RI "#define \fBSIZEOF_UNSIGNED\fP   4"
.br
.ti -1c
.RI "#define \fBSIZEOF_UNSIGNED_LONG\fP   8"
.br
.ti -1c
.RI "#define \fBSIZEOF_UNSIGNED_SHORT\fP   2"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '2\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE_DIRENT_H   1"

.PP
Definition at line \fB5\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_FCNTL_H   1"

.PP
Definition at line \fB11\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_GETHOSTNAME   1"

.PP
Definition at line \fB14\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_GETTIMEOFDAY   1"

.PP
Definition at line \fB17\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_INTTYPES_H   1"

.PP
Definition at line \fB23\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_LIBDL   1"

.PP
Definition at line \fB26\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_LIBPTHREAD   1"

.PP
Definition at line \fB35\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_MEMCMP   1"

.PP
Definition at line \fB38\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_MEMCPY   1"

.PP
Definition at line \fB41\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_MEMMOVE   1"

.PP
Definition at line \fB44\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_MEMORY_H   1"

.PP
Definition at line \fB47\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_MEMSET   1"

.PP
Definition at line \fB50\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_NETINET_IN_H   1"

.PP
Definition at line \fB59\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_NETINET_TCP_H   1"

.PP
Definition at line \fB62\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_PTHREAD_H   1"

.PP
Definition at line \fB65\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_RPC_CLNT_H   1"

.PP
Definition at line \fB68\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_RPC_RPC_H   1"

.PP
Definition at line \fB71\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_RPC_TYPES_H   1"

.PP
Definition at line \fB74\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SELECT   1"

.PP
Definition at line \fB77\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SOCKET   1"

.PP
Definition at line \fB80\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_STDINT_H   1"

.PP
Definition at line \fB83\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_STDLIB_H   1"

.PP
Definition at line \fB86\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_STRDUP   1"

.PP
Definition at line \fB89\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_STRERROR   1"

.PP
Definition at line \fB92\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_STRING_H   1"

.PP
Definition at line \fB98\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_STRINGS_H   1"

.PP
Definition at line \fB95\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SYS_IOCTL_H   1"

.PP
Definition at line \fB101\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SYS_PARAM_H   1"

.PP
Definition at line \fB104\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SYS_STAT_H   1"

.PP
Definition at line \fB107\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SYS_TIME_H   1"

.PP
Definition at line \fB110\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SYS_TYPES_H   1"

.PP
Definition at line \fB113\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_SYS_WAIT_H   1"

.PP
Definition at line \fB116\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_UNISTD_H   1"

.PP
Definition at line \fB119\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define HAVE_VPRINTF   1"

.PP
Definition at line \fB122\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define PACKAGE   'expand'"

.PP
Definition at line \fB128\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define PACKAGE_BUGREPORT   'fgcarbal@inf\&.uc3m\&.es'"

.PP
Definition at line \fB131\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define PACKAGE_NAME   'Expand'"

.PP
Definition at line \fB134\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define PACKAGE_STRING   'Expand 2\&.0'"

.PP
Definition at line \fB137\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define PACKAGE_TARNAME   'expand'"

.PP
Definition at line \fB140\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define PACKAGE_URL   ''"

.PP
Definition at line \fB143\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define PACKAGE_VERSION   '2\&.0'"

.PP
Definition at line \fB146\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define SIZEOF_CHAR_P   8"

.PP
Definition at line \fB149\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define SIZEOF_PTRDIFF_T   8"

.PP
Definition at line \fB152\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define SIZEOF_SIZE_T   8"

.PP
Definition at line \fB155\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define SIZEOF_UNSIGNED   4"

.PP
Definition at line \fB158\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define SIZEOF_UNSIGNED_LONG   8"

.PP
Definition at line \fB161\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define SIZEOF_UNSIGNED_SHORT   2"

.PP
Definition at line \fB164\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define STDC_HEADERS   1"

.PP
Definition at line \fB167\fP of file \fBinclude/config\&.h\fP\&.
.SS "#define VERSION   '2\&.0'"

.PP
Definition at line \fB170\fP of file \fBinclude/config\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
