.TH "link3wcc" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
link3wcc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpost_op_attr\fP \fBfile_attributes\fP"
.br
.ti -1c
.RI "\fBwcc_data\fP \fBlinkdir_wcc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB710\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBpost_op_attr\fP link3wcc::file_attributes"

.PP
Definition at line \fB712\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_link3wcc()\fP\&.
.SS "\fBwcc_data\fP link3wcc::linkdir_wcc"

.PP
Definition at line \fB713\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_link3wcc()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
