.TH "link3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
link3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfhandle3\fP \fBfile\fP"
.br
.ti -1c
.RI "\fBdiropargs3\fP \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB703\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBfhandle3\fP link3args::file"

.PP
Definition at line \fB705\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_link3args()\fP\&.
.SS "\fBdiropargs3\fP link3args::link"

.PP
Definition at line \fB706\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_link3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
