.TH "lookup3resok" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lookup3resok
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfhandle3\fP \fBobject\fP"
.br
.ti -1c
.RI "\fBpost_op_attr\fP \fBobj_attributes\fP"
.br
.ti -1c
.RI "\fBpost_op_attr\fP \fBdir_attributes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB465\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBpost_op_attr\fP lookup3resok::dir_attributes"

.PP
Definition at line \fB469\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_lookup3resok()\fP\&.
.SS "\fBpost_op_attr\fP lookup3resok::obj_attributes"

.PP
Definition at line \fB468\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_lookup()\fP, and \fBxdr_lookup3resok()\fP\&.
.SS "\fBfhandle3\fP lookup3resok::object"

.PP
Definition at line \fB467\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_lookup()\fP, and \fBxdr_lookup3resok()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
