.TH "lookup3res" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lookup3res
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfsstat3\fP \fBstatus\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBlookup3resok\fP \fBresok\fP"
.br
.ti -1c
.RI "   \fBpost_op_attr\fP \fBresfail\fP"
.br
.ti -1c
.RI "} \fBlookup3res_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB473\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "union  { \&.\&.\&. }  lookup3res::lookup3res_u"

.PP
Referenced by \fBnfs3_lookup()\fP, and \fBxdr_lookup3res()\fP\&.
.SS "\fBpost_op_attr\fP lookup3res::resfail"

.PP
Definition at line \fB479\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_lookup3res()\fP\&.
.SS "\fBlookup3resok\fP lookup3res::resok"

.PP
Definition at line \fB478\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_lookup()\fP, and \fBxdr_lookup3res()\fP\&.
.SS "\fBnfsstat3\fP lookup3res::status"

.PP
Definition at line \fB475\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_lookup()\fP, and \fBxdr_lookup3res()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
