.TH "md_src_2tcp__server_2README" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_2tcp__server_2README \- tcp_server for XPN 
.PP
 
.SH "Pre-requisites:"
.PP
.IP "\(bu" 2
In order to use mosquitto on tcp_server module, you have to install the following packages:
.PP
.PP
.PP
.nf
sudo apt\-get install mosquitto mosquitto\-clients mosquitto\-dev libmosquitto\-dev
.fi
.PP
.PP
.IP "\(bu" 2
Create the mosquitto config file:
.PP
.PP
.PP
.nf
touch /etc/mosquitto/conf\&.d/mosquitto\&.conf
.fi
.PP
.PP
.IP "\(bu" 2
Insert the following parameters:
.PP
.PP
.PP
.nf
port 2555
max_queued_messages 0
memory_limit 0
.fi
.PP
.PP
.IP "\(bu" 2
Then, we need to start the Mosquitto MQTT service:
.PP
.PP
.PP
.nf
sudo systemctl restart mosquitto
.fi
.PP
.SH "Compile:"
.PP
.IP "\(bu" 2
To compile the tcp_server just execute: 
.PP
.nf
make clean
make

.fi
.PP

.PP
.SH "Execution:"
.PP
.IP "\(bu" 2
In order to start one tcp_server at host 'localhost' and port '7555', you can use: 
.PP
.nf
echo localhost > machinefile
\&./scripts/execute/tcp_server\&.sh /tmp/xpn machinefile 7555

.fi
.PP

.PP
.SS "Individual tcp_server"
.PP
.nf
/work/xpn/src/tcp_server/xpn_tcp_server \\
        \-ns /export/tcp_server\&.dns \\
        \-p 3456
.fi
.PP
.SS "Several tcp_server with MPI"
.PP
.nf
mpirun \-np 2 \\
        \-machinefile machinefile \\
        /work/xpn/src/tcp_server/xpn_tcp_server \\
        \-ns /export/tcp_server\&.dns \\
        \-p 3456
.fi
.PP
.SS "Using docker u20\&.sh"
.PP
.nf
\&./u20\&.sh start 4
\&./u20\&.sh network | grep \-v "Show" > machinefile
\&./u20\&.sh mpirun 2 "/work/xpn/src/tcp_server/xpn_tcp_server \-ns /export/tcp_server\&.dns \-p 3456" &
\&./u20\&.sh mpirun 2 "/work/xpn/test/integrity/xpn/run\&.sh"
\&./u20\&.sh stop
.fi
.PP
 
