.TH "mkdir3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mkdir3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdiropargs3\fP \fBwhere\fP"
.br
.ti -1c
.RI "\fBsattr3\fP \fBattributes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB633\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBsattr3\fP mkdir3args::attributes"

.PP
Definition at line \fB636\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mkdir3args()\fP\&.
.SS "\fBdiropargs3\fP mkdir3args::where"

.PP
Definition at line \fB635\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mkdir3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
