.TH "mknod3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mknod3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdiropargs3\fP \fBwhere\fP"
.br
.ti -1c
.RI "\fBmknoddata3\fP \fBwhat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB672\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBmknoddata3\fP mknod3args::what"

.PP
Definition at line \fB675\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mknod3args()\fP\&.
.SS "\fBdiropargs3\fP mknod3args::where"

.PP
Definition at line \fB674\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mknod3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
