.TH "mknoddata3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mknoddata3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBftype3\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBdevicedata3\fP \fBdevice\fP"
.br
.ti -1c
.RI "   \fBsattr3\fP \fBpipe_attributes\fP"
.br
.ti -1c
.RI "} \fBmknoddata3_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB661\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBdevicedata3\fP mknoddata3::device"

.PP
Definition at line \fB666\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mknoddata3()\fP\&.
.SS "union  { \&.\&.\&. }  mknoddata3::mknoddata3_u"

.PP
Referenced by \fBxdr_mknoddata3()\fP\&.
.SS "\fBsattr3\fP mknoddata3::pipe_attributes"

.PP
Definition at line \fB667\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mknoddata3()\fP\&.
.SS "\fBftype3\fP mknoddata3::type"

.PP
Definition at line \fB663\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mknoddata3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
