.TH "mountbody3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mountbody3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfs3_name\fP \fBml_hostname\fP"
.br
.ti -1c
.RI "\fBnfs3_dirpath\fP \fBml_directory\fP"
.br
.ti -1c
.RI "\fBmountlist3\fP \fBml_next\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB80\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBnfs3_dirpath\fP mountbody3::ml_directory"

.PP
Definition at line \fB83\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mountbody3()\fP\&.
.SS "\fBnfs3_name\fP mountbody3::ml_hostname"

.PP
Definition at line \fB82\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mountbody3()\fP\&.
.SS "\fBmountlist3\fP mountbody3::ml_next"

.PP
Definition at line \fB84\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_mountbody3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
