.TH "nfi_mpi_server_fhandle" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_mpi_server_fhandle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_mpi_server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "DIR * \fBdir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB68\fP of file \fBnfi_mpi_server\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "DIR* nfi_mpi_server_fhandle::dir"

.PP
Definition at line \fB72\fP of file \fBnfi_mpi_server\&.h\fP\&.
.PP
Referenced by \fBnfi_mpi_server_closedir()\fP, \fBnfi_mpi_server_create()\fP, \fBnfi_mpi_server_mkdir()\fP, \fBnfi_mpi_server_open()\fP, \fBnfi_mpi_server_opendir()\fP, \fBnfi_mpi_server_readdir()\fP, and \fBnfi_mpi_server_rmdir()\fP\&.
.SS "int nfi_mpi_server_fhandle::fd"

.PP
Definition at line \fB71\fP of file \fBnfi_mpi_server\&.h\fP\&.
.PP
Referenced by \fBnfi_mpi_server_close()\fP, \fBnfi_mpi_server_create()\fP, \fBnfi_mpi_server_mkdir()\fP, \fBnfi_mpi_server_open()\fP, \fBnfi_mpi_server_read()\fP, and \fBnfi_mpi_server_write()\fP\&.
.SS "char nfi_mpi_server_fhandle::path[\fBPATH_MAX\fP]"

.PP
Definition at line \fB70\fP of file \fBnfi_mpi_server\&.h\fP\&.
.PP
Referenced by \fBnfi_mpi_server_create()\fP, \fBnfi_mpi_server_mkdir()\fP, \fBnfi_mpi_server_open()\fP, \fBnfi_mpi_server_opendir()\fP, \fBnfi_mpi_server_read()\fP, and \fBnfi_mpi_server_write()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
