.TH "nfi_worker_io" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_worker_io \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_worker_task\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "off_t \fBoffset\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "void * \fBbuffer\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB58\fP of file \fBnfi_worker_task\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_worker_io::buffer"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB62\fP of file \fBnfi_worker_task\&.h\fP\&.
.PP
Referenced by \fBnfi_do_operation()\fP, \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBXpnReadBlocks()\fP, \fBXpnReadBlocksFinish()\fP, \fBXpnReadBlocksPolicyRAID0_AllInOne()\fP, \fBXpnReadBlocksPolicyRAID0_AllInOne_Finish()\fP, \fBXpnReadBlocksPolicyRAID1_AllInOne()\fP, \fBXpnRWBlocksPolicyBlockByBlock()\fP, \fBXpnWriteBlocks()\fP, \fBXpnWriteBlocksFinish()\fP, \fBXpnWriteBlocksPolicyRAID0_AllInOne()\fP, \fBXpnWriteBlocksPolicyRAID1_AllInOne()\fP, and \fBXpnWriteBlocksPolicyRAID1_BlockByBlock()\fP\&.
.SS "nfi_worker_io::offset"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB60\fP of file \fBnfi_worker_task\&.h\fP\&.
.PP
Referenced by \fBnfi_do_operation()\fP, \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBXpnReadBlocks()\fP, \fBXpnReadBlocksFinish()\fP, \fBXpnReadBlocksPolicyRAID0_AllInOne()\fP, \fBXpnReadBlocksPolicyRAID0_AllInOne_Finish()\fP, \fBXpnReadBlocksPolicyRAID1_AllInOne()\fP, \fBXpnRWBlocksPolicyBlockByBlock()\fP, \fBXpnWriteBlocks()\fP, \fBXpnWriteBlocksPolicyRAID0_AllInOne()\fP, \fBXpnWriteBlocksPolicyRAID1_AllInOne()\fP, and \fBXpnWriteBlocksPolicyRAID1_BlockByBlock()\fP\&.
.SS "nfi_worker_io::size"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB61\fP of file \fBnfi_worker_task\&.h\fP\&.
.PP
Referenced by \fBnfi_do_operation()\fP, \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBXpnReadBlocks()\fP, \fBXpnReadBlocksFinish()\fP, \fBXpnReadBlocksPolicyRAID0_AllInOne()\fP, \fBXpnReadBlocksPolicyRAID0_AllInOne_Finish()\fP, \fBXpnReadBlocksPolicyRAID1_AllInOne()\fP, \fBXpnRWBlocksPolicyBlockByBlock()\fP, \fBXpnWriteBlocks()\fP, \fBXpnWriteBlocksPolicyRAID0_AllInOne()\fP, \fBXpnWriteBlocksPolicyRAID1_AllInOne()\fP, and \fBXpnWriteBlocksPolicyRAID1_BlockByBlock()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
