.TH "nfi_tcp_server_fhandle" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_tcp_server_fhandle \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_tcp_server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBfd\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "DIR * \fBdir\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB105\fP of file \fBnfi_tcp_server\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_tcp_server_fhandle::dir"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB109\fP of file \fBnfi_tcp_server\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_closedir()\fP, \fBnfi_tcp_server_create()\fP, \fBnfi_tcp_server_mkdir()\fP, \fBnfi_tcp_server_open()\fP, \fBnfi_tcp_server_opendir()\fP, \fBnfi_tcp_server_readdir()\fP, and \fBnfi_tcp_server_rmdir()\fP\&.
.SS "nfi_tcp_server_fhandle::fd"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB108\fP of file \fBnfi_tcp_server\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_close()\fP, \fBnfi_tcp_server_create()\fP, \fBnfi_tcp_server_mkdir()\fP, \fBnfi_tcp_server_open()\fP, \fBnfi_tcp_server_read()\fP, and \fBnfi_tcp_server_write()\fP\&.
.SS "nfi_tcp_server_fhandle::path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB107\fP of file \fBnfi_tcp_server\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_close()\fP, \fBnfi_tcp_server_create()\fP, \fBnfi_tcp_server_mkdir()\fP, \fBnfi_tcp_server_open()\fP, \fBnfi_tcp_server_opendir()\fP, \fBnfi_tcp_server_read()\fP, and \fBnfi_tcp_server_write()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
