.TH "nfi_tcp_server_err.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_tcp_server_err.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nfi_tcp_server\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtcp_server_err\fP (int err)"
.br
.RI "'TODO'\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrno\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfi_tcp_server_err\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void tcp_server_err (int err)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIerr\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBnfi_tcp_server_err\&.c\fP\&.
.PP
References \fBerrno\fP, \fBTCP_SERVERERR_GETATTR\fP, \fBTCP_SERVERERR_MEMORY\fP, \fBTCP_SERVERERR_MNTCONNECTION\fP, \fBTCP_SERVERERR_MOUNT\fP, \fBTCP_SERVERERR_NFSCONNECTION\fP, \fBTCP_SERVERERR_PARAM\fP, and \fBTCP_SERVERERR_URL\fP\&.
.PP
Referenced by \fBnfi_tcp_server_create()\fP, \fBnfi_tcp_server_flush()\fP, \fBnfi_tcp_server_getattr()\fP, \fBnfi_tcp_server_init()\fP, \fBnfi_tcp_server_mkdir()\fP, \fBnfi_tcp_server_open()\fP, \fBnfi_tcp_server_opendir()\fP, \fBnfi_tcp_server_preload()\fP, \fBnfi_tcp_server_read()\fP, \fBnfi_tcp_server_readdir()\fP, \fBnfi_tcp_server_reconnect()\fP, \fBnfi_tcp_server_remove()\fP, \fBnfi_tcp_server_rename()\fP, \fBnfi_tcp_server_rmdir()\fP, and \fBnfi_tcp_server_write()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int errno\fC [extern]\fP"

.PP
Referenced by \fBtcp_server_err()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
