.TH "nfi_info" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_info \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_long \fBat_size\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "u_long \fBat_bsize\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "u_long \fBat_blocks\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "u_long \fBat_bfree\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "u_long \fBat_bavail\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB136\fP of file \fBnfi\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_info::at_bavail"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB142\fP of file \fBnfi\&.h\fP\&.
.SS "nfi_info::at_bfree"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB141\fP of file \fBnfi\&.h\fP\&.
.SS "nfi_info::at_blocks"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB140\fP of file \fBnfi\&.h\fP\&.
.SS "nfi_info::at_bsize"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB139\fP of file \fBnfi\&.h\fP\&.
.SS "nfi_info::at_size"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB138\fP of file \fBnfi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
