.TH "nfi_worker.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_worker.h \- Header file to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nfi_worker_task\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnfi_worker_init\fP (struct \fBnfi_worker\fP *wrk, struct \fBnfi_server\fP *serv, int thread)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBnfi_worker_thread\fP (struct \fBnfi_worker\fP *wrk, int flag)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBnfi_worker_wait\fP (struct \fBnfi_worker\fP *wrk)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBnfi_worker_end\fP (struct \fBnfi_worker\fP *wrk)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBnfi_worker_destroy\fP ()"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBnfiworker_init\fP (struct \fBnfi_server\fP *serv)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBnfiworker_launch\fP (void(*worker_function)(struct \fBst_th\fP), struct \fBnfi_worker\fP *wrk)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBnfiworker_wait\fP (struct \fBnfi_worker\fP *wrk)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void \fBnfiworker_destroy\fP (struct \fBnfi_server\fP *serv)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file to 'TODO'\&. 

Header file to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Copyright 2020-2023 Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfi_worker\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int nfi_worker_destroy ()"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
None\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB189\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBglobal_cnd\fP, and \fBglobal_mt\fP\&.
.PP
Referenced by \fBxpn_simple_destroy()\fP\&.
.SS "int nfi_worker_end (struct \fBnfi_worker\fP * wrk)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIwrk\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB175\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBnfi_worker::cnd\fP, \fBdebug_info\fP, \fBnfi_worker::mt\fP, and \fBnfi_worker::thread\fP\&.
.PP
Referenced by \fBnfi_nfs3_destroy()\fP, \fBnfi_nfs3_disconnect()\fP, \fBnfi_nfs_destroy()\fP, and \fBnfi_nfs_disconnect()\fP\&.
.SS "int nfi_worker_init (struct \fBnfi_worker\fP * wrk, struct \fBnfi_server\fP * serv, int thread)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIwrk\fP 'TODO'\&. 
.br
\fIserv\fP 'TODO'\&. 
.br
\fIthread\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB82\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBnfi_worker::cnd\fP, \fBcreate_m\fP, \fBdebug_info\fP, \fBglobal_busy\fP, \fBglobal_cnd\fP, \fBglobal_mt\fP, \fBKB\fP, \fBnfi_worker::mt\fP, \fBnfi_worker_run()\fP, \fBnfi_worker::pth\fP, \fBnfi_worker::server\fP, and \fBnfi_worker::thread\fP\&.
.PP
Referenced by \fBnfi_nfs3_init()\fP, and \fBnfi_nfs_init()\fP\&.
.SS "int nfi_worker_thread (struct \fBnfi_worker\fP * wrk, int flag)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIwrk\fP 'TODO'\&. 
.br
\fIflag\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.SS "ssize_t nfi_worker_wait (struct \fBnfi_worker\fP * wrk)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIwrk\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB143\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBnfi_worker::arg\fP, \fBnfi_worker::cnd\fP, \fBdebug_info\fP, \fBnfi_worker::mt\fP, \fBnfi_worker::ready\fP, \fBnfi_worker_args::result\fP, and \fBnfi_worker::thread\fP\&.
.SS "void nfiworker_destroy (struct \fBnfi_server\fP * serv)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIserv\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB230\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBTH_NOT\fP, \fBnfi_worker::wb\fP, \fBworkers_destroy()\fP, \fBnfi_server::wrk\fP, and \fBnfi_server::xpn_thread\fP\&.
.PP
Referenced by \fBnfi_local_destroy()\fP, \fBnfi_mpi_server_destroy()\fP, and \fBnfi_tcp_server_destroy()\fP\&.
.SS "int nfiworker_init (struct \fBnfi_server\fP * serv)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIserv\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB199\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBnfi_worker::wb\fP, \fBworkers_init()\fP, \fBnfi_server::wrk\fP, and \fBnfi_server::xpn_thread\fP\&.
.PP
Referenced by \fBnfi_local_init()\fP, \fBnfi_mpi_server_init()\fP, and \fBnfi_tcp_server_init()\fP\&.
.SS "int nfiworker_launch (void(*)(struct \fBst_th\fP) worker_function, struct \fBnfi_worker\fP * wrk)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIworker_function\fP 'TODO'\&. 
.br
\fIwrk\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB204\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBst_th::c_wait\fP, \fBst_th::function\fP, \fBst_th::m_wait\fP, \fBst_th::params\fP, \fBst_th::r_wait\fP, \fBTRUE\fP, \fBst_th::wait4me\fP, \fBnfi_worker::warg\fP, \fBnfi_worker::wb\fP, and \fBworkers_launch()\fP\&.
.PP
Referenced by \fBnfi_worker_do_close()\fP, \fBnfi_worker_do_closedir()\fP, \fBnfi_worker_do_create()\fP, \fBnfi_worker_do_flush()\fP, \fBnfi_worker_do_getattr()\fP, \fBnfi_worker_do_mkdir()\fP, \fBnfi_worker_do_open()\fP, \fBnfi_worker_do_opendir()\fP, \fBnfi_worker_do_preload()\fP, \fBnfi_worker_do_read()\fP, \fBnfi_worker_do_readdir()\fP, \fBnfi_worker_do_remove()\fP, \fBnfi_worker_do_rename()\fP, \fBnfi_worker_do_rmdir()\fP, \fBnfi_worker_do_setattr()\fP, \fBnfi_worker_do_statfs()\fP, and \fBnfi_worker_do_write()\fP\&.
.SS "ssize_t nfiworker_wait (struct \fBnfi_worker\fP * wrk)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIwrk\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB220\fP of file \fBnfi_worker\&.c\fP\&.
.PP
References \fBnfi_worker::arg\fP, \fBnfi_worker_args::result\fP, \fBnfi_worker::warg\fP, \fBnfi_worker::wb\fP, and \fBworkers_wait()\fP\&.
.PP
Referenced by \fBxpn_internal_creat()\fP, \fBxpn_internal_remove()\fP, \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBxpn_simple_flush()\fP, \fBxpn_simple_mkdir()\fP, \fBxpn_simple_preload()\fP, \fBxpn_simple_rename()\fP, \fBxpn_simple_rmdir()\fP, \fBXpnGetAtribFd()\fP, and \fBXpnGetAtribPath()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
