.TH "nfi_nfs3_server" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_nfs3_server
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "CLIENT * \fBcl\fP"
.br
.ti -1c
.RI "\fBfhandle3\fP \fBfh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB44\fP of file \fBnfi_nfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "CLIENT* nfi_nfs3_server::cl"

.PP
Definition at line \fB46\fP of file \fBnfi_nfs3\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs3_create()\fP, \fBnfi_nfs3_destroy()\fP, \fBnfi_nfs3_disconnect()\fP, \fBnfi_nfs3_getattr()\fP, \fBnfi_nfs3_init()\fP, \fBnfi_nfs3_mkdir()\fP, \fBnfi_nfs3_read()\fP, \fBnfi_nfs3_readdir()\fP, \fBnfi_nfs3_reconnect()\fP, \fBnfi_nfs3_remove()\fP, \fBnfi_nfs3_rmdir()\fP, \fBnfi_nfs3_setattr()\fP, \fBnfi_nfs3_statfs()\fP, \fBnfi_nfs3_write()\fP, and \fBnfs3_open()\fP\&.
.SS "\fBfhandle3\fP nfi_nfs3_server::fh"

.PP
Definition at line \fB47\fP of file \fBnfi_nfs3\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs3_close()\fP, \fBnfi_nfs3_create()\fP, \fBnfi_nfs3_getattr()\fP, \fBnfi_nfs3_init()\fP, \fBnfi_nfs3_mkdir()\fP, \fBnfi_nfs3_read()\fP, \fBnfi_nfs3_reconnect()\fP, \fBnfi_nfs3_remove()\fP, \fBnfi_nfs3_rmdir()\fP, \fBnfi_nfs3_setattr()\fP, \fBnfi_nfs3_statfs()\fP, \fBnfi_nfs3_write()\fP, and \fBnfs3_open()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
