.TH "nfi_attr_server" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_attr_server \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "void * \fBprivate_info\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "struct \fBnfi_attr_server\fP * \fBnext\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB114\fP of file \fBnfi\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_attr_server::next"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB119\fP of file \fBnfi\&.h\fP\&.
.SS "nfi_attr_server::private_info"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB118\fP of file \fBnfi\&.h\fP\&.
.SS "nfi_attr_server::size"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB117\fP of file \fBnfi\&.h\fP\&.
.SS "nfi_attr_server::type"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB116\fP of file \fBnfi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
