.TH "nfi_nfs_server" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_nfs_server \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_nfs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "CLIENT * \fBcl\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "fhandle \fBfh\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB57\fP of file \fBnfi_nfs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_nfs_server::cl"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB59\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_create()\fP, \fBnfi_nfs_destroy()\fP, \fBnfi_nfs_disconnect()\fP, \fBnfi_nfs_getattr()\fP, \fBnfi_nfs_init()\fP, \fBnfi_nfs_mkdir()\fP, \fBnfi_nfs_read()\fP, \fBnfi_nfs_readdir()\fP, \fBnfi_nfs_reconnect()\fP, \fBnfi_nfs_remove()\fP, \fBnfi_nfs_rename()\fP, \fBnfi_nfs_rmdir()\fP, \fBnfi_nfs_setattr()\fP, \fBnfi_nfs_statfs()\fP, \fBnfi_nfs_write()\fP, and \fBnfs_open()\fP\&.
.SS "nfi_nfs_server::fh"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB60\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_close()\fP, \fBnfi_nfs_create()\fP, \fBnfi_nfs_getattr()\fP, \fBnfi_nfs_init()\fP, \fBnfi_nfs_mkdir()\fP, \fBnfi_nfs_read()\fP, \fBnfi_nfs_reconnect()\fP, \fBnfi_nfs_remove()\fP, \fBnfi_nfs_rename()\fP, \fBnfi_nfs_rmdir()\fP, \fBnfi_nfs_setattr()\fP, \fBnfi_nfs_statfs()\fP, \fBnfi_nfs_write()\fP, and \fBnfs_open()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
