.TH "nfi_tcp_server_server" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_tcp_server_server
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_tcp_server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBid\fP [\fBPATH_MAX\fP]"
.br
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.ti -1c
.RI "struct mosquitto * \fBmqtt\fP"
.br
.ti -1c
.RI "\fBtcpClient_param_st\fP \fBparams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB71\fP of file \fBnfi_tcp_server\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char nfi_tcp_server_server::id[\fBPATH_MAX\fP]"

.PP
Definition at line \fB74\fP of file \fBnfi_tcp_server\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_close()\fP, \fBnfi_tcp_server_closedir()\fP, \fBnfi_tcp_server_create()\fP, \fBnfi_tcp_server_doRequest()\fP, \fBnfi_tcp_server_flush()\fP, \fBnfi_tcp_server_getattr()\fP, \fBnfi_tcp_server_mkdir()\fP, \fBnfi_tcp_server_open()\fP, \fBnfi_tcp_server_opendir()\fP, \fBnfi_tcp_server_preload()\fP, \fBnfi_tcp_server_read()\fP, \fBnfi_tcp_server_readdir()\fP, \fBnfi_tcp_server_remove()\fP, \fBnfi_tcp_server_rename()\fP, and \fBnfi_tcp_server_write()\fP\&.
.SS "struct mosquitto* nfi_tcp_server_server::mqtt"

.PP
Definition at line \fB77\fP of file \fBnfi_tcp_server\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_destroy()\fP, \fBnfi_tcp_server_init()\fP, and \fBnfi_tcp_server_write()\fP\&.
.SS "\fBtcpClient_param_st\fP nfi_tcp_server_server::params"

.PP
Definition at line \fB80\fP of file \fBnfi_tcp_server\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_close()\fP, \fBnfi_tcp_server_closedir()\fP, \fBnfi_tcp_server_connect()\fP, \fBnfi_tcp_server_create()\fP, \fBnfi_tcp_server_destroy()\fP, \fBnfi_tcp_server_disconnect()\fP, \fBnfi_tcp_server_doRequest()\fP, \fBnfi_tcp_server_getattr()\fP, \fBnfi_tcp_server_init()\fP, \fBnfi_tcp_server_mkdir()\fP, \fBnfi_tcp_server_open()\fP, \fBnfi_tcp_server_opendir()\fP, \fBnfi_tcp_server_read()\fP, \fBnfi_tcp_server_readdir()\fP, \fBnfi_tcp_server_reconnect()\fP, \fBnfi_tcp_server_remove()\fP, \fBnfi_tcp_server_rename()\fP, \fBnfi_tcp_server_rmdir()\fP, and \fBnfi_tcp_server_write()\fP\&.
.SS "char nfi_tcp_server_server::path[\fBPATH_MAX\fP]"

.PP
Definition at line \fB75\fP of file \fBnfi_tcp_server\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_reconnect()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
