.TH "nfi_nfs_fhandle" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_nfs_fhandle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_nfs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBeofdir\fP"
.br
.ti -1c
.RI "nfscookie \fBcookie\fP"
.br
.ti -1c
.RI "fhandle \fBfh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBnfi_nfs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfscookie nfi_nfs_fhandle::cookie"

.PP
Definition at line \fB58\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_readdir()\fP\&.
.SS "int nfi_nfs_fhandle::eofdir"

.PP
Definition at line \fB57\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_readdir()\fP\&.
.SS "fhandle nfi_nfs_fhandle::fh"

.PP
Definition at line \fB59\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_closedir()\fP, \fBnfi_nfs_create()\fP, \fBnfi_nfs_getattr()\fP, \fBnfi_nfs_mkdir()\fP, \fBnfi_nfs_read()\fP, \fBnfi_nfs_readdir()\fP, \fBnfi_nfs_setattr()\fP, \fBnfi_nfs_write()\fP, and \fBnfs_open()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
