.TH "nfi_nfs_err.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_nfs_err.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nfi_nfs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnfs_err\fP (int err)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrno\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfi_nfs_err\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void nfs_err (int err)"

.PP
Definition at line \fB40\fP of file \fBnfi_nfs_err\&.c\fP\&.
.PP
References \fBerrno\fP, \fBNFSERR_GETATTR\fP, \fBNFSERR_MEMORY\fP, \fBNFSERR_MNTCONNECTION\fP, \fBNFSERR_MOUNT\fP, \fBNFSERR_NFSCONNECTION\fP, \fBNFSERR_PARAM\fP, and \fBNFSERR_URL\fP\&.
.PP
Referenced by \fBnfi_nfs_close()\fP, \fBnfi_nfs_create()\fP, \fBnfi_nfs_destroy()\fP, \fBnfi_nfs_disconnect()\fP, \fBnfi_nfs_getattr()\fP, \fBnfi_nfs_init()\fP, \fBnfi_nfs_mkdir()\fP, \fBnfi_nfs_read()\fP, \fBnfi_nfs_readdir()\fP, \fBnfi_nfs_reconnect()\fP, \fBnfi_nfs_remove()\fP, \fBnfi_nfs_rename()\fP, \fBnfi_nfs_rmdir()\fP, \fBnfi_nfs_setattr()\fP, \fBnfi_nfs_statfs()\fP, \fBnfi_nfs_write()\fP, and \fBnfs_open()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int errno\fC [extern]\fP"

.PP
Referenced by \fBnfs_err()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
