.TH "nfi_nfs3_err.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_nfs3_err.h \- Header file to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nfs3\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBnfi_nfs3_err\fP { \fBNFS3ERR_PARAM\fP = 0, \fBNFS3ERR_MEMORY\fP = 1, \fBNFS3ERR_URL\fP = 2, \fBNFS3ERR_MNTCONNECTION\fP = 3, \fBNFS3ERR_MOUNT\fP = 4, \fBNFS3ERR_NFSCONNECTION\fP = 5, \fBNFS3ERR_GETATTR\fP = 6, \fBNFS3ERR_SETATTR\fP = 7, \fBNFS3ERR_LOOKUP\fP = 8, \fBNFS3ERR_READ\fP = 9, \fBNFS3ERR_WRITE\fP = 10, \fBNFS3ERR_CREATE\fP = 11, \fBNFS3ERR_REMOVE\fP = 12, \fBNFS3ERR_MKDIR\fP = 13, \fBNFS3ERR_READDIR\fP = 14, \fBNFS3ERR_STATFS\fP = 15 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnfs3_err\fP (int err)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file to 'TODO'\&. 

Header file to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfi_nfs3_err\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBnfi_nfs3_err\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINFS3ERR_PARAM \fP\fP
.TP
\fB\fINFS3ERR_MEMORY \fP\fP
.TP
\fB\fINFS3ERR_URL \fP\fP
.TP
\fB\fINFS3ERR_MNTCONNECTION \fP\fP
.TP
\fB\fINFS3ERR_MOUNT \fP\fP
.TP
\fB\fINFS3ERR_NFSCONNECTION \fP\fP
.TP
\fB\fINFS3ERR_GETATTR \fP\fP
.TP
\fB\fINFS3ERR_SETATTR \fP\fP
.TP
\fB\fINFS3ERR_LOOKUP \fP\fP
.TP
\fB\fINFS3ERR_READ \fP\fP
.TP
\fB\fINFS3ERR_WRITE \fP\fP
.TP
\fB\fINFS3ERR_CREATE \fP\fP
.TP
\fB\fINFS3ERR_REMOVE \fP\fP
.TP
\fB\fINFS3ERR_MKDIR \fP\fP
.TP
\fB\fINFS3ERR_READDIR \fP\fP
.TP
\fB\fINFS3ERR_STATFS \fP\fP
.PP
Definition at line \fB37\fP of file \fBnfi_nfs3_err\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void nfs3_err (int err)"

.PP
Definition at line \fB40\fP of file \fBnfi_nfs3_err\&.c\fP\&.
.PP
References \fBerrno\fP, \fBNFS3_OK\fP, \fBNFS3ERR_ABORTED\fP, \fBNFS3ERR_ACCES\fP, \fBNFS3ERR_BAD_COOKIE\fP, \fBNFS3ERR_BADHANDLE\fP, \fBNFS3ERR_BADTYPE\fP, \fBNFS3ERR_DQUOT\fP, \fBNFS3ERR_EXIST\fP, \fBNFS3ERR_FBIG\fP, \fBNFS3ERR_FPRINTNOTFOUND\fP, \fBNFS3ERR_INVAL\fP, \fBNFS3ERR_IO\fP, \fBNFS3ERR_ISDIR\fP, \fBNFS3ERR_JUKEBOX\fP, \fBNFS3ERR_MLINK\fP, \fBNFS3ERR_NAMETOOLONG\fP, \fBNFS3ERR_NODEV\fP, \fBNFS3ERR_NOENT\fP, \fBNFS3ERR_NOSPC\fP, \fBNFS3ERR_NOT_SYNC\fP, \fBNFS3ERR_NOTDIR\fP, \fBNFS3ERR_NOTEMPTY\fP, \fBNFS3ERR_NOTSUPP\fP, \fBNFS3ERR_NXIO\fP, \fBNFS3ERR_PERM\fP, \fBNFS3ERR_REMOTE\fP, \fBNFS3ERR_ROFS\fP, \fBNFS3ERR_SERVERFAULT\fP, \fBNFS3ERR_STALE\fP, \fBNFS3ERR_TOOSMALL\fP, and \fBNFS3ERR_XDEV\fP\&.
.PP
Referenced by \fBnfi_nfs3_close()\fP, \fBnfi_nfs3_create()\fP, \fBnfi_nfs3_destroy()\fP, \fBnfi_nfs3_disconnect()\fP, \fBnfi_nfs3_getattr()\fP, \fBnfi_nfs3_init()\fP, \fBnfi_nfs3_mkdir()\fP, \fBnfi_nfs3_opendir()\fP, \fBnfi_nfs3_read()\fP, \fBnfi_nfs3_readdir()\fP, \fBnfi_nfs3_reconnect()\fP, \fBnfi_nfs3_remove()\fP, \fBnfi_nfs3_rmdir()\fP, \fBnfi_nfs3_setattr()\fP, \fBnfi_nfs3_statfs()\fP, \fBnfi_nfs3_write()\fP, and \fBnfs3_open()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
