.TH "nfi_local_err.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_local_err.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nfi_local\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlocal_err\fP (int err)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrno\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfi_local_err\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void local_err (int err)"

.PP
Definition at line \fB43\fP of file \fBnfi_local_err\&.c\fP\&.
.PP
References \fBerrno\fP, \fBLOCALERR_GETATTR\fP, \fBLOCALERR_MEMORY\fP, \fBLOCALERR_MNTCONNECTION\fP, \fBLOCALERR_MOUNT\fP, \fBLOCALERR_NFSCONNECTION\fP, \fBLOCALERR_PARAM\fP, and \fBLOCALERR_URL\fP\&.
.PP
Referenced by \fBnfi_local_create()\fP, \fBnfi_local_mkdir()\fP, \fBnfi_local_open()\fP, \fBnfi_local_opendir()\fP, \fBnfi_local_readdir()\fP, \fBnfi_local_remove()\fP, \fBnfi_local_rename()\fP, and \fBnfi_local_rmdir()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int errno\fC [extern]\fP"

.PP
Referenced by \fBdo_cp_recursive()\fP, \fBlocal_err()\fP, \fBnfi_local_mkdir()\fP, \fBnfi_local_read()\fP, \fBnfi_local_write()\fP, \fBnfi_mpi_server_mkdir()\fP, \fBnfi_mpi_server_read()\fP, \fBnfi_mpi_server_write()\fP, \fBnfi_tcp_server_mkdir()\fP, \fBnfi_tcp_server_read()\fP, \fBnfi_tcp_server_write()\fP, \fBread()\fP, \fBwrite()\fP, \fBxpn_pread()\fP, \fBxpn_simple_fclose()\fP, \fBxpn_simple_fstat()\fP, \fBxpn_simple_lseek()\fP, \fBxpn_simple_open()\fP, \fBxpn_simple_opendir()\fP, \fBxpn_simple_read()\fP, \fBxpn_simple_stat()\fP, \fBxpn_simple_write()\fP, and \fBxpn_sread()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
