.TH "nfi_nfs3_err.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_nfs3_err.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nfi_nfs3\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnfs3_err\fP (int err)"
.br
.RI "'TODO'\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrno\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfi_nfs3_err\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void nfs3_err (int err)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIerr\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBnfi_nfs3_err\&.c\fP\&.
.PP
References \fBerrno\fP, \fBNFS3_OK\fP, \fBNFS3ERR_ABORTED\fP, \fBNFS3ERR_ACCES\fP, \fBNFS3ERR_BAD_COOKIE\fP, \fBNFS3ERR_BADHANDLE\fP, \fBNFS3ERR_BADTYPE\fP, \fBNFS3ERR_DQUOT\fP, \fBNFS3ERR_EXIST\fP, \fBNFS3ERR_FBIG\fP, \fBNFS3ERR_FPRINTNOTFOUND\fP, \fBNFS3ERR_INVAL\fP, \fBNFS3ERR_IO\fP, \fBNFS3ERR_ISDIR\fP, \fBNFS3ERR_JUKEBOX\fP, \fBNFS3ERR_MLINK\fP, \fBNFS3ERR_NAMETOOLONG\fP, \fBNFS3ERR_NODEV\fP, \fBNFS3ERR_NOENT\fP, \fBNFS3ERR_NOSPC\fP, \fBNFS3ERR_NOT_SYNC\fP, \fBNFS3ERR_NOTDIR\fP, \fBNFS3ERR_NOTEMPTY\fP, \fBNFS3ERR_NOTSUPP\fP, \fBNFS3ERR_NXIO\fP, \fBNFS3ERR_PERM\fP, \fBNFS3ERR_REMOTE\fP, \fBNFS3ERR_ROFS\fP, \fBNFS3ERR_SERVERFAULT\fP, \fBNFS3ERR_STALE\fP, \fBNFS3ERR_TOOSMALL\fP, and \fBNFS3ERR_XDEV\fP\&.
.PP
Referenced by \fBnfi_nfs3_close()\fP, \fBnfi_nfs3_create()\fP, \fBnfi_nfs3_destroy()\fP, \fBnfi_nfs3_disconnect()\fP, \fBnfi_nfs3_getattr()\fP, \fBnfi_nfs3_init()\fP, \fBnfi_nfs3_mkdir()\fP, \fBnfi_nfs3_opendir()\fP, \fBnfi_nfs3_read()\fP, \fBnfi_nfs3_readdir()\fP, \fBnfi_nfs3_reconnect()\fP, \fBnfi_nfs3_remove()\fP, \fBnfi_nfs3_rmdir()\fP, \fBnfi_nfs3_setattr()\fP, \fBnfi_nfs3_statfs()\fP, \fBnfi_nfs3_write()\fP, and \fBnfs3_open()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int errno\fC [extern]\fP"

.PP
Referenced by \fBnfs3_err()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
