.TH "nfi_nfs_fhandle" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_nfs_fhandle \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_nfs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBeofdir\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "nfscookie \fBcookie\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "fhandle \fBfh\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB73\fP of file \fBnfi_nfs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_nfs_fhandle::cookie"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB76\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_readdir()\fP\&.
.SS "nfi_nfs_fhandle::eofdir"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB75\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_readdir()\fP\&.
.SS "nfi_nfs_fhandle::fh"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB77\fP of file \fBnfi_nfs\&.h\fP\&.
.PP
Referenced by \fBnfi_nfs_closedir()\fP, \fBnfi_nfs_create()\fP, \fBnfi_nfs_getattr()\fP, \fBnfi_nfs_mkdir()\fP, \fBnfi_nfs_read()\fP, \fBnfi_nfs_readdir()\fP, \fBnfi_nfs_setattr()\fP, \fBnfi_nfs_write()\fP, and \fBnfs_open()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
