.TH "nfi_mpi_server_server" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_mpi_server_server \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_mpi_server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBid\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "\fBmpiClient_param_st\fP \fBparams\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB69\fP of file \fBnfi_mpi_server\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_mpi_server_server::id"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB72\fP of file \fBnfi_mpi_server\&.h\fP\&.
.PP
Referenced by \fBnfi_mpi_server_close()\fP, \fBnfi_mpi_server_closedir()\fP, \fBnfi_mpi_server_create()\fP, \fBnfi_mpi_server_doRequest()\fP, \fBnfi_mpi_server_flush()\fP, \fBnfi_mpi_server_getattr()\fP, \fBnfi_mpi_server_mkdir()\fP, \fBnfi_mpi_server_open()\fP, \fBnfi_mpi_server_opendir()\fP, \fBnfi_mpi_server_preload()\fP, \fBnfi_mpi_server_read()\fP, \fBnfi_mpi_server_readdir()\fP, \fBnfi_mpi_server_remove()\fP, \fBnfi_mpi_server_rename()\fP, and \fBnfi_mpi_server_write()\fP\&.
.SS "nfi_mpi_server_server::params"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB77\fP of file \fBnfi_mpi_server\&.h\fP\&.
.PP
Referenced by \fBnfi_mpi_server_close()\fP, \fBnfi_mpi_server_closedir()\fP, \fBnfi_mpi_server_connect()\fP, \fBnfi_mpi_server_create()\fP, \fBnfi_mpi_server_destroy()\fP, \fBnfi_mpi_server_disconnect()\fP, \fBnfi_mpi_server_doRequest()\fP, \fBnfi_mpi_server_getattr()\fP, \fBnfi_mpi_server_init()\fP, \fBnfi_mpi_server_mkdir()\fP, \fBnfi_mpi_server_open()\fP, \fBnfi_mpi_server_opendir()\fP, \fBnfi_mpi_server_read()\fP, \fBnfi_mpi_server_readdir()\fP, \fBnfi_mpi_server_reconnect()\fP, \fBnfi_mpi_server_remove()\fP, \fBnfi_mpi_server_rename()\fP, \fBnfi_mpi_server_rmdir()\fP, and \fBnfi_mpi_server_write()\fP\&.
.SS "nfi_mpi_server_server::path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB73\fP of file \fBnfi_mpi_server\&.h\fP\&.
.PP
Referenced by \fBnfi_mpi_server_getattr()\fP, \fBnfi_mpi_server_opendir()\fP, \fBnfi_mpi_server_reconnect()\fP, \fBnfi_mpi_server_remove()\fP, and \fBnfi_mpi_server_rmdir()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
