.TH "nfi_local_fhandle" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_local_fhandle \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_local\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBfd\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "DIR * \fBdir\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB78\fP of file \fBnfi_local\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_local_fhandle::dir"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB82\fP of file \fBnfi_local\&.h\fP\&.
.PP
Referenced by \fBnfi_local_closedir()\fP, \fBnfi_local_create()\fP, \fBnfi_local_getattr()\fP, \fBnfi_local_mkdir()\fP, \fBnfi_local_open()\fP, \fBnfi_local_opendir()\fP, \fBnfi_local_readdir()\fP, \fBnfi_local_remove()\fP, and \fBnfi_local_rmdir()\fP\&.
.SS "nfi_local_fhandle::fd"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB81\fP of file \fBnfi_local\&.h\fP\&.
.PP
Referenced by \fBnfi_local_close()\fP, \fBnfi_local_create()\fP, \fBnfi_local_open()\fP, \fBnfi_local_read()\fP, and \fBnfi_local_write()\fP\&.
.SS "nfi_local_fhandle::path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB80\fP of file \fBnfi_local\&.h\fP\&.
.PP
Referenced by \fBnfi_local_create()\fP, \fBnfi_local_open()\fP, and \fBnfi_local_opendir()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
