.TH "nfi_mpi_server_err.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_mpi_server_err.h \- Header file to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBnfi_mpi_server_err\fP { \fBMPI_SERVERERR_PARAM\fP = 0, \fBMPI_SERVERERR_MEMORY\fP = 1, \fBMPI_SERVERERR_URL\fP = 2, \fBMPI_SERVERERR_MNTCONNECTION\fP = 3, \fBMPI_SERVERERR_MOUNT\fP = 4, \fBMPI_SERVERERR_NFSCONNECTION\fP = 5, \fBMPI_SERVERERR_GETATTR\fP = 6, \fBMPI_SERVERERR_LOOKUP\fP = 7, \fBMPI_SERVERERR_READ\fP = 8, \fBMPI_SERVERERR_WRITE\fP = 9, \fBMPI_SERVERERR_CREATE\fP = 10, \fBMPI_SERVERERR_REMOVE\fP = 11, \fBMPI_SERVERERR_MKDIR\fP = 12, \fBMPI_SERVERERR_READDIR\fP = 13, \fBMPI_SERVERERR_STATFS\fP = 14, \fBMPI_SERVERERR_NOTDIR\fP = 15 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmpi_server_err\fP (int err)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file to 'TODO'\&. 

Header file to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfi_mpi_server_err\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBnfi_mpi_server_err\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMPI_SERVERERR_PARAM \fP\fP
.TP
\fB\fIMPI_SERVERERR_MEMORY \fP\fP
.TP
\fB\fIMPI_SERVERERR_URL \fP\fP
.TP
\fB\fIMPI_SERVERERR_MNTCONNECTION \fP\fP
.TP
\fB\fIMPI_SERVERERR_MOUNT \fP\fP
.TP
\fB\fIMPI_SERVERERR_NFSCONNECTION \fP\fP
.TP
\fB\fIMPI_SERVERERR_GETATTR \fP\fP
.TP
\fB\fIMPI_SERVERERR_LOOKUP \fP\fP
.TP
\fB\fIMPI_SERVERERR_READ \fP\fP
.TP
\fB\fIMPI_SERVERERR_WRITE \fP\fP
.TP
\fB\fIMPI_SERVERERR_CREATE \fP\fP
.TP
\fB\fIMPI_SERVERERR_REMOVE \fP\fP
.TP
\fB\fIMPI_SERVERERR_MKDIR \fP\fP
.TP
\fB\fIMPI_SERVERERR_READDIR \fP\fP
.TP
\fB\fIMPI_SERVERERR_STATFS \fP\fP
.TP
\fB\fIMPI_SERVERERR_NOTDIR \fP\fP
.PP
Definition at line \fB40\fP of file \fBnfi_mpi_server_err\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void mpi_server_err (int err)"

.PP
Definition at line \fB40\fP of file \fBnfi_mpi_server_err\&.c\fP\&.
.PP
References \fBerrno\fP, \fBMPI_SERVERERR_GETATTR\fP, \fBMPI_SERVERERR_MEMORY\fP, \fBMPI_SERVERERR_MNTCONNECTION\fP, \fBMPI_SERVERERR_MOUNT\fP, \fBMPI_SERVERERR_NFSCONNECTION\fP, \fBMPI_SERVERERR_PARAM\fP, and \fBMPI_SERVERERR_URL\fP\&.
.PP
Referenced by \fBnfi_mpi_server_create()\fP, \fBnfi_mpi_server_flush()\fP, \fBnfi_mpi_server_getattr()\fP, \fBnfi_mpi_server_init()\fP, \fBnfi_mpi_server_mkdir()\fP, \fBnfi_mpi_server_open()\fP, \fBnfi_mpi_server_opendir()\fP, \fBnfi_mpi_server_preload()\fP, \fBnfi_mpi_server_read()\fP, \fBnfi_mpi_server_readdir()\fP, \fBnfi_mpi_server_reconnect()\fP, \fBnfi_mpi_server_remove()\fP, \fBnfi_mpi_server_rename()\fP, \fBnfi_mpi_server_rmdir()\fP, and \fBnfi_mpi_server_write()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
