.TH "nfi_local_server" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfi_local_server \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfi_local\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB63\fP of file \fBnfi_local\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "nfi_local_server::path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB65\fP of file \fBnfi_local\&.h\fP\&.
.PP
Referenced by \fBnfi_local_init()\fP, and \fBnfi_local_reconnect()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
