.TH "nfs.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nfi/nfi_nfs/nfs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintfh\fP (fhandle fh)"
.br
.ti -1c
.RI "CLIENT * \fBcreate_connection_mount\fP (char *name, int type)"
.br
.ti -1c
.RI "void \fBclose_connection_mount\fP (CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_mount\fP (char *dir, fhandle fhand, CLIENT *cli)"
.br
.ti -1c
.RI "int \fBnfs_umount\fP (char *path, CLIENT *cli)"
.br
.ti -1c
.RI "int \fBnfs_export\fP (exports *exp, CLIENT *cli)"
.br
.ti -1c
.RI "CLIENT * \fBcreate_connection_nfs\fP (char *name, int type)"
.br
.ti -1c
.RI "void \fBclose_connection_nfs\fP (CLIENT *cl)"
.br
.ti -1c
.RI "void \fBsetDate\fP (timevalNfs *t)"
.br
.ti -1c
.RI "void \fBsetAttr\fP (sattr *at, unsigned int mode)"
.br
.ti -1c
.RI "int \fBnfs_setattr\fP (fhandle fh, fattr *fatt, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_getattr\fP (fhandle fh, fattr *fatt, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_lookup\fP (fhandle fhin, char *path, fhandle fhout, fattr *att, CLIENT *cl)"
.br
.ti -1c
.RI "ssize_t \fBnfs_read\fP (fhandle fh, void *data, off_t offset, size_t size, CLIENT *cl)"
.br
.ti -1c
.RI "ssize_t \fBnfs_write\fP (fhandle fh, void *data, off_t offset, size_t size, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_create\fP (fhandle fhin, char *file, mode_t mode, fhandle fhout, fattr *at, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_remove\fP (fhandle fh, char *file, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_rename\fP (fhandle fh, char *name, fhandle fhR, char *nameR, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_mkdir\fP (fhandle fhin, char *dir, mode_t mode, fhandle fhout, fattr *at, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_rmdir\fP (fhandle fh, char *dir, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_readdir\fP (fhandle fh, nfscookie cookie, char *entr, CLIENT *cl)"
.br
.ti -1c
.RI "int \fBnfs_statfs\fP (fhandle arg, struct nfs_info *inf, CLIENT *cl)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBnfs\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void close_connection_mount (CLIENT * cl)"

.PP
Definition at line \fB207\fP of file \fBnfs\&.c\fP\&.
.PP
Referenced by \fBcreate_connection_mount()\fP, \fBnfi_nfs_destroy()\fP, \fBnfi_nfs_disconnect()\fP, \fBnfi_nfs_init()\fP, and \fBnfi_nfs_reconnect()\fP\&.
.SS "void close_connection_nfs (CLIENT * cl)"

.PP
Definition at line \fB500\fP of file \fBnfs\&.c\fP\&.
.PP
Referenced by \fBcreate_connection_nfs()\fP, \fBnfi_nfs_destroy()\fP, \fBnfi_nfs_disconnect()\fP, and \fBnfi_nfs_init()\fP\&.
.SS "CLIENT * create_connection_mount (char * name, int type)"

.PP
Definition at line \fB103\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBclose_connection_mount()\fP, \fBMNTNAMLEN\fP, \fBMOUNT1_PROGRAM\fP, \fBMOUNT1_VERSION\fP, \fBNFS_TCP\fP, \fBNFS_UDP\fP, \fBRECVSZ\fP, and \fBSENDSZ\fP\&.
.PP
Referenced by \fBnfi_nfs_destroy()\fP, \fBnfi_nfs_disconnect()\fP, \fBnfi_nfs_init()\fP, and \fBnfi_nfs_reconnect()\fP\&.
.SS "CLIENT * create_connection_nfs (char * name, int type)"

.PP
Definition at line \fB401\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBclose_connection_nfs()\fP, \fBMNTNAMLEN\fP, \fBNFS2_PROGRAM\fP, \fBNFS2_VERSION\fP, \fBNFS_TCP\fP, \fBNFS_UDP\fP, \fBRECVSZ\fP, and \fBSENDSZ\fP\&.
.PP
Referenced by \fBnfi_nfs_init()\fP, and \fBnfi_nfs_reconnect()\fP\&.
.SS "int nfs_create (fhandle fhin, char * file, mode_t mode, fhandle fhout, fattr * at, CLIENT * cl)"

.PP
Definition at line \fB1053\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP, \fBprintfh()\fP, and \fBsetAttr()\fP\&.
.PP
Referenced by \fBnfi_nfs_create()\fP\&.
.SS "int nfs_export (exports * exp, CLIENT * cli)"

.PP
Definition at line \fB354\fP of file \fBnfs\&.c\fP\&.
.SS "int nfs_getattr (fhandle fh, fattr * fatt, CLIENT * cl)"

.PP
Definition at line \fB631\fP of file \fBnfs\&.c\fP\&.
.PP
Referenced by \fBnfi_nfs_getattr()\fP\&.
.SS "int nfs_lookup (fhandle fhin, char * path, fhandle fhout, fattr * att, CLIENT * cl)"

.PP
Definition at line \fB693\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP, \fBgetFirstDir()\fP, \fBMNTNAMLEN\fP, and \fBprintfh()\fP\&.
.PP
Referenced by \fBnfi_nfs_create()\fP, \fBnfi_nfs_mkdir()\fP, \fBnfi_nfs_remove()\fP, \fBnfi_nfs_rename()\fP, \fBnfi_nfs_rmdir()\fP, and \fBnfs_open()\fP\&.
.SS "int nfs_mkdir (fhandle fhin, char * dir, mode_t mode, fhandle fhout, fattr * at, CLIENT * cl)"

.PP
Definition at line \fB1262\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP, and \fBsetAttr()\fP\&.
.PP
Referenced by \fBnfi_nfs_mkdir()\fP\&.
.SS "int nfs_mount (char * dir, fhandle fhand, CLIENT * cli)"

.PP
Definition at line \fB241\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP, and \fBprintfh()\fP\&.
.PP
Referenced by \fBnfi_nfs_init()\fP, and \fBnfi_nfs_reconnect()\fP\&.
.SS "ssize_t nfs_read (fhandle fh, void * data, off_t offset, size_t size, CLIENT * cl)"

.PP
Definition at line \fB838\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP\&.
.PP
Referenced by \fBnfi_nfs_read()\fP\&.
.SS "int nfs_readdir (fhandle fh, nfscookie cookie, char * entr, CLIENT * cl)"

.PP
Definition at line \fB1408\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP, \fBNFSMAXPATHLEN\fP, and \fBTRUE\fP\&.
.PP
Referenced by \fBnfi_nfs_readdir()\fP\&.
.SS "int nfs_remove (fhandle fh, char * file, CLIENT * cl)"

.PP
Definition at line \fB1123\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP\&.
.PP
Referenced by \fBnfi_nfs_remove()\fP\&.
.SS "int nfs_rename (fhandle fh, char * name, fhandle fhR, char * nameR, CLIENT * cl)"

.PP
Definition at line \fB1187\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP\&.
.PP
Referenced by \fBnfi_nfs_rename()\fP\&.
.SS "int nfs_rmdir (fhandle fh, char * dir, CLIENT * cl)"

.PP
Definition at line \fB1336\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP\&.
.PP
Referenced by \fBnfi_nfs_rmdir()\fP\&.
.SS "int nfs_setattr (fhandle fh, fattr * fatt, CLIENT * cl)"

.PP
Definition at line \fB570\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP\&.
.PP
Referenced by \fBnfi_nfs_setattr()\fP\&.
.SS "int nfs_statfs (fhandle arg, struct nfs_info * inf, CLIENT * cl)"

.PP
Definition at line \fB1528\fP of file \fBnfs\&.c\fP\&.
.PP
Referenced by \fBnfi_nfs_statfs()\fP\&.
.SS "int nfs_umount (char * path, CLIENT * cli)"

.PP
Definition at line \fB307\fP of file \fBnfs\&.c\fP\&.
.PP
Referenced by \fBnfi_nfs_destroy()\fP, and \fBnfi_nfs_disconnect()\fP\&.
.SS "ssize_t nfs_write (fhandle fh, void * data, off_t offset, size_t size, CLIENT * cl)"

.PP
Definition at line \fB952\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBFHSIZE\fP\&.
.PP
Referenced by \fBnfi_nfs_write()\fP\&.
.SS "void printfh (fhandle fh)"

.PP
Definition at line \fB40\fP of file \fBnfs\&.c\fP\&.
.PP
Referenced by \fBnfs_create()\fP, \fBnfs_lookup()\fP, and \fBnfs_mount()\fP\&.
.SS "void setAttr (sattr * at, unsigned int mode)"

.PP
Definition at line \fB534\fP of file \fBnfs\&.c\fP\&.
.PP
References \fBsetDate()\fP\&.
.PP
Referenced by \fBnfs_create()\fP, and \fBnfs_mkdir()\fP\&.
.SS "void setDate (timevalNfs * t)"

.PP
Definition at line \fB521\fP of file \fBnfs\&.c\fP\&.
.PP
Referenced by \fBsetAttr()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
