.TH "nfs3_xdr.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfs3_xdr.c
.SH SYNOPSIS
.br
.PP
\fC#include 'nfi/nfi_nfs3/nfs3\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool_t \fBxdr_uint64\fP (XDR *xdrs, \fBuint64\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_int64\fP (XDR *xdrs, \fBint64\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_uint32\fP (XDR *xdrs, \fBuint32\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_int32\fP (XDR *xdrs, \fBint32\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_filename3\fP (XDR *xdrs, \fBfilename3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_nfspath3\fP (XDR *xdrs, \fBnfspath3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_cookieverf3\fP (XDR *xdrs, \fBcookieverf3\fP objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_createverf3\fP (XDR *xdrs, \fBcreateverf3\fP objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_writeverf3\fP (XDR *xdrs, \fBwriteverf3\fP objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_fhandle3\fP (XDR *xdrs, \fBfhandle3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mountstat3\fP (XDR *xdrs, \fBmountstat3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mountres3_ok\fP (XDR *xdrs, \fBmountres3_ok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mountres3\fP (XDR *xdrs, \fBmountres3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mountlist3\fP (XDR *xdrs, \fBmountlist3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mountbody3\fP (XDR *xdrs, \fBmountbody3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_groups3\fP (XDR *xdrs, \fBgroups3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_groupnode3\fP (XDR *xdrs, \fBgroupnode3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_exports3\fP (XDR *xdrs, \fBexports3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_exportnode3\fP (XDR *xdrs, \fBexportnode3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_nfsstat3\fP (XDR *xdrs, \fBnfsstat3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_ftype3\fP (XDR *xdrs, \fBftype3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_specdata3\fP (XDR *xdrs, \fBspecdata3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_nfstime3\fP (XDR *xdrs, \fBnfstime3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_fattr3\fP (XDR *xdrs, \fBfattr3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_post_op_attr\fP (XDR *xdrs, \fBpost_op_attr\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_wcc_attr\fP (XDR *xdrs, \fBwcc_attr\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_pre_op_attr\fP (XDR *xdrs, \fBpre_op_attr\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_wcc_data\fP (XDR *xdrs, \fBwcc_data\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_post_op_fh3\fP (XDR *xdrs, \fBpost_op_fh3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_set_uint32\fP (XDR *xdrs, \fBset_uint32\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_set_uint64\fP (XDR *xdrs, \fBset_uint64\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_time_how\fP (XDR *xdrs, \fBtime_how\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_set_time\fP (XDR *xdrs, \fBset_time\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_sattr3\fP (XDR *xdrs, \fBsattr3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_diropargs3\fP (XDR *xdrs, \fBdiropargs3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_diropres3ok\fP (XDR *xdrs, \fBdiropres3ok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_diropres3\fP (XDR *xdrs, \fBdiropres3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_wccstat3\fP (XDR *xdrs, \fBwccstat3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_getattr3res\fP (XDR *xdrs, \fBgetattr3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_sattrguard3\fP (XDR *xdrs, \fBsattrguard3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_setattr3args\fP (XDR *xdrs, \fBsetattr3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_lookup3resok\fP (XDR *xdrs, \fBlookup3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_lookup3res\fP (XDR *xdrs, \fBlookup3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_access3args\fP (XDR *xdrs, \fBaccess3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_access3resok\fP (XDR *xdrs, \fBaccess3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_access3res\fP (XDR *xdrs, \fBaccess3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readlink3resok\fP (XDR *xdrs, \fBreadlink3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readlink3res\fP (XDR *xdrs, \fBreadlink3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_read3args\fP (XDR *xdrs, \fBread3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_read3resok\fP (XDR *xdrs, \fBread3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_read3res\fP (XDR *xdrs, \fBread3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_stable_how\fP (XDR *xdrs, \fBstable_how\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_write3args\fP (XDR *xdrs, \fBwrite3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_write3resok\fP (XDR *xdrs, \fBwrite3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_write3res\fP (XDR *xdrs, \fBwrite3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_createmode3\fP (XDR *xdrs, \fBcreatemode3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_createhow3\fP (XDR *xdrs, \fBcreatehow3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_create3args\fP (XDR *xdrs, \fBcreate3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mkdir3args\fP (XDR *xdrs, \fBmkdir3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_symlinkdata3\fP (XDR *xdrs, \fBsymlinkdata3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_symlink3args\fP (XDR *xdrs, \fBsymlink3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_devicedata3\fP (XDR *xdrs, \fBdevicedata3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mknoddata3\fP (XDR *xdrs, \fBmknoddata3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_mknod3args\fP (XDR *xdrs, \fBmknod3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_rename3args\fP (XDR *xdrs, \fBrename3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_rename3wcc\fP (XDR *xdrs, \fBrename3wcc\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_rename3res\fP (XDR *xdrs, \fBrename3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_link3args\fP (XDR *xdrs, \fBlink3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_link3wcc\fP (XDR *xdrs, \fBlink3wcc\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_link3res\fP (XDR *xdrs, \fBlink3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readdir3args\fP (XDR *xdrs, \fBreaddir3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_entry3\fP (XDR *xdrs, \fBentry3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_dirlist3\fP (XDR *xdrs, \fBdirlist3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readdir3resok\fP (XDR *xdrs, \fBreaddir3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readdir3res\fP (XDR *xdrs, \fBreaddir3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readdirplus3args\fP (XDR *xdrs, \fBreaddirplus3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_entryplus3\fP (XDR *xdrs, \fBentryplus3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_dirlistplus3\fP (XDR *xdrs, \fBdirlistplus3\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readdirplus3resok\fP (XDR *xdrs, \fBreaddirplus3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_readdirplus3res\fP (XDR *xdrs, \fBreaddirplus3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_fsstat3resok\fP (XDR *xdrs, \fBfsstat3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_fsstat3res\fP (XDR *xdrs, \fBfsstat3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_fsinfo3resok\fP (XDR *xdrs, \fBfsinfo3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_fsinfo3res\fP (XDR *xdrs, \fBfsinfo3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_pathconf3resok\fP (XDR *xdrs, \fBpathconf3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_pathconf3res\fP (XDR *xdrs, \fBpathconf3res\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_commit3args\fP (XDR *xdrs, \fBcommit3args\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_commit3resok\fP (XDR *xdrs, \fBcommit3resok\fP *objp)"
.br
.ti -1c
.RI "bool_t \fBxdr_commit3res\fP (XDR *xdrs, \fBcommit3res\fP *objp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool_t xdr_access3args (XDR * xdrs, \fBaccess3args\fP * objp)"

.PP
Definition at line \fB618\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBaccess3args::access\fP, \fBFALSE\fP, \fBaccess3args::object\fP, \fBTRUE\fP, \fBxdr_fhandle3()\fP, and \fBxdr_uint32()\fP\&.
.SS "bool_t xdr_access3res (XDR * xdrs, \fBaccess3res\fP * objp)"

.PP
Definition at line \fB642\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBaccess3res::access3res_u\fP, \fBFALSE\fP, \fBNFS3_OK\fP, \fBaccess3res::resfail\fP, \fBaccess3res::resok\fP, \fBaccess3res::status\fP, \fBTRUE\fP, \fBxdr_access3resok()\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_access3resok (XDR * xdrs, \fBaccess3resok\fP * objp)"

.PP
Definition at line \fB630\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBaccess3resok::access\fP, \fBFALSE\fP, \fBaccess3resok::obj_attributes\fP, \fBTRUE\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_uint32()\fP\&.
.SS "bool_t xdr_commit3args (XDR * xdrs, \fBcommit3args\fP * objp)"

.PP
Definition at line \fB1370\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBcommit3args::count\fP, \fBFALSE\fP, \fBcommit3args::file\fP, \fBcommit3args::offset\fP, \fBTRUE\fP, \fBxdr_fhandle3()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_commit3res (XDR * xdrs, \fBcommit3res\fP * objp)"

.PP
Definition at line \fB1396\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBcommit3res::commit3res_u\fP, \fBFALSE\fP, \fBNFS3_OK\fP, \fBcommit3res::resfail\fP, \fBcommit3res::resok\fP, \fBcommit3res::status\fP, \fBTRUE\fP, \fBxdr_commit3resok()\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_wcc_data()\fP\&.
.SS "bool_t xdr_commit3resok (XDR * xdrs, \fBcommit3resok\fP * objp)"

.PP
Definition at line \fB1384\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBcommit3resok::file_wcc\fP, \fBTRUE\fP, \fBcommit3resok::verf\fP, \fBxdr_wcc_data()\fP, and \fBxdr_writeverf3()\fP\&.
.SS "bool_t xdr_cookieverf3 (XDR * xdrs, \fBcookieverf3\fP objp)"

.PP
Definition at line \fB69\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_COOKIEVERFSIZE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_create3args (XDR * xdrs, \fBcreate3args\fP * objp)"

.PP
Definition at line \fB841\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBcreate3args::how\fP, \fBTRUE\fP, \fBcreate3args::where\fP, \fBxdr_createhow3()\fP, and \fBxdr_diropargs3()\fP\&.
.SS "bool_t xdr_createhow3 (XDR * xdrs, \fBcreatehow3\fP * objp)"

.PP
Definition at line \fB818\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBcreatehow3::createhow3_u\fP, \fBEXCLUSIVE\fP, \fBFALSE\fP, \fBGUARDED\fP, \fBcreatehow3::mode\fP, \fBcreatehow3::obj_attributes\fP, \fBTRUE\fP, \fBUNCHECKED\fP, \fBcreatehow3::verf\fP, \fBxdr_createmode3()\fP, \fBxdr_createverf3()\fP, and \fBxdr_sattr3()\fP\&.
.SS "bool_t xdr_createmode3 (XDR * xdrs, \fBcreatemode3\fP * objp)"

.PP
Definition at line \fB808\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_createverf3 (XDR * xdrs, \fBcreateverf3\fP objp)"

.PP
Definition at line \fB79\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_CREATEVERFSIZE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_devicedata3 (XDR * xdrs, \fBdevicedata3\fP * objp)"

.PP
Definition at line \fB889\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBdevicedata3::dev_attributes\fP, \fBFALSE\fP, \fBdevicedata3::spec\fP, \fBTRUE\fP, \fBxdr_sattr3()\fP, and \fBxdr_specdata3()\fP\&.
.SS "bool_t xdr_dirlist3 (XDR * xdrs, \fBdirlist3\fP * objp)"

.PP
Definition at line \fB1053\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBdirlist3::entries\fP, \fBdirlist3::eof\fP, \fBFALSE\fP, \fBTRUE\fP, and \fBxdr_entry3()\fP\&.
.SS "bool_t xdr_dirlistplus3 (XDR * xdrs, \fBdirlistplus3\fP * objp)"

.PP
Definition at line \fB1137\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBdirlistplus3::entries\fP, \fBdirlistplus3::eof\fP, \fBFALSE\fP, \fBTRUE\fP, and \fBxdr_entryplus3()\fP\&.
.SS "bool_t xdr_diropargs3 (XDR * xdrs, \fBdiropargs3\fP * objp)"

.PP
Definition at line \fB468\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBdiropargs3::dir\fP, \fBFALSE\fP, \fBdiropargs3::name\fP, \fBTRUE\fP, \fBxdr_fhandle3()\fP, and \fBxdr_filename3()\fP\&.
.SS "bool_t xdr_diropres3 (XDR * xdrs, \fBdiropres3\fP * objp)"

.PP
Definition at line \fB494\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBdiropres3::diropres3_u\fP, \fBFALSE\fP, \fBNFS3_OK\fP, \fBdiropres3::resfail\fP, \fBdiropres3::resok\fP, \fBdiropres3::status\fP, \fBTRUE\fP, \fBxdr_diropres3ok()\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_wcc_data()\fP\&.
.SS "bool_t xdr_diropres3ok (XDR * xdrs, \fBdiropres3ok\fP * objp)"

.PP
Definition at line \fB480\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBdiropres3ok::dir_wcc\fP, \fBFALSE\fP, \fBdiropres3ok::obj\fP, \fBdiropres3ok::obj_attributes\fP, \fBTRUE\fP, \fBxdr_post_op_attr()\fP, \fBxdr_post_op_fh3()\fP, and \fBxdr_wcc_data()\fP\&.
.SS "bool_t xdr_entry3 (XDR * xdrs, \fBentry3\fP * objp)"

.PP
Definition at line \fB1037\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBentry3::cookie\fP, \fBFALSE\fP, \fBentry3::fileid\fP, \fBentry3::name\fP, \fBentry3::nextentry\fP, \fBTRUE\fP, \fBxdr_entry3()\fP, \fBxdr_filename3()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_entryplus3 (XDR * xdrs, \fBentryplus3\fP * objp)"

.PP
Definition at line \fB1117\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBentryplus3::cookie\fP, \fBFALSE\fP, \fBentryplus3::fileid\fP, \fBentryplus3::name\fP, \fBentryplus3::name_attributes\fP, \fBentryplus3::name_handle\fP, \fBentryplus3::nextentry\fP, \fBTRUE\fP, \fBxdr_entryplus3()\fP, \fBxdr_filename3()\fP, \fBxdr_post_op_attr()\fP, \fBxdr_post_op_fh3()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_exportnode3 (XDR * xdrs, \fBexportnode3\fP * objp)"

.PP
Definition at line \fB206\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBexportnode3::ex_dir\fP, \fBexportnode3::ex_groups3\fP, \fBexportnode3::ex_next\fP, \fBFALSE\fP, \fBTRUE\fP, \fBxdr_exports3()\fP, \fBxdr_groups3()\fP, and \fBxdr_nfspath3()\fP\&.
.SS "bool_t xdr_exports3 (XDR * xdrs, \fBexports3\fP * objp)"

.PP
Definition at line \fB196\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBTRUE\fP, and \fBxdr_exportnode3()\fP\&.
.SS "bool_t xdr_fattr3 (XDR * xdrs, \fBfattr3\fP * objp)"

.PP
Definition at line \fB264\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBfattr3::atime\fP, \fBfattr3::ctime\fP, \fBFALSE\fP, \fBfattr3::fileid\fP, \fBfattr3::fsid\fP, \fBfattr3::gid\fP, \fBfattr3::mode\fP, \fBfattr3::mtime\fP, \fBfattr3::nlink\fP, \fBfattr3::rdev\fP, \fBfattr3::size\fP, \fBTRUE\fP, \fBfattr3::type\fP, \fBfattr3::uid\fP, \fBfattr3::used\fP, \fBxdr_ftype3()\fP, \fBxdr_nfstime3()\fP, \fBxdr_specdata3()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_fhandle3 (XDR * xdrs, \fBfhandle3\fP * objp)"

.PP
Definition at line \fB99\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBfhandle3::fhandle3_len\fP, \fBfhandle3::fhandle3_val\fP, \fBNFS3_FHSIZE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_filename3 (XDR * xdrs, \fBfilename3\fP * objp)"

.PP
Definition at line \fB49\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_fsinfo3res (XDR * xdrs, \fBfsinfo3res\fP * objp)"

.PP
Definition at line \fB1257\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBfsinfo3res::fsinfo3res_u\fP, \fBNFS3_OK\fP, \fBfsinfo3res::resfail\fP, \fBfsinfo3res::resok\fP, \fBfsinfo3res::status\fP, \fBTRUE\fP, \fBxdr_fsinfo3resok()\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_fsinfo3resok (XDR * xdrs, \fBfsinfo3resok\fP * objp)"

.PP
Definition at line \fB1227\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBfsinfo3resok::dtpref\fP, \fBFALSE\fP, \fBfsinfo3resok::maxfilesize\fP, \fBfsinfo3resok::obj_attributes\fP, \fBfsinfo3resok::properties\fP, \fBfsinfo3resok::rtmax\fP, \fBfsinfo3resok::rtmult\fP, \fBfsinfo3resok::rtpref\fP, \fBfsinfo3resok::time_delta\fP, \fBTRUE\fP, \fBfsinfo3resok::wtmax\fP, \fBfsinfo3resok::wtmult\fP, \fBfsinfo3resok::wtpref\fP, \fBxdr_nfstime3()\fP, \fBxdr_post_op_attr()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_fsstat3res (XDR * xdrs, \fBfsstat3res\fP * objp)"

.PP
Definition at line \fB1207\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBfsstat3res::fsstat3res_u\fP, \fBNFS3_OK\fP, \fBfsstat3res::resfail\fP, \fBfsstat3res::resok\fP, \fBfsstat3res::status\fP, \fBTRUE\fP, \fBxdr_fsstat3resok()\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_fsstat3resok (XDR * xdrs, \fBfsstat3resok\fP * objp)"

.PP
Definition at line \fB1183\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBfsstat3resok::abytes\fP, \fBfsstat3resok::afiles\fP, \fBFALSE\fP, \fBfsstat3resok::fbytes\fP, \fBfsstat3resok::ffiles\fP, \fBfsstat3resok::invarsec\fP, \fBfsstat3resok::obj_attributes\fP, \fBfsstat3resok::tbytes\fP, \fBfsstat3resok::tfiles\fP, \fBTRUE\fP, \fBxdr_post_op_attr()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_ftype3 (XDR * xdrs, \fBftype3\fP * objp)"

.PP
Definition at line \fB230\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_getattr3res (XDR * xdrs, \fBgetattr3res\fP * objp)"

.PP
Definition at line \fB532\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBgetattr3res::attributes\fP, \fBFALSE\fP, \fBgetattr3res::getattr3res_u\fP, \fBNFS3_OK\fP, \fBgetattr3res::status\fP, \fBTRUE\fP, \fBxdr_fattr3()\fP, and \fBxdr_nfsstat3()\fP\&.
.SS "bool_t xdr_groupnode3 (XDR * xdrs, \fBgroupnode3\fP * objp)"

.PP
Definition at line \fB184\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBgroupnode3::gr_name\fP, \fBgroupnode3::gr_next\fP, \fBTRUE\fP, \fBxdr_filename3()\fP, and \fBxdr_groups3()\fP\&.
.SS "bool_t xdr_groups3 (XDR * xdrs, \fBgroups3\fP * objp)"

.PP
Definition at line \fB174\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBTRUE\fP, and \fBxdr_groupnode3()\fP\&.
.SS "bool_t xdr_int32 (XDR * xdrs, \fBint32\fP * objp)"

.PP
Definition at line \fB39\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_int64 (XDR * xdrs, \fBint64\fP * objp)"

.PP
Definition at line \fB19\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_link3args (XDR * xdrs, \fBlink3args\fP * objp)"

.PP
Definition at line \fB979\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBlink3args::file\fP, \fBlink3args::link\fP, \fBTRUE\fP, \fBxdr_diropargs3()\fP, and \fBxdr_fhandle3()\fP\&.
.SS "bool_t xdr_link3res (XDR * xdrs, \fBlink3res\fP * objp)"

.PP
Definition at line \fB1003\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBlink3res::link3res_u\fP, \fBlink3res::res\fP, \fBlink3res::status\fP, \fBTRUE\fP, \fBxdr_link3wcc()\fP, and \fBxdr_nfsstat3()\fP\&.
.SS "bool_t xdr_link3wcc (XDR * xdrs, \fBlink3wcc\fP * objp)"

.PP
Definition at line \fB991\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBlink3wcc::file_attributes\fP, \fBlink3wcc::linkdir_wcc\fP, \fBTRUE\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_wcc_data()\fP\&.
.SS "bool_t xdr_lookup3res (XDR * xdrs, \fBlookup3res\fP * objp)"

.PP
Definition at line \fB598\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBlookup3res::lookup3res_u\fP, \fBNFS3_OK\fP, \fBlookup3res::resfail\fP, \fBlookup3res::resok\fP, \fBlookup3res::status\fP, \fBTRUE\fP, \fBxdr_lookup3resok()\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_lookup3resok (XDR * xdrs, \fBlookup3resok\fP * objp)"

.PP
Definition at line \fB584\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBlookup3resok::dir_attributes\fP, \fBFALSE\fP, \fBlookup3resok::obj_attributes\fP, \fBlookup3resok::object\fP, \fBTRUE\fP, \fBxdr_fhandle3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_mkdir3args (XDR * xdrs, \fBmkdir3args\fP * objp)"

.PP
Definition at line \fB853\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBmkdir3args::attributes\fP, \fBFALSE\fP, \fBTRUE\fP, \fBmkdir3args::where\fP, \fBxdr_diropargs3()\fP, and \fBxdr_sattr3()\fP\&.
.SS "bool_t xdr_mknod3args (XDR * xdrs, \fBmknod3args\fP * objp)"

.PP
Definition at line \fB925\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBTRUE\fP, \fBmknod3args::what\fP, \fBmknod3args::where\fP, \fBxdr_diropargs3()\fP, and \fBxdr_mknoddata3()\fP\&.
.SS "bool_t xdr_mknoddata3 (XDR * xdrs, \fBmknoddata3\fP * objp)"

.PP
Definition at line \fB901\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBmknoddata3::device\fP, \fBFALSE\fP, \fBmknoddata3::mknoddata3_u\fP, \fBNF3BLK\fP, \fBNF3CHR\fP, \fBNF3FIFO\fP, \fBNF3SOCK\fP, \fBmknoddata3::pipe_attributes\fP, \fBTRUE\fP, \fBmknoddata3::type\fP, \fBxdr_devicedata3()\fP, \fBxdr_ftype3()\fP, and \fBxdr_sattr3()\fP\&.
.SS "bool_t xdr_mountbody3 (XDR * xdrs, \fBmountbody3\fP * objp)"

.PP
Definition at line \fB160\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBmountbody3::ml_directory\fP, \fBmountbody3::ml_hostname\fP, \fBmountbody3::ml_next\fP, \fBTRUE\fP, \fBxdr_filename3()\fP, \fBxdr_mountlist3()\fP, and \fBxdr_nfspath3()\fP\&.
.SS "bool_t xdr_mountlist3 (XDR * xdrs, \fBmountlist3\fP * objp)"

.PP
Definition at line \fB150\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBTRUE\fP, and \fBxdr_mountbody3()\fP\&.
.SS "bool_t xdr_mountres3 (XDR * xdrs, \fBmountres3\fP * objp)"

.PP
Definition at line \fB132\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBmountres3::fhs_status\fP, \fBMNT3_OK\fP, \fBmountres3::mountinfo\fP, \fBmountres3::mountres3_u\fP, \fBTRUE\fP, \fBxdr_mountres3_ok()\fP, and \fBxdr_mountstat3()\fP\&.
.SS "bool_t xdr_mountres3_ok (XDR * xdrs, \fBmountres3_ok\fP * objp)"

.PP
Definition at line \fB119\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBmountres3_ok::auth_flavors\fP, \fBmountres3_ok::auth_flavors_len\fP, \fBmountres3_ok::auth_flavors_val\fP, \fBFALSE\fP, \fBmountres3_ok::fhandle\fP, \fBTRUE\fP, and \fBxdr_fhandle3()\fP\&.
.SS "bool_t xdr_mountstat3 (XDR * xdrs, \fBmountstat3\fP * objp)"

.PP
Definition at line \fB109\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_nfspath3 (XDR * xdrs, \fBnfspath3\fP * objp)"

.PP
Definition at line \fB59\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_nfsstat3 (XDR * xdrs, \fBnfsstat3\fP * objp)"

.PP
Definition at line \fB220\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_nfstime3 (XDR * xdrs, \fBnfstime3\fP * objp)"

.PP
Definition at line \fB252\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBnfstime3::nseconds\fP, \fBnfstime3::seconds\fP, \fBTRUE\fP, and \fBxdr_uint32()\fP\&.
.SS "bool_t xdr_pathconf3res (XDR * xdrs, \fBpathconf3res\fP * objp)"

.PP
Definition at line \fB1350\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_OK\fP, \fBpathconf3res::pathconf3res_u\fP, \fBpathconf3res::resfail\fP, \fBpathconf3res::resok\fP, \fBpathconf3res::status\fP, \fBTRUE\fP, \fBxdr_nfsstat3()\fP, \fBxdr_pathconf3resok()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_pathconf3resok (XDR * xdrs, \fBpathconf3resok\fP * objp)"

.PP
Definition at line \fB1277\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBbuf\fP, \fBpathconf3resok::case_insensitive\fP, \fBpathconf3resok::case_preserving\fP, \fBpathconf3resok::chown_restricted\fP, \fBFALSE\fP, \fBpathconf3resok::linkmax\fP, \fBpathconf3resok::name_max\fP, \fBpathconf3resok::no_trunc\fP, \fBpathconf3resok::obj_attributes\fP, \fBTRUE\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_uint32()\fP\&.
.SS "bool_t xdr_post_op_attr (XDR * xdrs, \fBpost_op_attr\fP * objp)"

.PP
Definition at line \fB298\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBpost_op_attr::attributes\fP, \fBFALSE\fP, \fBpost_op_attr::post_op_attr_u\fP, \fBpost_op_attr::present\fP, \fBTRUE\fP, and \fBxdr_fattr3()\fP\&.
.SS "bool_t xdr_post_op_fh3 (XDR * xdrs, \fBpost_op_fh3\fP * objp)"

.PP
Definition at line \fB364\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBpost_op_fh3::handle\fP, \fBpost_op_fh3::post_op_fh3_u\fP, \fBpost_op_fh3::present\fP, \fBTRUE\fP, and \fBxdr_fhandle3()\fP\&.
.SS "bool_t xdr_pre_op_attr (XDR * xdrs, \fBpre_op_attr\fP * objp)"

.PP
Definition at line \fB332\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBpre_op_attr::attributes\fP, \fBFALSE\fP, \fBpre_op_attr::pre_op_attr_u\fP, \fBpre_op_attr::present\fP, \fBTRUE\fP, and \fBxdr_wcc_attr()\fP\&.
.SS "bool_t xdr_read3args (XDR * xdrs, \fBread3args\fP * objp)"

.PP
Definition at line \fB694\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBread3args::count\fP, \fBFALSE\fP, \fBread3args::file\fP, \fBread3args::offset\fP, \fBTRUE\fP, \fBxdr_fhandle3()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_read3res (XDR * xdrs, \fBread3res\fP * objp)"

.PP
Definition at line \fB724\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_OK\fP, \fBread3res::read3res_u\fP, \fBread3res::resfail\fP, \fBread3res::resok\fP, \fBread3res::status\fP, \fBTRUE\fP, \fBxdr_nfsstat3()\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_read3resok()\fP\&.
.SS "bool_t xdr_read3resok (XDR * xdrs, \fBread3resok\fP * objp)"

.PP
Definition at line \fB708\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBread3resok::count\fP, \fBread3resok::data\fP, \fBread3resok::data_len\fP, \fBread3resok::data_val\fP, \fBread3resok::eof\fP, \fBFALSE\fP, \fBread3resok::file_attributes\fP, \fBTRUE\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_uint32()\fP\&.
.SS "bool_t xdr_readdir3args (XDR * xdrs, \fBreaddir3args\fP * objp)"

.PP
Definition at line \fB1021\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBreaddir3args::cookie\fP, \fBreaddir3args::cookieverf\fP, \fBreaddir3args::count\fP, \fBreaddir3args::dir\fP, \fBFALSE\fP, \fBTRUE\fP, \fBxdr_cookieverf3()\fP, \fBxdr_fhandle3()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_readdir3res (XDR * xdrs, \fBreaddir3res\fP * objp)"

.PP
Definition at line \fB1079\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_OK\fP, \fBreaddir3res::readdir3res_u\fP, \fBreaddir3res::resfail\fP, \fBreaddir3res::resok\fP, \fBreaddir3res::status\fP, \fBTRUE\fP, \fBxdr_nfsstat3()\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_readdir3resok()\fP\&.
.SS "bool_t xdr_readdir3resok (XDR * xdrs, \fBreaddir3resok\fP * objp)"

.PP
Definition at line \fB1065\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBreaddir3resok::cookieverf\fP, \fBreaddir3resok::dir_attributes\fP, \fBFALSE\fP, \fBreaddir3resok::reply\fP, \fBTRUE\fP, \fBxdr_cookieverf3()\fP, \fBxdr_dirlist3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_readdirplus3args (XDR * xdrs, \fBreaddirplus3args\fP * objp)"

.PP
Definition at line \fB1099\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBreaddirplus3args::cookie\fP, \fBreaddirplus3args::cookieverf\fP, \fBreaddirplus3args::dir\fP, \fBreaddirplus3args::dircount\fP, \fBFALSE\fP, \fBreaddirplus3args::maxcount\fP, \fBTRUE\fP, \fBxdr_cookieverf3()\fP, \fBxdr_fhandle3()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_readdirplus3res (XDR * xdrs, \fBreaddirplus3res\fP * objp)"

.PP
Definition at line \fB1163\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_OK\fP, \fBreaddirplus3res::readdirplus3res_u\fP, \fBreaddirplus3res::resfail\fP, \fBreaddirplus3res::resok\fP, \fBreaddirplus3res::status\fP, \fBTRUE\fP, \fBxdr_nfsstat3()\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_readdirplus3resok()\fP\&.
.SS "bool_t xdr_readdirplus3resok (XDR * xdrs, \fBreaddirplus3resok\fP * objp)"

.PP
Definition at line \fB1149\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBreaddirplus3resok::cookieverf\fP, \fBreaddirplus3resok::dir_attributes\fP, \fBFALSE\fP, \fBreaddirplus3resok::reply\fP, \fBTRUE\fP, \fBxdr_cookieverf3()\fP, \fBxdr_dirlistplus3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_readlink3res (XDR * xdrs, \fBreadlink3res\fP * objp)"

.PP
Definition at line \fB674\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_OK\fP, \fBreadlink3res::readlink3res_u\fP, \fBreadlink3res::resfail\fP, \fBreadlink3res::resok\fP, \fBreadlink3res::status\fP, \fBTRUE\fP, \fBxdr_nfsstat3()\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_readlink3resok()\fP\&.
.SS "bool_t xdr_readlink3resok (XDR * xdrs, \fBreadlink3resok\fP * objp)"

.PP
Definition at line \fB662\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBreadlink3resok::data\fP, \fBFALSE\fP, \fBreadlink3resok::symlink_attributes\fP, \fBTRUE\fP, \fBxdr_nfspath3()\fP, and \fBxdr_post_op_attr()\fP\&.
.SS "bool_t xdr_rename3args (XDR * xdrs, \fBrename3args\fP * objp)"

.PP
Definition at line \fB937\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBrename3args::from\fP, \fBrename3args::to\fP, \fBTRUE\fP, and \fBxdr_diropargs3()\fP\&.
.SS "bool_t xdr_rename3res (XDR * xdrs, \fBrename3res\fP * objp)"

.PP
Definition at line \fB961\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBrename3res::rename3res_u\fP, \fBrename3res::res\fP, \fBrename3res::status\fP, \fBTRUE\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_rename3wcc()\fP\&.
.SS "bool_t xdr_rename3wcc (XDR * xdrs, \fBrename3wcc\fP * objp)"

.PP
Definition at line \fB949\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBrename3wcc::fromdir_wcc\fP, \fBrename3wcc::todir_wcc\fP, \fBTRUE\fP, and \fBxdr_wcc_data()\fP\&.
.SS "bool_t xdr_sattr3 (XDR * xdrs, \fBsattr3\fP * objp)"

.PP
Definition at line \fB448\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBsattr3::atime\fP, \fBFALSE\fP, \fBsattr3::gid\fP, \fBsattr3::mode\fP, \fBsattr3::mtime\fP, \fBsattr3::size\fP, \fBTRUE\fP, \fBsattr3::uid\fP, \fBxdr_set_time()\fP, \fBxdr_set_uint32()\fP, and \fBxdr_set_uint64()\fP\&.
.SS "bool_t xdr_sattrguard3 (XDR * xdrs, \fBsattrguard3\fP * objp)"

.PP
Definition at line \fB550\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBsattrguard3::check\fP, \fBsattrguard3::ctime\fP, \fBFALSE\fP, \fBsattrguard3::sattrguard3_u\fP, \fBTRUE\fP, and \fBxdr_nfstime3()\fP\&.
.SS "bool_t xdr_set_time (XDR * xdrs, \fBset_time\fP * objp)"

.PP
Definition at line \fB430\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBset_time::set\fP, \fBset_time::set_time_u\fP, \fBSET_TO_CLIENT_TIME\fP, \fBset_time::time\fP, \fBTRUE\fP, \fBxdr_nfstime3()\fP, and \fBxdr_time_how()\fP\&.
.SS "bool_t xdr_set_uint32 (XDR * xdrs, \fBset_uint32\fP * objp)"

.PP
Definition at line \fB384\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBset_uint32::set\fP, \fBset_uint32::set_uint32_u\fP, \fBTRUE\fP, \fBset_uint32::val\fP, and \fBxdr_uint32()\fP\&.
.SS "bool_t xdr_set_uint64 (XDR * xdrs, \fBset_uint64\fP * objp)"

.PP
Definition at line \fB402\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBset_uint64::set\fP, \fBset_uint64::set_uint64_u\fP, \fBTRUE\fP, \fBset_uint64::val\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_setattr3args (XDR * xdrs, \fBsetattr3args\fP * objp)"

.PP
Definition at line \fB570\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBsetattr3args::guard\fP, \fBsetattr3args::new_attributes\fP, \fBsetattr3args::object\fP, \fBTRUE\fP, \fBxdr_fhandle3()\fP, \fBxdr_sattr3()\fP, and \fBxdr_sattrguard3()\fP\&.
.SS "bool_t xdr_specdata3 (XDR * xdrs, \fBspecdata3\fP * objp)"

.PP
Definition at line \fB240\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBspecdata3::major\fP, \fBspecdata3::minor\fP, \fBTRUE\fP, and \fBxdr_uint32()\fP\&.
.SS "bool_t xdr_stable_how (XDR * xdrs, \fBstable_how\fP * objp)"

.PP
Definition at line \fB744\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_symlink3args (XDR * xdrs, \fBsymlink3args\fP * objp)"

.PP
Definition at line \fB877\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBsymlink3args::symlink\fP, \fBTRUE\fP, \fBsymlink3args::where\fP, \fBxdr_diropargs3()\fP, and \fBxdr_symlinkdata3()\fP\&.
.SS "bool_t xdr_symlinkdata3 (XDR * xdrs, \fBsymlinkdata3\fP * objp)"

.PP
Definition at line \fB865\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBsymlinkdata3::symlink_attributes\fP, \fBsymlinkdata3::symlink_data\fP, \fBTRUE\fP, \fBxdr_nfspath3()\fP, and \fBxdr_sattr3()\fP\&.
.SS "bool_t xdr_time_how (XDR * xdrs, \fBtime_how\fP * objp)"

.PP
Definition at line \fB420\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_uint32 (XDR * xdrs, \fBuint32\fP * objp)"

.PP
Definition at line \fB29\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_uint64 (XDR * xdrs, \fBuint64\fP * objp)"

.PP
Definition at line \fB9\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, and \fBTRUE\fP\&.
.SS "bool_t xdr_wcc_attr (XDR * xdrs, \fBwcc_attr\fP * objp)"

.PP
Definition at line \fB318\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBwcc_attr::ctime\fP, \fBFALSE\fP, \fBwcc_attr::mtime\fP, \fBwcc_attr::size\fP, \fBTRUE\fP, \fBxdr_nfstime3()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_wcc_data (XDR * xdrs, \fBwcc_data\fP * objp)"

.PP
Definition at line \fB352\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBwcc_data::after\fP, \fBwcc_data::before\fP, \fBFALSE\fP, \fBTRUE\fP, \fBxdr_post_op_attr()\fP, and \fBxdr_pre_op_attr()\fP\&.
.SS "bool_t xdr_wccstat3 (XDR * xdrs, \fBwccstat3\fP * objp)"

.PP
Definition at line \fB514\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBwccstat3::status\fP, \fBTRUE\fP, \fBwccstat3::wcc\fP, \fBwccstat3::wccstat3_u\fP, \fBxdr_nfsstat3()\fP, and \fBxdr_wcc_data()\fP\&.
.SS "bool_t xdr_write3args (XDR * xdrs, \fBwrite3args\fP * objp)"

.PP
Definition at line \fB754\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBwrite3args::count\fP, \fBwrite3args::data\fP, \fBwrite3args::data_len\fP, \fBwrite3args::data_val\fP, \fBFALSE\fP, \fBwrite3args::file\fP, \fBwrite3args::offset\fP, \fBwrite3args::stable\fP, \fBTRUE\fP, \fBxdr_fhandle3()\fP, \fBxdr_stable_how()\fP, \fBxdr_uint32()\fP, and \fBxdr_uint64()\fP\&.
.SS "bool_t xdr_write3res (XDR * xdrs, \fBwrite3res\fP * objp)"

.PP
Definition at line \fB788\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_OK\fP, \fBwrite3res::resfail\fP, \fBwrite3res::resok\fP, \fBwrite3res::status\fP, \fBTRUE\fP, \fBwrite3res::write3res_u\fP, \fBxdr_nfsstat3()\fP, \fBxdr_wcc_data()\fP, and \fBxdr_write3resok()\fP\&.
.SS "bool_t xdr_write3resok (XDR * xdrs, \fBwrite3resok\fP * objp)"

.PP
Definition at line \fB772\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBwrite3resok::committed\fP, \fBwrite3resok::count\fP, \fBFALSE\fP, \fBwrite3resok::file_wcc\fP, \fBTRUE\fP, \fBwrite3resok::verf\fP, \fBxdr_stable_how()\fP, \fBxdr_uint32()\fP, \fBxdr_wcc_data()\fP, and \fBxdr_writeverf3()\fP\&.
.SS "bool_t xdr_writeverf3 (XDR * xdrs, \fBwriteverf3\fP objp)"

.PP
Definition at line \fB89\fP of file \fBnfs3_xdr\&.c\fP\&.
.PP
References \fBFALSE\fP, \fBNFS3_WRITEVERFSIZE\fP, and \fBTRUE\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
