.TH "nfstime3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nfstime3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32\fP \fBseconds\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBnseconds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB282\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint32\fP nfstime3::nseconds"

.PP
Definition at line \fB285\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_nfstime3()\fP\&.
.SS "\fBuint32\fP nfstime3::seconds"

.PP
Definition at line \fB284\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBNFItoNFS3attr()\fP, \fBNFS3toNFIattr()\fP, and \fBxdr_nfstime3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
