.TH "ns.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ns.c
.SH SYNOPSIS
.br
.PP
\fC#include 'base/ns\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBns_get_hostname\fP (char *srv_name)"
.br
.RI "Get hostname\&. "
.ti -1c
.RI "char * \fBns_get_host_ip\fP (void)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBns_publish\fP (char *dns_file, char *protocol, char *param_srv_name, char *srv_ip, char *port_name)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBns_unpublish\fP (char *dns_file, char *protocol, char *param_srv_name)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBns_lookup\fP (char *protocol, char *param_srv_name, char *srv_ip, char *port_name)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ns_get_host_ip (void)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
None\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBns\&.c\fP\&.
.PP
Referenced by \fBmpi_server_comm_init()\fP, and \fBtcp_server_comm_init()\fP\&.
.SS "void ns_get_hostname (char * srv_name)"

.PP
Get hostname\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIsrv_name\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBns\&.c\fP\&.
.PP
Referenced by \fBmpi_server_comm_destroy()\fP, and \fBmpi_server_comm_init()\fP\&.
.SS "int ns_lookup (char * protocol, char * param_srv_name, char * srv_ip, char * port_name)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIprotocol\fP 'TODO'\&. 
.br
\fIparam_srv_name\fP 'TODO'\&. 
.br
\fIsrv_ip\fP 'TODO'\&. 
.br
\fIport_name\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB144\fP of file \fBns\&.c\fP\&.
.PP
References \fBMPI_SERVER_DNS_FILE_DEFAULT\fP, \fBPATH_MAX\fP, and \fBTCP_SERVER_DNS_FILE_DEFAULT\fP\&.
.PP
Referenced by \fBmpi_server_down()\fP, \fBmpiClient_comm_connect()\fP, \fBtcp_server_down()\fP, and \fBtcpClient_comm_connect()\fP\&.
.SS "int ns_publish (char * dns_file, char * protocol, char * param_srv_name, char * srv_ip, char * port_name)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdns_file\fP 'TODO'\&. 
.br
\fIprotocol\fP 'TODO'\&. 
.br
\fIparam_srv_name\fP 'TODO'\&. 
.br
\fIsrv_ip\fP 'TODO'\&. 
.br
\fIport_name\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB58\fP of file \fBns\&.c\fP\&.
.PP
Referenced by \fBmpi_server_comm_init()\fP, and \fBtcp_server_comm_init()\fP\&.
.SS "int ns_unpublish (char * dns_file, char * protocol, char * param_srv_name)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdns_file\fP 'TODO'\&. 
.br
\fIprotocol\fP 'TODO'\&. 
.br
\fIparam_srv_name\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB81\fP of file \fBns\&.c\fP\&.
.PP
References \fBPATH_MAX\fP, \fBrename()\fP, and \fBunlink()\fP\&.
.PP
Referenced by \fBmpi_server_comm_destroy()\fP, and \fBtcp_server_comm_destroy()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
