.TH "path_misc.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
path_misc.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'base/path_misc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBhash\fP (__attribute__((__unused__)) char *file, __attribute__((__unused__)) int nServ)"
.br
.ti -1c
.RI "int \fBgetFirstDir\fP (char *dir, char *path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBgetSizeFactor\fP (char *name)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBgetNameFile\fP (char *file, char *dir)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBgetNamePart\fP (char *part, char *dir)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBpath_misc\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int getFirstDir (char * dir, char * path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdir\fP 'TODO'\&. 
.br
\fIpath\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBpath_misc\&.c\fP\&.
.PP
Referenced by \fBnfs3_lookup()\fP, and \fBnfs_lookup()\fP\&.
.SS "int getNameFile (char * file, char * dir)"

.PP
'TODO'\&. Get the last name of a path and erase the file name\&.
.PP
\fBParameters\fP
.RS 4
\fIfile\fP 'TODO'\&. 
.br
\fIdir\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB125\fP of file \fBpath_misc\&.c\fP\&.
.PP
Referenced by \fBnfi_nfs3_create()\fP, \fBnfi_nfs3_mkdir()\fP, \fBnfi_nfs3_remove()\fP, \fBnfi_nfs3_rmdir()\fP, \fBnfi_nfs_create()\fP, \fBnfi_nfs_mkdir()\fP, \fBnfi_nfs_remove()\fP, \fBnfi_nfs_rename()\fP, and \fBnfi_nfs_rmdir()\fP\&.
.SS "int getNamePart (char * part, char * dir)"

.PP
'TODO'\&. Get the first name of the path and erase the part name\&.
.PP
\fBParameters\fP
.RS 4
\fIpart\fP 'TODO'\&. 
.br
\fIdir\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB162\fP of file \fBpath_misc\&.c\fP\&.
.PP
Referenced by \fBXpnGetPartition()\fP\&.
.SS "int getSizeFactor (char * name)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBpath_misc\&.c\fP\&.
.PP
References \fBGB\fP, \fBKB\fP, and \fBMB\fP\&.
.PP
Referenced by \fBXpnGetInfoPartition()\fP\&.
.SS "int hash (__attribute__((__unused__)) char * file, __attribute__((__unused__)) int nServ)"

.PP
Definition at line \fB41\fP of file \fBpath_misc\&.c\fP\&.
.PP
Referenced by \fBxpn_internal_remove()\fP, \fBXpnCreateMetadata()\fP, \fBXpnGetAtribPath()\fP, and \fBXpnReadMetadata()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
