.TH "pre_op_attr" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pre_op_attr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool_t \fBpresent\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBwcc_attr\fP \fBattributes\fP"
.br
.ti -1c
.RI "} \fBpre_op_attr_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB325\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBwcc_attr\fP pre_op_attr::attributes"

.PP
Definition at line \fB330\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_pre_op_attr()\fP\&.
.SS "union  { \&.\&.\&. }  pre_op_attr::pre_op_attr_u"

.PP
Referenced by \fBxdr_pre_op_attr()\fP\&.
.SS "bool_t pre_op_attr::present"

.PP
Definition at line \fB327\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_pre_op_attr()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
