.TH "readdirplus3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
readdirplus3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfhandle3\fP \fBdir\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBcookie\fP"
.br
.ti -1c
.RI "\fBcookieverf3\fP \fBcookieverf\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBdircount\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBmaxcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB771\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint64\fP readdirplus3args::cookie"

.PP
Definition at line \fB774\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3args()\fP\&.
.SS "\fBcookieverf3\fP readdirplus3args::cookieverf"

.PP
Definition at line \fB775\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3args()\fP\&.
.SS "\fBfhandle3\fP readdirplus3args::dir"

.PP
Definition at line \fB773\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3args()\fP\&.
.SS "\fBuint32\fP readdirplus3args::dircount"

.PP
Definition at line \fB776\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3args()\fP\&.
.SS "\fBuint32\fP readdirplus3args::maxcount"

.PP
Definition at line \fB777\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
