.TH "readdirplus3res" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
readdirplus3res
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfsstat3\fP \fBstatus\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBreaddirplus3resok\fP \fBresok\fP"
.br
.ti -1c
.RI "   \fBpost_op_attr\fP \fBresfail\fP"
.br
.ti -1c
.RI "} \fBreaddirplus3res_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB807\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "union  { \&.\&.\&. }  readdirplus3res::readdirplus3res_u"

.PP
Referenced by \fBxdr_readdirplus3res()\fP\&.
.SS "\fBpost_op_attr\fP readdirplus3res::resfail"

.PP
Definition at line \fB813\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3res()\fP\&.
.SS "\fBreaddirplus3resok\fP readdirplus3res::resok"

.PP
Definition at line \fB812\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3res()\fP\&.
.SS "\fBnfsstat3\fP readdirplus3res::status"

.PP
Definition at line \fB809\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdirplus3res()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
