.TH "readdir3resok" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
readdir3resok
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpost_op_attr\fP \fBdir_attributes\fP"
.br
.ti -1c
.RI "\fBcookieverf3\fP \fBcookieverf\fP"
.br
.ti -1c
.RI "\fBdirlist3\fP \fBreply\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB752\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBcookieverf3\fP readdir3resok::cookieverf"

.PP
Definition at line \fB755\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdir3resok()\fP\&.
.SS "\fBpost_op_attr\fP readdir3resok::dir_attributes"

.PP
Definition at line \fB754\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdir3resok()\fP\&.
.SS "\fBdirlist3\fP readdir3resok::reply"

.PP
Definition at line \fB756\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdir3resok()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
