.TH "readdir3res" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
readdir3res
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnfsstat3\fP \fBstatus\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBreaddir3resok\fP \fBresok\fP"
.br
.ti -1c
.RI "   \fBpost_op_attr\fP \fBresfail\fP"
.br
.ti -1c
.RI "} \fBreaddir3res_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB760\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "union  { \&.\&.\&. }  readdir3res::readdir3res_u"

.PP
Referenced by \fBxdr_readdir3res()\fP\&.
.SS "\fBpost_op_attr\fP readdir3res::resfail"

.PP
Definition at line \fB766\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdir3res()\fP\&.
.SS "\fBreaddir3resok\fP readdir3res::resok"

.PP
Definition at line \fB765\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdir3res()\fP\&.
.SS "\fBnfsstat3\fP readdir3res::status"

.PP
Definition at line \fB762\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readdir3res()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
