.TH "readlink3resok" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
readlink3resok
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpost_op_attr\fP \fBsymlink_attributes\fP"
.br
.ti -1c
.RI "\fBnfspath3\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB515\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBnfspath3\fP readlink3resok::data"

.PP
Definition at line \fB518\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readlink3resok()\fP\&.
.SS "\fBpost_op_attr\fP readlink3resok::symlink_attributes"

.PP
Definition at line \fB517\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_readlink3resok()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
