.TH "rename3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rename3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdiropargs3\fP \fBfrom\fP"
.br
.ti -1c
.RI "\fBdiropargs3\fP \fBto\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB679\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBdiropargs3\fP rename3args::from"

.PP
Definition at line \fB681\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_rename3args()\fP\&.
.SS "\fBdiropargs3\fP rename3args::to"

.PP
Definition at line \fB682\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_rename3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
