.TH "sattr3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sattr3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBset_uint32\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBset_uint32\fP \fBuid\fP"
.br
.ti -1c
.RI "\fBset_uint32\fP \fBgid\fP"
.br
.ti -1c
.RI "\fBset_uint64\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBset_time\fP \fBatime\fP"
.br
.ti -1c
.RI "\fBset_time\fP \fBmtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB390\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBset_time\fP sattr3::atime"

.PP
Definition at line \fB396\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_sattr3()\fP\&.
.SS "\fBset_uint32\fP sattr3::gid"

.PP
Definition at line \fB394\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_sattr3()\fP\&.
.SS "\fBset_uint32\fP sattr3::mode"

.PP
Definition at line \fB392\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_create()\fP, \fBnfs3_setattr()\fP, and \fBxdr_sattr3()\fP\&.
.SS "\fBset_time\fP sattr3::mtime"

.PP
Definition at line \fB397\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_sattr3()\fP\&.
.SS "\fBset_uint64\fP sattr3::size"

.PP
Definition at line \fB395\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_sattr3()\fP\&.
.SS "\fBset_uint32\fP sattr3::uid"

.PP
Definition at line \fB393\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_sattr3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
