.TH "sattrguard3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sattrguard3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool_t \fBcheck\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBnfstime3\fP \fBctime\fP"
.br
.ti -1c
.RI "} \fBsattrguard3_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB447\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool_t sattrguard3::check"

.PP
Definition at line \fB449\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_sattrguard3()\fP\&.
.SS "\fBnfstime3\fP sattrguard3::ctime"

.PP
Definition at line \fB452\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_sattrguard3()\fP\&.
.SS "union  { \&.\&.\&. }  sattrguard3::sattrguard3_u"

.PP
Referenced by \fBxdr_sattrguard3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
