.TH "set_uint64" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_uint64
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool_t \fBset\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint64\fP \fBval\fP"
.br
.ti -1c
.RI "} \fBset_uint64_u\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB362\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool_t set_uint64::set"

.PP
Definition at line \fB364\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_set_uint64()\fP\&.
.SS "union  { \&.\&.\&. }  set_uint64::set_uint64_u"

.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_set_uint64()\fP\&.
.SS "\fBuint64\fP set_uint64::val"

.PP
Definition at line \fB367\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_set_uint64()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
