.TH "setattr3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setattr3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfhandle3\fP \fBobject\fP"
.br
.ti -1c
.RI "\fBsattr3\fP \fBnew_attributes\fP"
.br
.ti -1c
.RI "\fBsattrguard3\fP \fBguard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB457\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBsattrguard3\fP setattr3args::guard"

.PP
Definition at line \fB461\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_setattr3args()\fP\&.
.SS "\fBsattr3\fP setattr3args::new_attributes"

.PP
Definition at line \fB460\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_setattr3args()\fP\&.
.SS "\fBfhandle3\fP setattr3args::object"

.PP
Definition at line \fB459\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_setattr()\fP, and \fBxdr_setattr3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
