.TH "config.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRETSIGTYPE\fP   void"
.br
.ti -1c
.RI "#define \fBHAVE_VPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETHOSTNAME\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETTIMEOFDAY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SELECT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SOCKET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRDUP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRERROR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_PARAM_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_WAIT_H\fP   1"
.br
.ti -1c
.RI "#define \fBTIME_WITH_SYS_TIME\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DIRENT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FCNTL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_IOCTL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TIME_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PTHREAD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NETINET_IN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_RPC_RPC_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_RPC_CLNT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_RPC_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FCNTL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBPTHREAD\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE_DIRENT_H   1"

.PP
Definition at line \fB94\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_FCNTL_H   1"

.PP
Definition at line \fB97\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_FCNTL_H   1"

.PP
Definition at line \fB97\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_GETHOSTNAME   1"

.PP
Definition at line \fB50\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_GETTIMEOFDAY   1"

.PP
Definition at line \fB53\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_LIBPTHREAD   1"

.PP
Definition at line \fB150\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_MEMCMP   1"

.PP
Definition at line \fB68\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_MEMMOVE   1"

.PP
Definition at line \fB71\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_MEMSET   1"

.PP
Definition at line \fB74\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_NETINET_IN_H   1"

.PP
Definition at line \fB127\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_PTHREAD_H   1"

.PP
Definition at line \fB124\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_RPC_CLNT_H   1"

.PP
Definition at line \fB136\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_RPC_RPC_H   1"

.PP
Definition at line \fB133\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_RPC_TYPES_H   1"

.PP
Definition at line \fB139\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_SELECT   1"

.PP
Definition at line \fB56\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_SOCKET   1"

.PP
Definition at line \fB59\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_STRDUP   1"

.PP
Definition at line \fB62\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_STRERROR   1"

.PP
Definition at line \fB65\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_STRING_H   1"

.PP
Definition at line \fB109\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_STRINGS_H   1"

.PP
Definition at line \fB106\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_SYS_IOCTL_H   1"

.PP
Definition at line \fB115\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_SYS_PARAM_H   1"

.PP
Definition at line \fB85\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_SYS_TIME_H   1"

.PP
Definition at line \fB118\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_SYS_WAIT_H   1"

.PP
Definition at line \fB88\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_UNISTD_H   1"

.PP
Definition at line \fB121\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define HAVE_VPRINTF   1"

.PP
Definition at line \fB47\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define RETSIGTYPE   void"

.PP
Definition at line \fB36\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define STDC_HEADERS   1"

.PP
Definition at line \fB82\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SS "#define TIME_WITH_SYS_TIME   1"

.PP
Definition at line \fB91\fP of file \fBsrc/tcp_server/config\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
