.TH "st_mpi_server_opendir" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_mpi_server_opendir \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpi_server_ops\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB305\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char st_mpi_server_opendir::path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB307\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.PP
Referenced by \fBmpi_server_op_opendir()\fP, and \fBnfi_mpi_server_opendir()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
