.TH "st_mpi_server_preload" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_mpi_server_preload \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpi_server_ops\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstorage_path\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBvirtual_path\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBblock_size\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBopt\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB391\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int st_mpi_server_preload::block_size"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB395\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.PP
Referenced by \fBmpi_server_op_preload()\fP, and \fBnfi_mpi_server_preload()\fP\&.
.SS "char st_mpi_server_preload::opt"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB396\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.PP
Referenced by \fBnfi_mpi_server_preload()\fP\&.
.SS "char st_mpi_server_preload::storage_path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB393\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.PP
Referenced by \fBmpi_server_op_preload()\fP, and \fBnfi_mpi_server_preload()\fP\&.
.SS "char st_mpi_server_preload::virtual_path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB394\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.PP
Referenced by \fBmpi_server_op_preload()\fP, and \fBnfi_mpi_server_preload()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
