.TH "st_mpi_server_attr_req" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_mpi_server_attr_req \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpi_server_ops\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstatus\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "struct stat \fBattr\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB282\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "struct stat st_mpi_server_attr_req::attr"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB285\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.PP
Referenced by \fBmpi_server_op_getattr()\fP, \fBnfi_mpi_server_create()\fP, \fBnfi_mpi_server_getattr()\fP, and \fBnfi_mpi_server_mkdir()\fP\&.
.SS "char st_mpi_server_attr_req::status"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB284\fP of file \fBmpi_server/mpi_server_ops\&.h\fP\&.
.PP
Referenced by \fBmpi_server_op_getattr()\fP, and \fBnfi_mpi_server_getattr()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
