.TH "st_tcp_server_read_req" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_tcp_server_read_req \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_server_ops\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ssize_t \fBsize\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBlast\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB178\fP of file \fBtcp_server/tcp_server_ops\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char st_tcp_server_read_req::last"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB181\fP of file \fBtcp_server/tcp_server_ops\&.h\fP\&.
.SS "ssize_t st_tcp_server_read_req::size"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB180\fP of file \fBtcp_server/tcp_server_ops\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_read()\fP, \fBtcp_server_op_read_wos()\fP, and \fBtcp_server_op_read_ws()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
