.TH "st_tcp_server_open" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_tcp_server_open \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_server_ops\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB123\fP of file \fBtcp_server/tcp_server_ops\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char st_tcp_server_open::path"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB125\fP of file \fBtcp_server/tcp_server_ops\&.h\fP\&.
.PP
Referenced by \fBnfi_tcp_server_open()\fP, \fBtcp_server_op_open_wos()\fP, and \fBtcp_server_op_open_ws()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
