.TH "symlink3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
symlink3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdiropargs3\fP \fBwhere\fP"
.br
.ti -1c
.RI "\fBsymlinkdata3\fP \fBsymlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB647\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBsymlinkdata3\fP symlink3args::symlink"

.PP
Definition at line \fB650\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_symlink3args()\fP\&.
.SS "\fBdiropargs3\fP symlink3args::where"

.PP
Definition at line \fB649\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_symlink3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
