.TH "symlinkdata3" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
symlinkdata3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsattr3\fP \fBsymlink_attributes\fP"
.br
.ti -1c
.RI "\fBnfspath3\fP \fBsymlink_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB640\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBsattr3\fP symlinkdata3::symlink_attributes"

.PP
Definition at line \fB642\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_symlinkdata3()\fP\&.
.SS "\fBnfspath3\fP symlinkdata3::symlink_data"

.PP
Definition at line \fB643\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBxdr_symlinkdata3()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
