.TH "syscall_proxies.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
syscall_proxies.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'base/syscall_proxies\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdlsym_open\fP (char *path, int flags)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_open2\fP (char *path, int flags, mode_t mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_open64\fP (char *path, int flags, mode_t mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym___open_2\fP (char *path, int flags)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_creat\fP (const char *path, mode_t mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_ftruncate\fP (int fd, off_t length)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBdlsym_read\fP (int fd, void *\fBbuf\fP, size_t nbyte)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBdlsym_write\fP (int fd, void *\fBbuf\fP, size_t nbyte)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "off_t \fBdlsym_lseek\fP (int fd, off_t offset, int whence)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "off64_t \fBdlsym_lseek64\fP (int fd, off64_t offset, int whence)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_lxstat64\fP (int ver, const char *path, struct stat64 *\fBbuf\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_xstat64\fP (int ver, const char *path, struct stat64 *\fBbuf\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fxstat64\fP (int ver, int fd, struct stat64 *\fBbuf\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_lstat\fP (int ver, const char *path, struct stat *\fBbuf\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_stat\fP (int ver, const char *path, struct stat *\fBbuf\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fstat\fP (int ver, int fd, struct stat *\fBbuf\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fstatat\fP (int dfd, const char *path, struct stat *\fBbuf\fP, int flags)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fstatat64\fP (int dfd, const char *path, struct stat64 *\fBbuf\fP, int flags)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_close\fP (int fd)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_rename\fP (const char *old_path, const char *new_path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_unlink\fP (char *path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "DIR * \fBdlsym_opendir\fP (char *dirname)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "DIR * \fBdlsym_opendir64\fP (char *dirname)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_mkdir\fP (char *path, mode_t mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "struct dirent * \fBdlsym_readdir\fP (DIR *dirp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "struct dirent64 * \fBdlsym_readdir64\fP (DIR *dirp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_closedir\fP (DIR *dirp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_rmdir\fP (char *path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fork\fP (void)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_pipe\fP (int pipefd[2])"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_dup\fP (int fd)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_dup2\fP (int fd, int fd2)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void \fBdlsym_exit\fP (int status)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_chdir\fP (char *path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_chmod\fP (char *path, mode_t mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fchmod\fP (int fd, mode_t mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_chown\fP (char *path, uid_t owner, gid_t group)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fcntl\fP (int fd, int cmd, long arg)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_access\fP (const char *path, int mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "char * \fBdlsym_realpath\fP (const char *restrict path, char *restrict resolved_path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBdlsym_fsync\fP (int fd)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void * \fBdlsym_mmap\fP (void *addr, size_t length, int prot, int flags, int fd, off_t offset)"
.br
.RI "'TODO'\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int(* \fBreal_open\fP )(char *, int, mode_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_open64\fP )(char *, int, mode_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal___open_2\fP )(char *, int) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_creat\fP )(const char *, mode_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_close\fP )(int) = NULL"
.br
.ti -1c
.RI "ssize_t(* \fBreal_read\fP )(int, void *, size_t) = NULL"
.br
.ti -1c
.RI "ssize_t(* \fBreal_write\fP )(int, const void *, size_t) = NULL"
.br
.ti -1c
.RI "off_t(* \fBreal_lseek\fP )(int, off_t, int) = NULL"
.br
.ti -1c
.RI "off64_t(* \fBreal_lseek64\fP )(int, off64_t, int) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_ftruncate\fP )(int, off_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_stat\fP )(int, char *, struct stat *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_xstat64\fP )(int, const char *, struct stat64 *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_lstat\fP )(int, char *, struct stat *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_lxstat64\fP )(int, const char *, struct stat64 *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fstat\fP )(int, int, struct stat *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fxstat64\fP )(int, int, struct stat64 *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fstatat\fP )(int, const char *, struct stat *, int) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fstatat64\fP )(int, const char *, struct stat64 *, int) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_rename\fP )(const char *, const char *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_unlink\fP )(char *) = NULL"
.br
.ti -1c
.RI "DIR *(* \fBreal_opendir\fP )(char *) = NULL"
.br
.ti -1c
.RI "DIR *(* \fBreal_opendir64\fP )(char *) = NULL"
.br
.ti -1c
.RI "struct dirent *(* \fBreal_readdir\fP )(DIR *) = NULL"
.br
.ti -1c
.RI "struct dirent64 *(* \fBreal_readdir64\fP )(DIR *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_closedir\fP )(DIR *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_mkdir\fP )(char *, mode_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_rmdir\fP )(char *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fork\fP )(void) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_pipe\fP )(int *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_dup\fP )(int) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_dup2\fP )(int, int) = NULL"
.br
.ti -1c
.RI "void(* \fBreal_exit\fP )(int) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_chdir\fP )(char *) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_chmod\fP )(char *, mode_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fchmod\fP )(int, mode_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_chown\fP )(char *, uid_t, gid_t) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fcntl\fP )(int, int, long) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_access\fP )(const char *, int) = NULL"
.br
.ti -1c
.RI "char *(* \fBreal_realpath\fP )(const char *restrict, char *restrict) = NULL"
.br
.ti -1c
.RI "int(* \fBreal_fsync\fP )(int) = NULL"
.br
.ti -1c
.RI "void *(* \fBreal_mmap\fP )(void *, size_t, int, int, int, off_t) = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBsyscall_proxies\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int dlsym___open_2 (char * path, int flags)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB153\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal___open_2\fP\&.
.PP
Referenced by \fB__open_2()\fP\&.
.SS "int dlsym_access (const char * path, int mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB596\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_access\fP\&.
.PP
Referenced by \fBaccess()\fP\&.
.SS "int dlsym_chdir (char * path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB536\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_chdir\fP\&.
.PP
Referenced by \fBchdir()\fP\&.
.SS "int dlsym_chmod (char * path, mode_t mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB548\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_chmod\fP\&.
.PP
Referenced by \fBchmod()\fP\&.
.SS "int dlsym_chown (char * path, uid_t owner, gid_t group)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fIowner\fP 'TODO'\&. 
.br
\fIgroup\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB572\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_chown\fP\&.
.PP
Referenced by \fBchown()\fP\&.
.SS "int dlsym_close (int fd)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB344\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_close\fP\&.
.PP
Referenced by \fBclose()\fP\&.
.SS "int dlsym_closedir (DIR * dirp)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirp\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB444\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_closedir\fP\&.
.PP
Referenced by \fBclosedir()\fP\&.
.SS "int dlsym_creat (const char * path, mode_t mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB170\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_creat\fP\&.
.PP
Referenced by \fBcreat()\fP\&.
.SS "int dlsym_dup (int fd)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB496\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_dup\fP\&.
.PP
Referenced by \fBdup()\fP\&.
.SS "int dlsym_dup2 (int fd, int fd2)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIfd2\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB508\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_dup2\fP\&.
.PP
Referenced by \fBdup2()\fP\&.
.SS "void dlsym_exit (int status)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIstatus\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB520\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_exit\fP\&.
.PP
Referenced by \fBexit()\fP\&.
.SS "int dlsym_fchmod (int fd, mode_t mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB560\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_fchmod\fP\&.
.PP
Referenced by \fBfchmod()\fP\&.
.SS "int dlsym_fcntl (int fd, int cmd, long arg)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIcmd\fP 'TODO'\&. 
.br
\fIarg\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB584\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_fcntl\fP\&.
.PP
Referenced by \fBfcntl()\fP\&.
.SS "int dlsym_fork (void)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
None\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB472\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_fork\fP\&.
.PP
Referenced by \fBfork()\fP\&.
.SS "int dlsym_fstat (int ver, int fd, struct stat * buf)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIver\fP 'TODO'\&. 
.br
\fIfd\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB308\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_fstat\fP\&.
.PP
Referenced by \fB__fxstat()\fP\&.
.SS "int dlsym_fstatat (int dfd, const char * path, struct stat * buf, int flags)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdfd\fP 'TODO'\&. 
.br
\fIpath\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB320\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_fstatat\fP\&.
.SS "int dlsym_fstatat64 (int dfd, const char * path, struct stat64 * buf, int flags)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdfd\fP 'TODO'\&. 
.br
\fIpath\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB332\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_fstatat64\fP\&.
.SS "int dlsym_fsync (int fd)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB630\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_fsync\fP\&.
.PP
Referenced by \fBfsync()\fP\&.
.SS "int dlsym_ftruncate (int fd, off_t length)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIlength\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB187\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_ftruncate\fP\&.
.PP
Referenced by \fBftruncate()\fP\&.
.SS "int dlsym_fxstat64 (int ver, int fd, struct stat64 * buf)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIver\fP 'TODO'\&. 
.br
\fIfd\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB271\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_fxstat64\fP\&.
.PP
Referenced by \fB__fxstat64()\fP\&.
.SS "off_t dlsym_lseek (int fd, off_t offset, int whence)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.br
\fIwhence\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB223\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_lseek\fP\&.
.PP
Referenced by \fBlseek()\fP\&.
.SS "off64_t dlsym_lseek64 (int fd, off64_t offset, int whence)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.br
\fIwhence\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB235\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_lseek64\fP\&.
.PP
Referenced by \fBlseek64()\fP\&.
.SS "int dlsym_lstat (int ver, const char * path, struct stat * buf)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIver\fP 'TODO'\&. 
.br
\fIpath\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB284\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_lstat\fP\&.
.PP
Referenced by \fB__lxstat()\fP\&.
.SS "int dlsym_lxstat64 (int ver, const char * path, struct stat64 * buf)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIver\fP 'TODO'\&. 
.br
\fIpath\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB247\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_lxstat64\fP\&.
.PP
Referenced by \fB__lxstat64()\fP\&.
.SS "int dlsym_mkdir (char * path, mode_t mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB408\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_mkdir\fP\&.
.PP
Referenced by \fBmkdir()\fP\&.
.SS "void * dlsym_mmap (void * addr, size_t length, int prot, int flags, int fd, off_t offset)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIaddr\fP 'TODO'\&. 
.br
\fIlength\fP 'TODO'\&. 
.br
\fIprot\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.br
\fIfd\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB646\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_mmap\fP\&.
.SS "int dlsym_open (char * path, int flags)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB97\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_open\fP\&.
.SS "int dlsym_open2 (char * path, int flags, mode_t mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB115\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_open\fP\&.
.PP
Referenced by \fBopen()\fP\&.
.SS "int dlsym_open64 (char * path, int flags, mode_t mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fIflags\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB134\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_open64\fP\&.
.PP
Referenced by \fBopen64()\fP\&.
.SS "DIR * dlsym_opendir (char * dirname)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB384\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_opendir\fP\&.
.PP
Referenced by \fBopendir()\fP\&.
.SS "DIR * dlsym_opendir64 (char * dirname)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirname\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB396\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_opendir64\fP\&.
.SS "int dlsym_pipe (int pipefd[2])"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpipefd\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB484\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_pipe\fP\&.
.PP
Referenced by \fBpipe()\fP\&.
.SS "ssize_t dlsym_read (int fd, void * buf, size_t nbyte)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.br
\fInbyte\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB199\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_read\fP\&.
.PP
Referenced by \fBread()\fP\&.
.SS "struct dirent * dlsym_readdir (DIR * dirp)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirp\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB420\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_readdir\fP\&.
.PP
Referenced by \fBreaddir()\fP\&.
.SS "struct dirent64 * dlsym_readdir64 (DIR * dirp)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirp\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB432\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_readdir64\fP\&.
.PP
Referenced by \fBreaddir64()\fP\&.
.SS "char * dlsym_realpath (const char *restrict path, char *restrict resolved_path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.br
\fIresolved_path\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB613\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_realpath\fP\&.
.PP
Referenced by \fB__realpath_chk()\fP, and \fBrealpath()\fP\&.
.SS "int dlsym_rename (const char * old_path, const char * new_path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIold_path\fP 'TODO'\&. 
.br
\fInew_path\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB356\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_rename\fP\&.
.PP
Referenced by \fBrename()\fP\&.
.SS "int dlsym_rmdir (char * path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB456\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_rmdir\fP\&.
.PP
Referenced by \fBrmdir()\fP\&.
.SS "int dlsym_stat (int ver, const char * path, struct stat * buf)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIver\fP 'TODO'\&. 
.br
\fIpath\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB296\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_stat\fP\&.
.PP
Referenced by \fB__xstat()\fP\&.
.SS "int dlsym_unlink (char * path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB368\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBdebug_info\fP, and \fBreal_unlink\fP\&.
.PP
Referenced by \fBunlink()\fP\&.
.SS "ssize_t dlsym_write (int fd, void * buf, size_t nbyte)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.br
\fInbyte\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB211\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_write\fP\&.
.PP
Referenced by \fBwrite()\fP\&.
.SS "int dlsym_xstat64 (int ver, const char * path, struct stat64 * buf)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIver\fP 'TODO'\&. 
.br
\fIpath\fP 'TODO'\&. 
.br
\fIbuf\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB259\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
References \fBbuf\fP, \fBdebug_info\fP, and \fBreal_xstat64\fP\&.
.PP
Referenced by \fB__xstat64()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int(* real___open_2) (char *, int) (char *, int) = NULL"

.PP
Definition at line \fB43\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym___open_2()\fP\&.
.SS "int(* real_access) (const char *, int) (const char *, int) = NULL"

.PP
Definition at line \fB84\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_access()\fP\&.
.SS "int(* real_chdir) (char *) (char *) = NULL"

.PP
Definition at line \fB79\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_chdir()\fP\&.
.SS "int(* real_chmod) (char *, mode_t) (char *, mode_t) = NULL"

.PP
Definition at line \fB80\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_chmod()\fP\&.
.SS "int(* real_chown) (char *, uid_t, gid_t) (char *, uid_t, gid_t) = NULL"

.PP
Definition at line \fB82\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_chown()\fP\&.
.SS "int(* real_close) (int) (int) = NULL"

.PP
Definition at line \fB45\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_close()\fP\&.
.SS "int(* real_closedir) (DIR *) (DIR *) = NULL"

.PP
Definition at line \fB69\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_closedir()\fP\&.
.SS "int(* real_creat) (const char *, mode_t) (const char *, mode_t) = NULL"

.PP
Definition at line \fB44\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_creat()\fP\&.
.SS "int(* real_dup) (int) (int) = NULL"

.PP
Definition at line \fB76\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_dup()\fP\&.
.SS "int(* real_dup2) (int, int) (int, int) = NULL"

.PP
Definition at line \fB77\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_dup2()\fP\&.
.SS "void(* real_exit) (int) (int) = NULL"

.PP
Definition at line \fB78\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_exit()\fP\&.
.SS "int(* real_fchmod) (int, mode_t) (int, mode_t) = NULL"

.PP
Definition at line \fB81\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fchmod()\fP\&.
.SS "int(* real_fcntl) (int, int, long) (int, int, long) = NULL"

.PP
Definition at line \fB83\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fcntl()\fP\&.
.SS "int(* real_fork) (void) (void) = NULL"

.PP
Definition at line \fB74\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fork()\fP\&.
.SS "int(* real_fstat) (int, int, struct stat *) (int, int, struct stat *) = NULL"

.PP
Definition at line \fB57\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fstat()\fP\&.
.SS "int(* real_fstatat) (int, const char *, struct stat *, int) (int, const char *, struct stat *, int) = NULL"

.PP
Definition at line \fB59\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fstatat()\fP\&.
.SS "int(* real_fstatat64) (int, const char *, struct stat64 *, int) (int, const char *, struct stat64 *, int) = NULL"

.PP
Definition at line \fB60\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fstatat64()\fP\&.
.SS "int(* real_fsync) (int) (int) = NULL"

.PP
Definition at line \fB86\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fsync()\fP\&.
.SS "int(* real_ftruncate) (int, off_t) (int, off_t) = NULL"

.PP
Definition at line \fB51\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_ftruncate()\fP\&.
.SS "int(* real_fxstat64) (int, int, struct stat64 *) (int, int, struct stat64 *) = NULL"

.PP
Definition at line \fB58\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_fxstat64()\fP\&.
.SS "off_t(* real_lseek) (int, off_t, int) (int, off_t, int) = NULL"

.PP
Definition at line \fB49\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_lseek()\fP\&.
.SS "off64_t(* real_lseek64) (int, off64_t, int) (int, off64_t, int) = NULL"

.PP
Definition at line \fB50\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_lseek64()\fP\&.
.SS "int(* real_lstat) (int, char *, struct stat *) (int, char *, struct stat *) = NULL"

.PP
Definition at line \fB55\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_lstat()\fP\&.
.SS "int(* real_lxstat64) (int, const char *, struct stat64 *) (int, const char *, struct stat64 *) = NULL"

.PP
Definition at line \fB56\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_lxstat64()\fP\&.
.SS "int(* real_mkdir) (char *, mode_t) (char *, mode_t) = NULL"

.PP
Definition at line \fB71\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_mkdir()\fP\&.
.SS "void *(* real_mmap) (void *, size_t, int, int, int, off_t) (void *, size_t, int, int, int, off_t) = NULL"

.PP
Definition at line \fB87\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_mmap()\fP\&.
.SS "int(* real_open) (char *, int, mode_t) (char *, int, mode_t) = NULL"

.PP
Definition at line \fB41\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_open()\fP, and \fBdlsym_open2()\fP\&.
.SS "int(* real_open64) (char *, int, mode_t) (char *, int, mode_t) = NULL"

.PP
Definition at line \fB42\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_open64()\fP\&.
.SS "DIR *(* real_opendir) (char *) (char *) = NULL"

.PP
Definition at line \fB65\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_opendir()\fP\&.
.SS "DIR *(* real_opendir64) (char *) (char *) = NULL"

.PP
Definition at line \fB66\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_opendir64()\fP\&.
.SS "int(* real_pipe) (int *) (int *) = NULL"

.PP
Definition at line \fB75\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_pipe()\fP\&.
.SS "ssize_t(* real_read) (int, void *, size_t) (int, void *, size_t) = NULL"

.PP
Definition at line \fB47\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_read()\fP, and \fBtcpClient_read_data()\fP\&.
.SS "struct dirent *(* real_readdir) (DIR *) (DIR *) = NULL"

.PP
Definition at line \fB66\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_readdir()\fP\&.
.SS "struct dirent64 *(* real_readdir64) (DIR *) (DIR *) = NULL"

.PP
Definition at line \fB66\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_readdir64()\fP\&.
.SS "char *(* real_realpath) (const char *restrict, char *restrict) (const char * restrict, char * restrict) = NULL"

.PP
Definition at line \fB85\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_realpath()\fP\&.
.SS "int(* real_rename) (const char *, const char *) (const char *, const char *) = NULL"

.PP
Definition at line \fB62\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_rename()\fP\&.
.SS "int(* real_rmdir) (char *) (char *) = NULL"

.PP
Definition at line \fB72\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_rmdir()\fP\&.
.SS "int(* real_stat) (int, char *, struct stat *) (int, char *, struct stat *) = NULL"

.PP
Definition at line \fB53\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_stat()\fP\&.
.SS "int(* real_unlink) (char *) (char *) = NULL"

.PP
Definition at line \fB63\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_unlink()\fP\&.
.SS "ssize_t(* real_write) (int, const void *, size_t) (int, const void *, size_t) = NULL"

.PP
Definition at line \fB48\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_write()\fP, and \fBtcpClient_write_data()\fP\&.
.SS "int(* real_xstat64) (int, const char *, struct stat64 *) (int, const char *, struct stat64 *) = NULL"

.PP
Definition at line \fB54\fP of file \fBsyscall_proxies\&.c\fP\&.
.PP
Referenced by \fBdlsym_xstat64()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
