.TH "tcp_server_d2xpn.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_server_d2xpn.h \- Header file to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/param\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/file\&.h>\fP
.br
\fC#include <sys/fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/errno\&.h>\fP
.br
\fC#include 'all_system\&.h'\fP
.br
\fC#include 'base/utils\&.h'\fP
.br
\fC#include 'tcp_server_params\&.h'\fP
.br
\fC#include 'tcp_server_ops\&.h'\fP
.br
\fC#include 'xpn\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPRELOAD_SYNC\fP   0"
.br
.ti -1c
.RI "#define \fBPRELOAD_ASYNC\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtcp_server_d2xpn\fP (\fBtcp_server_param_st\fP *\fBparams\fP, char *origen, char *destino)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file to 'TODO'\&. 

Header file to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBtcp_server_d2xpn\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define PRELOAD_ASYNC   1"

.PP
Definition at line \fB55\fP of file \fBtcp_server_d2xpn\&.h\fP\&.
.SS "#define PRELOAD_SYNC   0"

.PP
Definition at line \fB54\fP of file \fBtcp_server_d2xpn\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int tcp_server_d2xpn (\fBtcp_server_param_st\fP * params, char * origen, char * destino)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIparams\fP 'TODO'\&. 
.br
\fIorigen\fP 'TODO'\&. 
.br
\fIdestino\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB146\fP of file \fBtcp_server_d2xpn\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBmpi_server_param_st::dirbase\fP, \fBmylock()\fP, \fBmyunlock()\fP, \fBO_CREAT\fP, \fBO_RDONLY\fP, \fBO_TRUNC\fP, \fBO_WRONLY\fP, \fBopen()\fP, \fBparams\fP, \fBPATH_MAX\fP, \fBmpi_server_param_st::rank\fP, \fBst\fP, \fBTCP_SERVER_PATH_DEFAULT\fP, \fBxpn_init()\fP, and \fBxpn_open()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
