.TH "tcp_server_param_st" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_server_param_st \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_server_params\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBrank\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBport_name\fP [\fBTCP_MAX_PORT_NAME\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBsrv_name\fP [\fBTCP_MAX_PORT_NAME\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBname\fP [\fBTCP_MAX_PORT_NAME\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBport\fP [\fBTCP_MAX_PORT_NAME\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBIOsize\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBdirbase\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBdns_file\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char \fBshutdown_file\fP [\fBPATH_MAX\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBthread_mode\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBmosquitto_mode\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBmosquitto_qos\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBclient\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBglobal_sock\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBargc\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "char ** \fBargv\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB106\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "tcp_server_param_st::argc"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB144\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::argv"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB145\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::client"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB140\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.PP
Referenced by \fBtcp_server_up()\fP\&.
.SS "tcp_server_param_st::dirbase"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB118\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::dns_file"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB119\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.PP
Referenced by \fBtcp_server_down()\fP\&.
.SS "tcp_server_param_st::global_sock"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB141\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::IOsize"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB116\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::mosquitto_mode"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB126\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::mosquitto_qos"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB127\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::name"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB114\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::port"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB115\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::port_name"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB111\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::rank"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB110\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::shutdown_file"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB120\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.PP
Referenced by \fBtcp_server_down()\fP\&.
.SS "tcp_server_param_st::size"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB109\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::srv_name"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB112\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.SS "tcp_server_param_st::thread_mode"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB123\fP of file \fBtcp_server/tcp_server_params\&.h\fP\&.
.PP
Referenced by \fBtcp_server_down()\fP, and \fBtcp_server_up()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
