.TH "tcp_server.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_server.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'all_system\&.h'\fP
.br
\fC#include 'base/utils\&.h'\fP
.br
\fC#include 'base/ns\&.h'\fP
.br
\fC#include 'tcp_server/tcp_server_params\&.h'\fP
.br
\fC#include 'tcp_server/tcp_server_ops\&.h'\fP
.br
\fC#include 'base/workers\&.h'\fP
.br
\fC#include 'tcp_server/tcp_server_comm\&.h'\fP
.br
\fC#include 'tcp_server/tcp_server_d2xpn\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtcp_server_run\fP (struct \fBst_th\fP th)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void \fBtcp_server_dispatcher\fP (struct \fBst_th\fP th)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBtcp_server_up\fP (void)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBtcp_server_down\fP (void)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtcp_server_param_st\fP \fBparams\fP"
.br
.ti -1c
.RI "\fBworker_t\fP \fBworker\fP"
.br
.ti -1c
.RI "int \fBthe_end\fP = 0"
.br
.ti -1c
.RI "char \fBserv_name\fP [HOST_NAME_MAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBtcp_server\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB333\fP of file \fBtcp_server\&.c\fP\&.
.PP
References \fBparams\fP, \fBserv_name\fP, \fBtcp_server_down()\fP, \fBtcp_server_params_get()\fP, \fBtcp_server_params_show()\fP, \fBtcp_server_params_show_usage()\fP, and \fBtcp_server_up()\fP\&.
.SS "void tcp_server_dispatcher (struct \fBst_th\fP th)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIth\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB83\fP of file \fBtcp_server\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBFALSE\fP, \fBst_th::function\fP, \fBst_th::id\fP, \fBst_th::params\fP, \fBparams\fP, \fBst_th::rank_client_id\fP, \fBst_th::sd\fP, \fBtcp_server_comm_close()\fP, \fBtcp_server_comm_read_operation()\fP, \fBTCP_SERVER_DISCONNECT\fP, \fBTCP_SERVER_FINALIZE\fP, \fBtcp_server_run()\fP, \fBthe_end\fP, \fBst_th::type_op\fP, and \fBst_th::wait4me\fP\&.
.PP
Referenced by \fBtcp_server_up()\fP\&.
.SS "int tcp_server_down (void)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
None\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB249\fP of file \fBtcp_server\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBdebug_msg_init()\fP, \fBtcp_server_param_st::dns_file\fP, \fBns_lookup()\fP, \fBparams\fP, \fBst_th::sd\fP, \fBserv_name\fP, \fBtcp_server_param_st::shutdown_file\fP, \fBtcp_server_comm_close()\fP, \fBtcp_server_comm_connect()\fP, \fBtcp_server_comm_destroy()\fP, \fBtcp_server_comm_init()\fP, \fBtcp_server_comm_write_data()\fP, \fBTCP_SERVER_FINALIZE\fP, \fBtcp_server_param_st::thread_mode\fP, \fBworker\fP, \fBworkers_destroy()\fP, and \fBworkers_init()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void tcp_server_run (struct \fBst_th\fP th)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIth\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB65\fP of file \fBtcp_server\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBst_th::id\fP, \fBtcp_server_do_operation()\fP, \fBtcp_server_op2string()\fP, \fBthe_end\fP, and \fBst_th::type_op\fP\&.
.PP
Referenced by \fBtcp_server_dispatcher()\fP\&.
.SS "int tcp_server_up (void)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
None\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB157\fP of file \fBtcp_server\&.c\fP\&.
.PP
References \fBtcp_server_param_st::client\fP, \fBdebug_info\fP, \fBdebug_msg_init()\fP, \fBFALSE\fP, \fBst_th::function\fP, \fBst_th::params\fP, \fBparams\fP, \fBst_th::rank_client_id\fP, \fBst_th::sd\fP, \fBserv_name\fP, \fBtcp_server_comm_accept()\fP, \fBtcp_server_comm_destroy()\fP, \fBtcp_server_comm_init()\fP, \fBtcp_server_dispatcher()\fP, \fBthe_end\fP, \fBtcp_server_param_st::thread_mode\fP, \fBst_th::type_op\fP, \fBst_th::wait4me\fP, \fBworker\fP, \fBworkers_destroy()\fP, \fBworkers_init()\fP, and \fBworkers_launch()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBtcp_server_param_st\fP params"

.PP
Definition at line \fB47\fP of file \fBtcp_server\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBtcp_server_dispatcher()\fP, \fBtcp_server_down()\fP, and \fBtcp_server_up()\fP\&.
.SS "char serv_name[HOST_NAME_MAX]"

.PP
Definition at line \fB50\fP of file \fBtcp_server\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBtcp_server_down()\fP, and \fBtcp_server_up()\fP\&.
.SS "int the_end = 0"

.PP
Definition at line \fB49\fP of file \fBtcp_server\&.c\fP\&.
.PP
Referenced by \fBtcp_server_dispatcher()\fP, \fBtcp_server_run()\fP, and \fBtcp_server_up()\fP\&.
.SS "\fBworker_t\fP worker"

.PP
Definition at line \fB48\fP of file \fBtcp_server\&.c\fP\&.
.PP
Referenced by \fBtcp_server_down()\fP, and \fBtcp_server_up()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
