.TH "tcp_server_params.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_server_params.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tcp_server_params\&.h'\fP
.br
\fC#include 'base/ns\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtcp_server_params_show\fP (\fBtcp_server_param_st\fP *\fBparams\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void \fBtcp_server_params_show_usage\fP (void)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBtcp_server_params_get\fP (\fBtcp_server_param_st\fP *\fBparams\fP, int argc, char *argv[])"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBtcp_server_params\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int tcp_server_params_get (\fBtcp_server_param_st\fP * params, int argc, char * argv[])"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIparams\fP 'TODO'\&. 
.br
\fIargc\fP 'TODO'\&. 
.br
\fIargv\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBtcp_server_params\&.c\fP\&.
.PP
References \fBmpi_server_param_st::argc\fP, \fBmpi_server_param_st::argv\fP, \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBmpi_server_param_st::dirbase\fP, \fBmpi_server_param_st::dns_file\fP, \fBparams\fP, \fBmpi_server_param_st::port_name\fP, \fBmpi_server_param_st::rank\fP, \fBmpi_server_param_st::shutdown_file\fP, \fBmpi_server_param_st::size\fP, \fBmpi_server_param_st::srv_name\fP, \fBTCP_MAX_PORT_NAME\fP, \fBTCP_SERVER_DIRBASE_DEFAULT\fP, \fBTCP_SERVER_DNS_FILE_DEFAULT\fP, \fBTCP_SERVER_IOSIZE_DEFAULT\fP, \fBTCP_SERVER_PORT_DEFAULT\fP, \fBTH_NOT\fP, \fBTH_OP\fP, \fBTH_POOL\fP, and \fBmpi_server_param_st::thread_mode\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void tcp_server_params_show (\fBtcp_server_param_st\fP * params)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIparams\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBtcp_server_params\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBmpi_server_param_st::dirbase\fP, \fBmpi_server_param_st::dns_file\fP, \fBparams\fP, \fBmpi_server_param_st::shutdown_file\fP, \fBTH_NOT\fP, \fBTH_OP\fP, \fBTH_POOL\fP, and \fBmpi_server_param_st::thread_mode\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void tcp_server_params_show_usage (void)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
None\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB76\fP of file \fBtcp_server_params\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, and \fBDEBUG_END\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
