.TH "time_misc.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
time_misc.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'base/time_misc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTIME_MISC_Timer\fP (struct timeval *t)"
.br
.RI "Get a timestamp 't' at current time\&. "
.ti -1c
.RI "void \fBTIME_MISC_DiffTime\fP (struct timeval *to, struct timeval *tn, struct timeval *dif)"
.br
.RI "Compute 'dig = tn - to'\&. "
.ti -1c
.RI "void \fBTIME_MISC_AddTime\fP (struct timeval *to, struct timeval *tn, struct timeval *\fBsum\fP)"
.br
.RI "Compute 'sum = tn + to'\&. "
.ti -1c
.RI "float \fBTIME_MISC_TimevaltoFloat\fP (struct timeval *timet)"
.br
.RI "Return a timestamp as seconds\&. "
.ti -1c
.RI "float \fBTIME_MISC_TimevaltoMicro\fP (struct timeval *timet)"
.br
.RI "Return a timestamp as microseconds\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBtime_misc\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void TIME_MISC_AddTime (struct timeval * to, struct timeval * tn, struct timeval * sum)"

.PP
Compute 'sum = tn + to'\&. 
.PP
\fBParameters\fP
.RS 4
\fIto\fP initial instant\&. 
.br
\fItn\fP final instant\&. 
.br
\fIsum\fP the addition value ('tn + to')\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB70\fP of file \fBtime_misc\&.c\fP\&.
.PP
References \fBsum\fP, and \fBUSECPSEC\fP\&.
.SS "void TIME_MISC_DiffTime (struct timeval * to, struct timeval * tn, struct timeval * dif)"

.PP
Compute 'dig = tn - to'\&. 
.PP
\fBParameters\fP
.RS 4
\fIto\fP initial instant\&. 
.br
\fItn\fP final instant\&. 
.br
\fIdif\fP the substaction value ('tn - to')\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBtime_misc\&.c\fP\&.
.PP
References \fBUSECPSEC\fP\&.
.PP
Referenced by \fBmpi_server_comm_init()\fP, and \fBtcp_server_comm_init()\fP\&.
.SS "void TIME_MISC_Timer (struct timeval * t)"

.PP
Get a timestamp 't' at current time\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP the timestamp\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBtime_misc\&.c\fP\&.
.PP
Referenced by \fBmpi_server_comm_init()\fP, and \fBtcp_server_comm_init()\fP\&.
.SS "float TIME_MISC_TimevaltoFloat (struct timeval * timet)"

.PP
Return a timestamp as seconds\&. 
.PP
\fBParameters\fP
.RS 4
\fItimet\fP the timestamp\&. 
.RE
.PP
\fBReturns\fP
.RS 4
timestamp as seconds\&. 
.RE
.PP

.PP
Definition at line \fB81\fP of file \fBtime_misc\&.c\fP\&.
.PP
References \fBUSECPSEC\fP\&.
.PP
Referenced by \fBmpi_server_comm_init()\fP, and \fBtcp_server_comm_init()\fP\&.
.SS "float TIME_MISC_TimevaltoMicro (struct timeval * timet)"

.PP
Return a timestamp as microseconds\&. 
.PP
\fBParameters\fP
.RS 4
\fItimet\fP the timestamp\&. 
.RE
.PP
\fBReturns\fP
.RS 4
timestamp as microseconds\&. 
.RE
.PP

.PP
Definition at line \fB86\fP of file \fBtime_misc\&.c\fP\&.
.PP
References \fBUSECPSEC\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
