.TH "workers_ondemand.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
workers_ondemand.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'workers_ondemand\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBworker_run\fP (void *arg)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBworker_ondemand_init\fP (\fBworker_ondemand_t\fP *w)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBworker_ondemand_launch\fP (\fBworker_ondemand_t\fP *w, struct \fBst_th\fP *th_arg, void(*worker_function)(struct \fBst_th\fP))"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBworker_ondemand_wait\fP (struct \fBst_th\fP *th_arg)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void \fBworkers_ondemand_destroy\fP (\fBworker_ondemand_t\fP *w)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBworkers_ondemand\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int worker_ondemand_init (\fBworker_ondemand_t\fP * w)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIw\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB112\fP of file \fBworkers_ondemand\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBTRUE\fP, and \fBst_th::w\fP\&.
.PP
Referenced by \fBworkers_init()\fP\&.
.SS "int worker_ondemand_launch (\fBworker_ondemand_t\fP * w, struct \fBst_th\fP * th_arg, void(*)(struct \fBst_th\fP) worker_function)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIw\fP 'TODO'\&. 
.br
\fIth_arg\fP 'TODO'\&. 
.br
\fIworker_function\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB128\fP of file \fBworkers_ondemand\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_error\fP, \fBdebug_info\fP, \fBst_th::function\fP, \fBst_th::id\fP, \fBSTACK_SIZE\fP, \fBst_th::th_worker\fP, \fBTRUE\fP, \fBst_th::v\fP, \fBst_th::w\fP, and \fBworker_run()\fP\&.
.PP
Referenced by \fBworkers_launch()\fP\&.
.SS "int worker_ondemand_wait (struct \fBst_th\fP * th_arg)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIth_arg\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB175\fP of file \fBworkers_ondemand\&.c\fP\&.
.PP
References \fBst_th::c_wait\fP, \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBst_th::m_wait\fP, \fBst_th::r_wait\fP, and \fBTRUE\fP\&.
.PP
Referenced by \fBworkers_wait()\fP\&.
.SS "void * worker_run (void * arg)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIarg\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB49\fP of file \fBworkers_ondemand\&.c\fP\&.
.PP
References \fBworker_ondemand_t::busy_worker\fP, \fBworker_ondemand_t::c_nworkers\fP, \fBst_th::c_wait\fP, \fBworker_ondemand_t::c_worker\fP, \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_info\fP, \fBFALSE\fP, \fBst_th::function\fP, \fBst_th::m_wait\fP, \fBworker_ondemand_t::m_worker\fP, \fBworker_ondemand_t::n_workers\fP, \fBst_th::r_wait\fP, \fBTRUE\fP, \fBst_th::v\fP, \fBst_th::w\fP, and \fBst_th::wait4me\fP\&.
.PP
Referenced by \fBworker_ondemand_launch()\fP\&.
.SS "void workers_ondemand_destroy (\fBworker_ondemand_t\fP * w)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIw\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB193\fP of file \fBworkers_ondemand\&.c\fP\&.
.PP
References \fBDEBUG_BEGIN\fP, \fBDEBUG_END\fP, \fBdebug_info\fP, and \fBst_th::w\fP\&.
.PP
Referenced by \fBworkers_destroy()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
