.TH "worker_pool_t" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
worker_pool_t \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <workers_pool\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBm_pool\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "pthread_cond_t \fBc_pool_no_full\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "pthread_cond_t \fBc_poll_no_empty\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "pthread_mutex_t \fBm_pool_end\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBPOOL_MAX_THREADS\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "pthread_t * \fBthid\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "struct \fBst_th\fP \fBoperations_buffer\fP [\fBMAX_OPERATIONS\fP]"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBn_operation\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBdeq_pos\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBenq_pos\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBpool_end\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB75\fP of file \fBworkers_pool\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "worker_pool_t::c_poll_no_empty"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB79\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::c_pool_no_full"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB78\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::deq_pos"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB87\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::enq_pos"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB88\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::m_pool"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB77\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::m_pool_end"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB80\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::n_operation"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB86\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::operations_buffer"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB85\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::pool_end"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB89\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::POOL_MAX_THREADS"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB82\fP of file \fBworkers_pool\&.h\fP\&.
.SS "worker_pool_t::thid"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB83\fP of file \fBworkers_pool\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
