.TH "worker_t" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
worker_t \- This is a struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <workers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBworker_ondemand_t\fP \fBw1\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "\fBworker_pool_t\fP \fBw2\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBthread_mode\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a struct\&. 


.PP
Definition at line \fB66\fP of file \fBworkers\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "worker_t::thread_mode"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB70\fP of file \fBworkers\&.h\fP\&.
.PP
Referenced by \fBworkers_destroy()\fP, \fBworkers_init()\fP, \fBworkers_launch()\fP, and \fBworkers_wait()\fP\&.
.SS "worker_t::w1"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB68\fP of file \fBworkers\&.h\fP\&.
.PP
Referenced by \fBworkers_destroy()\fP, \fBworkers_init()\fP, and \fBworkers_launch()\fP\&.
.SS "worker_t::w2"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB69\fP of file \fBworkers\&.h\fP\&.
.PP
Referenced by \fBworkers_destroy()\fP, \fBworkers_init()\fP, and \fBworkers_launch()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
