.TH "write3args" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
write3args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nfs3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfhandle3\fP \fBfile\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBcount\fP"
.br
.ti -1c
.RI "\fBstable_how\fP \fBstable\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   u_int \fBdata_len\fP"
.br
.ti -1c
.RI "   char * \fBdata_val\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB573\fP of file \fBnfs3\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint32\fP write3args::count"

.PP
Definition at line \fB577\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_write()\fP, and \fBxdr_write3args()\fP\&.
.SS "struct  { \&.\&.\&. }  write3args::data"

.PP
Referenced by \fBnfs3_write()\fP, and \fBxdr_write3args()\fP\&.
.SS "u_int write3args::data_len"

.PP
Definition at line \fB581\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_write()\fP, and \fBxdr_write3args()\fP\&.
.SS "char* write3args::data_val"

.PP
Definition at line \fB582\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_write()\fP, and \fBxdr_write3args()\fP\&.
.SS "\fBfhandle3\fP write3args::file"

.PP
Definition at line \fB575\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_write()\fP, and \fBxdr_write3args()\fP\&.
.SS "\fBuint64\fP write3args::offset"

.PP
Definition at line \fB576\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_write()\fP, and \fBxdr_write3args()\fP\&.
.SS "\fBstable_how\fP write3args::stable"

.PP
Definition at line \fB578\fP of file \fBnfs3\&.h\fP\&.
.PP
Referenced by \fBnfs3_write()\fP, and \fBxdr_write3args()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
