.TH "xpn-ls.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn-ls.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/param\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/file\&.h>\fP
.br
\fC#include <sys/fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/errno\&.h>\fP
.br
\fC#include <pwd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'xpn\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNFSMAXPATHLEN\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBget_perm\fP (int attr, char *attrstr)"
.br
.ti -1c
.RI "void \fBdel_slash\fP (char *path)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NFSMAXPATHLEN   1024"

.PP
Definition at line \fB35\fP of file \fBxpn\-ls\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void del_slash (char * path)"

.PP
Definition at line \fB52\fP of file \fBxpn\-ls\&.c\fP\&.
.PP
References \fBNFSMAXPATHLEN\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void get_perm (int attr, char * attrstr)"

.PP
Definition at line \fB37\fP of file \fBxpn\-ls\&.c\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB80\fP of file \fBxpn\-ls\&.c\fP\&.
.PP
References \fBdel_slash()\fP, \fBexit()\fP, \fBget_perm()\fP, \fBNFSMAXPATHLEN\fP, \fBst\fP, \fBxpn_closedir()\fP, \fBxpn_destroy()\fP, \fBxpn_init()\fP, \fBxpn_opendir()\fP, \fBxpn_readdir()\fP, and \fBxpn_stat()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
