.TH "xpn-rm.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn-rm.c
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include 'xpn\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (char *\fBprogram_name\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB36\fP of file \fBxpn\-rm\&.c\fP\&.
.PP
References \fBexit()\fP, \fBunlink()\fP, \fBusage()\fP, \fBxpn_destroy()\fP, \fBxpn_init()\fP, and \fBxpn_unlink()\fP\&.
.SS "void usage (char * program_name)"

.PP
Definition at line \fB31\fP of file \fBxpn\-rm\&.c\fP\&.
.PP
References \fBprogram_name\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
