.TH "xpn-rmdir.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn-rmdir.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/param\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/file\&.h>\fP
.br
\fC#include <sys/fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/errno\&.h>\fP
.br
\fC#include 'xpn\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB32\fP of file \fBxpn\-rmdir\&.c\fP\&.
.PP
References \fBexit()\fP, \fBxpn_destroy()\fP, \fBxpn_init()\fP, and \fBxpn_rmdir()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
