.TH "xpn_stdio.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_stdio.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'xpn\&.h'\fP
.br
\fC#include 'xpn_client/xpn/xpn_simple/xpn_simple_lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "FILE * \fBxpn_fopen\fP (const char *name, const char *mode)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_fclose\fP (FILE *fp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "size_t \fBxpn_fread\fP (void *ptr, size_t size, size_t nmemb, register FILE *stream)"
.br
.ti -1c
.RI "size_t \fBxpn_fwrite\fP (const void *ptr, size_t size, size_t nmemb, register FILE *stream)"
.br
.ti -1c
.RI "int \fBxpn_fflush\fP (FILE *stream)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_fseek\fP (FILE *stream, long int offset, int whence)"
.br
.ti -1c
.RI "long \fBxpn_ftell\fP (FILE *stream)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void \fBxpn_rewind\fP (FILE *stream)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_preload\fP (const char *virtual_path, const char *storage_path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_flush\fP (const char *virtual_path, const char *storage_path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_fgetc\fP (FILE *stream)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "char * \fBxpn_fgets\fP (char *s, int tam, FILE *stream)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_getc\fP (FILE *stream)"
.br
.ti -1c
.RI "int \fBxpn_fileno\fP (FILE *stream)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_ferror\fP (FILE *stream)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBxpn_stdio\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int xpn_fclose (FILE * stream)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIstream\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB50\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fclose()\fP\&.
.SS "int xpn_ferror (FILE * stream)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIstream\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB135\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_ferror()\fP\&.
.SS "int xpn_fflush (FILE * stream)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIstream\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB69\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fflush()\fP\&.
.SS "int xpn_fgetc (FILE * stream)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIflujo\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB111\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fgetc()\fP\&.
.SS "char * xpn_fgets (char * s, int tam, FILE * flujo)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIs\fP 'TODO'\&. 
.br
\fItam\fP 'TODO'\&. 
.br
\fIflujo\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB116\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fgets()\fP\&.
.SS "int xpn_fileno (FILE * stream)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIstream\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB130\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fileno()\fP\&.
.SS "int xpn_flush (const char * virtual_path, const char * storage_path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIvirtual_path\fP 'TODO'\&. 
.br
\fIstorage_path\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB102\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_flush()\fP\&.
.SS "FILE * xpn_fopen (const char * filename, const char * mode)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP 'TODO'\&. 
.br
\fImode\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fopen()\fP\&.
.SS "size_t xpn_fread (void * ptr, size_t size, size_t nmemb, register FILE * stream)"

.PP
Definition at line \fB59\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fread()\fP\&.
.SS "int xpn_fseek (FILE * stream, long int offset, int whence)"

.PP
Definition at line \fB78\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fseek()\fP\&.
.SS "long xpn_ftell (FILE * stream)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIstream\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB83\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_ftell()\fP\&.
.SS "size_t xpn_fwrite (const void * ptr, size_t size, size_t nmemb, register FILE * stream)"

.PP
Definition at line \fB64\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_fwrite()\fP\&.
.SS "int xpn_getc (FILE * stream)"

.PP
Definition at line \fB121\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_getc()\fP\&.
.SS "int xpn_preload (const char * virtual_path, const char * storage_path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIvirtual_path\fP 'TODO'\&. 
.br
\fIstorage_path\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB97\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_preload()\fP\&.
.SS "void xpn_rewind (FILE * stream)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIstream\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB88\fP of file \fBxpn_stdio\&.c\fP\&.
.PP
References \fBxpn_simple_rewind()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
