.TH "xpn_metadata" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_metadata \- Metadata of xpn file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Id of partition\&. "
.ti -1c
.RI "int \fBversion\fP"
.br
.RI "Number of version\&. "
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "Type of file: file or dir\&. "
.ti -1c
.RI "ssize_t \fBblock_size\fP"
.br
.RI "Size of distribution used\&. "
.ti -1c
.RI "ssize_t \fBsize_threads\fP"
.br
.RI "'TODO' "
.ti -1c
.RI "int \fBdata_nserv\fP"
.br
.RI "Number of servers\&. "
.ti -1c
.RI "int \fBmeta_nserv\fP"
.br
.RI "Number of metadata servers\&. "
.ti -1c
.RI "struct \fBnfi_attr\fP \fBattr\fP"
.br
.RI "'TODO' "
.ti -1c
.RI "int \fBtype_policy\fP"
.br
.RI "RAID0, RAID1\&. "
.ti -1c
.RI "void * \fBpolicy\fP"
.br
.RI "'TODO' "
.ti -1c
.RI "int \fBpolicy_size\fP"
.br
.RI "'TODO' "
.in -1c
.SH "Detailed Description"
.PP 
Metadata of xpn file\&. 
.PP
Definition at line \fB118\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "xpn_metadata::attr"

.PP
'TODO' 
.PP
Definition at line \fB127\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SS "xpn_metadata::block_size"

.PP
Size of distribution used\&. 
.PP
Definition at line \fB123\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP\&.
.SS "xpn_metadata::data_nserv"

.PP
Number of servers\&. 
.PP
Definition at line \fB125\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP, and \fBXpnGetMetadataPos()\fP\&.
.SS "xpn_metadata::id"

.PP
Id of partition\&. 
.PP
Definition at line \fB120\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP\&.
.SS "xpn_metadata::meta_nserv"

.PP
Number of metadata servers\&. 
.PP
Definition at line \fB126\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP\&.
.SS "xpn_metadata::policy"

.PP
'TODO' 
.PP
Definition at line \fB129\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_file_table()\fP, \fBxpn_simple_closedir()\fP, \fBXpnCreateMetadata()\fP, \fBXpnGetAtribFd()\fP, and \fBXpnGetMetadataPos()\fP\&.
.SS "xpn_metadata::policy_size"

.PP
'TODO' 
.PP
Definition at line \fB130\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP\&.
.SS "xpn_metadata::size_threads"

.PP
'TODO' 
.PP
Definition at line \fB124\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SS "xpn_metadata::type"

.PP
Type of file: file or dir\&. 
.PP
Definition at line \fB122\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP, \fBXpnReadMetadata()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_metadata::type_policy"

.PP
RAID0, RAID1\&. 
.PP
Definition at line \fB128\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP, \fBXpnGetFh()\fP, \fBXpnGetMetadataPos()\fP, and \fBXpnReadMetadata()\fP\&.
.SS "xpn_metadata::version"

.PP
Number of version\&. 
.PP
Definition at line \fB121\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
