.TH "xpn_cwd" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_cwd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn_cwd\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBxpn_cwd_path\fP [\fBPATH_MAX\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB47\fP of file \fBxpn_cwd\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char xpn_cwd::xpn_cwd_path[\fBPATH_MAX\fP]"

.PP
Definition at line \fB49\fP of file \fBxpn_cwd\&.h\fP\&.
.PP
Referenced by \fBxpn_init_cwd()\fP, \fBxpn_simple_chdir()\fP, \fBxpn_simple_getcwd()\fP, and \fBXpnGetAbsolutePath()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
