.TH "xpn_metadata_header" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_metadata_header \- Metadata header of xpn file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.RI "Number of version\&. "
.ti -1c
.RI "ssize_t \fBblock_size\fP"
.br
.RI "Size of distribution used\&. "
.ti -1c
.RI "int \fBdata_nserv\fP"
.br
.RI "Number of servers\&. "
.ti -1c
.RI "ssize_t \fBfile_size\fP"
.br
.RI "'TODO' "
.ti -1c
.RI "int \fBtype_policy\fP"
.br
.RI "RAID0, RAID1\&. "
.in -1c
.SH "Detailed Description"
.PP 
Metadata header of xpn file\&. 
.PP
Definition at line \fB164\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "xpn_metadata_header::block_size"

.PP
Size of distribution used\&. 
.PP
Definition at line \fB167\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SS "xpn_metadata_header::data_nserv"

.PP
Number of servers\&. 
.PP
Definition at line \fB168\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SS "xpn_metadata_header::file_size"

.PP
'TODO' 
.PP
Definition at line \fB169\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SS "xpn_metadata_header::type_policy"

.PP
RAID0, RAID1\&. 
.PP
Definition at line \fB170\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SS "xpn_metadata_header::version"

.PP
Number of version\&. 
.PP
Definition at line \fB166\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
