.TH "xpn_policy_opendir.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_policy_opendir.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'xpn\&.h'\fP
.br
\fC#include 'xpn/xpn_simple/xpn_opendir\&.h'\fP
.br
\fC#include 'xpn/xpn_simple/xpn_policy_open\&.h'\fP
.br
\fC#include 'xpn/xpn_simple/xpn_policy_opendir\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBXpnGetEntry\fP (int fd, struct dirent *entry)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBxpn_policy_opendir\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int XpnGetEntry (int fd, struct dirent * entry)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIentry\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBxpn_policy_opendir\&.c\fP\&.
.PP
References \fBxpn_filedesc::data_vfh\fP, \fBxpn_filedesc::id\fP, \fBnfi_ops::nfi_readdir\fP, \fBxpn_fh::nfih\fP, \fBop_xpn_readdir\fP, \fBnfi_server::ops\fP, \fBxpn_filedesc::path\fP, \fBnfi_fhandle::server\fP, \fBXPN_DATA_SERVER\fP, \fBXPN_DEBUG_BEGIN\fP, \fBXPN_DEBUG_END\fP, \fBxpn_file_table\fP, \fBXpnGetFh()\fP, and \fBXpnGetServers()\fP\&.
.PP
Referenced by \fBxpn_simple_readdir()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
