.TH "tcp_server_comm.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_server_comm.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tcp_server_comm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtcpClient_comm_init\fP (__attribute__((__unused__)) \fBtcpClient_param_st\fP *\fBparams\fP)"
.br
.ti -1c
.RI "int \fBtcpClient_comm_destroy\fP (__attribute__((__unused__)) \fBtcpClient_param_st\fP *\fBparams\fP)"
.br
.ti -1c
.RI "int \fBtcpClient_comm_connect\fP (\fBtcpClient_param_st\fP *\fBparams\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBtcpClient_comm_disconnect\fP (__attribute__((__unused__)) \fBtcpClient_param_st\fP *\fBparams\fP)"
.br
.ti -1c
.RI "int \fBtcpClient_comm_locality\fP (\fBtcpClient_param_st\fP *\fBparams\fP)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBtcpClient_write_operation\fP (int fd, char *data, ssize_t size, __attribute__((__unused__)) char *msg_id)"
.br
.ti -1c
.RI "ssize_t \fBtcpClient_write_data\fP (int fd, char *data, ssize_t size, __attribute__((__unused__)) char *msg_id)"
.br
.ti -1c
.RI "ssize_t \fBtcpClient_read_data\fP (int fd, char *data, ssize_t size, __attribute__((__unused__)) char *msg_id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int tcpClient_comm_connect (\fBtcpClient_param_st\fP * params)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIparams\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_error\fP, \fBdebug_info\fP, \fBns_lookup()\fP, \fBparams\fP, and \fBmpi_server_param_st::srv_name\fP\&.
.PP
Referenced by \fBnfi_tcp_server_connect()\fP, and \fBnfi_tcp_server_reconnect()\fP\&.
.SS "int tcpClient_comm_destroy (__attribute__((__unused__)) \fBtcpClient_param_st\fP * params)"

.PP
Definition at line \fB51\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_info\fP\&.
.PP
Referenced by \fBnfi_tcp_server_destroy()\fP\&.
.SS "int tcpClient_comm_disconnect (__attribute__((__unused__)) \fBtcpClient_param_st\fP * params)"

.PP
Definition at line \fB171\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_info\fP\&.
.PP
Referenced by \fBnfi_tcp_server_disconnect()\fP\&.
.SS "int tcpClient_comm_init (__attribute__((__unused__)) \fBtcpClient_param_st\fP * params)"

.PP
Definition at line \fB39\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_info\fP\&.
.PP
Referenced by \fBnfi_tcp_server_init()\fP\&.
.SS "int tcpClient_comm_locality (\fBtcpClient_param_st\fP * params)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIparams\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB181\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBdebug_warning\fP, \fBmpi_server_param_st::dirbase\fP, \fBparams\fP, \fBPATH_MAX\fP, \fBserv_name\fP, \fBTCP_SERVER_GETNODENAME\fP, \fBtcpClient_read_data()\fP, and \fBtcpClient_write_data()\fP\&.
.PP
Referenced by \fBnfi_tcp_server_init()\fP\&.
.SS "ssize_t tcpClient_read_data (int fd, char * data, ssize_t size, __attribute__((__unused__)) char * msg_id)"

.PP
Definition at line \fB326\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBdebug_warning\fP, and \fBreal_read\fP\&.
.PP
Referenced by \fBnfi_tcp_server_doRequest()\fP, \fBnfi_tcp_server_read()\fP, \fBnfi_tcp_server_write()\fP, and \fBtcpClient_comm_locality()\fP\&.
.SS "ssize_t tcpClient_write_data (int fd, char * data, ssize_t size, __attribute__((__unused__)) char * msg_id)"

.PP
Definition at line \fB271\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBdebug_warning\fP, and \fBreal_write\fP\&.
.PP
Referenced by \fBnfi_tcp_server_write()\fP, \fBtcp_server_write_operation()\fP, \fBtcpClient_comm_locality()\fP, and \fBtcpClient_write_operation()\fP\&.
.SS "ssize_t tcpClient_write_operation (int fd, char * data, ssize_t size, __attribute__((__unused__)) char * msg_id)"

.PP
Definition at line \fB245\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_comm\&.c\fP\&.
.PP
References \fBdebug_info\fP, \fBdebug_warning\fP, and \fBtcpClient_write_data()\fP\&.
.PP
Referenced by \fBtcp_server_write_operation()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
