.TH "xpn_filedesc" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_filedesc \- File table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn_file\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Id of file\&. "
.ti -1c
.RI "char \fBpath\fP [\fBPATH_MAX\fP]"
.br
.RI "Absolute path\&. "
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "Indicate FILE or DIR\&. "
.ti -1c
.RI "int \fBlinks\fP"
.br
.RI "Number of links that this file has\&. "
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.RI "O_RDONLY, O_WRONLY,\&.\&.\&. "
.ti -1c
.RI "struct \fBxpn_partition\fP * \fBpart\fP"
.br
.RI "Partition\&. "
.ti -1c
.RI "struct \fBxpn_metadata\fP * \fBmdata\fP"
.br
.RI "Metadata\&. "
.ti -1c
.RI "struct \fBxpn_attr\fP \fBattr\fP"
.br
.RI "Attributes of the open file\&. "
.ti -1c
.RI "off_t \fBoffset\fP"
.br
.RI "Offset of the open file\&. "
.ti -1c
.RI "ssize_t \fBblock_size\fP"
.br
.RI "Size of distribution used\&. "
.ti -1c
.RI "ssize_t \fBsize_threads\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "struct \fBxpn_fh\fP * \fBdata_vfh\fP"
.br
.RI "Virtual FH\&. "
.ti -1c
.RI "struct \fBxpn_fh\fP * \fBmeta_vfh\fP"
.br
.RI "Virtual METADATA FH\&. "
.ti -1c
.RI "struct stat \fBst\fP"
.br
.RI "A 'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File table\&. 


.PP
Definition at line \fB144\fP of file \fBxpn_file\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "xpn_filedesc::attr"

.PP
Attributes of the open file\&. 
.PP
Definition at line \fB153\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_filedesc::block_size"

.PP
Size of distribution used\&. 
.PP
Definition at line \fB155\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBxpn_sread()\fP, \fBxpn_swrite()\fP, \fBXpnGetBlock()\fP, \fBXpnRWBlocksPolicyBlockByBlock()\fP, \fBXpnSearchSlotFile()\fP, and \fBXpnWriteBlocksPolicyRAID1_BlockByBlock()\fP\&.
.SS "xpn_filedesc::data_vfh"

.PP
Virtual FH\&. 
.PP
Definition at line \fB157\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_file_table()\fP, \fBxpn_simple_close()\fP, \fBxpn_simple_closedir()\fP, \fBXpnGetEntry()\fP, \fBXpnGetServers()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::id"

.PP
Id of file\&. 
.PP
Definition at line \fB146\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBxpn_sread()\fP, \fBxpn_swrite()\fP, \fBXpnGetAtribFd()\fP, \fBXpnGetEntry()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::links"

.PP
Number of links that this file has\&. 
.PP
Definition at line \fB149\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_internal_open()\fP, \fBxpn_simple_close()\fP, \fBxpn_simple_closedir()\fP, \fBxpn_simple_dup()\fP, \fBxpn_simple_dup2()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::mdata"

.PP
Metadata\&. 
.PP
Definition at line \fB152\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_file_table()\fP, \fBxpn_simple_closedir()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::meta_vfh"

.PP
Virtual METADATA FH\&. 
.PP
Definition at line \fB158\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBXpnGetServers()\fP\&.
.SS "xpn_filedesc::mode"

.PP
O_RDONLY, O_WRONLY,\&.\&.\&. 
.PP
Definition at line \fB150\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_fopencookie()\fP, \fBxpn_simple_fopen()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::offset"

.PP
Offset of the open file\&. 
.PP
Definition at line \fB154\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBxpn_simple_fseek()\fP, \fBxpn_simple_ftell()\fP, \fBxpn_simple_lseek()\fP, \fBxpn_sread()\fP, \fBxpn_swrite()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::part"

.PP
Partition\&. 
.PP
Definition at line \fB151\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBXpnGetServers()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::path"

.PP
Absolute path\&. 
.PP
Definition at line \fB147\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_fopencookie()\fP, \fBxpn_pread()\fP, \fBxpn_pwrite()\fP, \fBxpn_sread()\fP, \fBxpn_swrite()\fP, \fBXpnGetAtribFd()\fP, \fBXpnGetEntry()\fP, \fBXpnSearchFile()\fP, \fBXpnSearchSlotFile()\fP, and \fBXpnShowFileTable()\fP\&.
.SS "xpn_filedesc::size_threads"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB156\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_filedesc::st"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB159\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_filedesc::type"

.PP
Indicate FILE or DIR\&. 
.PP
Definition at line \fB148\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBXpnSearchSlotFile()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
