.TH "xpn_attr" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_attr \- File table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn_file\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBat_type\fP"
.br
.RI "FILE or DIR\&. "
.ti -1c
.RI "mode_t \fBat_mode\fP"
.br
.RI "Protection\&. "
.ti -1c
.RI "nlink_t \fBat_nlink\fP"
.br
.RI "Number of hard links\&. "
.ti -1c
.RI "uid_t \fBat_uid\fP"
.br
.RI "User ID of owner\&. "
.ti -1c
.RI "gid_t \fBat_gid\fP"
.br
.RI "Group ID of owner\&. "
.ti -1c
.RI "off_t \fBat_size\fP"
.br
.RI "Total size, in bytes\&. "
.ti -1c
.RI "u_long \fBat_blksize\fP"
.br
.RI "Blocksize for filesystem I/O\&. "
.ti -1c
.RI "u_long \fBat_blocks\fP"
.br
.RI "Number of blocks allocated\&. "
.ti -1c
.RI "time_t \fBat_atime\fP"
.br
.RI "Time of last access\&. "
.ti -1c
.RI "time_t \fBat_mtime\fP"
.br
.RI "Time of last modification\&. "
.ti -1c
.RI "time_t \fBat_ctime\fP"
.br
.RI "Time of last status change\&. "
.ti -1c
.RI "void * \fBprivate_info\fP"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File table\&. 


.PP
Definition at line \fB96\fP of file \fBxpn_file\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "xpn_attr::at_atime"

.PP
Time of last access\&. 
.PP
Definition at line \fB106\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_blksize"

.PP
Blocksize for filesystem I/O\&. 
.PP
Definition at line \fB104\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_blocks"

.PP
Number of blocks allocated\&. 
.PP
Definition at line \fB105\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_ctime"

.PP
Time of last status change\&. 
.PP
Definition at line \fB108\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_gid"

.PP
Group ID of owner\&. 
.PP
Definition at line \fB102\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_mode"

.PP
Protection\&. 
.PP
Definition at line \fB99\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_mtime"

.PP
Time of last modification\&. 
.PP
Definition at line \fB107\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_nlink"

.PP
Number of hard links\&. 
.PP
Definition at line \fB100\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_size"

.PP
Total size, in bytes\&. 
.PP
Definition at line \fB103\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_type"

.PP
FILE or DIR\&. 
.PP
Definition at line \fB98\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::at_uid"

.PP
User ID of owner\&. 
.PP
Definition at line \fB101\fP of file \fBxpn_file\&.h\fP\&.
.SS "xpn_attr::private_info"

.PP
'TODO'\&. 
.PP
Definition at line \fB109\fP of file \fBxpn_file\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
