.TH "xpn_opendir.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_opendir.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'xpn\&.h'\fP
.br
\fC#include 'xpn/xpn_simple/xpn_open\&.h'\fP
.br
\fC#include 'xpn/xpn_simple/xpn_opendir\&.h'\fP
.br
\fC#include 'xpn/xpn_simple/xpn_policy_opendir\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "DIR * \fBxpn_simple_opendir\fP (const char *path)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "struct dirent * \fBxpn_simple_readdir\fP (DIR *dirp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "int \fBxpn_simple_closedir\fP (DIR *dirp)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "void \fBxpn_simple_rewinddir\fP (__attribute__((__unused__)) DIR *dirp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBxpn_opendir\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int xpn_simple_closedir (DIR * dirp)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirp\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB139\fP of file \fBxpn_opendir\&.c\fP\&.
.PP
References \fBxpn_filedesc::data_vfh\fP, \fBxpn_filedesc::links\fP, \fBxpn_filedesc::mdata\fP, \fBxpn_fh::n_nfih\fP, \fBnfi_ops::nfi_closedir\fP, \fBxpn_fh::nfih\fP, \fBnfi_server::ops\fP, \fBxpn_metadata::policy\fP, \fBnfi_fhandle::priv_fh\fP, \fBnfi_fhandle::server\fP, \fBxpn_err()\fP, \fBxpn_file_table\fP, \fBXPN_MAX_FILE\fP, and \fBXPN_OK\fP\&.
.PP
Referenced by \fBxpn_closedir()\fP\&.
.SS "DIR * xpn_simple_opendir (const char * path)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBxpn_opendir\&.c\fP\&.
.PP
References \fBerrno\fP, \fBO_RDONLY\fP, \fBPATH_MAX\fP, \fBXPN_DEBUG_BEGIN_ARGS1\fP, \fBXPN_DEBUG_END_ARGS1\fP, and \fBxpn_simple_open()\fP\&.
.PP
Referenced by \fBxpn_opendir()\fP\&.
.SS "struct dirent * xpn_simple_readdir (DIR * dirp)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIdirp\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBxpn_opendir\&.c\fP\&.
.PP
References \fBXPN_DEBUG_BEGIN\fP, \fBXPN_DEBUG_END\fP, \fBxpn_file_table\fP, \fBXPN_MAX_FILE\fP, and \fBXpnGetEntry()\fP\&.
.PP
Referenced by \fBxpn_readdir()\fP\&.
.SS "void xpn_simple_rewinddir (__attribute__((__unused__)) DIR * dirp)"

.PP
Definition at line \fB191\fP of file \fBxpn_opendir\&.c\fP\&.
.PP
Referenced by \fBxpn_rewinddir()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
