.TH "xpn_ls.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_ls.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include 'mpi\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBlist\fP (char *dir_name, FILE *fd)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int list (char * dir_name, FILE * fd)"

.PP
Definition at line \fB34\fP of file \fBxpn_ls\&.c\fP\&.
.PP
References \fBclosedir()\fP, \fBlist()\fP, \fBopendir()\fP, \fBPATH_MAX\fP, and \fBreaddir()\fP\&.
.PP
Referenced by \fBlist()\fP, and \fBmain()\fP\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB90\fP of file \fBxpn_ls\&.c\fP\&.
.PP
References \fBlist()\fP, \fBMPI_Finalize()\fP, and \fBMPI_Init()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
