.TH "xpn_rw.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_rw.c \- File to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'xpn/xpn_simple/xpn_rw\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXpnShowFileTable\fP ()"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBxpn_simple_read\fP (int fd, void *buffer, size_t size)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBxpn_simple_write\fP (int fd, const void *buffer, size_t size)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBxpn_sread\fP (int fd, const void *buffer, size_t size, off_t offset)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBxpn_pread\fP (int fd, void *buffer, size_t size, off_t offset)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBxpn_swrite\fP (int fd, const void *buffer, size_t size, off_t offset)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "ssize_t \fBxpn_pwrite\fP (int fd, const void *buffer, size_t size, off_t offset)"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "off_t \fBxpn_simple_lseek\fP (int fd, off_t offset, int flag)"
.br
.RI "'TODO'\&. "
.in -1c
.SH "Detailed Description"
.PP 
File to 'TODO'\&. 

File to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBxpn_rw\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "ssize_t xpn_pread (int fd, void * buffer, size_t size, off_t offset)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fIsize\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB209\fP of file \fBxpn_rw\&.c\fP\&.
.PP
References \fBxpn_filedesc::block_size\fP, \fBnfi_worker_io::buffer\fP, \fBerrno\fP, \fBxpn_filedesc::id\fP, \fBnfi_worker_do_read()\fP, \fBnfiworker_wait()\fP, \fBO_WRONLY\fP, \fBnfi_worker_io::offset\fP, \fBxpn_filedesc::offset\fP, \fBop_xpn_read\fP, \fBxpn_filedesc::path\fP, \fBnfi_worker_io::size\fP, \fBnfi_worker::thread\fP, \fBnfi_server::wrk\fP, \fBXPN_DATA_SERVER\fP, \fBXPN_DEBUG_BEGIN_CUSTOM\fP, \fBXPN_DEBUG_END_CUSTOM\fP, \fBXPN_DIR\fP, \fBxpn_file_table\fP, \fBXPN_MAX_FILE\fP, \fBnfi_server::xpn_thread\fP, \fBXpnGetFh()\fP, \fBXpnGetMetadataPos()\fP, \fBXpnGetServers()\fP, \fBXpnReadBlocks()\fP, \fBXpnReadBlocksFinish()\fP, \fBXpnReadGetTotalBytes()\fP, and \fBXpnShowFileTable()\fP\&.
.PP
Referenced by \fBxpn_simple_read()\fP\&.
.SS "ssize_t xpn_pwrite (int fd, const void * buffer, size_t size, off_t offset)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fIsize\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB573\fP of file \fBxpn_rw\&.c\fP\&.
.PP
References \fBxpn_filedesc::block_size\fP, \fBnfi_worker_io::buffer\fP, \fBxpn_filedesc::id\fP, \fBnfi_worker_do_write()\fP, \fBnfiworker_wait()\fP, \fBO_RDONLY\fP, \fBnfi_worker_io::offset\fP, \fBxpn_filedesc::offset\fP, \fBop_xpn_write\fP, \fBxpn_filedesc::path\fP, \fBnfi_worker_io::size\fP, \fBnfi_worker::thread\fP, \fBnfi_server::wrk\fP, \fBXPN_DATA_SERVER\fP, \fBXPN_DEBUG_BEGIN_CUSTOM\fP, \fBXPN_DEBUG_END_CUSTOM\fP, \fBXPN_DIR\fP, \fBxpn_file_table\fP, \fBXPN_MAX_FILE\fP, \fBnfi_server::xpn_thread\fP, \fBXpnGetFh()\fP, \fBXpnGetMetadataPos()\fP, \fBXpnGetServers()\fP, \fBXpnWriteBlocks()\fP, \fBXpnWriteBlocksFinish()\fP, and \fBXpnWriteGetTotalBytes()\fP\&.
.PP
Referenced by \fBxpn_simple_write()\fP\&.
.SS "off_t xpn_simple_lseek (int fd, off_t offset, int flag)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.br
\fIflag\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB833\fP of file \fBxpn_rw\&.c\fP\&.
.PP
References \fBerrno\fP, \fBxpn_filedesc::offset\fP, \fBst\fP, \fBxpn_file_table\fP, and \fBxpn_simple_fstat()\fP\&.
.PP
Referenced by \fBxpn_lseek()\fP, \fBxpn_seeker()\fP, \fBxpn_simple_fseek()\fP, and \fBxpn_simple_rewind()\fP\&.
.SS "ssize_t xpn_simple_read (int fd, void * buffer, size_t size)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fIsize\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBxpn_rw\&.c\fP\&.
.PP
References \fBerrno\fP, \fBXPN_DEBUG_BEGIN_CUSTOM\fP, \fBXPN_DEBUG_END_CUSTOM\fP, \fBxpn_file_table\fP, \fBxpn_pread()\fP, \fBxpn_sread()\fP, and \fBXpnShowFileTable()\fP\&.
.PP
Referenced by \fBxpn_read()\fP, \fBxpn_reader()\fP, \fBxpn_simple_fgetc()\fP, and \fBxpn_simple_fread()\fP\&.
.SS "ssize_t xpn_simple_write (int fd, const void * buffer, size_t size)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fIsize\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB74\fP of file \fBxpn_rw\&.c\fP\&.
.PP
References \fBerrno\fP, \fBXPN_DEBUG_BEGIN_CUSTOM\fP, \fBXPN_DEBUG_END_CUSTOM\fP, \fBxpn_file_table\fP, \fBxpn_pwrite()\fP, \fBxpn_swrite()\fP, and \fBXpnShowFileTable()\fP\&.
.PP
Referenced by \fBxpn_simple_fwrite()\fP, \fBxpn_write()\fP, and \fBxpn_writer()\fP\&.
.SS "ssize_t xpn_sread (int fd, const void * buffer, size_t size, off_t offset)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fIsize\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBxpn_rw\&.c\fP\&.
.PP
References \fBxpn_filedesc::block_size\fP, \fBerrno\fP, \fBxpn_filedesc::id\fP, \fBnfi_ops::nfi_read\fP, \fBO_WRONLY\fP, \fBxpn_filedesc::offset\fP, \fBop_xpn_read\fP, \fBnfi_server::ops\fP, \fBxpn_filedesc::path\fP, \fBXPN_DATA_SERVER\fP, \fBXPN_DEBUG_BEGIN_CUSTOM\fP, \fBXPN_DEBUG_END_CUSTOM\fP, \fBXPN_DIR\fP, \fBxpn_file_table\fP, \fBXPN_HEADER_SIZE\fP, \fBXPN_MAX_FILE\fP, \fBXpnGetBlock()\fP, \fBXpnGetFh()\fP, \fBXpnGetServers()\fP, and \fBXpnShowFileTable()\fP\&.
.PP
Referenced by \fBxpn_simple_read()\fP\&.
.SS "ssize_t xpn_swrite (int fd, const void * buffer, size_t size, off_t offset)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
\fIfd\fP 'TODO'\&. 
.br
\fIbuffer\fP 'TODO'\&. 
.br
\fIsize\fP 'TODO'\&. 
.br
\fIoffset\fP 'TODO'\&. 
.RE
.PP
\fBReturns\fP
.RS 4
'TODO'\&. 
.RE
.PP

.PP
Definition at line \fB473\fP of file \fBxpn_rw\&.c\fP\&.
.PP
References \fBxpn_filedesc::block_size\fP, \fBxpn_filedesc::id\fP, \fBnfi_ops::nfi_write\fP, \fBO_RDONLY\fP, \fBxpn_filedesc::offset\fP, \fBop_xpn_write\fP, \fBnfi_server::ops\fP, \fBxpn_filedesc::path\fP, \fBXPN_DATA_SERVER\fP, \fBXPN_DEBUG_BEGIN_CUSTOM\fP, \fBXPN_DIR\fP, \fBxpn_file_table\fP, \fBXPN_HEADER_SIZE\fP, \fBXPN_MAX_FILE\fP, \fBXpnGetBlock()\fP, \fBXpnGetFh()\fP, and \fBXpnGetServers()\fP\&.
.PP
Referenced by \fBxpn_simple_write()\fP\&.
.SS "void XpnShowFileTable (void)"

.PP
'TODO'\&. 'TODO'\&.
.PP
\fBParameters\fP
.RS 4
None\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBxpn_open\&.c\fP\&.
.PP
References \fBxpn_filedesc::path\fP, \fBxpn_file_table\fP, and \fBXPN_MAX_FILE\fP\&.
.PP
Referenced by \fBxpn_pread()\fP, \fBxpn_simple_read()\fP, \fBxpn_simple_write()\fP, and \fBxpn_sread()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
