.TH "tcp_server_ops.h" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_server_ops.h \- Header file to 'TODO'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'all_system\&.h'\fP
.br
\fC#include 'tcp_server_params\&.h'\fP
.br
\fC#include 'base/utils\&.h'\fP
.br
\fC#include 'base/filesystem\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBst_tcp_server_open\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_open_req\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_creat\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_read\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_read_req\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_write\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_write_req\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_close\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_rm\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_rename\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_getattr\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_setattr\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_attr_req\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_mkdir\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_opendir\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_readdir\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_direntry\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_closedir\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_rmdir\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_flush\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_preload\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_end\fP"
.br
.RI "This is a struct\&. "
.ti -1c
.RI "struct \fBst_tcp_server_msg\fP"
.br
.RI "This is a struct\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBASYNC_CLOSE\fP   1"
.br
.ti -1c
.RI "#define \fBFILESYSTEM_DLSYM\fP   1"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_ID\fP   32"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_OPEN_FILE_WS\fP   0"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_CREAT_FILE_WS\fP   1"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_READ_FILE_WS\fP   2"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_WRITE_FILE_WS\fP   3"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_CLOSE_FILE_WS\fP   4"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_RM_FILE\fP   5"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_RM_FILE_ASYNC\fP   6"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_RENAME_FILE\fP   7"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_GETATTR_FILE\fP   8"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_SETATTR_FILE\fP   9"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_OPEN_FILE_WOS\fP   100"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_CREAT_FILE_WOS\fP   101"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_READ_FILE_WOS\fP   102"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_WRITE_FILE_WOS\fP   103"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_MKDIR_DIR\fP   20"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_RMDIR_DIR\fP   21"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_RMDIR_DIR_ASYNC\fP   22"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_OPENDIR_DIR\fP   23"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_READDIR_DIR\fP   24"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_CLOSEDIR_DIR\fP   25"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_FLUSH_FILE\fP   40"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_PRELOAD_FILE\fP   41"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_STATFS_DIR\fP   60"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_GETNODENAME\fP   61"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_GETID\fP   62"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_FINALIZE\fP   80"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_DISCONNECT\fP   81"
.br
.ti -1c
.RI "#define \fBTCP_SERVER_END\fP   \-1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file to 'TODO'\&. 

Header file to 'TODO'\&.
.PP
\fBAuthors\fP
.RS 4
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra 
.RE
.PP
\fBDate\fP
.RS 4
Jul 22, 2021 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.PP
Definition in file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASYNC_CLOSE   1"

.PP
Definition at line \fB35\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define FILESYSTEM_DLSYM   1"

.PP
Definition at line \fB36\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_CLOSE_FILE_WS   4"

.PP
Definition at line \fB64\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_CLOSEDIR_DIR   25"

.PP
Definition at line \fB87\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_CREAT_FILE_WOS   101"

.PP
Definition at line \fB75\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_CREAT_FILE_WS   1"

.PP
Definition at line \fB61\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_DISCONNECT   81"

.PP
Definition at line \fB106\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_END   \-1"

.PP
Definition at line \fB107\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_FINALIZE   80"

.PP
Definition at line \fB105\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_FLUSH_FILE   40"

.PP
Definition at line \fB92\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_GETATTR_FILE   8"

.PP
Definition at line \fB68\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_GETID   62"

.PP
Definition at line \fB100\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_GETNODENAME   61"

.PP
Definition at line \fB99\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_ID   32"

.PP
Definition at line \fB50\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_MKDIR_DIR   20"

.PP
Definition at line \fB82\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_OPEN_FILE_WOS   100"

.PP
Definition at line \fB74\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_OPEN_FILE_WS   0"

.PP
Definition at line \fB60\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_OPENDIR_DIR   23"

.PP
Definition at line \fB85\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_PRELOAD_FILE   41"

.PP
Definition at line \fB93\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_READ_FILE_WOS   102"

.PP
Definition at line \fB76\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_READ_FILE_WS   2"

.PP
Definition at line \fB62\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_READDIR_DIR   24"

.PP
Definition at line \fB86\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_RENAME_FILE   7"

.PP
Definition at line \fB67\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_RM_FILE   5"

.PP
Definition at line \fB65\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_RM_FILE_ASYNC   6"

.PP
Definition at line \fB66\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_RMDIR_DIR   21"

.PP
Definition at line \fB83\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_RMDIR_DIR_ASYNC   22"

.PP
Definition at line \fB84\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_SETATTR_FILE   9"

.PP
Definition at line \fB69\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_STATFS_DIR   60"

.PP
Definition at line \fB98\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_WRITE_FILE_WOS   103"

.PP
Definition at line \fB77\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SS "#define TCP_SERVER_WRITE_FILE_WS   3"

.PP
Definition at line \fB63\fP of file \fBxpn_client/nfi/nfi_tcp_server/tcp_server_ops\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
