.TH "xpn_fh" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_fh \- 'TODO'  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn_file\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBn_nfih\fP"
.br
.RI "'TODO'\&. "
.ti -1c
.RI "struct \fBnfi_fhandle\fP ** \fBnfih\fP"
.br
.RI "NFI handler\&. "
.in -1c
.SH "Detailed Description"
.PP 
'TODO' 


.PP
Definition at line \fB62\fP of file \fBxpn_file\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "xpn_fh::n_nfih"

.PP
'TODO'\&. 
.PP
Definition at line \fB64\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_file_table()\fP, \fBxpn_internal_creat()\fP, \fBxpn_internal_open()\fP, \fBxpn_simple_close()\fP, \fBxpn_simple_closedir()\fP, \fBxpn_simple_mkdir()\fP, \fBxpn_simple_rename()\fP, \fBXpnGetAtribPath()\fP, and \fBXpnGetServers()\fP\&.
.SS "xpn_fh::nfih"

.PP
NFI handler\&. 
.PP
Definition at line \fB65\fP of file \fBxpn_file\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_file_table()\fP, \fBxpn_internal_creat()\fP, \fBxpn_internal_open()\fP, \fBxpn_simple_close()\fP, \fBxpn_simple_closedir()\fP, \fBxpn_simple_mkdir()\fP, \fBxpn_simple_rename()\fP, \fBXpnGetAtribPath()\fP, \fBXpnGetEntry()\fP, and \fBXpnReadMetadata()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
