.TH "xpn_partition" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpn_partition \- Paralel struct partition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xpn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Id of partition\&. "
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "Type of file :NORMAL, RAID5,\&.\&.\&.\&. "
.ti -1c
.RI "char \fBname\fP [\fBPATH_MAX\fP]"
.br
.RI "Name of partition\&. "
.ti -1c
.RI "ssize_t \fBblock_size\fP"
.br
.RI "Size of distribution used\&. "
.ti -1c
.RI "ssize_t \fBsize_threads\fP"
.br
.RI "A 'TODO'\&. "
.ti -1c
.RI "int \fBinitialized\fP"
.br
.RI "Whether it is already initialized or not\&. "
.ti -1c
.RI "int \fBdata_nserv\fP"
.br
.RI "Number of server\&. "
.ti -1c
.RI "struct \fBnfi_server\fP * \fBdata_serv\fP"
.br
.RI "List of data servers in the partition\&. "
.ti -1c
.RI "int \fBmeta_nserv\fP"
.br
.RI "Number of metadata_server\&. "
.ti -1c
.RI "struct \fBnfi_server\fP * \fBmeta_serv\fP"
.br
.RI "List of metadata servers in the partition\&. "
.in -1c
.SH "Detailed Description"
.PP 
Paralel struct partition\&. 
.PP
Definition at line \fB75\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "xpn_partition::block_size"

.PP
Size of distribution used\&. 
.PP
Definition at line \fB80\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP, \fBXpnGetInfoPartition()\fP, and \fBXpnSearchSlotFile()\fP\&.
.SS "xpn_partition::data_nserv"

.PP
Number of server\&. 
.PP
Definition at line \fB85\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_servers()\fP, \fBxpn_init_partition()\fP, \fBXpnCreateMetadata()\fP, \fBXpnGetInfoPartition()\fP, \fBXpnGetNumServersPartition()\fP, and \fBXpnGetServers()\fP\&.
.SS "xpn_partition::data_serv"

.PP
List of data servers in the partition\&. 
.PP
Definition at line \fB86\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_servers()\fP, \fBxpn_init_partition()\fP, and \fBXpnGetServers()\fP\&.
.SS "xpn_partition::id"

.PP
Id of partition\&. 
.PP
Definition at line \fB77\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBxpn_init_partition()\fP, \fBxpn_simple_destroy()\fP, and \fBXpnGetPartition()\fP\&.
.SS "xpn_partition::initialized"

.PP
Whether it is already initialized or not\&. 
.PP
Definition at line \fB83\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBxpn_init_partition()\fP\&.
.SS "xpn_partition::meta_nserv"

.PP
Number of metadata_server\&. 
.PP
Definition at line \fB88\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_servers()\fP, \fBXpnCreateMetadata()\fP, \fBXpnGetInfoPartition()\fP, \fBXpnGetNumServersPartition()\fP, and \fBXpnGetServers()\fP\&.
.SS "xpn_partition::meta_serv"

.PP
List of metadata servers in the partition\&. 
.PP
Definition at line \fB89\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBxpn_destroy_servers()\fP, and \fBXpnGetServers()\fP\&.
.SS "xpn_partition::name"

.PP
Name of partition\&. 
.PP
Definition at line \fB79\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnGetInfoPartition()\fP, and \fBXpnShowPartitionTable()\fP\&.
.SS "xpn_partition::size_threads"

.PP
A 'TODO'\&. 
.PP
Definition at line \fB81\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnGetInfoPartition()\fP, and \fBXpnGetSizeThreads()\fP\&.
.SS "xpn_partition::type"

.PP
Type of file :NORMAL, RAID5,\&.\&.\&.\&. 
.PP
Definition at line \fB78\fP of file \fBxpn/xpn_simple/xpn\&.h\fP\&.
.PP
Referenced by \fBXpnCreateMetadata()\fP, and \fBXpnGetInfoPartition()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
