.TH "xpnwriter.c" 3 "Wed May 24 2023" "Version Expand version 1.0r5" "Expand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpnwriter.c
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include 'xpn\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBAR_LENGTH\fP   50"
.br
.ti -1c
.RI "#define \fBKB\fP   (1024)"
.br
.ti -1c
.RI "#define \fBMB\fP   (\fBKB\fP * \fBKB\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBprogram_name\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BAR_LENGTH   50"

.PP
Definition at line \fB31\fP of file \fBxpnwriter\&.c\fP\&.
.SS "#define KB   (1024)"

.PP
Definition at line \fB34\fP of file \fBxpnwriter\&.c\fP\&.
.SS "#define MB   (\fBKB\fP * \fBKB\fP)"

.PP
Definition at line \fB38\fP of file \fBxpnwriter\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB48\fP of file \fBxpnwriter\&.c\fP\&.
.PP
References \fBclose()\fP, \fBexit()\fP, \fBKB\fP, \fBO_CREAT\fP, \fBO_TRUNC\fP, \fBO_WRONLY\fP, \fBopen()\fP, \fBprogram_name\fP, \fBusage()\fP, \fBwrite()\fP, \fBxpn_close()\fP, \fBxpn_destroy()\fP, \fBxpn_init()\fP, \fBxpn_open()\fP, and \fBxpn_write()\fP\&.
.SS "void usage ()"

.PP
Definition at line \fB43\fP of file \fBxpnwriter\&.c\fP\&.
.PP
References \fBprogram_name\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char* program_name"

.PP
Definition at line \fB41\fP of file \fBxpnwriter\&.c\fP\&.
.PP
Referenced by \fBmain()\fP, \fBusage()\fP, and \fBusage()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Expand from the source code\&.
