/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_expand_jni_ExpandToPosix */

#ifndef _Included_org_expand_jni_ExpandToPosix
#define _Included_org_expand_jni_ExpandToPosix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_chdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1chdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_chmod
 * Signature: (Ljava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1chmod
  (JNIEnv *, jobject, jstring, jshort);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_creat
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1creat
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_createFlags
 * Signature: ()Lorg/expand/jni/ExpandFlags;
 */
JNIEXPORT jobject JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1createFlags
  (JNIEnv *, jobject);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_exist
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1exist
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_fstat
 * Signature: (I)Lorg/expand/jni/Stat;
 */
JNIEXPORT jobject JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1fstat
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_get_block_locality
 * Signature: (Ljava/lang/String;J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1get_1block_1locality
  (JNIEnv *, jobject, jstring, jlong, jobjectArray);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_getcwd
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1getcwd
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_getDirContent
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1getDirContent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_getGroupname
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1getGroupname
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_getUsername
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1getUsername
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1init
  (JNIEnv *, jobject);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_isDir
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1isDir
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_lseek
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1lseek
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_mkdir
 * Signature: (Ljava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1mkdir
  (JNIEnv *, jobject, jstring, jshort);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_open
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1open
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_read
 * Signature: (ILjava/nio/ByteBuffer;J)J
 */
JNIEXPORT jlong JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1read
  (JNIEnv *, jobject, jint, jobject, jlong);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_rename
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1rename
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_rmdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1rmdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_stat
 * Signature: (Ljava/lang/String;)Lorg/expand/jni/Stat;
 */
JNIEXPORT jobject JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1stat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_unlink
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1unlink
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_expand_jni_ExpandToPosix
 * Method:    jni_xpn_write
 * Signature: (ILjava/nio/ByteBuffer;J)J
 */
JNIEXPORT jlong JNICALL Java_org_expand_jni_ExpandToPosix_jni_1xpn_1write
  (JNIEnv *, jobject, jint, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
