cp-local2xpn.c File Reference
#include <stdlib.h>
#include <sys/param.h>
#include <stdio.h>
#include <sys/file.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include xpn.h
Macros
#define KB 1024
#define MB (KB * KB)
#define DATAM (256 * KB)
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
DATAM
#define DATAM (256 * KB)
Definition at line 39 of file cp-local2xpn.c.
KB
#define KB 1024
Definition at line 33 of file cp-local2xpn.c.
MB
#define MB (KB * KB)
Definition at line 37 of file cp-local2xpn.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 41 of file cp-local2xpn.c.
References close(), DATAM, exit(), O_CREAT, O_RDWR, O_TRUNC, open(), read(), sum, xpn_close(), xpn_destroy(), xpn_init(), xpn_open(), and xpn_write().