cp-xpn2local.c File Reference
#include <stdlib.h>
#include <sys/param.h>
#include <stdio.h>
#include <sys/file.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include xpn.h
Macros
#define DATAM (64 * KB)
#define KB (1024)
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
DATAM
#define DATAM (64 * KB)
Definition at line 32 of file cp-xpn2local.c.
KB
#define KB (1024)
Definition at line 35 of file cp-xpn2local.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 38 of file cp-xpn2local.c.
References close(), creat(), DATAM, exit(), O_RDONLY, O_RDWR, open(), sum, write(), xpn_close(), xpn_destroy(), xpn_init(), xpn_open(), and xpn_read().