darray.h File Reference
Header file to execute operations on dynamic arrays.
#include all_system.h
#include <stdlib.h>
Macros
#define c_POINTER sizeof(T_POINTER)
#define c_POINTERTABLA sizeof(t_pointerDArray)
#define DARRAY_GetNFromDarray(t, orden) (((t) == (t_pointerDArray)NULL) ? NULL : ((t)[(orden)]))
Typedefs
typedef void * T_POINTER
A type definition for a dynamic array element.
typedef T_POINTER * t_pointerDArray
A type definition for a dynamic array.
Functions
int8_t DARRAY_InsEndDarray (t_pointerDArray *t, long *n, T_POINTER gptr)
Insert the element 'gptr' into the end of the dynamic array '*t' that allready has '*n' elements.
int8_t DARRAY_DelEndDarray (t_pointerDArray *t, long *n, T_POINTER *delGPtr)
Remove the last element from the dynamic array.
int8_t DARRAY_DelBeginDarray (t_pointerDArray *t, long *n, T_POINTER *delGPtr)
Remove the first element from the dynamic array.
int8_t DARRAY_DelNFromDarray (t_pointerDArray *t, long *n, long orden, T_POINTER *delGPtr)
Remove the 'orden'th element from the dynamic array.
int8_t DARRAY_ChangeNFromDarray (t_pointerDArray *t, long *n, long orden, T_POINTER nPtr)
Change the value of 'orden'th element from the dynamic array.
int8_t DARRAY_FreeEltosDarray (t_pointerDArray *t, long *n, void(*freef)(T_POINTER))
Remove all '*n' elements from the dynamic array.
T_POINTER DARRAY_GetNFromDarray (t_pointerDArray t, long orden)
Return the 'orden'-th element from the dynamic array.
T_POINTER DARRAY_FindEltoDarray (t_pointerDArray t, long n, T_POINTER gptr, int8_t(*findf)(T_POINTER, T_POINTER))
Find i-th element in dynamic array.
long DARRAY_GetNDarray (t_pointerDArray t)
Number of elements in the dynamic array.
int8_t DARRAY_FreeEltosDarray2 (t_pointerDArray *t, void(*freef)(T_POINTER))
Remove all elements from the dynamic array.
int8_t DARRAY_DelEltoDarray (t_pointerDArray *t, T_POINTER elto)
Remove the element with value 'elto' from the dynamic array.
int8_t DARRAY_InsEndDarray2 (t_pointerDArray *t, T_POINTER gptr)
Insert the element into the end of the dynamic array.
int8_t DARRAY_DelEndDarray2 (t_pointerDArray *t, T_POINTER *delGPtr)
Remove the last element from the dynamic array.
Detailed Description
Header file to execute operations on dynamic arrays.
Header file to insert, delete, find, get elements from a dynamic array.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file darray.h.
Macro Definition Documentation
c_POINTER
#define c_POINTER sizeof(T_POINTER)
Definition at line 50 of file darray.h.
c_POINTERTABLA
#define c_POINTERTABLA sizeof(t_pointerDArray)
Definition at line 51 of file darray.h.
DARRAY_GetNFromDarray
#define DARRAY_GetNFromDarray(t, orden) (((t) == (t_pointerDArray)NULL) ? NULL : ((t)[(orden)]))
Definition at line 295 of file darray.h.
Typedef Documentation
T_POINTER
typedef void * T_POINTER
A type definition for a dynamic array element.
Definition at line 61 of file darray.h.
t_pointerDArray
typedef T_POINTER * t_pointerDArray
A type definition for a dynamic array.
Dynamic array, NULL end.
Definition at line 68 of file darray.h.
Function Documentation
DARRAY_ChangeNFromDarray()
int8_t DARRAY_ChangeNFromDarray (t_pointerDArray * t, long * n, long orden, T_POINTER nPtr)
Change the value of 'orden'th element from the dynamic array.
The value of the 'orden'-th element of the dynamic array '*t' of '*n' elements is changed to a new element ('nPtr').
Parameters
t a dynamic array.
n number of elements in the dynamic array.
orden position (begin at 0) of element to be changed.
nPtr element that has been changed.
Returns
true (1) if element is changed and error (-1) if a problem is found.
Definition at line 176 of file darray.c.
DARRAY_DelBeginDarray()
int8_t DARRAY_DelBeginDarray (t_pointerDArray * t, long * n, T_POINTER * delGPtr)
Remove the first element from the dynamic array.
The first element of the dynamic array '*t' of '*n' elements is removed and return that element in '*delGPtr'.
Parameters
t a dynamic array.
n number of elements in the dynamic array.
delGPtr element that has been removed.
Returns
true (1) if element is removed and error (-1) if a problem is found.
See also
'DARRAY_DelEndDarray' to remove the last element.
Definition at line 108 of file darray.c.
References c_POINTER.
DARRAY_DelEltoDarray()
int8_t DARRAY_DelEltoDarray (t_pointerDArray * t, T_POINTER elto)
Remove the element with value 'elto' from the dynamic array.
Try to delete the element 'elto' from the table 't' that is NULL ended. It looks for it and if it is not found it returns FALSE. If it finds it, it deletes it and adjusts the table. It does not need the data 'number of elements' because in the search it already goes through the table.
Parameters
t a dynamic array.
elto element that has been removed.
Returns
true (1) if element is removed and error (-1) if a problem is found.
Definition at line 280 of file darray.c.
References c_POINTER.
DARRAY_DelEndDarray()
int8_t DARRAY_DelEndDarray (t_pointerDArray * t, long * n, T_POINTER * delGPtr)
Remove the last element from the dynamic array.
It deletes last element of dynamic array 't' of '*n' elements and return that element in '*delGPtr'.
Parameters
t a dynamic array.
n number of elements in the dynamic array.
delGPtr element that has been removed.
Returns
true (1) if element is removed and error (-1) if a problem is found.
See also
'DARRAY_DelBeginDarray' to remove the first element.
Definition at line 78 of file darray.c.
References c_POINTER.
Referenced by DARRAY_DelEndDarray2().
DARRAY_DelEndDarray2()
int8_t DARRAY_DelEndDarray2 (t_pointerDArray * t, T_POINTER * delGPtr)
Remove the last element from the dynamic array.
It deletes the last element of the table 't' that is NULL ended, and places in the parameter 'delGPtr' the deleted element, in case we are interested. The difference with the previous function is that, not knowing the number of elements, it 'counts' them, something that is inefficient.
Parameters
t a dynamic array.
delGPtr element that has been removed.
Returns
true (1) if element is removed and error (-1) if a problem is found.
Definition at line 334 of file darray.c.
References DARRAY_DelEndDarray().
DARRAY_DelNFromDarray()
int8_t DARRAY_DelNFromDarray (t_pointerDArray * t, long * n, long orden, T_POINTER * delGPtr)
Remove the 'orden'th element from the dynamic array.
It deletes the element of position 'order' from the dynamic array '*t', decrements the number of elements '*n' in the dynamic array and return that element that has been removed in '*delGPtr'.
Parameters
t a dynamic array.
n number of elements in the dynamic array.
orden position (begin at 0) of element to remove.
delGPtr element that has been removed.
Returns
true (1) if element is removed and error (-1) if a problem is found.
See also
'DARRAY_DelBeginDarray' to remove first element.
Definition at line 141 of file darray.c.
References c_POINTER.
DARRAY_FindEltoDarray()
T_POINTER DARRAY_FindEltoDarray (t_pointerDArray t, long n, T_POINTER gptr, int8_t(*)(T_POINTER, T_POINTER) findf)
Find i-th element in dynamic array.
Find in the dynamic array, the first element that makes that, (*findf)(gptr,darray element) == TRUE. Execute '*findf' function with 'gptr' as one parameter and i-th element as the other parameter, for all '*n' elements at the dynamic array '*t'. Using NULL elto as end tag.
Parameters
t a dynamic array.
n number of elements in the dynamic array.
gptr element for first param to 'findf'.
findf function to be used to compare i-th element and 'gptr'.
Returns
the element to be find or NULL.
Definition at line 226 of file darray.c.
DARRAY_FreeEltosDarray()
int8_t DARRAY_FreeEltosDarray (t_pointerDArray * t, long * n, void(*)(T_POINTER) freef)
Remove all '*n' elements from the dynamic array.
It goes through the dynamic array '*t', from 0..n applying the function 'freef' on each element to remove it. When finished, it does a 'free(t)'.
Parameters
t a dynamic array.
n number of elements in the dynamic array.
freef the free function to be used.
Returns
true (1) if elements are freeded and error (-1) if a problem is found.
Definition at line 198 of file darray.c.
DARRAY_FreeEltosDarray2()
int8_t DARRAY_FreeEltosDarray2 (t_pointerDArray * t, void(*)(T_POINTER) freef)
Remove all elements from the dynamic array.
It goes through the dynamic array '*t', from 0..n applying the function 'freef' on each element to remove it. When finished, it does a 'free(t)'.
Parameters
t a dynamic array.
freef the free function to be used.
Returns
true (1) if elements are removed and error (-1) if a problem is found.
Definition at line 257 of file darray.c.
DARRAY_GetNDarray()
long DARRAY_GetNDarray (t_pointerDArray t)
Number of elements in the dynamic array.
Return the number of elements in the 't' dynamic array, in a NULL ended array.
Parameters
t a dynamic array.
Returns
the number of element in the 't' array.
Definition at line 243 of file darray.c.
DARRAY_GetNFromDarray()
T_POINTER DARRAY_GetNFromDarray (t_pointerDArray t, long orden)
Return the 'orden'-th element from the dynamic array.
Return the 'orden'-th element in the 't' dynamic array, in a NULL ended array.
Parameters
t a dynamic array.
orden position (begin at 0) of element to return.
Returns
the element at this position or NULL.
Warning
If order is 3, returns t[3] (i.e., the fourth). It does not check that it goes outside the array bounds.
DARRAY_InsEndDarray()
int8_t DARRAY_InsEndDarray (t_pointerDArray * t, long * n, T_POINTER gptr)
Insert the element 'gptr' into the end of the dynamic array '*t' that allready has '*n' elements.
Inserts 'gptr' at the end of table 't', with '(*n)' pointers and adds one more ((*n) = (*n) + 1)
Parameters
t a dynamic array.
n number of elements in the dynamic array.
gptr the element that has been inserted.
Returns
true (1) if element is inserted and error (-1) if a problem is found.
See also
'DARRAY_InsEndDarray2' if dynamic array is NULL terminated.
Definition at line 41 of file darray.c.
References c_POINTER.
Referenced by DARRAY_InsEndDarray2(), and dtable_insert().
DARRAY_InsEndDarray2()
int8_t DARRAY_InsEndDarray2 (t_pointerDArray * t, T_POINTER gptr)
Insert the element into the end of the dynamic array.
Insert the element 'gptr' into the end of the dynamic array '*t' that is NULL ended. The difference with the previous function is that, not knowing the number of elements, it 'counts' them, which is inefficient. Remember, the table of pointers ends with the NULL pointer.
Parameters
t a dynamic array.
gptr element that has been inserted.
Returns
true (1) if element is inserted and error (-1) if a problem is found.
Definition at line 317 of file darray.c.
References DARRAY_InsEndDarray().