debug_msg.c File Reference
File to execute debug messages.
#include base/debug_msg.h
Functions
void debug_msg_init (void)
int debug_msg_printf (int src_type, char *src_fname, long src_line, FILE *fd, char *msg_fmt,...)
void DEBUG_MSG_setPrinter (int(*printer)(const char *, va_list))
Set 'printer' dispacher.
void DEBUG_MSG_doPrint (char *fto,...)
void DEBUG_MSG_VPrintF (int line, char *name, long pid, int type, char *fto, va_list vl)
Write a message.
void DEBUG_MSG_PrintF (int line, char *name, long pid, int type, char *fto,...)
Write a message.
Variables
int(* DEBUG_MSG_PrintMsg)(const char *, va_list) = NULL
Detailed Description
File to execute debug messages.
File to execute debug messages of type information, warnings or error.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file debug_msg.c.
Function Documentation
DEBUG_MSG_doPrint()
void DEBUG_MSG_doPrint (char * fto, ...)
Definition at line 97 of file debug_msg.c.
References DEBUG_MSG_PrintMsg.
Referenced by DEBUG_MSG_VPrintF().
debug_msg_init()
void debug_msg_init (void)
Definition at line 47 of file debug_msg.c.
Referenced by mpi_server_up(), tcp_server_down(), and tcp_server_up().
DEBUG_MSG_PrintF()
void DEBUG_MSG_PrintF (int line, char * name, long pid, int type, char * fto, ...)
Write a message.
Write a message using the format and arguments given to it.
Parameters
line the line of code where message is generated.
name the file name at the code where message is generated.
pid the process that send this message.
type the type of message.
fto the message format.
Returns
Nothing.
Definition at line 134 of file debug_msg.c.
References DEBUG_MSG_PrintMsg, and DEBUG_MSG_VPrintF().
debug_msg_printf()
int debug_msg_printf (int src_type, char * src_fname, long src_line, FILE * fd, char * msg_fmt, ...)
Definition at line 53 of file debug_msg.c.
DEBUG_MSG_setPrinter()
void DEBUG_MSG_setPrinter (int(*)(const char *, va_list) printer)
Set 'printer' dispacher.
Parameters
printer the printer function to be used.
Returns
Nothing.
Definition at line 91 of file debug_msg.c.
References DEBUG_MSG_PrintMsg.
DEBUG_MSG_VPrintF()
void DEBUG_MSG_VPrintF (int line, char * name, long pid, int type, char * fto, va_list vl)
Write a message.
Write a message using the format and the argument list given to it.
Parameters
line the line of code where message is generated.
name the file name at the code where message is generated.
pid the process that send this message.
type the type of message.
fto the message format.
vl the argument list.
Returns
Nothing.
Definition at line 111 of file debug_msg.c.
References DEBUG_MSG_doPrint(), DEBUG_MSG_PrintMsg, and STRING_MISC_Dvsprintf().
Referenced by DEBUG_MSG_PrintF().
Variable Documentation
DEBUG_MSG_PrintMsg
int(* DEBUG_MSG_PrintMsg) (const char *, va_list) (const char * , va_list) = NULL
Definition at line 41 of file debug_msg.c.
Referenced by DEBUG_MSG_doPrint(), DEBUG_MSG_PrintF(), DEBUG_MSG_setPrinter(), and DEBUG_MSG_VPrintF().