debug_msg.h File Reference
Header file for executing debug messages.
#include all_system.h
#include string_misc.h
Macros
#define debug_error(...)
#define debug_warning(...)
#define debug_info(...)
#define DEBUG_BEGIN() debug_info(Begin %s()\n, __func__)
#define DEBUG_END() debug_info(End %s(), errno=%d\n, __func__, errno)
Functions
void debug_msg_init (void)
int debug_msg_printf (int src_type, char *src_fname, long src_line, FILE *fd, char *msg_fmt,...)
void DEBUG_MSG_setPrinter (int(*printer)(const char *, va_list))
Set 'printer' dispacher.
void DEBUG_MSG_VPrintF (int line, char *name, long pid, int type, char *fto, va_list vl)
Write a message.
void DEBUG_MSG_PrintF (int line, char *name, long pid, int type, char *fto,...)
Write a message.
Detailed Description
Header file for executing debug messages.
Header file to execute debug messages of type information, warnings or error.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file debug_msg.h.
Macro Definition Documentation
DEBUG_BEGIN
#define DEBUG_BEGIN() debug_info(Begin %s()\n, __func__)
Definition at line 61 of file debug_msg.h.
DEBUG_END
#define DEBUG_END() debug_info(End %s(), errno=%d\n, __func__, errno)
Definition at line 64 of file debug_msg.h.
debug_error
#define debug_error(...)
Definition at line 55 of file debug_msg.h.
debug_info
#define debug_info(...)
Definition at line 57 of file debug_msg.h.
debug_warning
#define debug_warning(...)
Definition at line 56 of file debug_msg.h.
Function Documentation
debug_msg_init()
void debug_msg_init (void)
Definition at line 47 of file debug_msg.c.
Referenced by mpi_server_up(), tcp_server_down(), and tcp_server_up().
DEBUG_MSG_PrintF()
void DEBUG_MSG_PrintF (int line, char * name, long pid, int type, char * fto, ...)
Write a message.
Write a message using the format and arguments given to it.
Parameters
line the line of code where message is generated.
name the file name at the code where message is generated.
pid the process that send this message.
type the type of message.
fto the message format.
Returns
Nothing.
Definition at line 134 of file debug_msg.c.
References DEBUG_MSG_PrintMsg, and DEBUG_MSG_VPrintF().
debug_msg_printf()
int debug_msg_printf (int src_type, char * src_fname, long src_line, FILE * fd, char * msg_fmt, ...)
Definition at line 53 of file debug_msg.c.
DEBUG_MSG_setPrinter()
void DEBUG_MSG_setPrinter (int(*)(const char *, va_list) printer)
Set 'printer' dispacher.
Parameters
printer the printer function to be used.
Returns
Nothing.
Definition at line 91 of file debug_msg.c.
References DEBUG_MSG_PrintMsg.
DEBUG_MSG_VPrintF()
void DEBUG_MSG_VPrintF (int line, char * name, long pid, int type, char * fto, va_list vl)
Write a message.
Write a message using the format and the argument list given to it.
Parameters
line the line of code where message is generated.
name the file name at the code where message is generated.
pid the process that send this message.
type the type of message.
fto the message format.
vl the argument list.
Returns
Nothing.
Definition at line 111 of file debug_msg.c.
References DEBUG_MSG_doPrint(), DEBUG_MSG_PrintMsg, and STRING_MISC_Dvsprintf().
Referenced by DEBUG_MSG_PrintF().