filesystem.c File Reference
#include filesystem.h
Functions
int aux_clear_dirs (char *path)
int aux_get_dirs (char *path, int n, char *s)
void * filesystem_async_close (void *arg)
int filesystem_creat (char *pathname, mode_t mode)
Create a file.
int filesystem_open (char *pathname, int flags)
Open a file.
int filesystem_open2 (char *pathname, int flags, mode_t mode)
Open a file.
int filesystem_close (int fd)
Close a file.
long filesystem_read (int read_fd2, void *buffer, int buffer_size)
Read a file.
long filesystem_write (int write_fd2, void *buffer, int num_bytes_to_write)
Write a file.
int filesystem_rename (char *old_pathname, char *new_pathname)
Rename a file.
int filesystem_mkpath (char *pathname)
'TODO'.
int filesystem_mkdir (char *pathname, mode_t mode)
'TODO'.
int filesystem_rmdir (char *pathname)
'TODO'.
DIR * filesystem_opendir (char *pathname)
'TODO'.
struct dirent * filesystem_readdir (DIR *dirp)
'TODO'.
int filesystem_closedir (DIR *dirp)
'TODO'.
off_t filesystem_lseek (int fd, off_t offset, int whence)
'TODO'.
int filesystem_unlink (char *pathname)
'TODO'.
int filesystem_stat (char *pathname, struct stat *sinfo)
'TODO'.
Function Documentation
aux_clear_dirs()
int aux_clear_dirs (char * path)
Definition at line 36 of file filesystem.c.
Referenced by aux_get_dirs().
aux_get_dirs()
int aux_get_dirs (char * path, int n, char * s)
Definition at line 70 of file filesystem.c.
References aux_clear_dirs(), and PATH_MAX.
Referenced by filesystem_mkpath().
filesystem_async_close()
void * filesystem_async_close (void * arg)
Definition at line 132 of file filesystem.c.
References debug_warning, and real_posix_close.
Referenced by filesystem_close().
filesystem_close()
int filesystem_close (int fd)
Close a file.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 238 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, filesystem_async_close(), and real_posix_close.
Referenced by mpi_server_op_close_ws(), mpi_server_op_creat_wos(), mpi_server_op_flush(), mpi_server_op_open_wos(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_write_wos(), tcp_server_op_close_ws(), tcp_server_op_creat_wos(), tcp_server_op_flush(), tcp_server_op_open_wos(), tcp_server_op_preload(), tcp_server_op_read_wos(), and tcp_server_op_write_wos().
filesystem_closedir()
int filesystem_closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 510 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_closedir.
Referenced by mpi_server_op_closedir(), and tcp_server_op_closedir().
filesystem_creat()
int filesystem_creat (char * pathname, mode_t mode)
Create a file.
'TODO'.
Parameters
pathname 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 156 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_creat.
Referenced by mpi_server_op_creat_wos(), mpi_server_op_creat_ws(), mpi_server_op_preload(), tcp_server_op_creat_wos(), tcp_server_op_creat_ws(), and tcp_server_op_preload().
filesystem_lseek()
off_t filesystem_lseek (int fd, off_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 536 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_lseek.
Referenced by mpi_server_op_flush(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_read_ws(), mpi_server_op_write_wos(), mpi_server_op_write_ws(), tcp_server_op_flush(), tcp_server_op_preload(), tcp_server_op_read_wos(), tcp_server_op_read_ws(), tcp_server_op_write_wos(), and tcp_server_op_write_ws().
filesystem_mkdir()
int filesystem_mkdir (char * pathname, mode_t mode)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 406 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_mkdir.
Referenced by mpi_server_op_mkdir(), and tcp_server_op_mkdir().
filesystem_mkpath()
int filesystem_mkpath (char * pathname)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
Returns
'TODO'.
Definition at line 383 of file filesystem.c.
References aux_get_dirs(), DEBUG_BEGIN, DEBUG_END, debug_warning, PATH_MAX, and real_posix_mkdir.
Referenced by mpi_server_op_creat_wos(), mpi_server_op_creat_ws(), tcp_server_op_creat_wos(), and tcp_server_op_creat_ws().
filesystem_open()
int filesystem_open (char * pathname, int flags)
Open a file.
'TODO'.
Parameters
pathname 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 186 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_open.
Referenced by mpi_server_op_flush(), mpi_server_op_open_wos(), mpi_server_op_open_ws(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_write_wos(), tcp_server_op_flush(), tcp_server_op_open_wos(), tcp_server_op_open_ws(), tcp_server_op_preload(), tcp_server_op_read_wos(), and tcp_server_op_write_wos().
filesystem_open2()
int filesystem_open2 (char * pathname, int flags, mode_t mode)
Open a file.
'TODO'.
Parameters
pathname 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 212 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_open2.
filesystem_opendir()
DIR * filesystem_opendir (char * name)
'TODO'.
'TODO'.
Parameters
name 'TODO'.
Returns
'TODO'.
Definition at line 458 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_opendir.
Referenced by mpi_server_op_opendir(), and tcp_server_op_opendir().
filesystem_read()
long filesystem_read (int read_fd2, void * buffer, int buffer_size)
Read a file.
'TODO'.
Parameters
read_fd2 'TODO'.
buffer 'TODO'.
buffer_size 'TODO'.
Returns
'TODO'.
Definition at line 282 of file filesystem.c.
References debug_error, debug_warning, and real_posix_read.
Referenced by mpi_server_op_flush(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_read_ws(), tcp_server_op_flush(), tcp_server_op_preload(), tcp_server_op_read_wos(), and tcp_server_op_read_ws().
filesystem_readdir()
struct dirent * filesystem_readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 484 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_readdir.
Referenced by mpi_server_op_readdir(), and tcp_server_op_readdir().
filesystem_rename()
int filesystem_rename (char * old_pathname, char * new_pathname)
Rename a file.
'TODO'.
Parameters
old_pathname 'TODO'.
new_pathname 'TODO'.
Returns
'TODO'.
Definition at line 353 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_rename.
Referenced by mpi_server_op_rename(), and tcp_server_op_rename().
filesystem_rmdir()
int filesystem_rmdir (char * pathname)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
Returns
'TODO'.
Definition at line 432 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_rmdir.
Referenced by mpi_server_op_rmdir(), mpi_server_op_rmdir_async(), and tcp_server_op_rmdir().
filesystem_stat()
int filesystem_stat (char * pathname, struct stat * sinfo)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
sinfo 'TODO'.
Returns
'TODO'.
Definition at line 588 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_stat.
Referenced by mpi_server_op_getattr(), and tcp_server_op_getattr().
filesystem_unlink()
int filesystem_unlink (char * pathname)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
Returns
'TODO'.
Definition at line 562 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_unlink.
Referenced by mpi_server_op_rm(), mpi_server_op_rm_async(), and tcp_server_op_rm().
filesystem_write()
long filesystem_write (int write_fd2, void * buffer, int num_bytes_to_write)
Write a file.
'TODO'.
Parameters
write_fd2 'TODO'.
buffer 'TODO'.
num_bytes_to_write 'TODO'.
Returns
'TODO'.
Definition at line 321 of file filesystem.c.
References debug_error, debug_warning, and real_posix_write.
Referenced by mpi_server_op_flush(), mpi_server_op_preload(), mpi_server_op_write_wos(), mpi_server_op_write_ws(), tcp_server_op_flush(), tcp_server_op_preload(), tcp_server_op_write_wos(), and tcp_server_op_write_ws().