filesystem.h File Reference
Header file to 'TODO'.
#include all_system.h
#include syscall_proxies.h
#include base/utils.h
#include <pthread.h>
#include <sys/stat.h>
#include <sys/types.h>
Macros
#define real_posix_creat(path, mode) creat(path, mode)
#define real_posix_open(path, flags) open(path, flags)
#define real_posix_open2(path, flags, mode) open(path, flags, mode)
#define real_posix_close(fd) close(fd)
#define real_posix_lseek(fd, offset, whence) lseek(fd, offset, whence)
#define real_posix_lseek64(fd, offset, whence) lseek64(fd, offset, whence)
#define real_posix_read(fd, buffer, buffer_size) read(fd, buffer, buffer_size)
#define real_posix_write(fd, buffer, buffer_size) write(fd, buffer, buffer_size)
#define real_posix_rename(old_path, new_path) rename(old_path, new_path)
#define real_posix_mkdir(pathname, mode) mkdir(pathname, mode)
#define real_posix_rmdir(pathname) rmdir(pathname)
#define real_posix_unlink(pathname) unlink(pathname)
#define real_posix_stat(pathname, info) stat(pathname, info)
#define real_posix_opendir(pathname) opendir(pathname)
#define real_posix_readdir(dirptr) readdir(dirptr)
#define real_posix_closedir(dirptr) closedir(dirptr)
Typedefs
typedef off_t offset_t
Library for 'TODO'.
Functions
int filesystem_creat (char *pathname, mode_t mode)
Create a file.
int filesystem_open (char *pathname, int flags)
Open a file.
int filesystem_open2 (char *pathname, int flags, mode_t mode)
Open a file.
int filesystem_close (int fd)
Close a file.
long filesystem_read (int read_fd2, void *buffer, int buffer_size)
Read a file.
long filesystem_write (int write_fd2, void *buffer, int num_bytes_to_write)
Write a file.
int filesystem_rename (char *old_pathname, char *new_pathname)
Rename a file.
int filesystem_mkpath (char *pathname)
'TODO'.
int filesystem_mkdir (char *pathname, mode_t mode)
'TODO'.
int filesystem_rmdir (char *pathname)
'TODO'.
DIR * filesystem_opendir (char *name)
'TODO'.
struct dirent * filesystem_readdir (DIR *dirp)
'TODO'.
int filesystem_closedir (DIR *dirp)
'TODO'.
off_t filesystem_lseek (int fd, off_t offset, int whence)
'TODO'.
int filesystem_unlink (char *pathname)
'TODO'.
int filesystem_stat (char *pathname, struct stat *sinfo)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file filesystem.h.
Macro Definition Documentation
real_posix_close
#define real_posix_close(fd) close(fd)
Definition at line 263 of file filesystem.h.
real_posix_closedir
#define real_posix_closedir(dirptr) closedir(dirptr)
Definition at line 279 of file filesystem.h.
real_posix_creat
#define real_posix_creat(path, mode) creat(path, mode)
Definition at line 260 of file filesystem.h.
real_posix_lseek
#define real_posix_lseek(fd, offset, whence) lseek(fd, offset, whence)
Definition at line 265 of file filesystem.h.
real_posix_lseek64
#define real_posix_lseek64(fd, offset, whence) lseek64(fd, offset, whence)
Definition at line 266 of file filesystem.h.
real_posix_mkdir
#define real_posix_mkdir(pathname, mode) mkdir(pathname, mode)
Definition at line 272 of file filesystem.h.
real_posix_open
#define real_posix_open(path, flags) open(path, flags)
Definition at line 261 of file filesystem.h.
real_posix_open2
#define real_posix_open2(path, flags, mode) open(path, flags, mode)
Definition at line 262 of file filesystem.h.
real_posix_opendir
#define real_posix_opendir(pathname) opendir(pathname)
Definition at line 277 of file filesystem.h.
real_posix_read
#define real_posix_read(fd, buffer, buffer_size) read(fd, buffer, buffer_size)
Definition at line 267 of file filesystem.h.
real_posix_readdir
#define real_posix_readdir(dirptr) readdir(dirptr)
Definition at line 278 of file filesystem.h.
real_posix_rename
#define real_posix_rename(old_path, new_path) rename(old_path, new_path)
Definition at line 270 of file filesystem.h.
real_posix_rmdir
#define real_posix_rmdir(pathname) rmdir(pathname)
Definition at line 273 of file filesystem.h.
real_posix_stat
#define real_posix_stat(pathname, info) stat(pathname, info)
Definition at line 275 of file filesystem.h.
real_posix_unlink
#define real_posix_unlink(pathname) unlink(pathname)
Definition at line 274 of file filesystem.h.
real_posix_write
#define real_posix_write(fd, buffer, buffer_size) write(fd, buffer, buffer_size)
Definition at line 268 of file filesystem.h.
Typedef Documentation
offset_t
typedef off_t offset_t
Library for 'TODO'.
Library for 'TODO' Library for 'TODO' Library for 'TODO' Library for 'TODO' Library for 'TODO'
Definition at line 47 of file filesystem.h.
Function Documentation
filesystem_close()
int filesystem_close (int fd)
Close a file.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 238 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, filesystem_async_close(), and real_posix_close.
Referenced by mpi_server_op_close_ws(), mpi_server_op_creat_wos(), mpi_server_op_flush(), mpi_server_op_open_wos(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_write_wos(), tcp_server_op_close_ws(), tcp_server_op_creat_wos(), tcp_server_op_flush(), tcp_server_op_open_wos(), tcp_server_op_preload(), tcp_server_op_read_wos(), and tcp_server_op_write_wos().
filesystem_closedir()
int filesystem_closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 510 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_closedir.
Referenced by mpi_server_op_closedir(), and tcp_server_op_closedir().
filesystem_creat()
int filesystem_creat (char * pathname, mode_t mode)
Create a file.
'TODO'.
Parameters
pathname 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 156 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_creat.
Referenced by mpi_server_op_creat_wos(), mpi_server_op_creat_ws(), mpi_server_op_preload(), tcp_server_op_creat_wos(), tcp_server_op_creat_ws(), and tcp_server_op_preload().
filesystem_lseek()
off_t filesystem_lseek (int fd, off_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 536 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_lseek.
Referenced by mpi_server_op_flush(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_read_ws(), mpi_server_op_write_wos(), mpi_server_op_write_ws(), tcp_server_op_flush(), tcp_server_op_preload(), tcp_server_op_read_wos(), tcp_server_op_read_ws(), tcp_server_op_write_wos(), and tcp_server_op_write_ws().
filesystem_mkdir()
int filesystem_mkdir (char * pathname, mode_t mode)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 406 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_mkdir.
Referenced by mpi_server_op_mkdir(), and tcp_server_op_mkdir().
filesystem_mkpath()
int filesystem_mkpath (char * pathname)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
Returns
'TODO'.
Definition at line 383 of file filesystem.c.
References aux_get_dirs(), DEBUG_BEGIN, DEBUG_END, debug_warning, PATH_MAX, and real_posix_mkdir.
Referenced by mpi_server_op_creat_wos(), mpi_server_op_creat_ws(), tcp_server_op_creat_wos(), and tcp_server_op_creat_ws().
filesystem_open()
int filesystem_open (char * pathname, int flags)
Open a file.
'TODO'.
Parameters
pathname 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 186 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_open.
Referenced by mpi_server_op_flush(), mpi_server_op_open_wos(), mpi_server_op_open_ws(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_write_wos(), tcp_server_op_flush(), tcp_server_op_open_wos(), tcp_server_op_open_ws(), tcp_server_op_preload(), tcp_server_op_read_wos(), and tcp_server_op_write_wos().
filesystem_open2()
int filesystem_open2 (char * pathname, int flags, mode_t mode)
Open a file.
'TODO'.
Parameters
pathname 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 212 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_open2.
filesystem_opendir()
DIR * filesystem_opendir (char * name)
'TODO'.
'TODO'.
Parameters
name 'TODO'.
Returns
'TODO'.
Definition at line 458 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_opendir.
Referenced by mpi_server_op_opendir(), and tcp_server_op_opendir().
filesystem_read()
long filesystem_read (int read_fd2, void * buffer, int buffer_size)
Read a file.
'TODO'.
Parameters
read_fd2 'TODO'.
buffer 'TODO'.
buffer_size 'TODO'.
Returns
'TODO'.
Definition at line 282 of file filesystem.c.
References debug_error, debug_warning, and real_posix_read.
Referenced by mpi_server_op_flush(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_read_ws(), tcp_server_op_flush(), tcp_server_op_preload(), tcp_server_op_read_wos(), and tcp_server_op_read_ws().
filesystem_readdir()
struct dirent * filesystem_readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 484 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_readdir.
Referenced by mpi_server_op_readdir(), and tcp_server_op_readdir().
filesystem_rename()
int filesystem_rename (char * old_pathname, char * new_pathname)
Rename a file.
'TODO'.
Parameters
old_pathname 'TODO'.
new_pathname 'TODO'.
Returns
'TODO'.
Definition at line 353 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_rename.
Referenced by mpi_server_op_rename(), and tcp_server_op_rename().
filesystem_rmdir()
int filesystem_rmdir (char * pathname)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
Returns
'TODO'.
Definition at line 432 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_rmdir.
Referenced by mpi_server_op_rmdir(), mpi_server_op_rmdir_async(), and tcp_server_op_rmdir().
filesystem_stat()
int filesystem_stat (char * pathname, struct stat * sinfo)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
sinfo 'TODO'.
Returns
'TODO'.
Definition at line 588 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_stat.
Referenced by mpi_server_op_getattr(), and tcp_server_op_getattr().
filesystem_unlink()
int filesystem_unlink (char * pathname)
'TODO'.
'TODO'.
Parameters
pathname 'TODO'.
Returns
'TODO'.
Definition at line 562 of file filesystem.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, and real_posix_unlink.
Referenced by mpi_server_op_rm(), mpi_server_op_rm_async(), and tcp_server_op_rm().
filesystem_write()
long filesystem_write (int write_fd2, void * buffer, int num_bytes_to_write)
Write a file.
'TODO'.
Parameters
write_fd2 'TODO'.
buffer 'TODO'.
num_bytes_to_write 'TODO'.
Returns
'TODO'.
Definition at line 321 of file filesystem.c.
References debug_error, debug_warning, and real_posix_write.
Referenced by mpi_server_op_flush(), mpi_server_op_preload(), mpi_server_op_write_wos(), mpi_server_op_write_ws(), tcp_server_op_flush(), tcp_server_op_preload(), tcp_server_op_write_wos(), and tcp_server_op_write_ws().