mpi_server_d2xpn.h File Reference
Header file to 'TODO'.
#include <sys/param.h>
#include <stdio.h>
#include <sys/file.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include all_system.h
#include base/utils.h
#include mpi_server_params.h
#include mpi_server_ops.h
#include xpn.h
Macros
#define PRELOAD_SYNC 0
#define PRELOAD_ASYNC 1
Functions
int mpi_server_d2xpn (mpi_server_param_st *params, char *origen, char *destino)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file mpi_server_d2xpn.h.
Macro Definition Documentation
PRELOAD_ASYNC
#define PRELOAD_ASYNC 1
Definition at line 55 of file mpi_server_d2xpn.h.
PRELOAD_SYNC
#define PRELOAD_SYNC 0
Definition at line 54 of file mpi_server_d2xpn.h.
Function Documentation
mpi_server_d2xpn()
int mpi_server_d2xpn (mpi_server_param_st * params, char * origen, char * destino)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
origen 'TODO'.
destino 'TODO'.
Returns
'TODO'.
Definition at line 147 of file mpi_server_d2xpn.c.
References debug_info, mpi_server_param_st::dirbase, MPI_SERVER_PATH_DEFAULT, mylock(), myunlock(), O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), params, PATH_MAX, mpi_server_param_st::rank, st, xpn_init(), and xpn_open().