mpi_server_ops.h File Reference
Header file to 'TODO'.
#include <libgen.h>
#include all_system.h
#include base/filesystem.h
#include base/urlstr.h
#include base/utils.h
#include base/workers.h
#include mpi_server_ops.h
#include mpi_server_comm.h
#include mpi_server_d2xpn.h
#include mpi_server_params.h
Data Structures
struct st_mpi_server_open
This is a struct.
struct st_mpi_server_open_req
This is a struct.
struct st_mpi_server_creat
This is a struct.
struct st_mpi_server_read
This is a struct.
struct st_mpi_server_read_req
This is a struct.
struct st_mpi_server_write
This is a struct.
struct st_mpi_server_write_req
This is a struct.
struct st_mpi_server_close
This is a struct.
struct st_mpi_server_rename
This is a struct.
struct st_mpi_server_rm
This is a struct.
struct st_mpi_server_getattr
This is a struct.
struct st_mpi_server_setattr
This is a struct.
struct st_mpi_server_attr_req
This is a struct.
struct st_mpi_server_mkdir
This is a struct.
struct st_mpi_server_opendir
This is a struct.
struct st_mpi_server_readdir
This is a struct.
struct st_mpi_server_direntry
This is a struct.
struct st_mpi_server_closedir
This is a struct.
struct st_mpi_server_rmdir
This is a struct.
struct st_mpi_server_flush
This is a struct.
struct st_mpi_server_preload
This is a struct.
struct st_mpi_server_end
This is a struct.
struct st_mpi_server_msg
This is a struct.
Macros
#define MPI_SERVER_ID 32
#define MPI_SERVER_OPEN_FILE_WS 0
#define MPI_SERVER_CREAT_FILE_WS 1
#define MPI_SERVER_READ_FILE_WS 2
#define MPI_SERVER_WRITE_FILE_WS 3
#define MPI_SERVER_CLOSE_FILE_WS 4
#define MPI_SERVER_RM_FILE 5
#define MPI_SERVER_RM_FILE_ASYNC 6
#define MPI_SERVER_RENAME_FILE 7
#define MPI_SERVER_GETATTR_FILE 8
#define MPI_SERVER_SETATTR_FILE 9
#define MPI_SERVER_OPEN_FILE_WOS 100
#define MPI_SERVER_CREAT_FILE_WOS 101
#define MPI_SERVER_READ_FILE_WOS 102
#define MPI_SERVER_WRITE_FILE_WOS 103
#define MPI_SERVER_MKDIR_DIR 20
#define MPI_SERVER_RMDIR_DIR 21
#define MPI_SERVER_RMDIR_DIR_ASYNC 22
#define MPI_SERVER_OPENDIR_DIR 23
#define MPI_SERVER_READDIR_DIR 24
#define MPI_SERVER_CLOSEDIR_DIR 25
#define MPI_SERVER_FLUSH_FILE 40
#define MPI_SERVER_PRELOAD_FILE 41
#define MPI_SERVER_STATFS_DIR 60
#define MPI_SERVER_GETNODENAME 61
#define MPI_SERVER_GETID 62
#define MPI_SERVER_FINALIZE 80
#define MPI_SERVER_DISCONNECT 81
#define MPI_SERVER_END -1
Functions
char * mpi_server_op2string (int op_code)
'TODO'.
int mpi_server_do_operation (struct st_th *th, int *the_end)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file mpi_server/mpi_server_ops.h.
Macro Definition Documentation
MPI_SERVER_CLOSE_FILE_WS
#define MPI_SERVER_CLOSE_FILE_WS 4
Definition at line 67 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_CLOSEDIR_DIR
#define MPI_SERVER_CLOSEDIR_DIR 25
Definition at line 90 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_CREAT_FILE_WOS
#define MPI_SERVER_CREAT_FILE_WOS 101
Definition at line 78 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_CREAT_FILE_WS
#define MPI_SERVER_CREAT_FILE_WS 1
Definition at line 64 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_DISCONNECT
#define MPI_SERVER_DISCONNECT 81
Definition at line 109 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_END
#define MPI_SERVER_END -1
Definition at line 110 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_FINALIZE
#define MPI_SERVER_FINALIZE 80
Definition at line 108 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_FLUSH_FILE
#define MPI_SERVER_FLUSH_FILE 40
Definition at line 95 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_GETATTR_FILE
#define MPI_SERVER_GETATTR_FILE 8
Definition at line 71 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_GETID
#define MPI_SERVER_GETID 62
Definition at line 103 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_GETNODENAME
#define MPI_SERVER_GETNODENAME 61
Definition at line 102 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_ID
#define MPI_SERVER_ID 32
Definition at line 53 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_MKDIR_DIR
#define MPI_SERVER_MKDIR_DIR 20
Definition at line 85 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_OPEN_FILE_WOS
#define MPI_SERVER_OPEN_FILE_WOS 100
Definition at line 77 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_OPEN_FILE_WS
#define MPI_SERVER_OPEN_FILE_WS 0
Definition at line 63 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_OPENDIR_DIR
#define MPI_SERVER_OPENDIR_DIR 23
Definition at line 88 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_PRELOAD_FILE
#define MPI_SERVER_PRELOAD_FILE 41
Definition at line 96 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_READ_FILE_WOS
#define MPI_SERVER_READ_FILE_WOS 102
Definition at line 79 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_READ_FILE_WS
#define MPI_SERVER_READ_FILE_WS 2
Definition at line 65 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_READDIR_DIR
#define MPI_SERVER_READDIR_DIR 24
Definition at line 89 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_RENAME_FILE
#define MPI_SERVER_RENAME_FILE 7
Definition at line 70 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_RM_FILE
#define MPI_SERVER_RM_FILE 5
Definition at line 68 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_RM_FILE_ASYNC
#define MPI_SERVER_RM_FILE_ASYNC 6
Definition at line 69 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_RMDIR_DIR
#define MPI_SERVER_RMDIR_DIR 21
Definition at line 86 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_RMDIR_DIR_ASYNC
#define MPI_SERVER_RMDIR_DIR_ASYNC 22
Definition at line 87 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_SETATTR_FILE
#define MPI_SERVER_SETATTR_FILE 9
Definition at line 72 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_STATFS_DIR
#define MPI_SERVER_STATFS_DIR 60
Definition at line 101 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_WRITE_FILE_WOS
#define MPI_SERVER_WRITE_FILE_WOS 103
Definition at line 80 of file mpi_server/mpi_server_ops.h.
MPI_SERVER_WRITE_FILE_WS
#define MPI_SERVER_WRITE_FILE_WS 3
Definition at line 66 of file mpi_server/mpi_server_ops.h.
Function Documentation
mpi_server_do_operation()
int mpi_server_do_operation (struct st_th * th, int * the_end)
'TODO'.
'TODO'
Parameters
th 'TODO'.
the_end 'TODO'.
Returns
'TODO'.
Definition at line 494 of file mpi_server_ops.c.
References DEBUG_BEGIN, DEBUG_END, MPI_SERVER_CLOSE_FILE_WS, MPI_SERVER_CLOSEDIR_DIR, mpi_server_comm_read_data(), MPI_SERVER_CREAT_FILE_WOS, MPI_SERVER_CREAT_FILE_WS, MPI_SERVER_DISCONNECT, MPI_SERVER_FINALIZE, MPI_SERVER_FLUSH_FILE, MPI_SERVER_GETATTR_FILE, MPI_SERVER_GETNODENAME, MPI_SERVER_MKDIR_DIR, mpi_server_op_close_ws(), mpi_server_op_closedir(), mpi_server_op_creat_wos(), mpi_server_op_creat_ws(), mpi_server_op_flush(), mpi_server_op_getattr(), mpi_server_op_getnodename(), mpi_server_op_mkdir(), mpi_server_op_open_wos(), mpi_server_op_open_ws(), mpi_server_op_opendir(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_read_ws(), mpi_server_op_readdir(), mpi_server_op_rename(), mpi_server_op_rm(), mpi_server_op_rm_async(), mpi_server_op_rmdir(), mpi_server_op_rmdir_async(), mpi_server_op_setattr(), mpi_server_op_write_wos(), mpi_server_op_write_ws(), MPI_SERVER_OPEN_FILE_WOS, MPI_SERVER_OPEN_FILE_WS, MPI_SERVER_OPENDIR_DIR, MPI_SERVER_PRELOAD_FILE, MPI_SERVER_READ_FILE_WOS, MPI_SERVER_READ_FILE_WS, MPI_SERVER_READDIR_DIR, MPI_SERVER_RENAME_FILE, MPI_SERVER_RM_FILE, MPI_SERVER_RM_FILE_ASYNC, MPI_SERVER_RMDIR_DIR, MPI_SERVER_RMDIR_DIR_ASYNC, MPI_SERVER_SETATTR_FILE, MPI_SERVER_WRITE_FILE_WOS, MPI_SERVER_WRITE_FILE_WS, st_mpi_server_msg::op_close, st_mpi_server_msg::op_closedir, st_mpi_server_msg::op_creat, st_mpi_server_msg::op_flush, st_mpi_server_msg::op_getattr, st_mpi_server_msg::op_mkdir, st_mpi_server_msg::op_open, st_mpi_server_msg::op_opendir, st_mpi_server_msg::op_preload, st_mpi_server_msg::op_read, st_mpi_server_msg::op_readdir, st_mpi_server_msg::op_rename, st_mpi_server_msg::op_rm, st_mpi_server_msg::op_rmdir, st_mpi_server_msg::op_setattr, st_mpi_server_msg::op_write, st_th::params, st_th::rank_client_id, st_th::sd, the_end, st_th::type_op, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_run().
mpi_server_op2string()
char * mpi_server_op2string (int op_code)
'TODO'.
'TODO'
Parameters
op_code 'TODO'.
Returns
'TODO'.
Definition at line 41 of file mpi_server_ops.c.
References MPI_SERVER_CLOSE_FILE_WS, MPI_SERVER_CLOSEDIR_DIR, MPI_SERVER_CREAT_FILE_WOS, MPI_SERVER_CREAT_FILE_WS, MPI_SERVER_DISCONNECT, MPI_SERVER_END, MPI_SERVER_FINALIZE, MPI_SERVER_FLUSH_FILE, MPI_SERVER_GETATTR_FILE, MPI_SERVER_GETID, MPI_SERVER_GETNODENAME, MPI_SERVER_MKDIR_DIR, MPI_SERVER_OPEN_FILE_WOS, MPI_SERVER_OPEN_FILE_WS, MPI_SERVER_OPENDIR_DIR, MPI_SERVER_PRELOAD_FILE, MPI_SERVER_READ_FILE_WOS, MPI_SERVER_READ_FILE_WS, MPI_SERVER_READDIR_DIR, MPI_SERVER_RENAME_FILE, MPI_SERVER_RM_FILE, MPI_SERVER_RM_FILE_ASYNC, MPI_SERVER_RMDIR_DIR, MPI_SERVER_RMDIR_DIR_ASYNC, MPI_SERVER_SETATTR_FILE, MPI_SERVER_STATFS_DIR, MPI_SERVER_WRITE_FILE_WOS, and MPI_SERVER_WRITE_FILE_WS.
Referenced by mpi_server_run().