mpi_server_comm.h File Reference
Header file to 'TODO'.
#include all_system.h
#include base/utils.h
#include base/time_misc.h
#include base/ns.h
#include mpi_server_params.h
Functions
int mpi_server_comm_init (mpi_server_param_st *params)
'TODO'.
int mpi_server_comm_destroy (mpi_server_param_st *params)
'TODO'.
MPI_Comm mpi_server_comm_accept (mpi_server_param_st *params)
'TODO'.
int mpiClient_comm_close (MPI_Comm fd)
'TODO'.
ssize_t mpi_server_comm_write_data (mpi_server_param_st *params, MPI_Comm fd, char *data, ssize_t size, int rank_client_id)
'TODO'.
ssize_t mpi_server_comm_read_operation (mpi_server_param_st *params, MPI_Comm fd, char *data, ssize_t size, int *rank_client_id)
'TODO'.
ssize_t mpi_server_comm_read_data (mpi_server_param_st *params, MPI_Comm fd, char *data, ssize_t size, int rank_client_id)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file mpi_server/mpi_server_comm.h.
Function Documentation
mpi_server_comm_accept()
MPI_Comm mpi_server_comm_accept (mpi_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 248 of file mpi_server/mpi_server_comm.c.
References mpi_server_param_st::client, DEBUG_BEGIN, DEBUG_END, debug_error, params, mpi_server_param_st::port_name, and mpi_server_param_st::rank.
Referenced by mpi_server_up().
mpi_server_comm_destroy()
int mpi_server_comm_destroy (mpi_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 188 of file mpi_server/mpi_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, mpi_server_param_st::dns_file, MPI_Finalize(), ns_get_hostname(), ns_unpublish(), params, mpi_server_param_st::port_name, mpi_server_param_st::rank, mpi_server_param_st::size, and mpi_server_param_st::srv_name.
Referenced by mpi_server_up().
mpi_server_comm_init()
int mpi_server_comm_init (mpi_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 41 of file mpi_server/mpi_server_comm.c.
References mpi_server_param_st::argc, mpi_server_param_st::argv, DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, mpi_server_param_st::dns_file, MPI_Init(), ns_get_host_ip(), ns_get_hostname(), ns_publish(), params, mpi_server_param_st::port_name, mpi_server_param_st::rank, serv_name, mpi_server_param_st::size, mpi_server_param_st::srv_name, mpi_server_param_st::thread_mode, TIME_MISC_DiffTime(), TIME_MISC_Timer(), and TIME_MISC_TimevaltoFloat().
Referenced by mpi_server_up().
mpi_server_comm_read_data()
ssize_t mpi_server_comm_read_data (mpi_server_param_st * params, MPI_Comm fd, char * data, ssize_t size, int rank_client_id)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
fd 'TODO'.
data 'TODO'.
size 'TODO'.
rank_client_id 'TODO'.
Returns
'TODO'.
Definition at line 365 of file mpi_server/mpi_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, debug_warning, params, and mpi_server_param_st::rank.
Referenced by mpi_server_do_operation(), mpi_server_op_write_wos(), and mpi_server_op_write_ws().
mpi_server_comm_read_operation()
ssize_t mpi_server_comm_read_operation (mpi_server_param_st * params, MPI_Comm fd, char * data, ssize_t size, int * rank_client_id)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
fd 'TODO'.
data 'TODO'.
size 'TODO'.
rank_client_id 'TODO'.
Returns
'TODO'.
Definition at line 290 of file mpi_server/mpi_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, debug_warning, params, and mpi_server_param_st::rank.
Referenced by mpi_server_dispatcher().
mpi_server_comm_write_data()
ssize_t mpi_server_comm_write_data (mpi_server_param_st * params, MPI_Comm fd, char * data, ssize_t size, int rank_client_id)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
fd 'TODO'.
data 'TODO'.
size 'TODO'.
rank_client_id 'TODO'.
Returns
'TODO'.
Definition at line 330 of file mpi_server/mpi_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, params, and mpi_server_param_st::rank.
Referenced by mpi_server_op_close_ws(), mpi_server_op_closedir(), mpi_server_op_creat_wos(), mpi_server_op_creat_ws(), mpi_server_op_flush(), mpi_server_op_getattr(), mpi_server_op_getid(), mpi_server_op_getnodename(), mpi_server_op_mkdir(), mpi_server_op_open_wos(), mpi_server_op_open_ws(), mpi_server_op_opendir(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_read_ws(), mpi_server_op_readdir(), mpi_server_op_rename(), mpi_server_op_rm(), mpi_server_op_rmdir(), mpi_server_op_rmdir_async(), mpi_server_op_write_wos(), and mpi_server_op_write_ws().
mpiClient_comm_close()
int mpiClient_comm_close (MPI_Comm fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 268 of file mpi_server/mpi_server_comm.c.
References debug_error.
Referenced by mpi_server_dispatcher().