mpi_server_ops.c File Reference
File to 'TODO'.
#include mpi_server_ops.h
Functions
char * mpi_server_op2string (int op_code)
'TODO'.
void mpi_server_op_open_ws (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_open_wos (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_creat_ws (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_creat_wos (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_read_ws (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_read_wos (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_write_ws (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_write_wos (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_close_ws (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_rm (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_rm_async (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_rename (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_setattr (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_getattr (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_mkdir (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_opendir (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_readdir (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_closedir (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_rmdir (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_rmdir_async (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_flush (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_preload (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_getnodename (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_fstat (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
void mpi_server_op_getid (mpi_server_param_st *params, MPI_Comm sd, struct st_mpi_server_msg *head, int rank_client_id)
'TODO'.
int mpi_server_do_operation (struct st_th *th, int *the_end)
'TODO'.
void mpi_server_op_rm_async (mpi_server_param_st *params, __attribute__((__unused__)) MPI_Comm sd, struct st_mpi_server_msg *head, __attribute__((__unused__)) int rank_client_id)
void mpi_server_op_setattr (mpi_server_param_st *params, __attribute__((__unused__)) MPI_Comm sd, struct st_mpi_server_msg *head, __attribute__((__unused__)) int rank_client_id)
void mpi_server_op_rmdir_async (__attribute__((__unused__)) mpi_server_param_st *params, __attribute__((__unused__)) MPI_Comm sd, struct st_mpi_server_msg *head, __attribute__((__unused__)) int rank_client_id)
void mpi_server_op_getnodename (mpi_server_param_st *params, MPI_Comm sd, __attribute__((__unused__)) struct st_mpi_server_msg *head, int rank_client_id)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file mpi_server_ops.c.
Function Documentation
mpi_server_do_operation()
int mpi_server_do_operation (struct st_th * th, int * the_end)
'TODO'.
'TODO'
Parameters
th 'TODO'.
the_end 'TODO'.
Returns
'TODO'.
Definition at line 494 of file mpi_server_ops.c.
References DEBUG_BEGIN, DEBUG_END, MPI_SERVER_CLOSE_FILE_WS, MPI_SERVER_CLOSEDIR_DIR, mpi_server_comm_read_data(), MPI_SERVER_CREAT_FILE_WOS, MPI_SERVER_CREAT_FILE_WS, MPI_SERVER_DISCONNECT, MPI_SERVER_FINALIZE, MPI_SERVER_FLUSH_FILE, MPI_SERVER_GETATTR_FILE, MPI_SERVER_GETNODENAME, MPI_SERVER_MKDIR_DIR, mpi_server_op_close_ws(), mpi_server_op_closedir(), mpi_server_op_creat_wos(), mpi_server_op_creat_ws(), mpi_server_op_flush(), mpi_server_op_getattr(), mpi_server_op_getnodename(), mpi_server_op_mkdir(), mpi_server_op_open_wos(), mpi_server_op_open_ws(), mpi_server_op_opendir(), mpi_server_op_preload(), mpi_server_op_read_wos(), mpi_server_op_read_ws(), mpi_server_op_readdir(), mpi_server_op_rename(), mpi_server_op_rm(), mpi_server_op_rm_async(), mpi_server_op_rmdir(), mpi_server_op_rmdir_async(), mpi_server_op_setattr(), mpi_server_op_write_wos(), mpi_server_op_write_ws(), MPI_SERVER_OPEN_FILE_WOS, MPI_SERVER_OPEN_FILE_WS, MPI_SERVER_OPENDIR_DIR, MPI_SERVER_PRELOAD_FILE, MPI_SERVER_READ_FILE_WOS, MPI_SERVER_READ_FILE_WS, MPI_SERVER_READDIR_DIR, MPI_SERVER_RENAME_FILE, MPI_SERVER_RM_FILE, MPI_SERVER_RM_FILE_ASYNC, MPI_SERVER_RMDIR_DIR, MPI_SERVER_RMDIR_DIR_ASYNC, MPI_SERVER_SETATTR_FILE, MPI_SERVER_WRITE_FILE_WOS, MPI_SERVER_WRITE_FILE_WS, st_mpi_server_msg::op_close, st_mpi_server_msg::op_closedir, st_mpi_server_msg::op_creat, st_mpi_server_msg::op_flush, st_mpi_server_msg::op_getattr, st_mpi_server_msg::op_mkdir, st_mpi_server_msg::op_open, st_mpi_server_msg::op_opendir, st_mpi_server_msg::op_preload, st_mpi_server_msg::op_read, st_mpi_server_msg::op_readdir, st_mpi_server_msg::op_rename, st_mpi_server_msg::op_rm, st_mpi_server_msg::op_rmdir, st_mpi_server_msg::op_setattr, st_mpi_server_msg::op_write, st_th::params, st_th::rank_client_id, st_th::sd, the_end, st_th::type_op, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_run().
mpi_server_op2string()
char * mpi_server_op2string (int op_code)
'TODO'.
'TODO'
Parameters
op_code 'TODO'.
Returns
'TODO'.
Definition at line 41 of file mpi_server_ops.c.
References MPI_SERVER_CLOSE_FILE_WS, MPI_SERVER_CLOSEDIR_DIR, MPI_SERVER_CREAT_FILE_WOS, MPI_SERVER_CREAT_FILE_WS, MPI_SERVER_DISCONNECT, MPI_SERVER_END, MPI_SERVER_FINALIZE, MPI_SERVER_FLUSH_FILE, MPI_SERVER_GETATTR_FILE, MPI_SERVER_GETID, MPI_SERVER_GETNODENAME, MPI_SERVER_MKDIR_DIR, MPI_SERVER_OPEN_FILE_WOS, MPI_SERVER_OPEN_FILE_WS, MPI_SERVER_OPENDIR_DIR, MPI_SERVER_PRELOAD_FILE, MPI_SERVER_READ_FILE_WOS, MPI_SERVER_READ_FILE_WS, MPI_SERVER_READDIR_DIR, MPI_SERVER_RENAME_FILE, MPI_SERVER_RM_FILE, MPI_SERVER_RM_FILE_ASYNC, MPI_SERVER_RMDIR_DIR, MPI_SERVER_RMDIR_DIR_ASYNC, MPI_SERVER_SETATTR_FILE, MPI_SERVER_STATFS_DIR, MPI_SERVER_WRITE_FILE_WOS, and MPI_SERVER_WRITE_FILE_WS.
Referenced by mpi_server_run().
mpi_server_op_close_ws()
void mpi_server_op_close_ws (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1092 of file mpi_server_ops.c.
References debug_info, st_mpi_server_close::fd, filesystem_close(), mpi_server_comm_write_data(), st_mpi_server_msg::op_close, params, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_closedir()
void mpi_server_op_closedir (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1283 of file mpi_server_ops.c.
References debug_info, st_mpi_server_closedir::dir, filesystem_closedir(), mpi_server_comm_write_data(), st_mpi_server_msg::op_closedir, params, st_mpi_server_direntry::ret, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_creat_wos()
void mpi_server_op_creat_wos (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 750 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_close(), filesystem_creat(), filesystem_mkpath(), mpi_server_comm_write_data(), st_mpi_server_msg::op_creat, params, st_mpi_server_creat::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_creat_ws()
void mpi_server_op_creat_ws (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 727 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_creat(), filesystem_mkpath(), mpi_server_comm_write_data(), st_mpi_server_msg::op_creat, params, st_mpi_server_creat::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_flush()
void mpi_server_op_flush (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1423 of file mpi_server_ops.c.
References st_mpi_server_flush::block_size, debug_info, filesystem_close(), filesystem_lseek(), filesystem_open(), filesystem_read(), filesystem_write(), mpi_server_comm_write_data(), O_CREAT, O_RDONLY, O_WRONLY, st_mpi_server_msg::op_flush, params, ParseURL(), mpi_server_param_st::rank, st_mpi_server_direntry::ret, mpi_server_param_st::size, mpi_server_param_st::srv_name, st_mpi_server_flush::storage_path, st_mpi_server_msg::u_st_mpi_server_msg, and st_mpi_server_flush::virtual_path.
Referenced by mpi_server_do_operation().
mpi_server_op_fstat()
void mpi_server_op_fstat (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
mpi_server_op_getattr()
void mpi_server_op_getattr (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1179 of file mpi_server_ops.c.
References st_mpi_server_attr_req::attr, debug_info, mpi_server_param_st::dirbase, filesystem_stat(), mpi_server_comm_write_data(), st_mpi_server_msg::op_getattr, params, st_mpi_server_getattr::path, PATH_MAX, mpi_server_param_st::srv_name, st_mpi_server_attr_req::status, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_getid()
void mpi_server_op_getid (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1520 of file mpi_server_ops.c.
References debug_info, st_mpi_server_msg::id, mpi_server_comm_write_data(), MPI_SERVER_ID, params, and mpi_server_param_st::srv_name.
mpi_server_op_getnodename() [1/2]
void mpi_server_op_getnodename (mpi_server_param_st * params, MPI_Comm sd, __attribute__((__unused__)) struct st_mpi_server_msg * head, int rank_client_id)
Definition at line 1501 of file mpi_server_ops.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, mpi_server_param_st::dirbase, mpi_server_comm_write_data(), params, PATH_MAX, serv_name, and mpi_server_param_st::srv_name.
mpi_server_op_getnodename() [2/2]
void mpi_server_op_getnodename (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Referenced by mpi_server_do_operation().
mpi_server_op_mkdir()
void mpi_server_op_mkdir (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1219 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_mkdir(), mpi_server_comm_write_data(), st_mpi_server_msg::op_mkdir, params, st_mpi_server_mkdir::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_open_wos()
void mpi_server_op_open_wos (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 707 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_close(), filesystem_open(), mpi_server_comm_write_data(), O_RDWR, st_mpi_server_msg::op_open, params, st_mpi_server_open::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_open_ws()
void mpi_server_op_open_ws (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 689 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_open(), mpi_server_comm_write_data(), O_RDWR, st_mpi_server_msg::op_open, params, st_mpi_server_open::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_opendir()
void mpi_server_op_opendir (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1237 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_opendir(), mpi_server_comm_write_data(), st_mpi_server_msg::op_opendir, params, st_mpi_server_opendir::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_preload()
void mpi_server_op_preload (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1337 of file mpi_server_ops.c.
References st_mpi_server_preload::block_size, close(), debug_info, filesystem_close(), filesystem_creat(), filesystem_lseek(), filesystem_open(), filesystem_read(), filesystem_write(), mpi_server_comm_write_data(), O_RDONLY, st_mpi_server_msg::op_preload, params, ParseURL(), mpi_server_param_st::rank, st_mpi_server_direntry::ret, mpi_server_param_st::size, mpi_server_param_st::srv_name, st_mpi_server_preload::storage_path, st_mpi_server_msg::u_st_mpi_server_msg, and st_mpi_server_preload::virtual_path.
Referenced by mpi_server_do_operation().
mpi_server_op_read_wos()
void mpi_server_op_read_wos (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 851 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_close(), filesystem_lseek(), filesystem_open(), filesystem_read(), FREE_AND_NULL, MAX_BUFFER_SIZE, mpi_server_comm_write_data(), O_RDONLY, st_mpi_server_read::offset, st_mpi_server_msg::op_read, params, st_mpi_server_read::path, PATH_MAX, st_mpi_server_read::size, st_mpi_server_read_req::size, mpi_server_param_st::size, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_read_ws()
void mpi_server_op_read_ws (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 775 of file mpi_server_ops.c.
References debug_info, st_mpi_server_read::fd, filesystem_lseek(), filesystem_read(), FREE_AND_NULL, MAX_BUFFER_SIZE, mpi_server_comm_write_data(), st_mpi_server_read::offset, st_mpi_server_msg::op_read, params, st_mpi_server_read::size, st_mpi_server_read_req::size, mpi_server_param_st::size, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_readdir()
void mpi_server_op_readdir (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1258 of file mpi_server_ops.c.
References debug_info, st_mpi_server_readdir::dir, st_mpi_server_direntry::end, filesystem_readdir(), mpi_server_comm_write_data(), st_mpi_server_msg::op_readdir, params, st_mpi_server_direntry::ret, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_rename()
void mpi_server_op_rename (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1153 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_rename(), mpi_server_comm_write_data(), st_mpi_server_rename::new_url, st_mpi_server_rename::old_url, st_mpi_server_msg::op_rename, params, PATH_MAX, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_rm()
void mpi_server_op_rm (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1109 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_unlink(), mpi_server_comm_write_data(), st_mpi_server_msg::op_rm, params, st_mpi_server_rm::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_rm_async() [1/2]
void mpi_server_op_rm_async (mpi_server_param_st * params, __attribute__((__unused__)) MPI_Comm sd, struct st_mpi_server_msg * head, __attribute__((__unused__)) int rank_client_id)
Definition at line 1132 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_unlink(), st_mpi_server_msg::op_rm, params, st_mpi_server_rm::path, PATH_MAX, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
mpi_server_op_rm_async() [2/2]
void mpi_server_op_rm_async (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Referenced by mpi_server_do_operation().
mpi_server_op_rmdir()
void mpi_server_op_rmdir (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1298 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_rmdir(), mpi_server_comm_write_data(), st_mpi_server_msg::op_rmdir, params, st_mpi_server_rmdir::path, PATH_MAX, st_mpi_server_direntry::ret, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_rmdir_async() [1/2]
void mpi_server_op_rmdir_async (__attribute__((__unused__)) mpi_server_param_st * params, __attribute__((__unused__)) MPI_Comm sd, struct st_mpi_server_msg * head, __attribute__((__unused__)) int rank_client_id)
Definition at line 1316 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_rmdir(), mpi_server_comm_write_data(), st_mpi_server_msg::op_rmdir, params, st_mpi_server_rmdir::path, PATH_MAX, st_mpi_server_direntry::ret, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
mpi_server_op_rmdir_async() [2/2]
void mpi_server_op_rmdir_async (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Referenced by mpi_server_do_operation().
mpi_server_op_setattr() [1/2]
void mpi_server_op_setattr (mpi_server_param_st * params, __attribute__((__unused__)) MPI_Comm sd, struct st_mpi_server_msg * head, __attribute__((__unused__)) int rank_client_id)
Definition at line 1197 of file mpi_server_ops.c.
References debug_info, params, and mpi_server_param_st::srv_name.
mpi_server_op_setattr() [2/2]
void mpi_server_op_setattr (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Referenced by mpi_server_do_operation().
mpi_server_op_write_wos()
void mpi_server_op_write_wos (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 1011 of file mpi_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, st_mpi_server_write::fd, filesystem_close(), filesystem_lseek(), filesystem_open(), filesystem_write(), FREE_AND_NULL, MAX_BUFFER_SIZE, mpi_server_comm_read_data(), mpi_server_comm_write_data(), O_WRONLY, st_mpi_server_write::offset, st_mpi_server_msg::op_read, st_mpi_server_msg::op_write, params, st_mpi_server_write::path, PATH_MAX, st_mpi_server_read::size, st_mpi_server_write::size, st_mpi_server_write_req::size, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().
mpi_server_op_write_ws()
void mpi_server_op_write_ws (mpi_server_param_st * params, MPI_Comm sd, struct st_mpi_server_msg * head, int rank_client_id)
'TODO'.
'TODO'
Parameters
params 'TODO'.
sd 'TODO'.
head 'TODO'.
rank_client_id 'TODO'.
Returns
Nothing.
Definition at line 949 of file mpi_server_ops.c.
References debug_info, st_mpi_server_write::fd, filesystem_lseek(), filesystem_write(), FREE_AND_NULL, MAX_BUFFER_SIZE, mpi_server_comm_read_data(), mpi_server_comm_write_data(), st_mpi_server_write::offset, st_mpi_server_msg::op_read, st_mpi_server_msg::op_write, params, st_mpi_server_read::size, st_mpi_server_write::size, st_mpi_server_write_req::size, mpi_server_param_st::srv_name, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by mpi_server_do_operation().