mpi_server_params.h File Reference
Header file to 'TODO'.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include mpi.h
#include base/utils.h
#include base/workers.h
Data Structures
struct mpi_server_param_st
This is a struct.
Macros
#define MPI_SERVER_DIRBASE_DEFAULT /tmp
Functions
void mpi_server_params_show_usage (void)
'TODO'.
int mpi_server_params_get (mpi_server_param_st *params, int argc, char *argv[])
'TODO'.
void mpi_server_params_show (mpi_server_param_st *params)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file mpi_server/mpi_server_params.h.
Macro Definition Documentation
MPI_SERVER_DIRBASE_DEFAULT
#define MPI_SERVER_DIRBASE_DEFAULT /tmp
Definition at line 51 of file mpi_server/mpi_server_params.h.
Function Documentation
mpi_server_params_get()
int mpi_server_params_get (mpi_server_param_st * params, int argc, char * argv[])
'TODO'.
'TODO'.
Parameters
params 'TODO'.
argc 'TODO'.
argv 'TODO'.
Returns
'TODO'.
Definition at line 79 of file mpi_server_params.c.
References mpi_server_param_st::argc, mpi_server_param_st::argv, DEBUG_BEGIN, DEBUG_END, mpi_server_param_st::dirbase, mpi_server_param_st::dns_file, MPI_SERVER_DIRBASE_DEFAULT, MPI_SERVER_DNS_FILE_DEFAULT, params, mpi_server_param_st::port_name, mpi_server_param_st::rank, mpi_server_param_st::shutdown_file, mpi_server_param_st::size, mpi_server_param_st::srv_name, TH_NOT, TH_OP, TH_POOL, and mpi_server_param_st::thread_mode.
Referenced by main().
mpi_server_params_show()
void mpi_server_params_show (mpi_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
Nothing.
Definition at line 42 of file mpi_server_params.c.
References DEBUG_BEGIN, DEBUG_END, mpi_server_param_st::dirbase, mpi_server_param_st::dns_file, params, mpi_server_param_st::shutdown_file, TH_NOT, TH_OP, TH_POOL, and mpi_server_param_st::thread_mode.
Referenced by main().
mpi_server_params_show_usage()
void mpi_server_params_show_usage (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 66 of file mpi_server_params.c.
References DEBUG_BEGIN, and DEBUG_END.
Referenced by main().