nfi_nfs.c File Reference
File to 'TODO'.
#include nfi_nfs.h
Macros
#define DBG_NFI 0
#define DBG_NFI 0
Functions
void NFItoNFSattr (fattr *nfs_att, struct nfi_attr *nfi_att)
void NFStoNFIattr (struct nfi_attr *nfi_att, fattr *nfs_att)
void NFStoNFIInfo (__attribute__((__unused__)) struct nfi_info *nfi_inf, __attribute__((__unused__)) struct nfs_info *nfs_inf)
int nfi_nfs_init (char *url, struct nfi_server *serv, __attribute__((__unused__)) struct nfi_attr_server *attr)
int nfi_nfs_disconnect (struct nfi_server *serv)
int nfi_nfs_reconnect (struct nfi_server *serv)
int nfi_nfs_destroy (struct nfi_server *serv)
int nfi_nfs_getattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
int nfi_nfs_setattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
int nfs_open (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
int nfi_nfs_open (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
int nfi_nfs_close (struct nfi_server *server, struct nfi_fhandle *fh)
ssize_t nfi_nfs_read (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
ssize_t nfi_nfs_write (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
int nfi_nfs_create (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
int nfi_nfs_remove (struct nfi_server *serv, char *url)
int nfi_nfs_rename (struct nfi_server *serv, char *old_url, char *new_url)
int nfi_nfs_mkdir (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
int nfi_nfs_rmdir (struct nfi_server *serv, char *url)
int nfi_nfs_opendir (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
int nfi_nfs_readdir (struct nfi_server *serv, struct nfi_fhandle *fh, struct dirent *entry)
int nfi_nfs_closedir (struct nfi_server *serv, struct nfi_fhandle *fh)
int nfi_nfs_statfs (struct nfi_server *serv, struct nfi_info *inf)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_nfs.c.
Macro Definition Documentation
DBG_NFI [1/2]
#define DBG_NFI 0
DBG_NFI [2/2]
#define DBG_NFI 0
Function Documentation
nfi_nfs_close()
int nfi_nfs_close (struct nfi_server * server, struct nfi_fhandle * fh)
Definition at line 720 of file nfi_nfs.c.
References nfi_nfs_server::fh, NFINULL, nfs_err(), and NFSERR_PARAM.
Referenced by nfi_nfs_closedir(), nfi_nfs_init(), nfi_nfs_open(), and nfi_nfs_opendir().
nfi_nfs_closedir()
int nfi_nfs_closedir (struct nfi_server * serv, struct nfi_fhandle * fh)
Definition at line 1491 of file nfi_nfs.c.
References nfi_nfs_fhandle::fh, and nfi_nfs_close().
Referenced by nfi_nfs_init().
nfi_nfs_create()
int nfi_nfs_create (struct nfi_server * serv, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
Definition at line 884 of file nfi_nfs.c.
References nfi_attr::at_mode, nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_fhandle::fh, getDirWithURL(), getNameFile(), nfi_nfs_reconnect(), nfs_create(), nfs_err(), nfs_lookup(), nfs_open(), NFSERR_CREATE, NFSERR_LOOKUP, NFSERR_MEMORY, NFSERR_PARAM, NFSERR_URL, NFSPATHLEN, NFStoNFIattr(), ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs_init().
nfi_nfs_destroy()
int nfi_nfs_destroy (struct nfi_server * serv)
Definition at line 406 of file nfi_nfs.c.
References nfi_nfs_server::cl, close_connection_mount(), close_connection_nfs(), create_connection_mount(), nfi_worker_end(), nfs_err(), NFS_UDP, nfs_umount(), NFSERR_URL, NFSPATHLEN, nfi_server::ops, ParseURL(), nfi_server::private_info, nfi_server::server, nfi_server::url, and nfi_server::wrk.
nfi_nfs_disconnect()
int nfi_nfs_disconnect (struct nfi_server * serv)
Definition at line 291 of file nfi_nfs.c.
References nfi_nfs_server::cl, close_connection_mount(), close_connection_nfs(), create_connection_mount(), nfi_worker_end(), nfs_err(), NFS_UDP, nfs_umount(), NFSERR_URL, NFSPATHLEN, ParseURL(), nfi_server::private_info, nfi_server::server, nfi_server::url, and nfi_server::wrk.
Referenced by nfi_nfs_init().
nfi_nfs_getattr()
int nfi_nfs_getattr (struct nfi_server * serv, struct nfi_fhandle * fh, struct nfi_attr * attr)
Definition at line 466 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_fhandle::fh, nfi_nfs_reconnect(), nfs_err(), nfs_getattr(), NFSERR_GETATTR, NFSERR_PARAM, NFStoNFIattr(), nfi_server::private_info, and nfi_server::server.
Referenced by nfi_nfs_init().
nfi_nfs_init()
int nfi_nfs_init (char * url, struct nfi_server * serv, __attribute__((__unused__)) struct nfi_attr_server * attr)
Definition at line 128 of file nfi_nfs.c.
References nfi_nfs_server::cl, close_connection_mount(), close_connection_nfs(), create_connection_mount(), create_connection_nfs(), nfi_nfs_server::fh, nfi_ops::nfi_close, nfi_ops::nfi_closedir, nfi_ops::nfi_create, nfi_ops::nfi_disconnect, nfi_ops::nfi_flush, nfi_ops::nfi_getattr, nfi_ops::nfi_mkdir, nfi_nfs_close(), nfi_nfs_closedir(), nfi_nfs_create(), nfi_nfs_disconnect(), nfi_nfs_getattr(), nfi_nfs_mkdir(), nfi_nfs_open(), nfi_nfs_opendir(), nfi_nfs_read(), nfi_nfs_readdir(), nfi_nfs_reconnect(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), nfi_nfs_setattr(), nfi_nfs_statfs(), nfi_nfs_write(), nfi_ops::nfi_open, nfi_ops::nfi_opendir, nfi_ops::nfi_preload, nfi_ops::nfi_read, nfi_ops::nfi_readdir, nfi_ops::nfi_reconnect, nfi_ops::nfi_remove, nfi_ops::nfi_rename, nfi_ops::nfi_rmdir, nfi_ops::nfi_setattr, nfi_ops::nfi_statfs, nfi_worker_init(), nfi_ops::nfi_write, nfs_err(), nfs_mount(), NFS_TCP, NFS_UDP, NFSERR_MEMORY, NFSERR_MNTCONNECTION, NFSERR_MOUNT, NFSERR_NFSCONNECTION, NFSERR_PARAM, NFSERR_URL, NFSPATHLEN, nfi_server::ops, ParseURL(), nfi_server::private_info, nfi_server::server, nfi_server::url, and nfi_server::wrk.
Referenced by XpnGetServer().
nfi_nfs_mkdir()
int nfi_nfs_mkdir (struct nfi_server * serv, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
Definition at line 1206 of file nfi_nfs.c.
References nfi_attr::at_mode, nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_fhandle::fh, getDirWithURL(), getNameFile(), nfi_nfs_reconnect(), nfs_err(), nfs_lookup(), nfs_mkdir(), NFSERR_LOOKUP, NFSERR_MEMORY, NFSERR_MKDIR, NFSERR_PARAM, NFSERR_URL, NFSPATHLEN, NFStoNFIattr(), ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs_init().
nfi_nfs_open()
int nfi_nfs_open (struct nfi_server * serv, char * url, struct nfi_fhandle * fho)
Definition at line 702 of file nfi_nfs.c.
References nfi_nfs_close(), NFIFILE, nfs_open(), and nfi_fhandle::type.
Referenced by nfi_nfs_init().
nfi_nfs_opendir()
int nfi_nfs_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
Definition at line 1402 of file nfi_nfs.c.
References nfi_nfs_close(), NFIDIR, nfs_open(), and nfi_fhandle::type.
Referenced by nfi_nfs_init().
nfi_nfs_read()
ssize_t nfi_nfs_read (struct nfi_server * serv, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
Definition at line 754 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_fhandle::fh, nfi_nfs_reconnect(), nfs_err(), nfs_read(), NFSERR_PARAM, NFSERR_READ, and nfi_server::private_info.
Referenced by nfi_nfs_init().
nfi_nfs_readdir()
int nfi_nfs_readdir (struct nfi_server * serv, struct nfi_fhandle * fh, struct dirent * entry)
Definition at line 1417 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_fhandle::cookie, nfi_nfs_fhandle::eofdir, nfi_nfs_fhandle::fh, nfi_nfs_reconnect(), NFIDIR, nfs_err(), nfs_readdir(), NFSERR_PARAM, NFSERR_READDIR, and nfi_server::private_info.
Referenced by nfi_nfs_init().
nfi_nfs_reconnect()
int nfi_nfs_reconnect (struct nfi_server * serv)
Definition at line 345 of file nfi_nfs.c.
References nfi_nfs_server::cl, close_connection_mount(), create_connection_mount(), create_connection_nfs(), nfi_nfs_server::fh, nfs_err(), nfs_mount(), NFS_UDP, NFSERR_MEMORY, NFSERR_MNTCONNECTION, NFSERR_MOUNT, NFSERR_NFSCONNECTION, NFSERR_URL, NFSPATHLEN, ParseURL(), nfi_server::private_info, and nfi_server::url.
Referenced by nfi_nfs_create(), nfi_nfs_getattr(), nfi_nfs_init(), nfi_nfs_mkdir(), nfi_nfs_read(), nfi_nfs_readdir(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), nfi_nfs_setattr(), nfi_nfs_statfs(), nfi_nfs_write(), and nfs_open().
nfi_nfs_remove()
int nfi_nfs_remove (struct nfi_server * serv, char * url)
Definition at line 1012 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, getDirWithURL(), getNameFile(), nfi_nfs_reconnect(), nfs_err(), nfs_lookup(), nfs_remove(), NFSERR_LOOKUP, NFSERR_PARAM, NFSERR_REMOVE, NFSERR_URL, NFSPATHLEN, ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs_init().
nfi_nfs_rename()
int nfi_nfs_rename (struct nfi_server * serv, char * old_url, char * new_url)
Definition at line 1093 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, getDirWithURL(), getNameFile(), nfi_nfs_reconnect(), nfs_err(), nfs_lookup(), nfs_rename(), NFSERR_LOOKUP, NFSERR_PARAM, NFSERR_REMOVE, NFSERR_URL, NFSPATHLEN, ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs_init().
nfi_nfs_rmdir()
int nfi_nfs_rmdir (struct nfi_server * serv, char * url)
Definition at line 1323 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, getDirWithURL(), getNameFile(), nfi_nfs_reconnect(), nfs_err(), nfs_lookup(), nfs_rmdir(), NFSERR_LOOKUP, NFSERR_PARAM, NFSERR_REMOVE, NFSERR_URL, NFSPATHLEN, ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs_init().
nfi_nfs_setattr()
int nfi_nfs_setattr (struct nfi_server * serv, struct nfi_fhandle * fh, struct nfi_attr * attr)
Definition at line 535 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_fhandle::fh, nfi_nfs_reconnect(), NFItoNFSattr(), nfs_err(), nfs_setattr(), NFSERR_GETATTR, NFSERR_PARAM, nfi_server::private_info, and nfi_server::server.
Referenced by nfi_nfs_init().
nfi_nfs_statfs()
int nfi_nfs_statfs (struct nfi_server * serv, struct nfi_info * inf)
Definition at line 1496 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_reconnect(), nfs_err(), nfs_statfs(), NFSERR_PARAM, NFSERR_STATFS, NFStoNFIInfo(), and nfi_server::private_info.
Referenced by nfi_nfs_init().
nfi_nfs_write()
ssize_t nfi_nfs_write (struct nfi_server * serv, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
Definition at line 820 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_fhandle::fh, nfi_nfs_reconnect(), nfs_err(), nfs_write(), NFSERR_PARAM, NFSERR_WRITE, and nfi_server::private_info.
Referenced by nfi_nfs_init().
NFItoNFSattr()
void NFItoNFSattr (fattr * nfs_att, struct nfi_attr * nfi_att)
Definition at line 55 of file nfi_nfs.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, and NFIFILE.
Referenced by nfi_nfs_setattr().
nfs_open()
int nfs_open (struct nfi_server * serv, char * url, struct nfi_fhandle * fho)
Definition at line 597 of file nfi_nfs.c.
References nfi_nfs_server::cl, nfi_nfs_server::fh, nfi_nfs_fhandle::fh, getDirWithURL(), nfi_nfs_reconnect(), NFIDIR, NFIFILE, nfs_err(), nfs_lookup(), NFSERR_MEMORY, NFSERR_PARAM, NFSERR_URL, NFSPATHLEN, ParseURL(), nfi_fhandle::priv_fh, nfi_server::private_info, nfi_fhandle::server, nfi_fhandle::type, nfi_server::url, and nfi_fhandle::url.
Referenced by nfi_nfs_create(), nfi_nfs_open(), and nfi_nfs_opendir().
NFStoNFIattr()
void NFStoNFIattr (struct nfi_attr * nfi_att, fattr * nfs_att)
Definition at line 85 of file nfi_nfs.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, NFIFILE, and nfi_attr::private_info.
Referenced by nfi_nfs_create(), nfi_nfs_getattr(), and nfi_nfs_mkdir().
NFStoNFIInfo()
void NFStoNFIInfo (__attribute__((__unused__)) struct nfi_info * nfi_inf, __attribute__((__unused__)) struct nfs_info * nfs_inf)
Definition at line 117 of file nfi_nfs.c.
Referenced by nfi_nfs_statfs().