nfi_nfs3_err.c File Reference
File to 'TODO'.
#include nfi_nfs3.h
Functions
void nfs3_err (int err)
Variables
int errno
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_nfs3_err.c.
Function Documentation
nfs3_err()
void nfs3_err (int err)
Definition at line 40 of file nfi_nfs3_err.c.
References errno, NFS3_OK, NFS3ERR_ABORTED, NFS3ERR_ACCES, NFS3ERR_BAD_COOKIE, NFS3ERR_BADHANDLE, NFS3ERR_BADTYPE, NFS3ERR_DQUOT, NFS3ERR_EXIST, NFS3ERR_FBIG, NFS3ERR_FPRINTNOTFOUND, NFS3ERR_INVAL, NFS3ERR_IO, NFS3ERR_ISDIR, NFS3ERR_JUKEBOX, NFS3ERR_MLINK, NFS3ERR_NAMETOOLONG, NFS3ERR_NODEV, NFS3ERR_NOENT, NFS3ERR_NOSPC, NFS3ERR_NOT_SYNC, NFS3ERR_NOTDIR, NFS3ERR_NOTEMPTY, NFS3ERR_NOTSUPP, NFS3ERR_NXIO, NFS3ERR_PERM, NFS3ERR_REMOTE, NFS3ERR_ROFS, NFS3ERR_SERVERFAULT, NFS3ERR_STALE, NFS3ERR_TOOSMALL, and NFS3ERR_XDEV.
Referenced by nfi_nfs3_close(), nfi_nfs3_create(), nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs3_getattr(), nfi_nfs3_init(), nfi_nfs3_mkdir(), nfi_nfs3_opendir(), nfi_nfs3_read(), nfi_nfs3_readdir(), nfi_nfs3_reconnect(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs3_setattr(), nfi_nfs3_statfs(), nfi_nfs3_write(), and nfs3_open().
Variable Documentation
errno
int errno [extern]
Referenced by nfs3_err().