nfi_local.h File Reference
Header file to 'TODO'.
#include all_system.h
#include base/filesystem.h
#include base/path_misc.h
#include base/urlstr.h
#include nfi/nfi.h
#include nfi/nfi_local/nfi_local_err.h
#include nfi_worker.h
Data Structures
struct nfi_local_server
This is a struct.
struct nfi_local_fhandle
This is a struct.
Macros
#define ASYNC_CLOSE 1
#define FILESYSTEM_DLSYM 1
Functions
int nfi_local_init (char *url, struct nfi_server *serv, struct nfi_attr_server *attr)
Init Local.
int nfi_local_connect (struct nfi_server *serv, char *url, char *prt, char *server, char *dir)
Connect to the server.
int nfi_local_reconnect (struct nfi_server *server)
Reconnect to the LOCAL server.
int nfi_local_disconnect (struct nfi_server *server)
Disconnect to the server.
int nfi_local_create (struct nfi_server *server, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_local_open (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
'TODO'.
ssize_t nfi_local_read (struct nfi_server *server, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
ssize_t nfi_local_write (struct nfi_server *server, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
int nfi_local_close (struct nfi_server *server, struct nfi_fhandle *fh)
'TODO'.
int nfi_local_remove (struct nfi_server *server, char *url)
'TODO'.
int nfi_local_rename (struct nfi_server *server, char *old_url, char *new_url)
'TODO'.
int nfi_local_getattr (struct nfi_server *server, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_local_setattr (struct nfi_server *server, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_local_mkdir (struct nfi_server *server, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_local_opendir (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_local_readdir (struct nfi_server *server, struct nfi_fhandle *fhd, struct dirent *entry)
'TODO'.
int nfi_local_closedir (struct nfi_server *server, struct nfi_fhandle *fh)
'TODO'.
int nfi_local_rmdir (struct nfi_server *server, char *url)
'TODO'.
int nfi_local_statfs (struct nfi_server *server, struct nfi_info *inf)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_local.h.
Macro Definition Documentation
ASYNC_CLOSE
#define ASYNC_CLOSE 1
Definition at line 43 of file nfi_local.h.
FILESYSTEM_DLSYM
#define FILESYSTEM_DLSYM 1
Definition at line 44 of file nfi_local.h.
Function Documentation
nfi_local_close()
int nfi_local_close (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 635 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, nfi_local_fhandle::fd, FREE_AND_NULL, LOCALERR_PARAM, nfi_local_keepConnected(), NFINULL, NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, nfi_fhandle::server, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_closedir()
int nfi_local_closedir (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 975 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, nfi_local_fhandle::dir, FREE_AND_NULL, LOCALERR_PARAM, nfi_local_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_closedir, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_connect()
int nfi_local_connect (struct nfi_server * serv, char * url, char * prt, char * server, char * dir)
Connect to the server.
'TODO'.
Parameters
serv 'TODO'.
url 'TODO'.
prt 'TODO'.
server 'TODO'.
dir 'TODO'.
Returns
'TODO'.
nfi_local_create()
int nfi_local_create (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 500 of file nfi_local.c.
References nfi_attr::at_mode, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, nfi_local_fhandle::fd, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, LOCALtoNFIattr(), nfi_local_keepConnected(), NFIFILE, NULL_RET_ERR, O_CREAT, O_RDWR, O_TRUNC, ParseURL(), nfi_local_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_open2, real_posix_stat, nfi_server::server, nfi_fhandle::server, st, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_disconnect()
int nfi_local_disconnect (struct nfi_server * server)
Disconnect to the server.
'TODO'
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 367 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, FREE_AND_NULL, and nfi_server::private_info.
Referenced by nfi_local_init().
nfi_local_getattr()
int nfi_local_getattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 748 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, LOCALERR_PARAM, LOCALtoNFIattr(), nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_stat, st, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_init()
int nfi_local_init (char * url, struct nfi_server * serv, struct nfi_attr_server * attr)
Init Local.
'TODO'
Parameters
url 'TODO'.
serv 'TODO'.
attr 'TODO'.
Returns
'TODO'.
nfi_local_mkdir()
int nfi_local_mkdir (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 815 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, errno, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, LOCALtoNFIattr(), nfi_local_keepConnected(), NFIDIR, NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_mkdir, real_posix_stat, st, STRING_MISC_StrDup(), nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_open()
int nfi_local_open (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 444 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, nfi_local_fhandle::fd, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NFIFILE, NULL_RET_ERR, O_RDWR, ParseURL(), nfi_local_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_open2, nfi_server::server, nfi_fhandle::server, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_opendir()
int nfi_local_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 880 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NFIDIR, NULL_RET_ERR, ParseURL(), nfi_local_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_opendir, nfi_server::server, nfi_fhandle::server, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_read()
ssize_t nfi_local_read (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 568 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, nfi_local_fhandle::fd, LOCALERR_PARAM, nfi_local_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_lseek, real_posix_read, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_readdir()
int nfi_local_readdir (struct nfi_server * server, struct nfi_fhandle * fhd, struct dirent * entry)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fhd 'TODO'.
entry 'TODO'.
Returns
'TODO'.
Definition at line 936 of file nfi_local.c.
References DEBUG_BEGIN, debug_error, nfi_local_fhandle::dir, local_err(), LOCALERR_NOTDIR, LOCALERR_PARAM, nfi_local_keepConnected(), NFIDIR, NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_readdir, and nfi_fhandle::type.
Referenced by nfi_local_init().
nfi_local_reconnect()
int nfi_local_reconnect (struct nfi_server * server)
Reconnect to the LOCAL server.
'TODO'
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 396 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, ParseURL(), nfi_local_server::path, PATH_MAX, nfi_server::private_info, and nfi_server::url.
Referenced by nfi_local_init(), and nfi_local_keepConnected().
nfi_local_remove()
int nfi_local_remove (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 668 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, local_err(), LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_unlink, and nfi_server::server.
Referenced by nfi_local_init().
nfi_local_rename()
int nfi_local_rename (struct nfi_server * server, char * old_url, char * new_url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
old_url 'TODO'.
new_url 'TODO'.
Returns
'TODO'.
Definition at line 704 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, local_err(), LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_rename, and nfi_server::server.
Referenced by nfi_local_init().
nfi_local_rmdir()
int nfi_local_rmdir (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 1004 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, local_err(), LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, and real_posix_rmdir.
Referenced by nfi_local_init().
nfi_local_setattr()
int nfi_local_setattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 791 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, LOCALERR_PARAM, nfi_local_keepConnected(), NFItoLOCALattr(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, and st.
Referenced by nfi_local_init().
nfi_local_statfs()
int nfi_local_statfs (struct nfi_server * server, struct nfi_info * inf)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
inf 'TODO'.
Returns
'TODO'.
nfi_local_write()
ssize_t nfi_local_write (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 599 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, nfi_local_fhandle::fd, LOCALERR_PARAM, nfi_local_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_lseek, real_posix_write, and nfi_fhandle::url.
Referenced by nfi_local_init().