nfi_mpi_server.c File Reference
File to 'TODO'.
#include nfi_mpi_server.h
Macros
#define FILESYSTEM_DLSYM 1
Functions
int mpi_server_write_operation (MPI_Comm sd, struct st_mpi_server_msg *head)
int nfi_mpi_server_doRequest (struct nfi_mpi_server_server *server_aux, struct st_mpi_server_msg *msg, char *req, int req_size)
int nfi_mpi_server_keepConnected (struct nfi_server *serv)
void NFItoMPI_SERVERattr (struct stat *att, struct nfi_attr *nfi_att)
void MPI_SERVERtoNFIattr (struct nfi_attr *nfi_att, struct stat *att)
void MPI_SERVERtoNFIInfo (__attribute__((__unused__)) struct nfi_info *nfi_inf, __attribute__((__unused__)) struct nfi_info *mpi_server_inf)
int nfi_mpi_server_init (char *url, struct nfi_server *serv, __attribute__((__unused__)) struct nfi_attr_server *attr)
int nfi_mpi_server_destroy (struct nfi_server *serv)
int nfi_mpi_server_connect (struct nfi_server *serv, __attribute__((__unused__)) char *url, __attribute__((__unused__)) char *prt, char *server, __attribute__((__unused__)) char *dir)
int nfi_mpi_server_disconnect (struct nfi_server *serv)
Disconnect to the server.
int nfi_mpi_server_reconnect (struct nfi_server *serv)
Reconnect to the MPI server.
int nfi_mpi_server_open (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_mpi_server_create (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
ssize_t nfi_mpi_server_read (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
ssize_t nfi_mpi_server_write (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
int nfi_mpi_server_close (struct nfi_server *serv, struct nfi_fhandle *fh)
'TODO'.
int nfi_mpi_server_remove (struct nfi_server *serv, char *url)
'TODO'.
int nfi_mpi_server_rename (struct nfi_server *serv, char *old_url, char *new_url)
'TODO'.
int nfi_mpi_server_getattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_mpi_server_setattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_mpi_server_mkdir (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_mpi_server_opendir (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_mpi_server_readdir (struct nfi_server *serv, struct nfi_fhandle *fh, struct dirent *entry)
'TODO'.
int nfi_mpi_server_closedir (struct nfi_server *serv, struct nfi_fhandle *fh)
'TODO'.
int nfi_mpi_server_rmdir (struct nfi_server *serv, char *url)
'TODO'.
int nfi_mpi_server_statfs (__attribute__((__unused__)) struct nfi_server *serv, __attribute__((__unused__)) struct nfi_info *inf)
int nfi_mpi_server_preload (struct nfi_server *serv, char *url, char *virtual_path, char *storage_path, int opt)
'TODO'.
int nfi_mpi_server_flush (struct nfi_server *serv, char *url, char *virtual_path, char *storage_path, int opt)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_mpi_server.c.
Macro Definition Documentation
FILESYSTEM_DLSYM
#define FILESYSTEM_DLSYM 1
Definition at line 39 of file nfi_mpi_server.c.
Function Documentation
mpi_server_write_operation()
int mpi_server_write_operation (MPI_Comm sd, struct st_mpi_server_msg * head)
Definition at line 48 of file nfi_mpi_server.c.
References debug_info, debug_warning, st_mpi_server_msg::id, MPI_SERVER_CLOSE_FILE_WS, MPI_SERVER_CLOSEDIR_DIR, MPI_SERVER_CREAT_FILE_WOS, MPI_SERVER_CREAT_FILE_WS, MPI_SERVER_FLUSH_FILE, MPI_SERVER_GETATTR_FILE, MPI_SERVER_MKDIR_DIR, MPI_SERVER_OPEN_FILE_WOS, MPI_SERVER_OPEN_FILE_WS, MPI_SERVER_OPENDIR_DIR, MPI_SERVER_PRELOAD_FILE, MPI_SERVER_READ_FILE_WOS, MPI_SERVER_READ_FILE_WS, MPI_SERVER_READDIR_DIR, MPI_SERVER_RENAME_FILE, MPI_SERVER_RM_FILE, MPI_SERVER_RM_FILE_ASYNC, MPI_SERVER_RMDIR_DIR, MPI_SERVER_RMDIR_DIR_ASYNC, MPI_SERVER_WRITE_FILE_WOS, MPI_SERVER_WRITE_FILE_WS, mpiClient_write_data(), mpiClient_write_operation(), st_mpi_server_msg::op_close, st_mpi_server_msg::op_closedir, st_mpi_server_msg::op_creat, st_mpi_server_msg::op_flush, st_mpi_server_msg::op_getattr, st_mpi_server_msg::op_mkdir, st_mpi_server_msg::op_open, st_mpi_server_msg::op_opendir, st_mpi_server_msg::op_preload, st_mpi_server_msg::op_read, st_mpi_server_msg::op_readdir, st_mpi_server_msg::op_rename, st_mpi_server_msg::op_rm, st_mpi_server_msg::op_rmdir, st_mpi_server_msg::op_write, st_mpi_server_msg::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_doRequest(), nfi_mpi_server_read(), nfi_mpi_server_remove(), and nfi_mpi_server_write().
MPI_SERVERtoNFIattr()
void MPI_SERVERtoNFIattr (struct nfi_attr * nfi_att, struct stat * att)
Definition at line 225 of file nfi_mpi_server.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, NFIFILE, nfi_attr::st_dev, and nfi_attr::st_ino.
Referenced by nfi_mpi_server_create(), nfi_mpi_server_getattr(), and nfi_mpi_server_mkdir().
MPI_SERVERtoNFIInfo()
void MPI_SERVERtoNFIInfo (__attribute__((__unused__)) struct nfi_info * nfi_inf, __attribute__((__unused__)) struct nfi_info * mpi_server_inf)
Definition at line 251 of file nfi_mpi_server.c.
nfi_mpi_server_close()
int nfi_mpi_server_close (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 1118 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, st_mpi_server_close::fd, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MPI_SERVER_CLOSE_FILE_WS, MPI_SERVER_ID, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFINULL, NULL_RET_ERR, st_mpi_server_msg::op_close, nfi_mpi_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_closedir()
int nfi_mpi_server_closedir (struct nfi_server * server, struct nfi_fhandle * fhd)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fhd 'TODO'.
Returns
'TODO'.
Definition at line 1690 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, st_mpi_server_closedir::dir, nfi_mpi_server_fhandle::dir, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MPI_SERVER_CLOSEDIR_DIR, MPI_SERVER_ID, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_closedir, nfi_mpi_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_closedir, st_mpi_server_msg::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_connect()
int nfi_mpi_server_connect (struct nfi_server * serv, __attribute__((__unused__)) char * url, __attribute__((__unused__)) char * prt, char * server, __attribute__((__unused__)) char * dir)
Definition at line 448 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, mpiClient_comm_connect(), nfi_mpi_server_server::params, nfi_server::private_info, and mpiClient_param_st::srv_name.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_create()
int nfi_mpi_server_create (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 671 of file nfi_mpi_server.c.
References nfi_attr::at_mode, st_mpi_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MPI_SERVER_CREAT_FILE_WOS, MPI_SERVER_CREAT_FILE_WS, mpi_server_err(), MPI_SERVER_GETATTR_FILE, MPI_SERVER_ID, MPI_SERVERERR_MEMORY, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, MPI_SERVERtoNFIattr(), nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_CREAT, O_RDWR, O_TRUNC, st_mpi_server_msg::op_creat, st_mpi_server_msg::op_getattr, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_creat::path, st_mpi_server_getattr::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, real_posix_stat, nfi_server::server, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_destroy()
int nfi_mpi_server_destroy (struct nfi_server * serv)
Definition at line 403 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, FREE_AND_NULL, mpiClient_comm_destroy(), nfiworker_destroy(), nfi_server::ops, nfi_mpi_server_server::params, nfi_server::private_info, nfi_server::server, and nfi_server::url.
nfi_mpi_server_disconnect()
int nfi_mpi_server_disconnect (struct nfi_server * server)
Disconnect to the server.
'TODO'.
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 483 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, FREE_AND_NULL, mpiClient_comm_disconnect(), nfi_mpi_server_server::params, and nfi_server::private_info.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_doRequest()
int nfi_mpi_server_doRequest (struct nfi_mpi_server_server * server_aux, struct st_mpi_server_msg * msg, char * req, int req_size)
Definition at line 148 of file nfi_mpi_server.c.
References debug_info, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpi_server_write_operation(), mpiClient_read_data(), nfi_mpi_server_server::params, and mpiClient_param_st::server.
Referenced by nfi_mpi_server_close(), nfi_mpi_server_closedir(), nfi_mpi_server_create(), nfi_mpi_server_flush(), nfi_mpi_server_getattr(), nfi_mpi_server_mkdir(), nfi_mpi_server_open(), nfi_mpi_server_opendir(), nfi_mpi_server_preload(), nfi_mpi_server_readdir(), nfi_mpi_server_remove(), nfi_mpi_server_rename(), and nfi_mpi_server_rmdir().
nfi_mpi_server_flush()
int nfi_mpi_server_flush (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
virtual_path 'TODO'.
storage_path 'TODO'.
opt 'TODO'.
Returns
'TODO'.
Definition at line 1890 of file nfi_mpi_server.c.
References st_mpi_server_flush::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpi_server_err(), MPI_SERVER_FLUSH_FILE, MPI_SERVER_ID, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_flush, st_mpi_server_flush::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_mpi_server_flush::storage_path, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and st_mpi_server_flush::virtual_path.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_getattr()
int nfi_mpi_server_getattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 1346 of file nfi_mpi_server.c.
References st_mpi_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, mpiClient_param_st::dirbase, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_GETATTR_FILE, MPI_SERVER_ID, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, MPI_SERVERtoNFIattr(), nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_getattr, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_getattr::path, nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, real_posix_stat, st_mpi_server_attr_req::status, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_fhandle::url.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_init()
int nfi_mpi_server_init (char * url, struct nfi_server * serv, __attribute__((__unused__)) struct nfi_attr_server * attr)
Definition at line 263 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, FREE_AND_NULL, mpi_server_err(), MPI_SERVERERR_MEMORY, MPI_SERVERERR_URL, mpiClient_comm_init(), mpiClient_comm_locality(), nfi_ops::nfi_close, nfi_ops::nfi_closedir, nfi_ops::nfi_create, nfi_ops::nfi_disconnect, nfi_ops::nfi_flush, nfi_ops::nfi_getattr, nfi_ops::nfi_mkdir, nfi_mpi_server_close(), nfi_mpi_server_closedir(), nfi_mpi_server_connect(), nfi_mpi_server_create(), nfi_mpi_server_disconnect(), nfi_mpi_server_flush(), nfi_mpi_server_getattr(), nfi_mpi_server_mkdir(), nfi_mpi_server_open(), nfi_mpi_server_opendir(), nfi_mpi_server_preload(), nfi_mpi_server_read(), nfi_mpi_server_readdir(), nfi_mpi_server_reconnect(), nfi_mpi_server_remove(), nfi_mpi_server_rename(), nfi_mpi_server_rmdir(), nfi_mpi_server_setattr(), nfi_mpi_server_statfs(), nfi_mpi_server_write(), nfi_ops::nfi_open, nfi_ops::nfi_opendir, nfi_ops::nfi_preload, nfi_ops::nfi_read, nfi_ops::nfi_readdir, nfi_ops::nfi_reconnect, nfi_ops::nfi_remove, nfi_ops::nfi_rename, nfi_ops::nfi_rmdir, nfi_ops::nfi_setattr, nfi_ops::nfi_statfs, nfi_ops::nfi_write, nfiworker_init(), NULL_RET_ERR, nfi_server::ops, nfi_mpi_server_server::params, ParseURL(), PATH_MAX, nfi_server::private_info, nfi_worker::server, TH_NOT, nfi_server::url, nfi_server::wrk, mpiClient_param_st::xpn_locality, mpiClient_param_st::xpn_session, nfi_server::xpn_thread, and mpiClient_param_st::xpn_thread.
Referenced by XpnGetServer().
nfi_mpi_server_keepConnected()
int nfi_mpi_server_keepConnected (struct nfi_server * serv)
Definition at line 172 of file nfi_mpi_server.c.
References nfi_mpi_server_reconnect(), and nfi_server::private_info.
Referenced by nfi_mpi_server_close(), nfi_mpi_server_closedir(), nfi_mpi_server_create(), nfi_mpi_server_flush(), nfi_mpi_server_getattr(), nfi_mpi_server_mkdir(), nfi_mpi_server_open(), nfi_mpi_server_opendir(), nfi_mpi_server_preload(), nfi_mpi_server_read(), nfi_mpi_server_readdir(), nfi_mpi_server_remove(), nfi_mpi_server_rename(), nfi_mpi_server_rmdir(), nfi_mpi_server_setattr(), and nfi_mpi_server_write().
nfi_mpi_server_mkdir()
int nfi_mpi_server_mkdir (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 1439 of file nfi_mpi_server.c.
References st_mpi_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, errno, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_GETATTR_FILE, MPI_SERVER_ID, MPI_SERVER_MKDIR_DIR, MPI_SERVERERR_MEMORY, MPI_SERVERERR_MKDIR, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, MPI_SERVERtoNFIattr(), nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_mpi_server_msg::op_getattr, st_mpi_server_msg::op_mkdir, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_getattr::path, st_mpi_server_mkdir::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_mkdir, real_posix_stat, nfi_server::server, STRING_MISC_StrDup(), st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_fhandle::url.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_open()
int nfi_mpi_server_open (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 568 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_OPEN_FILE_WOS, MPI_SERVER_OPEN_FILE_WS, MPI_SERVERERR_MEMORY, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_RDWR, st_mpi_server_msg::op_open, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_open::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, nfi_server::server, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_opendir()
int nfi_mpi_server_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 1543 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_OPENDIR_DIR, MPI_SERVERERR_MEMORY, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_mpi_server_msg::op_opendir, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_opendir::path, nfi_mpi_server_server::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_opendir, nfi_server::server, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_fhandle::url.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_preload()
int nfi_mpi_server_preload (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
virtual_path 'TODO'.
storage_path 'TODO'.
opt 'TODO'.
Returns
'TODO'.
Definition at line 1836 of file nfi_mpi_server.c.
References st_mpi_server_preload::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_PRELOAD_FILE, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_preload, st_mpi_server_preload::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_mpi_server_preload::storage_path, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and st_mpi_server_preload::virtual_path.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_read()
ssize_t nfi_mpi_server_read (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 797 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, errno, st_mpi_server_read::fd, nfi_mpi_server_fhandle::fd, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_READ_FILE_WOS, MPI_SERVER_READ_FILE_WS, mpi_server_write_operation(), MPI_SERVERERR_PARAM, MPI_SERVERERR_READ, mpiClient_read_data(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, O_RDONLY, st_mpi_server_read::offset, st_mpi_server_msg::op_read, nfi_mpi_server_server::params, st_mpi_server_read::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_read, mpiClient_param_st::server, st_mpi_server_read::size, st_mpi_server_read_req::size, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_readdir()
int nfi_mpi_server_readdir (struct nfi_server * server, struct nfi_fhandle * fhd, struct dirent * entry)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fhd 'TODO'.
entry 'TODO'.
Returns
'TODO'.
Definition at line 1625 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, st_mpi_server_readdir::dir, nfi_mpi_server_fhandle::dir, st_mpi_server_direntry::end, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_READDIR_DIR, MPI_SERVERERR_NOTDIR, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_mpi_server_msg::op_readdir, nfi_mpi_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_readdir, st_mpi_server_direntry::ret, st_mpi_server_msg::type, nfi_fhandle::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_reconnect()
int nfi_mpi_server_reconnect (struct nfi_server * server)
Reconnect to the MPI server.
'TODO'.
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 519 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, mpi_server_err(), MPI_SERVERERR_MEMORY, MPI_SERVERERR_URL, mpiClient_comm_connect(), NULL_RET_ERR, nfi_mpi_server_server::params, ParseURL(), nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, and nfi_server::url.
Referenced by nfi_mpi_server_init(), and nfi_mpi_server_keepConnected().
nfi_mpi_server_remove()
int nfi_mpi_server_remove (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 1188 of file nfi_mpi_server.c.
References nfi_worker::arg, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, st_mpi_server_msg::id, nfi_mpi_server_server::id, nfi_worker_args::is_master_node, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_RM_FILE, MPI_SERVER_RM_FILE_ASYNC, mpi_server_write_operation(), MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_rm, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_rm::path, nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, real_posix_unlink, nfi_server::server, mpiClient_param_st::server, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_server::wrk.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_rename()
int nfi_mpi_server_rename (struct nfi_server * server, char * old_url, char * new_url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
old_url 'TODO'.
new_url 'TODO'.
Returns
'TODO'.
Definition at line 1265 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_RENAME_FILE, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, st_mpi_server_rename::new_url, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_rename::old_url, st_mpi_server_msg::op_rename, nfi_mpi_server_server::params, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_rename, nfi_server::server, st_mpi_server_msg::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_rmdir()
int nfi_mpi_server_rmdir (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 1738 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_RMDIR_DIR, MPI_SERVERERR_PARAM, MPI_SERVERERR_REMOVE, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_rmdir, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_rmdir::path, nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, real_posix_rmdir, nfi_server::server, st_mpi_server_msg::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_setattr()
int nfi_mpi_server_setattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 1412 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, MPI_SERVERERR_PARAM, nfi_mpi_server_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, and nfi_server::private_info.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_statfs()
int nfi_mpi_server_statfs (__attribute__((__unused__)) struct nfi_server * serv, __attribute__((__unused__)) struct nfi_info * inf)
Definition at line 1802 of file nfi_mpi_server.c.
References DEBUG_BEGIN, and DEBUG_END.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_write()
ssize_t nfi_mpi_server_write (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 949 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, errno, st_mpi_server_write::fd, nfi_mpi_server_fhandle::fd, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MAX_BUFFER_SIZE, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_WRITE_FILE_WOS, MPI_SERVER_WRITE_FILE_WS, mpi_server_write_operation(), MPI_SERVERERR_PARAM, MPI_SERVERERR_WRITE, mpiClient_read_data(), mpiClient_write_data(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, O_WRONLY, st_mpi_server_write::offset, st_mpi_server_msg::op_write, nfi_mpi_server_server::params, st_mpi_server_write::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_write, mpiClient_param_st::server, st_mpi_server_write::size, st_mpi_server_write_req::size, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
NFItoMPI_SERVERattr()
void NFItoMPI_SERVERattr (struct stat * att, struct nfi_attr * nfi_att)
Definition at line 199 of file nfi_mpi_server.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, NFIFILE, nfi_attr::st_dev, and nfi_attr::st_ino.