nfi_worker.c File Reference
#include nfi/nfi_worker.h
#include nfi/nfi_ops.h
Functions
void * nfi_worker_run (struct nfi_worker *args)
int nfi_worker_init (struct nfi_worker *wrk, struct nfi_server *serv, int thread)
'TODO'.
ssize_t nfi_worker_wait (struct nfi_worker *wrk)
'TODO'.
int nfi_worker_end (struct nfi_worker *wrk)
'TODO'.
int nfi_worker_destroy ()
'TODO'.
int nfiworker_init (struct nfi_server *serv)
'TODO'.
int nfiworker_launch (void(*worker_function)(struct st_th), struct nfi_worker *wrk)
'TODO'.
ssize_t nfiworker_wait (struct nfi_worker *wrk)
'TODO'.
void nfiworker_destroy (struct nfi_server *serv)
'TODO'.
Variables
static int create_m = 0
pthread_mutex_t global_mt
pthread_cond_t global_cnd
int global_busy
Function Documentation
nfi_worker_destroy()
int nfi_worker_destroy ()
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 189 of file nfi_worker.c.
References global_cnd, and global_mt.
Referenced by xpn_simple_destroy().
nfi_worker_end()
int nfi_worker_end (struct nfi_worker * wrk)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
Returns
'TODO'.
Definition at line 175 of file nfi_worker.c.
References nfi_worker::cnd, debug_info, nfi_worker::mt, and nfi_worker::thread.
Referenced by nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs_destroy(), and nfi_nfs_disconnect().
nfi_worker_init()
int nfi_worker_init (struct nfi_worker * wrk, struct nfi_server * serv, int thread)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
serv 'TODO'.
thread 'TODO'.
Returns
'TODO'.
Definition at line 82 of file nfi_worker.c.
References nfi_worker::cnd, create_m, debug_info, global_busy, global_cnd, global_mt, KB, nfi_worker::mt, nfi_worker_run(), nfi_worker::pth, nfi_worker::server, and nfi_worker::thread.
Referenced by nfi_nfs3_init(), and nfi_nfs_init().
nfi_worker_run()
void * nfi_worker_run (struct nfi_worker * args)
Definition at line 41 of file nfi_worker.c.
References nfi_worker::arg, nfi_worker::cnd, global_busy, global_cnd, global_mt, nfi_worker::mt, nfi_worker::ready, and nfi_worker_args::result.
Referenced by nfi_worker_init().
nfi_worker_wait()
ssize_t nfi_worker_wait (struct nfi_worker * wrk)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
Returns
'TODO'.
Definition at line 143 of file nfi_worker.c.
References nfi_worker::arg, nfi_worker::cnd, debug_info, nfi_worker::mt, nfi_worker::ready, nfi_worker_args::result, and nfi_worker::thread.
nfiworker_destroy()
void nfiworker_destroy (struct nfi_server * serv)
'TODO'.
'TODO'.
Parameters
serv 'TODO'.
Returns
Nothing.
Definition at line 230 of file nfi_worker.c.
References TH_NOT, nfi_worker::wb, workers_destroy(), nfi_server::wrk, and nfi_server::xpn_thread.
Referenced by nfi_local_destroy(), nfi_mpi_server_destroy(), and nfi_tcp_server_destroy().
nfiworker_init()
int nfiworker_init (struct nfi_server * serv)
'TODO'.
'TODO'.
Parameters
serv 'TODO'.
Returns
'TODO'.
Definition at line 199 of file nfi_worker.c.
References nfi_worker::wb, workers_init(), nfi_server::wrk, and nfi_server::xpn_thread.
Referenced by nfi_local_init(), nfi_mpi_server_init(), and nfi_tcp_server_init().
nfiworker_launch()
int nfiworker_launch (void(*)(struct st_th) worker_function, struct nfi_worker * wrk)
'TODO'.
'TODO'.
Parameters
worker_function 'TODO'.
wrk 'TODO'.
Returns
'TODO'.
Definition at line 204 of file nfi_worker.c.
References st_th::c_wait, st_th::function, st_th::m_wait, st_th::params, st_th::r_wait, TRUE, st_th::wait4me, nfi_worker::warg, nfi_worker::wb, and workers_launch().
Referenced by nfi_worker_do_close(), nfi_worker_do_closedir(), nfi_worker_do_create(), nfi_worker_do_flush(), nfi_worker_do_getattr(), nfi_worker_do_mkdir(), nfi_worker_do_open(), nfi_worker_do_opendir(), nfi_worker_do_preload(), nfi_worker_do_read(), nfi_worker_do_readdir(), nfi_worker_do_remove(), nfi_worker_do_rename(), nfi_worker_do_rmdir(), nfi_worker_do_setattr(), nfi_worker_do_statfs(), and nfi_worker_do_write().
nfiworker_wait()
ssize_t nfiworker_wait (struct nfi_worker * wrk)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
Returns
'TODO'.
Definition at line 220 of file nfi_worker.c.
References nfi_worker::arg, nfi_worker_args::result, nfi_worker::warg, nfi_worker::wb, and workers_wait().
Referenced by xpn_internal_creat(), xpn_internal_remove(), xpn_pread(), xpn_pwrite(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), XpnGetAtribFd(), and XpnGetAtribPath().
Variable Documentation
create_m
int create_m = 0 [static]
Definition at line 32 of file nfi_worker.c.
Referenced by nfi_worker_init().
global_busy
int global_busy
Definition at line 35 of file nfi_worker.c.
Referenced by nfi_worker_init(), and nfi_worker_run().
global_cnd
pthread_cond_t global_cnd
Definition at line 34 of file nfi_worker.c.
Referenced by nfi_worker_destroy(), nfi_worker_init(), and nfi_worker_run().
global_mt
pthread_mutex_t global_mt
Definition at line 33 of file nfi_worker.c.
Referenced by nfi_worker_destroy(), nfi_worker_init(), and nfi_worker_run().