nfi_tcp_server_err.h File Reference
Header file to 'TODO'.
Enumerations
enum nfi_tcp_server_err {
TCP_SERVERERR_PARAM = 0
, TCP_SERVERERR_MEMORY = 1
, TCP_SERVERERR_URL = 2
, TCP_SERVERERR_MNTCONNECTION = 3
,
TCP_SERVERERR_MOUNT = 4
, TCP_SERVERERR_NFSCONNECTION = 5
, TCP_SERVERERR_GETATTR = 6
, TCP_SERVERERR_LOOKUP = 7
,
TCP_SERVERERR_READ = 8
, TCP_SERVERERR_WRITE = 9
, TCP_SERVERERR_CREATE = 10
, TCP_SERVERERR_REMOVE = 11
,
TCP_SERVERERR_MKDIR = 12
, TCP_SERVERERR_READDIR = 13
, TCP_SERVERERR_STATFS = 14
, TCP_SERVERERR_NOTDIR = 15
 }
Functions
void tcp_server_err (int err)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_tcp_server_err.h.
Enumeration Type Documentation
nfi_tcp_server_err
enum nfi_tcp_server_err
Enumerator
TCP_SERVERERR_PARAM
TCP_SERVERERR_MEMORY
TCP_SERVERERR_URL
TCP_SERVERERR_MNTCONNECTION
TCP_SERVERERR_MOUNT
TCP_SERVERERR_NFSCONNECTION
TCP_SERVERERR_GETATTR
TCP_SERVERERR_LOOKUP
TCP_SERVERERR_READ
TCP_SERVERERR_WRITE
TCP_SERVERERR_CREATE
TCP_SERVERERR_REMOVE
TCP_SERVERERR_MKDIR
TCP_SERVERERR_READDIR
TCP_SERVERERR_STATFS
TCP_SERVERERR_NOTDIR
Definition at line 40 of file nfi_tcp_server_err.h.
Function Documentation
tcp_server_err()
void tcp_server_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
Nothing.
Definition at line 40 of file nfi_tcp_server_err.c.
References errno, TCP_SERVERERR_GETATTR, TCP_SERVERERR_MEMORY, TCP_SERVERERR_MNTCONNECTION, TCP_SERVERERR_MOUNT, TCP_SERVERERR_NFSCONNECTION, TCP_SERVERERR_PARAM, and TCP_SERVERERR_URL.
Referenced by nfi_tcp_server_create(), nfi_tcp_server_flush(), nfi_tcp_server_getattr(), nfi_tcp_server_init(), nfi_tcp_server_mkdir(), nfi_tcp_server_open(), nfi_tcp_server_opendir(), nfi_tcp_server_preload(), nfi_tcp_server_read(), nfi_tcp_server_readdir(), nfi_tcp_server_reconnect(), nfi_tcp_server_remove(), nfi_tcp_server_rename(), nfi_tcp_server_rmdir(), and nfi_tcp_server_write().