nfi_nfs_err.h File Reference
Header file to 'TODO'.
#include nfs.h
Enumerations
enum nfi_nfs_err {
NFSERR_PARAM = 0
, NFSERR_MEMORY = 1
, NFSERR_URL = 2
, NFSERR_MNTCONNECTION = 3
,
NFSERR_MOUNT = 4
, NFSERR_NFSCONNECTION = 5
, NFSERR_GETATTR = 6
, NFSERR_LOOKUP = 7
,
NFSERR_READ = 8
, NFSERR_WRITE = 9
, NFSERR_CREATE = 10
, NFSERR_REMOVE = 11
,
NFSERR_MKDIR = 12
, NFSERR_READDIR = 13
, NFSERR_STATFS = 14
 }
Functions
void nfs_err (int err)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_nfs_err.h.
Enumeration Type Documentation
nfi_nfs_err
enum nfi_nfs_err
Enumerator
NFSERR_PARAM
NFSERR_MEMORY
NFSERR_URL
NFSERR_MNTCONNECTION
NFSERR_MOUNT
NFSERR_NFSCONNECTION
NFSERR_GETATTR
NFSERR_LOOKUP
NFSERR_READ
NFSERR_WRITE
NFSERR_CREATE
NFSERR_REMOVE
NFSERR_MKDIR
NFSERR_READDIR
NFSERR_STATFS
Definition at line 45 of file nfi_nfs_err.h.
Function Documentation
nfs_err()
void nfs_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
Nothing.
Definition at line 40 of file nfi_nfs_err.c.
References errno, NFSERR_GETATTR, NFSERR_MEMORY, NFSERR_MNTCONNECTION, NFSERR_MOUNT, NFSERR_NFSCONNECTION, NFSERR_PARAM, and NFSERR_URL.
Referenced by nfi_nfs_close(), nfi_nfs_create(), nfi_nfs_destroy(), nfi_nfs_disconnect(), nfi_nfs_getattr(), nfi_nfs_init(), nfi_nfs_mkdir(), nfi_nfs_read(), nfi_nfs_readdir(), nfi_nfs_reconnect(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), nfi_nfs_setattr(), nfi_nfs_statfs(), nfi_nfs_write(), and nfs_open().