nfi_tcp_server.h File Reference
Header file to 'TODO'.
#include all_system.h
#include base/utils.h
#include base/path_misc.h
#include base/urlstr.h
#include base/workers.h
#include tcp_server_ops.h
#include tcp_server_comm.h
#include tcp_server_params.h
#include nfi_tcp_server_err.h
#include nfi.h
#include nfi_worker.h
Data Structures
struct nfi_tcp_server_server
struct nfi_tcp_server_fhandle
Macros
#define MOSQ_OPT_TCP_NODELAY 0
Functions
int nfi_tcp_server_init (char *url, struct nfi_server *serv, struct nfi_attr_server *attr)
int nfi_tcp_server_connect (struct nfi_server *server, char *url, char *prt, char *serv, char *dir)
int nfi_tcp_server_reconnect (struct nfi_server *server)
int nfi_tcp_server_disconnect (struct nfi_server *server)
int nfi_tcp_server_create (struct nfi_server *server, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
int nfi_tcp_server_open (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
ssize_t nfi_tcp_server_read (struct nfi_server *server, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
ssize_t nfi_tcp_server_write (struct nfi_server *server, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
int nfi_tcp_server_close (struct nfi_server *server, struct nfi_fhandle *fh)
int nfi_tcp_server_remove (struct nfi_server *server, char *url)
int nfi_tcp_server_rename (struct nfi_server *server, char *old_url, char *new_url)
int nfi_tcp_server_getattr (struct nfi_server *server, struct nfi_fhandle *fh, struct nfi_attr *attr)
int nfi_tcp_server_setattr (struct nfi_server *server, struct nfi_fhandle *fh, struct nfi_attr *attr)
int nfi_tcp_server_mkdir (struct nfi_server *server, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
int nfi_tcp_server_opendir (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
int nfi_tcp_server_readdir (struct nfi_server *server, struct nfi_fhandle *fhd, struct dirent *entry)
int nfi_tcp_server_closedir (struct nfi_server *server, struct nfi_fhandle *fhd)
int nfi_tcp_server_rmdir (struct nfi_server *server, char *url)
int nfi_tcp_server_statfs (struct nfi_server *server, struct nfi_info *inf)
int nfi_tcp_server_preload (struct nfi_server *server, char *url, char *virtual_path, char *storage_path, int opt)
int nfi_tcp_server_flush (struct nfi_server *server, char *url, char *virtual_path, char *storage_path, int opt)
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_tcp_server.h.
Macro Definition Documentation
MOSQ_OPT_TCP_NODELAY
#define MOSQ_OPT_TCP_NODELAY 0
Definition at line 64 of file nfi_tcp_server.h.
Function Documentation
nfi_tcp_server_close()
int nfi_tcp_server_close (struct nfi_server * server, struct nfi_fhandle * fh)
Definition at line 1192 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, st_tcp_server_close::fd, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFINULL, NULL_RET_ERR, st_tcp_server_msg::op_close, nfi_tcp_server_server::params, st_tcp_server_close::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, nfi_fhandle::server, TCP_SERVER_CLOSE_FILE_WS, TCP_SERVER_ID, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_closedir()
int nfi_tcp_server_closedir (struct nfi_server * server, struct nfi_fhandle * fhd)
Definition at line 1706 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, st_tcp_server_closedir::dir, nfi_tcp_server_fhandle::dir, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_closedir, nfi_tcp_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_closedir, TCP_SERVER_CLOSEDIR_DIR, TCP_SERVER_ID, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_connect()
int nfi_tcp_server_connect (struct nfi_server * server, char * url, char * prt, char * serv, char * dir)
nfi_tcp_server_create()
int nfi_tcp_server_create (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
Definition at line 723 of file nfi_tcp_server.c.
References nfi_attr::at_mode, st_tcp_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_fhandle::dir, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_CREAT, O_RDWR, O_TRUNC, st_tcp_server_msg::op_creat, st_tcp_server_msg::op_getattr, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_creat::path, st_tcp_server_getattr::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, real_posix_stat, nfi_server::server, nfi_fhandle::server, tcpClient_param_st::server_name, TCP_SERVER_CREAT_FILE_WOS, TCP_SERVER_CREAT_FILE_WS, tcp_server_err(), TCP_SERVER_GETATTR_FILE, TCP_SERVER_ID, TCP_SERVERERR_MEMORY, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, TCP_SERVERtoNFIattr(), st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_disconnect()
int nfi_tcp_server_disconnect (struct nfi_server * server)
Definition at line 544 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, FREE_AND_NULL, nfi_tcp_server_server::params, nfi_server::private_info, and tcpClient_comm_disconnect().
Referenced by nfi_tcp_server_init().
nfi_tcp_server_flush()
int nfi_tcp_server_flush (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
Definition at line 1892 of file nfi_tcp_server.c.
References st_tcp_server_flush::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_flush, st_tcp_server_flush::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_tcp_server_flush::storage_path, tcp_server_err(), TCP_SERVER_FLUSH_FILE, TCP_SERVER_ID, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, and st_tcp_server_flush::virtual_path.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_getattr()
int nfi_tcp_server_getattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
Definition at line 1386 of file nfi_tcp_server.c.
References st_tcp_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_getattr, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_getattr::path, PATH_MAX, nfi_server::private_info, real_posix_stat, st_tcp_server_attr_req::status, tcp_server_err(), TCP_SERVER_GETATTR_FILE, TCP_SERVER_ID, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, TCP_SERVERtoNFIattr(), st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, and nfi_fhandle::url.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_init()
int nfi_tcp_server_init (char * url, struct nfi_server * serv, struct nfi_attr_server * attr)
nfi_tcp_server_mkdir()
int nfi_tcp_server_mkdir (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
Definition at line 1471 of file nfi_tcp_server.c.
References st_tcp_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_tcp_server_fhandle::dir, errno, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_tcp_server_msg::op_getattr, st_tcp_server_msg::op_mkdir, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_getattr::path, st_tcp_server_mkdir::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_mkdir, real_posix_stat, nfi_server::server, STRING_MISC_StrDup(), tcp_server_err(), TCP_SERVER_GETATTR_FILE, TCP_SERVER_ID, TCP_SERVER_MKDIR_DIR, TCP_SERVERERR_MEMORY, TCP_SERVERERR_MKDIR, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, TCP_SERVERtoNFIattr(), st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, and nfi_fhandle::url.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_open()
int nfi_tcp_server_open (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
Definition at line 629 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_fhandle::dir, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_RDWR, st_tcp_server_msg::op_open, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_open::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, nfi_server::server, nfi_fhandle::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_OPEN_FILE_WOS, TCP_SERVER_OPEN_FILE_WS, TCP_SERVERERR_MEMORY, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_opendir()
int nfi_tcp_server_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
Definition at line 1567 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_tcp_server_fhandle::dir, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_tcp_server_msg::op_opendir, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_opendir::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_opendir, nfi_server::server, nfi_fhandle::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_OPENDIR_DIR, TCP_SERVERERR_MEMORY, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, and nfi_fhandle::url.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_preload()
int nfi_tcp_server_preload (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
Definition at line 1844 of file nfi_tcp_server.c.
References st_tcp_server_preload::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_preload, st_tcp_server_preload::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_tcp_server_preload::storage_path, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_PRELOAD_FILE, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, and st_tcp_server_preload::virtual_path.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_read()
ssize_t nfi_tcp_server_read (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
Definition at line 846 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, st_tcp_server_read::fd, nfi_tcp_server_fhandle::fd, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_keepConnected(), NULL_RET_ERR, O_RDONLY, st_tcp_server_read::offset, st_tcp_server_msg::op_read, nfi_tcp_server_server::params, st_tcp_server_read::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_read, tcpClient_param_st::server, st_tcp_server_read::size, st_tcp_server_read_req::size, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_READ_FILE_WOS, TCP_SERVER_READ_FILE_WS, tcp_server_write_operation(), TCP_SERVERERR_PARAM, TCP_SERVERERR_READ, tcpClient_read_data(), st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_readdir()
int nfi_tcp_server_readdir (struct nfi_server * server, struct nfi_fhandle * fhd, struct dirent * entry)
Definition at line 1641 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, st_tcp_server_readdir::dir, nfi_tcp_server_fhandle::dir, st_tcp_server_direntry::end, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_tcp_server_msg::op_readdir, nfi_tcp_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_readdir, st_tcp_server_direntry::ret, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_READDIR_DIR, TCP_SERVERERR_NOTDIR, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, nfi_fhandle::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_reconnect()
int nfi_tcp_server_reconnect (struct nfi_server * server)
Definition at line 580 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, NULL_RET_ERR, nfi_tcp_server_server::params, ParseURL(), nfi_tcp_server_server::path, PATH_MAX, nfi_server::private_info, tcp_server_err(), TCP_SERVERERR_MEMORY, TCP_SERVERERR_URL, tcpClient_comm_connect(), and nfi_server::url.
Referenced by nfi_tcp_server_init(), and nfi_tcp_server_keepConnected().
nfi_tcp_server_remove()
int nfi_tcp_server_remove (struct nfi_server * server, char * url)
Definition at line 1262 of file nfi_tcp_server.c.
References DEBUG_END, debug_error, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_rm, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_rm::path, PATH_MAX, nfi_server::private_info, real_posix_unlink, nfi_server::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_RM_FILE, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_rename()
int nfi_tcp_server_rename (struct nfi_server * server, char * old_url, char * new_url)
Definition at line 1318 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, st_tcp_server_rename::new_url, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_rename::old_url, st_tcp_server_msg::op_rename, nfi_tcp_server_server::params, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_rename, nfi_server::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_RENAME_FILE, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_rmdir()
int nfi_tcp_server_rmdir (struct nfi_server * server, char * url)
Definition at line 1753 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_fhandle::dir, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_rmdir, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_rmdir::path, PATH_MAX, nfi_server::private_info, real_posix_rmdir, nfi_server::server, tcp_server_err(), TCP_SERVER_RMDIR_DIR, TCP_SERVERERR_PARAM, TCP_SERVERERR_REMOVE, TCP_SERVERERR_URL, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_setattr()
int nfi_tcp_server_setattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
Definition at line 1444 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, nfi_tcp_server_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, and TCP_SERVERERR_PARAM.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_statfs()
int nfi_tcp_server_statfs (struct nfi_server * server, struct nfi_info * inf)
nfi_tcp_server_write()
ssize_t nfi_tcp_server_write (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
Definition at line 983 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, st_tcp_server_write::fd, nfi_tcp_server_fhandle::fd, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, MAX_BUFFER_SIZE, nfi_tcp_server_server::mqtt, nfi_tcp_server_keepConnected(), NULL_RET_ERR, O_WRONLY, st_tcp_server_write::offset, st_tcp_server_msg::op_write, nfi_tcp_server_server::params, st_tcp_server_write::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_write, tcpClient_param_st::server, tcpClient_param_st::server_name, st_tcp_server_write::size, st_tcp_server_write_req::size, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_WRITE_FILE_WOS, TCP_SERVER_WRITE_FILE_WS, tcp_server_write_operation(), TCP_SERVERERR_PARAM, TCP_SERVERERR_WRITE, tcpClient_read_data(), tcpClient_write_data(), st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, tcpClient_param_st::xpn_mosquitto_mode, tcpClient_param_st::xpn_mosquitto_qos, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().