nfi_mpi_server_err.c File Reference
File to 'TODO'.
#include nfi_mpi_server.h
Functions
void mpi_server_err (int err)
'TODO'.
Variables
int errno
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_mpi_server_err.c.
Function Documentation
mpi_server_err()
void mpi_server_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
Nothing.
Definition at line 40 of file nfi_mpi_server_err.c.
References errno, MPI_SERVERERR_GETATTR, MPI_SERVERERR_MEMORY, MPI_SERVERERR_MNTCONNECTION, MPI_SERVERERR_MOUNT, MPI_SERVERERR_NFSCONNECTION, MPI_SERVERERR_PARAM, and MPI_SERVERERR_URL.
Referenced by nfi_mpi_server_create(), nfi_mpi_server_flush(), nfi_mpi_server_getattr(), nfi_mpi_server_init(), nfi_mpi_server_mkdir(), nfi_mpi_server_open(), nfi_mpi_server_opendir(), nfi_mpi_server_preload(), nfi_mpi_server_read(), nfi_mpi_server_readdir(), nfi_mpi_server_reconnect(), nfi_mpi_server_remove(), nfi_mpi_server_rename(), nfi_mpi_server_rmdir(), and nfi_mpi_server_write().
Variable Documentation
errno
int errno [extern]
Referenced by mpi_server_err().