nfi_mpi_server_err.h File Reference
Header file to 'TODO'.
Enumerations
enum nfi_mpi_server_err {
MPI_SERVERERR_PARAM = 0
, MPI_SERVERERR_MEMORY = 1
, MPI_SERVERERR_URL = 2
, MPI_SERVERERR_MNTCONNECTION = 3
,
MPI_SERVERERR_MOUNT = 4
, MPI_SERVERERR_NFSCONNECTION = 5
, MPI_SERVERERR_GETATTR = 6
, MPI_SERVERERR_LOOKUP = 7
,
MPI_SERVERERR_READ = 8
, MPI_SERVERERR_WRITE = 9
, MPI_SERVERERR_CREATE = 10
, MPI_SERVERERR_REMOVE = 11
,
MPI_SERVERERR_MKDIR = 12
, MPI_SERVERERR_READDIR = 13
, MPI_SERVERERR_STATFS = 14
, MPI_SERVERERR_NOTDIR = 15
 }
Functions
void mpi_server_err (int err)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_mpi_server_err.h.
Enumeration Type Documentation
nfi_mpi_server_err
enum nfi_mpi_server_err
Enumerator
MPI_SERVERERR_PARAM
MPI_SERVERERR_MEMORY
MPI_SERVERERR_URL
MPI_SERVERERR_MNTCONNECTION
MPI_SERVERERR_MOUNT
MPI_SERVERERR_NFSCONNECTION
MPI_SERVERERR_GETATTR
MPI_SERVERERR_LOOKUP
MPI_SERVERERR_READ
MPI_SERVERERR_WRITE
MPI_SERVERERR_CREATE
MPI_SERVERERR_REMOVE
MPI_SERVERERR_MKDIR
MPI_SERVERERR_READDIR
MPI_SERVERERR_STATFS
MPI_SERVERERR_NOTDIR
Definition at line 40 of file nfi_mpi_server_err.h.
Function Documentation
mpi_server_err()
void mpi_server_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
Nothing.
Definition at line 40 of file nfi_mpi_server_err.c.
References errno, MPI_SERVERERR_GETATTR, MPI_SERVERERR_MEMORY, MPI_SERVERERR_MNTCONNECTION, MPI_SERVERERR_MOUNT, MPI_SERVERERR_NFSCONNECTION, MPI_SERVERERR_PARAM, and MPI_SERVERERR_URL.
Referenced by nfi_mpi_server_create(), nfi_mpi_server_flush(), nfi_mpi_server_getattr(), nfi_mpi_server_init(), nfi_mpi_server_mkdir(), nfi_mpi_server_open(), nfi_mpi_server_opendir(), nfi_mpi_server_preload(), nfi_mpi_server_read(), nfi_mpi_server_readdir(), nfi_mpi_server_reconnect(), nfi_mpi_server_remove(), nfi_mpi_server_rename(), nfi_mpi_server_rmdir(), and nfi_mpi_server_write().