nfi_nfs3_err.h File Reference
Header file to 'TODO'.
#include nfs3.h
Enumerations
enum nfi_nfs3_err {
NFS3ERR_PARAM = 0
, NFS3ERR_MEMORY = 1
, NFS3ERR_URL = 2
, NFS3ERR_MNTCONNECTION = 3
,
NFS3ERR_MOUNT = 4
, NFS3ERR_NFSCONNECTION = 5
, NFS3ERR_GETATTR = 6
, NFS3ERR_SETATTR = 7
,
NFS3ERR_LOOKUP = 8
, NFS3ERR_READ = 9
, NFS3ERR_WRITE = 10
, NFS3ERR_CREATE = 11
,
NFS3ERR_REMOVE = 12
, NFS3ERR_MKDIR = 13
, NFS3ERR_READDIR = 14
, NFS3ERR_STATFS = 15
 }
Functions
void nfs3_err (int err)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_nfs3_err.h.
Enumeration Type Documentation
nfi_nfs3_err
enum nfi_nfs3_err
Enumerator
NFS3ERR_PARAM
NFS3ERR_MEMORY
NFS3ERR_URL
NFS3ERR_MNTCONNECTION
NFS3ERR_MOUNT
NFS3ERR_NFSCONNECTION
NFS3ERR_GETATTR
NFS3ERR_SETATTR
NFS3ERR_LOOKUP
NFS3ERR_READ
NFS3ERR_WRITE
NFS3ERR_CREATE
NFS3ERR_REMOVE
NFS3ERR_MKDIR
NFS3ERR_READDIR
NFS3ERR_STATFS
Definition at line 40 of file nfi_nfs3_err.h.
Function Documentation
nfs3_err()
void nfs3_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
Nothing.
Definition at line 40 of file nfi_nfs3_err.c.
References errno, NFS3_OK, NFS3ERR_ABORTED, NFS3ERR_ACCES, NFS3ERR_BAD_COOKIE, NFS3ERR_BADHANDLE, NFS3ERR_BADTYPE, NFS3ERR_DQUOT, NFS3ERR_EXIST, NFS3ERR_FBIG, NFS3ERR_FPRINTNOTFOUND, NFS3ERR_INVAL, NFS3ERR_IO, NFS3ERR_ISDIR, NFS3ERR_JUKEBOX, NFS3ERR_MLINK, NFS3ERR_NAMETOOLONG, NFS3ERR_NODEV, NFS3ERR_NOENT, NFS3ERR_NOSPC, NFS3ERR_NOT_SYNC, NFS3ERR_NOTDIR, NFS3ERR_NOTEMPTY, NFS3ERR_NOTSUPP, NFS3ERR_NXIO, NFS3ERR_PERM, NFS3ERR_REMOTE, NFS3ERR_ROFS, NFS3ERR_SERVERFAULT, NFS3ERR_STALE, NFS3ERR_TOOSMALL, and NFS3ERR_XDEV.
Referenced by nfi_nfs3_close(), nfi_nfs3_create(), nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs3_getattr(), nfi_nfs3_init(), nfi_nfs3_mkdir(), nfi_nfs3_opendir(), nfi_nfs3_read(), nfi_nfs3_readdir(), nfi_nfs3_reconnect(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs3_setattr(), nfi_nfs3_statfs(), nfi_nfs3_write(), and nfs3_open().