nfi_nfs_err.c File Reference
File to 'TODO'.
#include nfi_nfs.h
Functions
void nfs_err (int err)
Variables
int errno
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_nfs_err.c.
Function Documentation
nfs_err()
void nfs_err (int err)
Definition at line 40 of file nfi_nfs_err.c.
References errno, NFSERR_GETATTR, NFSERR_MEMORY, NFSERR_MNTCONNECTION, NFSERR_MOUNT, NFSERR_NFSCONNECTION, NFSERR_PARAM, and NFSERR_URL.
Referenced by nfi_nfs_close(), nfi_nfs_create(), nfi_nfs_destroy(), nfi_nfs_disconnect(), nfi_nfs_getattr(), nfi_nfs_init(), nfi_nfs_mkdir(), nfi_nfs_read(), nfi_nfs_readdir(), nfi_nfs_reconnect(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), nfi_nfs_setattr(), nfi_nfs_statfs(), nfi_nfs_write(), and nfs_open().
Variable Documentation
errno
int errno [extern]
Referenced by nfs_err().