nfi_local_err.h File Reference
Header file to 'TODO'.
Enumerations
enum nfi_local_err {
LOCALERR_PARAM = 0
, LOCALERR_MEMORY = 1
, LOCALERR_URL = 2
, LOCALERR_MNTCONNECTION = 3
,
LOCALERR_MOUNT = 4
, LOCALERR_NFSCONNECTION = 5
, LOCALERR_GETATTR = 6
, LOCALERR_LOOKUP = 7
,
LOCALERR_READ = 8
, LOCALERR_WRITE = 9
, LOCALERR_CREATE = 10
, LOCALERR_REMOVE = 11
,
LOCALERR_MKDIR = 12
, LOCALERR_READDIR = 13
, LOCALERR_STATFS = 14
, LOCALERR_NOTDIR = 15
 }
Functions
void local_err (int err)
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_local_err.h.
Enumeration Type Documentation
nfi_local_err
enum nfi_local_err
Enumerator
LOCALERR_PARAM
LOCALERR_MEMORY
LOCALERR_URL
LOCALERR_MNTCONNECTION
LOCALERR_MOUNT
LOCALERR_NFSCONNECTION
LOCALERR_GETATTR
LOCALERR_LOOKUP
LOCALERR_READ
LOCALERR_WRITE
LOCALERR_CREATE
LOCALERR_REMOVE
LOCALERR_MKDIR
LOCALERR_READDIR
LOCALERR_STATFS
LOCALERR_NOTDIR
Definition at line 40 of file nfi_local_err.h.
Function Documentation
local_err()
void local_err (int err)
Definition at line 43 of file nfi_local_err.c.
References errno, LOCALERR_GETATTR, LOCALERR_MEMORY, LOCALERR_MNTCONNECTION, LOCALERR_MOUNT, LOCALERR_NFSCONNECTION, LOCALERR_PARAM, and LOCALERR_URL.
Referenced by nfi_local_create(), nfi_local_mkdir(), nfi_local_open(), nfi_local_opendir(), nfi_local_readdir(), nfi_local_remove(), nfi_local_rename(), and nfi_local_rmdir().