nfi_tcp_server_err.c File Reference
File to 'TODO'.
#include nfi_tcp_server.h
Functions
void tcp_server_err (int err)
'TODO'.
Variables
int errno
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_tcp_server_err.c.
Function Documentation
tcp_server_err()
void tcp_server_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
Nothing.
Definition at line 40 of file nfi_tcp_server_err.c.
References errno, TCP_SERVERERR_GETATTR, TCP_SERVERERR_MEMORY, TCP_SERVERERR_MNTCONNECTION, TCP_SERVERERR_MOUNT, TCP_SERVERERR_NFSCONNECTION, TCP_SERVERERR_PARAM, and TCP_SERVERERR_URL.
Referenced by nfi_tcp_server_create(), nfi_tcp_server_flush(), nfi_tcp_server_getattr(), nfi_tcp_server_init(), nfi_tcp_server_mkdir(), nfi_tcp_server_open(), nfi_tcp_server_opendir(), nfi_tcp_server_preload(), nfi_tcp_server_read(), nfi_tcp_server_readdir(), nfi_tcp_server_reconnect(), nfi_tcp_server_remove(), nfi_tcp_server_rename(), nfi_tcp_server_rmdir(), and nfi_tcp_server_write().
Variable Documentation
errno
int errno [extern]
Referenced by tcp_server_err().