nfi_ops.h File Reference
Header file to 'TODO'.
#include nfi_worker_task.h
#include nfi_worker.h
Macros
#define XPN_HEADER_SIZE 8192
Enumerations
enum nfi_work {
noop = -1
, op_open = 0
, op_create = 1
, op_read = 2
,
op_write = 3
, op_close = 4
, op_remove = 5
, op_rename = 6
,
op_getattr = 7
, op_setattr = 8
, op_mkdir = 20
, op_rmdir = 21
,
op_opendir = 22
, op_readdir = 23
, op_closedir = 24
, op_statfs = 60
,
op_preload = 61
, op_flush = 62
 }
Functions
void nfi_do_operation (struct st_th th_arg)
'TODO'.
int nfi_worker_do_open (struct nfi_worker *wrk, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_worker_do_create (struct nfi_worker *wrk, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_worker_do_read (struct nfi_worker *wrk, struct nfi_fhandle *fh, struct nfi_worker_io *io, int n)
'TODO'.
int nfi_worker_do_write (struct nfi_worker *wrk, struct nfi_fhandle *fh, struct nfi_worker_io *io, int n)
'TODO'.
int nfi_worker_do_close (struct nfi_worker *wrk, struct nfi_fhandle *fh)
'TODO'.
int nfi_worker_do_remove (struct nfi_worker *wrk, char *url)
'TODO'.
int nfi_worker_do_rename (struct nfi_worker *wrk, char *old_url, char *new_url)
'TODO'.
int nfi_worker_do_getattr (struct nfi_worker *wrk, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_worker_do_setattr (struct nfi_worker *wrk, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_worker_do_mkdir (struct nfi_worker *wrk, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_worker_do_opendir (struct nfi_worker *wrk, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_worker_do_readdir (struct nfi_worker *wrk, struct nfi_fhandle *fhd, struct dirent *entry)
'TODO'.
int nfi_worker_do_closedir (struct nfi_worker *wrk, struct nfi_fhandle *fh)
'TODO'.
int nfi_worker_do_rmdir (struct nfi_worker *wrk, char *url)
'TODO'.
int nfi_worker_do_statfs (struct nfi_worker *wrk, struct nfi_info *inf)
'TODO'.
int nfi_worker_do_preload (struct nfi_worker *wrk, char *url, char *virtual_path, char *storage_path, int opt)
'TODO'.
int nfi_worker_do_flush (struct nfi_worker *wrk, char *url, char *virtual_path, char *storage_path, int opt)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_ops.h.
Macro Definition Documentation
XPN_HEADER_SIZE
#define XPN_HEADER_SIZE 8192
Definition at line 41 of file nfi_ops.h.
Enumeration Type Documentation
nfi_work
enum nfi_work
Enumerator
noop
op_open
op_create
op_read
op_write
op_close
op_remove
op_rename
op_getattr
op_setattr
op_mkdir
op_rmdir
op_opendir
op_readdir
op_closedir
op_statfs
op_preload
op_flush
Definition at line 50 of file nfi_ops.h.
Function Documentation
nfi_do_operation()
void nfi_do_operation (struct st_th th_arg)
'TODO'.
'TODO'.
Parameters
th_arg 'TODO'.
Returns
Nothing.
Definition at line 45 of file nfi_ops.c.
References nfi_worker::arg, nfi_worker_args::attr, nfi_worker_io::buffer, DEBUG_BEGIN, DEBUG_END, debug_info, nfi_worker_args::entry, nfi_worker_args::fh, nfi_worker_args::inf, nfi_worker_args::io, nfi_worker_args::n_io, nfi_worker_args::newurl, nfi_ops::nfi_close, nfi_ops::nfi_closedir, nfi_ops::nfi_create, nfi_ops::nfi_flush, nfi_ops::nfi_getattr, nfi_ops::nfi_mkdir, nfi_ops::nfi_open, nfi_ops::nfi_opendir, nfi_ops::nfi_preload, nfi_ops::nfi_read, nfi_ops::nfi_readdir, nfi_ops::nfi_remove, nfi_ops::nfi_rename, nfi_ops::nfi_rmdir, nfi_ops::nfi_setattr, nfi_ops::nfi_statfs, nfi_ops::nfi_write, nfi_worker_io::offset, op_close, op_closedir, op_create, op_flush, op_getattr, op_mkdir, op_open, op_opendir, op_preload, op_read, op_readdir, op_remove, op_rename, op_rmdir, op_setattr, op_statfs, op_write, nfi_worker_args::operation, nfi_server::ops, nfi_worker_args::opt, st_th::params, nfi_worker_args::result, nfi_worker::server, nfi_worker_io::size, nfi_worker_args::storage_path, nfi_worker_args::url, nfi_worker_args::virtual_path, and XPN_HEADER_SIZE.
Referenced by nfi_worker_do_close(), nfi_worker_do_closedir(), nfi_worker_do_create(), nfi_worker_do_flush(), nfi_worker_do_getattr(), nfi_worker_do_mkdir(), nfi_worker_do_open(), nfi_worker_do_opendir(), nfi_worker_do_preload(), nfi_worker_do_read(), nfi_worker_do_readdir(), nfi_worker_do_remove(), nfi_worker_do_rename(), nfi_worker_do_rmdir(), nfi_worker_do_setattr(), nfi_worker_do_statfs(), and nfi_worker_do_write().
nfi_worker_do_close()
int nfi_worker_do_close (struct nfi_worker * wrk, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 237 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_close, nfi_worker_args::operation, and nfi_worker::thread.
nfi_worker_do_closedir()
int nfi_worker_do_closedir (struct nfi_worker * wrk, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 365 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_closedir, nfi_worker_args::operation, and nfi_worker::thread.
nfi_worker_do_create()
int nfi_worker_do_create (struct nfi_worker * wrk, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 189 of file nfi_ops.c.
References nfi_worker::arg, nfi_worker_args::attr, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_create, nfi_worker_args::operation, nfi_worker::thread, and nfi_worker_args::url.
Referenced by xpn_internal_creat().
nfi_worker_do_flush()
int nfi_worker_do_flush (struct nfi_worker * wrk, char * url, char * virtual_path, char * storage_path, int opt)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
virtual_path 'TODO'.
storage_path 'TODO'.
opt 'TODO'.
Returns
'TODO'.
Definition at line 411 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_do_operation(), nfi_ops::nfi_flush, nfiworker_launch(), op_flush, nfi_worker_args::operation, nfi_server::ops, nfi_worker_args::opt, nfi_worker_args::result, nfi_worker::server, nfi_worker_args::storage_path, nfi_worker::thread, nfi_worker_args::url, and nfi_worker_args::virtual_path.
Referenced by xpn_simple_flush().
nfi_worker_do_getattr()
int nfi_worker_do_getattr (struct nfi_worker * wrk, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 284 of file nfi_ops.c.
References nfi_worker::arg, nfi_worker_args::attr, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_getattr, nfi_worker_args::operation, and nfi_worker::thread.
Referenced by XpnGetAtribFd(), and XpnGetAtribPath().
nfi_worker_do_mkdir()
int nfi_worker_do_mkdir (struct nfi_worker * wrk, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 319 of file nfi_ops.c.
References nfi_worker::arg, nfi_worker_args::attr, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_mkdir, nfi_worker_args::operation, nfi_worker::thread, and nfi_worker_args::url.
Referenced by xpn_simple_mkdir().
nfi_worker_do_open()
int nfi_worker_do_open (struct nfi_worker * wrk, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 174 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_open, nfi_worker_args::operation, nfi_worker::thread, and nfi_worker_args::url.
nfi_worker_do_opendir()
int nfi_worker_do_opendir (struct nfi_worker * wrk, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 335 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_opendir, nfi_worker_args::operation, nfi_worker::thread, and nfi_worker_args::url.
nfi_worker_do_preload()
int nfi_worker_do_preload (struct nfi_worker * wrk, char * url, char * virtual_path, char * storage_path, int opt)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
virtual_path 'TODO'.
storage_path 'TODO'.
opt 'TODO'.
Returns
'TODO'.
Definition at line 434 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_do_operation(), nfi_ops::nfi_preload, nfiworker_launch(), op_preload, nfi_worker_args::operation, nfi_server::ops, nfi_worker_args::opt, nfi_worker_args::result, nfi_worker::server, nfi_worker_args::storage_path, nfi_worker::thread, nfi_worker_args::url, and nfi_worker_args::virtual_path.
Referenced by xpn_simple_preload().
nfi_worker_do_read()
int nfi_worker_do_read (struct nfi_worker * wrk, struct nfi_fhandle * fh, struct nfi_worker_io * io, int n)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
fh 'TODO'.
io 'TODO'.
n 'TODO'.
Returns
'TODO'.
Definition at line 205 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::fh, nfi_worker_args::io, nfi_worker_args::n_io, nfi_do_operation(), nfiworker_launch(), op_read, nfi_worker_args::operation, and nfi_worker::thread.
Referenced by xpn_pread().
nfi_worker_do_readdir()
int nfi_worker_do_readdir (struct nfi_worker * wrk, struct nfi_fhandle * fhd, struct dirent * entry)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
fhd 'TODO'.
entry 'TODO'.
Returns
'TODO'.
Definition at line 350 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::entry, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_readdir, nfi_worker_args::operation, and nfi_worker::thread.
nfi_worker_do_remove()
int nfi_worker_do_remove (struct nfi_worker * wrk, char * url)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 255 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_do_operation(), nfiworker_launch(), op_remove, nfi_worker_args::operation, nfi_worker::thread, and nfi_worker_args::url.
Referenced by xpn_internal_remove().
nfi_worker_do_rename()
int nfi_worker_do_rename (struct nfi_worker * wrk, char * old_url, char * new_url)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
old_url 'TODO'.
new_url 'TODO'.
Returns
'TODO'.
Definition at line 269 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::newurl, nfi_do_operation(), nfiworker_launch(), op_rename, nfi_worker_args::operation, nfi_worker::thread, and nfi_worker_args::url.
Referenced by xpn_simple_rename().
nfi_worker_do_rmdir()
int nfi_worker_do_rmdir (struct nfi_worker * wrk, char * url)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 379 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_do_operation(), nfiworker_launch(), op_rmdir, nfi_worker_args::operation, nfi_worker::thread, and nfi_worker_args::url.
Referenced by xpn_simple_rmdir().
nfi_worker_do_setattr()
int nfi_worker_do_setattr (struct nfi_worker * wrk, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 299 of file nfi_ops.c.
References nfi_worker::arg, nfi_worker_args::attr, debug_info, nfi_worker_args::fh, nfi_do_operation(), nfiworker_launch(), op_setattr, nfi_worker_args::operation, and nfi_worker::thread.
nfi_worker_do_statfs()
int nfi_worker_do_statfs (struct nfi_worker * wrk, struct nfi_info * inf)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
inf 'TODO'.
Returns
'TODO'.
Definition at line 397 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::inf, nfi_do_operation(), nfiworker_launch(), op_statfs, nfi_worker_args::operation, and nfi_worker::thread.
nfi_worker_do_write()
int nfi_worker_do_write (struct nfi_worker * wrk, struct nfi_fhandle * fh, struct nfi_worker_io * io, int n)
'TODO'.
'TODO'.
Parameters
wrk 'TODO'.
fh 'TODO'.
io 'TODO'.
n 'TODO'.
Returns
'TODO'.
Definition at line 221 of file nfi_ops.c.
References nfi_worker::arg, debug_info, nfi_worker_args::fh, nfi_worker_args::io, nfi_worker_args::n_io, nfi_do_operation(), nfiworker_launch(), op_write, nfi_worker_args::operation, and nfi_worker::thread.
Referenced by xpn_pwrite().