nfi_mpi_server.h File Reference
Header file to 'TODO'.
#include all_system.h
#include base/utils.h
#include base/path_misc.h
#include base/urlstr.h
#include base/workers.h
#include mpi_server_ops.h
#include mpi_server_comm.h
#include mpi_server_params.h
#include nfi_mpi_server_err.h
#include nfi.h
#include nfi_worker.h
Data Structures
struct nfi_mpi_server_server
struct nfi_mpi_server_fhandle
Functions
int nfi_mpi_server_init (char *url, struct nfi_server *serv, struct nfi_attr_server *attr)
int nfi_mpi_server_connect (struct nfi_server *server, char *url, char *prt, char *serv, char *dir)
int nfi_mpi_server_reconnect (struct nfi_server *server)
int nfi_mpi_server_disconnect (struct nfi_server *server)
int nfi_mpi_server_create (struct nfi_server *server, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
int nfi_mpi_server_open (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
ssize_t nfi_mpi_server_read (struct nfi_server *server, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
ssize_t nfi_mpi_server_write (struct nfi_server *server, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
int nfi_mpi_server_close (struct nfi_server *server, struct nfi_fhandle *fh)
int nfi_mpi_server_remove (struct nfi_server *server, char *url)
int nfi_mpi_server_rename (struct nfi_server *server, char *old_url, char *new_url)
int nfi_mpi_server_getattr (struct nfi_server *server, struct nfi_fhandle *fh, struct nfi_attr *attr)
int nfi_mpi_server_setattr (struct nfi_server *server, struct nfi_fhandle *fh, struct nfi_attr *attr)
int nfi_mpi_server_mkdir (struct nfi_server *server, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
int nfi_mpi_server_opendir (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
int nfi_mpi_server_readdir (struct nfi_server *server, struct nfi_fhandle *fhd, struct dirent *entry)
int nfi_mpi_server_closedir (struct nfi_server *server, struct nfi_fhandle *fhd)
int nfi_mpi_server_rmdir (struct nfi_server *server, char *url)
int nfi_mpi_server_statfs (struct nfi_server *server, struct nfi_info *inf)
int nfi_mpi_server_preload (struct nfi_server *server, char *url, char *virtual_path, char *storage_path, int opt)
int nfi_mpi_server_flush (struct nfi_server *server, char *url, char *virtual_path, char *storage_path, int opt)
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_mpi_server.h.
Function Documentation
nfi_mpi_server_close()
int nfi_mpi_server_close (struct nfi_server * server, struct nfi_fhandle * fh)
Definition at line 1118 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, st_mpi_server_close::fd, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MPI_SERVER_CLOSE_FILE_WS, MPI_SERVER_ID, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFINULL, NULL_RET_ERR, st_mpi_server_msg::op_close, nfi_mpi_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_closedir()
int nfi_mpi_server_closedir (struct nfi_server * server, struct nfi_fhandle * fhd)
Definition at line 1690 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, st_mpi_server_closedir::dir, nfi_mpi_server_fhandle::dir, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MPI_SERVER_CLOSEDIR_DIR, MPI_SERVER_ID, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_closedir, nfi_mpi_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_closedir, st_mpi_server_msg::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_connect()
int nfi_mpi_server_connect (struct nfi_server * server, char * url, char * prt, char * serv, char * dir)
nfi_mpi_server_create()
int nfi_mpi_server_create (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
Definition at line 671 of file nfi_mpi_server.c.
References nfi_attr::at_mode, st_mpi_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MPI_SERVER_CREAT_FILE_WOS, MPI_SERVER_CREAT_FILE_WS, mpi_server_err(), MPI_SERVER_GETATTR_FILE, MPI_SERVER_ID, MPI_SERVERERR_MEMORY, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, MPI_SERVERtoNFIattr(), nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_CREAT, O_RDWR, O_TRUNC, st_mpi_server_msg::op_creat, st_mpi_server_msg::op_getattr, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_creat::path, st_mpi_server_getattr::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, real_posix_stat, nfi_server::server, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_disconnect()
int nfi_mpi_server_disconnect (struct nfi_server * server)
Definition at line 483 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, FREE_AND_NULL, mpiClient_comm_disconnect(), nfi_mpi_server_server::params, and nfi_server::private_info.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_flush()
int nfi_mpi_server_flush (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
Definition at line 1890 of file nfi_mpi_server.c.
References st_mpi_server_flush::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpi_server_err(), MPI_SERVER_FLUSH_FILE, MPI_SERVER_ID, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_flush, st_mpi_server_flush::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_mpi_server_flush::storage_path, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and st_mpi_server_flush::virtual_path.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_getattr()
int nfi_mpi_server_getattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
Definition at line 1346 of file nfi_mpi_server.c.
References st_mpi_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, mpiClient_param_st::dirbase, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_GETATTR_FILE, MPI_SERVER_ID, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, MPI_SERVERtoNFIattr(), nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_getattr, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_getattr::path, nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, real_posix_stat, st_mpi_server_attr_req::status, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_fhandle::url.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_init()
int nfi_mpi_server_init (char * url, struct nfi_server * serv, struct nfi_attr_server * attr)
nfi_mpi_server_mkdir()
int nfi_mpi_server_mkdir (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
Definition at line 1439 of file nfi_mpi_server.c.
References st_mpi_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, errno, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_GETATTR_FILE, MPI_SERVER_ID, MPI_SERVER_MKDIR_DIR, MPI_SERVERERR_MEMORY, MPI_SERVERERR_MKDIR, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, MPI_SERVERtoNFIattr(), nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_mpi_server_msg::op_getattr, st_mpi_server_msg::op_mkdir, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_getattr::path, st_mpi_server_mkdir::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_mkdir, real_posix_stat, nfi_server::server, STRING_MISC_StrDup(), st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_fhandle::url.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_open()
int nfi_mpi_server_open (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
Definition at line 568 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, nfi_mpi_server_fhandle::fd, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_OPEN_FILE_WOS, MPI_SERVER_OPEN_FILE_WS, MPI_SERVERERR_MEMORY, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_RDWR, st_mpi_server_msg::op_open, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_open::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, nfi_server::server, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_opendir()
int nfi_mpi_server_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
Definition at line 1543 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, FREE_AND_NULL, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_OPENDIR_DIR, MPI_SERVERERR_MEMORY, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_mpi_server_msg::op_opendir, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_opendir::path, nfi_mpi_server_server::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_opendir, nfi_server::server, nfi_fhandle::server, st_mpi_server_msg::type, nfi_fhandle::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_fhandle::url.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_preload()
int nfi_mpi_server_preload (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
Definition at line 1836 of file nfi_mpi_server.c.
References st_mpi_server_preload::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_PRELOAD_FILE, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_preload, st_mpi_server_preload::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_mpi_server_preload::storage_path, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and st_mpi_server_preload::virtual_path.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_read()
ssize_t nfi_mpi_server_read (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
Definition at line 797 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, errno, st_mpi_server_read::fd, nfi_mpi_server_fhandle::fd, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_READ_FILE_WOS, MPI_SERVER_READ_FILE_WS, mpi_server_write_operation(), MPI_SERVERERR_PARAM, MPI_SERVERERR_READ, mpiClient_read_data(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, O_RDONLY, st_mpi_server_read::offset, st_mpi_server_msg::op_read, nfi_mpi_server_server::params, st_mpi_server_read::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_read, mpiClient_param_st::server, st_mpi_server_read::size, st_mpi_server_read_req::size, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_readdir()
int nfi_mpi_server_readdir (struct nfi_server * server, struct nfi_fhandle * fhd, struct dirent * entry)
Definition at line 1625 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, st_mpi_server_readdir::dir, nfi_mpi_server_fhandle::dir, st_mpi_server_direntry::end, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_READDIR_DIR, MPI_SERVERERR_NOTDIR, MPI_SERVERERR_PARAM, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_mpi_server_msg::op_readdir, nfi_mpi_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_readdir, st_mpi_server_direntry::ret, st_mpi_server_msg::type, nfi_fhandle::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_reconnect()
int nfi_mpi_server_reconnect (struct nfi_server * server)
Definition at line 519 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, mpi_server_err(), MPI_SERVERERR_MEMORY, MPI_SERVERERR_URL, mpiClient_comm_connect(), NULL_RET_ERR, nfi_mpi_server_server::params, ParseURL(), nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, and nfi_server::url.
Referenced by nfi_mpi_server_init(), and nfi_mpi_server_keepConnected().
nfi_mpi_server_remove()
int nfi_mpi_server_remove (struct nfi_server * server, char * url)
Definition at line 1188 of file nfi_mpi_server.c.
References nfi_worker::arg, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, st_mpi_server_msg::id, nfi_mpi_server_server::id, nfi_worker_args::is_master_node, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_RM_FILE, MPI_SERVER_RM_FILE_ASYNC, mpi_server_write_operation(), MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_rm, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_rm::path, nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, real_posix_unlink, nfi_server::server, mpiClient_param_st::server, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, and nfi_server::wrk.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_rename()
int nfi_mpi_server_rename (struct nfi_server * server, char * old_url, char * new_url)
Definition at line 1265 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_RENAME_FILE, MPI_SERVERERR_PARAM, MPI_SERVERERR_URL, st_mpi_server_rename::new_url, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_rename::old_url, st_mpi_server_msg::op_rename, nfi_mpi_server_server::params, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_rename, nfi_server::server, st_mpi_server_msg::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_rmdir()
int nfi_mpi_server_rmdir (struct nfi_server * server, char * url)
Definition at line 1738 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_mpi_server_fhandle::dir, mpiClient_param_st::dirbase, mpiClient_param_st::locality, mpi_server_err(), MPI_SERVER_RMDIR_DIR, MPI_SERVERERR_PARAM, MPI_SERVERERR_REMOVE, MPI_SERVERERR_URL, nfi_mpi_server_doRequest(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, st_mpi_server_msg::op_rmdir, nfi_mpi_server_server::params, ParseURL(), st_mpi_server_rmdir::path, nfi_mpi_server_server::path, PATH_MAX, nfi_server::private_info, real_posix_rmdir, nfi_server::server, st_mpi_server_msg::type, and st_mpi_server_msg::u_st_mpi_server_msg.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_setattr()
int nfi_mpi_server_setattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
Definition at line 1412 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, MPI_SERVERERR_PARAM, nfi_mpi_server_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, and nfi_server::private_info.
Referenced by nfi_mpi_server_init().
nfi_mpi_server_statfs()
int nfi_mpi_server_statfs (struct nfi_server * server, struct nfi_info * inf)
nfi_mpi_server_write()
ssize_t nfi_mpi_server_write (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
Definition at line 949 of file nfi_mpi_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, mpiClient_param_st::dirbase, errno, st_mpi_server_write::fd, nfi_mpi_server_fhandle::fd, st_mpi_server_msg::id, nfi_mpi_server_server::id, mpiClient_param_st::locality, MAX_BUFFER_SIZE, mpi_server_err(), MPI_SERVER_ID, MPI_SERVER_WRITE_FILE_WOS, MPI_SERVER_WRITE_FILE_WS, mpi_server_write_operation(), MPI_SERVERERR_PARAM, MPI_SERVERERR_WRITE, mpiClient_read_data(), mpiClient_write_data(), nfi_mpi_server_keepConnected(), NULL_RET_ERR, O_WRONLY, st_mpi_server_write::offset, st_mpi_server_msg::op_write, nfi_mpi_server_server::params, st_mpi_server_write::path, nfi_mpi_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_write, mpiClient_param_st::server, st_mpi_server_write::size, st_mpi_server_write_req::size, st_mpi_server_msg::type, st_mpi_server_msg::u_st_mpi_server_msg, nfi_fhandle::url, and mpiClient_param_st::xpn_session.
Referenced by nfi_mpi_server_init().