nfi_nfs3.c File Reference
File to 'TODO'.
#include nfi_nfs3.h
Functions
void NFItoNFS3attr (fattr3 *nfs3_att, struct nfi_attr *nfi_att)
'TODO'.
void NFS3toNFIattr (struct nfi_attr *nfi_att, fattr3 *nfs3_att)
'TODO'.
void NFS3toNFIInfo (__attribute__((__unused__)) struct nfi_info *nfi_inf, __attribute__((__unused__)) fsinfo3resok *nfs3_inf)
int nfi_nfs3_init (char *url, struct nfi_server *serv, __attribute__((__unused__)) struct nfi_attr_server *attr)
int nfi_nfs3_disconnect (struct nfi_server *serv)
Disconnect to the server.
int nfi_nfs3_reconnect (struct nfi_server *serv)
Reconnect to the NFS server.
int nfi_nfs3_destroy (struct nfi_server *serv)
Destroy NFS operations.
int nfi_nfs3_getattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_nfs3_setattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfs3_open (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_nfs3_open (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_nfs3_close (struct nfi_server *server, struct nfi_fhandle *fh)
'TODO'.
ssize_t nfi_nfs3_read (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
ssize_t nfi_nfs3_write (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
int nfi_nfs3_create (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_nfs3_remove (struct nfi_server *serv, char *url)
'TODO'.
int nfi_nfs3_rename (__attribute__((__unused__)) struct nfi_server *server, __attribute__((__unused__)) char *old_url, __attribute__((__unused__)) char *new_url)
int nfi_nfs3_mkdir (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_nfs3_rmdir (struct nfi_server *serv, char *url)
'TODO'.
int nfi_nfs3_opendir (struct nfi_server *server, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_nfs3_readdir (struct nfi_server *serv, struct nfi_fhandle *fh, struct dirent *entry)
int nfi_nfs3_closedir (struct nfi_server *serv, struct nfi_fhandle *fh)
'TODO'.
int nfi_nfs3_statfs (struct nfi_server *serv, struct nfi_info *inf)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_nfs3.c.
Function Documentation
nfi_nfs3_close()
int nfi_nfs3_close (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 713 of file nfi_nfs3.c.
References nfi_nfs3_server::fh, NFINULL, nfs3_err(), and NFS3ERR_PARAM.
Referenced by nfi_nfs3_closedir(), nfi_nfs3_init(), nfi_nfs3_open(), and nfi_nfs3_opendir().
nfi_nfs3_closedir()
int nfi_nfs3_closedir (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 1399 of file nfi_nfs3.c.
References nfi_nfs3_fhandle::fh, and nfi_nfs3_close().
Referenced by nfi_nfs3_init().
nfi_nfs3_create()
int nfi_nfs3_create (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 869 of file nfi_nfs3.c.
References nfi_attr::at_mode, nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_fhandle::fh, getDirWithURL(), getNameFile(), MNTNAMLEN, nfi_nfs3_reconnect(), nfs3_create(), nfs3_err(), nfs3_lookup(), NFS3ERR_CREATE, NFS3ERR_MEMORY, NFS3ERR_PARAM, NFS3ERR_URL, NFS3toNFIattr(), ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs3_init().
nfi_nfs3_destroy()
int nfi_nfs3_destroy (struct nfi_server * server)
Destroy NFS operations.
'TODO'.
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 391 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, close_connection_mount3(), close_connection_nfs3(), create_connection_mount3(), MNTNAMLEN, nfi_worker_end(), nfs3_err(), NFS3_UDP, nfs3_umount(), NFS3ERR_URL, nfi_server::ops, ParseURL(), nfi_server::private_info, nfi_server::server, nfi_server::url, and nfi_server::wrk.
nfi_nfs3_disconnect()
int nfi_nfs3_disconnect (struct nfi_server * server)
Disconnect to the server.
'TODO'.
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 282 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, close_connection_mount3(), close_connection_nfs3(), create_connection_mount3(), MNTNAMLEN, nfi_worker_end(), nfs3_err(), NFS3_UDP, nfs3_umount(), NFS3ERR_URL, ParseURL(), nfi_server::private_info, nfi_server::server, nfi_server::url, and nfi_server::wrk.
Referenced by nfi_nfs3_init().
nfi_nfs3_getattr()
int nfi_nfs3_getattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 451 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_fhandle::fh, nfi_nfs3_reconnect(), nfs3_err(), nfs3_getattr(), NFS3ERR_PARAM, NFS3toNFIattr(), nfi_server::private_info, and nfi_server::server.
Referenced by nfi_nfs3_init().
nfi_nfs3_init()
int nfi_nfs3_init (char * url, struct nfi_server * serv, __attribute__((__unused__)) struct nfi_attr_server * attr)
Definition at line 119 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, close_connection_mount3(), close_connection_nfs3(), create_connection_mount3(), create_connection_nfs3(), nfi_nfs3_server::fh, MNTNAMLEN, nfi_ops::nfi_close, nfi_ops::nfi_closedir, nfi_ops::nfi_create, nfi_ops::nfi_disconnect, nfi_ops::nfi_getattr, nfi_ops::nfi_mkdir, nfi_nfs3_close(), nfi_nfs3_closedir(), nfi_nfs3_create(), nfi_nfs3_disconnect(), nfi_nfs3_getattr(), nfi_nfs3_mkdir(), nfi_nfs3_open(), nfi_nfs3_opendir(), nfi_nfs3_read(), nfi_nfs3_readdir(), nfi_nfs3_reconnect(), nfi_nfs3_remove(), nfi_nfs3_rename(), nfi_nfs3_rmdir(), nfi_nfs3_setattr(), nfi_nfs3_statfs(), nfi_nfs3_write(), nfi_ops::nfi_open, nfi_ops::nfi_opendir, nfi_ops::nfi_read, nfi_ops::nfi_readdir, nfi_ops::nfi_reconnect, nfi_ops::nfi_remove, nfi_ops::nfi_rename, nfi_ops::nfi_rmdir, nfi_ops::nfi_setattr, nfi_ops::nfi_statfs, nfi_worker_init(), nfi_ops::nfi_write, nfs3_err(), nfs3_mount(), NFS3_TCP, NFS3_UDP, NFS3ERR_MEMORY, NFS3ERR_MNTCONNECTION, NFS3ERR_NFSCONNECTION, NFS3ERR_PARAM, NFS3ERR_URL, nfi_server::ops, ParseURL(), nfi_server::private_info, nfi_server::server, nfi_server::url, and nfi_server::wrk.
Referenced by XpnGetServer().
nfi_nfs3_mkdir()
int nfi_nfs3_mkdir (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 1104 of file nfi_nfs3.c.
References nfi_attr::at_mode, nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_fhandle::fh, getDirWithURL(), getNameFile(), MNTNAMLEN, nfi_nfs3_reconnect(), nfs3_err(), nfs3_lookup(), nfs3_mkdir(), NFS3ERR_MEMORY, NFS3ERR_MKDIR, NFS3ERR_PARAM, NFS3ERR_URL, NFS3toNFIattr(), ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs3_init().
nfi_nfs3_open()
int nfi_nfs3_open (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 695 of file nfi_nfs3.c.
References nfi_nfs3_close(), NFIFILE, nfs3_open(), and nfi_fhandle::type.
Referenced by nfi_nfs3_init().
nfi_nfs3_opendir()
int nfi_nfs3_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 1305 of file nfi_nfs3.c.
References nfi_nfs3_close(), NFIDIR, nfs3_err(), nfs3_open(), nfi_server::server, and nfi_fhandle::type.
Referenced by nfi_nfs3_init().
nfi_nfs3_read()
ssize_t nfi_nfs3_read (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 744 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_fhandle::fh, nfi_nfs3_reconnect(), nfs3_err(), nfs3_read(), NFS3ERR_PARAM, and nfi_server::private_info.
Referenced by nfi_nfs3_init().
nfi_nfs3_readdir()
int nfi_nfs3_readdir (struct nfi_server * serv, struct nfi_fhandle * fh, struct dirent * entry)
Definition at line 1324 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_fhandle::cookie, nfi_nfs3_fhandle::eofdir, nfi_nfs3_fhandle::fh, nfi_nfs3_reconnect(), NFIDIR, nfs3_err(), nfs3_readdir(), NFS3ERR_EOFDIR, NFS3ERR_PARAM, NFS3ERR_READDIR, nfi_server::private_info, and nfi_server::server.
Referenced by nfi_nfs3_init().
nfi_nfs3_reconnect()
int nfi_nfs3_reconnect (struct nfi_server * server)
Reconnect to the NFS server.
'TODO'.
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 333 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, close_connection_mount3(), create_connection_mount3(), create_connection_nfs3(), nfi_nfs3_server::fh, MNTNAMLEN, nfs3_err(), nfs3_mount(), NFS3_UDP, NFS3ERR_MEMORY, NFS3ERR_MNTCONNECTION, NFS3ERR_NFSCONNECTION, NFS3ERR_URL, ParseURL(), nfi_server::private_info, and nfi_server::url.
Referenced by nfi_nfs3_create(), nfi_nfs3_getattr(), nfi_nfs3_init(), nfi_nfs3_mkdir(), nfi_nfs3_read(), nfi_nfs3_readdir(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs3_setattr(), nfi_nfs3_statfs(), nfi_nfs3_write(), and nfs3_open().
nfi_nfs3_remove()
int nfi_nfs3_remove (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 990 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, getDirWithURL(), getNameFile(), MNTNAMLEN, nfi_nfs3_reconnect(), nfs3_err(), nfs3_lookup(), nfs3_remove(), NFS3ERR_LOOKUP, NFS3ERR_PARAM, NFS3ERR_REMOVE, NFS3ERR_URL, ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs3_init().
nfi_nfs3_rename()
int nfi_nfs3_rename (__attribute__((__unused__)) struct nfi_server * server, __attribute__((__unused__)) char * old_url, __attribute__((__unused__)) char * new_url)
Definition at line 1073 of file nfi_nfs3.c.
Referenced by nfi_nfs3_init().
nfi_nfs3_rmdir()
int nfi_nfs3_rmdir (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 1224 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, getDirWithURL(), getNameFile(), MNTNAMLEN, nfi_nfs3_reconnect(), nfs3_err(), nfs3_lookup(), nfs3_rmdir(), NFS3ERR_LOOKUP, NFS3ERR_PARAM, NFS3ERR_REMOVE, NFS3ERR_URL, ParseURL(), nfi_server::private_info, nfi_server::server, and nfi_server::url.
Referenced by nfi_nfs3_init().
nfi_nfs3_setattr()
int nfi_nfs3_setattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 521 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_fhandle::fh, nfi_nfs3_reconnect(), NFItoNFS3attr(), nfs3_err(), nfs3_setattr(), NFS3ERR_PARAM, nfi_server::private_info, and nfi_server::server.
Referenced by nfi_nfs3_init().
nfi_nfs3_statfs()
int nfi_nfs3_statfs (struct nfi_server * server, struct nfi_info * inf)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
inf 'TODO'.
Returns
'TODO'.
Definition at line 1404 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_reconnect(), nfs3_err(), nfs3_statfs(), NFS3ERR_PARAM, NFS3ERR_STATFS, NFS3toNFIInfo(), nfi_server::private_info, and nfi_server::server.
Referenced by nfi_nfs3_init().
nfi_nfs3_write()
ssize_t nfi_nfs3_write (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 808 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_fhandle::fh, nfi_nfs3_reconnect(), nfs3_err(), nfs3_write(), NFS3ERR_PARAM, NFS3ERR_WRITE, and nfi_server::private_info.
Referenced by nfi_nfs3_init().
NFItoNFS3attr()
void NFItoNFS3attr (fattr3 * nfs_att, struct nfi_attr * nfi_att)
'TODO'.
'TODO'.
Parameters
nfs_att 'TODO'.
nfi_att 'TODO'.
Returns
Nothing.
Definition at line 40 of file nfi_nfs3.c.
References nfi_attr::at_atime, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, fattr3::atime, fattr3::ctime, fattr3::gid, fattr3::mode, fattr3::mtime, NF3DIR, NF3REG, NFIDIR, NFIFILE, nfstime3::seconds, fattr3::size, nfi_attr::st_dev, nfi_attr::st_ino, fattr3::type, and fattr3::uid.
Referenced by nfi_nfs3_setattr().
nfs3_open()
int nfs3_open (struct nfi_server * serv, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
serv 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 593 of file nfi_nfs3.c.
References nfi_nfs3_server::cl, nfi_nfs3_server::fh, nfi_nfs3_fhandle::fh, getDirWithURL(), MNTNAMLEN, NF3DIR, NF3REG, nfi_nfs3_reconnect(), NFIDIR, NFIFILE, nfs3_err(), nfs3_lookup(), NFS3ERR_MEMORY, NFS3ERR_PARAM, NFS3ERR_URL, ParseURL(), nfi_fhandle::priv_fh, nfi_server::private_info, nfi_fhandle::server, nfi_fhandle::type, nfi_server::url, and nfi_fhandle::url.
Referenced by nfi_nfs3_open(), and nfi_nfs3_opendir().
NFS3toNFIattr()
void NFS3toNFIattr (struct nfi_attr * nfi_att, fattr3 * nfs_att)
'TODO'.
'TODO'.
Parameters
nfi_att 'TODO'.
nfs_att 'TODO'.
Returns
Nothing.
Definition at line 73 of file nfi_nfs3.c.
References nfi_attr::at_atime, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, fattr3::atime, fattr3::ctime, fattr3::gid, fattr3::mode, fattr3::mtime, NF3DIR, NF3REG, NFIDIR, NFIFILE, nfi_attr::private_info, nfstime3::seconds, fattr3::size, nfi_attr::st_dev, nfi_attr::st_ino, fattr3::type, and fattr3::uid.
Referenced by nfi_nfs3_create(), nfi_nfs3_getattr(), and nfi_nfs3_mkdir().
NFS3toNFIInfo()
void NFS3toNFIInfo (__attribute__((__unused__)) struct nfi_info * nfi_inf, __attribute__((__unused__)) fsinfo3resok * nfs3_inf)
Definition at line 110 of file nfi_nfs3.c.
Referenced by nfi_nfs3_statfs().