nfi_tcp_server.c File Reference
File to 'TODO'.
#include nfi_tcp_server.h
Macros
#define FILESYSTEM_DLSYM 1
Functions
int tcp_server_write_operation (int sd, struct st_tcp_server_msg *head)
int nfi_tcp_server_doRequest (struct nfi_tcp_server_server *server_aux, struct st_tcp_server_msg *msg, char *req, int req_size)
int nfi_tcp_server_keepConnected (struct nfi_server *serv)
void NFItoTCP_SERVERattr (struct stat *att, struct nfi_attr *nfi_att)
void TCP_SERVERtoNFIattr (struct nfi_attr *nfi_att, struct stat *att)
void TCP_SERVERtoNFIInfo (__attribute__((__unused__)) struct nfi_info *nfi_inf, __attribute__((__unused__)) struct nfi_info *tcp_server_inf)
int nfi_tcp_server_init (char *url, struct nfi_server *serv, __attribute__((__unused__)) struct nfi_attr_server *attr)
int nfi_tcp_server_destroy (struct nfi_server *serv)
Destroy tcp_server.
int nfi_tcp_server_connect (struct nfi_server *serv, __attribute__((__unused__)) char *url, __attribute__((__unused__)) char *prt, char *server, __attribute__((__unused__)) char *dir)
int nfi_tcp_server_disconnect (struct nfi_server *serv)
Disconnect to the server.
int nfi_tcp_server_reconnect (struct nfi_server *serv)
Reconnect to the TCP server.
int nfi_tcp_server_open (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_tcp_server_create (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
ssize_t nfi_tcp_server_read (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
ssize_t nfi_tcp_server_write (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
int nfi_tcp_server_close (struct nfi_server *serv, struct nfi_fhandle *fh)
'TODO'.
int nfi_tcp_server_remove (struct nfi_server *serv, char *url)
'TODO'.
int nfi_tcp_server_rename (struct nfi_server *serv, char *old_url, char *new_url)
'TODO'.
int nfi_tcp_server_getattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_tcp_server_setattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_tcp_server_mkdir (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_tcp_server_opendir (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_tcp_server_readdir (struct nfi_server *serv, struct nfi_fhandle *fh, struct dirent *entry)
'TODO'.
int nfi_tcp_server_closedir (struct nfi_server *serv, struct nfi_fhandle *fh)
'TODO'.
int nfi_tcp_server_rmdir (struct nfi_server *serv, char *url)
'TODO'.
int nfi_tcp_server_statfs (__attribute__((__unused__)) struct nfi_server *serv, __attribute__((__unused__)) struct nfi_info *inf)
int nfi_tcp_server_preload (struct nfi_server *serv, char *url, char *virtual_path, char *storage_path, int opt)
'TODO'.
int nfi_tcp_server_flush (struct nfi_server *serv, char *url, char *virtual_path, char *storage_path, int opt)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_tcp_server.c.
Macro Definition Documentation
FILESYSTEM_DLSYM
#define FILESYSTEM_DLSYM 1
Definition at line 41 of file nfi_tcp_server.c.
Function Documentation
nfi_tcp_server_close()
int nfi_tcp_server_close (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 1190 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, st_tcp_server_close::fd, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFINULL, NULL_RET_ERR, st_tcp_server_msg::op_close, nfi_tcp_server_server::params, st_tcp_server_close::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, nfi_fhandle::server, TCP_SERVER_CLOSE_FILE_WS, TCP_SERVER_ID, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_closedir()
int nfi_tcp_server_closedir (struct nfi_server * server, struct nfi_fhandle * fhd)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fhd 'TODO'.
Returns
'TODO'.
Definition at line 1704 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, st_tcp_server_closedir::dir, nfi_tcp_server_fhandle::dir, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_closedir, nfi_tcp_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_closedir, TCP_SERVER_CLOSEDIR_DIR, TCP_SERVER_ID, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_connect()
int nfi_tcp_server_connect (struct nfi_server * serv, __attribute__((__unused__)) char * url, __attribute__((__unused__)) char * prt, char * server, __attribute__((__unused__)) char * dir)
Definition at line 512 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, nfi_tcp_server_server::params, nfi_server::private_info, tcpClient_param_st::srv_name, and tcpClient_comm_connect().
Referenced by nfi_tcp_server_init().
nfi_tcp_server_create()
int nfi_tcp_server_create (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 721 of file nfi_tcp_server.c.
References nfi_attr::at_mode, st_tcp_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_fhandle::dir, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_CREAT, O_RDWR, O_TRUNC, st_tcp_server_msg::op_creat, st_tcp_server_msg::op_getattr, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_creat::path, st_tcp_server_getattr::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, real_posix_stat, nfi_server::server, nfi_fhandle::server, tcpClient_param_st::server_name, TCP_SERVER_CREAT_FILE_WOS, TCP_SERVER_CREAT_FILE_WS, tcp_server_err(), TCP_SERVER_GETATTR_FILE, TCP_SERVER_ID, TCP_SERVERERR_MEMORY, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, TCP_SERVERtoNFIattr(), st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_destroy()
int nfi_tcp_server_destroy (struct nfi_server * serv)
Destroy tcp_server.
'TODO'.
Parameters
serv 'TODO'.
Returns
'TODO'.
Definition at line 458 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, FREE_AND_NULL, nfi_tcp_server_server::mqtt, nfiworker_destroy(), nfi_server::ops, nfi_tcp_server_server::params, nfi_server::private_info, nfi_server::server, tcpClient_comm_destroy(), nfi_server::url, and tcpClient_param_st::xpn_mosquitto_mode.
nfi_tcp_server_disconnect()
int nfi_tcp_server_disconnect (struct nfi_server * server)
Disconnect to the server.
'TODO'.
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 545 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, FREE_AND_NULL, nfi_tcp_server_server::params, nfi_server::private_info, and tcpClient_comm_disconnect().
Referenced by nfi_tcp_server_init().
nfi_tcp_server_doRequest()
int nfi_tcp_server_doRequest (struct nfi_tcp_server_server * server_aux, struct st_tcp_server_msg * msg, char * req, int req_size)
Definition at line 140 of file nfi_tcp_server.c.
References debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, nfi_tcp_server_server::params, tcpClient_param_st::server, tcp_server_write_operation(), and tcpClient_read_data().
Referenced by nfi_tcp_server_close(), nfi_tcp_server_closedir(), nfi_tcp_server_create(), nfi_tcp_server_flush(), nfi_tcp_server_getattr(), nfi_tcp_server_mkdir(), nfi_tcp_server_open(), nfi_tcp_server_opendir(), nfi_tcp_server_preload(), nfi_tcp_server_readdir(), nfi_tcp_server_remove(), nfi_tcp_server_rename(), and nfi_tcp_server_rmdir().
nfi_tcp_server_flush()
int nfi_tcp_server_flush (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
virtual_path 'TODO'.
storage_path 'TODO'.
opt 'TODO'.
Returns
'TODO'.
Definition at line 1890 of file nfi_tcp_server.c.
References st_tcp_server_flush::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_flush, st_tcp_server_flush::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_tcp_server_flush::storage_path, tcp_server_err(), TCP_SERVER_FLUSH_FILE, TCP_SERVER_ID, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, and st_tcp_server_flush::virtual_path.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_getattr()
int nfi_tcp_server_getattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 1384 of file nfi_tcp_server.c.
References st_tcp_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_getattr, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_getattr::path, PATH_MAX, nfi_server::private_info, real_posix_stat, st_tcp_server_attr_req::status, tcp_server_err(), TCP_SERVER_GETATTR_FILE, TCP_SERVER_ID, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, TCP_SERVERtoNFIattr(), st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, and nfi_fhandle::url.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_init()
int nfi_tcp_server_init (char * url, struct nfi_server * serv, __attribute__((__unused__)) struct nfi_attr_server * attr)
Definition at line 252 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, FREE_AND_NULL, MOSQ_OPT_TCP_NODELAY, nfi_tcp_server_server::mqtt, nfi_ops::nfi_close, nfi_ops::nfi_closedir, nfi_ops::nfi_create, nfi_ops::nfi_disconnect, nfi_ops::nfi_flush, nfi_ops::nfi_getattr, nfi_ops::nfi_mkdir, nfi_ops::nfi_open, nfi_ops::nfi_opendir, nfi_ops::nfi_preload, nfi_ops::nfi_read, nfi_ops::nfi_readdir, nfi_ops::nfi_reconnect, nfi_ops::nfi_remove, nfi_ops::nfi_rename, nfi_ops::nfi_rmdir, nfi_ops::nfi_setattr, nfi_ops::nfi_statfs, nfi_tcp_server_close(), nfi_tcp_server_closedir(), nfi_tcp_server_connect(), nfi_tcp_server_create(), nfi_tcp_server_disconnect(), nfi_tcp_server_flush(), nfi_tcp_server_getattr(), nfi_tcp_server_mkdir(), nfi_tcp_server_open(), nfi_tcp_server_opendir(), nfi_tcp_server_preload(), nfi_tcp_server_read(), nfi_tcp_server_readdir(), nfi_tcp_server_reconnect(), nfi_tcp_server_remove(), nfi_tcp_server_rename(), nfi_tcp_server_rmdir(), nfi_tcp_server_setattr(), nfi_tcp_server_statfs(), nfi_tcp_server_write(), nfi_ops::nfi_write, nfiworker_init(), NULL_RET_ERR, nfi_server::ops, nfi_tcp_server_server::params, ParseURL(), PATH_MAX, nfi_server::private_info, nfi_worker::server, tcpClient_param_st::server_name, tcp_server_err(), TCP_SERVERERR_MEMORY, TCP_SERVERERR_URL, tcpClient_comm_init(), tcpClient_comm_locality(), TH_NOT, nfi_server::url, nfi_server::wrk, tcpClient_param_st::xpn_locality, tcpClient_param_st::xpn_mosquitto_mode, tcpClient_param_st::xpn_mosquitto_qos, tcpClient_param_st::xpn_session, nfi_server::xpn_thread, and tcpClient_param_st::xpn_thread.
Referenced by XpnGetServer().
nfi_tcp_server_keepConnected()
int nfi_tcp_server_keepConnected (struct nfi_server * serv)
Definition at line 164 of file nfi_tcp_server.c.
References nfi_tcp_server_reconnect(), and nfi_server::private_info.
Referenced by nfi_tcp_server_close(), nfi_tcp_server_closedir(), nfi_tcp_server_create(), nfi_tcp_server_flush(), nfi_tcp_server_getattr(), nfi_tcp_server_mkdir(), nfi_tcp_server_open(), nfi_tcp_server_opendir(), nfi_tcp_server_preload(), nfi_tcp_server_read(), nfi_tcp_server_readdir(), nfi_tcp_server_remove(), nfi_tcp_server_rename(), nfi_tcp_server_rmdir(), nfi_tcp_server_setattr(), and nfi_tcp_server_write().
nfi_tcp_server_mkdir()
int nfi_tcp_server_mkdir (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 1469 of file nfi_tcp_server.c.
References st_tcp_server_attr_req::attr, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_tcp_server_fhandle::dir, errno, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_tcp_server_msg::op_getattr, st_tcp_server_msg::op_mkdir, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_getattr::path, st_tcp_server_mkdir::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_mkdir, real_posix_stat, nfi_server::server, STRING_MISC_StrDup(), tcp_server_err(), TCP_SERVER_GETATTR_FILE, TCP_SERVER_ID, TCP_SERVER_MKDIR_DIR, TCP_SERVERERR_MEMORY, TCP_SERVERERR_MKDIR, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, TCP_SERVERtoNFIattr(), st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, and nfi_fhandle::url.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_open()
int nfi_tcp_server_open (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 627 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_fhandle::dir, nfi_tcp_server_fhandle::fd, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIFILE, NULL_RET_ERR, O_RDWR, st_tcp_server_msg::op_open, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_open::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_open2, nfi_server::server, nfi_fhandle::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_OPEN_FILE_WOS, TCP_SERVER_OPEN_FILE_WS, TCP_SERVERERR_MEMORY, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_opendir()
int nfi_tcp_server_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 1565 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_tcp_server_fhandle::dir, FREE_AND_NULL, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_tcp_server_msg::op_opendir, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_opendir::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_opendir, nfi_server::server, nfi_fhandle::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_OPENDIR_DIR, TCP_SERVERERR_MEMORY, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, nfi_fhandle::type, st_tcp_server_msg::u_st_tcp_server_msg, and nfi_fhandle::url.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_preload()
int nfi_tcp_server_preload (struct nfi_server * server, char * url, char * virtual_path, char * storage_path, int opt)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
virtual_path 'TODO'.
storage_path 'TODO'.
opt 'TODO'.
Returns
'TODO'.
Definition at line 1842 of file nfi_tcp_server.c.
References st_tcp_server_preload::block_size, nfi_server::block_size, DEBUG_BEGIN, DEBUG_END, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_preload, st_tcp_server_preload::opt, PATH_MAX, nfi_server::private_info, nfi_server::server, st_tcp_server_preload::storage_path, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_PRELOAD_FILE, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, and st_tcp_server_preload::virtual_path.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_read()
ssize_t nfi_tcp_server_read (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 844 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, st_tcp_server_read::fd, nfi_tcp_server_fhandle::fd, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_keepConnected(), NULL_RET_ERR, O_RDONLY, st_tcp_server_read::offset, st_tcp_server_msg::op_read, nfi_tcp_server_server::params, st_tcp_server_read::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_read, tcpClient_param_st::server, st_tcp_server_read::size, st_tcp_server_read_req::size, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_READ_FILE_WOS, TCP_SERVER_READ_FILE_WS, tcp_server_write_operation(), TCP_SERVERERR_PARAM, TCP_SERVERERR_READ, tcpClient_read_data(), st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_readdir()
int nfi_tcp_server_readdir (struct nfi_server * server, struct nfi_fhandle * fhd, struct dirent * entry)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fhd 'TODO'.
entry 'TODO'.
Returns
'TODO'.
Definition at line 1639 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, st_tcp_server_readdir::dir, nfi_tcp_server_fhandle::dir, st_tcp_server_direntry::end, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NFIDIR, NULL_RET_ERR, st_tcp_server_msg::op_readdir, nfi_tcp_server_server::params, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_readdir, st_tcp_server_direntry::ret, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_READDIR_DIR, TCP_SERVERERR_NOTDIR, TCP_SERVERERR_PARAM, st_tcp_server_msg::type, nfi_fhandle::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_reconnect()
int nfi_tcp_server_reconnect (struct nfi_server * server)
Reconnect to the TCP server.
'TODO'.
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 578 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, NULL_RET_ERR, nfi_tcp_server_server::params, ParseURL(), nfi_tcp_server_server::path, PATH_MAX, nfi_server::private_info, tcp_server_err(), TCP_SERVERERR_MEMORY, TCP_SERVERERR_URL, tcpClient_comm_connect(), and nfi_server::url.
Referenced by nfi_tcp_server_init(), and nfi_tcp_server_keepConnected().
nfi_tcp_server_remove()
int nfi_tcp_server_remove (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 1260 of file nfi_tcp_server.c.
References DEBUG_END, debug_error, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_rm, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_rm::path, PATH_MAX, nfi_server::private_info, real_posix_unlink, nfi_server::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_RM_FILE, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_rename()
int nfi_tcp_server_rename (struct nfi_server * server, char * old_url, char * new_url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
old_url 'TODO'.
new_url 'TODO'.
Returns
'TODO'.
Definition at line 1316 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, st_tcp_server_rename::new_url, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_rename::old_url, st_tcp_server_msg::op_rename, nfi_tcp_server_server::params, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_rename, nfi_server::server, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_RENAME_FILE, TCP_SERVERERR_PARAM, TCP_SERVERERR_URL, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_rmdir()
int nfi_tcp_server_rmdir (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 1751 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, nfi_tcp_server_fhandle::dir, tcpClient_param_st::locality, nfi_tcp_server_doRequest(), nfi_tcp_server_keepConnected(), NULL_RET_ERR, st_tcp_server_msg::op_rmdir, nfi_tcp_server_server::params, ParseURL(), st_tcp_server_rmdir::path, PATH_MAX, nfi_server::private_info, real_posix_rmdir, nfi_server::server, tcp_server_err(), TCP_SERVER_RMDIR_DIR, TCP_SERVERERR_PARAM, TCP_SERVERERR_REMOVE, TCP_SERVERERR_URL, st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_setattr()
int nfi_tcp_server_setattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 1442 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, nfi_tcp_server_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, and TCP_SERVERERR_PARAM.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_statfs()
int nfi_tcp_server_statfs (__attribute__((__unused__)) struct nfi_server * serv, __attribute__((__unused__)) struct nfi_info * inf)
Definition at line 1808 of file nfi_tcp_server.c.
References DEBUG_BEGIN, and DEBUG_END.
Referenced by nfi_tcp_server_init().
nfi_tcp_server_write()
ssize_t nfi_tcp_server_write (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 981 of file nfi_tcp_server.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, st_tcp_server_write::fd, nfi_tcp_server_fhandle::fd, nfi_tcp_server_server::id, st_tcp_server_msg::id, tcpClient_param_st::locality, MAX_BUFFER_SIZE, nfi_tcp_server_server::mqtt, nfi_tcp_server_keepConnected(), NULL_RET_ERR, O_WRONLY, st_tcp_server_write::offset, st_tcp_server_msg::op_write, nfi_tcp_server_server::params, st_tcp_server_write::path, nfi_tcp_server_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, real_posix_lseek, real_posix_open, real_posix_write, tcpClient_param_st::server, tcpClient_param_st::server_name, st_tcp_server_write::size, st_tcp_server_write_req::size, tcp_server_err(), TCP_SERVER_ID, TCP_SERVER_WRITE_FILE_WOS, TCP_SERVER_WRITE_FILE_WS, tcp_server_write_operation(), TCP_SERVERERR_PARAM, TCP_SERVERERR_WRITE, tcpClient_read_data(), tcpClient_write_data(), st_tcp_server_msg::type, st_tcp_server_msg::u_st_tcp_server_msg, nfi_fhandle::url, tcpClient_param_st::xpn_mosquitto_mode, tcpClient_param_st::xpn_mosquitto_qos, and tcpClient_param_st::xpn_session.
Referenced by nfi_tcp_server_init().
NFItoTCP_SERVERattr()
void NFItoTCP_SERVERattr (struct stat * att, struct nfi_attr * nfi_att)
Definition at line 191 of file nfi_tcp_server.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, NFIFILE, nfi_attr::st_dev, and nfi_attr::st_ino.
tcp_server_write_operation()
int tcp_server_write_operation (int sd, struct st_tcp_server_msg * head)
Definition at line 50 of file nfi_tcp_server.c.
References debug_info, debug_warning, st_tcp_server_msg::id, st_tcp_server_msg::op_close, st_tcp_server_msg::op_closedir, st_tcp_server_msg::op_creat, st_tcp_server_msg::op_flush, st_tcp_server_msg::op_getattr, st_tcp_server_msg::op_mkdir, st_tcp_server_msg::op_open, st_tcp_server_msg::op_opendir, st_tcp_server_msg::op_preload, st_tcp_server_msg::op_read, st_tcp_server_msg::op_readdir, st_tcp_server_msg::op_rename, st_tcp_server_msg::op_rm, st_tcp_server_msg::op_rmdir, st_tcp_server_msg::op_write, TCP_SERVER_CLOSE_FILE_WS, TCP_SERVER_CLOSEDIR_DIR, TCP_SERVER_CREAT_FILE_WOS, TCP_SERVER_CREAT_FILE_WS, TCP_SERVER_FLUSH_FILE, TCP_SERVER_GETATTR_FILE, TCP_SERVER_MKDIR_DIR, TCP_SERVER_OPEN_FILE_WOS, TCP_SERVER_OPEN_FILE_WS, TCP_SERVER_OPENDIR_DIR, TCP_SERVER_PRELOAD_FILE, TCP_SERVER_READ_FILE_WOS, TCP_SERVER_READ_FILE_WS, TCP_SERVER_READDIR_DIR, TCP_SERVER_RENAME_FILE, TCP_SERVER_RM_FILE, TCP_SERVER_RMDIR_DIR, TCP_SERVER_WRITE_FILE_WOS, TCP_SERVER_WRITE_FILE_WS, tcpClient_write_data(), tcpClient_write_operation(), st_tcp_server_msg::type, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by nfi_tcp_server_doRequest(), nfi_tcp_server_read(), and nfi_tcp_server_write().
TCP_SERVERtoNFIattr()
void TCP_SERVERtoNFIattr (struct nfi_attr * nfi_att, struct stat * att)
Definition at line 217 of file nfi_tcp_server.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, NFIFILE, nfi_attr::st_dev, and nfi_attr::st_ino.
Referenced by nfi_tcp_server_create(), nfi_tcp_server_getattr(), and nfi_tcp_server_mkdir().
TCP_SERVERtoNFIInfo()
void TCP_SERVERtoNFIInfo (__attribute__((__unused__)) struct nfi_info * nfi_inf, __attribute__((__unused__)) struct nfi_info * tcp_server_inf)
Definition at line 243 of file nfi_tcp_server.c.