nfi_local.c File Reference
File to 'TODO'.
#include nfi_local.h
Macros
#define FILESYSTEM_DLSYM 1
Functions
int nfi_local_keepConnected (struct nfi_server *serv)
'TODO'.
void NFItoLOCALattr (struct stat *att, struct nfi_attr *nfi_att)
'TODO'.
void LOCALtoNFIattr (struct nfi_attr *nfi_att, struct stat *att)
'TODO'.
void LOCALtoNFIInfo (__attribute__((__unused__)) struct nfi_info *nfi_inf, __attribute__((__unused__)) struct nfi_info *local_inf)
'TODO'.
int nfi_local_init (char *url, struct nfi_server *serv, __attribute__((__unused__)) struct nfi_attr_server *attr)
int nfi_local_destroy (struct nfi_server *serv)
'TODO'.
int nfi_local_connect (struct nfi_server *serv, __attribute__((__unused__)) char *url, __attribute__((__unused__)) char *prt, __attribute__((__unused__)) char *server, __attribute__((__unused__)) char *dir)
int nfi_local_disconnect (struct nfi_server *serv)
Disconnect to the server.
int nfi_local_reconnect (struct nfi_server *serv)
Reconnect to the LOCAL server.
int nfi_local_open (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_local_create (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
ssize_t nfi_local_read (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
ssize_t nfi_local_write (struct nfi_server *serv, struct nfi_fhandle *fh, void *buffer, off_t offset, size_t size)
'TODO'.
int nfi_local_close (struct nfi_server *serv, struct nfi_fhandle *fh)
'TODO'.
int nfi_local_remove (struct nfi_server *serv, char *url)
'TODO'.
int nfi_local_rename (struct nfi_server *serv, char *old_url, char *new_url)
'TODO'.
int nfi_local_getattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_local_setattr (struct nfi_server *serv, struct nfi_fhandle *fh, struct nfi_attr *attr)
'TODO'.
int nfi_local_mkdir (struct nfi_server *serv, char *url, struct nfi_attr *attr, struct nfi_fhandle *fh)
'TODO'.
int nfi_local_opendir (struct nfi_server *serv, char *url, struct nfi_fhandle *fho)
'TODO'.
int nfi_local_readdir (struct nfi_server *serv, struct nfi_fhandle *fh, struct dirent *entry)
'TODO'.
int nfi_local_closedir (struct nfi_server *serv, struct nfi_fhandle *fh)
'TODO'.
int nfi_local_rmdir (struct nfi_server *serv, char *url)
'TODO'.
int nfi_local_statfs (__attribute__((__unused__)) struct nfi_server *serv, __attribute__((__unused__)) struct nfi_info *inf)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfi_local.c.
Macro Definition Documentation
FILESYSTEM_DLSYM
#define FILESYSTEM_DLSYM 1
Definition at line 40 of file nfi_local.c.
Function Documentation
LOCALtoNFIattr()
void LOCALtoNFIattr (struct nfi_attr * nfi_att, struct stat * att)
'TODO'.
'TODO'.
Parameters
nfi_att 'TODO'.
att 'TODO'.
Returns
Nothing.
Definition at line 130 of file nfi_local.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, NFIFILE, nfi_attr::st_dev, and nfi_attr::st_ino.
Referenced by nfi_local_create(), nfi_local_getattr(), and nfi_local_mkdir().
LOCALtoNFIInfo()
void LOCALtoNFIInfo (__attribute__((__unused__)) struct nfi_info * nfi_inf, __attribute__((__unused__)) struct nfi_info * local_inf)
'TODO'.
'TODO'.
Parameters
nfi_inf 'TODO'.
local_inf 'TODO'.
Returns
Nothing.
Definition at line 166 of file nfi_local.c.
nfi_local_close()
int nfi_local_close (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 635 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, nfi_local_fhandle::fd, FREE_AND_NULL, LOCALERR_PARAM, nfi_local_keepConnected(), NFINULL, NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_close, nfi_fhandle::server, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_closedir()
int nfi_local_closedir (struct nfi_server * server, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 975 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, nfi_local_fhandle::dir, FREE_AND_NULL, LOCALERR_PARAM, nfi_local_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_closedir, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_connect()
int nfi_local_connect (struct nfi_server * serv, __attribute__((__unused__)) char * url, __attribute__((__unused__)) char * prt, __attribute__((__unused__)) char * server, __attribute__((__unused__)) char * dir)
Definition at line 341 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, and nfi_server::private_info.
Referenced by nfi_local_init().
nfi_local_create()
int nfi_local_create (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 500 of file nfi_local.c.
References nfi_attr::at_mode, DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, nfi_local_fhandle::fd, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, LOCALtoNFIattr(), nfi_local_keepConnected(), NFIFILE, NULL_RET_ERR, O_CREAT, O_RDWR, O_TRUNC, ParseURL(), nfi_local_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_open2, real_posix_stat, nfi_server::server, nfi_fhandle::server, st, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_destroy()
int nfi_local_destroy (struct nfi_server * serv)
'TODO'.
'TODO'.
Parameters
serv 'TODO'.
Returns
'TODO'.
Definition at line 304 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, FREE_AND_NULL, nfiworker_destroy(), nfi_server::ops, nfi_server::private_info, nfi_server::server, and nfi_server::url.
nfi_local_disconnect()
int nfi_local_disconnect (struct nfi_server * server)
Disconnect to the server.
'TODO'
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 367 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, FREE_AND_NULL, and nfi_server::private_info.
Referenced by nfi_local_init().
nfi_local_getattr()
int nfi_local_getattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 748 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, LOCALERR_PARAM, LOCALtoNFIattr(), nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_stat, st, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_init()
int nfi_local_init (char * url, struct nfi_server * serv, __attribute__((__unused__)) struct nfi_attr_server * attr)
Definition at line 178 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, FREE_AND_NULL, LOCALERR_MEMORY, nfi_ops::nfi_close, nfi_ops::nfi_closedir, nfi_ops::nfi_create, nfi_ops::nfi_disconnect, nfi_ops::nfi_getattr, nfi_local_close(), nfi_local_closedir(), nfi_local_connect(), nfi_local_create(), nfi_local_disconnect(), nfi_local_getattr(), nfi_local_mkdir(), nfi_local_open(), nfi_local_opendir(), nfi_local_read(), nfi_local_readdir(), nfi_local_reconnect(), nfi_local_remove(), nfi_local_rename(), nfi_local_rmdir(), nfi_local_setattr(), nfi_local_statfs(), nfi_local_write(), nfi_ops::nfi_mkdir, nfi_ops::nfi_open, nfi_ops::nfi_opendir, nfi_ops::nfi_read, nfi_ops::nfi_readdir, nfi_ops::nfi_reconnect, nfi_ops::nfi_remove, nfi_ops::nfi_rename, nfi_ops::nfi_rmdir, nfi_ops::nfi_setattr, nfi_ops::nfi_statfs, nfi_ops::nfi_write, nfiworker_init(), NULL_RET_ERR, nfi_server::ops, ParseURL(), nfi_local_server::path, PATH_MAX, nfi_server::private_info, nfi_server::server, nfi_worker::server, STRING_MISC_StrDup(), TH_NOT, nfi_server::url, nfi_server::wrk, and nfi_server::xpn_thread.
Referenced by XpnGetServer().
nfi_local_keepConnected()
int nfi_local_keepConnected (struct nfi_server * serv)
'TODO'.
'TODO'.
Parameters
serv 'TODO'.
Returns
'TODO'.
Definition at line 57 of file nfi_local.c.
References nfi_local_reconnect(), and nfi_server::private_info.
Referenced by nfi_local_close(), nfi_local_closedir(), nfi_local_create(), nfi_local_getattr(), nfi_local_mkdir(), nfi_local_open(), nfi_local_opendir(), nfi_local_read(), nfi_local_readdir(), nfi_local_remove(), nfi_local_rename(), nfi_local_rmdir(), nfi_local_setattr(), and nfi_local_write().
nfi_local_mkdir()
int nfi_local_mkdir (struct nfi_server * server, char * url, struct nfi_attr * attr, struct nfi_fhandle * fh)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
attr 'TODO'.
fh 'TODO'.
Returns
'TODO'.
Definition at line 815 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, errno, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, LOCALtoNFIattr(), nfi_local_keepConnected(), NFIDIR, NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_mkdir, real_posix_stat, st, STRING_MISC_StrDup(), nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_open()
int nfi_local_open (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 444 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, nfi_local_fhandle::fd, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NFIFILE, NULL_RET_ERR, O_RDWR, ParseURL(), nfi_local_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_open2, nfi_server::server, nfi_fhandle::server, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_opendir()
int nfi_local_opendir (struct nfi_server * server, char * url, struct nfi_fhandle * fho)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
fho 'TODO'.
Returns
'TODO'.
Definition at line 880 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, FREE_AND_NULL, local_err(), LOCALERR_MEMORY, LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NFIDIR, NULL_RET_ERR, ParseURL(), nfi_local_fhandle::path, PATH_MAX, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_opendir, nfi_server::server, nfi_fhandle::server, nfi_fhandle::type, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_read()
ssize_t nfi_local_read (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 568 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, nfi_local_fhandle::fd, LOCALERR_PARAM, nfi_local_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_lseek, real_posix_read, and nfi_fhandle::url.
Referenced by nfi_local_init().
nfi_local_readdir()
int nfi_local_readdir (struct nfi_server * server, struct nfi_fhandle * fhd, struct dirent * entry)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fhd 'TODO'.
entry 'TODO'.
Returns
'TODO'.
Definition at line 936 of file nfi_local.c.
References DEBUG_BEGIN, debug_error, nfi_local_fhandle::dir, local_err(), LOCALERR_NOTDIR, LOCALERR_PARAM, nfi_local_keepConnected(), NFIDIR, NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_readdir, and nfi_fhandle::type.
Referenced by nfi_local_init().
nfi_local_reconnect()
int nfi_local_reconnect (struct nfi_server * server)
Reconnect to the LOCAL server.
'TODO'
Parameters
server 'TODO'.
Returns
'TODO'.
Definition at line 396 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, ParseURL(), nfi_local_server::path, PATH_MAX, nfi_server::private_info, and nfi_server::url.
Referenced by nfi_local_init(), and nfi_local_keepConnected().
nfi_local_remove()
int nfi_local_remove (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 668 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, local_err(), LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_unlink, and nfi_server::server.
Referenced by nfi_local_init().
nfi_local_rename()
int nfi_local_rename (struct nfi_server * server, char * old_url, char * new_url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
old_url 'TODO'.
new_url 'TODO'.
Returns
'TODO'.
Definition at line 704 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, local_err(), LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, real_posix_rename, and nfi_server::server.
Referenced by nfi_local_init().
nfi_local_rmdir()
int nfi_local_rmdir (struct nfi_server * server, char * url)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
url 'TODO'.
Returns
'TODO'.
Definition at line 1004 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, nfi_local_fhandle::dir, local_err(), LOCALERR_PARAM, LOCALERR_URL, nfi_local_keepConnected(), NULL_RET_ERR, ParseURL(), PATH_MAX, nfi_server::private_info, and real_posix_rmdir.
Referenced by nfi_local_init().
nfi_local_setattr()
int nfi_local_setattr (struct nfi_server * server, struct nfi_fhandle * fh, struct nfi_attr * attr)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
attr 'TODO'.
Returns
'TODO'.
Definition at line 791 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, LOCALERR_PARAM, nfi_local_keepConnected(), NFItoLOCALattr(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, and st.
Referenced by nfi_local_init().
nfi_local_statfs()
int nfi_local_statfs (__attribute__((__unused__)) struct nfi_server * serv, __attribute__((__unused__)) struct nfi_info * inf)
Definition at line 1040 of file nfi_local.c.
References DEBUG_BEGIN, and DEBUG_END.
Referenced by nfi_local_init().
nfi_local_write()
ssize_t nfi_local_write (struct nfi_server * server, struct nfi_fhandle * fh, void * buffer, off_t offset, size_t size)
'TODO'.
'TODO'.
Parameters
server 'TODO'.
fh 'TODO'.
buffer 'TODO'.
offset 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 599 of file nfi_local.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, errno, nfi_local_fhandle::fd, LOCALERR_PARAM, nfi_local_keepConnected(), NULL_RET_ERR, nfi_fhandle::priv_fh, nfi_server::private_info, real_posix_lseek, real_posix_write, and nfi_fhandle::url.
Referenced by nfi_local_init().
NFItoLOCALattr()
void NFItoLOCALattr (struct stat * att, struct nfi_attr * nfi_att)
'TODO'.
'TODO'.
Parameters
att 'TODO'.
nfi_att 'TODO'.
Returns
Nothing.
Definition at line 94 of file nfi_local.c.
References nfi_attr::at_atime, nfi_attr::at_blksize, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_gid, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, nfi_attr::at_type, nfi_attr::at_uid, NFIDIR, NFIFILE, nfi_attr::st_dev, and nfi_attr::st_ino.
Referenced by nfi_local_setattr().