nfs3_xdr.c File Reference
#include nfi/nfi_nfs3/nfs3.h
Functions
bool_t xdr_uint64 (XDR *xdrs, uint64 *objp)
bool_t xdr_int64 (XDR *xdrs, int64 *objp)
bool_t xdr_uint32 (XDR *xdrs, uint32 *objp)
bool_t xdr_int32 (XDR *xdrs, int32 *objp)
bool_t xdr_filename3 (XDR *xdrs, filename3 *objp)
bool_t xdr_nfspath3 (XDR *xdrs, nfspath3 *objp)
bool_t xdr_cookieverf3 (XDR *xdrs, cookieverf3 objp)
bool_t xdr_createverf3 (XDR *xdrs, createverf3 objp)
bool_t xdr_writeverf3 (XDR *xdrs, writeverf3 objp)
bool_t xdr_fhandle3 (XDR *xdrs, fhandle3 *objp)
bool_t xdr_mountstat3 (XDR *xdrs, mountstat3 *objp)
bool_t xdr_mountres3_ok (XDR *xdrs, mountres3_ok *objp)
bool_t xdr_mountres3 (XDR *xdrs, mountres3 *objp)
bool_t xdr_mountlist3 (XDR *xdrs, mountlist3 *objp)
bool_t xdr_mountbody3 (XDR *xdrs, mountbody3 *objp)
bool_t xdr_groups3 (XDR *xdrs, groups3 *objp)
bool_t xdr_groupnode3 (XDR *xdrs, groupnode3 *objp)
bool_t xdr_exports3 (XDR *xdrs, exports3 *objp)
bool_t xdr_exportnode3 (XDR *xdrs, exportnode3 *objp)
bool_t xdr_nfsstat3 (XDR *xdrs, nfsstat3 *objp)
bool_t xdr_ftype3 (XDR *xdrs, ftype3 *objp)
bool_t xdr_specdata3 (XDR *xdrs, specdata3 *objp)
bool_t xdr_nfstime3 (XDR *xdrs, nfstime3 *objp)
bool_t xdr_fattr3 (XDR *xdrs, fattr3 *objp)
bool_t xdr_post_op_attr (XDR *xdrs, post_op_attr *objp)
bool_t xdr_wcc_attr (XDR *xdrs, wcc_attr *objp)
bool_t xdr_pre_op_attr (XDR *xdrs, pre_op_attr *objp)
bool_t xdr_wcc_data (XDR *xdrs, wcc_data *objp)
bool_t xdr_post_op_fh3 (XDR *xdrs, post_op_fh3 *objp)
bool_t xdr_set_uint32 (XDR *xdrs, set_uint32 *objp)
bool_t xdr_set_uint64 (XDR *xdrs, set_uint64 *objp)
bool_t xdr_time_how (XDR *xdrs, time_how *objp)
bool_t xdr_set_time (XDR *xdrs, set_time *objp)
bool_t xdr_sattr3 (XDR *xdrs, sattr3 *objp)
bool_t xdr_diropargs3 (XDR *xdrs, diropargs3 *objp)
bool_t xdr_diropres3ok (XDR *xdrs, diropres3ok *objp)
bool_t xdr_diropres3 (XDR *xdrs, diropres3 *objp)
bool_t xdr_wccstat3 (XDR *xdrs, wccstat3 *objp)
bool_t xdr_getattr3res (XDR *xdrs, getattr3res *objp)
bool_t xdr_sattrguard3 (XDR *xdrs, sattrguard3 *objp)
bool_t xdr_setattr3args (XDR *xdrs, setattr3args *objp)
bool_t xdr_lookup3resok (XDR *xdrs, lookup3resok *objp)
bool_t xdr_lookup3res (XDR *xdrs, lookup3res *objp)
bool_t xdr_access3args (XDR *xdrs, access3args *objp)
bool_t xdr_access3resok (XDR *xdrs, access3resok *objp)
bool_t xdr_access3res (XDR *xdrs, access3res *objp)
bool_t xdr_readlink3resok (XDR *xdrs, readlink3resok *objp)
bool_t xdr_readlink3res (XDR *xdrs, readlink3res *objp)
bool_t xdr_read3args (XDR *xdrs, read3args *objp)
bool_t xdr_read3resok (XDR *xdrs, read3resok *objp)
bool_t xdr_read3res (XDR *xdrs, read3res *objp)
bool_t xdr_stable_how (XDR *xdrs, stable_how *objp)
bool_t xdr_write3args (XDR *xdrs, write3args *objp)
bool_t xdr_write3resok (XDR *xdrs, write3resok *objp)
bool_t xdr_write3res (XDR *xdrs, write3res *objp)
bool_t xdr_createmode3 (XDR *xdrs, createmode3 *objp)
bool_t xdr_createhow3 (XDR *xdrs, createhow3 *objp)
bool_t xdr_create3args (XDR *xdrs, create3args *objp)
bool_t xdr_mkdir3args (XDR *xdrs, mkdir3args *objp)
bool_t xdr_symlinkdata3 (XDR *xdrs, symlinkdata3 *objp)
bool_t xdr_symlink3args (XDR *xdrs, symlink3args *objp)
bool_t xdr_devicedata3 (XDR *xdrs, devicedata3 *objp)
bool_t xdr_mknoddata3 (XDR *xdrs, mknoddata3 *objp)
bool_t xdr_mknod3args (XDR *xdrs, mknod3args *objp)
bool_t xdr_rename3args (XDR *xdrs, rename3args *objp)
bool_t xdr_rename3wcc (XDR *xdrs, rename3wcc *objp)
bool_t xdr_rename3res (XDR *xdrs, rename3res *objp)
bool_t xdr_link3args (XDR *xdrs, link3args *objp)
bool_t xdr_link3wcc (XDR *xdrs, link3wcc *objp)
bool_t xdr_link3res (XDR *xdrs, link3res *objp)
bool_t xdr_readdir3args (XDR *xdrs, readdir3args *objp)
bool_t xdr_entry3 (XDR *xdrs, entry3 *objp)
bool_t xdr_dirlist3 (XDR *xdrs, dirlist3 *objp)
bool_t xdr_readdir3resok (XDR *xdrs, readdir3resok *objp)
bool_t xdr_readdir3res (XDR *xdrs, readdir3res *objp)
bool_t xdr_readdirplus3args (XDR *xdrs, readdirplus3args *objp)
bool_t xdr_entryplus3 (XDR *xdrs, entryplus3 *objp)
bool_t xdr_dirlistplus3 (XDR *xdrs, dirlistplus3 *objp)
bool_t xdr_readdirplus3resok (XDR *xdrs, readdirplus3resok *objp)
bool_t xdr_readdirplus3res (XDR *xdrs, readdirplus3res *objp)
bool_t xdr_fsstat3resok (XDR *xdrs, fsstat3resok *objp)
bool_t xdr_fsstat3res (XDR *xdrs, fsstat3res *objp)
bool_t xdr_fsinfo3resok (XDR *xdrs, fsinfo3resok *objp)
bool_t xdr_fsinfo3res (XDR *xdrs, fsinfo3res *objp)
bool_t xdr_pathconf3resok (XDR *xdrs, pathconf3resok *objp)
bool_t xdr_pathconf3res (XDR *xdrs, pathconf3res *objp)
bool_t xdr_commit3args (XDR *xdrs, commit3args *objp)
bool_t xdr_commit3resok (XDR *xdrs, commit3resok *objp)
bool_t xdr_commit3res (XDR *xdrs, commit3res *objp)
Function Documentation
xdr_access3args()
bool_t xdr_access3args (XDR * xdrs, access3args * objp)
Definition at line 618 of file nfs3_xdr.c.
References access3args::access, FALSE, access3args::object, TRUE, xdr_fhandle3(), and xdr_uint32().
xdr_access3res()
bool_t xdr_access3res (XDR * xdrs, access3res * objp)
Definition at line 642 of file nfs3_xdr.c.
References access3res::access3res_u, FALSE, NFS3_OK, access3res::resfail, access3res::resok, access3res::status, TRUE, xdr_access3resok(), xdr_nfsstat3(), and xdr_post_op_attr().
xdr_access3resok()
bool_t xdr_access3resok (XDR * xdrs, access3resok * objp)
Definition at line 630 of file nfs3_xdr.c.
References access3resok::access, FALSE, access3resok::obj_attributes, TRUE, xdr_post_op_attr(), and xdr_uint32().
xdr_commit3args()
bool_t xdr_commit3args (XDR * xdrs, commit3args * objp)
Definition at line 1370 of file nfs3_xdr.c.
References commit3args::count, FALSE, commit3args::file, commit3args::offset, TRUE, xdr_fhandle3(), xdr_uint32(), and xdr_uint64().
xdr_commit3res()
bool_t xdr_commit3res (XDR * xdrs, commit3res * objp)
Definition at line 1396 of file nfs3_xdr.c.
References commit3res::commit3res_u, FALSE, NFS3_OK, commit3res::resfail, commit3res::resok, commit3res::status, TRUE, xdr_commit3resok(), xdr_nfsstat3(), and xdr_wcc_data().
xdr_commit3resok()
bool_t xdr_commit3resok (XDR * xdrs, commit3resok * objp)
Definition at line 1384 of file nfs3_xdr.c.
References FALSE, commit3resok::file_wcc, TRUE, commit3resok::verf, xdr_wcc_data(), and xdr_writeverf3().
xdr_cookieverf3()
bool_t xdr_cookieverf3 (XDR * xdrs, cookieverf3 objp)
Definition at line 69 of file nfs3_xdr.c.
References FALSE, NFS3_COOKIEVERFSIZE, and TRUE.
xdr_create3args()
bool_t xdr_create3args (XDR * xdrs, create3args * objp)
Definition at line 841 of file nfs3_xdr.c.
References FALSE, create3args::how, TRUE, create3args::where, xdr_createhow3(), and xdr_diropargs3().
xdr_createhow3()
bool_t xdr_createhow3 (XDR * xdrs, createhow3 * objp)
Definition at line 818 of file nfs3_xdr.c.
References createhow3::createhow3_u, EXCLUSIVE, FALSE, GUARDED, createhow3::mode, createhow3::obj_attributes, TRUE, UNCHECKED, createhow3::verf, xdr_createmode3(), xdr_createverf3(), and xdr_sattr3().
xdr_createmode3()
bool_t xdr_createmode3 (XDR * xdrs, createmode3 * objp)
Definition at line 808 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_createverf3()
bool_t xdr_createverf3 (XDR * xdrs, createverf3 objp)
Definition at line 79 of file nfs3_xdr.c.
References FALSE, NFS3_CREATEVERFSIZE, and TRUE.
xdr_devicedata3()
bool_t xdr_devicedata3 (XDR * xdrs, devicedata3 * objp)
Definition at line 889 of file nfs3_xdr.c.
References devicedata3::dev_attributes, FALSE, devicedata3::spec, TRUE, xdr_sattr3(), and xdr_specdata3().
xdr_dirlist3()
bool_t xdr_dirlist3 (XDR * xdrs, dirlist3 * objp)
Definition at line 1053 of file nfs3_xdr.c.
References dirlist3::entries, dirlist3::eof, FALSE, TRUE, and xdr_entry3().
xdr_dirlistplus3()
bool_t xdr_dirlistplus3 (XDR * xdrs, dirlistplus3 * objp)
Definition at line 1137 of file nfs3_xdr.c.
References dirlistplus3::entries, dirlistplus3::eof, FALSE, TRUE, and xdr_entryplus3().
xdr_diropargs3()
bool_t xdr_diropargs3 (XDR * xdrs, diropargs3 * objp)
Definition at line 468 of file nfs3_xdr.c.
References diropargs3::dir, FALSE, diropargs3::name, TRUE, xdr_fhandle3(), and xdr_filename3().
xdr_diropres3()
bool_t xdr_diropres3 (XDR * xdrs, diropres3 * objp)
Definition at line 494 of file nfs3_xdr.c.
References diropres3::diropres3_u, FALSE, NFS3_OK, diropres3::resfail, diropres3::resok, diropres3::status, TRUE, xdr_diropres3ok(), xdr_nfsstat3(), and xdr_wcc_data().
xdr_diropres3ok()
bool_t xdr_diropres3ok (XDR * xdrs, diropres3ok * objp)
Definition at line 480 of file nfs3_xdr.c.
References diropres3ok::dir_wcc, FALSE, diropres3ok::obj, diropres3ok::obj_attributes, TRUE, xdr_post_op_attr(), xdr_post_op_fh3(), and xdr_wcc_data().
xdr_entry3()
bool_t xdr_entry3 (XDR * xdrs, entry3 * objp)
Definition at line 1037 of file nfs3_xdr.c.
References entry3::cookie, FALSE, entry3::fileid, entry3::name, entry3::nextentry, TRUE, xdr_entry3(), xdr_filename3(), and xdr_uint64().
xdr_entryplus3()
bool_t xdr_entryplus3 (XDR * xdrs, entryplus3 * objp)
Definition at line 1117 of file nfs3_xdr.c.
References entryplus3::cookie, FALSE, entryplus3::fileid, entryplus3::name, entryplus3::name_attributes, entryplus3::name_handle, entryplus3::nextentry, TRUE, xdr_entryplus3(), xdr_filename3(), xdr_post_op_attr(), xdr_post_op_fh3(), and xdr_uint64().
xdr_exportnode3()
bool_t xdr_exportnode3 (XDR * xdrs, exportnode3 * objp)
Definition at line 206 of file nfs3_xdr.c.
References exportnode3::ex_dir, exportnode3::ex_groups3, exportnode3::ex_next, FALSE, TRUE, xdr_exports3(), xdr_groups3(), and xdr_nfspath3().
xdr_exports3()
bool_t xdr_exports3 (XDR * xdrs, exports3 * objp)
Definition at line 196 of file nfs3_xdr.c.
References FALSE, TRUE, and xdr_exportnode3().
xdr_fattr3()
bool_t xdr_fattr3 (XDR * xdrs, fattr3 * objp)
Definition at line 264 of file nfs3_xdr.c.
References fattr3::atime, fattr3::ctime, FALSE, fattr3::fileid, fattr3::fsid, fattr3::gid, fattr3::mode, fattr3::mtime, fattr3::nlink, fattr3::rdev, fattr3::size, TRUE, fattr3::type, fattr3::uid, fattr3::used, xdr_ftype3(), xdr_nfstime3(), xdr_specdata3(), xdr_uint32(), and xdr_uint64().
xdr_fhandle3()
bool_t xdr_fhandle3 (XDR * xdrs, fhandle3 * objp)
Definition at line 99 of file nfs3_xdr.c.
References FALSE, fhandle3::fhandle3_len, fhandle3::fhandle3_val, NFS3_FHSIZE, and TRUE.
xdr_filename3()
bool_t xdr_filename3 (XDR * xdrs, filename3 * objp)
Definition at line 49 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_fsinfo3res()
bool_t xdr_fsinfo3res (XDR * xdrs, fsinfo3res * objp)
Definition at line 1257 of file nfs3_xdr.c.
References FALSE, fsinfo3res::fsinfo3res_u, NFS3_OK, fsinfo3res::resfail, fsinfo3res::resok, fsinfo3res::status, TRUE, xdr_fsinfo3resok(), xdr_nfsstat3(), and xdr_post_op_attr().
xdr_fsinfo3resok()
bool_t xdr_fsinfo3resok (XDR * xdrs, fsinfo3resok * objp)
Definition at line 1227 of file nfs3_xdr.c.
References fsinfo3resok::dtpref, FALSE, fsinfo3resok::maxfilesize, fsinfo3resok::obj_attributes, fsinfo3resok::properties, fsinfo3resok::rtmax, fsinfo3resok::rtmult, fsinfo3resok::rtpref, fsinfo3resok::time_delta, TRUE, fsinfo3resok::wtmax, fsinfo3resok::wtmult, fsinfo3resok::wtpref, xdr_nfstime3(), xdr_post_op_attr(), xdr_uint32(), and xdr_uint64().
xdr_fsstat3res()
bool_t xdr_fsstat3res (XDR * xdrs, fsstat3res * objp)
Definition at line 1207 of file nfs3_xdr.c.
References FALSE, fsstat3res::fsstat3res_u, NFS3_OK, fsstat3res::resfail, fsstat3res::resok, fsstat3res::status, TRUE, xdr_fsstat3resok(), xdr_nfsstat3(), and xdr_post_op_attr().
xdr_fsstat3resok()
bool_t xdr_fsstat3resok (XDR * xdrs, fsstat3resok * objp)
Definition at line 1183 of file nfs3_xdr.c.
References fsstat3resok::abytes, fsstat3resok::afiles, FALSE, fsstat3resok::fbytes, fsstat3resok::ffiles, fsstat3resok::invarsec, fsstat3resok::obj_attributes, fsstat3resok::tbytes, fsstat3resok::tfiles, TRUE, xdr_post_op_attr(), xdr_uint32(), and xdr_uint64().
xdr_ftype3()
bool_t xdr_ftype3 (XDR * xdrs, ftype3 * objp)
Definition at line 230 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_getattr3res()
bool_t xdr_getattr3res (XDR * xdrs, getattr3res * objp)
Definition at line 532 of file nfs3_xdr.c.
References getattr3res::attributes, FALSE, getattr3res::getattr3res_u, NFS3_OK, getattr3res::status, TRUE, xdr_fattr3(), and xdr_nfsstat3().
xdr_groupnode3()
bool_t xdr_groupnode3 (XDR * xdrs, groupnode3 * objp)
Definition at line 184 of file nfs3_xdr.c.
References FALSE, groupnode3::gr_name, groupnode3::gr_next, TRUE, xdr_filename3(), and xdr_groups3().
xdr_groups3()
bool_t xdr_groups3 (XDR * xdrs, groups3 * objp)
Definition at line 174 of file nfs3_xdr.c.
References FALSE, TRUE, and xdr_groupnode3().
xdr_int32()
bool_t xdr_int32 (XDR * xdrs, int32 * objp)
Definition at line 39 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_int64()
bool_t xdr_int64 (XDR * xdrs, int64 * objp)
Definition at line 19 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_link3args()
bool_t xdr_link3args (XDR * xdrs, link3args * objp)
Definition at line 979 of file nfs3_xdr.c.
References FALSE, link3args::file, link3args::link, TRUE, xdr_diropargs3(), and xdr_fhandle3().
xdr_link3res()
bool_t xdr_link3res (XDR * xdrs, link3res * objp)
Definition at line 1003 of file nfs3_xdr.c.
References FALSE, link3res::link3res_u, link3res::res, link3res::status, TRUE, xdr_link3wcc(), and xdr_nfsstat3().
xdr_link3wcc()
bool_t xdr_link3wcc (XDR * xdrs, link3wcc * objp)
Definition at line 991 of file nfs3_xdr.c.
References FALSE, link3wcc::file_attributes, link3wcc::linkdir_wcc, TRUE, xdr_post_op_attr(), and xdr_wcc_data().
xdr_lookup3res()
bool_t xdr_lookup3res (XDR * xdrs, lookup3res * objp)
Definition at line 598 of file nfs3_xdr.c.
References FALSE, lookup3res::lookup3res_u, NFS3_OK, lookup3res::resfail, lookup3res::resok, lookup3res::status, TRUE, xdr_lookup3resok(), xdr_nfsstat3(), and xdr_post_op_attr().
xdr_lookup3resok()
bool_t xdr_lookup3resok (XDR * xdrs, lookup3resok * objp)
Definition at line 584 of file nfs3_xdr.c.
References lookup3resok::dir_attributes, FALSE, lookup3resok::obj_attributes, lookup3resok::object, TRUE, xdr_fhandle3(), and xdr_post_op_attr().
xdr_mkdir3args()
bool_t xdr_mkdir3args (XDR * xdrs, mkdir3args * objp)
Definition at line 853 of file nfs3_xdr.c.
References mkdir3args::attributes, FALSE, TRUE, mkdir3args::where, xdr_diropargs3(), and xdr_sattr3().
xdr_mknod3args()
bool_t xdr_mknod3args (XDR * xdrs, mknod3args * objp)
Definition at line 925 of file nfs3_xdr.c.
References FALSE, TRUE, mknod3args::what, mknod3args::where, xdr_diropargs3(), and xdr_mknoddata3().
xdr_mknoddata3()
bool_t xdr_mknoddata3 (XDR * xdrs, mknoddata3 * objp)
Definition at line 901 of file nfs3_xdr.c.
References mknoddata3::device, FALSE, mknoddata3::mknoddata3_u, NF3BLK, NF3CHR, NF3FIFO, NF3SOCK, mknoddata3::pipe_attributes, TRUE, mknoddata3::type, xdr_devicedata3(), xdr_ftype3(), and xdr_sattr3().
xdr_mountbody3()
bool_t xdr_mountbody3 (XDR * xdrs, mountbody3 * objp)
Definition at line 160 of file nfs3_xdr.c.
References FALSE, mountbody3::ml_directory, mountbody3::ml_hostname, mountbody3::ml_next, TRUE, xdr_filename3(), xdr_mountlist3(), and xdr_nfspath3().
xdr_mountlist3()
bool_t xdr_mountlist3 (XDR * xdrs, mountlist3 * objp)
Definition at line 150 of file nfs3_xdr.c.
References FALSE, TRUE, and xdr_mountbody3().
xdr_mountres3()
bool_t xdr_mountres3 (XDR * xdrs, mountres3 * objp)
Definition at line 132 of file nfs3_xdr.c.
References FALSE, mountres3::fhs_status, MNT3_OK, mountres3::mountinfo, mountres3::mountres3_u, TRUE, xdr_mountres3_ok(), and xdr_mountstat3().
xdr_mountres3_ok()
bool_t xdr_mountres3_ok (XDR * xdrs, mountres3_ok * objp)
Definition at line 119 of file nfs3_xdr.c.
References mountres3_ok::auth_flavors, mountres3_ok::auth_flavors_len, mountres3_ok::auth_flavors_val, FALSE, mountres3_ok::fhandle, TRUE, and xdr_fhandle3().
xdr_mountstat3()
bool_t xdr_mountstat3 (XDR * xdrs, mountstat3 * objp)
Definition at line 109 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_nfspath3()
bool_t xdr_nfspath3 (XDR * xdrs, nfspath3 * objp)
Definition at line 59 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_nfsstat3()
bool_t xdr_nfsstat3 (XDR * xdrs, nfsstat3 * objp)
Definition at line 220 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_nfstime3()
bool_t xdr_nfstime3 (XDR * xdrs, nfstime3 * objp)
Definition at line 252 of file nfs3_xdr.c.
References FALSE, nfstime3::nseconds, nfstime3::seconds, TRUE, and xdr_uint32().
xdr_pathconf3res()
bool_t xdr_pathconf3res (XDR * xdrs, pathconf3res * objp)
Definition at line 1350 of file nfs3_xdr.c.
References FALSE, NFS3_OK, pathconf3res::pathconf3res_u, pathconf3res::resfail, pathconf3res::resok, pathconf3res::status, TRUE, xdr_nfsstat3(), xdr_pathconf3resok(), and xdr_post_op_attr().
xdr_pathconf3resok()
bool_t xdr_pathconf3resok (XDR * xdrs, pathconf3resok * objp)
Definition at line 1277 of file nfs3_xdr.c.
References buf, pathconf3resok::case_insensitive, pathconf3resok::case_preserving, pathconf3resok::chown_restricted, FALSE, pathconf3resok::linkmax, pathconf3resok::name_max, pathconf3resok::no_trunc, pathconf3resok::obj_attributes, TRUE, xdr_post_op_attr(), and xdr_uint32().
xdr_post_op_attr()
bool_t xdr_post_op_attr (XDR * xdrs, post_op_attr * objp)
Definition at line 298 of file nfs3_xdr.c.
References post_op_attr::attributes, FALSE, post_op_attr::post_op_attr_u, post_op_attr::present, TRUE, and xdr_fattr3().
xdr_post_op_fh3()
bool_t xdr_post_op_fh3 (XDR * xdrs, post_op_fh3 * objp)
Definition at line 364 of file nfs3_xdr.c.
References FALSE, post_op_fh3::handle, post_op_fh3::post_op_fh3_u, post_op_fh3::present, TRUE, and xdr_fhandle3().
xdr_pre_op_attr()
bool_t xdr_pre_op_attr (XDR * xdrs, pre_op_attr * objp)
Definition at line 332 of file nfs3_xdr.c.
References pre_op_attr::attributes, FALSE, pre_op_attr::pre_op_attr_u, pre_op_attr::present, TRUE, and xdr_wcc_attr().
xdr_read3args()
bool_t xdr_read3args (XDR * xdrs, read3args * objp)
Definition at line 694 of file nfs3_xdr.c.
References read3args::count, FALSE, read3args::file, read3args::offset, TRUE, xdr_fhandle3(), xdr_uint32(), and xdr_uint64().
xdr_read3res()
bool_t xdr_read3res (XDR * xdrs, read3res * objp)
Definition at line 724 of file nfs3_xdr.c.
References FALSE, NFS3_OK, read3res::read3res_u, read3res::resfail, read3res::resok, read3res::status, TRUE, xdr_nfsstat3(), xdr_post_op_attr(), and xdr_read3resok().
xdr_read3resok()
bool_t xdr_read3resok (XDR * xdrs, read3resok * objp)
Definition at line 708 of file nfs3_xdr.c.
References read3resok::count, read3resok::data, read3resok::data_len, read3resok::data_val, read3resok::eof, FALSE, read3resok::file_attributes, TRUE, xdr_post_op_attr(), and xdr_uint32().
xdr_readdir3args()
bool_t xdr_readdir3args (XDR * xdrs, readdir3args * objp)
Definition at line 1021 of file nfs3_xdr.c.
References readdir3args::cookie, readdir3args::cookieverf, readdir3args::count, readdir3args::dir, FALSE, TRUE, xdr_cookieverf3(), xdr_fhandle3(), xdr_uint32(), and xdr_uint64().
xdr_readdir3res()
bool_t xdr_readdir3res (XDR * xdrs, readdir3res * objp)
Definition at line 1079 of file nfs3_xdr.c.
References FALSE, NFS3_OK, readdir3res::readdir3res_u, readdir3res::resfail, readdir3res::resok, readdir3res::status, TRUE, xdr_nfsstat3(), xdr_post_op_attr(), and xdr_readdir3resok().
xdr_readdir3resok()
bool_t xdr_readdir3resok (XDR * xdrs, readdir3resok * objp)
Definition at line 1065 of file nfs3_xdr.c.
References readdir3resok::cookieverf, readdir3resok::dir_attributes, FALSE, readdir3resok::reply, TRUE, xdr_cookieverf3(), xdr_dirlist3(), and xdr_post_op_attr().
xdr_readdirplus3args()
bool_t xdr_readdirplus3args (XDR * xdrs, readdirplus3args * objp)
Definition at line 1099 of file nfs3_xdr.c.
References readdirplus3args::cookie, readdirplus3args::cookieverf, readdirplus3args::dir, readdirplus3args::dircount, FALSE, readdirplus3args::maxcount, TRUE, xdr_cookieverf3(), xdr_fhandle3(), xdr_uint32(), and xdr_uint64().
xdr_readdirplus3res()
bool_t xdr_readdirplus3res (XDR * xdrs, readdirplus3res * objp)
Definition at line 1163 of file nfs3_xdr.c.
References FALSE, NFS3_OK, readdirplus3res::readdirplus3res_u, readdirplus3res::resfail, readdirplus3res::resok, readdirplus3res::status, TRUE, xdr_nfsstat3(), xdr_post_op_attr(), and xdr_readdirplus3resok().
xdr_readdirplus3resok()
bool_t xdr_readdirplus3resok (XDR * xdrs, readdirplus3resok * objp)
Definition at line 1149 of file nfs3_xdr.c.
References readdirplus3resok::cookieverf, readdirplus3resok::dir_attributes, FALSE, readdirplus3resok::reply, TRUE, xdr_cookieverf3(), xdr_dirlistplus3(), and xdr_post_op_attr().
xdr_readlink3res()
bool_t xdr_readlink3res (XDR * xdrs, readlink3res * objp)
Definition at line 674 of file nfs3_xdr.c.
References FALSE, NFS3_OK, readlink3res::readlink3res_u, readlink3res::resfail, readlink3res::resok, readlink3res::status, TRUE, xdr_nfsstat3(), xdr_post_op_attr(), and xdr_readlink3resok().
xdr_readlink3resok()
bool_t xdr_readlink3resok (XDR * xdrs, readlink3resok * objp)
Definition at line 662 of file nfs3_xdr.c.
References readlink3resok::data, FALSE, readlink3resok::symlink_attributes, TRUE, xdr_nfspath3(), and xdr_post_op_attr().
xdr_rename3args()
bool_t xdr_rename3args (XDR * xdrs, rename3args * objp)
Definition at line 937 of file nfs3_xdr.c.
References FALSE, rename3args::from, rename3args::to, TRUE, and xdr_diropargs3().
xdr_rename3res()
bool_t xdr_rename3res (XDR * xdrs, rename3res * objp)
Definition at line 961 of file nfs3_xdr.c.
References FALSE, rename3res::rename3res_u, rename3res::res, rename3res::status, TRUE, xdr_nfsstat3(), and xdr_rename3wcc().
xdr_rename3wcc()
bool_t xdr_rename3wcc (XDR * xdrs, rename3wcc * objp)
Definition at line 949 of file nfs3_xdr.c.
References FALSE, rename3wcc::fromdir_wcc, rename3wcc::todir_wcc, TRUE, and xdr_wcc_data().
xdr_sattr3()
bool_t xdr_sattr3 (XDR * xdrs, sattr3 * objp)
Definition at line 448 of file nfs3_xdr.c.
References sattr3::atime, FALSE, sattr3::gid, sattr3::mode, sattr3::mtime, sattr3::size, TRUE, sattr3::uid, xdr_set_time(), xdr_set_uint32(), and xdr_set_uint64().
xdr_sattrguard3()
bool_t xdr_sattrguard3 (XDR * xdrs, sattrguard3 * objp)
Definition at line 550 of file nfs3_xdr.c.
References sattrguard3::check, sattrguard3::ctime, FALSE, sattrguard3::sattrguard3_u, TRUE, and xdr_nfstime3().
xdr_set_time()
bool_t xdr_set_time (XDR * xdrs, set_time * objp)
Definition at line 430 of file nfs3_xdr.c.
References FALSE, set_time::set, set_time::set_time_u, SET_TO_CLIENT_TIME, set_time::time, TRUE, xdr_nfstime3(), and xdr_time_how().
xdr_set_uint32()
bool_t xdr_set_uint32 (XDR * xdrs, set_uint32 * objp)
Definition at line 384 of file nfs3_xdr.c.
References FALSE, set_uint32::set, set_uint32::set_uint32_u, TRUE, set_uint32::val, and xdr_uint32().
xdr_set_uint64()
bool_t xdr_set_uint64 (XDR * xdrs, set_uint64 * objp)
Definition at line 402 of file nfs3_xdr.c.
References FALSE, set_uint64::set, set_uint64::set_uint64_u, TRUE, set_uint64::val, and xdr_uint64().
xdr_setattr3args()
bool_t xdr_setattr3args (XDR * xdrs, setattr3args * objp)
Definition at line 570 of file nfs3_xdr.c.
References FALSE, setattr3args::guard, setattr3args::new_attributes, setattr3args::object, TRUE, xdr_fhandle3(), xdr_sattr3(), and xdr_sattrguard3().
xdr_specdata3()
bool_t xdr_specdata3 (XDR * xdrs, specdata3 * objp)
Definition at line 240 of file nfs3_xdr.c.
References FALSE, specdata3::major, specdata3::minor, TRUE, and xdr_uint32().
xdr_stable_how()
bool_t xdr_stable_how (XDR * xdrs, stable_how * objp)
Definition at line 744 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_symlink3args()
bool_t xdr_symlink3args (XDR * xdrs, symlink3args * objp)
Definition at line 877 of file nfs3_xdr.c.
References FALSE, symlink3args::symlink, TRUE, symlink3args::where, xdr_diropargs3(), and xdr_symlinkdata3().
xdr_symlinkdata3()
bool_t xdr_symlinkdata3 (XDR * xdrs, symlinkdata3 * objp)
Definition at line 865 of file nfs3_xdr.c.
References FALSE, symlinkdata3::symlink_attributes, symlinkdata3::symlink_data, TRUE, xdr_nfspath3(), and xdr_sattr3().
xdr_time_how()
bool_t xdr_time_how (XDR * xdrs, time_how * objp)
Definition at line 420 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_uint32()
bool_t xdr_uint32 (XDR * xdrs, uint32 * objp)
Definition at line 29 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_uint64()
bool_t xdr_uint64 (XDR * xdrs, uint64 * objp)
Definition at line 9 of file nfs3_xdr.c.
References FALSE, and TRUE.
xdr_wcc_attr()
bool_t xdr_wcc_attr (XDR * xdrs, wcc_attr * objp)
Definition at line 318 of file nfs3_xdr.c.
References wcc_attr::ctime, FALSE, wcc_attr::mtime, wcc_attr::size, TRUE, xdr_nfstime3(), and xdr_uint64().
xdr_wcc_data()
bool_t xdr_wcc_data (XDR * xdrs, wcc_data * objp)
Definition at line 352 of file nfs3_xdr.c.
References wcc_data::after, wcc_data::before, FALSE, TRUE, xdr_post_op_attr(), and xdr_pre_op_attr().
xdr_wccstat3()
bool_t xdr_wccstat3 (XDR * xdrs, wccstat3 * objp)
Definition at line 514 of file nfs3_xdr.c.
References FALSE, wccstat3::status, TRUE, wccstat3::wcc, wccstat3::wccstat3_u, xdr_nfsstat3(), and xdr_wcc_data().
xdr_write3args()
bool_t xdr_write3args (XDR * xdrs, write3args * objp)
Definition at line 754 of file nfs3_xdr.c.
References write3args::count, write3args::data, write3args::data_len, write3args::data_val, FALSE, write3args::file, write3args::offset, write3args::stable, TRUE, xdr_fhandle3(), xdr_stable_how(), xdr_uint32(), and xdr_uint64().
xdr_write3res()
bool_t xdr_write3res (XDR * xdrs, write3res * objp)
Definition at line 788 of file nfs3_xdr.c.
References FALSE, NFS3_OK, write3res::resfail, write3res::resok, write3res::status, TRUE, write3res::write3res_u, xdr_nfsstat3(), xdr_wcc_data(), and xdr_write3resok().
xdr_write3resok()
bool_t xdr_write3resok (XDR * xdrs, write3resok * objp)
Definition at line 772 of file nfs3_xdr.c.
References write3resok::committed, write3resok::count, FALSE, write3resok::file_wcc, TRUE, write3resok::verf, xdr_stable_how(), xdr_uint32(), xdr_wcc_data(), and xdr_writeverf3().
xdr_writeverf3()
bool_t xdr_writeverf3 (XDR * xdrs, writeverf3 objp)
Definition at line 89 of file nfs3_xdr.c.
References FALSE, NFS3_WRITEVERFSIZE, and TRUE.