nfs3_clnt.c File Reference
#include nfi/nfi_nfs3/nfs3.h
Functions
enum clnt_stat nfsproc3_null_3 (void *argp, void *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_getattr_3 (fhandle3 *argp, getattr3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_setattr_3 (setattr3args *argp, wccstat3 *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_lookup_3 (diropargs3 *argp, lookup3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_access_3 (access3args *argp, access3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_readlink_3 (fhandle3 *argp, readlink3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_read_3 (read3args *argp, read3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_write_3 (write3args *argp, write3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_create_3 (create3args *argp, diropres3 *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_mkdir_3 (mkdir3args *argp, diropres3 *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_symlink_3 (symlink3args *argp, diropres3 *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_mknod_3 (mknod3args *argp, diropres3 *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_remove_3 (diropargs3 *argp, wccstat3 *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_rmdir_3 (diropargs3 *argp, wccstat3 *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_rename_3 (rename3args *argp, rename3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_link_3 (link3args *argp, link3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_readdir_3 (readdir3args *argp, readdir3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_readdirplus_3 (readdirplus3args *argp, readdirplus3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_fsstat_3 (fhandle3 *argp, fsstat3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_fsinfo_3 (fhandle3 *argp, fsinfo3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_pathconf_3 (fhandle3 *argp, pathconf3res *clnt_res, CLIENT *clnt)
enum clnt_stat nfsproc3_commit_3 (commit3args *argp, commit3res *clnt_res, CLIENT *clnt)
enum clnt_stat mountproc3_null_3 (void *argp, void *clnt_res, CLIENT *clnt)
enum clnt_stat mountproc3_mnt_3 (nfspath3 *argp, mountres3 *clnt_res, CLIENT *clnt)
enum clnt_stat mountproc3_dump_3 (void *argp, mountlist3 *clnt_res, CLIENT *clnt)
enum clnt_stat mountproc3_umnt_3 (nfspath3 *argp, void *clnt_res, CLIENT *clnt)
enum clnt_stat mountproc3_umntall_3 (void *argp, void *clnt_res, CLIENT *clnt)
enum clnt_stat mountproc3_export_3 (void *argp, exports3 *clnt_res, CLIENT *clnt)
Variables
static struct timeval TIMEOUT = { 25, 0 }
Function Documentation
mountproc3_dump_3()
enum clnt_stat mountproc3_dump_3 (void * argp, mountlist3 * clnt_res, CLIENT * clnt)
Definition at line 230 of file nfs3_clnt.c.
References argp, MOUNTPROC3_DUMP, TIMEOUT, and xdr_mountlist3().
mountproc3_export_3()
enum clnt_stat mountproc3_export_3 (void * argp, exports3 * clnt_res, CLIENT * clnt)
Definition at line 257 of file nfs3_clnt.c.
References argp, MOUNTPROC3_EXPORT, TIMEOUT, and xdr_exports3().
mountproc3_mnt_3()
enum clnt_stat mountproc3_mnt_3 (nfspath3 * argp, mountres3 * clnt_res, CLIENT * clnt)
Definition at line 221 of file nfs3_clnt.c.
References argp, MOUNTPROC3_MNT, TIMEOUT, xdr_mountres3(), and xdr_nfspath3().
mountproc3_null_3()
enum clnt_stat mountproc3_null_3 (void * argp, void * clnt_res, CLIENT * clnt)
Definition at line 212 of file nfs3_clnt.c.
References argp, MOUNTPROC3_NULL, and TIMEOUT.
mountproc3_umnt_3()
enum clnt_stat mountproc3_umnt_3 (nfspath3 * argp, void * clnt_res, CLIENT * clnt)
Definition at line 239 of file nfs3_clnt.c.
References argp, MOUNTPROC3_UMNT, TIMEOUT, and xdr_nfspath3().
mountproc3_umntall_3()
enum clnt_stat mountproc3_umntall_3 (void * argp, void * clnt_res, CLIENT * clnt)
Definition at line 248 of file nfs3_clnt.c.
References argp, MOUNTPROC3_UMNTALL, and TIMEOUT.
nfsproc3_access_3()
enum clnt_stat nfsproc3_access_3 (access3args * argp, access3res * clnt_res, CLIENT * clnt)
Definition at line 50 of file nfs3_clnt.c.
References argp, NFSPROC3_ACCESS, TIMEOUT, xdr_access3args(), and xdr_access3res().
nfsproc3_commit_3()
enum clnt_stat nfsproc3_commit_3 (commit3args * argp, commit3res * clnt_res, CLIENT * clnt)
Definition at line 203 of file nfs3_clnt.c.
References argp, NFSPROC3_COMMIT, TIMEOUT, xdr_commit3args(), and xdr_commit3res().
nfsproc3_create_3()
enum clnt_stat nfsproc3_create_3 (create3args * argp, diropres3 * clnt_res, CLIENT * clnt)
Definition at line 86 of file nfs3_clnt.c.
References argp, NFSPROC3_CREATE, TIMEOUT, xdr_create3args(), and xdr_diropres3().
nfsproc3_fsinfo_3()
enum clnt_stat nfsproc3_fsinfo_3 (fhandle3 * argp, fsinfo3res * clnt_res, CLIENT * clnt)
Definition at line 185 of file nfs3_clnt.c.
References argp, NFSPROC3_FSINFO, TIMEOUT, xdr_fhandle3(), and xdr_fsinfo3res().
nfsproc3_fsstat_3()
enum clnt_stat nfsproc3_fsstat_3 (fhandle3 * argp, fsstat3res * clnt_res, CLIENT * clnt)
Definition at line 176 of file nfs3_clnt.c.
References argp, NFSPROC3_FSSTAT, TIMEOUT, xdr_fhandle3(), and xdr_fsstat3res().
nfsproc3_getattr_3()
enum clnt_stat nfsproc3_getattr_3 (fhandle3 * argp, getattr3res * clnt_res, CLIENT * clnt)
Definition at line 23 of file nfs3_clnt.c.
References argp, NFSPROC3_GETATTR, TIMEOUT, xdr_fhandle3(), and xdr_getattr3res().
nfsproc3_link_3()
enum clnt_stat nfsproc3_link_3 (link3args * argp, link3res * clnt_res, CLIENT * clnt)
Definition at line 149 of file nfs3_clnt.c.
References argp, NFSPROC3_LINK, TIMEOUT, xdr_link3args(), and xdr_link3res().
nfsproc3_lookup_3()
enum clnt_stat nfsproc3_lookup_3 (diropargs3 * argp, lookup3res * clnt_res, CLIENT * clnt)
Definition at line 41 of file nfs3_clnt.c.
References argp, NFSPROC3_LOOKUP, TIMEOUT, xdr_diropargs3(), and xdr_lookup3res().
nfsproc3_mkdir_3()
enum clnt_stat nfsproc3_mkdir_3 (mkdir3args * argp, diropres3 * clnt_res, CLIENT * clnt)
Definition at line 95 of file nfs3_clnt.c.
References argp, NFSPROC3_MKDIR, TIMEOUT, xdr_diropres3(), and xdr_mkdir3args().
nfsproc3_mknod_3()
enum clnt_stat nfsproc3_mknod_3 (mknod3args * argp, diropres3 * clnt_res, CLIENT * clnt)
Definition at line 113 of file nfs3_clnt.c.
References argp, NFSPROC3_MKNOD, TIMEOUT, xdr_diropres3(), and xdr_mknod3args().
nfsproc3_null_3()
enum clnt_stat nfsproc3_null_3 (void * argp, void * clnt_res, CLIENT * clnt)
Definition at line 14 of file nfs3_clnt.c.
References argp, NFSPROC3_NULL, and TIMEOUT.
nfsproc3_pathconf_3()
enum clnt_stat nfsproc3_pathconf_3 (fhandle3 * argp, pathconf3res * clnt_res, CLIENT * clnt)
Definition at line 194 of file nfs3_clnt.c.
References argp, NFSPROC3_PATHCONF, TIMEOUT, xdr_fhandle3(), and xdr_pathconf3res().
nfsproc3_read_3()
enum clnt_stat nfsproc3_read_3 (read3args * argp, read3res * clnt_res, CLIENT * clnt)
Definition at line 68 of file nfs3_clnt.c.
References argp, NFSPROC3_READ, TIMEOUT, xdr_read3args(), and xdr_read3res().
nfsproc3_readdir_3()
enum clnt_stat nfsproc3_readdir_3 (readdir3args * argp, readdir3res * clnt_res, CLIENT * clnt)
Definition at line 158 of file nfs3_clnt.c.
References argp, NFSPROC3_READDIR, TIMEOUT, xdr_readdir3args(), and xdr_readdir3res().
nfsproc3_readdirplus_3()
enum clnt_stat nfsproc3_readdirplus_3 (readdirplus3args * argp, readdirplus3res * clnt_res, CLIENT * clnt)
Definition at line 167 of file nfs3_clnt.c.
References argp, NFSPROC3_READDIRPLUS, TIMEOUT, xdr_readdirplus3args(), and xdr_readdirplus3res().
nfsproc3_readlink_3()
enum clnt_stat nfsproc3_readlink_3 (fhandle3 * argp, readlink3res * clnt_res, CLIENT * clnt)
Definition at line 59 of file nfs3_clnt.c.
References argp, NFSPROC3_READLINK, TIMEOUT, xdr_fhandle3(), and xdr_readlink3res().
nfsproc3_remove_3()
enum clnt_stat nfsproc3_remove_3 (diropargs3 * argp, wccstat3 * clnt_res, CLIENT * clnt)
Definition at line 122 of file nfs3_clnt.c.
References argp, NFSPROC3_REMOVE, TIMEOUT, xdr_diropargs3(), and xdr_wccstat3().
nfsproc3_rename_3()
enum clnt_stat nfsproc3_rename_3 (rename3args * argp, rename3res * clnt_res, CLIENT * clnt)
Definition at line 140 of file nfs3_clnt.c.
References argp, NFSPROC3_RENAME, TIMEOUT, xdr_rename3args(), and xdr_rename3res().
nfsproc3_rmdir_3()
enum clnt_stat nfsproc3_rmdir_3 (diropargs3 * argp, wccstat3 * clnt_res, CLIENT * clnt)
Definition at line 131 of file nfs3_clnt.c.
References argp, NFSPROC3_RMDIR, TIMEOUT, xdr_diropargs3(), and xdr_wccstat3().
nfsproc3_setattr_3()
enum clnt_stat nfsproc3_setattr_3 (setattr3args * argp, wccstat3 * clnt_res, CLIENT * clnt)
Definition at line 32 of file nfs3_clnt.c.
References argp, NFSPROC3_SETATTR, TIMEOUT, xdr_setattr3args(), and xdr_wccstat3().
nfsproc3_symlink_3()
enum clnt_stat nfsproc3_symlink_3 (symlink3args * argp, diropres3 * clnt_res, CLIENT * clnt)
Definition at line 104 of file nfs3_clnt.c.
References argp, NFSPROC3_SYMLINK, TIMEOUT, xdr_diropres3(), and xdr_symlink3args().
nfsproc3_write_3()
enum clnt_stat nfsproc3_write_3 (write3args * argp, write3res * clnt_res, CLIENT * clnt)
Definition at line 77 of file nfs3_clnt.c.
References argp, NFSPROC3_WRITE, TIMEOUT, xdr_write3args(), and xdr_write3res().
Variable Documentation
TIMEOUT
struct timeval TIMEOUT = { 25, 0 } [static]
Definition at line 11 of file nfs3_clnt.c.
Referenced by mountproc3_dump_3(), mountproc3_export_3(), mountproc3_mnt_3(), mountproc3_null_3(), mountproc3_umnt_3(), mountproc3_umntall_3(), nfsproc3_access_3(), nfsproc3_commit_3(), nfsproc3_create_3(), nfsproc3_fsinfo_3(), nfsproc3_fsstat_3(), nfsproc3_getattr_3(), nfsproc3_link_3(), nfsproc3_lookup_3(), nfsproc3_mkdir_3(), nfsproc3_mknod_3(), nfsproc3_null_3(), nfsproc3_pathconf_3(), nfsproc3_read_3(), nfsproc3_readdir_3(), nfsproc3_readdirplus_3(), nfsproc3_readlink_3(), nfsproc3_remove_3(), nfsproc3_rename_3(), nfsproc3_rmdir_3(), nfsproc3_setattr_3(), nfsproc3_symlink_3(), and nfsproc3_write_3().