nfs3.c File Reference
File to 'TODO'.
#include nfi/nfi_nfs3/nfs3.h
Functions
void printfh3 (char *s, fhandle3 *fh)
CLIENT * create_connection_mount3 (char *name, int type)
void close_connection_mount3 (CLIENT *cl)
int nfs3_mount (char *dir, fhandle3 *fhand, CLIENT *cli)
int nfs3_umount (char *path, CLIENT *cli)
int nfs3_export (__attribute__((__unused__)) exports3 *exp, __attribute__((__unused__)) CLIENT *cli)
CLIENT * create_connection_nfs3 (char *name, int type)
void close_connection_nfs3 (CLIENT *cl)
int nfs3_setattr (fhandle3 *fh, fattr3 *fatt, CLIENT *cl)
int nfs3_getattr (fhandle3 *fh, fattr3 *fatt, CLIENT *cl)
int nfs3_lookup (fhandle3 *fhin, char *path, fhandle3 *fhout, fattr3 *att, CLIENT *cl)
ssize_t nfs3_read (fhandle3 *fh, void *data, off_t offset, size_t size, CLIENT *cl)
ssize_t nfs3_write (fhandle3 *fh, void *data, off_t offset, size_t size, CLIENT *cl)
int nfs3_create (fhandle3 *fhin, char *file, mode_t mode, fhandle3 *fhout, __attribute__((__unused__)) fattr3 *at, CLIENT *cl)
int nfs3_remove (fhandle3 *fh, char *file, CLIENT *cl)
int nfs3_rename (__attribute__((__unused__)) fhandle3 *fh, __attribute__((__unused__)) char *name, __attribute__((__unused__)) fhandle3 *fhR, __attribute__((__unused__)) char *nameR, __attribute__((__unused__)) CLIENT *cl)
int nfs3_mkdir (__attribute__((__unused__)) fhandle3 *fhin, __attribute__((__unused__)) char *dir, __attribute__((__unused__)) mode_t mode, __attribute__((__unused__)) fhandle3 *fhout, __attribute__((__unused__)) fattr3 *at, __attribute__((__unused__)) CLIENT *cl)
int nfs3_rmdir (__attribute__((__unused__)) fhandle3 *fh, __attribute__((__unused__)) char *dir, __attribute__((__unused__)) CLIENT *cl)
int nfs3_readdir (__attribute__((__unused__)) fhandle3 *fh, __attribute__((__unused__)) cookieverf3 cookie, __attribute__((__unused__)) char *entr, __attribute__((__unused__)) CLIENT *cl)
int nfs3_statfs (__attribute__((__unused__)) fhandle3 *arg, __attribute__((__unused__)) fsinfo3resok *inf, __attribute__((__unused__)) CLIENT *cl)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfs3.c.
Function Documentation
close_connection_mount3()
void close_connection_mount3 (CLIENT * cl)
Definition at line 180 of file nfs3.c.
Referenced by create_connection_mount3(), nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs3_init(), and nfi_nfs3_reconnect().
close_connection_nfs3()
void close_connection_nfs3 (CLIENT * cl)
Definition at line 492 of file nfs3.c.
Referenced by create_connection_nfs3(), nfi_nfs3_destroy(), nfi_nfs3_disconnect(), and nfi_nfs3_init().
create_connection_mount3()
CLIENT * create_connection_mount3 (char * name, int type)
Definition at line 76 of file nfs3.c.
References close_connection_mount3(), MNTNAMLEN, MOUNT3_PROGRAM, MOUNT3_VERSION, NFS3_RECVSZ, NFS3_SENDSZ, NFS3_TCP, and NFS3_UDP.
Referenced by nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs3_init(), and nfi_nfs3_reconnect().
create_connection_nfs3()
CLIENT * create_connection_nfs3 (char * name, int type)
Definition at line 390 of file nfs3.c.
References close_connection_nfs3(), MNTNAMLEN, NFS3_PROGRAM, NFS3_RECVSZ, NFS3_SENDSZ, NFS3_TCP, NFS3_UDP, and NFS3_VERSION.
Referenced by nfi_nfs3_init(), and nfi_nfs3_reconnect().
nfs3_create()
int nfs3_create (fhandle3 * fhin, char * file, mode_t mode, fhandle3 * fhout, __attribute__((__unused__)) fattr3 * at, CLIENT * cl)
Definition at line 1039 of file nfs3.c.
References createhow3::createhow3_u, diropargs3::dir, diropres3::diropres3_u, fhandle3::fhandle3_len, fhandle3::fhandle3_val, FHSIZE3, post_op_fh3::handle, create3args::how, sattr3::mode, createhow3::mode, diropargs3::name, nfsproc3_create_3(), diropres3ok::obj, createhow3::obj_attributes, post_op_fh3::post_op_fh3_u, printfh3(), diropres3::resok, set_uint32::set, set_uint32::set_uint32_u, diropres3::status, UNCHECKED, set_uint32::val, and create3args::where.
Referenced by nfi_nfs3_create().
nfs3_export()
int nfs3_export (__attribute__((__unused__)) exports3 * exp, __attribute__((__unused__)) CLIENT * cli)
Definition at line 370 of file nfs3.c.
nfs3_getattr()
int nfs3_getattr (fhandle3 * fh, fattr3 * fatt, CLIENT * cl)
Definition at line 614 of file nfs3.c.
References getattr3res::attributes, getattr3res::getattr3res_u, NFS3_OK, nfsproc3_getattr_3(), and getattr3res::status.
Referenced by nfi_nfs3_getattr().
nfs3_lookup()
int nfs3_lookup (fhandle3 * fhin, char * path, fhandle3 * fhout, fattr3 * att, CLIENT * cl)
Definition at line 676 of file nfs3.c.
References post_op_attr::attributes, diropargs3::dir, fhandle3::fhandle3_len, fhandle3::fhandle3_val, FHSIZE3, getFirstDir(), lookup3res::lookup3res_u, MNTNAMLEN, diropargs3::name, nfsproc3_lookup_3(), lookup3resok::obj_attributes, lookup3resok::object, post_op_attr::post_op_attr_u, post_op_attr::present, lookup3res::resok, lookup3res::status, and fattr3::type.
Referenced by nfi_nfs3_create(), nfi_nfs3_mkdir(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), and nfs3_open().
nfs3_mkdir()
int nfs3_mkdir (__attribute__((__unused__)) fhandle3 * fhin, __attribute__((__unused__)) char * dir, __attribute__((__unused__)) mode_t mode, __attribute__((__unused__)) fhandle3 * fhout, __attribute__((__unused__)) fattr3 * at, __attribute__((__unused__)) CLIENT * cl)
Definition at line 1227 of file nfs3.c.
Referenced by nfi_nfs3_mkdir().
nfs3_mount()
int nfs3_mount (char * dir, fhandle3 * fhand, CLIENT * cli)
Definition at line 223 of file nfs3.c.
References mountres3_ok::auth_flavors, mountres3_ok::auth_flavors_len, mountres3_ok::auth_flavors_val, mountres3_ok::fhandle, fhandle3::fhandle3_len, fhandle3::fhandle3_val, mountres3::fhs_status, FHSIZE3, mountres3::mountinfo, mountproc3_mnt_3(), and mountres3::mountres3_u.
Referenced by nfi_nfs3_init(), and nfi_nfs3_reconnect().
nfs3_read()
ssize_t nfs3_read (fhandle3 * fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 814 of file nfs3.c.
References read3args::count, read3resok::data, read3resok::data_len, read3resok::data_val, fhandle3::fhandle3_len, fhandle3::fhandle3_val, read3args::file, MAXDATA3, nfsproc3_read_3(), read3args::offset, read3res::read3res_u, read3res::resok, and read3res::status.
Referenced by nfi_nfs3_read().
nfs3_readdir()
int nfs3_readdir (__attribute__((__unused__)) fhandle3 * fh, __attribute__((__unused__)) cookieverf3 cookie, __attribute__((__unused__)) char * entr, __attribute__((__unused__)) CLIENT * cl)
Definition at line 1280 of file nfs3.c.
Referenced by nfi_nfs3_readdir().
nfs3_remove()
int nfs3_remove (fhandle3 * fh, char * file, CLIENT * cl)
Definition at line 1134 of file nfs3.c.
References diropargs3::dir, fhandle3::fhandle3_len, fhandle3::fhandle3_val, diropargs3::name, nfsproc3_remove_3(), and wccstat3::status.
Referenced by nfi_nfs3_remove().
nfs3_rename()
int nfs3_rename (__attribute__((__unused__)) fhandle3 * fh, __attribute__((__unused__)) char * name, __attribute__((__unused__)) fhandle3 * fhR, __attribute__((__unused__)) char * nameR, __attribute__((__unused__)) CLIENT * cl)
Definition at line 1200 of file nfs3.c.
nfs3_rmdir()
int nfs3_rmdir (__attribute__((__unused__)) fhandle3 * fh, __attribute__((__unused__)) char * dir, __attribute__((__unused__)) CLIENT * cl)
Definition at line 1248 of file nfs3.c.
Referenced by nfi_nfs3_rmdir().
nfs3_setattr()
int nfs3_setattr (fhandle3 * fh, fattr3 * fatt, CLIENT * cl)
Definition at line 555 of file nfs3.c.
References fattr3::atime, sattr3::atime, fattr3::gid, sattr3::gid, fattr3::mode, sattr3::mode, fattr3::mtime, sattr3::mtime, setattr3args::new_attributes, NFS3_FHSIZE, NFS3_OK, nfsproc3_setattr_3(), setattr3args::object, set_time::set_time_u, set_uint32::set_uint32_u, set_uint64::set_uint64_u, fattr3::size, sattr3::size, wccstat3::status, set_time::time, fattr3::uid, sattr3::uid, set_uint32::val, and set_uint64::val.
Referenced by nfi_nfs3_setattr().
nfs3_statfs()
int nfs3_statfs (__attribute__((__unused__)) fhandle3 * arg, __attribute__((__unused__)) fsinfo3resok * inf, __attribute__((__unused__)) CLIENT * cl)
Definition at line 1301 of file nfs3.c.
Referenced by nfi_nfs3_statfs().
nfs3_umount()
int nfs3_umount (char * path, CLIENT * cli)
Definition at line 320 of file nfs3.c.
References mountproc3_umnt_3().
Referenced by nfi_nfs3_destroy(), and nfi_nfs3_disconnect().
nfs3_write()
ssize_t nfs3_write (fhandle3 * fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 929 of file nfs3.c.
References write3args::count, write3args::data, write3args::data_len, DATA_SYNC, write3args::data_val, fhandle3::fhandle3_len, fhandle3::fhandle3_val, write3args::file, FILE_SYNC, MAXDATA3, nfsproc3_write_3(), write3args::offset, printfh3(), write3args::stable, write3res::status, and UNSTABLE.
Referenced by nfi_nfs3_write().
printfh3()
void printfh3 (char * s, fhandle3 * fh)
Definition at line 39 of file nfs3.c.
References fhandle3::fhandle3_val, and FHSIZE3.
Referenced by nfs3_create(), and nfs3_write().