nfs3.h File Reference
#include all_system.h
#include base/path_misc.h
Data Structures
struct fhandle3
struct mountres3_ok
struct mountres3
struct mountbody3
struct groupnode3
struct exportnode3
struct specdata3
struct nfstime3
struct fattr3
struct post_op_attr
struct wcc_attr
struct pre_op_attr
struct wcc_data
struct post_op_fh3
struct set_uint32
struct set_uint64
struct set_time
struct sattr3
struct diropargs3
struct diropres3ok
struct diropres3
struct wccstat3
struct getattr3res
struct sattrguard3
struct setattr3args
struct lookup3resok
struct lookup3res
struct access3args
struct access3resok
struct access3res
struct readlink3resok
struct readlink3res
struct read3args
struct read3resok
struct read3res
struct write3args
struct write3resok
struct write3res
struct createhow3
struct create3args
struct mkdir3args
struct symlinkdata3
struct symlink3args
struct devicedata3
struct mknoddata3
struct mknod3args
struct rename3args
struct rename3wcc
struct rename3res
struct link3args
struct link3wcc
struct link3res
struct readdir3args
struct entry3
struct dirlist3
struct readdir3resok
struct readdir3res
struct readdirplus3args
struct entryplus3
struct dirlistplus3
struct readdirplus3resok
struct readdirplus3res
struct fsstat3resok
struct fsstat3res
struct fsinfo3resok
struct fsinfo3res
struct pathconf3resok
struct pathconf3res
struct commit3args
struct commit3resok
struct commit3res
Macros
#define NFS3_TCP 1
#define NFS3_UDP 0
#define NFS3_SENDSZ (unsigned int)(128 * 1024)
#define NFS3_RECVSZ (unsigned int)(128 * 1024)
#define NFS3ERR_EOFDIR -10011
#define MAXDATA3 (1024 * 32)
#define MNTPATHLEN 1024
#define MNTNAMLEN 255
#define FHSIZE3 64
#define MOUNT3_PROGRAM 100005
#define MOUNT3_VERSION 3
#define MOUNTPROC3_NULL 0
#define MOUNTPROC3_MNT 1
#define MOUNTPROC3_DUMP 2
#define MOUNTPROC3_UMNT 3
#define MOUNTPROC3_UMNTALL 4
#define MOUNTPROC3_EXPORT 5
#define NFS3_FHSIZE FHSIZE3
#define NFS3_COOKIEVERFSIZE 8
#define NFS3_CREATEVERFSIZE 8
#define NFS3_WRITEVERFSIZE 8
#define ACCESS3_READ 0x0001
#define ACCESS3_LOOKUP 0x0002
#define ACCESS3_MODIFY 0x0004
#define ACCESS3_EXTEND 0x0008
#define ACCESS3_DELETE 0x0010
#define ACCESS3_EXECUTE 0x0020
#define FSF3_LINK 0x0001
#define FSF3_SYMLINK 0x0002
#define FSF3_HOMOGENEOUS 0x0008
#define FSF3_CANSETTIME 0x0010
#define NFS3_PROGRAM 100003
#define NFS3_VERSION 3
#define NFSPROC3_NULL 0
#define NFSPROC3_GETATTR 1
#define NFSPROC3_SETATTR 2
#define NFSPROC3_LOOKUP 3
#define NFSPROC3_ACCESS 4
#define NFSPROC3_READLINK 5
#define NFSPROC3_READ 6
#define NFSPROC3_WRITE 7
#define NFSPROC3_CREATE 8
#define NFSPROC3_MKDIR 9
#define NFSPROC3_SYMLINK 10
#define NFSPROC3_MKNOD 11
#define NFSPROC3_REMOVE 12
#define NFSPROC3_RMDIR 13
#define NFSPROC3_RENAME 14
#define NFSPROC3_LINK 15
#define NFSPROC3_READDIR 16
#define NFSPROC3_READDIRPLUS 17
#define NFSPROC3_FSSTAT 18
#define NFSPROC3_FSINFO 19
#define NFSPROC3_PATHCONF 20
#define NFSPROC3_COMMIT 21
Typedefs
typedef char * nfs3_dirpath
typedef char * nfs3_name
typedef enum mountstat3 mountstat3
typedef struct mountres3_ok mountres3_ok
typedef struct mountres3 mountres3
typedef struct mountbody3 * mountlist3
typedef struct mountbody3 mountbody3
typedef struct groupnode3 * groups3
typedef struct groupnode3 groupnode3
typedef struct exportnode3 * exports3
typedef struct exportnode3 exportnode3
typedef uint64_t uint64
typedef int64_t int64
typedef u_int uint32
typedef int int32
typedef char * filename3
typedef char * nfspath3
typedef char cookieverf3[NFS3_COOKIEVERFSIZE]
typedef char createverf3[NFS3_CREATEVERFSIZE]
typedef char writeverf3[NFS3_WRITEVERFSIZE]
typedef enum nfsstat3 nfsstat3
typedef enum ftype3 ftype3
typedef struct specdata3 specdata3
typedef struct nfstime3 nfstime3
typedef struct fattr3 fattr3
typedef struct post_op_attr post_op_attr
typedef struct wcc_attr wcc_attr
typedef struct pre_op_attr pre_op_attr
typedef struct wcc_data wcc_data
typedef struct post_op_fh3 post_op_fh3
typedef struct set_uint32 set_uint32
typedef struct set_uint64 set_uint64
typedef enum time_how time_how
typedef struct set_time set_time
typedef struct sattr3 sattr3
typedef struct diropargs3 diropargs3
typedef struct diropres3ok diropres3ok
typedef struct diropres3 diropres3
typedef struct wccstat3 wccstat3
typedef struct getattr3res getattr3res
typedef struct sattrguard3 sattrguard3
typedef struct setattr3args setattr3args
typedef struct lookup3resok lookup3resok
typedef struct lookup3res lookup3res
typedef struct access3args access3args
typedef struct access3resok access3resok
typedef struct access3res access3res
typedef struct readlink3resok readlink3resok
typedef struct readlink3res readlink3res
typedef struct read3args read3args
typedef struct read3resok read3resok
typedef struct read3res read3res
typedef enum stable_how stable_how
typedef struct write3args write3args
typedef struct write3resok write3resok
typedef struct write3res write3res
typedef enum createmode3 createmode3
typedef struct createhow3 createhow3
typedef struct create3args create3args
typedef struct mkdir3args mkdir3args
typedef struct symlinkdata3 symlinkdata3
typedef struct symlink3args symlink3args
typedef struct devicedata3 devicedata3
typedef struct mknoddata3 mknoddata3
typedef struct mknod3args mknod3args
typedef struct rename3args rename3args
typedef struct rename3wcc rename3wcc
typedef struct rename3res rename3res
typedef struct link3args link3args
typedef struct link3wcc link3wcc
typedef struct link3res link3res
typedef struct readdir3args readdir3args
typedef struct entry3 entry3
typedef struct dirlist3 dirlist3
typedef struct readdir3resok readdir3resok
typedef struct readdir3res readdir3res
typedef struct readdirplus3args readdirplus3args
typedef struct entryplus3 entryplus3
typedef struct dirlistplus3 dirlistplus3
typedef struct readdirplus3resok readdirplus3resok
typedef struct readdirplus3res readdirplus3res
typedef struct fsstat3resok fsstat3resok
typedef struct fsstat3res fsstat3res
typedef struct fsinfo3resok fsinfo3resok
typedef struct fsinfo3res fsinfo3res
typedef struct pathconf3resok pathconf3resok
typedef struct pathconf3res pathconf3res
typedef struct commit3args commit3args
typedef struct commit3resok commit3resok
typedef struct commit3res commit3res
Enumerations
enum mountstat3 {
MNT3_OK = 0
, MNT3ERR_PERM = 1
, MNT3ERR_NOENT = 2
, MNT3ERR_IO = 5
,
MNT3ERR_ACCES = 13
, MNT3ERR_NOTDIR = 20
, MNT3ERR_INVAL = 22
, MNT3ERR_NAMETOOLONG = 63
,
MNT3ERR_NOTSUPP = 10004
, MNT3ERR_SERVERFAULT = 10006
 }
enum nfsstat3 {
NFS3_OK = 0
, NFS3ERR_PERM = 1
, NFS3ERR_NOENT = 2
, NFS3ERR_IO = 5
,
NFS3ERR_NXIO = 6
, NFS3ERR_ACCES = 13
, NFS3ERR_EXIST = 17
, NFS3ERR_XDEV = 18
,
NFS3ERR_NODEV = 19
, NFS3ERR_NOTDIR = 20
, NFS3ERR_ISDIR = 21
, NFS3ERR_INVAL = 22
,
NFS3ERR_FBIG = 27
, NFS3ERR_NOSPC = 28
, NFS3ERR_ROFS = 30
, NFS3ERR_MLINK = 31
,
NFS3ERR_NAMETOOLONG = 63
, NFS3ERR_NOTEMPTY = 66
, NFS3ERR_DQUOT = 69
, NFS3ERR_STALE = 70
,
NFS3ERR_REMOTE = 71
, NFS3ERR_BADHANDLE = 10001
, NFS3ERR_NOT_SYNC = 10002
, NFS3ERR_BAD_COOKIE = 10003
,
NFS3ERR_NOTSUPP = 10004
, NFS3ERR_TOOSMALL = 10005
, NFS3ERR_SERVERFAULT = 10006
, NFS3ERR_BADTYPE = 10007
,
NFS3ERR_JUKEBOX = 10008
, NFS3ERR_FPRINTNOTFOUND = 10009
, NFS3ERR_ABORTED = 10010
 }
enum ftype3 {
NF3REG = 1
, NF3DIR = 2
, NF3BLK = 3
, NF3CHR = 4
,
NF3LNK = 5
, NF3SOCK = 6
, NF3FIFO = 7
 }
enum time_how { DONT_CHANGE = 0
, SET_TO_SERVER_TIME = 1
, SET_TO_CLIENT_TIME = 2
 }
enum stable_how { UNSTABLE = 0
, DATA_SYNC = 1
, FILE_SYNC = 2
 }
enum createmode3 { UNCHECKED = 0
, GUARDED = 1
, EXCLUSIVE = 2
 }
Functions
enum clnt_stat mountproc3_null_3 ()
bool_t mountproc3_null_3_svc ()
enum clnt_stat mountproc3_mnt_3 ()
bool_t mountproc3_mnt_3_svc ()
enum clnt_stat mountproc3_dump_3 ()
bool_t mountproc3_dump_3_svc ()
enum clnt_stat mountproc3_umnt_3 ()
bool_t mountproc3_umnt_3_svc ()
enum clnt_stat mountproc3_umntall_3 ()
bool_t mountproc3_umntall_3_svc ()
enum clnt_stat mountproc3_export_3 ()
bool_t mountproc3_export_3_svc ()
int mount_program_3_freeresult ()
bool_t xdr_fhandle3 ()
bool_t xdr_dirpath ()
bool_t xdr_name ()
bool_t xdr_mountstat3 ()
bool_t xdr_mountres3_ok ()
bool_t xdr_mountres3 ()
bool_t xdr_mountlist3 ()
bool_t xdr_mountbody3 ()
bool_t xdr_groups3 ()
bool_t xdr_groupnode3 ()
bool_t xdr_exports3 ()
bool_t xdr_exportnode3 ()
enum clnt_stat nfsproc3_null_3 ()
bool_t nfsproc3_null_3_svc ()
enum clnt_stat nfsproc3_getattr_3 ()
bool_t nfsproc3_getattr_3_svc ()
enum clnt_stat nfsproc3_setattr_3 ()
bool_t nfsproc3_setattr_3_svc ()
enum clnt_stat nfsproc3_lookup_3 ()
bool_t nfsproc3_lookup_3_svc ()
enum clnt_stat nfsproc3_access_3 ()
bool_t nfsproc3_access_3_svc ()
enum clnt_stat nfsproc3_readlink_3 ()
bool_t nfsproc3_readlink_3_svc ()
enum clnt_stat nfsproc3_read_3 ()
bool_t nfsproc3_read_3_svc ()
enum clnt_stat nfsproc3_write_3 ()
bool_t nfsproc3_write_3_svc ()
enum clnt_stat nfsproc3_create_3 ()
bool_t nfsproc3_create_3_svc ()
enum clnt_stat nfsproc3_mkdir_3 ()
bool_t nfsproc3_mkdir_3_svc ()
enum clnt_stat nfsproc3_symlink_3 ()
bool_t nfsproc3_symlink_3_svc ()
enum clnt_stat nfsproc3_mknod_3 ()
bool_t nfsproc3_mknod_3_svc ()
enum clnt_stat nfsproc3_remove_3 ()
bool_t nfsproc3_remove_3_svc ()
enum clnt_stat nfsproc3_rmdir_3 ()
bool_t nfsproc3_rmdir_3_svc ()
enum clnt_stat nfsproc3_rename_3 ()
bool_t nfsproc3_rename_3_svc ()
enum clnt_stat nfsproc3_link_3 ()
bool_t nfsproc3_link_3_svc ()
enum clnt_stat nfsproc3_readdir_3 ()
bool_t nfsproc3_readdir_3_svc ()
enum clnt_stat nfsproc3_readdirplus_3 ()
bool_t nfsproc3_readdirplus_3_svc ()
enum clnt_stat nfsproc3_fsstat_3 ()
bool_t nfsproc3_fsstat_3_svc ()
enum clnt_stat nfsproc3_fsinfo_3 ()
bool_t nfsproc3_fsinfo_3_svc ()
enum clnt_stat nfsproc3_pathconf_3 ()
bool_t nfsproc3_pathconf_3_svc ()
enum clnt_stat nfsproc3_commit_3 ()
bool_t nfsproc3_commit_3_svc ()
int nfs_program_3_freeresult ()
bool_t xdr_uint64 ()
bool_t xdr_int64 ()
bool_t xdr_uint32 ()
bool_t xdr_int32 ()
bool_t xdr_filename3 ()
bool_t xdr_nfspath3 ()
bool_t xdr_cookieverf3 ()
bool_t xdr_createverf3 ()
bool_t xdr_writeverf3 ()
bool_t xdr_nfsstat3 ()
bool_t xdr_ftype3 ()
bool_t xdr_specdata3 ()
bool_t xdr_nfstime3 ()
bool_t xdr_fattr3 ()
bool_t xdr_post_op_attr ()
bool_t xdr_wcc_attr ()
bool_t xdr_pre_op_attr ()
bool_t xdr_wcc_data ()
bool_t xdr_post_op_fh3 ()
bool_t xdr_set_uint32 ()
bool_t xdr_set_uint64 ()
bool_t xdr_time_how ()
bool_t xdr_set_time ()
bool_t xdr_sattr3 ()
bool_t xdr_diropargs3 ()
bool_t xdr_diropres3ok ()
bool_t xdr_diropres3 ()
bool_t xdr_wccstat3 ()
bool_t xdr_getattr3res ()
bool_t xdr_sattrguard3 ()
bool_t xdr_setattr3args ()
bool_t xdr_lookup3resok ()
bool_t xdr_lookup3res ()
bool_t xdr_access3args ()
bool_t xdr_access3resok ()
bool_t xdr_access3res ()
bool_t xdr_readlink3resok ()
bool_t xdr_readlink3res ()
bool_t xdr_read3args ()
bool_t xdr_read3resok ()
bool_t xdr_read3res ()
bool_t xdr_stable_how ()
bool_t xdr_write3args ()
bool_t xdr_write3resok ()
bool_t xdr_write3res ()
bool_t xdr_createmode3 ()
bool_t xdr_createhow3 ()
bool_t xdr_create3args ()
bool_t xdr_mkdir3args ()
bool_t xdr_symlinkdata3 ()
bool_t xdr_symlink3args ()
bool_t xdr_devicedata3 ()
bool_t xdr_mknoddata3 ()
bool_t xdr_mknod3args ()
bool_t xdr_rename3args ()
bool_t xdr_rename3wcc ()
bool_t xdr_rename3res ()
bool_t xdr_link3args ()
bool_t xdr_link3wcc ()
bool_t xdr_link3res ()
bool_t xdr_readdir3args ()
bool_t xdr_entry3 ()
bool_t xdr_dirlist3 ()
bool_t xdr_readdir3resok ()
bool_t xdr_readdir3res ()
bool_t xdr_readdirplus3args ()
bool_t xdr_entryplus3 ()
bool_t xdr_dirlistplus3 ()
bool_t xdr_readdirplus3resok ()
bool_t xdr_readdirplus3res ()
bool_t xdr_fsstat3resok ()
bool_t xdr_fsstat3res ()
bool_t xdr_fsinfo3resok ()
bool_t xdr_fsinfo3res ()
bool_t xdr_pathconf3resok ()
bool_t xdr_pathconf3res ()
bool_t xdr_commit3args ()
bool_t xdr_commit3resok ()
bool_t xdr_commit3res ()
CLIENT * create_connection_mount3 (char *name, int type)
void close_connection_mount3 (CLIENT *cl)
int nfs3_mount (char *dir, fhandle3 *fhand, CLIENT *cl)
int nfs3_umount (char *path, CLIENT *cl)
int nfs3_export (exports3 *, CLIENT *cl)
CLIENT * create_connection_nfs3 (char *name, int type)
void close_connection_nfs3 (CLIENT *cl)
int nfs3_getattr (fhandle3 *fh, fattr3 *fatt, CLIENT *cl)
int nfs3_setattr (fhandle3 *fh, fattr3 *fatt, CLIENT *cl)
int nfs3_lookup (fhandle3 *fhin, char *path, fhandle3 *fhout, fattr3 *att, CLIENT *cl)
ssize_t nfs3_read (fhandle3 *fh, void *data, off_t offset, size_t size, CLIENT *cl)
ssize_t nfs3_write (fhandle3 *fh, void *data, off_t offset, size_t size, CLIENT *cl)
int nfs3_create (fhandle3 *fhin, char *file, mode_t mode, fhandle3 *fhout, fattr3 *at, CLIENT *cl)
int nfs3_remove (fhandle3 *fh, char *file, CLIENT *cl)
int nfs3_rename (fhandle3 *fh, char *name, fhandle3 *fhR, char *nameR, CLIENT *cl)
int nfs3_mkdir (fhandle3 *fhin, char *dir, mode_t mode, fhandle3 *fhout, fattr3 *att, CLIENT *cl)
int nfs3_rmdir (fhandle3 *fh, char *dir, CLIENT *cl)
int nfs3_readdir (fhandle3 *fh, cookieverf3 cookie, char *entry, CLIENT *cl)
int nfs3_statfs (fhandle3 *arg, fsinfo3resok *inf, CLIENT *cl)
Macro Definition Documentation
ACCESS3_DELETE
#define ACCESS3_DELETE 0x0010
Definition at line 487 of file nfs3.h.
ACCESS3_EXECUTE
#define ACCESS3_EXECUTE 0x0020
Definition at line 488 of file nfs3.h.
ACCESS3_EXTEND
#define ACCESS3_EXTEND 0x0008
Definition at line 486 of file nfs3.h.
ACCESS3_LOOKUP
#define ACCESS3_LOOKUP 0x0002
Definition at line 484 of file nfs3.h.
ACCESS3_MODIFY
#define ACCESS3_MODIFY 0x0004
Definition at line 485 of file nfs3.h.
ACCESS3_READ
#define ACCESS3_READ 0x0001
Definition at line 483 of file nfs3.h.
FHSIZE3
#define FHSIZE3 64
Definition at line 30 of file nfs3.h.
FSF3_CANSETTIME
#define FSF3_CANSETTIME 0x0010
Definition at line 844 of file nfs3.h.
FSF3_HOMOGENEOUS
#define FSF3_HOMOGENEOUS 0x0008
Definition at line 843 of file nfs3.h.
FSF3_LINK
#define FSF3_LINK 0x0001
Definition at line 841 of file nfs3.h.
FSF3_SYMLINK
#define FSF3_SYMLINK 0x0002
Definition at line 842 of file nfs3.h.
MAXDATA3
#define MAXDATA3 (1024 * 32)
Definition at line 27 of file nfs3.h.
MNTNAMLEN
#define MNTNAMLEN 255
Definition at line 29 of file nfs3.h.
MNTPATHLEN
#define MNTPATHLEN 1024
Definition at line 28 of file nfs3.h.
MOUNT3_PROGRAM
#define MOUNT3_PROGRAM 100005
Definition at line 107 of file nfs3.h.
MOUNT3_VERSION
#define MOUNT3_VERSION 3
Definition at line 108 of file nfs3.h.
MOUNTPROC3_DUMP
#define MOUNTPROC3_DUMP 2
Definition at line 138 of file nfs3.h.
MOUNTPROC3_EXPORT
#define MOUNTPROC3_EXPORT 5
Definition at line 147 of file nfs3.h.
MOUNTPROC3_MNT
#define MOUNTPROC3_MNT 1
Definition at line 135 of file nfs3.h.
MOUNTPROC3_NULL
#define MOUNTPROC3_NULL 0
Definition at line 132 of file nfs3.h.
MOUNTPROC3_UMNT
#define MOUNTPROC3_UMNT 3
Definition at line 141 of file nfs3.h.
MOUNTPROC3_UMNTALL
#define MOUNTPROC3_UMNTALL 4
Definition at line 144 of file nfs3.h.
NFS3_COOKIEVERFSIZE
#define NFS3_COOKIEVERFSIZE 8
Definition at line 204 of file nfs3.h.
NFS3_CREATEVERFSIZE
#define NFS3_CREATEVERFSIZE 8
Definition at line 205 of file nfs3.h.
NFS3_FHSIZE
#define NFS3_FHSIZE FHSIZE3
Definition at line 203 of file nfs3.h.
NFS3_PROGRAM
#define NFS3_PROGRAM 100003
Definition at line 922 of file nfs3.h.
NFS3_RECVSZ
#define NFS3_RECVSZ (unsigned int)(128 * 1024)
Definition at line 18 of file nfs3.h.
NFS3_SENDSZ
#define NFS3_SENDSZ (unsigned int)(128 * 1024)
Definition at line 16 of file nfs3.h.
NFS3_TCP
#define NFS3_TCP 1
Definition at line 12 of file nfs3.h.
NFS3_UDP
#define NFS3_UDP 0
Definition at line 13 of file nfs3.h.
NFS3_VERSION
#define NFS3_VERSION 3
Definition at line 923 of file nfs3.h.
NFS3_WRITEVERFSIZE
#define NFS3_WRITEVERFSIZE 8
Definition at line 206 of file nfs3.h.
NFS3ERR_EOFDIR
#define NFS3ERR_EOFDIR -10011
Definition at line 25 of file nfs3.h.
NFSPROC3_ACCESS
#define NFSPROC3_ACCESS 4
Definition at line 1007 of file nfs3.h.
NFSPROC3_COMMIT
#define NFSPROC3_COMMIT 21
Definition at line 1058 of file nfs3.h.
NFSPROC3_CREATE
#define NFSPROC3_CREATE 8
Definition at line 1019 of file nfs3.h.
NFSPROC3_FSINFO
#define NFSPROC3_FSINFO 19
Definition at line 1052 of file nfs3.h.
NFSPROC3_FSSTAT
#define NFSPROC3_FSSTAT 18
Definition at line 1049 of file nfs3.h.
NFSPROC3_GETATTR
#define NFSPROC3_GETATTR 1
Definition at line 998 of file nfs3.h.
NFSPROC3_LINK
#define NFSPROC3_LINK 15
Definition at line 1040 of file nfs3.h.
NFSPROC3_LOOKUP
#define NFSPROC3_LOOKUP 3
Definition at line 1004 of file nfs3.h.
NFSPROC3_MKDIR
#define NFSPROC3_MKDIR 9
Definition at line 1022 of file nfs3.h.
NFSPROC3_MKNOD
#define NFSPROC3_MKNOD 11
Definition at line 1028 of file nfs3.h.
NFSPROC3_NULL
#define NFSPROC3_NULL 0
Definition at line 995 of file nfs3.h.
NFSPROC3_PATHCONF
#define NFSPROC3_PATHCONF 20
Definition at line 1055 of file nfs3.h.
NFSPROC3_READ
#define NFSPROC3_READ 6
Definition at line 1013 of file nfs3.h.
NFSPROC3_READDIR
#define NFSPROC3_READDIR 16
Definition at line 1043 of file nfs3.h.
NFSPROC3_READDIRPLUS
#define NFSPROC3_READDIRPLUS 17
Definition at line 1046 of file nfs3.h.
NFSPROC3_READLINK
#define NFSPROC3_READLINK 5
Definition at line 1010 of file nfs3.h.
NFSPROC3_REMOVE
#define NFSPROC3_REMOVE 12
Definition at line 1031 of file nfs3.h.
NFSPROC3_RENAME
#define NFSPROC3_RENAME 14
Definition at line 1037 of file nfs3.h.
NFSPROC3_RMDIR
#define NFSPROC3_RMDIR 13
Definition at line 1034 of file nfs3.h.
NFSPROC3_SETATTR
#define NFSPROC3_SETATTR 2
Definition at line 1001 of file nfs3.h.
NFSPROC3_SYMLINK
#define NFSPROC3_SYMLINK 10
Definition at line 1025 of file nfs3.h.
NFSPROC3_WRITE
#define NFSPROC3_WRITE 7
Definition at line 1016 of file nfs3.h.
Typedef Documentation
access3args
typedef struct access3args access3args
Definition at line 495 of file nfs3.h.
access3res
typedef struct access3res access3res
Definition at line 513 of file nfs3.h.
access3resok
typedef struct access3resok access3resok
Definition at line 502 of file nfs3.h.
commit3args
typedef struct commit3args commit3args
Definition at line 902 of file nfs3.h.
commit3res
typedef struct commit3res commit3res
Definition at line 920 of file nfs3.h.
commit3resok
typedef struct commit3resok commit3resok
Definition at line 909 of file nfs3.h.
cookieverf3
typedef char cookieverf3[NFS3_COOKIEVERFSIZE]
Definition at line 212 of file nfs3.h.
create3args
typedef struct create3args create3args
Definition at line 631 of file nfs3.h.
createhow3
typedef struct createhow3 createhow3
Definition at line 624 of file nfs3.h.
createmode3
typedef enum createmode3 createmode3
Definition at line 613 of file nfs3.h.
createverf3
typedef char createverf3[NFS3_CREATEVERFSIZE]
Definition at line 214 of file nfs3.h.
devicedata3
typedef struct devicedata3 devicedata3
Definition at line 659 of file nfs3.h.
dirlist3
typedef struct dirlist3 dirlist3
Definition at line 750 of file nfs3.h.
dirlistplus3
typedef struct dirlistplus3 dirlistplus3
Definition at line 797 of file nfs3.h.
diropargs3
typedef struct diropargs3 diropargs3
Definition at line 406 of file nfs3.h.
diropres3
typedef struct diropres3 diropres3
Definition at line 425 of file nfs3.h.
diropres3ok
typedef struct diropres3ok diropres3ok
Definition at line 414 of file nfs3.h.
entry3
typedef struct entry3 entry3
Definition at line 743 of file nfs3.h.
entryplus3
typedef struct entryplus3 entryplus3
Definition at line 790 of file nfs3.h.
exportnode3
typedef struct exportnode3 exportnode3
Definition at line 105 of file nfs3.h.
exports3
typedef struct exportnode3* exports3
Definition at line 97 of file nfs3.h.
fattr3
typedef struct fattr3 fattr3
Definition at line 305 of file nfs3.h.
filename3
typedef char* filename3
Definition at line 208 of file nfs3.h.
fsinfo3res
typedef struct fsinfo3res fsinfo3res
Definition at line 871 of file nfs3.h.
fsinfo3resok
typedef struct fsinfo3resok fsinfo3resok
Definition at line 860 of file nfs3.h.
fsstat3res
typedef struct fsstat3res fsstat3res
Definition at line 840 of file nfs3.h.
fsstat3resok
typedef struct fsstat3resok fsstat3resok
Definition at line 829 of file nfs3.h.
ftype3
typedef enum ftype3 ftype3
Definition at line 264 of file nfs3.h.
getattr3res
typedef struct getattr3res getattr3res
Definition at line 445 of file nfs3.h.
groupnode3
typedef struct groupnode3 groupnode3
Definition at line 95 of file nfs3.h.
groups3
typedef struct groupnode3* groups3
Definition at line 88 of file nfs3.h.
int32
typedef int int32
Definition at line 202 of file nfs3.h.
int64
typedef int64_t int64
Definition at line 198 of file nfs3.h.
link3args
typedef struct link3args link3args
Definition at line 708 of file nfs3.h.
link3res
typedef struct link3res link3res
Definition at line 725 of file nfs3.h.
link3wcc
typedef struct link3wcc link3wcc
Definition at line 715 of file nfs3.h.
lookup3res
typedef struct lookup3res lookup3res
Definition at line 482 of file nfs3.h.
lookup3resok
typedef struct lookup3resok lookup3resok
Definition at line 471 of file nfs3.h.
mkdir3args
typedef struct mkdir3args mkdir3args
Definition at line 638 of file nfs3.h.
mknod3args
typedef struct mknod3args mknod3args
Definition at line 677 of file nfs3.h.
mknoddata3
typedef struct mknoddata3 mknoddata3
Definition at line 670 of file nfs3.h.
mountbody3
typedef struct mountbody3 mountbody3
Definition at line 86 of file nfs3.h.
mountlist3
typedef struct mountbody3* mountlist3
Definition at line 78 of file nfs3.h.
mountres3
typedef struct mountres3 mountres3
Definition at line 76 of file nfs3.h.
mountres3_ok
typedef struct mountres3_ok mountres3_ok
Definition at line 66 of file nfs3.h.
mountstat3
typedef enum mountstat3 mountstat3
Definition at line 55 of file nfs3.h.
nfs3_dirpath
typedef char* nfs3_dirpath
Definition at line 38 of file nfs3.h.
nfs3_name
typedef char* nfs3_name
Definition at line 40 of file nfs3.h.
nfspath3
typedef char* nfspath3
Definition at line 210 of file nfs3.h.
nfsstat3
typedef enum nfsstat3 nfsstat3
Definition at line 252 of file nfs3.h.
nfstime3
typedef struct nfstime3 nfstime3
Definition at line 287 of file nfs3.h.
pathconf3res
typedef struct pathconf3res pathconf3res
Definition at line 894 of file nfs3.h.
pathconf3resok
typedef struct pathconf3resok pathconf3resok
Definition at line 883 of file nfs3.h.
post_op_attr
typedef struct post_op_attr post_op_attr
Definition at line 315 of file nfs3.h.
post_op_fh3
typedef struct post_op_fh3 post_op_fh3
Definition at line 350 of file nfs3.h.
pre_op_attr
typedef struct pre_op_attr pre_op_attr
Definition at line 333 of file nfs3.h.
read3args
typedef struct read3args read3args
Definition at line 539 of file nfs3.h.
read3res
typedef struct read3res read3res
Definition at line 563 of file nfs3.h.
read3resok
typedef struct read3resok read3resok
Definition at line 552 of file nfs3.h.
readdir3args
typedef struct readdir3args readdir3args
Definition at line 734 of file nfs3.h.
readdir3res
typedef struct readdir3res readdir3res
Definition at line 769 of file nfs3.h.
readdir3resok
typedef struct readdir3resok readdir3resok
Definition at line 758 of file nfs3.h.
readdirplus3args
typedef struct readdirplus3args readdirplus3args
Definition at line 779 of file nfs3.h.
readdirplus3res
typedef struct readdirplus3res readdirplus3res
Definition at line 816 of file nfs3.h.
readdirplus3resok
typedef struct readdirplus3resok readdirplus3resok
Definition at line 805 of file nfs3.h.
readlink3res
typedef struct readlink3res readlink3res
Definition at line 531 of file nfs3.h.
readlink3resok
typedef struct readlink3resok readlink3resok
Definition at line 520 of file nfs3.h.
rename3args
typedef struct rename3args rename3args
Definition at line 684 of file nfs3.h.
rename3res
typedef struct rename3res rename3res
Definition at line 701 of file nfs3.h.
rename3wcc
typedef struct rename3wcc rename3wcc
Definition at line 691 of file nfs3.h.
sattr3
typedef struct sattr3 sattr3
Definition at line 399 of file nfs3.h.
sattrguard3
typedef struct sattrguard3 sattrguard3
Definition at line 455 of file nfs3.h.
set_time
typedef struct set_time set_time
Definition at line 388 of file nfs3.h.
set_uint32
typedef struct set_uint32 set_uint32
Definition at line 360 of file nfs3.h.
set_uint64
typedef struct set_uint64 set_uint64
Definition at line 370 of file nfs3.h.
setattr3args
typedef struct setattr3args setattr3args
Definition at line 463 of file nfs3.h.
specdata3
typedef struct specdata3 specdata3
Definition at line 271 of file nfs3.h.
stable_how
typedef enum stable_how stable_how
Definition at line 571 of file nfs3.h.
symlink3args
typedef struct symlink3args symlink3args
Definition at line 652 of file nfs3.h.
symlinkdata3
typedef struct symlinkdata3 symlinkdata3
Definition at line 645 of file nfs3.h.
time_how
typedef enum time_how time_how
Definition at line 378 of file nfs3.h.
uint32
typedef u_int uint32
Definition at line 200 of file nfs3.h.
uint64
typedef uint64_t uint64
Definition at line 196 of file nfs3.h.
wcc_attr
typedef struct wcc_attr wcc_attr
Definition at line 323 of file nfs3.h.
wcc_data
typedef struct wcc_data wcc_data
Definition at line 340 of file nfs3.h.
wccstat3
typedef struct wccstat3 wccstat3
Definition at line 435 of file nfs3.h.
write3args
typedef struct write3args write3args
Definition at line 585 of file nfs3.h.
write3res
typedef struct write3res write3res
Definition at line 605 of file nfs3.h.
write3resok
typedef struct write3resok write3resok
Definition at line 594 of file nfs3.h.
writeverf3
typedef char writeverf3[NFS3_WRITEVERFSIZE]
Definition at line 216 of file nfs3.h.
Enumeration Type Documentation
createmode3
enum createmode3
Enumerator
UNCHECKED
GUARDED
EXCLUSIVE
Definition at line 607 of file nfs3.h.
ftype3
enum ftype3
Enumerator
NF3REG
NF3DIR
NF3BLK
NF3CHR
NF3LNK
NF3SOCK
NF3FIFO
Definition at line 254 of file nfs3.h.
mountstat3
enum mountstat3
Enumerator
MNT3_OK
MNT3ERR_PERM
MNT3ERR_NOENT
MNT3ERR_IO
MNT3ERR_ACCES
MNT3ERR_NOTDIR
MNT3ERR_INVAL
MNT3ERR_NAMETOOLONG
MNT3ERR_NOTSUPP
MNT3ERR_SERVERFAULT
Definition at line 42 of file nfs3.h.
nfsstat3
enum nfsstat3
Enumerator
NFS3_OK
NFS3ERR_PERM
NFS3ERR_NOENT
NFS3ERR_IO
NFS3ERR_NXIO
NFS3ERR_ACCES
NFS3ERR_EXIST
NFS3ERR_XDEV
NFS3ERR_NODEV
NFS3ERR_NOTDIR
NFS3ERR_ISDIR
NFS3ERR_INVAL
NFS3ERR_FBIG
NFS3ERR_NOSPC
NFS3ERR_ROFS
NFS3ERR_MLINK
NFS3ERR_NAMETOOLONG
NFS3ERR_NOTEMPTY
NFS3ERR_DQUOT
NFS3ERR_STALE
NFS3ERR_REMOTE
NFS3ERR_BADHANDLE
NFS3ERR_NOT_SYNC
NFS3ERR_BAD_COOKIE
NFS3ERR_NOTSUPP
NFS3ERR_TOOSMALL
NFS3ERR_SERVERFAULT
NFS3ERR_BADTYPE
NFS3ERR_JUKEBOX
NFS3ERR_FPRINTNOTFOUND
NFS3ERR_ABORTED
Definition at line 218 of file nfs3.h.
stable_how
enum stable_how
Enumerator
UNSTABLE
DATA_SYNC
FILE_SYNC
Definition at line 565 of file nfs3.h.
time_how
enum time_how
Enumerator
DONT_CHANGE
SET_TO_SERVER_TIME
SET_TO_CLIENT_TIME
Definition at line 372 of file nfs3.h.
Function Documentation
close_connection_mount3()
void close_connection_mount3 (CLIENT * cl)
Definition at line 180 of file nfs3.c.
Referenced by create_connection_mount3(), nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs3_init(), and nfi_nfs3_reconnect().
close_connection_nfs3()
void close_connection_nfs3 (CLIENT * cl)
Definition at line 492 of file nfs3.c.
Referenced by create_connection_nfs3(), nfi_nfs3_destroy(), nfi_nfs3_disconnect(), and nfi_nfs3_init().
create_connection_mount3()
CLIENT * create_connection_mount3 (char * name, int type)
Definition at line 76 of file nfs3.c.
References close_connection_mount3(), MNTNAMLEN, MOUNT3_PROGRAM, MOUNT3_VERSION, NFS3_RECVSZ, NFS3_SENDSZ, NFS3_TCP, and NFS3_UDP.
Referenced by nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs3_init(), and nfi_nfs3_reconnect().
create_connection_nfs3()
CLIENT * create_connection_nfs3 (char * name, int type)
Definition at line 390 of file nfs3.c.
References close_connection_nfs3(), MNTNAMLEN, NFS3_PROGRAM, NFS3_RECVSZ, NFS3_SENDSZ, NFS3_TCP, NFS3_UDP, and NFS3_VERSION.
Referenced by nfi_nfs3_init(), and nfi_nfs3_reconnect().
mount_program_3_freeresult()
int mount_program_3_freeresult ()
mountproc3_dump_3()
enum clnt_stat mountproc3_dump_3 ()
mountproc3_dump_3_svc()
bool_t mountproc3_dump_3_svc ()
mountproc3_export_3()
enum clnt_stat mountproc3_export_3 ()
mountproc3_export_3_svc()
bool_t mountproc3_export_3_svc ()
mountproc3_mnt_3()
enum clnt_stat mountproc3_mnt_3 ()
Referenced by nfs3_mount().
mountproc3_mnt_3_svc()
bool_t mountproc3_mnt_3_svc ()
mountproc3_null_3()
enum clnt_stat mountproc3_null_3 ()
mountproc3_null_3_svc()
bool_t mountproc3_null_3_svc ()
mountproc3_umnt_3()
enum clnt_stat mountproc3_umnt_3 ()
Referenced by nfs3_umount().
mountproc3_umnt_3_svc()
bool_t mountproc3_umnt_3_svc ()
mountproc3_umntall_3()
enum clnt_stat mountproc3_umntall_3 ()
mountproc3_umntall_3_svc()
bool_t mountproc3_umntall_3_svc ()
nfs3_create()
int nfs3_create (fhandle3 * fhin, char * file, mode_t mode, fhandle3 * fhout, fattr3 * at, CLIENT * cl)
nfs3_export()
int nfs3_export (exports3 * , CLIENT * cl)
nfs3_getattr()
int nfs3_getattr (fhandle3 * fh, fattr3 * fatt, CLIENT * cl)
Definition at line 614 of file nfs3.c.
References getattr3res::attributes, getattr3res::getattr3res_u, NFS3_OK, nfsproc3_getattr_3(), and getattr3res::status.
Referenced by nfi_nfs3_getattr().
nfs3_lookup()
int nfs3_lookup (fhandle3 * fhin, char * path, fhandle3 * fhout, fattr3 * att, CLIENT * cl)
Definition at line 676 of file nfs3.c.
References post_op_attr::attributes, diropargs3::dir, fhandle3::fhandle3_len, fhandle3::fhandle3_val, FHSIZE3, getFirstDir(), lookup3res::lookup3res_u, MNTNAMLEN, diropargs3::name, nfsproc3_lookup_3(), lookup3resok::obj_attributes, lookup3resok::object, post_op_attr::post_op_attr_u, post_op_attr::present, lookup3res::resok, lookup3res::status, and fattr3::type.
Referenced by nfi_nfs3_create(), nfi_nfs3_mkdir(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), and nfs3_open().
nfs3_mkdir()
int nfs3_mkdir (fhandle3 * fhin, char * dir, mode_t mode, fhandle3 * fhout, fattr3 * att, CLIENT * cl)
nfs3_mount()
int nfs3_mount (char * dir, fhandle3 * fhand, CLIENT * cl)
Definition at line 223 of file nfs3.c.
References mountres3_ok::auth_flavors, mountres3_ok::auth_flavors_len, mountres3_ok::auth_flavors_val, mountres3_ok::fhandle, fhandle3::fhandle3_len, fhandle3::fhandle3_val, mountres3::fhs_status, FHSIZE3, mountres3::mountinfo, mountproc3_mnt_3(), and mountres3::mountres3_u.
Referenced by nfi_nfs3_init(), and nfi_nfs3_reconnect().
nfs3_read()
ssize_t nfs3_read (fhandle3 * fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 814 of file nfs3.c.
References read3args::count, read3resok::data, read3resok::data_len, read3resok::data_val, fhandle3::fhandle3_len, fhandle3::fhandle3_val, read3args::file, MAXDATA3, nfsproc3_read_3(), read3args::offset, read3res::read3res_u, read3res::resok, and read3res::status.
Referenced by nfi_nfs3_read().
nfs3_readdir()
int nfs3_readdir (fhandle3 * fh, cookieverf3 cookie, char * entry, CLIENT * cl)
nfs3_remove()
int nfs3_remove (fhandle3 * fh, char * file, CLIENT * cl)
Definition at line 1134 of file nfs3.c.
References diropargs3::dir, fhandle3::fhandle3_len, fhandle3::fhandle3_val, diropargs3::name, nfsproc3_remove_3(), and wccstat3::status.
Referenced by nfi_nfs3_remove().
nfs3_rename()
int nfs3_rename (fhandle3 * fh, char * name, fhandle3 * fhR, char * nameR, CLIENT * cl)
nfs3_rmdir()
int nfs3_rmdir (fhandle3 * fh, char * dir, CLIENT * cl)
nfs3_setattr()
int nfs3_setattr (fhandle3 * fh, fattr3 * fatt, CLIENT * cl)
Definition at line 555 of file nfs3.c.
References fattr3::atime, sattr3::atime, fattr3::gid, sattr3::gid, fattr3::mode, sattr3::mode, fattr3::mtime, sattr3::mtime, setattr3args::new_attributes, NFS3_FHSIZE, NFS3_OK, nfsproc3_setattr_3(), setattr3args::object, set_time::set_time_u, set_uint32::set_uint32_u, set_uint64::set_uint64_u, fattr3::size, sattr3::size, wccstat3::status, set_time::time, fattr3::uid, sattr3::uid, set_uint32::val, and set_uint64::val.
Referenced by nfi_nfs3_setattr().
nfs3_statfs()
int nfs3_statfs (fhandle3 * arg, fsinfo3resok * inf, CLIENT * cl)
nfs3_umount()
int nfs3_umount (char * path, CLIENT * cl)
Definition at line 320 of file nfs3.c.
References mountproc3_umnt_3().
Referenced by nfi_nfs3_destroy(), and nfi_nfs3_disconnect().
nfs3_write()
ssize_t nfs3_write (fhandle3 * fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 929 of file nfs3.c.
References write3args::count, write3args::data, write3args::data_len, DATA_SYNC, write3args::data_val, fhandle3::fhandle3_len, fhandle3::fhandle3_val, write3args::file, FILE_SYNC, MAXDATA3, nfsproc3_write_3(), write3args::offset, printfh3(), write3args::stable, write3res::status, and UNSTABLE.
Referenced by nfi_nfs3_write().
nfs_program_3_freeresult()
int nfs_program_3_freeresult ()
nfsproc3_access_3()
enum clnt_stat nfsproc3_access_3 ()
nfsproc3_access_3_svc()
bool_t nfsproc3_access_3_svc ()
nfsproc3_commit_3()
enum clnt_stat nfsproc3_commit_3 ()
nfsproc3_commit_3_svc()
bool_t nfsproc3_commit_3_svc ()
nfsproc3_create_3()
enum clnt_stat nfsproc3_create_3 ()
Referenced by nfs3_create().
nfsproc3_create_3_svc()
bool_t nfsproc3_create_3_svc ()
nfsproc3_fsinfo_3()
enum clnt_stat nfsproc3_fsinfo_3 ()
nfsproc3_fsinfo_3_svc()
bool_t nfsproc3_fsinfo_3_svc ()
nfsproc3_fsstat_3()
enum clnt_stat nfsproc3_fsstat_3 ()
nfsproc3_fsstat_3_svc()
bool_t nfsproc3_fsstat_3_svc ()
nfsproc3_getattr_3()
enum clnt_stat nfsproc3_getattr_3 ()
Referenced by nfs3_getattr().
nfsproc3_getattr_3_svc()
bool_t nfsproc3_getattr_3_svc ()
nfsproc3_link_3()
enum clnt_stat nfsproc3_link_3 ()
nfsproc3_link_3_svc()
bool_t nfsproc3_link_3_svc ()
nfsproc3_lookup_3()
enum clnt_stat nfsproc3_lookup_3 ()
Referenced by nfs3_lookup().
nfsproc3_lookup_3_svc()
bool_t nfsproc3_lookup_3_svc ()
nfsproc3_mkdir_3()
enum clnt_stat nfsproc3_mkdir_3 ()
nfsproc3_mkdir_3_svc()
bool_t nfsproc3_mkdir_3_svc ()
nfsproc3_mknod_3()
enum clnt_stat nfsproc3_mknod_3 ()
nfsproc3_mknod_3_svc()
bool_t nfsproc3_mknod_3_svc ()
nfsproc3_null_3()
enum clnt_stat nfsproc3_null_3 ()
nfsproc3_null_3_svc()
bool_t nfsproc3_null_3_svc ()
nfsproc3_pathconf_3()
enum clnt_stat nfsproc3_pathconf_3 ()
nfsproc3_pathconf_3_svc()
bool_t nfsproc3_pathconf_3_svc ()
nfsproc3_read_3()
enum clnt_stat nfsproc3_read_3 ()
Referenced by nfs3_read().
nfsproc3_read_3_svc()
bool_t nfsproc3_read_3_svc ()
nfsproc3_readdir_3()
enum clnt_stat nfsproc3_readdir_3 ()
nfsproc3_readdir_3_svc()
bool_t nfsproc3_readdir_3_svc ()
nfsproc3_readdirplus_3()
enum clnt_stat nfsproc3_readdirplus_3 ()
nfsproc3_readdirplus_3_svc()
bool_t nfsproc3_readdirplus_3_svc ()
nfsproc3_readlink_3()
enum clnt_stat nfsproc3_readlink_3 ()
nfsproc3_readlink_3_svc()
bool_t nfsproc3_readlink_3_svc ()
nfsproc3_remove_3()
enum clnt_stat nfsproc3_remove_3 ()
Referenced by nfs3_remove().
nfsproc3_remove_3_svc()
bool_t nfsproc3_remove_3_svc ()
nfsproc3_rename_3()
enum clnt_stat nfsproc3_rename_3 ()
nfsproc3_rename_3_svc()
bool_t nfsproc3_rename_3_svc ()
nfsproc3_rmdir_3()
enum clnt_stat nfsproc3_rmdir_3 ()
nfsproc3_rmdir_3_svc()
bool_t nfsproc3_rmdir_3_svc ()
nfsproc3_setattr_3()
enum clnt_stat nfsproc3_setattr_3 ()
Referenced by nfs3_setattr().
nfsproc3_setattr_3_svc()
bool_t nfsproc3_setattr_3_svc ()
nfsproc3_symlink_3()
enum clnt_stat nfsproc3_symlink_3 ()
nfsproc3_symlink_3_svc()
bool_t nfsproc3_symlink_3_svc ()
nfsproc3_write_3()
enum clnt_stat nfsproc3_write_3 ()
Referenced by nfs3_write().
nfsproc3_write_3_svc()
bool_t nfsproc3_write_3_svc ()
xdr_access3args()
bool_t xdr_access3args ()
Referenced by nfsproc3_access_3().
xdr_access3res()
bool_t xdr_access3res ()
Referenced by nfsproc3_access_3().
xdr_access3resok()
bool_t xdr_access3resok ()
Referenced by xdr_access3res().
xdr_commit3args()
bool_t xdr_commit3args ()
Referenced by nfsproc3_commit_3().
xdr_commit3res()
bool_t xdr_commit3res ()
Referenced by nfsproc3_commit_3().
xdr_commit3resok()
bool_t xdr_commit3resok ()
Referenced by xdr_commit3res().
xdr_cookieverf3()
bool_t xdr_cookieverf3 ()
Referenced by xdr_readdir3args(), xdr_readdir3resok(), xdr_readdirplus3args(), and xdr_readdirplus3resok().
xdr_create3args()
bool_t xdr_create3args ()
Referenced by nfsproc3_create_3().
xdr_createhow3()
bool_t xdr_createhow3 ()
Referenced by xdr_create3args().
xdr_createmode3()
bool_t xdr_createmode3 ()
Referenced by xdr_createhow3().
xdr_createverf3()
bool_t xdr_createverf3 ()
Referenced by xdr_createhow3().
xdr_devicedata3()
bool_t xdr_devicedata3 ()
Referenced by xdr_mknoddata3().
xdr_dirlist3()
bool_t xdr_dirlist3 ()
Referenced by xdr_readdir3resok().
xdr_dirlistplus3()
bool_t xdr_dirlistplus3 ()
Referenced by xdr_readdirplus3resok().
xdr_diropargs3()
bool_t xdr_diropargs3 ()
Referenced by nfsproc3_lookup_3(), nfsproc3_remove_3(), nfsproc3_rmdir_3(), xdr_create3args(), xdr_link3args(), xdr_mkdir3args(), xdr_mknod3args(), xdr_rename3args(), and xdr_symlink3args().
xdr_diropres3()
bool_t xdr_diropres3 ()
Referenced by nfsproc3_create_3(), nfsproc3_mkdir_3(), nfsproc3_mknod_3(), and nfsproc3_symlink_3().
xdr_diropres3ok()
bool_t xdr_diropres3ok ()
Referenced by xdr_diropres3().
xdr_dirpath()
bool_t xdr_dirpath ()
xdr_entry3()
bool_t xdr_entry3 ()
Referenced by xdr_dirlist3(), and xdr_entry3().
xdr_entryplus3()
bool_t xdr_entryplus3 ()
Referenced by xdr_dirlistplus3(), and xdr_entryplus3().
xdr_exportnode3()
bool_t xdr_exportnode3 ()
Referenced by xdr_exports3().
xdr_exports3()
bool_t xdr_exports3 ()
Referenced by mountproc3_export_3(), and xdr_exportnode3().
xdr_fattr3()
bool_t xdr_fattr3 ()
Referenced by xdr_getattr3res(), and xdr_post_op_attr().
xdr_fhandle3()
bool_t xdr_fhandle3 ()
Referenced by nfsproc3_fsinfo_3(), nfsproc3_fsstat_3(), nfsproc3_getattr_3(), nfsproc3_pathconf_3(), nfsproc3_readlink_3(), xdr_access3args(), xdr_commit3args(), xdr_diropargs3(), xdr_link3args(), xdr_lookup3resok(), xdr_mountres3_ok(), xdr_post_op_fh3(), xdr_read3args(), xdr_readdir3args(), xdr_readdirplus3args(), xdr_setattr3args(), and xdr_write3args().
xdr_filename3()
bool_t xdr_filename3 ()
Referenced by xdr_diropargs3(), xdr_entry3(), xdr_entryplus3(), xdr_groupnode3(), and xdr_mountbody3().
xdr_fsinfo3res()
bool_t xdr_fsinfo3res ()
Referenced by nfsproc3_fsinfo_3().
xdr_fsinfo3resok()
bool_t xdr_fsinfo3resok ()
Referenced by xdr_fsinfo3res().
xdr_fsstat3res()
bool_t xdr_fsstat3res ()
Referenced by nfsproc3_fsstat_3().
xdr_fsstat3resok()
bool_t xdr_fsstat3resok ()
Referenced by xdr_fsstat3res().
xdr_ftype3()
bool_t xdr_ftype3 ()
Referenced by xdr_fattr3(), and xdr_mknoddata3().
xdr_getattr3res()
bool_t xdr_getattr3res ()
Referenced by nfsproc3_getattr_3().
xdr_groupnode3()
bool_t xdr_groupnode3 ()
Referenced by xdr_groups3().
xdr_groups3()
bool_t xdr_groups3 ()
Referenced by xdr_exportnode3(), and xdr_groupnode3().
xdr_int32()
bool_t xdr_int32 ()
xdr_int64()
bool_t xdr_int64 ()
xdr_link3args()
bool_t xdr_link3args ()
Referenced by nfsproc3_link_3().
xdr_link3res()
bool_t xdr_link3res ()
Referenced by nfsproc3_link_3().
xdr_link3wcc()
bool_t xdr_link3wcc ()
Referenced by xdr_link3res().
xdr_lookup3res()
bool_t xdr_lookup3res ()
Referenced by nfsproc3_lookup_3().
xdr_lookup3resok()
bool_t xdr_lookup3resok ()
Referenced by xdr_lookup3res().
xdr_mkdir3args()
bool_t xdr_mkdir3args ()
Referenced by nfsproc3_mkdir_3().
xdr_mknod3args()
bool_t xdr_mknod3args ()
Referenced by nfsproc3_mknod_3().
xdr_mknoddata3()
bool_t xdr_mknoddata3 ()
Referenced by xdr_mknod3args().
xdr_mountbody3()
bool_t xdr_mountbody3 ()
Referenced by xdr_mountlist3().
xdr_mountlist3()
bool_t xdr_mountlist3 ()
Referenced by mountproc3_dump_3(), and xdr_mountbody3().
xdr_mountres3()
bool_t xdr_mountres3 ()
Referenced by mountproc3_mnt_3().
xdr_mountres3_ok()
bool_t xdr_mountres3_ok ()
Referenced by xdr_mountres3().
xdr_mountstat3()
bool_t xdr_mountstat3 ()
Referenced by xdr_mountres3().
xdr_name()
bool_t xdr_name ()
xdr_nfspath3()
bool_t xdr_nfspath3 ()
Referenced by mountproc3_mnt_3(), mountproc3_umnt_3(), xdr_exportnode3(), xdr_mountbody3(), xdr_readlink3resok(), and xdr_symlinkdata3().
xdr_nfsstat3()
bool_t xdr_nfsstat3 ()
Referenced by xdr_access3res(), xdr_commit3res(), xdr_diropres3(), xdr_fsinfo3res(), xdr_fsstat3res(), xdr_getattr3res(), xdr_link3res(), xdr_lookup3res(), xdr_pathconf3res(), xdr_read3res(), xdr_readdir3res(), xdr_readdirplus3res(), xdr_readlink3res(), xdr_rename3res(), xdr_wccstat3(), and xdr_write3res().
xdr_nfstime3()
bool_t xdr_nfstime3 ()
Referenced by xdr_fattr3(), xdr_fsinfo3resok(), xdr_sattrguard3(), xdr_set_time(), and xdr_wcc_attr().
xdr_pathconf3res()
bool_t xdr_pathconf3res ()
Referenced by nfsproc3_pathconf_3().
xdr_pathconf3resok()
bool_t xdr_pathconf3resok ()
Referenced by xdr_pathconf3res().
xdr_post_op_attr()
bool_t xdr_post_op_attr ()
Referenced by xdr_access3res(), xdr_access3resok(), xdr_diropres3ok(), xdr_entryplus3(), xdr_fsinfo3res(), xdr_fsinfo3resok(), xdr_fsstat3res(), xdr_fsstat3resok(), xdr_link3wcc(), xdr_lookup3res(), xdr_lookup3resok(), xdr_pathconf3res(), xdr_pathconf3resok(), xdr_read3res(), xdr_read3resok(), xdr_readdir3res(), xdr_readdir3resok(), xdr_readdirplus3res(), xdr_readdirplus3resok(), xdr_readlink3res(), xdr_readlink3resok(), and xdr_wcc_data().
xdr_post_op_fh3()
bool_t xdr_post_op_fh3 ()
Referenced by xdr_diropres3ok(), and xdr_entryplus3().
xdr_pre_op_attr()
bool_t xdr_pre_op_attr ()
Referenced by xdr_wcc_data().
xdr_read3args()
bool_t xdr_read3args ()
Referenced by nfsproc3_read_3().
xdr_read3res()
bool_t xdr_read3res ()
Referenced by nfsproc3_read_3().
xdr_read3resok()
bool_t xdr_read3resok ()
Referenced by xdr_read3res().
xdr_readdir3args()
bool_t xdr_readdir3args ()
Referenced by nfsproc3_readdir_3().
xdr_readdir3res()
bool_t xdr_readdir3res ()
Referenced by nfsproc3_readdir_3().
xdr_readdir3resok()
bool_t xdr_readdir3resok ()
Referenced by xdr_readdir3res().
xdr_readdirplus3args()
bool_t xdr_readdirplus3args ()
Referenced by nfsproc3_readdirplus_3().
xdr_readdirplus3res()
bool_t xdr_readdirplus3res ()
Referenced by nfsproc3_readdirplus_3().
xdr_readdirplus3resok()
bool_t xdr_readdirplus3resok ()
Referenced by xdr_readdirplus3res().
xdr_readlink3res()
bool_t xdr_readlink3res ()
Referenced by nfsproc3_readlink_3().
xdr_readlink3resok()
bool_t xdr_readlink3resok ()
Referenced by xdr_readlink3res().
xdr_rename3args()
bool_t xdr_rename3args ()
Referenced by nfsproc3_rename_3().
xdr_rename3res()
bool_t xdr_rename3res ()
Referenced by nfsproc3_rename_3().
xdr_rename3wcc()
bool_t xdr_rename3wcc ()
Referenced by xdr_rename3res().
xdr_sattr3()
bool_t xdr_sattr3 ()
Referenced by xdr_createhow3(), xdr_devicedata3(), xdr_mkdir3args(), xdr_mknoddata3(), xdr_setattr3args(), and xdr_symlinkdata3().
xdr_sattrguard3()
bool_t xdr_sattrguard3 ()
Referenced by xdr_setattr3args().
xdr_set_time()
bool_t xdr_set_time ()
Referenced by xdr_sattr3().
xdr_set_uint32()
bool_t xdr_set_uint32 ()
Referenced by xdr_sattr3().
xdr_set_uint64()
bool_t xdr_set_uint64 ()
Referenced by xdr_sattr3().
xdr_setattr3args()
bool_t xdr_setattr3args ()
Referenced by nfsproc3_setattr_3().
xdr_specdata3()
bool_t xdr_specdata3 ()
Referenced by xdr_devicedata3(), and xdr_fattr3().
xdr_stable_how()
bool_t xdr_stable_how ()
Referenced by xdr_write3args(), and xdr_write3resok().
xdr_symlink3args()
bool_t xdr_symlink3args ()
Referenced by nfsproc3_symlink_3().
xdr_symlinkdata3()
bool_t xdr_symlinkdata3 ()
Referenced by xdr_symlink3args().
xdr_time_how()
bool_t xdr_time_how ()
Referenced by xdr_set_time().
xdr_uint32()
bool_t xdr_uint32 ()
Referenced by xdr_access3args(), xdr_access3resok(), xdr_commit3args(), xdr_fattr3(), xdr_fsinfo3resok(), xdr_fsstat3resok(), xdr_nfstime3(), xdr_pathconf3resok(), xdr_read3args(), xdr_read3resok(), xdr_readdir3args(), xdr_readdirplus3args(), xdr_set_uint32(), xdr_specdata3(), xdr_write3args(), and xdr_write3resok().
xdr_uint64()
bool_t xdr_uint64 ()
Referenced by xdr_commit3args(), xdr_entry3(), xdr_entryplus3(), xdr_fattr3(), xdr_fsinfo3resok(), xdr_fsstat3resok(), xdr_read3args(), xdr_readdir3args(), xdr_readdirplus3args(), xdr_set_uint64(), xdr_wcc_attr(), and xdr_write3args().
xdr_wcc_attr()
bool_t xdr_wcc_attr ()
Referenced by xdr_pre_op_attr().
xdr_wcc_data()
bool_t xdr_wcc_data ()
Referenced by xdr_commit3res(), xdr_commit3resok(), xdr_diropres3(), xdr_diropres3ok(), xdr_link3wcc(), xdr_rename3wcc(), xdr_wccstat3(), xdr_write3res(), and xdr_write3resok().
xdr_wccstat3()
bool_t xdr_wccstat3 ()
Referenced by nfsproc3_remove_3(), nfsproc3_rmdir_3(), and nfsproc3_setattr_3().
xdr_write3args()
bool_t xdr_write3args ()
Referenced by nfsproc3_write_3().
xdr_write3res()
bool_t xdr_write3res ()
Referenced by nfsproc3_write_3().
xdr_write3resok()
bool_t xdr_write3resok ()
Referenced by xdr_write3res().
xdr_writeverf3()
bool_t xdr_writeverf3 ()
Referenced by xdr_commit3resok(), and xdr_write3resok().