nfs.h File Reference
Header file to 'TODO'.
#include all_system.h
#include base/path_misc.h
Macros
#define NFS_TCP 1
#define NFS_UDP 0
#define SENDSZ (unsigned int)(128 * 1024)
#define RECVSZ (unsigned int)(128 * 1024)
#define MNTPATHLEN 1024
#define MNTNAMLEN 255
#define NFSPATHLEN MNTPATHLEN
#define FHSIZE 32
#define MOUNT1_PROGRAM ((u_long)100005)
#define MOUNT1_VERSION ((u_long)1)
#define NFS2_PROGRAM ((u_long)100003)
#define NFS2_VERSION ((u_long)2)
Functions
CLIENT * create_connection_mount (char *name, int type)
void close_connection_mount (CLIENT *cl)
int nfs_mount (char *dir, fhandle fhand, CLIENT *cl)
int nfs_umount (char *path, CLIENT *cl)
int nfs_export (exports *, CLIENT *cl)
CLIENT * create_connection_nfs (char *name, int type)
void close_connection_nfs (CLIENT *cl)
int nfs_getattr (fhandle fh, fattr *fatt, CLIENT *cl)
int nfs_setattr (fhandle fh, fattr *fatt, CLIENT *cl)
int nfs_lookup (fhandle fhin, char *path, fhandle fhout, fattr *att, CLIENT *cl)
ssize_t nfs_read (fhandle fh, void *data, off_t offset, size_t size, CLIENT *cl)
ssize_t nfs_write (fhandle fh, void *data, off_t offset, size_t size, CLIENT *cl)
int nfs_create (fhandle fhin, char *file, mode_t mode, fhandle fhout, fattr *at, CLIENT *cl)
int nfs_remove (fhandle fh, char *file, CLIENT *cl)
int nfs_rename (fhandle fh, char *name, fhandle fhR, char *nameR, CLIENT *cl)
int nfs_mkdir (fhandle fhin, char *dir, mode_t mode, fhandle fhout, fattr *att, CLIENT *cl)
int nfs_rmdir (fhandle fh, char *dir, CLIENT *cl)
int nfs_readdir (fhandle fh, nfscookie cookie, char *entry, CLIENT *cl)
int nfs_statfs (fhandle arg, struct nfs_info *inf, CLIENT *cl)
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfs.h.
Macro Definition Documentation
FHSIZE
#define FHSIZE 32
Definition at line 55 of file nfs.h.
MNTNAMLEN
#define MNTNAMLEN 255
Definition at line 50 of file nfs.h.
MNTPATHLEN
#define MNTPATHLEN 1024
Definition at line 49 of file nfs.h.
MOUNT1_PROGRAM
#define MOUNT1_PROGRAM ((u_long)100005)
Definition at line 58 of file nfs.h.
MOUNT1_VERSION
#define MOUNT1_VERSION ((u_long)1)
Definition at line 60 of file nfs.h.
NFS2_PROGRAM
#define NFS2_PROGRAM ((u_long)100003)
Definition at line 63 of file nfs.h.
NFS2_VERSION
#define NFS2_VERSION ((u_long)2)
Definition at line 65 of file nfs.h.
NFS_TCP
#define NFS_TCP 1
Definition at line 41 of file nfs.h.
NFS_UDP
#define NFS_UDP 0
Definition at line 42 of file nfs.h.
NFSPATHLEN
#define NFSPATHLEN MNTPATHLEN
Definition at line 52 of file nfs.h.
RECVSZ
#define RECVSZ (unsigned int)(128 * 1024)
Definition at line 47 of file nfs.h.
SENDSZ
#define SENDSZ (unsigned int)(128 * 1024)
Definition at line 45 of file nfs.h.
Function Documentation
close_connection_mount()
void close_connection_mount (CLIENT * cl)
Definition at line 207 of file nfs.c.
Referenced by create_connection_mount(), nfi_nfs_destroy(), nfi_nfs_disconnect(), nfi_nfs_init(), and nfi_nfs_reconnect().
close_connection_nfs()
void close_connection_nfs (CLIENT * cl)
Definition at line 500 of file nfs.c.
Referenced by create_connection_nfs(), nfi_nfs_destroy(), nfi_nfs_disconnect(), and nfi_nfs_init().
create_connection_mount()
CLIENT * create_connection_mount (char * name, int type)
Definition at line 103 of file nfs.c.
References close_connection_mount(), MNTNAMLEN, MOUNT1_PROGRAM, MOUNT1_VERSION, NFS_TCP, NFS_UDP, RECVSZ, and SENDSZ.
Referenced by nfi_nfs_destroy(), nfi_nfs_disconnect(), nfi_nfs_init(), and nfi_nfs_reconnect().
create_connection_nfs()
CLIENT * create_connection_nfs (char * name, int type)
Definition at line 401 of file nfs.c.
References close_connection_nfs(), MNTNAMLEN, NFS2_PROGRAM, NFS2_VERSION, NFS_TCP, NFS_UDP, RECVSZ, and SENDSZ.
Referenced by nfi_nfs_init(), and nfi_nfs_reconnect().
nfs_create()
int nfs_create (fhandle fhin, char * file, mode_t mode, fhandle fhout, fattr * at, CLIENT * cl)
Definition at line 1053 of file nfs.c.
References FHSIZE, printfh(), and setAttr().
Referenced by nfi_nfs_create().
nfs_export()
int nfs_export (exports * exp, CLIENT * cl)
Definition at line 354 of file nfs.c.
nfs_getattr()
int nfs_getattr (fhandle fh, fattr * fatt, CLIENT * cl)
Definition at line 631 of file nfs.c.
Referenced by nfi_nfs_getattr().
nfs_lookup()
int nfs_lookup (fhandle fhin, char * path, fhandle fhout, fattr * att, CLIENT * cl)
Definition at line 693 of file nfs.c.
References FHSIZE, getFirstDir(), MNTNAMLEN, and printfh().
Referenced by nfi_nfs_create(), nfi_nfs_mkdir(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), and nfs_open().
nfs_mkdir()
int nfs_mkdir (fhandle fhin, char * dir, mode_t mode, fhandle fhout, fattr * att, CLIENT * cl)
Definition at line 1262 of file nfs.c.
References FHSIZE, and setAttr().
Referenced by nfi_nfs_mkdir().
nfs_mount()
int nfs_mount (char * dir, fhandle fhand, CLIENT * cl)
Definition at line 241 of file nfs.c.
References FHSIZE, and printfh().
Referenced by nfi_nfs_init(), and nfi_nfs_reconnect().
nfs_read()
ssize_t nfs_read (fhandle fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 838 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_read().
nfs_readdir()
int nfs_readdir (fhandle fh, nfscookie cookie, char * entry, CLIENT * cl)
Definition at line 1408 of file nfs.c.
References FHSIZE, NFSMAXPATHLEN, and TRUE.
Referenced by nfi_nfs_readdir().
nfs_remove()
int nfs_remove (fhandle fh, char * file, CLIENT * cl)
Definition at line 1123 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_remove().
nfs_rename()
int nfs_rename (fhandle fh, char * name, fhandle fhR, char * nameR, CLIENT * cl)
Definition at line 1187 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_rename().
nfs_rmdir()
int nfs_rmdir (fhandle fh, char * dir, CLIENT * cl)
Definition at line 1336 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_rmdir().
nfs_setattr()
int nfs_setattr (fhandle fh, fattr * fatt, CLIENT * cl)
Definition at line 570 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_setattr().
nfs_statfs()
int nfs_statfs (fhandle arg, struct nfs_info * inf, CLIENT * cl)
Definition at line 1528 of file nfs.c.
Referenced by nfi_nfs_statfs().
nfs_umount()
int nfs_umount (char * path, CLIENT * cl)
Definition at line 307 of file nfs.c.
Referenced by nfi_nfs_destroy(), and nfi_nfs_disconnect().
nfs_write()
ssize_t nfs_write (fhandle fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 952 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_write().