nfs.c File Reference
File to 'TODO'.
#include nfi/nfi_nfs/nfs.h
Functions
void printfh (fhandle fh)
CLIENT * create_connection_mount (char *name, int type)
void close_connection_mount (CLIENT *cl)
int nfs_mount (char *dir, fhandle fhand, CLIENT *cli)
int nfs_umount (char *path, CLIENT *cli)
int nfs_export (exports *exp, CLIENT *cli)
CLIENT * create_connection_nfs (char *name, int type)
void close_connection_nfs (CLIENT *cl)
void setDate (timevalNfs *t)
void setAttr (sattr *at, unsigned int mode)
int nfs_setattr (fhandle fh, fattr *fatt, CLIENT *cl)
int nfs_getattr (fhandle fh, fattr *fatt, CLIENT *cl)
int nfs_lookup (fhandle fhin, char *path, fhandle fhout, fattr *att, CLIENT *cl)
ssize_t nfs_read (fhandle fh, void *data, off_t offset, size_t size, CLIENT *cl)
ssize_t nfs_write (fhandle fh, void *data, off_t offset, size_t size, CLIENT *cl)
int nfs_create (fhandle fhin, char *file, mode_t mode, fhandle fhout, fattr *at, CLIENT *cl)
int nfs_remove (fhandle fh, char *file, CLIENT *cl)
int nfs_rename (fhandle fh, char *name, fhandle fhR, char *nameR, CLIENT *cl)
int nfs_mkdir (fhandle fhin, char *dir, mode_t mode, fhandle fhout, fattr *at, CLIENT *cl)
int nfs_rmdir (fhandle fh, char *dir, CLIENT *cl)
int nfs_readdir (fhandle fh, nfscookie cookie, char *entr, CLIENT *cl)
int nfs_statfs (fhandle arg, struct nfs_info *inf, CLIENT *cl)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file nfs.c.
Function Documentation
close_connection_mount()
void close_connection_mount (CLIENT * cl)
Definition at line 207 of file nfs.c.
Referenced by create_connection_mount(), nfi_nfs_destroy(), nfi_nfs_disconnect(), nfi_nfs_init(), and nfi_nfs_reconnect().
close_connection_nfs()
void close_connection_nfs (CLIENT * cl)
Definition at line 500 of file nfs.c.
Referenced by create_connection_nfs(), nfi_nfs_destroy(), nfi_nfs_disconnect(), and nfi_nfs_init().
create_connection_mount()
CLIENT * create_connection_mount (char * name, int type)
Definition at line 103 of file nfs.c.
References close_connection_mount(), MNTNAMLEN, MOUNT1_PROGRAM, MOUNT1_VERSION, NFS_TCP, NFS_UDP, RECVSZ, and SENDSZ.
Referenced by nfi_nfs_destroy(), nfi_nfs_disconnect(), nfi_nfs_init(), and nfi_nfs_reconnect().
create_connection_nfs()
CLIENT * create_connection_nfs (char * name, int type)
Definition at line 401 of file nfs.c.
References close_connection_nfs(), MNTNAMLEN, NFS2_PROGRAM, NFS2_VERSION, NFS_TCP, NFS_UDP, RECVSZ, and SENDSZ.
Referenced by nfi_nfs_init(), and nfi_nfs_reconnect().
nfs_create()
int nfs_create (fhandle fhin, char * file, mode_t mode, fhandle fhout, fattr * at, CLIENT * cl)
Definition at line 1053 of file nfs.c.
References FHSIZE, printfh(), and setAttr().
Referenced by nfi_nfs_create().
nfs_export()
int nfs_export (exports * exp, CLIENT * cli)
Definition at line 354 of file nfs.c.
nfs_getattr()
int nfs_getattr (fhandle fh, fattr * fatt, CLIENT * cl)
Definition at line 631 of file nfs.c.
Referenced by nfi_nfs_getattr().
nfs_lookup()
int nfs_lookup (fhandle fhin, char * path, fhandle fhout, fattr * att, CLIENT * cl)
Definition at line 693 of file nfs.c.
References FHSIZE, getFirstDir(), MNTNAMLEN, and printfh().
Referenced by nfi_nfs_create(), nfi_nfs_mkdir(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), and nfs_open().
nfs_mkdir()
int nfs_mkdir (fhandle fhin, char * dir, mode_t mode, fhandle fhout, fattr * at, CLIENT * cl)
Definition at line 1262 of file nfs.c.
References FHSIZE, and setAttr().
Referenced by nfi_nfs_mkdir().
nfs_mount()
int nfs_mount (char * dir, fhandle fhand, CLIENT * cli)
Definition at line 241 of file nfs.c.
References FHSIZE, and printfh().
Referenced by nfi_nfs_init(), and nfi_nfs_reconnect().
nfs_read()
ssize_t nfs_read (fhandle fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 838 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_read().
nfs_readdir()
int nfs_readdir (fhandle fh, nfscookie cookie, char * entr, CLIENT * cl)
Definition at line 1408 of file nfs.c.
References FHSIZE, NFSMAXPATHLEN, and TRUE.
Referenced by nfi_nfs_readdir().
nfs_remove()
int nfs_remove (fhandle fh, char * file, CLIENT * cl)
Definition at line 1123 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_remove().
nfs_rename()
int nfs_rename (fhandle fh, char * name, fhandle fhR, char * nameR, CLIENT * cl)
Definition at line 1187 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_rename().
nfs_rmdir()
int nfs_rmdir (fhandle fh, char * dir, CLIENT * cl)
Definition at line 1336 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_rmdir().
nfs_setattr()
int nfs_setattr (fhandle fh, fattr * fatt, CLIENT * cl)
Definition at line 570 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_setattr().
nfs_statfs()
int nfs_statfs (fhandle arg, struct nfs_info * inf, CLIENT * cl)
Definition at line 1528 of file nfs.c.
Referenced by nfi_nfs_statfs().
nfs_umount()
int nfs_umount (char * path, CLIENT * cli)
Definition at line 307 of file nfs.c.
Referenced by nfi_nfs_destroy(), and nfi_nfs_disconnect().
nfs_write()
ssize_t nfs_write (fhandle fh, void * data, off_t offset, size_t size, CLIENT * cl)
Definition at line 952 of file nfs.c.
References FHSIZE.
Referenced by nfi_nfs_write().
printfh()
void printfh (fhandle fh)
Definition at line 40 of file nfs.c.
Referenced by nfs_create(), nfs_lookup(), and nfs_mount().
setAttr()
void setAttr (sattr * at, unsigned int mode)
Definition at line 534 of file nfs.c.
References setDate().
Referenced by nfs_create(), and nfs_mkdir().
setDate()
void setDate (timevalNfs * t)
Definition at line 521 of file nfs.c.
Referenced by setAttr().