ns.h File Reference
File to 'TODO'.
#include all_system.h
#include base/utils.h
Macros
#define MPI_SERVER_DNS_FILE_DEFAULT /tmp/mpi_dns.txt
Library for 'TODO' Library for 'TODO'.
#define TCP_SERVER_DNS_FILE_DEFAULT /tmp/tcp_dns.txt
#define MAX_TCP_SERVER_NODES 256
#define CONST_TEMP 1024
Functions
void ns_get_hostname (char *srv_name)
Get hostname.
char * ns_get_host_ip (void)
'TODO'.
int ns_publish (char *dns_file, char *protocol, char *param_srv_name, char *srv_ip, char *port_name)
'TODO'.
int ns_unpublish (char *dns_file, char *protocol, char *param_srv_name)
'TODO'.
int ns_lookup (char *protocol, char *param_srv_name, char *srv_ip, char *port_name)
'TODO'.
Detailed Description
File to 'TODO'.
Header file to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos
Date
Jul 22, 2021
Bug
Bug No known bugs.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file ns.h.
Macro Definition Documentation
CONST_TEMP
#define CONST_TEMP 1024
Definition at line 58 of file ns.h.
MAX_TCP_SERVER_NODES
#define MAX_TCP_SERVER_NODES 256
Definition at line 54 of file ns.h.
MPI_SERVER_DNS_FILE_DEFAULT
#define MPI_SERVER_DNS_FILE_DEFAULT /tmp/mpi_dns.txt
Library for 'TODO' Library for 'TODO'.
Definition at line 46 of file ns.h.
TCP_SERVER_DNS_FILE_DEFAULT
#define TCP_SERVER_DNS_FILE_DEFAULT /tmp/tcp_dns.txt
Definition at line 50 of file ns.h.
Function Documentation
ns_get_host_ip()
char * ns_get_host_ip (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 45 of file ns.c.
Referenced by mpi_server_comm_init(), and tcp_server_comm_init().
ns_get_hostname()
void ns_get_hostname (char * srv_name)
Get hostname.
'TODO'.
Parameters
srv_name 'TODO'.
Returns
Nothing.
Definition at line 40 of file ns.c.
Referenced by mpi_server_comm_destroy(), and mpi_server_comm_init().
ns_lookup()
int ns_lookup (char * protocol, char * param_srv_name, char * srv_ip, char * port_name)
'TODO'.
'TODO'.
Parameters
protocol 'TODO'.
param_srv_name 'TODO'.
srv_ip 'TODO'.
port_name 'TODO'.
Returns
'TODO'.
Definition at line 144 of file ns.c.
References MPI_SERVER_DNS_FILE_DEFAULT, PATH_MAX, and TCP_SERVER_DNS_FILE_DEFAULT.
Referenced by mpi_server_down(), mpiClient_comm_connect(), tcp_server_down(), and tcpClient_comm_connect().
ns_publish()
int ns_publish (char * dns_file, char * protocol, char * param_srv_name, char * srv_ip, char * port_name)
'TODO'.
'TODO'.
Parameters
dns_file 'TODO'.
protocol 'TODO'.
param_srv_name 'TODO'.
srv_ip 'TODO'.
port_name 'TODO'.
Returns
'TODO'.
Definition at line 58 of file ns.c.
Referenced by mpi_server_comm_init(), and tcp_server_comm_init().
ns_unpublish()
int ns_unpublish (char * dns_file, char * protocol, char * param_srv_name)
'TODO'.
'TODO'.
Parameters
dns_file 'TODO'.
protocol 'TODO'.
param_srv_name 'TODO'.
Returns
'TODO'.
Definition at line 81 of file ns.c.
References PATH_MAX, rename(), and unlink().
Referenced by mpi_server_comm_destroy(), and tcp_server_comm_destroy().