path_misc.c File Reference
File to 'TODO'.
#include base/path_misc.h
Functions
int hash (__attribute__((__unused__)) char *file, __attribute__((__unused__)) int nServ)
int getFirstDir (char *dir, char *path)
'TODO'.
int getSizeFactor (char *name)
'TODO'.
int getNameFile (char *file, char *dir)
'TODO'.
int getNamePart (char *part, char *dir)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file path_misc.c.
Function Documentation
getFirstDir()
int getFirstDir (char * dir, char * path)
'TODO'.
'TODO'.
Parameters
dir 'TODO'.
path 'TODO'.
Returns
'TODO'.
Definition at line 56 of file path_misc.c.
Referenced by nfs3_lookup(), and nfs_lookup().
getNameFile()
int getNameFile (char * file, char * dir)
'TODO'.
Get the last name of a path and erase the file name.
Parameters
file 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 125 of file path_misc.c.
Referenced by nfi_nfs3_create(), nfi_nfs3_mkdir(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs_create(), nfi_nfs_mkdir(), nfi_nfs_remove(), nfi_nfs_rename(), and nfi_nfs_rmdir().
getNamePart()
int getNamePart (char * part, char * dir)
'TODO'.
Get the first name of the path and erase the part name.
Parameters
part 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 162 of file path_misc.c.
Referenced by XpnGetPartition().
getSizeFactor()
int getSizeFactor (char * name)
'TODO'.
'TODO'.
Parameters
name 'TODO'.
Returns
'TODO'.
Definition at line 91 of file path_misc.c.
References GB, KB, and MB.
Referenced by XpnGetInfoPartition().
hash()
int hash (__attribute__((__unused__)) char * file, __attribute__((__unused__)) int nServ)
Definition at line 41 of file path_misc.c.
Referenced by xpn_internal_remove(), XpnCreateMetadata(), XpnGetAtribPath(), and XpnReadMetadata().