path_misc.h File Reference
Header file to 'TODO'.
#include all_system.h
#include base/string_misc.h
Functions
int hash (char *file, int nServ)
'TODO'.
int getFirstDir (char *dir, char *path)
'TODO'.
int getSizeFactor (char *name)
'TODO'.
int getNameFile (char *file, char *dir)
'TODO'.
int getNamePart (char *part, char *dir)
'TODO'.
int getDirWithURL (char *url, char *dir)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file path_misc.h.
Function Documentation
getDirWithURL()
int getDirWithURL (char * url, char * dir)
'TODO'.
Erase the initial dir used in the url.
Parameters
url 'TODO'.
dir 'TODO'.
Returns
'TODO'.
'TODO'.
Parameters
url 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 345 of file urlstr.c.
References getURLDir(), and PATH_MAX.
Referenced by nfi_nfs3_create(), nfi_nfs3_mkdir(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs_create(), nfi_nfs_mkdir(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), nfs3_open(), and nfs_open().
getFirstDir()
int getFirstDir (char * dir, char * path)
'TODO'.
'TODO'.
Parameters
dir 'TODO'.
path 'TODO'.
Returns
'TODO'.
Definition at line 56 of file path_misc.c.
Referenced by nfs3_lookup(), and nfs_lookup().
getNameFile()
int getNameFile (char * file, char * dir)
'TODO'.
Get the last name of a path and erase the file name.
Parameters
file 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 125 of file path_misc.c.
Referenced by nfi_nfs3_create(), nfi_nfs3_mkdir(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs_create(), nfi_nfs_mkdir(), nfi_nfs_remove(), nfi_nfs_rename(), and nfi_nfs_rmdir().
getNamePart()
int getNamePart (char * part, char * dir)
'TODO'.
Get the first name of the path and erase the part name.
Parameters
part 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 162 of file path_misc.c.
Referenced by XpnGetPartition().
getSizeFactor()
int getSizeFactor (char * name)
'TODO'.
'TODO'.
Parameters
name 'TODO'.
Returns
'TODO'.
Definition at line 91 of file path_misc.c.
References GB, KB, and MB.
Referenced by XpnGetInfoPartition().
hash()
int hash (char * file, int nServ)
'TODO'.
'Server number calculation'.
Parameters
file 'TODO'.
nServ 'TODO'.
Returns
'TODO'.