string_misc.h File Reference
Header file to 'TODO'.
#include all_system.h
Functions
long STRING_MISC_StrLen (char *str)
Return the string length of 'str'.
int8_t STRING_MISC_Equal (char *str1, char *str2)
Return true if and only if the strings 'str1' and 'str2' are equals.
char * STRING_MISC_StrDup (char *str)
Return a string clone of 'str'.
int STRING_MISC_StrLenF (char *format, va_list argl)
Like 'strlen' but also accept a string with format.
char * STRING_MISC_Dvsprintf (char *format, va_list argl)
Like vsprintf, but request dynamic memory to write string elements into.
char * STRING_MISC_Dsprintf (char *format,...)
Like before, but with variable arguments.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file string_misc.h.
Function Documentation
STRING_MISC_Dsprintf()
char * STRING_MISC_Dsprintf (char * format, ...)
Like before, but with variable arguments.
Parameters
format string with message format.
Returns
string pointer or NULL if error.
Definition at line 129 of file string_misc.c.
References STRING_MISC_Dvsprintf().
STRING_MISC_Dvsprintf()
char * STRING_MISC_Dvsprintf (char * format, va_list argl)
Like vsprintf, but request dynamic memory to write string elements into.
Parameters
format string format.
argl format params.
Returns
string pointer or NULL if error.
Definition at line 113 of file string_misc.c.
References STRING_MISC_StrLenF().
Referenced by DEBUG_MSG_VPrintF(), STRING_MISC_Dsprintf(), and TRACE_MSG_VPrintF().
STRING_MISC_Equal()
int8_t STRING_MISC_Equal (char * str1, char * str2)
Return true if and only if the strings 'str1' and 'str2' are equals.
Parameters
str1 the first string.
str2 the second string.
Returns
true (1) iff are equals or false (0) in other case.
Definition at line 50 of file string_misc.c.
STRING_MISC_StrDup()
char * STRING_MISC_StrDup (char * str)
Return a string clone of 'str'.
Parameters
str the string.
Returns
a clone of 'str'.
Definition at line 66 of file string_misc.c.
References STRING_MISC_StrLen().
Referenced by nfi_local_init(), nfi_local_mkdir(), nfi_mpi_server_mkdir(), and nfi_tcp_server_mkdir().
STRING_MISC_StrLen()
long STRING_MISC_StrLen (char * str)
Return the string length of 'str'.
Parameters
str the string.
Returns
the string length.
Definition at line 41 of file string_misc.c.
Referenced by STRING_MISC_StrDup().
STRING_MISC_StrLenF()
int STRING_MISC_StrLenF (char * format, va_list argl)
Like 'strlen' but also accept a string with format.
Parameters
format string format.
argl format params.
Returns
string legth.
Definition at line 86 of file string_misc.c.
Referenced by STRING_MISC_Dvsprintf().