syscall_proxies.c File Reference
File to 'TODO'.
#include base/syscall_proxies.h
Functions
int dlsym_open (char *path, int flags)
'TODO'.
int dlsym_open2 (char *path, int flags, mode_t mode)
'TODO'.
int dlsym_open64 (char *path, int flags, mode_t mode)
'TODO'.
int dlsym___open_2 (char *path, int flags)
'TODO'.
int dlsym_creat (const char *path, mode_t mode)
'TODO'.
int dlsym_ftruncate (int fd, off_t length)
'TODO'.
ssize_t dlsym_read (int fd, void *buf, size_t nbyte)
'TODO'.
ssize_t dlsym_write (int fd, void *buf, size_t nbyte)
'TODO'.
off_t dlsym_lseek (int fd, off_t offset, int whence)
'TODO'.
off64_t dlsym_lseek64 (int fd, off64_t offset, int whence)
'TODO'.
int dlsym_lxstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int dlsym_xstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int dlsym_fxstat64 (int ver, int fd, struct stat64 *buf)
'TODO'.
int dlsym_lstat (int ver, const char *path, struct stat *buf)
'TODO'.
int dlsym_stat (int ver, const char *path, struct stat *buf)
'TODO'.
int dlsym_fstat (int ver, int fd, struct stat *buf)
'TODO'.
int dlsym_fstatat (int dfd, const char *path, struct stat *buf, int flags)
'TODO'.
int dlsym_fstatat64 (int dfd, const char *path, struct stat64 *buf, int flags)
'TODO'.
int dlsym_close (int fd)
'TODO'.
int dlsym_rename (const char *old_path, const char *new_path)
'TODO'.
int dlsym_unlink (char *path)
'TODO'.
DIR * dlsym_opendir (char *dirname)
'TODO'.
DIR * dlsym_opendir64 (char *dirname)
'TODO'.
int dlsym_mkdir (char *path, mode_t mode)
'TODO'.
struct dirent * dlsym_readdir (DIR *dirp)
'TODO'.
struct dirent64 * dlsym_readdir64 (DIR *dirp)
'TODO'.
int dlsym_closedir (DIR *dirp)
'TODO'.
int dlsym_rmdir (char *path)
'TODO'.
int dlsym_fork (void)
'TODO'.
int dlsym_pipe (int pipefd[2])
'TODO'.
int dlsym_dup (int fd)
'TODO'.
int dlsym_dup2 (int fd, int fd2)
'TODO'.
void dlsym_exit (int status)
'TODO'.
int dlsym_chdir (char *path)
'TODO'.
int dlsym_chmod (char *path, mode_t mode)
'TODO'.
int dlsym_fchmod (int fd, mode_t mode)
'TODO'.
int dlsym_chown (char *path, uid_t owner, gid_t group)
'TODO'.
int dlsym_fcntl (int fd, int cmd, long arg)
'TODO'.
int dlsym_access (const char *path, int mode)
'TODO'.
char * dlsym_realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
int dlsym_fsync (int fd)
'TODO'.
void * dlsym_mmap (void *addr, size_t length, int prot, int flags, int fd, off_t offset)
'TODO'.
Variables
int(* real_open)(char *, int, mode_t) = NULL
int(* real_open64)(char *, int, mode_t) = NULL
int(* real___open_2)(char *, int) = NULL
int(* real_creat)(const char *, mode_t) = NULL
int(* real_close)(int) = NULL
ssize_t(* real_read)(int, void *, size_t) = NULL
ssize_t(* real_write)(int, const void *, size_t) = NULL
off_t(* real_lseek)(int, off_t, int) = NULL
off64_t(* real_lseek64)(int, off64_t, int) = NULL
int(* real_ftruncate)(int, off_t) = NULL
int(* real_stat)(int, char *, struct stat *) = NULL
int(* real_xstat64)(int, const char *, struct stat64 *) = NULL
int(* real_lstat)(int, char *, struct stat *) = NULL
int(* real_lxstat64)(int, const char *, struct stat64 *) = NULL
int(* real_fstat)(int, int, struct stat *) = NULL
int(* real_fxstat64)(int, int, struct stat64 *) = NULL
int(* real_fstatat)(int, const char *, struct stat *, int) = NULL
int(* real_fstatat64)(int, const char *, struct stat64 *, int) = NULL
int(* real_rename)(const char *, const char *) = NULL
int(* real_unlink)(char *) = NULL
DIR *(* real_opendir)(char *) = NULL
DIR *(* real_opendir64)(char *) = NULL
struct dirent *(* real_readdir)(DIR *) = NULL
struct dirent64 *(* real_readdir64)(DIR *) = NULL
int(* real_closedir)(DIR *) = NULL
int(* real_mkdir)(char *, mode_t) = NULL
int(* real_rmdir)(char *) = NULL
int(* real_fork)(void) = NULL
int(* real_pipe)(int *) = NULL
int(* real_dup)(int) = NULL
int(* real_dup2)(int, int) = NULL
void(* real_exit)(int) = NULL
int(* real_chdir)(char *) = NULL
int(* real_chmod)(char *, mode_t) = NULL
int(* real_fchmod)(int, mode_t) = NULL
int(* real_chown)(char *, uid_t, gid_t) = NULL
int(* real_fcntl)(int, int, long) = NULL
int(* real_access)(const char *, int) = NULL
char *(* real_realpath)(const char *restrict, char *restrict) = NULL
int(* real_fsync)(int) = NULL
void *(* real_mmap)(void *, size_t, int, int, int, off_t) = NULL
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file syscall_proxies.c.
Function Documentation
dlsym___open_2()
int dlsym___open_2 (char * path, int flags)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 153 of file syscall_proxies.c.
References debug_info, and real___open_2.
Referenced by __open_2().
dlsym_access()
int dlsym_access (const char * path, int mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 596 of file syscall_proxies.c.
References debug_info, and real_access.
Referenced by access().
dlsym_chdir()
int dlsym_chdir (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 536 of file syscall_proxies.c.
References debug_info, and real_chdir.
Referenced by chdir().
dlsym_chmod()
int dlsym_chmod (char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 548 of file syscall_proxies.c.
References debug_info, and real_chmod.
Referenced by chmod().
dlsym_chown()
int dlsym_chown (char * path, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 572 of file syscall_proxies.c.
References debug_info, and real_chown.
Referenced by chown().
dlsym_close()
int dlsym_close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 344 of file syscall_proxies.c.
References debug_info, and real_close.
Referenced by close().
dlsym_closedir()
int dlsym_closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 444 of file syscall_proxies.c.
References debug_info, and real_closedir.
Referenced by closedir().
dlsym_creat()
int dlsym_creat (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 170 of file syscall_proxies.c.
References debug_info, and real_creat.
Referenced by creat().
dlsym_dup()
int dlsym_dup (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 496 of file syscall_proxies.c.
References debug_info, and real_dup.
Referenced by dup().
dlsym_dup2()
int dlsym_dup2 (int fd, int fd2)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
fd2 'TODO'.
Returns
'TODO'.
Definition at line 508 of file syscall_proxies.c.
References debug_info, and real_dup2.
Referenced by dup2().
dlsym_exit()
void dlsym_exit (int status)
'TODO'.
'TODO'.
Parameters
status 'TODO'.
Returns
Nothing.
Definition at line 520 of file syscall_proxies.c.
References debug_info, and real_exit.
Referenced by exit().
dlsym_fchmod()
int dlsym_fchmod (int fd, mode_t mode)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 560 of file syscall_proxies.c.
References debug_info, and real_fchmod.
Referenced by fchmod().
dlsym_fcntl()
int dlsym_fcntl (int fd, int cmd, long arg)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
cmd 'TODO'.
arg 'TODO'.
Returns
'TODO'.
Definition at line 584 of file syscall_proxies.c.
References debug_info, and real_fcntl.
Referenced by fcntl().
dlsym_fork()
int dlsym_fork (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 472 of file syscall_proxies.c.
References debug_info, and real_fork.
Referenced by fork().
dlsym_fstat()
int dlsym_fstat (int ver, int fd, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fd 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 308 of file syscall_proxies.c.
References buf, debug_info, and real_fstat.
Referenced by __fxstat().
dlsym_fstatat()
int dlsym_fstatat (int dfd, const char * path, struct stat * buf, int flags)
'TODO'.
'TODO'.
Parameters
dfd 'TODO'.
path 'TODO'.
buf 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 320 of file syscall_proxies.c.
References buf, debug_info, and real_fstatat.
dlsym_fstatat64()
int dlsym_fstatat64 (int dfd, const char * path, struct stat64 * buf, int flags)
'TODO'.
'TODO'.
Parameters
dfd 'TODO'.
path 'TODO'.
buf 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 332 of file syscall_proxies.c.
References buf, debug_info, and real_fstatat64.
dlsym_fsync()
int dlsym_fsync (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 630 of file syscall_proxies.c.
References debug_info, and real_fsync.
Referenced by fsync().
dlsym_ftruncate()
int dlsym_ftruncate (int fd, off_t length)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 187 of file syscall_proxies.c.
References debug_info, and real_ftruncate.
Referenced by ftruncate().
dlsym_fxstat64()
int dlsym_fxstat64 (int ver, int fd, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fd 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 271 of file syscall_proxies.c.
References buf, debug_info, and real_fxstat64.
Referenced by __fxstat64().
dlsym_lseek()
off_t dlsym_lseek (int fd, off_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 223 of file syscall_proxies.c.
References debug_info, and real_lseek.
Referenced by lseek().
dlsym_lseek64()
off64_t dlsym_lseek64 (int fd, off64_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 235 of file syscall_proxies.c.
References debug_info, and real_lseek64.
Referenced by lseek64().
dlsym_lstat()
int dlsym_lstat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 284 of file syscall_proxies.c.
References buf, debug_info, and real_lstat.
Referenced by __lxstat().
dlsym_lxstat64()
int dlsym_lxstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 247 of file syscall_proxies.c.
References buf, debug_info, and real_lxstat64.
Referenced by __lxstat64().
dlsym_mkdir()
int dlsym_mkdir (char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 408 of file syscall_proxies.c.
References debug_info, and real_mkdir.
Referenced by mkdir().
dlsym_mmap()
void * dlsym_mmap (void * addr, size_t length, int prot, int flags, int fd, off_t offset)
'TODO'.
'TODO'.
Parameters
addr 'TODO'.
length 'TODO'.
prot 'TODO'.
flags 'TODO'.
fd 'TODO'.
offset 'TODO'.
Returns
Nothing.
Definition at line 646 of file syscall_proxies.c.
References debug_info, and real_mmap.
dlsym_open()
int dlsym_open (char * path, int flags)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 97 of file syscall_proxies.c.
References debug_info, and real_open.
dlsym_open2()
int dlsym_open2 (char * path, int flags, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 115 of file syscall_proxies.c.
References debug_info, and real_open.
Referenced by open().
dlsym_open64()
int dlsym_open64 (char * path, int flags, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 134 of file syscall_proxies.c.
References debug_info, and real_open64.
Referenced by open64().
dlsym_opendir()
DIR * dlsym_opendir (char * dirname)
'TODO'.
'TODO'.
Parameters
dirname 'TODO'.
Returns
'TODO'.
Definition at line 384 of file syscall_proxies.c.
References debug_info, and real_opendir.
Referenced by opendir().
dlsym_opendir64()
DIR * dlsym_opendir64 (char * dirname)
'TODO'.
'TODO'.
Parameters
dirname 'TODO'.
Returns
'TODO'.
Definition at line 396 of file syscall_proxies.c.
References debug_info, and real_opendir64.
dlsym_pipe()
int dlsym_pipe (int pipefd[2])
'TODO'.
'TODO'.
Parameters
pipefd 'TODO'.
Returns
'TODO'.
Definition at line 484 of file syscall_proxies.c.
References debug_info, and real_pipe.
Referenced by pipe().
dlsym_read()
ssize_t dlsym_read (int fd, void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 199 of file syscall_proxies.c.
References buf, debug_info, and real_read.
Referenced by read().
dlsym_readdir()
struct dirent * dlsym_readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 420 of file syscall_proxies.c.
References debug_info, and real_readdir.
Referenced by readdir().
dlsym_readdir64()
struct dirent64 * dlsym_readdir64 (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 432 of file syscall_proxies.c.
References debug_info, and real_readdir64.
Referenced by readdir64().
dlsym_realpath()
char * dlsym_realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
resolved_path 'TODO'.
Returns
'TODO'.
Definition at line 613 of file syscall_proxies.c.
References debug_info, and real_realpath.
Referenced by __realpath_chk(), and realpath().
dlsym_rename()
int dlsym_rename (const char * old_path, const char * new_path)
'TODO'.
'TODO'.
Parameters
old_path 'TODO'.
new_path 'TODO'.
Returns
'TODO'.
Definition at line 356 of file syscall_proxies.c.
References debug_info, and real_rename.
Referenced by rename().
dlsym_rmdir()
int dlsym_rmdir (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 456 of file syscall_proxies.c.
References debug_info, and real_rmdir.
Referenced by rmdir().
dlsym_stat()
int dlsym_stat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 296 of file syscall_proxies.c.
References buf, debug_info, and real_stat.
Referenced by __xstat().
dlsym_unlink()
int dlsym_unlink (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 368 of file syscall_proxies.c.
References debug_info, and real_unlink.
Referenced by unlink().
dlsym_write()
ssize_t dlsym_write (int fd, void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 211 of file syscall_proxies.c.
References buf, debug_info, and real_write.
Referenced by write().
dlsym_xstat64()
int dlsym_xstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 259 of file syscall_proxies.c.
References buf, debug_info, and real_xstat64.
Referenced by __xstat64().
Variable Documentation
real___open_2
int(* real___open_2) (char *, int) (char * , int) = NULL
Definition at line 43 of file syscall_proxies.c.
Referenced by dlsym___open_2().
real_access
int(* real_access) (const char *, int) (const char * , int) = NULL
Definition at line 84 of file syscall_proxies.c.
Referenced by dlsym_access().
real_chdir
int(* real_chdir) (char *) (char *) = NULL
Definition at line 79 of file syscall_proxies.c.
Referenced by dlsym_chdir().
real_chmod
int(* real_chmod) (char *, mode_t) (char * , mode_t) = NULL
Definition at line 80 of file syscall_proxies.c.
Referenced by dlsym_chmod().
real_chown
int(* real_chown) (char *, uid_t, gid_t) (char * , uid_t , gid_t) = NULL
Definition at line 82 of file syscall_proxies.c.
Referenced by dlsym_chown().
real_close
int(* real_close) (int) (int) = NULL
Definition at line 45 of file syscall_proxies.c.
Referenced by dlsym_close().
real_closedir
int(* real_closedir) (DIR *) (DIR *) = NULL
Definition at line 69 of file syscall_proxies.c.
Referenced by dlsym_closedir().
real_creat
int(* real_creat) (const char *, mode_t) (const char * , mode_t) = NULL
Definition at line 44 of file syscall_proxies.c.
Referenced by dlsym_creat().
real_dup
int(* real_dup) (int) (int) = NULL
Definition at line 76 of file syscall_proxies.c.
Referenced by dlsym_dup().
real_dup2
int(* real_dup2) (int, int) (int , int) = NULL
Definition at line 77 of file syscall_proxies.c.
Referenced by dlsym_dup2().
real_exit
void(* real_exit) (int) (int) = NULL
Definition at line 78 of file syscall_proxies.c.
Referenced by dlsym_exit().
real_fchmod
int(* real_fchmod) (int, mode_t) (int , mode_t) = NULL
Definition at line 81 of file syscall_proxies.c.
Referenced by dlsym_fchmod().
real_fcntl
int(* real_fcntl) (int, int, long) (int , int , long) = NULL
Definition at line 83 of file syscall_proxies.c.
Referenced by dlsym_fcntl().
real_fork
int(* real_fork) (void) (void) = NULL
Definition at line 74 of file syscall_proxies.c.
Referenced by dlsym_fork().
real_fstat
int(* real_fstat) (int, int, struct stat *) (int , int , struct stat *) = NULL
Definition at line 57 of file syscall_proxies.c.
Referenced by dlsym_fstat().
real_fstatat
int(* real_fstatat) (int, const char *, struct stat *, int) (int , const char * , struct stat * , int) = NULL
Definition at line 59 of file syscall_proxies.c.
Referenced by dlsym_fstatat().
real_fstatat64
int(* real_fstatat64) (int, const char *, struct stat64 *, int) (int , const char * , struct stat64 * , int) = NULL
Definition at line 60 of file syscall_proxies.c.
Referenced by dlsym_fstatat64().
real_fsync
int(* real_fsync) (int) (int) = NULL
Definition at line 86 of file syscall_proxies.c.
Referenced by dlsym_fsync().
real_ftruncate
int(* real_ftruncate) (int, off_t) (int , off_t) = NULL
Definition at line 51 of file syscall_proxies.c.
Referenced by dlsym_ftruncate().
real_fxstat64
int(* real_fxstat64) (int, int, struct stat64 *) (int , int , struct stat64 *) = NULL
Definition at line 58 of file syscall_proxies.c.
Referenced by dlsym_fxstat64().
real_lseek
off_t(* real_lseek) (int, off_t, int) (int , off_t , int) = NULL
Definition at line 49 of file syscall_proxies.c.
Referenced by dlsym_lseek().
real_lseek64
off64_t(* real_lseek64) (int, off64_t, int) (int , off64_t , int) = NULL
Definition at line 50 of file syscall_proxies.c.
Referenced by dlsym_lseek64().
real_lstat
int(* real_lstat) (int, char *, struct stat *) (int , char * , struct stat *) = NULL
Definition at line 55 of file syscall_proxies.c.
Referenced by dlsym_lstat().
real_lxstat64
int(* real_lxstat64) (int, const char *, struct stat64 *) (int , const char * , struct stat64 *) = NULL
Definition at line 56 of file syscall_proxies.c.
Referenced by dlsym_lxstat64().
real_mkdir
int(* real_mkdir) (char *, mode_t) (char * , mode_t) = NULL
Definition at line 71 of file syscall_proxies.c.
Referenced by dlsym_mkdir().
real_mmap
void *(* real_mmap) (void *, size_t, int, int, int, off_t) (void * , size_t , int , int , int , off_t) = NULL
Definition at line 87 of file syscall_proxies.c.
Referenced by dlsym_mmap().
real_open
int(* real_open) (char *, int, mode_t) (char * , int , mode_t) = NULL
Definition at line 41 of file syscall_proxies.c.
Referenced by dlsym_open(), and dlsym_open2().
real_open64
int(* real_open64) (char *, int, mode_t) (char * , int , mode_t) = NULL
Definition at line 42 of file syscall_proxies.c.
Referenced by dlsym_open64().
real_opendir
DIR *(* real_opendir) (char *) (char *) = NULL
Definition at line 65 of file syscall_proxies.c.
Referenced by dlsym_opendir().
real_opendir64
DIR *(* real_opendir64) (char *) (char *) = NULL
Definition at line 66 of file syscall_proxies.c.
Referenced by dlsym_opendir64().
real_pipe
int(* real_pipe) (int *) (int *) = NULL
Definition at line 75 of file syscall_proxies.c.
Referenced by dlsym_pipe().
real_read
ssize_t(* real_read) (int, void *, size_t) (int , void * , size_t) = NULL
Definition at line 47 of file syscall_proxies.c.
Referenced by dlsym_read(), and tcpClient_read_data().
real_readdir
struct dirent *(* real_readdir) (DIR *) (DIR *) = NULL
Definition at line 66 of file syscall_proxies.c.
Referenced by dlsym_readdir().
real_readdir64
struct dirent64 *(* real_readdir64) (DIR *) (DIR *) = NULL
Definition at line 66 of file syscall_proxies.c.
Referenced by dlsym_readdir64().
real_realpath
char *(* real_realpath) (const char *restrict, char *restrict) (const char * restrict, char * restrict) = NULL
Definition at line 85 of file syscall_proxies.c.
Referenced by dlsym_realpath().
real_rename
int(* real_rename) (const char *, const char *) (const char * , const char *) = NULL
Definition at line 62 of file syscall_proxies.c.
Referenced by dlsym_rename().
real_rmdir
int(* real_rmdir) (char *) (char *) = NULL
Definition at line 72 of file syscall_proxies.c.
Referenced by dlsym_rmdir().
real_stat
int(* real_stat) (int, char *, struct stat *) (int , char * , struct stat *) = NULL
Definition at line 53 of file syscall_proxies.c.
Referenced by dlsym_stat().
real_unlink
int(* real_unlink) (char *) (char *) = NULL
Definition at line 63 of file syscall_proxies.c.
Referenced by dlsym_unlink().
real_write
ssize_t(* real_write) (int, const void *, size_t) (int , const void * , size_t) = NULL
Definition at line 48 of file syscall_proxies.c.
Referenced by dlsym_write(), and tcpClient_write_data().
real_xstat64
int(* real_xstat64) (int, const char *, struct stat64 *) (int , const char * , struct stat64 *) = NULL
Definition at line 54 of file syscall_proxies.c.
Referenced by dlsym_xstat64().