syscall_proxies.h File Reference
Header file to 'TODO'.
#include <dlfcn.h>
#include <sys/stat.h>
#include <dirent.h>
#include <stdlib.h>
#include utils.h
Functions
int dlsym_open (char *path, int flags)
'TODO'.
int dlsym_open2 (char *path, int flags, mode_t mode)
'TODO'.
int dlsym_open64 (char *path, int flags, mode_t mode)
'TODO'.
int dlsym___open_2 (char *path, int flags)
'TODO'.
int dlsym_close (int fd)
'TODO'.
int dlsym_creat (const char *path, mode_t mode)
'TODO'.
int dlsym_ftruncate (int fd, off_t length)
'TODO'.
ssize_t dlsym_read (int fd, void *buf, size_t nbyte)
'TODO'.
ssize_t dlsym_write (int fd, void *buf, size_t nbyte)
'TODO'.
off_t dlsym_lseek (int fd, off_t offset, int whence)
'TODO'.
off64_t dlsym_lseek64 (int fd, off64_t offset, int whence)
'TODO'.
int dlsym_fstat (int ver, int fd, struct stat *buf)
'TODO'.
int dlsym_fxstat64 (int ver, int fd, struct stat64 *buf)
'TODO'.
int dlsym_stat (int ver, const char *path, struct stat *buf)
'TODO'.
int dlsym_lstat (int ver, const char *path, struct stat *buf)
'TODO'.
int dlsym_lxstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int dlsym_xstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int dlsym_fstatat (int dfd, const char *path, struct stat *buf, int flags)
'TODO'.
int dlsym_fstatat64 (int dfd, const char *path, struct stat64 *buf, int flags)
'TODO'.
int dlsym_rename (const char *old_path, const char *new_path)
'TODO'.
int dlsym_unlink (char *path)
'TODO'.
DIR * dlsym_opendir (char *dirname)
'TODO'.
DIR * dlsym_opendir64 (char *dirname)
'TODO'.
int dlsym_closedir (DIR *)
'TODO'.
struct dirent * dlsym_readdir (DIR *dirp)
'TODO'.
struct dirent64 * dlsym_readdir64 (DIR *dirp)
'TODO'.
int dlsym_mkdir (char *path, mode_t mode)
'TODO'.
int dlsym_rmdir (char *path)
'TODO'.
int dlsym_fork (void)
'TODO'.
int dlsym_pipe (int pipefd[2])
'TODO'.
int dlsym_dup (int fd)
'TODO'.
int dlsym_dup2 (int fd, int fd2)
'TODO'.
void dlsym_exit (int status)
'TODO'.
int dlsym_chdir (char *path)
'TODO'.
int dlsym_chmod (char *path, mode_t mode)
'TODO'.
int dlsym_fchmod (int fd, mode_t mode)
'TODO'.
int dlsym_chown (char *path, uid_t owner, gid_t group)
'TODO'.
int dlsym_fcntl (int fd, int cmd, long arg)
'TODO'.
int dlsym_access (const char *path, int mode)
'TODO'.
char * dlsym_realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
int dlsym_fsync (int fd)
'TODO'.
void * dlsym_mmap (void *addr, size_t length, int prot, int flags, int fd, off_t offset)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file syscall_proxies.h.
Function Documentation
dlsym___open_2()
int dlsym___open_2 (char * path, int flags)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 153 of file syscall_proxies.c.
References debug_info, and real___open_2.
Referenced by __open_2().
dlsym_access()
int dlsym_access (const char * path, int mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 596 of file syscall_proxies.c.
References debug_info, and real_access.
Referenced by access().
dlsym_chdir()
int dlsym_chdir (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 536 of file syscall_proxies.c.
References debug_info, and real_chdir.
Referenced by chdir().
dlsym_chmod()
int dlsym_chmod (char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 548 of file syscall_proxies.c.
References debug_info, and real_chmod.
Referenced by chmod().
dlsym_chown()
int dlsym_chown (char * path, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 572 of file syscall_proxies.c.
References debug_info, and real_chown.
Referenced by chown().
dlsym_close()
int dlsym_close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 344 of file syscall_proxies.c.
References debug_info, and real_close.
Referenced by close().
dlsym_closedir()
int dlsym_closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 444 of file syscall_proxies.c.
References debug_info, and real_closedir.
Referenced by closedir().
dlsym_creat()
int dlsym_creat (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 170 of file syscall_proxies.c.
References debug_info, and real_creat.
Referenced by creat().
dlsym_dup()
int dlsym_dup (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 496 of file syscall_proxies.c.
References debug_info, and real_dup.
Referenced by dup().
dlsym_dup2()
int dlsym_dup2 (int fd, int fd2)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
fd2 'TODO'.
Returns
'TODO'.
Definition at line 508 of file syscall_proxies.c.
References debug_info, and real_dup2.
Referenced by dup2().
dlsym_exit()
void dlsym_exit (int status)
'TODO'.
'TODO'.
Parameters
status 'TODO'.
Returns
Nothing.
Definition at line 520 of file syscall_proxies.c.
References debug_info, and real_exit.
Referenced by exit().
dlsym_fchmod()
int dlsym_fchmod (int fd, mode_t mode)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 560 of file syscall_proxies.c.
References debug_info, and real_fchmod.
Referenced by fchmod().
dlsym_fcntl()
int dlsym_fcntl (int fd, int cmd, long arg)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
cmd 'TODO'.
arg 'TODO'.
Returns
'TODO'.
Definition at line 584 of file syscall_proxies.c.
References debug_info, and real_fcntl.
Referenced by fcntl().
dlsym_fork()
int dlsym_fork (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 472 of file syscall_proxies.c.
References debug_info, and real_fork.
Referenced by fork().
dlsym_fstat()
int dlsym_fstat (int ver, int fd, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fd 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 308 of file syscall_proxies.c.
References buf, debug_info, and real_fstat.
Referenced by __fxstat().
dlsym_fstatat()
int dlsym_fstatat (int dfd, const char * path, struct stat * buf, int flags)
'TODO'.
'TODO'.
Parameters
dfd 'TODO'.
path 'TODO'.
buf 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 320 of file syscall_proxies.c.
References buf, debug_info, and real_fstatat.
dlsym_fstatat64()
int dlsym_fstatat64 (int dfd, const char * path, struct stat64 * buf, int flags)
'TODO'.
'TODO'.
Parameters
dfd 'TODO'.
path 'TODO'.
buf 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 332 of file syscall_proxies.c.
References buf, debug_info, and real_fstatat64.
dlsym_fsync()
int dlsym_fsync (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 630 of file syscall_proxies.c.
References debug_info, and real_fsync.
Referenced by fsync().
dlsym_ftruncate()
int dlsym_ftruncate (int fd, off_t length)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 187 of file syscall_proxies.c.
References debug_info, and real_ftruncate.
Referenced by ftruncate().
dlsym_fxstat64()
int dlsym_fxstat64 (int ver, int fd, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fd 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 271 of file syscall_proxies.c.
References buf, debug_info, and real_fxstat64.
Referenced by __fxstat64().
dlsym_lseek()
off_t dlsym_lseek (int fd, off_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 223 of file syscall_proxies.c.
References debug_info, and real_lseek.
Referenced by lseek().
dlsym_lseek64()
off64_t dlsym_lseek64 (int fd, off64_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 235 of file syscall_proxies.c.
References debug_info, and real_lseek64.
Referenced by lseek64().
dlsym_lstat()
int dlsym_lstat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 284 of file syscall_proxies.c.
References buf, debug_info, and real_lstat.
Referenced by __lxstat().
dlsym_lxstat64()
int dlsym_lxstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 247 of file syscall_proxies.c.
References buf, debug_info, and real_lxstat64.
Referenced by __lxstat64().
dlsym_mkdir()
int dlsym_mkdir (char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 408 of file syscall_proxies.c.
References debug_info, and real_mkdir.
Referenced by mkdir().
dlsym_mmap()
void * dlsym_mmap (void * addr, size_t length, int prot, int flags, int fd, off_t offset)
'TODO'.
'TODO'.
Parameters
addr 'TODO'.
length 'TODO'.
prot 'TODO'.
flags 'TODO'.
fd 'TODO'.
offset 'TODO'.
Returns
Nothing.
Definition at line 646 of file syscall_proxies.c.
References debug_info, and real_mmap.
dlsym_open()
int dlsym_open (char * path, int flags)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 97 of file syscall_proxies.c.
References debug_info, and real_open.
dlsym_open2()
int dlsym_open2 (char * path, int flags, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 115 of file syscall_proxies.c.
References debug_info, and real_open.
Referenced by open().
dlsym_open64()
int dlsym_open64 (char * path, int flags, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 134 of file syscall_proxies.c.
References debug_info, and real_open64.
Referenced by open64().
dlsym_opendir()
DIR * dlsym_opendir (char * dirname)
'TODO'.
'TODO'.
Parameters
dirname 'TODO'.
Returns
'TODO'.
Definition at line 384 of file syscall_proxies.c.
References debug_info, and real_opendir.
Referenced by opendir().
dlsym_opendir64()
DIR * dlsym_opendir64 (char * dirname)
'TODO'.
'TODO'.
Parameters
dirname 'TODO'.
Returns
'TODO'.
Definition at line 396 of file syscall_proxies.c.
References debug_info, and real_opendir64.
dlsym_pipe()
int dlsym_pipe (int pipefd[2])
'TODO'.
'TODO'.
Parameters
pipefd 'TODO'.
Returns
'TODO'.
Definition at line 484 of file syscall_proxies.c.
References debug_info, and real_pipe.
Referenced by pipe().
dlsym_read()
ssize_t dlsym_read (int fd, void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 199 of file syscall_proxies.c.
References buf, debug_info, and real_read.
Referenced by read().
dlsym_readdir()
struct dirent * dlsym_readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 420 of file syscall_proxies.c.
References debug_info, and real_readdir.
Referenced by readdir().
dlsym_readdir64()
struct dirent64 * dlsym_readdir64 (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 432 of file syscall_proxies.c.
References debug_info, and real_readdir64.
Referenced by readdir64().
dlsym_realpath()
char * dlsym_realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
resolved_path 'TODO'.
Returns
'TODO'.
Definition at line 613 of file syscall_proxies.c.
References debug_info, and real_realpath.
Referenced by __realpath_chk(), and realpath().
dlsym_rename()
int dlsym_rename (const char * old_path, const char * new_path)
'TODO'.
'TODO'.
Parameters
old_path 'TODO'.
new_path 'TODO'.
Returns
'TODO'.
Definition at line 356 of file syscall_proxies.c.
References debug_info, and real_rename.
Referenced by rename().
dlsym_rmdir()
int dlsym_rmdir (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 456 of file syscall_proxies.c.
References debug_info, and real_rmdir.
Referenced by rmdir().
dlsym_stat()
int dlsym_stat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 296 of file syscall_proxies.c.
References buf, debug_info, and real_stat.
Referenced by __xstat().
dlsym_unlink()
int dlsym_unlink (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 368 of file syscall_proxies.c.
References debug_info, and real_unlink.
Referenced by unlink().
dlsym_write()
ssize_t dlsym_write (int fd, void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 211 of file syscall_proxies.c.
References buf, debug_info, and real_write.
Referenced by write().
dlsym_xstat64()
int dlsym_xstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 259 of file syscall_proxies.c.
References buf, debug_info, and real_xstat64.
Referenced by __xstat64().