tcp_server_params.h File Reference
Header file to 'TODO'.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include base/utils.h
#include base/workers.h
Data Structures
struct tcp_server_param_st
This is a struct.
Macros
#define TCP_SERVER_DIRBASE_DEFAULT /tmp
#define TCP_SERVER_PORT_DEFAULT 9999
#define TCP_SERVER_IOSIZE_DEFAULT (MB)
#define TCP_MAX_PORT_NAME 1024
Functions
void tcp_server_params_show_usage (void)
'TODO'.
int tcp_server_params_get (tcp_server_param_st *params, int argc, char *argv[])
'TODO'.
void tcp_server_params_show (tcp_server_param_st *params)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file tcp_server/tcp_server_params.h.
Macro Definition Documentation
TCP_MAX_PORT_NAME
#define TCP_MAX_PORT_NAME 1024
Definition at line 62 of file tcp_server/tcp_server_params.h.
TCP_SERVER_DIRBASE_DEFAULT
#define TCP_SERVER_DIRBASE_DEFAULT /tmp
Definition at line 51 of file tcp_server/tcp_server_params.h.
TCP_SERVER_IOSIZE_DEFAULT
#define TCP_SERVER_IOSIZE_DEFAULT (MB)
Definition at line 59 of file tcp_server/tcp_server_params.h.
TCP_SERVER_PORT_DEFAULT
#define TCP_SERVER_PORT_DEFAULT 9999
Definition at line 55 of file tcp_server/tcp_server_params.h.
Function Documentation
tcp_server_params_get()
int tcp_server_params_get (tcp_server_param_st * params, int argc, char * argv[])
'TODO'.
'TODO'.
Parameters
params 'TODO'.
argc 'TODO'.
argv 'TODO'.
Returns
'TODO'.
Definition at line 95 of file tcp_server_params.c.
References mpi_server_param_st::argc, mpi_server_param_st::argv, DEBUG_BEGIN, DEBUG_END, mpi_server_param_st::dirbase, mpi_server_param_st::dns_file, params, mpi_server_param_st::port_name, mpi_server_param_st::rank, mpi_server_param_st::shutdown_file, mpi_server_param_st::size, mpi_server_param_st::srv_name, TCP_MAX_PORT_NAME, TCP_SERVER_DIRBASE_DEFAULT, TCP_SERVER_DNS_FILE_DEFAULT, TCP_SERVER_IOSIZE_DEFAULT, TCP_SERVER_PORT_DEFAULT, TH_NOT, TH_OP, TH_POOL, and mpi_server_param_st::thread_mode.
Referenced by main().
tcp_server_params_show()
void tcp_server_params_show (tcp_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
Nothing.
Definition at line 42 of file tcp_server_params.c.
References DEBUG_BEGIN, DEBUG_END, mpi_server_param_st::dirbase, mpi_server_param_st::dns_file, params, mpi_server_param_st::shutdown_file, TH_NOT, TH_OP, TH_POOL, and mpi_server_param_st::thread_mode.
Referenced by main().
tcp_server_params_show_usage()
void tcp_server_params_show_usage (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 76 of file tcp_server_params.c.
References DEBUG_BEGIN, and DEBUG_END.
Referenced by main().