tcp_server_comm.c File Reference
File to 'TODO'.
#include tcp_server/tcp_server_comm.h
Functions
int tcp_server_comm_init (tcp_server_param_st *params)
'TODO'.
int tcp_server_comm_destroy (tcp_server_param_st *params)
'TODO'.
int tcp_server_comm_accept (tcp_server_param_st *params)
'TODO'.
int tcp_server_comm_connect (tcp_server_param_st *params, char *server_name, int port_number)
'TODO'.
int tcp_server_comm_close (int fd)
'TODO'.
ssize_t tcp_server_comm_read_operation (tcp_server_param_st *params, int fd, char *data, ssize_t size, int *rank_client_id)
'TODO'.
ssize_t tcp_server_comm_write_data (tcp_server_param_st *params, int fd, char *data, ssize_t size, __attribute__((__unused__)) int rank_client_id)
ssize_t tcp_server_comm_read_data (tcp_server_param_st *params, int fd, char *data, ssize_t size, __attribute__((__unused__)) int rank_client_id)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file tcp_server/tcp_server_comm.c.
Function Documentation
tcp_server_comm_accept()
int tcp_server_comm_accept (tcp_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 357 of file tcp_server/tcp_server_comm.c.
References mpi_server_param_st::client, DEBUG_BEGIN, DEBUG_END, debug_info, and params.
Referenced by tcp_server_up().
tcp_server_comm_close()
int tcp_server_comm_close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 482 of file tcp_server/tcp_server_comm.c.
References close(), DEBUG_BEGIN, and DEBUG_END.
Referenced by tcp_server_dispatcher(), and tcp_server_down().
tcp_server_comm_connect()
int tcp_server_comm_connect (tcp_server_param_st * params, char * server_name, int port_number)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
server_name 'TODO'.
port_number 'TODO'.
Returns
'TODO'.
Definition at line 405 of file tcp_server/tcp_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, params, and mpi_server_param_st::srv_name.
Referenced by tcp_server_down().
tcp_server_comm_destroy()
int tcp_server_comm_destroy (tcp_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 310 of file tcp_server/tcp_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, mpi_server_param_st::dns_file, ns_unpublish(), params, mpi_server_param_st::rank, serv_name, mpi_server_param_st::size, and mpi_server_param_st::srv_name.
Referenced by tcp_server_down(), and tcp_server_up().
tcp_server_comm_init()
int tcp_server_comm_init (tcp_server_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 169 of file tcp_server/tcp_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, mpi_server_param_st::dns_file, MOSQ_OPT_TCP_NODELAY, ns_get_host_ip(), ns_publish(), params, mpi_server_param_st::rank, TIME_MISC_DiffTime(), TIME_MISC_Timer(), and TIME_MISC_TimevaltoFloat().
Referenced by tcp_server_down(), and tcp_server_up().
tcp_server_comm_read_data()
ssize_t tcp_server_comm_read_data (tcp_server_param_st * params, int fd, char * data, ssize_t size, __attribute__((__unused__)) int rank_client_id)
Definition at line 580 of file tcp_server/tcp_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, params, mpi_server_param_st::rank, and read().
Referenced by tcp_server_comm_read_operation(), tcp_server_do_operation(), tcp_server_op_write_wos(), and tcp_server_op_write_ws().
tcp_server_comm_read_operation()
ssize_t tcp_server_comm_read_operation (tcp_server_param_st * params, int fd, char * data, ssize_t size, int * rank_client_id)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
fd 'TODO'.
data 'TODO'.
size 'TODO'.
rank_client_id 'TODO'.
Returns
'TODO'.
Definition at line 494 of file tcp_server/tcp_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_warning, params, mpi_server_param_st::rank, and tcp_server_comm_read_data().
Referenced by tcp_server_dispatcher().
tcp_server_comm_write_data()
ssize_t tcp_server_comm_write_data (tcp_server_param_st * params, int fd, char * data, ssize_t size, __attribute__((__unused__)) int rank_client_id)
Definition at line 529 of file tcp_server/tcp_server_comm.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, params, mpi_server_param_st::rank, and write().
Referenced by tcp_server_down(), tcp_server_op_close_ws(), tcp_server_op_closedir(), tcp_server_op_creat_wos(), tcp_server_op_creat_ws(), tcp_server_op_flush(), tcp_server_op_getattr(), tcp_server_op_getid(), tcp_server_op_getnodename(), tcp_server_op_mkdir(), tcp_server_op_open_wos(), tcp_server_op_open_ws(), tcp_server_op_opendir(), tcp_server_op_preload(), tcp_server_op_read_wos(), tcp_server_op_read_ws(), tcp_server_op_readdir(), tcp_server_op_rename(), tcp_server_op_rm(), tcp_server_op_rmdir(), tcp_server_op_write_wos(), and tcp_server_op_write_ws().