tcp_server_d2xpn.c File Reference
File to 'TODO'.
#include all_system.h
#include tcp_server_params.h
#include tcp_server_d2xpn.h
#include xpn.h
#include <sys/time.h>
Macros
#define DEFAULT_PATH /tmp
#define TCP_SERVER_PATH_DEFAULT /tmp
Functions
void generateName (char *file, char *new_file)
'TODO'.
int mylock (char *file)
'TODO'.
int myunlock (int fd)
'TODO'.
int tcp_server_d2xpn (tcp_server_param_st *params, char *origen, char *destino)
'TODO'.
Variables
pthread_mutex_t mutex_id = PTHREAD_MUTEX_INITIALIZER
int static_id = 0
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file tcp_server_d2xpn.c.
Macro Definition Documentation
DEFAULT_PATH
#define DEFAULT_PATH /tmp
Definition at line 45 of file tcp_server_d2xpn.c.
TCP_SERVER_PATH_DEFAULT
#define TCP_SERVER_PATH_DEFAULT /tmp
Definition at line 46 of file tcp_server_d2xpn.c.
Function Documentation
generateName()
void generateName (char * file, char * new_file)
'TODO'.
'TODO'.
Parameters
file 'TODO'.
new_file 'TODO'.
Returns
Nothing.
Definition at line 67 of file tcp_server_d2xpn.c.
References DEFAULT_PATH.
mylock()
int mylock (char * file)
'TODO'.
'TODO'.
Parameters
file 'TODO'.
Returns
'TODO'.
Definition at line 105 of file tcp_server_d2xpn.c.
References debug_info, and mutex_id.
Referenced by tcp_server_d2xpn().
myunlock()
int myunlock (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 132 of file tcp_server_d2xpn.c.
References debug_info, and mutex_id.
Referenced by tcp_server_d2xpn().
tcp_server_d2xpn()
int tcp_server_d2xpn (tcp_server_param_st * params, char * origen, char * destino)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
origen 'TODO'.
destino 'TODO'.
Returns
'TODO'.
Definition at line 146 of file tcp_server_d2xpn.c.
References debug_info, mpi_server_param_st::dirbase, mylock(), myunlock(), O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), params, PATH_MAX, mpi_server_param_st::rank, st, TCP_SERVER_PATH_DEFAULT, xpn_init(), and xpn_open().
Variable Documentation
mutex_id
pthread_mutex_t mutex_id = PTHREAD_MUTEX_INITIALIZER
Definition at line 51 of file tcp_server_d2xpn.c.
Referenced by mylock(), and myunlock().
static_id
int static_id = 0
Definition at line 52 of file tcp_server_d2xpn.c.