tcp_server_ops.c File Reference
#include tcp_server_ops.h
Functions
char * tcp_server_op2string (int op_code)
'TODO'.
void tcp_server_op_open_ws (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_open_wos (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_creat_ws (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_creat_wos (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_read_ws (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_read_wos (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_write_ws (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_write_wos (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_close_ws (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_rm (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_rename (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_setattr (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_getattr (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_mkdir (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_opendir (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_readdir (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_closedir (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_rmdir (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_flush (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_preload (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_getnodename (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_fstat (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
void tcp_server_op_getid (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, int rank_client_id)
int tcp_server_do_operation (struct st_th *th, int *the_end)
'TODO'.
void tcp_server_op_setattr (tcp_server_param_st *params, int sd, struct st_tcp_server_msg *head, __attribute__((__unused__)) int rank_client_id)
void tcp_server_op_getnodename (tcp_server_param_st *params, int sd, __attribute__((__unused__)) struct st_tcp_server_msg *head, int rank_client_id)
Function Documentation
tcp_server_do_operation()
int tcp_server_do_operation (struct st_th * th, int * the_end)
'TODO'.
'TODO'
Parameters
th 'TODO'.
the_end 'TODO'.
Returns
'TODO'.
Definition at line 152 of file tcp_server_ops.c.
References DEBUG_BEGIN, DEBUG_END, st_tcp_server_msg::op_close, st_tcp_server_msg::op_closedir, st_tcp_server_msg::op_creat, st_tcp_server_msg::op_flush, st_tcp_server_msg::op_getattr, st_tcp_server_msg::op_mkdir, st_tcp_server_msg::op_open, st_tcp_server_msg::op_opendir, st_tcp_server_msg::op_preload, st_tcp_server_msg::op_read, st_tcp_server_msg::op_readdir, st_tcp_server_msg::op_rename, st_tcp_server_msg::op_rm, st_tcp_server_msg::op_rmdir, st_tcp_server_msg::op_setattr, st_tcp_server_msg::op_write, st_th::params, st_th::sd, TCP_SERVER_CLOSE_FILE_WS, TCP_SERVER_CLOSEDIR_DIR, tcp_server_comm_read_data(), TCP_SERVER_CREAT_FILE_WOS, TCP_SERVER_CREAT_FILE_WS, TCP_SERVER_DISCONNECT, TCP_SERVER_FINALIZE, TCP_SERVER_FLUSH_FILE, TCP_SERVER_GETATTR_FILE, TCP_SERVER_GETNODENAME, TCP_SERVER_MKDIR_DIR, tcp_server_op_close_ws(), tcp_server_op_closedir(), tcp_server_op_creat_wos(), tcp_server_op_creat_ws(), tcp_server_op_flush(), tcp_server_op_getattr(), tcp_server_op_getnodename(), tcp_server_op_mkdir(), tcp_server_op_open_wos(), tcp_server_op_open_ws(), tcp_server_op_opendir(), tcp_server_op_preload(), tcp_server_op_read_wos(), tcp_server_op_read_ws(), tcp_server_op_readdir(), tcp_server_op_rename(), tcp_server_op_rm(), tcp_server_op_rmdir(), tcp_server_op_setattr(), tcp_server_op_write_wos(), tcp_server_op_write_ws(), TCP_SERVER_OPEN_FILE_WOS, TCP_SERVER_OPEN_FILE_WS, TCP_SERVER_OPENDIR_DIR, TCP_SERVER_PRELOAD_FILE, TCP_SERVER_READ_FILE_WOS, TCP_SERVER_READ_FILE_WS, TCP_SERVER_READDIR_DIR, TCP_SERVER_RENAME_FILE, TCP_SERVER_RM_FILE, TCP_SERVER_RMDIR_DIR, TCP_SERVER_SETATTR_FILE, TCP_SERVER_WRITE_FILE_WOS, TCP_SERVER_WRITE_FILE_WS, the_end, st_th::type_op, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_run().
tcp_server_op2string()
char * tcp_server_op2string (int op_code)
'TODO'.
'TODO'
Parameters
op_code 'TODO'.
Returns
'TODO'.
Definition at line 28 of file tcp_server_ops.c.
References TCP_SERVER_CLOSE_FILE_WS, TCP_SERVER_CLOSEDIR_DIR, TCP_SERVER_CREAT_FILE_WOS, TCP_SERVER_CREAT_FILE_WS, TCP_SERVER_DISCONNECT, TCP_SERVER_END, TCP_SERVER_FINALIZE, TCP_SERVER_FLUSH_FILE, TCP_SERVER_GETATTR_FILE, TCP_SERVER_GETID, TCP_SERVER_GETNODENAME, TCP_SERVER_MKDIR_DIR, TCP_SERVER_OPEN_FILE_WOS, TCP_SERVER_OPEN_FILE_WS, TCP_SERVER_OPENDIR_DIR, TCP_SERVER_PRELOAD_FILE, TCP_SERVER_READ_FILE_WOS, TCP_SERVER_READ_FILE_WS, TCP_SERVER_READDIR_DIR, TCP_SERVER_RENAME_FILE, TCP_SERVER_RM_FILE, TCP_SERVER_RMDIR_DIR, TCP_SERVER_SETATTR_FILE, TCP_SERVER_STATFS_DIR, TCP_SERVER_WRITE_FILE_WOS, and TCP_SERVER_WRITE_FILE_WS.
Referenced by tcp_server_run().
tcp_server_op_close_ws()
void tcp_server_op_close_ws (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 819 of file tcp_server_ops.c.
References debug_info, st_tcp_server_close::fd, filesystem_close(), st_tcp_server_msg::op_close, params, st_tcp_server_close::path, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_closedir()
void tcp_server_op_closedir (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 1011 of file tcp_server_ops.c.
References debug_info, st_tcp_server_closedir::dir, filesystem_closedir(), st_tcp_server_msg::op_closedir, params, st_tcp_server_direntry::ret, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_creat_wos()
void tcp_server_op_creat_wos (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 465 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_close(), filesystem_creat(), filesystem_mkpath(), st_tcp_server_msg::op_creat, params, st_tcp_server_creat::path, PATH_MAX, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_creat_ws()
void tcp_server_op_creat_ws (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 419 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_creat(), filesystem_mkpath(), st_tcp_server_msg::op_creat, params, st_tcp_server_creat::path, PATH_MAX, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_flush()
void tcp_server_op_flush (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 1126 of file tcp_server_ops.c.
References st_tcp_server_flush::block_size, debug_info, filesystem_close(), filesystem_lseek(), filesystem_open(), filesystem_read(), filesystem_write(), O_CREAT, O_RDONLY, O_WRONLY, st_tcp_server_msg::op_flush, params, ParseURL(), mpi_server_param_st::rank, st_tcp_server_direntry::ret, mpi_server_param_st::size, mpi_server_param_st::srv_name, st_tcp_server_flush::storage_path, tcp_server_comm_write_data(), st_tcp_server_msg::u_st_tcp_server_msg, and st_tcp_server_flush::virtual_path.
Referenced by tcp_server_do_operation().
tcp_server_op_fstat()
void tcp_server_op_fstat (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
tcp_server_op_getattr()
void tcp_server_op_getattr (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 907 of file tcp_server_ops.c.
References st_tcp_server_attr_req::attr, debug_info, mpi_server_param_st::dirbase, filesystem_stat(), st_tcp_server_msg::op_getattr, params, st_tcp_server_getattr::path, PATH_MAX, mpi_server_param_st::srv_name, st_tcp_server_attr_req::status, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_getid()
void tcp_server_op_getid (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 1222 of file tcp_server_ops.c.
References debug_info, st_tcp_server_msg::id, params, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and TCP_SERVER_ID.
tcp_server_op_getnodename() [1/2]
void tcp_server_op_getnodename (tcp_server_param_st * params, int sd, __attribute__((__unused__)) struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 1203 of file tcp_server_ops.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, mpi_server_param_st::dirbase, params, PATH_MAX, serv_name, mpi_server_param_st::srv_name, and tcp_server_comm_write_data().
tcp_server_op_getnodename() [2/2]
void tcp_server_op_getnodename (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Referenced by tcp_server_do_operation().
tcp_server_op_mkdir()
void tcp_server_op_mkdir (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 949 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_mkdir(), st_tcp_server_msg::op_mkdir, params, st_tcp_server_mkdir::path, PATH_MAX, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_open_wos()
void tcp_server_op_open_wos (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 372 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_close(), filesystem_open(), O_RDWR, st_tcp_server_msg::op_open, params, st_tcp_server_open::path, PATH_MAX, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_open_ws()
void tcp_server_op_open_ws (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 334 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_open(), O_RDWR, st_tcp_server_msg::op_open, params, st_tcp_server_open::path, PATH_MAX, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_opendir()
void tcp_server_op_opendir (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 967 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_opendir(), st_tcp_server_msg::op_opendir, params, st_tcp_server_opendir::path, PATH_MAX, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_preload()
void tcp_server_op_preload (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 1045 of file tcp_server_ops.c.
References st_tcp_server_preload::block_size, debug_info, filesystem_close(), filesystem_creat(), filesystem_lseek(), filesystem_open(), filesystem_read(), filesystem_write(), O_RDONLY, st_tcp_server_msg::op_preload, params, ParseURL(), mpi_server_param_st::rank, st_tcp_server_direntry::ret, mpi_server_param_st::size, mpi_server_param_st::srv_name, st_tcp_server_preload::storage_path, tcp_server_comm_write_data(), st_tcp_server_msg::u_st_tcp_server_msg, and st_tcp_server_preload::virtual_path.
Referenced by tcp_server_do_operation().
tcp_server_op_read_wos()
void tcp_server_op_read_wos (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 590 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_close(), filesystem_lseek(), filesystem_open(), filesystem_read(), FREE_AND_NULL, MAX_BUFFER_SIZE, O_RDONLY, st_tcp_server_read::offset, st_tcp_server_msg::op_read, params, st_tcp_server_read::path, PATH_MAX, mpi_server_param_st::size, st_tcp_server_read::size, st_tcp_server_read_req::size, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_read_ws()
void tcp_server_op_read_ws (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 519 of file tcp_server_ops.c.
References debug_info, st_tcp_server_read::fd, filesystem_lseek(), filesystem_read(), FREE_AND_NULL, MAX_BUFFER_SIZE, st_tcp_server_read::offset, st_tcp_server_msg::op_read, params, mpi_server_param_st::size, st_tcp_server_read::size, st_tcp_server_read_req::size, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_readdir()
void tcp_server_op_readdir (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 985 of file tcp_server_ops.c.
References debug_info, st_tcp_server_readdir::dir, st_tcp_server_direntry::end, filesystem_readdir(), st_tcp_server_msg::op_readdir, params, st_tcp_server_direntry::ret, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_rename()
void tcp_server_op_rename (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 884 of file tcp_server_ops.c.
References debug_info, filesystem_rename(), st_tcp_server_rename::new_url, st_tcp_server_rename::old_url, st_tcp_server_msg::op_rename, st_tcp_server_msg::op_rm, params, st_tcp_server_rm::path, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_rm()
void tcp_server_op_rm (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 861 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_unlink(), st_tcp_server_msg::op_rm, params, st_tcp_server_rm::path, PATH_MAX, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_rmdir()
void tcp_server_op_rmdir (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 1026 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, filesystem_rmdir(), st_tcp_server_msg::op_rmdir, params, st_tcp_server_rmdir::path, PATH_MAX, st_tcp_server_direntry::ret, mpi_server_param_st::srv_name, tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_setattr() [1/2]
void tcp_server_op_setattr (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, __attribute__((__unused__)) int rank_client_id)
Definition at line 925 of file tcp_server_ops.c.
References debug_info, params, and mpi_server_param_st::srv_name.
tcp_server_op_setattr() [2/2]
void tcp_server_op_setattr (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Referenced by tcp_server_do_operation().
tcp_server_op_write_wos()
void tcp_server_op_write_wos (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 741 of file tcp_server_ops.c.
References debug_info, mpi_server_param_st::dirbase, st_tcp_server_write::fd, filesystem_close(), filesystem_lseek(), filesystem_open(), filesystem_write(), FREE_AND_NULL, MAX_BUFFER_SIZE, O_WRONLY, st_tcp_server_write::offset, st_tcp_server_msg::op_read, st_tcp_server_msg::op_write, params, st_tcp_server_write::path, PATH_MAX, st_tcp_server_read::size, st_tcp_server_write::size, st_tcp_server_write_req::size, mpi_server_param_st::srv_name, tcp_server_comm_read_data(), tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().
tcp_server_op_write_ws()
void tcp_server_op_write_ws (tcp_server_param_st * params, int sd, struct st_tcp_server_msg * head, int rank_client_id)
Definition at line 678 of file tcp_server_ops.c.
References debug_info, st_tcp_server_write::fd, filesystem_lseek(), filesystem_write(), FREE_AND_NULL, MAX_BUFFER_SIZE, st_tcp_server_write::offset, st_tcp_server_msg::op_read, st_tcp_server_msg::op_write, params, st_tcp_server_read::size, st_tcp_server_write::size, st_tcp_server_write_req::size, mpi_server_param_st::srv_name, tcp_server_comm_read_data(), tcp_server_comm_write_data(), and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_do_operation().