tcp_server_d2xpn.h File Reference
Header file to 'TODO'.
#include <sys/param.h>
#include <stdio.h>
#include <sys/file.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include all_system.h
#include base/utils.h
#include tcp_server_params.h
#include tcp_server_ops.h
#include xpn.h
Macros
#define PRELOAD_SYNC 0
#define PRELOAD_ASYNC 1
Functions
int tcp_server_d2xpn (tcp_server_param_st *params, char *origen, char *destino)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file tcp_server_d2xpn.h.
Macro Definition Documentation
PRELOAD_ASYNC
#define PRELOAD_ASYNC 1
Definition at line 55 of file tcp_server_d2xpn.h.
PRELOAD_SYNC
#define PRELOAD_SYNC 0
Definition at line 54 of file tcp_server_d2xpn.h.
Function Documentation
tcp_server_d2xpn()
int tcp_server_d2xpn (tcp_server_param_st * params, char * origen, char * destino)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
origen 'TODO'.
destino 'TODO'.
Returns
'TODO'.
Definition at line 146 of file tcp_server_d2xpn.c.
References debug_info, mpi_server_param_st::dirbase, mylock(), myunlock(), O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), params, PATH_MAX, mpi_server_param_st::rank, st, TCP_SERVER_PATH_DEFAULT, xpn_init(), and xpn_open().