tcp_server_ops.h File Reference
Header file to 'TODO'.
#include <libgen.h>
#include all_system.h
#include base/filesystem.h
#include base/urlstr.h
#include base/utils.h
#include base/workers.h
#include tcp_server_ops.h
#include tcp_server_comm.h
#include tcp_server_d2xpn.h
#include tcp_server_params.h
Data Structures
struct st_tcp_server_open
This is a struct.
struct st_tcp_server_open_req
This is a struct.
struct st_tcp_server_creat
This is a struct.
struct st_tcp_server_read
This is a struct.
struct st_tcp_server_read_req
This is a struct.
struct st_tcp_server_write
This is a struct.
struct st_tcp_server_write_req
This is a struct.
struct st_tcp_server_close
This is a struct.
struct st_tcp_server_rename
This is a struct.
struct st_tcp_server_rm
This is a struct.
struct st_tcp_server_getattr
This is a struct.
struct st_tcp_server_setattr
This is a struct.
struct st_tcp_server_attr_req
This is a struct.
struct st_tcp_server_mkdir
This is a struct.
struct st_tcp_server_opendir
This is a struct.
struct st_tcp_server_readdir
This is a struct.
struct st_tcp_server_direntry
This is a struct.
struct st_tcp_server_closedir
This is a struct.
struct st_tcp_server_rmdir
This is a struct.
struct st_tcp_server_flush
This is a struct.
struct st_tcp_server_preload
This is a struct.
struct st_tcp_server_end
This is a struct.
struct st_tcp_server_msg
This is a struct.
Macros
#define TCP_SERVER_ID 32
#define TCP_SERVER_OPEN_FILE_WS 0
#define TCP_SERVER_CREAT_FILE_WS 1
#define TCP_SERVER_READ_FILE_WS 2
#define TCP_SERVER_WRITE_FILE_WS 3
#define TCP_SERVER_CLOSE_FILE_WS 4
#define TCP_SERVER_RM_FILE 5
#define TCP_SERVER_RM_FILE_ASYNC 6
#define TCP_SERVER_RENAME_FILE 7
#define TCP_SERVER_GETATTR_FILE 8
#define TCP_SERVER_SETATTR_FILE 9
#define TCP_SERVER_OPEN_FILE_WOS 100
#define TCP_SERVER_CREAT_FILE_WOS 101
#define TCP_SERVER_READ_FILE_WOS 102
#define TCP_SERVER_WRITE_FILE_WOS 103
#define TCP_SERVER_MKDIR_DIR 20
#define TCP_SERVER_RMDIR_DIR 21
#define TCP_SERVER_RMDIR_DIR_ASYNC 22
#define TCP_SERVER_OPENDIR_DIR 23
#define TCP_SERVER_READDIR_DIR 24
#define TCP_SERVER_CLOSEDIR_DIR 25
#define TCP_SERVER_FLUSH_FILE 40
#define TCP_SERVER_PRELOAD_FILE 41
#define TCP_SERVER_STATFS_DIR 60
#define TCP_SERVER_GETNODENAME 61
#define TCP_SERVER_GETID 62
#define TCP_SERVER_FINALIZE 80
#define TCP_SERVER_DISCONNECT 81
#define TCP_SERVER_END -1
Functions
char * tcp_server_op2string (int op_code)
'TODO'.
int tcp_server_do_operation (struct st_th *th, int *the_end)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file tcp_server/tcp_server_ops.h.
Macro Definition Documentation
TCP_SERVER_CLOSE_FILE_WS
#define TCP_SERVER_CLOSE_FILE_WS 4
Definition at line 68 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_CLOSEDIR_DIR
#define TCP_SERVER_CLOSEDIR_DIR 25
Definition at line 91 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_CREAT_FILE_WOS
#define TCP_SERVER_CREAT_FILE_WOS 101
Definition at line 79 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_CREAT_FILE_WS
#define TCP_SERVER_CREAT_FILE_WS 1
Definition at line 65 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_DISCONNECT
#define TCP_SERVER_DISCONNECT 81
Definition at line 110 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_END
#define TCP_SERVER_END -1
Definition at line 111 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_FINALIZE
#define TCP_SERVER_FINALIZE 80
Definition at line 109 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_FLUSH_FILE
#define TCP_SERVER_FLUSH_FILE 40
Definition at line 96 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_GETATTR_FILE
#define TCP_SERVER_GETATTR_FILE 8
Definition at line 72 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_GETID
#define TCP_SERVER_GETID 62
Definition at line 104 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_GETNODENAME
#define TCP_SERVER_GETNODENAME 61
Definition at line 103 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_ID
#define TCP_SERVER_ID 32
Definition at line 54 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_MKDIR_DIR
#define TCP_SERVER_MKDIR_DIR 20
Definition at line 86 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_OPEN_FILE_WOS
#define TCP_SERVER_OPEN_FILE_WOS 100
Definition at line 78 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_OPEN_FILE_WS
#define TCP_SERVER_OPEN_FILE_WS 0
Definition at line 64 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_OPENDIR_DIR
#define TCP_SERVER_OPENDIR_DIR 23
Definition at line 89 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_PRELOAD_FILE
#define TCP_SERVER_PRELOAD_FILE 41
Definition at line 97 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_READ_FILE_WOS
#define TCP_SERVER_READ_FILE_WOS 102
Definition at line 80 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_READ_FILE_WS
#define TCP_SERVER_READ_FILE_WS 2
Definition at line 66 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_READDIR_DIR
#define TCP_SERVER_READDIR_DIR 24
Definition at line 90 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_RENAME_FILE
#define TCP_SERVER_RENAME_FILE 7
Definition at line 71 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_RM_FILE
#define TCP_SERVER_RM_FILE 5
Definition at line 69 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_RM_FILE_ASYNC
#define TCP_SERVER_RM_FILE_ASYNC 6
Definition at line 70 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_RMDIR_DIR
#define TCP_SERVER_RMDIR_DIR 21
Definition at line 87 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_RMDIR_DIR_ASYNC
#define TCP_SERVER_RMDIR_DIR_ASYNC 22
Definition at line 88 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_SETATTR_FILE
#define TCP_SERVER_SETATTR_FILE 9
Definition at line 73 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_STATFS_DIR
#define TCP_SERVER_STATFS_DIR 60
Definition at line 102 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_WRITE_FILE_WOS
#define TCP_SERVER_WRITE_FILE_WOS 103
Definition at line 81 of file tcp_server/tcp_server_ops.h.
TCP_SERVER_WRITE_FILE_WS
#define TCP_SERVER_WRITE_FILE_WS 3
Definition at line 67 of file tcp_server/tcp_server_ops.h.
Function Documentation
tcp_server_do_operation()
int tcp_server_do_operation (struct st_th * th, int * the_end)
'TODO'.
'TODO'
Parameters
th 'TODO'.
the_end 'TODO'.
Returns
'TODO'.
Definition at line 152 of file tcp_server_ops.c.
References DEBUG_BEGIN, DEBUG_END, st_tcp_server_msg::op_close, st_tcp_server_msg::op_closedir, st_tcp_server_msg::op_creat, st_tcp_server_msg::op_flush, st_tcp_server_msg::op_getattr, st_tcp_server_msg::op_mkdir, st_tcp_server_msg::op_open, st_tcp_server_msg::op_opendir, st_tcp_server_msg::op_preload, st_tcp_server_msg::op_read, st_tcp_server_msg::op_readdir, st_tcp_server_msg::op_rename, st_tcp_server_msg::op_rm, st_tcp_server_msg::op_rmdir, st_tcp_server_msg::op_setattr, st_tcp_server_msg::op_write, st_th::params, st_th::sd, TCP_SERVER_CLOSE_FILE_WS, TCP_SERVER_CLOSEDIR_DIR, tcp_server_comm_read_data(), TCP_SERVER_CREAT_FILE_WOS, TCP_SERVER_CREAT_FILE_WS, TCP_SERVER_DISCONNECT, TCP_SERVER_FINALIZE, TCP_SERVER_FLUSH_FILE, TCP_SERVER_GETATTR_FILE, TCP_SERVER_GETNODENAME, TCP_SERVER_MKDIR_DIR, tcp_server_op_close_ws(), tcp_server_op_closedir(), tcp_server_op_creat_wos(), tcp_server_op_creat_ws(), tcp_server_op_flush(), tcp_server_op_getattr(), tcp_server_op_getnodename(), tcp_server_op_mkdir(), tcp_server_op_open_wos(), tcp_server_op_open_ws(), tcp_server_op_opendir(), tcp_server_op_preload(), tcp_server_op_read_wos(), tcp_server_op_read_ws(), tcp_server_op_readdir(), tcp_server_op_rename(), tcp_server_op_rm(), tcp_server_op_rmdir(), tcp_server_op_setattr(), tcp_server_op_write_wos(), tcp_server_op_write_ws(), TCP_SERVER_OPEN_FILE_WOS, TCP_SERVER_OPEN_FILE_WS, TCP_SERVER_OPENDIR_DIR, TCP_SERVER_PRELOAD_FILE, TCP_SERVER_READ_FILE_WOS, TCP_SERVER_READ_FILE_WS, TCP_SERVER_READDIR_DIR, TCP_SERVER_RENAME_FILE, TCP_SERVER_RM_FILE, TCP_SERVER_RMDIR_DIR, TCP_SERVER_SETATTR_FILE, TCP_SERVER_WRITE_FILE_WOS, TCP_SERVER_WRITE_FILE_WS, the_end, st_th::type_op, and st_tcp_server_msg::u_st_tcp_server_msg.
Referenced by tcp_server_run().
tcp_server_op2string()
char * tcp_server_op2string (int op_code)
'TODO'.
'TODO'
Parameters
op_code 'TODO'.
Returns
'TODO'.
Definition at line 28 of file tcp_server_ops.c.
References TCP_SERVER_CLOSE_FILE_WS, TCP_SERVER_CLOSEDIR_DIR, TCP_SERVER_CREAT_FILE_WOS, TCP_SERVER_CREAT_FILE_WS, TCP_SERVER_DISCONNECT, TCP_SERVER_END, TCP_SERVER_FINALIZE, TCP_SERVER_FLUSH_FILE, TCP_SERVER_GETATTR_FILE, TCP_SERVER_GETID, TCP_SERVER_GETNODENAME, TCP_SERVER_MKDIR_DIR, TCP_SERVER_OPEN_FILE_WOS, TCP_SERVER_OPEN_FILE_WS, TCP_SERVER_OPENDIR_DIR, TCP_SERVER_PRELOAD_FILE, TCP_SERVER_READ_FILE_WOS, TCP_SERVER_READ_FILE_WS, TCP_SERVER_READDIR_DIR, TCP_SERVER_RENAME_FILE, TCP_SERVER_RM_FILE, TCP_SERVER_RMDIR_DIR, TCP_SERVER_SETATTR_FILE, TCP_SERVER_STATFS_DIR, TCP_SERVER_WRITE_FILE_WOS, and TCP_SERVER_WRITE_FILE_WS.
Referenced by tcp_server_run().