tcp_server.c File Reference
File to 'TODO'.
#include all_system.h
#include base/utils.h
#include base/ns.h
#include tcp_server/tcp_server_params.h
#include tcp_server/tcp_server_ops.h
#include base/workers.h
#include tcp_server/tcp_server_comm.h
#include tcp_server/tcp_server_d2xpn.h
Functions
void tcp_server_run (struct st_th th)
'TODO'.
void tcp_server_dispatcher (struct st_th th)
'TODO'.
int tcp_server_up (void)
'TODO'.
int tcp_server_down (void)
'TODO'.
int main (int argc, char *argv[])
Variables
tcp_server_param_st params
worker_t worker
int the_end = 0
char serv_name [HOST_NAME_MAX]
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file tcp_server.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 333 of file tcp_server.c.
References params, serv_name, tcp_server_down(), tcp_server_params_get(), tcp_server_params_show(), tcp_server_params_show_usage(), and tcp_server_up().
tcp_server_dispatcher()
void tcp_server_dispatcher (struct st_th th)
'TODO'.
'TODO'.
Parameters
th 'TODO'.
Returns
Nothing.
Definition at line 83 of file tcp_server.c.
References debug_info, FALSE, st_th::function, st_th::id, st_th::params, params, st_th::rank_client_id, st_th::sd, tcp_server_comm_close(), tcp_server_comm_read_operation(), TCP_SERVER_DISCONNECT, TCP_SERVER_FINALIZE, tcp_server_run(), the_end, st_th::type_op, and st_th::wait4me.
Referenced by tcp_server_up().
tcp_server_down()
int tcp_server_down (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 249 of file tcp_server.c.
References debug_info, debug_msg_init(), tcp_server_param_st::dns_file, ns_lookup(), params, st_th::sd, serv_name, tcp_server_param_st::shutdown_file, tcp_server_comm_close(), tcp_server_comm_connect(), tcp_server_comm_destroy(), tcp_server_comm_init(), tcp_server_comm_write_data(), TCP_SERVER_FINALIZE, tcp_server_param_st::thread_mode, worker, workers_destroy(), and workers_init().
Referenced by main().
tcp_server_run()
void tcp_server_run (struct st_th th)
'TODO'.
'TODO'.
Parameters
th 'TODO'.
Returns
Nothing.
Definition at line 65 of file tcp_server.c.
References debug_info, st_th::id, tcp_server_do_operation(), tcp_server_op2string(), the_end, and st_th::type_op.
Referenced by tcp_server_dispatcher().
tcp_server_up()
int tcp_server_up (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 157 of file tcp_server.c.
References tcp_server_param_st::client, debug_info, debug_msg_init(), FALSE, st_th::function, st_th::params, params, st_th::rank_client_id, st_th::sd, serv_name, tcp_server_comm_accept(), tcp_server_comm_destroy(), tcp_server_comm_init(), tcp_server_dispatcher(), the_end, tcp_server_param_st::thread_mode, st_th::type_op, st_th::wait4me, worker, workers_destroy(), workers_init(), and workers_launch().
Referenced by main().
Variable Documentation
params
tcp_server_param_st params
Definition at line 47 of file tcp_server.c.
Referenced by main(), tcp_server_dispatcher(), tcp_server_down(), and tcp_server_up().
serv_name
char serv_name[HOST_NAME_MAX]
Definition at line 50 of file tcp_server.c.
Referenced by main(), tcp_server_down(), and tcp_server_up().
the_end
int the_end = 0
Definition at line 49 of file tcp_server.c.
Referenced by tcp_server_dispatcher(), tcp_server_run(), and tcp_server_up().
worker
worker_t worker
Definition at line 48 of file tcp_server.c.
Referenced by tcp_server_down(), and tcp_server_up().