time_misc.h File Reference
Header file to 'TODO'.
#include all_system.h
Macros
#define USECPSEC 1000000
Functions
void TIME_MISC_Timer (struct timeval *t)
Get a timestamp 't' at current time.
void TIME_MISC_DiffTime (struct timeval *to, struct timeval *tn, struct timeval *dif)
Compute 'dig = tn - to'.
void TIME_MISC_AddTime (struct timeval *to, struct timeval *tn, struct timeval *sum)
Compute 'sum = tn + to'.
float TIME_MISC_TimevaltoFloat (struct timeval *timet)
Return a timestamp as seconds.
float TIME_MISC_TimevaltoMicro (struct timeval *timet)
Return a timestamp as microseconds.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file time_misc.h.
Macro Definition Documentation
USECPSEC
#define USECPSEC 1000000
Definition at line 48 of file time_misc.h.
Function Documentation
TIME_MISC_AddTime()
void TIME_MISC_AddTime (struct timeval * to, struct timeval * tn, struct timeval * sum)
Compute 'sum = tn + to'.
Parameters
to initial instant.
tn final instant.
sum the addition value ('tn + to').
Returns
Nothing.
Definition at line 70 of file time_misc.c.
References sum, and USECPSEC.
TIME_MISC_DiffTime()
void TIME_MISC_DiffTime (struct timeval * to, struct timeval * tn, struct timeval * dif)
Compute 'dig = tn - to'.
Parameters
to initial instant.
tn final instant.
dif the substaction value ('tn - to').
Returns
Nothing.
Definition at line 52 of file time_misc.c.
References USECPSEC.
Referenced by mpi_server_comm_init(), and tcp_server_comm_init().
TIME_MISC_Timer()
void TIME_MISC_Timer (struct timeval * t)
Get a timestamp 't' at current time.
Parameters
t the timestamp.
Returns
Nothing.
Definition at line 41 of file time_misc.c.
Referenced by mpi_server_comm_init(), and tcp_server_comm_init().
TIME_MISC_TimevaltoFloat()
float TIME_MISC_TimevaltoFloat (struct timeval * timet)
Return a timestamp as seconds.
Parameters
timet the timestamp.
Returns
timestamp as seconds.
Definition at line 81 of file time_misc.c.
References USECPSEC.
Referenced by mpi_server_comm_init(), and tcp_server_comm_init().
TIME_MISC_TimevaltoMicro()
float TIME_MISC_TimevaltoMicro (struct timeval * timet)
Return a timestamp as microseconds.
Parameters
timet the timestamp.
Returns
timestamp as microseconds.
Definition at line 86 of file time_misc.c.
References USECPSEC.