trace_msg.c File Reference
File to 'TODO'.
#include base/trace_msg.h
Functions
void TRACE_MSG_setPrinter (int(*printer)(const char *, va_list))
Set 'printer' dispacher.
void TRACE_MSG_doPrint (char *fto,...)
void TRACE_MSG_VPrintF (int line, char *name, long pid, int type, char *fto, va_list vl)
Write a message using the format and the argument list given to it.
void TRACE_MSG_PrintF (int line, char *name, long pid, int type, char *fto,...)
Write a message using the format and arguments given to it.
Variables
int(* TRACE_MSG_PrintMsg)(const char *, va_list) = NULL
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file trace_msg.c.
Function Documentation
TRACE_MSG_doPrint()
void TRACE_MSG_doPrint (char * fto, ...)
Definition at line 52 of file trace_msg.c.
References TRACE_MSG_PrintMsg.
Referenced by TRACE_MSG_VPrintF().
TRACE_MSG_PrintF()
void TRACE_MSG_PrintF (int line, char * name, long pid, int type, char * fto, ...)
Write a message using the format and arguments given to it.
Parameters
line The line of code where message is generated.
name The file name at the code where message is generated.
pid The process that send this message.
type The type of message.
fto The message format.
Returns
Nothing.
Definition at line 89 of file trace_msg.c.
References TRACE_MSG_PrintMsg, and TRACE_MSG_VPrintF().
TRACE_MSG_setPrinter()
void TRACE_MSG_setPrinter (int(*)(const char *, va_list) printer)
Set 'printer' dispacher.
Set 'printer' dispacher.
Parameters
printer The printer function to be used.
Returns
Nothing.
Definition at line 46 of file trace_msg.c.
References TRACE_MSG_PrintMsg.
TRACE_MSG_VPrintF()
void TRACE_MSG_VPrintF (int line, char * name, long pid, int type, char * fto, va_list vl)
Write a message using the format and the argument list given to it.
Parameters
line The line of code where message is generated.
name The file name at the code where message is generated.
pid The process that send this message.
type The type of message.
fto The message format.
vl The argument list.
Returns
Nothing.
Definition at line 66 of file trace_msg.c.
References STRING_MISC_Dvsprintf(), TRACE_MSG_doPrint(), and TRACE_MSG_PrintMsg.
Referenced by TRACE_MSG_PrintF().
Variable Documentation
TRACE_MSG_PrintMsg
int(* TRACE_MSG_PrintMsg) (const char *, va_list) (const char * , va_list) = NULL
Definition at line 40 of file trace_msg.c.
Referenced by TRACE_MSG_doPrint(), TRACE_MSG_PrintF(), TRACE_MSG_setPrinter(), and TRACE_MSG_VPrintF().