urlstr.c File Reference
File to 'TODO'.
#include base/urlstr.h
Functions
int getURLProtocol (char *url, char *protocol)
'TODO'.
int getURLServer (char *url, char *server)
'TODO'.
int getURLPort (char *url, char *port)
'TODO'.
int getURLDir (char *url, char *dir)
'TODO'.
int clear_slash (char *path)
'TODO'.
int ParseURL (char *url, char *protocol, char *login, char *passwd, char *server, char *port, char *dir)
'TODO'.
int getDirWithURL (char *url, char *dir)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file urlstr.c.
Function Documentation
clear_slash()
int clear_slash (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 231 of file urlstr.c.
References PATH_MAX.
Referenced by ParseURL().
getDirWithURL()
int getDirWithURL (char * url, char * dir)
'TODO'.
'TODO'.
Parameters
url 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 345 of file urlstr.c.
References getURLDir(), and PATH_MAX.
Referenced by nfi_nfs3_create(), nfi_nfs3_mkdir(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs_create(), nfi_nfs_mkdir(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), nfs3_open(), and nfs_open().
getURLDir()
int getURLDir (char * url, char * dir)
'TODO'.
'TODO'.
Parameters
url 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 184 of file urlstr.c.
References getURLPort(), getURLProtocol(), and getURLServer().
Referenced by getDirWithURL(), and ParseURL().
getURLPort()
int getURLPort (char * url, char * port)
'TODO'.
'TODO'.
Parameters
url 'TODO'.
port 'TODO'.
Returns
'TODO'.
Definition at line 144 of file urlstr.c.
References getURLServer().
Referenced by getURLDir(), and ParseURL().
getURLProtocol()
int getURLProtocol (char * url, char * protocol)
'TODO'.
'TODO'.
Parameters
url 'TODO'.
protocol 'TODO'.
Returns
'TODO'.
Definition at line 50 of file urlstr.c.
Referenced by getURLDir(), getURLServer(), and ParseURL().
getURLServer()
int getURLServer (char * url, char * server)
'TODO'.
'TODO'.
Parameters
url 'TODO'.
server 'TODO'.
Returns
'TODO'.
Definition at line 110 of file urlstr.c.
References getURLProtocol().
Referenced by getURLDir(), getURLPort(), and ParseURL().
ParseURL()
int ParseURL (char * url, char * protocol, char * login, char * passwd, char * server, char * port, char * dir)
'TODO'.
'TODO'.
Parameters
url 'TODO'.
protocol 'TODO'.
login 'TODO'.
passwd 'TODO'.
server 'TODO'.
port 'TODO'.
dir 'TODO'.
Returns
'TODO'.
Definition at line 262 of file urlstr.c.
References clear_slash(), getURLDir(), getURLPort(), getURLProtocol(), and getURLServer().
Referenced by mpi_server_op_flush(), mpi_server_op_preload(), nfi_local_create(), nfi_local_getattr(), nfi_local_init(), nfi_local_mkdir(), nfi_local_open(), nfi_local_opendir(), nfi_local_reconnect(), nfi_local_remove(), nfi_local_rename(), nfi_local_rmdir(), nfi_mpi_server_create(), nfi_mpi_server_getattr(), nfi_mpi_server_init(), nfi_mpi_server_mkdir(), nfi_mpi_server_open(), nfi_mpi_server_opendir(), nfi_mpi_server_reconnect(), nfi_mpi_server_remove(), nfi_mpi_server_rename(), nfi_mpi_server_rmdir(), nfi_nfs3_create(), nfi_nfs3_destroy(), nfi_nfs3_disconnect(), nfi_nfs3_init(), nfi_nfs3_mkdir(), nfi_nfs3_reconnect(), nfi_nfs3_remove(), nfi_nfs3_rmdir(), nfi_nfs_create(), nfi_nfs_destroy(), nfi_nfs_disconnect(), nfi_nfs_init(), nfi_nfs_mkdir(), nfi_nfs_reconnect(), nfi_nfs_remove(), nfi_nfs_rename(), nfi_nfs_rmdir(), nfi_tcp_server_create(), nfi_tcp_server_getattr(), nfi_tcp_server_init(), nfi_tcp_server_mkdir(), nfi_tcp_server_open(), nfi_tcp_server_opendir(), nfi_tcp_server_reconnect(), nfi_tcp_server_remove(), nfi_tcp_server_rename(), nfi_tcp_server_rmdir(), nfs3_open(), nfs_open(), tcp_server_op_flush(), tcp_server_op_preload(), and XpnGetServer().