workers.h File Reference
Header file to 'TODO'.
#include all_system.h
#include workers_common.h
#include workers_ondemand.h
#include workers_pool.h
#include base/debug_msg.h
Data Structures
struct worker_t
This is a struct.
Macros
#define TH_NOT 0
#define TH_POOL 1
#define TH_OP 2
Functions
int workers_init (worker_t *w, int thread_mode)
'TODO'.
void workers_destroy (worker_t *w)
'TODO'.
int workers_launch (worker_t *w, struct st_th *th_arg, void(*worker_function)(struct st_th))
'TODO'.
int workers_wait (worker_t *w, struct st_th *th_arg)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file workers.h.
Macro Definition Documentation
TH_NOT
#define TH_NOT 0
Definition at line 48 of file workers.h.
TH_OP
#define TH_OP 2
Definition at line 50 of file workers.h.
TH_POOL
#define TH_POOL 1
Definition at line 49 of file workers.h.
Function Documentation
workers_destroy()
void workers_destroy (worker_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
Nothing.
Definition at line 147 of file workers.c.
References debug_error, debug_info, TH_NOT, TH_OP, TH_POOL, worker_t::thread_mode, worker_t::w1, worker_t::w2, worker_pool_destroy(), and workers_ondemand_destroy().
Referenced by mpi_server_up(), nfiworker_destroy(), tcp_server_down(), and tcp_server_up().
workers_init()
int workers_init (worker_t * w, int thread_mode)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
thread_mode 'TODO'.
Returns
'TODO'.
Definition at line 40 of file workers.c.
References debug_error, debug_info, TH_NOT, TH_OP, TH_POOL, worker_t::thread_mode, worker_t::w1, worker_t::w2, worker_ondemand_init(), and worker_pool_init().
Referenced by mpi_server_up(), nfiworker_init(), tcp_server_down(), and tcp_server_up().
workers_launch()
int workers_launch (worker_t * w, struct st_th * th_arg, void(*)(struct st_th) worker_function)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
th_arg 'TODO'.
worker_function 'TODO'.
Returns
'TODO'.
Definition at line 77 of file workers.c.
References debug_error, debug_info, TH_NOT, TH_OP, TH_POOL, worker_t::thread_mode, worker_t::w1, worker_t::w2, worker_ondemand_launch(), and worker_pool_enqueue().
Referenced by mpi_server_dispatcher(), mpi_server_up(), nfiworker_launch(), and tcp_server_up().
workers_wait()
int workers_wait (worker_t * w, struct st_th * th_arg)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
th_arg 'TODO'.
Returns
'TODO'.
Definition at line 113 of file workers.c.
References debug_error, debug_info, TH_NOT, TH_OP, TH_POOL, worker_t::thread_mode, worker_ondemand_wait(), and worker_pool_wait().
Referenced by nfiworker_wait().