workers_ondemand.h File Reference
Header file to 'TODO'.
#include all_system.h
#include workers_common.h
Data Structures
struct worker_ondemand_t
This is a struct.
Functions
int worker_ondemand_init (worker_ondemand_t *w)
'TODO'.
void workers_ondemand_destroy (worker_ondemand_t *w)
'TODO'.
int worker_ondemand_launch (worker_ondemand_t *w, struct st_th *th_arg, void(*worker_function)(struct st_th))
'TODO'.
int worker_ondemand_wait (struct st_th *th_arg)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file workers_ondemand.h.
Function Documentation
worker_ondemand_init()
int worker_ondemand_init (worker_ondemand_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
'TODO'.
Definition at line 112 of file workers_ondemand.c.
References DEBUG_BEGIN, DEBUG_END, TRUE, and st_th::w.
Referenced by workers_init().
worker_ondemand_launch()
int worker_ondemand_launch (worker_ondemand_t * w, struct st_th * th_arg, void(*)(struct st_th) worker_function)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
th_arg 'TODO'.
worker_function 'TODO'.
Returns
'TODO'.
Definition at line 128 of file workers_ondemand.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, st_th::function, st_th::id, STACK_SIZE, st_th::th_worker, TRUE, st_th::v, st_th::w, and worker_run().
Referenced by workers_launch().
worker_ondemand_wait()
int worker_ondemand_wait (struct st_th * th_arg)
'TODO'.
'TODO'.
Parameters
th_arg 'TODO'.
Returns
'TODO'.
Definition at line 175 of file workers_ondemand.c.
References st_th::c_wait, DEBUG_BEGIN, DEBUG_END, st_th::m_wait, st_th::r_wait, and TRUE.
Referenced by workers_wait().
workers_ondemand_destroy()
void workers_ondemand_destroy (worker_ondemand_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
Nothing.
Definition at line 193 of file workers_ondemand.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, and st_th::w.
Referenced by workers_destroy().