workers_ondemand.c File Reference
File to 'TODO'.
#include workers_ondemand.h
Functions
void * worker_run (void *arg)
'TODO'.
int worker_ondemand_init (worker_ondemand_t *w)
'TODO'.
int worker_ondemand_launch (worker_ondemand_t *w, struct st_th *th_arg, void(*worker_function)(struct st_th))
'TODO'.
int worker_ondemand_wait (struct st_th *th_arg)
'TODO'.
void workers_ondemand_destroy (worker_ondemand_t *w)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file workers_ondemand.c.
Function Documentation
worker_ondemand_init()
int worker_ondemand_init (worker_ondemand_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
'TODO'.
Definition at line 112 of file workers_ondemand.c.
References DEBUG_BEGIN, DEBUG_END, TRUE, and st_th::w.
Referenced by workers_init().
worker_ondemand_launch()
int worker_ondemand_launch (worker_ondemand_t * w, struct st_th * th_arg, void(*)(struct st_th) worker_function)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
th_arg 'TODO'.
worker_function 'TODO'.
Returns
'TODO'.
Definition at line 128 of file workers_ondemand.c.
References DEBUG_BEGIN, DEBUG_END, debug_error, debug_info, st_th::function, st_th::id, STACK_SIZE, st_th::th_worker, TRUE, st_th::v, st_th::w, and worker_run().
Referenced by workers_launch().
worker_ondemand_wait()
int worker_ondemand_wait (struct st_th * th_arg)
'TODO'.
'TODO'.
Parameters
th_arg 'TODO'.
Returns
'TODO'.
Definition at line 175 of file workers_ondemand.c.
References st_th::c_wait, DEBUG_BEGIN, DEBUG_END, st_th::m_wait, st_th::r_wait, and TRUE.
Referenced by workers_wait().
worker_run()
void * worker_run (void * arg)
'TODO'.
'TODO'.
Parameters
arg 'TODO'.
Returns
'TODO'.
Definition at line 49 of file workers_ondemand.c.
References worker_ondemand_t::busy_worker, worker_ondemand_t::c_nworkers, st_th::c_wait, worker_ondemand_t::c_worker, DEBUG_BEGIN, DEBUG_END, debug_info, FALSE, st_th::function, st_th::m_wait, worker_ondemand_t::m_worker, worker_ondemand_t::n_workers, st_th::r_wait, TRUE, st_th::v, st_th::w, and st_th::wait4me.
Referenced by worker_ondemand_launch().
workers_ondemand_destroy()
void workers_ondemand_destroy (worker_ondemand_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
Nothing.
Definition at line 193 of file workers_ondemand.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, and st_th::w.
Referenced by workers_destroy().