workers_pool.h File Reference
Header file to 'TODO'.
#include all_system.h
#include workers_common.h
Data Structures
struct worker_pool_t
This is a struct.
Macros
#define POOL_OVERSUSCRIPTION 2
#define TH_FINALIZE 200
Functions
int worker_pool_init (worker_pool_t *w)
'TODO'.
void worker_pool_destroy (worker_pool_t *w)
'TODO'.
void worker_pool_enqueue (worker_pool_t *w, struct st_th *th_arg, void(*worker_function)(struct st_th))
'TODO'.
struct st_th worker_pool_dequeue (worker_pool_t *w)
'TODO'.
int worker_pool_wait (struct st_th *th_arg)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file workers_pool.h.
Macro Definition Documentation
POOL_OVERSUSCRIPTION
#define POOL_OVERSUSCRIPTION 2
Definition at line 42 of file workers_pool.h.
TH_FINALIZE
#define TH_FINALIZE 200
Definition at line 44 of file workers_pool.h.
Function Documentation
worker_pool_dequeue()
struct st_th worker_pool_dequeue (worker_pool_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
'TODO'.
Definition at line 154 of file workers_pool.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, st_th::id, MAX_OPERATIONS, TH_FINALIZE, st_th::type_op, and st_th::w.
Referenced by worker_pool_function().
worker_pool_destroy()
void worker_pool_destroy (worker_pool_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
Nothing.
Definition at line 213 of file workers_pool.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, TH_FINALIZE, st_th::type_op, st_th::w, and worker_pool_enqueue().
Referenced by workers_destroy().
worker_pool_enqueue()
void worker_pool_enqueue (worker_pool_t * w, struct st_th * th_arg, void(*)(struct st_th) worker_function)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
th_arg 'TODO'.
worker_function 'TODO'.
Returns
Nothing.
Definition at line 116 of file workers_pool.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, st_th::function, st_th::id, MAX_OPERATIONS, st_th::rank_client_id, st_th::v, and st_th::w.
Referenced by worker_pool_destroy(), and workers_launch().
worker_pool_init()
int worker_pool_init (worker_pool_t * w)
'TODO'.
'TODO'.
Parameters
w 'TODO'.
Returns
'TODO'.
Definition at line 81 of file workers_pool.c.
References DEBUG_BEGIN, DEBUG_END, debug_info, POOL_OVERSUSCRIPTION, st_th::w, and worker_pool_function().
Referenced by workers_init().
worker_pool_wait()
int worker_pool_wait (struct st_th * th_arg)
'TODO'.
'TODO'.
Parameters
th_arg 'TODO'.
Returns
'TODO'.
Definition at line 195 of file workers_pool.c.
References st_th::c_wait, DEBUG_BEGIN, DEBUG_END, st_th::m_wait, st_th::r_wait, and TRUE.
Referenced by workers_wait().