xpn-statfs.c File Reference
#include <stdlib.h>
#include <sys/param.h>
#include <stdio.h>
#include <sys/file.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include xpn.h
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 32 of file xpn-statfs.c.
References exit(), xpn_destroy(), xpn_init(), and xpn_mkdir().