xpn-ls.c File Reference
#include <stdlib.h>
#include <string.h>
#include <sys/param.h>
#include <stdio.h>
#include <sys/file.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <pwd.h>
#include <sys/types.h>
#include xpn.h
Macros
#define NFSMAXPATHLEN 1024
Functions
void get_perm (int attr, char *attrstr)
void del_slash (char *path)
int main (int argc, char *argv[])
Macro Definition Documentation
NFSMAXPATHLEN
#define NFSMAXPATHLEN 1024
Definition at line 35 of file xpn-ls.c.
Function Documentation
del_slash()
void del_slash (char * path)
Definition at line 52 of file xpn-ls.c.
References NFSMAXPATHLEN.
Referenced by main().
get_perm()
void get_perm (int attr, char * attrstr)
Definition at line 37 of file xpn-ls.c.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 80 of file xpn-ls.c.
References del_slash(), exit(), get_perm(), NFSMAXPATHLEN, st, xpn_closedir(), xpn_destroy(), xpn_init(), xpn_opendir(), xpn_readdir(), and xpn_stat().