xpn-rm.c File Reference
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include <pthread.h>
#include <stdlib.h>
#include <ctype.h>
#include <fcntl.h>
#include xpn.h
Functions
void usage (char *program_name)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 36 of file xpn-rm.c.
References exit(), unlink(), usage(), xpn_destroy(), xpn_init(), and xpn_unlink().
usage()
void usage (char * program_name)
Definition at line 31 of file xpn-rm.c.
References program_name.