xpn-cat.c File Reference
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include <pthread.h>
#include <stdlib.h>
#include <ctype.h>
#include <fcntl.h>
#include xpn.h
Macros
#define BAR_LENGTH 50
#define KB (1024)
#define MB (KB * KB)
Functions
void usage (char *program_name)
int main (int argc, char *argv[])
Variables
struct stat st
ssize_t sum
Macro Definition Documentation
BAR_LENGTH
#define BAR_LENGTH 50
Definition at line 31 of file xpn-cat.c.
KB
#define KB (1024)
Definition at line 34 of file xpn-cat.c.
MB
#define MB (KB * KB)
Definition at line 38 of file xpn-cat.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 49 of file xpn-cat.c.
References close(), exit(), KB, O_RDONLY, open(), read(), st, sum, usage(), xpn_close(), xpn_destroy(), xpn_init(), xpn_open(), xpn_read(), and xpn_stat().
usage()
void usage (char * program_name)
Definition at line 44 of file xpn-cat.c.
References program_name.
Variable Documentation
st
struct stat st
Definition at line 41 of file xpn-cat.c.
Referenced by __fxstat64(), __lxstat64(), __xstat64(), add_xpn_file_to_fdstable(), main(), mpi_server_d2xpn(), nfi_local_create(), nfi_local_getattr(), nfi_local_mkdir(), nfi_local_setattr(), stat64_to_stat(), stat_to_stat64(), tcp_server_d2xpn(), xpn_simple_lseek(), XpnGetAtribFd(), and XpnGetAtribPath().
sum
ssize_t sum
Definition at line 42 of file xpn-cat.c.
Referenced by main(), and TIME_MISC_AddTime().