xpn_stdio.c File Reference
File to 'TODO'.
#include xpn.h
#include xpn_client/xpn/xpn_simple/xpn_simple_lib.h
Functions
FILE * xpn_fopen (const char *name, const char *mode)
'TODO'.
int xpn_fclose (FILE *fp)
'TODO'.
size_t xpn_fread (void *ptr, size_t size, size_t nmemb, register FILE *stream)
size_t xpn_fwrite (const void *ptr, size_t size, size_t nmemb, register FILE *stream)
int xpn_fflush (FILE *stream)
'TODO'.
int xpn_fseek (FILE *stream, long int offset, int whence)
long xpn_ftell (FILE *stream)
'TODO'.
void xpn_rewind (FILE *stream)
'TODO'.
int xpn_preload (const char *virtual_path, const char *storage_path)
'TODO'.
int xpn_flush (const char *virtual_path, const char *storage_path)
'TODO'.
int xpn_fgetc (FILE *stream)
'TODO'.
char * xpn_fgets (char *s, int tam, FILE *stream)
'TODO'.
int xpn_getc (FILE *stream)
int xpn_fileno (FILE *stream)
'TODO'.
int xpn_ferror (FILE *stream)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_stdio.c.
Function Documentation
xpn_fclose()
int xpn_fclose (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 50 of file xpn_stdio.c.
References xpn_simple_fclose().
xpn_ferror()
int xpn_ferror (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 135 of file xpn_stdio.c.
References xpn_simple_ferror().
xpn_fflush()
int xpn_fflush (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 69 of file xpn_stdio.c.
References xpn_simple_fflush().
xpn_fgetc()
int xpn_fgetc (FILE * stream)
'TODO'.
'TODO'.
Parameters
flujo 'TODO'.
Returns
'TODO'.
Definition at line 111 of file xpn_stdio.c.
References xpn_simple_fgetc().
xpn_fgets()
char * xpn_fgets (char * s, int tam, FILE * flujo)
'TODO'.
'TODO'.
Parameters
s 'TODO'.
tam 'TODO'.
flujo 'TODO'.
Returns
'TODO'.
Definition at line 116 of file xpn_stdio.c.
References xpn_simple_fgets().
xpn_fileno()
int xpn_fileno (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 130 of file xpn_stdio.c.
References xpn_simple_fileno().
xpn_flush()
int xpn_flush (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 102 of file xpn_stdio.c.
References xpn_simple_flush().
xpn_fopen()
FILE * xpn_fopen (const char * filename, const char * mode)
'TODO'.
'TODO'.
Parameters
filename 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 45 of file xpn_stdio.c.
References xpn_simple_fopen().
xpn_fread()
size_t xpn_fread (void * ptr, size_t size, size_t nmemb, register FILE * stream)
Definition at line 59 of file xpn_stdio.c.
References xpn_simple_fread().
xpn_fseek()
int xpn_fseek (FILE * stream, long int offset, int whence)
Definition at line 78 of file xpn_stdio.c.
References xpn_simple_fseek().
xpn_ftell()
long xpn_ftell (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 83 of file xpn_stdio.c.
References xpn_simple_ftell().
xpn_fwrite()
size_t xpn_fwrite (const void * ptr, size_t size, size_t nmemb, register FILE * stream)
Definition at line 64 of file xpn_stdio.c.
References xpn_simple_fwrite().
xpn_getc()
int xpn_getc (FILE * stream)
Definition at line 121 of file xpn_stdio.c.
References xpn_simple_getc().
xpn_preload()
int xpn_preload (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 97 of file xpn_stdio.c.
References xpn_simple_preload().
xpn_rewind()
void xpn_rewind (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
Nothing.
Definition at line 88 of file xpn_stdio.c.
References xpn_simple_rewind().