xpn_policy_open.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_policy_open.h
Functions
ssize_t XpnGetSizeThreads (struct xpn_partition *p)
'TODO'.
void XpnGetURLServer (struct nfi_server *serv, char *abs_path, char *url_serv)
'TODO'.
int XpnGetServers (int op, int pd, __attribute__((__unused__)) char *abs_path, int fd, struct nfi_server ***servers, int type)
TODO: ** int op -> not used (!) ** XpnGetServers(....
int XpnCreateMetadata (struct xpn_metadata *mdata, int pd, char *path)
'TODO'.
int XpnGetMetadataPos (struct xpn_metadata *mdata, int pos)
'TODO'.
int XpnUpdateMetadata (__attribute__((__unused__)) struct xpn_metadata *mdata, __attribute__((__unused__)) int nserv, __attribute__((__unused__)) struct nfi_server **servers, __attribute__((__unused__)) struct xpn_fh *fh, __attribute__((__unused__)) char *path)
int XpnReadMetadata (struct xpn_metadata *mdata, __attribute__((__unused__)) int nserv, struct nfi_server **servers, struct xpn_fh *fh, char *path, int pd)
int XpnGetFh (struct xpn_metadata *mdata, struct nfi_fhandle **fh, struct nfi_server *servers, char *path)
'TODO'.
int XpnGetAtribFd (int fd, struct stat *st)
'TODO'.
int XpnGetAtribPath (char *path, struct stat *st)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_policy_open.c.
Function Documentation
XpnCreateMetadata()
int XpnCreateMetadata (struct xpn_metadata * mdata, int pd, char * path)
'TODO'.
'TODO'.
Parameters
mdata 'TODO'.
pd 'TODO'.
path 'TODO'.
Returns
'TODO'.
Definition at line 209 of file xpn_policy_open.c.
References xpn_partition::block_size, xpn_metadata::block_size, xpn_partition::data_nserv, xpn_metadata::data_nserv, hash(), xpn_metadata::id, xpn_partition::meta_nserv, xpn_metadata::meta_nserv, xpn_metadata::policy, xpn_metadata::policy_size, xpn_partition::type, xpn_metadata::type, xpn_metadata::type_policy, xpn_metadata::version, XPN_MAX_PART, and xpn_parttable.
Referenced by xpn_internal_creat(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_preload(), and XpnReadMetadata().
XpnGetAtribFd()
int XpnGetAtribFd (int fd, struct stat * st)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
st 'TODO'.
Returns
'TODO'.
Definition at line 439 of file xpn_policy_open.c.
References nfi_attr::at_atime, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, nfi_attr::at_type, xpn_filedesc::id, nfi_worker_do_getattr(), nfiworker_wait(), op_xpn_getattr, xpn_filedesc::path, xpn_metadata::policy, st, nfi_attr::st_dev, nfi_attr::st_ino, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, xpn_err(), xpn_file_table, XPN_HEADER_SIZE, XPNERR_REMOVE, XpnGetFh(), and XpnGetServers().
Referenced by xpn_simple_fstat().
XpnGetAtribPath()
int XpnGetAtribPath (char * path, struct stat * st)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
st 'TODO'.
Returns
'TODO'.
Definition at line 547 of file xpn_policy_open.c.
References nfi_attr::at_atime, nfi_attr::at_blocks, nfi_attr::at_ctime, nfi_attr::at_mode, nfi_attr::at_mtime, nfi_attr::at_nlink, nfi_attr::at_size, hash(), xpn_fh::n_nfih, nfi_worker_do_getattr(), xpn_fh::nfih, nfiworker_wait(), op_xpn_getattr, PATH_MAX, st, nfi_attr::st_dev, nfi_attr::st_ino, nfi_fhandle::url, XPN_DATA_SERVER, XPN_DEBUG_END_ARGS1, xpn_err(), XPN_HEADER_SIZE, XPNERR_NOMEMORY, XPNERR_PART_NOEXIST, XPNERR_REMOVE, XpnGetPartition(), XpnGetServers(), and XpnGetURLServer().
Referenced by xpn_simple_stat().
XpnGetFh()
int XpnGetFh (struct xpn_metadata * mdata, struct nfi_fhandle ** fh, struct nfi_server * servers, char * path)
'TODO'.
'TODO'.
Parameters
mdata 'TODO'.
fh 'TODO'.
servers 'TODO'.
path 'TODO'.
Returns
'TODO'.
Definition at line 378 of file xpn_policy_open.c.
References nfi_ops::nfi_open, nfi_ops::nfi_opendir, nfi_server::ops, PATH_MAX, xpn_metadata::type_policy, XPN_DEBUG_BEGIN, XPN_DEBUG_END, and XpnGetURLServer().
Referenced by xpn_pread(), xpn_pwrite(), xpn_sread(), xpn_swrite(), XpnGetAtribFd(), XpnGetEntry(), and XpnReadMetadata().
XpnGetMetadataPos()
int XpnGetMetadataPos (struct xpn_metadata * mdata, int pos)
'TODO'.
'TODO'.
Parameters
mdata 'TODO'.
pos 'TODO'.
Returns
'TODO'.
Definition at line 274 of file xpn_policy_open.c.
References xpn_metadata::data_nserv, policy::first_node, xpn_metadata::policy, and xpn_metadata::type_policy.
Referenced by xpn_internal_creat(), xpn_pread(), xpn_pwrite(), xpn_simple_flush(), and xpn_simple_preload().
XpnGetServers()
int XpnGetServers (int op, int pd, __attribute__((__unused__)) char * abs_path, int fd, struct nfi_server *** servers, int type)
TODO: ** int op -> not used (!) ** XpnGetServers(....
int type==XPN_META_SERVER) -> XpnGetServers_mdata(....) ; ** fd < 0 => XpnGetServers_data_by_path(....) ; ** fd > 0 => XpnGetServers_data_by_fd(....) ;
Returns the data or metadata servers.
Parameters
op Flag operation.
pd Partition id.
abs_path Absolute path.
fd File descriptor.
servers [out] The data or metadata servers to be obtained.
type Metadata or data server.
Returns
The number of data or metadata servers on success or -1 on error,
Definition at line 103 of file xpn_policy_open.c.
References xpn_partition::data_nserv, xpn_partition::data_serv, xpn_filedesc::data_vfh, xpn_partition::meta_nserv, xpn_partition::meta_serv, xpn_filedesc::meta_vfh, xpn_fh::n_nfih, xpn_filedesc::part, XPN_DATA_SERVER, xpn_file_table, XPN_MAX_FILE, XPN_MAX_PART, XPN_META_SERVER, and xpn_parttable.
Referenced by xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), xpn_pread(), xpn_pwrite(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), xpn_sread(), xpn_swrite(), XpnGetAtribFd(), XpnGetAtribPath(), and XpnGetEntry().
XpnGetSizeThreads()
ssize_t XpnGetSizeThreads (struct xpn_partition * p)
'TODO'.
'TODO'.
Parameters
p 'TODO'.
Returns
'TODO'.
Definition at line 41 of file xpn_policy_open.c.
References xpn_partition::size_threads.
Referenced by XpnSearchSlotFile().
XpnGetURLServer()
void XpnGetURLServer (struct nfi_server * serv, char * abs_path, char * url_serv)
'TODO'.
'TODO'.
Parameters
serv 'TODO'.
abs_path 'TODO'.
url_serv 'TODO'.
Returns
Nothing.
Definition at line 46 of file xpn_policy_open.c.
References PATH_MAX, and nfi_server::url.
Referenced by xpn_internal_creat(), xpn_internal_remove(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), XpnGetAtribPath(), and XpnGetFh().
XpnReadMetadata()
int XpnReadMetadata (struct xpn_metadata * mdata, __attribute__((__unused__)) int nserv, struct nfi_server ** servers, struct xpn_fh * fh, char * path, int pd)
Definition at line 322 of file xpn_policy_open.c.
References hash(), NFIDIR, xpn_fh::nfih, nfi_fhandle::type, xpn_metadata::type, xpn_metadata::type_policy, XPN_DEBUG_BEGIN, XPN_DEBUG_END, XPN_DIR, XPN_FILE, XPN_MAX_PART, xpn_parttable, XpnCreateMetadata(), and XpnGetFh().
Referenced by xpn_internal_open(), and xpn_simple_rename().
XpnUpdateMetadata()
int XpnUpdateMetadata (__attribute__((__unused__)) struct xpn_metadata * mdata, __attribute__((__unused__)) int nserv, __attribute__((__unused__)) struct nfi_server ** servers, __attribute__((__unused__)) struct xpn_fh * fh, __attribute__((__unused__)) char * path)
Definition at line 311 of file xpn_policy_open.c.
Referenced by xpn_internal_creat(), xpn_simple_mkdir(), and xpn_simple_rename().