tcp_server_comm.c File Reference
File to 'TODO'.
#include tcp_server_comm.h
Functions
int tcpClient_comm_init (__attribute__((__unused__)) tcpClient_param_st *params)
int tcpClient_comm_destroy (__attribute__((__unused__)) tcpClient_param_st *params)
int tcpClient_comm_connect (tcpClient_param_st *params)
'TODO'.
int tcpClient_comm_disconnect (__attribute__((__unused__)) tcpClient_param_st *params)
int tcpClient_comm_locality (tcpClient_param_st *params)
'TODO'.
ssize_t tcpClient_write_operation (int fd, char *data, ssize_t size, __attribute__((__unused__)) char *msg_id)
ssize_t tcpClient_write_data (int fd, char *data, ssize_t size, __attribute__((__unused__)) char *msg_id)
ssize_t tcpClient_read_data (int fd, char *data, ssize_t size, __attribute__((__unused__)) char *msg_id)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
Function Documentation
tcpClient_comm_connect()
int tcpClient_comm_connect (tcpClient_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 65 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_error, debug_info, ns_lookup(), params, and mpi_server_param_st::srv_name.
Referenced by nfi_tcp_server_connect(), and nfi_tcp_server_reconnect().
tcpClient_comm_destroy()
int tcpClient_comm_destroy (__attribute__((__unused__)) tcpClient_param_st * params)
Definition at line 53 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info.
Referenced by nfi_tcp_server_destroy().
tcpClient_comm_disconnect()
int tcpClient_comm_disconnect (__attribute__((__unused__)) tcpClient_param_st * params)
Definition at line 173 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info.
Referenced by nfi_tcp_server_disconnect().
tcpClient_comm_init()
int tcpClient_comm_init (__attribute__((__unused__)) tcpClient_param_st * params)
Definition at line 41 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info.
Referenced by nfi_tcp_server_init().
tcpClient_comm_locality()
int tcpClient_comm_locality (tcpClient_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 183 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info, debug_warning, mpi_server_param_st::dirbase, params, PATH_MAX, serv_name, TCP_SERVER_GETNODENAME, tcpClient_read_data(), and tcpClient_write_data().
Referenced by nfi_tcp_server_init().
tcpClient_read_data()
ssize_t tcpClient_read_data (int fd, char * data, ssize_t size, __attribute__((__unused__)) char * msg_id)
Definition at line 328 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info, debug_warning, and real_read.
Referenced by nfi_tcp_server_doRequest(), nfi_tcp_server_read(), nfi_tcp_server_write(), and tcpClient_comm_locality().
tcpClient_write_data()
ssize_t tcpClient_write_data (int fd, char * data, ssize_t size, __attribute__((__unused__)) char * msg_id)
Definition at line 273 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info, debug_warning, and real_write.
Referenced by nfi_tcp_server_write(), tcp_server_write_operation(), tcpClient_comm_locality(), and tcpClient_write_operation().
tcpClient_write_operation()
ssize_t tcpClient_write_operation (int fd, char * data, ssize_t size, __attribute__((__unused__)) char * msg_id)
Definition at line 247 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info, debug_warning, and tcpClient_write_data().
Referenced by tcp_server_write_operation().