xpn_bypass.h File Reference
Header file to 'TODO'.
#include config.h
#include <dlfcn.h>
#include <sys/stat.h>
#include <stdarg.h>
#include xpn.h
#include syscall_proxies.h
#include <dirent.h>
#include <string.h>
#include mpi.h
Data Structures
struct __dirstream
This is a struct.
struct generic_fd
This is a struct.
Macros
#define _GNU_SOURCE
#define _STAT_VER 0
#define MAX_FDS 10000
#define MAX_DIRS 10000
#define PLUSXPN 1000
#define FD_FREE 0
#define FD_SYS 1
#define FD_XPN 2
Functions
int open (const char *path, int flags,...)
'TODO'.
int open64 (const char *path, int flags,...)
'TODO'.
int __open_2 (const char *path, int flags,...)
'TODO'.
int creat (const char *path, mode_t mode)
'TODO'.
int close (int fd)
'TODO'.
int ftruncate (int fildes, off_t length)
'TODO'.
ssize_t read (int fildes, void *buf, size_t nbyte)
'TODO'.
ssize_t write (int fildes, const void *buf, size_t nbyte)
'TODO'.
off_t lseek (int fildes, off_t offset, int whence)
'TODO'.
off64_t lseek64 (int fd, off64_t offset, int whence)
'TODO'.
int __lxstat (int ver, const char *path, struct stat *buf)
'TODO'.
int __lxstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int __xstat (int ver, const char *path, struct stat *buf)
'TODO'.
int __xstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int __fxstat (int ver, int fd, struct stat *buf)
'TODO'.
int __fxstat64 (int ver, int fildes, struct stat64 *buf)
'TODO'.
int __fxstatat (int ver, int dirfd, const char *path, struct stat *buf, int flags)
'TODO'.
int __fxstatat64 (int ver, int dirfd, const char *path, struct stat64 *buf, int flags)
'TODO'.
int rename (const char *old_path, const char *new_path)
'TODO'.
int unlink (const char *path)
'TODO'.
int mkdir (const char *path, mode_t mode)
'TODO'.
DIR * opendir (const char *dirname)
'TODO'.
struct dirent * readdir (DIR *dirp)
'TODO'.
struct dirent64 * readdir64 (DIR *dirp)
'TODO'.
int closedir (DIR *dirp)
'TODO'.
int rmdir (const char *path)
'TODO'.
int fork (void)
'TODO'.
int dup (int fildes)
'TODO'.
int dup2 (int fildes, int fildes2)
'TODO'.
void exit (int status)
'TODO'.
int chdir (const char *path)
'TODO'.
int chmod (const char *path, mode_t mode)
'TODO'.
int fchmod (int fildes, mode_t mode)
'TODO'.
int chown (const char *path, uid_t owner, gid_t group)
'TODO'.
int fcntl (int fd, int cmd, long arg)
'TODO'.
int access (const char *path, int mode)
'TODO'.
char * realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
char * __realpath_chk (const char *path, char *resolved_path, size_t resolved_len)
'TODO'.
int fsync (int fd)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_bypass.h.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 35 of file xpn_bypass.h.
_STAT_VER
#define _STAT_VER 0
Definition at line 60 of file xpn_bypass.h.
FD_FREE
#define FD_FREE 0
Definition at line 71 of file xpn_bypass.h.
FD_SYS
#define FD_SYS 1
Definition at line 72 of file xpn_bypass.h.
FD_XPN
#define FD_XPN 2
Definition at line 73 of file xpn_bypass.h.
MAX_DIRS
#define MAX_DIRS 10000
Definition at line 65 of file xpn_bypass.h.
MAX_FDS
#define MAX_FDS 10000
Definition at line 64 of file xpn_bypass.h.
PLUSXPN
#define PLUSXPN 1000
Definition at line 66 of file xpn_bypass.h.
Function Documentation
__fxstat()
int __fxstat (int ver, int fd, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fd 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 1072 of file xpn_bypass.c.
References buf, debug_info, dlsym_fstat(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_fstat().
__fxstat64()
int __fxstat64 (int ver, int fildes, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fildes 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 960 of file xpn_bypass.c.
References buf, debug_info, dlsym_fxstat64(), FD_XPN, fdstable_get(), generic_fd::real_fd, st, stat_to_stat64(), generic_fd::type, xpn_adaptor_keepInit(), and xpn_fstat().
__fxstatat()
int __fxstatat (int ver, int dirfd, const char * path, struct stat * buf, int flags)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
dirfd 'TODO'.
path 'TODO'.
buf 'TODO'.
flags 'TODO'.
Returns
'TODO'.
__fxstatat64()
int __fxstatat64 (int ver, int dirfd, const char * path, struct stat64 * buf, int flags)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
dirfd 'TODO'.
path 'TODO'.
buf 'TODO'.
flags 'TODO'.
Returns
'TODO'.
__lxstat()
int __lxstat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 1016 of file xpn_bypass.c.
References buf, debug_info, dlsym_lstat(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_stat().
__lxstat64()
int __lxstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 888 of file xpn_bypass.c.
References buf, debug_info, dlsym_lxstat64(), is_xpn_prefix(), skip_xpn_prefix(), st, stat_to_stat64(), xpn_adaptor_keepInit(), and xpn_stat().
Referenced by access().
__open_2()
int __open_2 (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 628 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym___open_2(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_open().
__realpath_chk()
char * __realpath_chk (const char * path, char * resolved_path, size_t resolved_len)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
resolved_path 'TODO'.
resolved_len 'TODO'.
Returns
'TODO'.
__xstat()
int __xstat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 1044 of file xpn_bypass.c.
References buf, debug_info, dlsym_stat(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_stat().
__xstat64()
int __xstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 925 of file xpn_bypass.c.
References buf, debug_info, dlsym_xstat64(), is_xpn_prefix(), skip_xpn_prefix(), st, stat_to_stat64(), xpn_adaptor_keepInit(), and xpn_stat().
access()
int access (const char * path, int mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1664 of file xpn_bypass.c.
References __lxstat64(), _STAT_VER, debug_info, dlsym_access(), is_xpn_prefix(), and xpn_adaptor_keepInit().
chdir()
int chdir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1557 of file xpn_bypass.c.
References debug_info, dlsym_chdir(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_chdir().
chmod()
int chmod (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1577 of file xpn_bypass.c.
References debug_info, dlsym_chmod(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_chmod().
chown()
int chown (const char * path, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 1623 of file xpn_bypass.c.
References debug_info, dlsym_chown(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_chown().
close()
int close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 1178 of file xpn_bypass.c.
References debug_info, dlsym_close(), FD_XPN, fdstable_get(), fdstable_remove(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_close().
Referenced by copy(), do_cp(), main(), mpi_server_op_preload(), and tcp_server_comm_close().
closedir()
int closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 1397 of file xpn_bypass.c.
References debug_info, dlsym_closedir(), fdsdirtable_get(), fdsdirtable_remove(), xpn_adaptor_keepInit(), and xpn_closedir().
Referenced by do_cp_recursive(), list(), and list().
creat()
int creat (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 678 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym_creat(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_creat().
Referenced by main().
dup()
int dup (int fildes)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
Returns
'TODO'.
Definition at line 1482 of file xpn_bypass.c.
References debug_info, dlsym_dup(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_dup().
dup2()
int dup2 (int fildes, int fildes2)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
fildes2 'TODO'.
Returns
'TODO'.
Definition at line 1510 of file xpn_bypass.c.
References debug_info, dlsym_dup2(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_dup2().
exit()
void exit (int status)
'TODO'.
'TODO'.
Parameters
status 'TODO'.
Returns
Nothing.
Definition at line 1540 of file xpn_bypass.c.
References debug_info, dlsym_exit(), xpn_adaptor_initCalled, and xpn_destroy().
Referenced by fdsdirtable_realloc(), fdstable_realloc(), and main().
fchmod()
int fchmod (int fildes, mode_t mode)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1597 of file xpn_bypass.c.
References debug_info, dlsym_fchmod(), FD_XPN, fdstable_get(), generic_fd::type, xpn_adaptor_keepInit(), and xpn_fchmod().
fcntl()
int fcntl (int fd, int cmd, long arg)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
cmd 'TODO'.
arg 'TODO'.
Returns
'TODO'.
Definition at line 1643 of file xpn_bypass.c.
References debug_info, dlsym_fcntl(), FD_XPN, fdstable_get(), and generic_fd::type.
fork()
int fork (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 1457 of file xpn_bypass.c.
References debug_info, dlsym_fork(), and xpn_adaptor_initCalled.
fsync()
int fsync (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 1753 of file xpn_bypass.c.
References debug_info, dlsym_fsync(), FD_XPN, fdstable_get(), and generic_fd::type.
Referenced by write_func().
ftruncate()
int ftruncate (int fildes, off_t length)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 706 of file xpn_bypass.c.
References debug_info, dlsym_ftruncate(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_ftruncate().
lseek()
off_t lseek (int fildes, off_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 811 of file xpn_bypass.c.
References debug_info, dlsym_lseek(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_lseek().
Referenced by main().
lseek64()
off64_t lseek64 (int fd, off64_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 840 of file xpn_bypass.c.
References debug_info, dlsym_lseek64(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_lseek().
Referenced by copy().
mkdir()
int mkdir (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1269 of file xpn_bypass.c.
References debug_info, dlsym_mkdir(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_mkdir().
Referenced by copy(), and do_cp_recursive().
open()
int open (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 527 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym_open2(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_open().
Referenced by do_cp(), main(), mpi_server_d2xpn(), and tcp_server_d2xpn().
open64()
int open64 (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 577 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym_open64(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_open().
Referenced by copy().
opendir()
DIR * opendir (const char * dirname)
'TODO'.
'TODO'.
Parameters
dirname 'TODO'.
Returns
'TODO'.
Definition at line 1297 of file xpn_bypass.c.
References debug_info, dlsym_opendir(), fdsdirtable_put(), is_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_opendir().
Referenced by do_cp_recursive(), list(), and list().
read()
ssize_t read (int fildes, void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 735 of file xpn_bypass.c.
References buf, debug_info, dlsym_read(), errno, FD_XPN, fdstable_get(), generic_fd::is_file, generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_read().
Referenced by copy(), do_cp(), main(), and tcp_server_comm_read_data().
readdir()
struct dirent * readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 1329 of file xpn_bypass.c.
References debug_info, dlsym_readdir(), fdsdirtable_get(), fdsdirtable_getfd(), xpn_adaptor_keepInit(), and xpn_readdir().
Referenced by do_cp_recursive(), list(), and list().
readdir64()
struct dirent64 * readdir64 (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 1357 of file xpn_bypass.c.
References debug_info, dlsym_readdir64(), fdsdirtable_get(), fdsdirtable_getfd(), xpn_adaptor_keepInit(), and xpn_readdir().
realpath()
char * realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
resolved_path 'TODO'.
Returns
'TODO'.
Definition at line 1702 of file xpn_bypass.c.
References debug_info, dlsym_realpath(), is_xpn_prefix(), and xpn_adaptor_keepInit().
rename()
int rename (const char * old_path, const char * new_path)
'TODO'.
'TODO'.
Parameters
old_path 'TODO'.
new_path 'TODO'.
Returns
'TODO'.
Definition at line 1209 of file xpn_bypass.c.
References debug_info, dlsym_rename(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_rename().
Referenced by ns_unpublish().
rmdir()
int rmdir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1425 of file xpn_bypass.c.
References debug_info, dlsym_rmdir(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_rmdir().
unlink()
int unlink (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1240 of file xpn_bypass.c.
References debug_info, dlsym_unlink(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_unlink().
Referenced by main(), and ns_unpublish().
write()
ssize_t write (int fildes, const void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 773 of file xpn_bypass.c.
References buf, debug_info, dlsym_write(), errno, FD_XPN, fdstable_get(), generic_fd::is_file, generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_write().
Referenced by copy(), do_cp(), main(), tcp_server_comm_write_data(), and write_func().