xpn_stdio.c File Reference
File to 'TODO'.
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <xpn.h>
#include <unistd.h>
#include <strings.h>
#include xpn_open.h
Functions
ssize_t xpn_reader (void *cookie, char *buffer, size_t size)
'TODO'.
ssize_t xpn_writer (void *cookie, const char *buffer, size_t size)
'TODO'.
int xpn_seeker (void *cookie, __off64_t *position, int whence)
'TODO'.
int xpn_cleaner (void *cookie)
'TODO'.
FILE * xpn_fopencookie (const char *path, const char *mode)
'TODO'.
FILE * xpn_simple_fopen (const char *filename, const char *mode)
'TODO'.
int xpn_simple_fclose (FILE *stream)
'TODO'.
size_t xpn_simple_fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
'TODO'.
size_t xpn_simple_fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
'TODO'.
int xpn_simple_fgetc (FILE *stream)
'TODO'.
char * xpn_simple_fgets (char *s, int tam, FILE *stream)
'TODO'.
int xpn_simple_getc (FILE *stream)
'TODO'.
int xpn_simple_fseek (FILE *stream, off_t offset, int whence)
long xpn_simple_ftell (FILE *stream)
'TODO'.
void xpn_simple_rewind (FILE *stream)
'TODO'.
int xpn_simple_fflush (__attribute__((__unused__)) FILE *stream)
int xpn_simple_fileno (FILE *stream)
'TODO'.
int xpn_simple_ferror (__attribute__((__unused__)) FILE *stream)
Variables
struct xpn_filedesc * xpn_file_table [XPN_MAX_FILE]
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn/xpn_simple/xpncore/xpn_stdio.c.
Function Documentation
xpn_cleaner()
int xpn_cleaner (void * cookie)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
Returns
'TODO'.
Definition at line 73 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_close().
Referenced by xpn_fopencookie().
xpn_fopencookie()
FILE * xpn_fopencookie (const char * path, const char * mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 82 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_filedesc::mode, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, xpn_filedesc::path, xpn_cleaner(), xpn_reader(), xpn_seeker(), xpn_simple_open(), and xpn_writer().
xpn_reader()
ssize_t xpn_reader (void * cookie, char * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 58 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_read().
Referenced by xpn_fopencookie().
xpn_seeker()
int xpn_seeker (void * cookie, __off64_t * position, int whence)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
position 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 68 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_lseek().
Referenced by xpn_fopencookie().
xpn_simple_fclose()
int xpn_simple_fclose (FILE * fp)
'TODO'.
'TODO'.
Parameters
fp 'TODO'.
Returns
'TODO'.
Definition at line 174 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References errno, xpn_simple_close(), and xpn_simple_fflush().
Referenced by xpn_fclose().
xpn_simple_ferror()
int xpn_simple_ferror (__attribute__((__unused__)) FILE * stream)
Definition at line 268 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
Referenced by xpn_ferror().
xpn_simple_fflush()
int xpn_simple_fflush (__attribute__((__unused__)) FILE * stream)
Definition at line 258 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
Referenced by xpn_fflush(), and xpn_simple_fclose().
xpn_simple_fgetc()
int xpn_simple_fgetc (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 211 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_read().
Referenced by xpn_fgetc(), and xpn_simple_getc().
xpn_simple_fgets()
char * xpn_simple_fgets (char * s, int tam, FILE * stream)
'TODO'.
'TODO'.
Parameters
s 'TODO'.
tam 'TODO'.
stream 'TODO'.
Returns
'TODO'.
Definition at line 220 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_fread().
Referenced by xpn_fgets().
xpn_simple_fileno()
int xpn_simple_fileno (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 263 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
Referenced by xpn_fileno().
xpn_simple_fopen()
FILE * xpn_simple_fopen (const char * filename, const char * mode)
'TODO'.
'TODO'.
Parameters
filename 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 129 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_filedesc::mode, O_APPEND, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, and xpn_simple_open().
Referenced by xpn_fopen().
xpn_simple_fread()
size_t xpn_simple_fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
'TODO'.
'TODO'.
Parameters
ptr 'TODO'.
size 'TODO'.
nmemb 'TODO'.
stream 'TODO'.
Returns
'TODO'.
Definition at line 201 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_read().
Referenced by xpn_fread(), and xpn_simple_fgets().
xpn_simple_fseek()
int xpn_simple_fseek (FILE * stream, off_t offset, int whence)
Definition at line 234 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_filedesc::offset, and xpn_simple_lseek().
Referenced by xpn_fseek().
xpn_simple_ftell()
long xpn_simple_ftell (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 247 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_filedesc::offset, and xpn_file_table.
Referenced by xpn_ftell().
xpn_simple_fwrite()
size_t xpn_simple_fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
'TODO'.
'TODO'.
Parameters
ptr 'TODO'.
size 'TODO'.
nmemb 'TODO'.
stream 'TODO'.
Returns
'TODO'.
Definition at line 206 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_write().
Referenced by xpn_fwrite().
xpn_simple_getc()
int xpn_simple_getc (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 229 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_fgetc().
Referenced by xpn_getc().
xpn_simple_rewind()
void xpn_simple_rewind (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
Nothing.
Definition at line 253 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_lseek().
Referenced by xpn_rewind().
xpn_writer()
ssize_t xpn_writer (void * cookie, const char * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 63 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_write().
Referenced by xpn_fopencookie().
Variable Documentation
xpn_file_table
struct xpn_filedesc* xpn_file_table[XPN_MAX_FILE] [extern]
Definition at line 37 of file xpn_file.c.
Referenced by xpn_simple_ftell().