xpn_policy_cwd.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_policy_cwd.h
Functions
int XpnGetAbsolutePath (const char *path, char *path_part)
'TODO'.
Variables
struct xpn_cwd xpn_cwddir
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_policy_cwd.c.
Function Documentation
XpnGetAbsolutePath()
int XpnGetAbsolutePath (const char * path, char * path_part)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
path_part 'TODO'.
Returns
'TODO'.
Definition at line 43 of file xpn_policy_cwd.c.
References xpn_cwd::xpn_cwd_path, and xpn_cwddir.
Referenced by xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), and xpn_simple_stat().
Variable Documentation
xpn_cwddir
struct xpn_cwd xpn_cwddir [extern]
Definition at line 37 of file xpn_cwd.c.
Referenced by XpnGetAbsolutePath().