xpn_open.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_open.h
#include xpn/xpn_simple/xpn_opendir.h
Macros
#define MASK 0000777
Functions
void XpnShowFileTable (void)
'TODO'.
int XpnSearchSlotFile (int pd, char *path, struct xpn_fh *vfh, struct xpn_metadata *mdata, int mode)
'TODO'.
int XpnSearchFile (const char *path)
'TODO'.
int xpn_internal_creat (const char *path, mode_t perm, struct xpn_fh **vfh, struct xpn_metadata **mdata)
'TODO'.
int xpn_internal_open (const char *path, struct xpn_fh *vfh, struct xpn_metadata *mdata, int mode)
'TODO'.
int xpn_internal_resize (__attribute__((__unused__)) char *path, __attribute__((__unused__)) struct xpn_fh **vfh, __attribute__((__unused__)) int size)
'TODO'.
int xpn_internal_fresize (__attribute__((__unused__)) int fd, __attribute__((__unused__)) int size)
'TODO'.
int xpn_internal_remove (const char *path)
'TODO'.
int xpn_simple_preload (const char *virtual_path, const char *storage_path)
'TODO'.
int xpn_simple_flush (const char *virtual_path, const char *storage_path)
'TODO'.
int xpn_simple_creat (const char *path, mode_t perm)
'TODO'.
int xpn_simple_open (const char *path, int flags, mode_t mode)
'TODO'.
int xpn_simple_close (int fd)
'TODO'.
int xpn_simple_unlink (const char *path)
'TODO'.
int xpn_simple_rename (const char *path, const char *newpath)
'TODO'.
int xpn_simple_fstat (int fd, struct stat *sb)
'TODO'.
int xpn_simple_stat (const char *path, struct stat *sb)
'TODO'.
int xpn_simple_chown (__attribute__((__unused__)) const char *path, __attribute__((__unused__)) uid_t owner, __attribute__((__unused__)) gid_t group)
int xpn_simple_fchown (int __attribute__((__unused__)) fd, __attribute__((__unused__)) uid_t owner, __attribute__((__unused__)) gid_t group)
int xpn_simple_chmod (__attribute__((__unused__)) const char *path, __attribute__((__unused__)) mode_t mode)
int xpn_simple_fchmod (__attribute__((__unused__)) int fd, __attribute__((__unused__)) mode_t mode)
int xpn_simple_truncate (__attribute__((__unused__)) const char *path, __attribute__((__unused__)) off_t length)
int xpn_simple_ftruncate (__attribute__((__unused__)) int fd, __attribute__((__unused__)) off_t length)
int xpn_simple_dup (int fd)
'TODO'.
int xpn_simple_dup2 (int fd, int fd2)
'TODO'.
Variables
struct xpn_filedesc * xpn_file_table [XPN_MAX_FILE]
int ino_counter = 0
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_open.c.
Macro Definition Documentation
MASK
#define MASK 0000777
Definition at line 38 of file xpn_open.c.
Function Documentation
xpn_internal_creat()
int xpn_internal_creat (const char * path, mode_t perm, struct xpn_fh ** vfh, struct xpn_metadata ** mdata)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
vfh 'TODO'.
mdata 'TODO'.
Returns
'TODO'.
Definition at line 177 of file xpn_open.c.
References nfi_attr::at_mode, xpn_fh::n_nfih, nfi_ops::nfi_close, nfi_worker_do_create(), xpn_fh::nfih, nfiworker_wait(), op_xpn_creat, nfi_server::ops, PATH_MAX, nfi_fhandle::priv_fh, nfi_fhandle::server, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END, XPN_DEBUG_END_ARGS1, xpn_err(), nfi_server::xpn_thread, XpnCreateMetadata(), XPNERR_CREATE, XPNERR_NOMEMORY, XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetMetadataPos(), XpnGetPartition(), XpnGetServers(), XpnGetURLServer(), and XpnUpdateMetadata().
Referenced by xpn_simple_creat(), and xpn_simple_open().
xpn_internal_fresize()
int xpn_internal_fresize (__attribute__((__unused__)) int fd, __attribute__((__unused__)) int size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 510 of file xpn_open.c.
xpn_internal_open()
int xpn_internal_open (const char * path, struct xpn_fh * vfh, struct xpn_metadata * mdata, int mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
vfh 'TODO'.
mdata 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 392 of file xpn_open.c.
References xpn_filedesc::links, xpn_fh::n_nfih, xpn_fh::nfih, op_xpn_open, PATH_MAX, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_err(), xpn_file_table, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetPartition(), XpnGetServers(), XpnReadMetadata(), XpnSearchFile(), and XpnSearchSlotFile().
Referenced by xpn_simple_creat(), and xpn_simple_open().
xpn_internal_remove()
int xpn_internal_remove (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 524 of file xpn_open.c.
References nfi_worker::arg, hash(), nfi_worker_args::is_master_node, nfi_worker_args::master_node, nfi_worker_do_remove(), nfiworker_wait(), op_xpn_remove, PATH_MAX, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, xpn_err(), XPN_OK, nfi_server::xpn_thread, XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XPNERR_REMOVE, XpnGetAbsolutePath(), XpnGetPartition(), XpnGetServers(), and XpnGetURLServer().
Referenced by xpn_simple_creat(), xpn_simple_open(), and xpn_simple_unlink().
xpn_internal_resize()
int xpn_internal_resize (__attribute__((__unused__)) char * path, __attribute__((__unused__)) struct xpn_fh ** vfh, __attribute__((__unused__)) int size)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
vfh 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 495 of file xpn_open.c.
xpn_simple_chmod()
int xpn_simple_chmod (__attribute__((__unused__)) const char * path, __attribute__((__unused__)) mode_t mode)
Definition at line 1327 of file xpn_open.c.
Referenced by xpn_chmod().
xpn_simple_chown()
int xpn_simple_chown (__attribute__((__unused__)) const char * path, __attribute__((__unused__)) uid_t owner, __attribute__((__unused__)) gid_t group)
Definition at line 1315 of file xpn_open.c.
Referenced by xpn_chown().
xpn_simple_close()
int xpn_simple_close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 931 of file xpn_open.c.
References xpn_filedesc::data_vfh, xpn_filedesc::links, xpn_fh::n_nfih, nfi_ops::nfi_close, xpn_fh::nfih, nfi_server::ops, nfi_fhandle::server, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, xpn_err(), xpn_file_table, XPN_MAX_FILE, and XPN_OK.
Referenced by xpn_cleaner(), xpn_close(), and xpn_simple_fclose().
xpn_simple_creat()
int xpn_simple_creat (const char * path, mode_t perm)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
Returns
'TODO'.
Definition at line 812 of file xpn_open.c.
References PATH_MAX, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_err(), xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), and XPN_OK.
Referenced by xpn_creat().
xpn_simple_dup()
int xpn_simple_dup (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 1351 of file xpn_open.c.
References xpn_filedesc::links, xpn_file_table, and XPN_MAX_FILE.
Referenced by xpn_dup().
xpn_simple_dup2()
int xpn_simple_dup2 (int fd, int fd2)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
fd2 'TODO'.
Returns
'TODO'.
Definition at line 1381 of file xpn_open.c.
References xpn_filedesc::links, xpn_file_table, and XPN_MAX_FILE.
Referenced by xpn_dup2().
xpn_simple_fchmod()
int xpn_simple_fchmod (__attribute__((__unused__)) int fd, __attribute__((__unused__)) mode_t mode)
Definition at line 1333 of file xpn_open.c.
Referenced by xpn_fchmod().
xpn_simple_fchown()
int xpn_simple_fchown (int __attribute__((__unused__)) fd, __attribute__((__unused__)) uid_t owner, __attribute__((__unused__)) gid_t group)
Definition at line 1321 of file xpn_open.c.
Referenced by xpn_fchown().
xpn_simple_flush()
int xpn_simple_flush (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 724 of file xpn_open.c.
References nfi_worker_do_flush(), nfiworker_wait(), op_xpn_flush, PATH_MAX, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, xpn_err(), nfi_server::xpn_thread, XpnCreateMetadata(), XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetMetadataPos(), XpnGetPartition(), XpnGetServers(), and XpnGetURLServer().
Referenced by xpn_flush().
xpn_simple_fstat()
int xpn_simple_fstat (int fd, struct stat * sb)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 1254 of file xpn_open.c.
References errno, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, and XpnGetAtribFd().
Referenced by xpn_fstat(), and xpn_simple_lseek().
xpn_simple_ftruncate()
int xpn_simple_ftruncate (__attribute__((__unused__)) int fd, __attribute__((__unused__)) off_t length)
Definition at line 1345 of file xpn_open.c.
Referenced by xpn_ftruncate().
xpn_simple_open()
int xpn_simple_open (const char * path, int flags, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 860 of file xpn_open.c.
References errno, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, PATH_MAX, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_err(), xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), XPN_OK, and xpn_simple_stat().
Referenced by xpn_fopencookie(), xpn_open(), xpn_simple_fopen(), and xpn_simple_opendir().
xpn_simple_preload()
int xpn_simple_preload (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 629 of file xpn_open.c.
References nfi_worker_do_preload(), nfiworker_wait(), op_xpn_flush, PATH_MAX, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_ARGS2, XPN_DEBUG_END, xpn_err(), nfi_server::xpn_thread, XpnCreateMetadata(), XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetMetadataPos(), XpnGetPartition(), XpnGetServers(), and XpnGetURLServer().
Referenced by xpn_preload().
xpn_simple_rename()
int xpn_simple_rename (const char * path, const char * newpath)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
newpath 'TODO'.
Returns
'TODO'.
Definition at line 1037 of file xpn_open.c.
References xpn_fh::n_nfih, nfi_ops::nfi_close, nfi_worker_do_rename(), xpn_fh::nfih, nfiworker_wait(), op_xpn_rename, nfi_server::ops, PATH_MAX, nfi_fhandle::priv_fh, nfi_fhandle::server, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, xpn_err(), nfi_server::xpn_thread, XPNERR_NOMEMORY, XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetPartition(), XpnGetServers(), XpnGetURLServer(), XpnReadMetadata(), and XpnUpdateMetadata().
Referenced by xpn_rename().
xpn_simple_stat()
int xpn_simple_stat (const char * path, struct stat * sb)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 1274 of file xpn_open.c.
References errno, PATH_MAX, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_err(), XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), and XpnGetAtribPath().
Referenced by xpn_simple_open(), and xpn_stat().
xpn_simple_truncate()
int xpn_simple_truncate (__attribute__((__unused__)) const char * path, __attribute__((__unused__)) off_t length)
Definition at line 1339 of file xpn_open.c.
Referenced by xpn_truncate().
xpn_simple_unlink()
int xpn_simple_unlink (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1025 of file xpn_open.c.
References XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, and xpn_internal_remove().
Referenced by xpn_unlink().
XpnSearchFile()
int XpnSearchFile (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 134 of file xpn_open.c.
References xpn_filedesc::path, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END, xpn_file_table, and XPN_MAX_FILE.
Referenced by xpn_internal_open().
XpnSearchSlotFile()
int XpnSearchSlotFile (int pd, char * path, struct xpn_fh * vfh, struct xpn_metadata * mdata, int mode)
'TODO'.
'TODO'.
Parameters
pd 'TODO'.
path 'TODO'.
vfh 'TODO'.
mdata 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 84 of file xpn_open.c.
References xpn_partition::block_size, xpn_filedesc::block_size, xpn_filedesc::data_vfh, xpn_filedesc::id, xpn_filedesc::links, xpn_filedesc::mdata, xpn_filedesc::mode, xpn_filedesc::offset, xpn_filedesc::part, xpn_filedesc::path, PATH_MAX, xpn_filedesc::size_threads, xpn_metadata::type, xpn_filedesc::type, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_file_table, XPN_MAX_FILE, XpnGetSizeThreads(), and XpnSearchPart().
Referenced by xpn_internal_open().
XpnShowFileTable()
void XpnShowFileTable (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 59 of file xpn_open.c.
References xpn_filedesc::path, xpn_file_table, and XPN_MAX_FILE.
Referenced by xpn_pread(), xpn_simple_read(), xpn_simple_write(), and xpn_sread().
Variable Documentation
ino_counter
int ino_counter = 0
Definition at line 42 of file xpn_open.c.
xpn_file_table
struct xpn_filedesc* xpn_file_table[XPN_MAX_FILE] [extern]
Definition at line 37 of file xpn_file.c.
Referenced by xpn_internal_open(), xpn_simple_close(), xpn_simple_dup(), xpn_simple_dup2(), XpnSearchFile(), XpnSearchSlotFile(), and XpnShowFileTable().