xpn_cwd.h File Reference
Header file to 'TODO'.
#include xpn.h
#include xpn_err.h
#include xpn_policy_cwd.h
Data Structures
struct xpn_cwd
Functions
void xpn_init_cwd ()
'TODO'.
char * xpn_simple_getcwd (char *path, size_t size)
'TODO'.
int xpn_simple_chdir (char *path)
'TODO'.
Variables
struct xpn_cwd xpn_cwddir
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_cwd.h.
Function Documentation
xpn_init_cwd()
void xpn_init_cwd ()
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 43 of file xpn_cwd.c.
References xpn_cwd::xpn_cwd_path, and xpn_cwddir.
Referenced by xpn_init_partition().
xpn_simple_chdir()
int xpn_simple_chdir (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 54 of file xpn_cwd.c.
References xpn_cwd::xpn_cwd_path, and xpn_cwddir.
Referenced by xpn_chdir().
xpn_simple_getcwd()
char * xpn_simple_getcwd (char * path, size_t size)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 48 of file xpn_cwd.c.
References xpn_cwd::xpn_cwd_path, and xpn_cwddir.
Referenced by xpn_getcwd().
Variable Documentation
xpn_cwddir
struct xpn_cwd xpn_cwddir [extern]
Definition at line 37 of file xpn_cwd.c.
Referenced by xpn_init_cwd(), xpn_simple_chdir(), and xpn_simple_getcwd().