xpn_policy_init.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_policy_init.h
Functions
char * param_get (char *key)
'TODO'.
struct conf_connect_st * XpnPartitionOpen (void)
'TODO'.
void XpnPartitionClose (struct conf_connect_st *fconf)
'TODO'.
int XpnGetNextPartition (struct conf_connect_st *fconf, char *name)
'TODO'.
int XpnGetIdPartition (__attribute__((__unused__)) struct conf_connect_st *fconf, __attribute__((__unused__)) char *name)
int XpnGetInfoPartition (struct conf_connect_st *fconf, struct xpn_partition *part)
'TODO'.
int XpnGetNumServersPartition (struct conf_connect_st *fconf, struct xpn_partition *part, int type)
'TODO'.
int XpnGetServer (struct conf_connect_st *fconf, __attribute__((__unused__)) struct xpn_partition *part, struct nfi_server *serv, int type)
int XpnGetPartition (char *path)
'TODO'.
struct xpn_partition * XpnSearchPart (int pd)
'TODO'.
void XpnShowPartitionTable (void)
'TODO'.
Variables
struct xpn_partition xpn_parttable [XPN_MAX_PART]
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_policy_init.c.
Function Documentation
param_get()
char * param_get (char * key)
'TODO'.
'TODO'.
Parameters
key 'TODO'.
Returns
'TODO'.
Definition at line 51 of file xpn_policy_init.c.
Referenced by XpnPartitionOpen().
XpnGetIdPartition()
int XpnGetIdPartition (__attribute__((__unused__)) struct conf_connect_st * fconf, __attribute__((__unused__)) char * name)
Definition at line 206 of file xpn_policy_init.c.
Referenced by xpn_init_partition().
XpnGetInfoPartition()
int XpnGetInfoPartition (struct conf_connect_st * fconf, struct xpn_partition * part)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
part 'TODO'.
Returns
'TODO'.
Definition at line 213 of file xpn_policy_init.c.
References xpn_partition::block_size, CONF_FILE, CONF_MXML, conf_connect_st::connect_u, xpn_partition::data_nserv, debug_info, conf_connect_st::f, getSizeFactor(), KB, xpn_partition::meta_nserv, xpn_partition::name, POLICY_RAID0, POLICY_RAID1, xpn_partition::size_threads, xpn_partition::type, and conf_connect_st::type.
Referenced by xpn_init_partition().
XpnGetNextPartition()
int XpnGetNextPartition (struct conf_connect_st * fconf, char * name)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
name 'TODO'.
Returns
'TODO'.
Definition at line 164 of file xpn_policy_init.c.
References CONF_FILE, CONF_MXML, conf_connect_st::connect_u, conf_connect_st::f, and conf_connect_st::type.
Referenced by xpn_init_partition().
XpnGetNumServersPartition()
int XpnGetNumServersPartition (struct conf_connect_st * fconf, struct xpn_partition * part, int type)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
part 'TODO'.
type 'TODO'.
Returns
'TODO'.
Definition at line 379 of file xpn_policy_init.c.
References CONF_FILE, CONF_MXML, xpn_partition::data_nserv, xpn_partition::meta_nserv, conf_connect_st::type, XPN_DATA_SERVER, and XPN_META_SERVER.
Referenced by xpn_init_partition().
XpnGetPartition()
int XpnGetPartition (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 550 of file xpn_policy_init.c.
References getNamePart(), xpn_partition::id, PATH_MAX, XPN_MAX_PART, and xpn_parttable.
Referenced by xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), and XpnGetAtribPath().
XpnGetServer()
int XpnGetServer (struct conf_connect_st * fconf, __attribute__((__unused__)) struct xpn_partition * part, struct nfi_server * serv, int type)
Definition at line 399 of file xpn_policy_init.c.
References nfi_server::block_size, CONF_FILE, CONF_MXML, conf_connect_st::connect_u, conf_connect_st::f, nfi_local_init(), nfi_mpi_server_init(), nfi_nfs3_init(), nfi_nfs_init(), nfi_tcp_server_init(), ParseURL(), PROTOCOL_MAXLEN, conf_connect_st::type, nfi_server::url, XPN_DATA_SERVER, XPN_DEBUG, xpn_err(), XPN_META_SERVER, XPNERR_INITSERV, and XPNERR_INVALURL.
Referenced by xpn_init_partition().
XpnPartitionClose()
void XpnPartitionClose (struct conf_connect_st * fconf)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
Returns
Nothing.
Definition at line 138 of file xpn_policy_init.c.
References CONF_FILE, CONF_MXML, conf_connect_st::connect_u, conf_connect_st::f, and conf_connect_st::type.
Referenced by xpn_init_partition().
XpnPartitionOpen()
struct conf_connect_st * XpnPartitionOpen (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 65 of file xpn_policy_init.c.
References CONF_DEFAULT, CONF_FILE, CONF_MXML, conf_connect_st::connect_u, conf_connect_st::f, param_get(), PATH_MAX, conf_connect_st::type, XPN_CONF, XPN_CONF_DEFAULT, and XPN_DEBUG.
Referenced by xpn_init_partition().
XpnSearchPart()
struct xpn_partition * XpnSearchPart (int pd)
'TODO'.
'TODO'.
Parameters
pd 'TODO'.
Returns
'TODO'.
Definition at line 572 of file xpn_policy_init.c.
References XPN_MAX_PART, and xpn_parttable.
Referenced by XpnSearchSlotFile().
XpnShowPartitionTable()
void XpnShowPartitionTable (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 599 of file xpn_policy_init.c.
References xpn_partition::name, XPN_MAX_PART, and xpn_parttable.
Variable Documentation
xpn_parttable
struct xpn_partition xpn_parttable[XPN_MAX_PART] [extern]
Definition at line 37 of file xpn_init.c.
Referenced by XpnCreateMetadata(), XpnGetPartition(), XpnGetServers(), XpnReadMetadata(), XpnSearchPart(), and XpnShowPartitionTable().