xpn_policy_rw.h File Reference
Header file to 'TODO'.
#include xpn_file.h
#include xpn_policy_open.h
Functions
int XpnGetBlock (int fd, off_t global_offset, off_t *local_offset, int *serv)
Calculates the server and the offset.
void * XpnReadBlocks (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
Read blocks.
int XpnReadBlocksFinish (int fd, void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers, void *new_buffer)
'TODO'.
void * XpnWriteBlocks (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
Write blocks.
int XpnWriteBlocksFinish (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers, void *new_buffer)
'TODO'.
ssize_t XpnReadGetTotalBytes (int fd, ssize_t *res_v, int num_servers)
'TODO'.
ssize_t XpnWriteGetTotalBytes (int fd, ssize_t *res_v, int num_servers)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_policy_rw.h.
Function Documentation
XpnGetBlock()
int XpnGetBlock (int fd, off_t global_offset, off_t * local_offset, int * serv)
Calculates the server and the offset.
Calculates the server and the offset in that server of the given offset of a file.
Parameters
fd [in] A file descriptor.
global_offset [in] The original offset.
local_offset [out] The offset in the server.
serv [out] The server in which is located the given offset.
Returns
Returns 0 on success or -1 on error.
Definition at line 41 of file xpn_policy_rw.c.
References xpn_filedesc::block_size, policy::first_node, POLICY_RAID0, POLICY_RAID1, and xpn_file_table.
Referenced by xpn_sread(), xpn_swrite(), XpnReadBlocks(), XpnRWBlocksPolicyBlockByBlock(), and XpnWriteBlocksPolicyRAID1_BlockByBlock().
XpnReadBlocks()
void * XpnReadBlocks (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
Read blocks.
Calculates how the blocks have to be read from the servers. io_out is an operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'. While ion_out[i] is the number of operations in server 'i' (io_out[i]).
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix.
ion_out [out] The length of every row in io_out.
num_servers [in] The number of servers.
Returns
Returns a pointer to a new buffer on success, or NULL on error.
Definition at line 363 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, POLICY_RAID0, POLICY_RAID1, nfi_worker_io::size, xpn_file_table, XpnGetBlock(), XpnReadBlocksPolicyRAID0_AllInOne(), XpnReadBlocksPolicyRAID1_AllInOne(), and XpnRWBlocksPolicyBlockByBlock().
Referenced by xpn_pread().
XpnReadBlocksFinish()
int XpnReadBlocksFinish (int fd, void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers, void * new_buffer)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
io_out 'TODO'.
ion_out 'TODO'.
num_servers 'TODO'.
new_buffer 'TODO'.
Returns
'TODO'.
Definition at line 419 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, POLICY_RAID0, POLICY_RAID1, nfi_worker_io::size, xpn_file_table, and XpnReadBlocksPolicyRAID0_AllInOne_Finish().
Referenced by xpn_pread().
XpnReadGetTotalBytes()
ssize_t XpnReadGetTotalBytes (int fd, ssize_t * res_v, int num_servers)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
res_v 'TODO'.
num_servers 'TODO'.
Returns
'TODO'.
Definition at line 502 of file xpn_policy_rw.c.
References POLICY_RAID0, POLICY_RAID1, and xpn_file_table.
Referenced by xpn_pread().
XpnWriteBlocks()
void * XpnWriteBlocks (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
Write blocks.
Calculates how the blocks have to be written to the servers. io_out is an operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'. While ion_out[i] is the number of operations in server 'i' (io_out[i]).
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix.
ion_out [out] The length of every row in io_out.
num_servers [in] The number of servers.
Returns
Returns 0 on success or -1 on error.
Definition at line 441 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, POLICY_RAID0, POLICY_RAID1, nfi_worker_io::size, xpn_file_table, XpnRWBlocksPolicyBlockByBlock(), XpnWriteBlocksPolicyRAID0_AllInOne(), XpnWriteBlocksPolicyRAID1_AllInOne(), and XpnWriteBlocksPolicyRAID1_BlockByBlock().
Referenced by xpn_pwrite().
XpnWriteBlocksFinish()
int XpnWriteBlocksFinish (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers, void * new_buffer)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
io_out 'TODO'.
ion_out 'TODO'.
num_servers 'TODO'.
new_buffer 'TODO'.
Returns
'TODO'.
XpnWriteGetTotalBytes()
ssize_t XpnWriteGetTotalBytes (int fd, ssize_t * res_v, int num_servers)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
res_v 'TODO'.
num_servers 'TODO'.
Returns
'TODO'.
Definition at line 523 of file xpn_policy_rw.c.
References POLICY_RAID0, POLICY_RAID1, and xpn_file_table.
Referenced by xpn_pwrite().