xpn_rw.h File Reference
Header file to 'TODO'.
#include xpn.h
#include xpn_file.h
#include xpn_open.h
#include xpn_policy_rw.h
#include xpn_err.h
#include base/workers.h
Functions
ssize_t xpn_simple_read (int fd, void *buffer, size_t size)
'TODO'.
ssize_t xpn_simple_write (int fd, const void *buffer, size_t size)
'TODO'.
off_t xpn_simple_lseek (int fd, off_t offset, int flag)
'TODO'.
FILE * xpn_simple_fopen (const char *filename, const char *mode)
'TODO'.
int xpn_simple_fclose (FILE *stream)
'TODO'.
size_t xpn_simple_fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
'TODO'.
size_t xpn_simple_fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
'TODO'.
int xpn_simple_fseek (FILE *stream, long offset, int whence)
'TODO'.
long xpn_simple_ftell (FILE *stream)
'TODO'.
int xpn_simple_fflush (FILE *stream)
'TODO'.
ssize_t xpn_sread (int fd, const void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_pread (int fd, void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_swrite (int fd, const void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_pwrite (int fd, const void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_reader (void *cookie, char *buffer, size_t size)
'TODO'.
ssize_t xpn_writer (void *cookie, const char *buffer, size_t size)
'TODO'.
int xpn_seeker (void *cookie, __off64_t *position, int whence)
'TODO'.
int xpn_cleaner (void *cookie)
'TODO'.
int xpn_fgetc (FILE *flujo)
'TODO'.
char * xpn_fgets (char *s, int tam, FILE *flujo)
'TODO'.
void xpn_rewind (FILE *stream)
'TODO'.
int xpn_ferror (FILE *stream)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_rw.h.
Function Documentation
xpn_cleaner()
int xpn_cleaner (void * cookie)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
Returns
'TODO'.
Definition at line 73 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_close().
Referenced by xpn_fopencookie().
xpn_ferror()
int xpn_ferror (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 135 of file xpn_stdio.c.
References xpn_simple_ferror().
xpn_fgetc()
int xpn_fgetc (FILE * flujo)
'TODO'.
'TODO'.
Parameters
flujo 'TODO'.
Returns
'TODO'.
Definition at line 111 of file xpn_stdio.c.
References xpn_simple_fgetc().
xpn_fgets()
char * xpn_fgets (char * s, int tam, FILE * flujo)
'TODO'.
'TODO'.
Parameters
s 'TODO'.
tam 'TODO'.
flujo 'TODO'.
Returns
'TODO'.
Definition at line 116 of file xpn_stdio.c.
References xpn_simple_fgets().
xpn_pread()
ssize_t xpn_pread (int fd, void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 209 of file xpn_rw.c.
References xpn_filedesc::block_size, nfi_worker_io::buffer, errno, xpn_filedesc::id, nfi_worker_do_read(), nfiworker_wait(), O_WRONLY, nfi_worker_io::offset, xpn_filedesc::offset, op_xpn_read, xpn_filedesc::path, nfi_worker_io::size, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, XPN_DIR, xpn_file_table, XPN_MAX_FILE, nfi_server::xpn_thread, XpnGetFh(), XpnGetMetadataPos(), XpnGetServers(), XpnReadBlocks(), XpnReadBlocksFinish(), XpnReadGetTotalBytes(), and XpnShowFileTable().
Referenced by xpn_simple_read().
xpn_pwrite()
ssize_t xpn_pwrite (int fd, const void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 573 of file xpn_rw.c.
References xpn_filedesc::block_size, nfi_worker_io::buffer, xpn_filedesc::id, nfi_worker_do_write(), nfiworker_wait(), O_RDONLY, nfi_worker_io::offset, xpn_filedesc::offset, op_xpn_write, xpn_filedesc::path, nfi_worker_io::size, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, XPN_DIR, xpn_file_table, XPN_MAX_FILE, nfi_server::xpn_thread, XpnGetFh(), XpnGetMetadataPos(), XpnGetServers(), XpnWriteBlocks(), XpnWriteBlocksFinish(), and XpnWriteGetTotalBytes().
Referenced by xpn_simple_write().
xpn_reader()
ssize_t xpn_reader (void * cookie, char * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 58 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_read().
Referenced by xpn_fopencookie().
xpn_rewind()
void xpn_rewind (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
Nothing.
Definition at line 88 of file xpn_stdio.c.
References xpn_simple_rewind().
xpn_seeker()
int xpn_seeker (void * cookie, __off64_t * position, int whence)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
position 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 68 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_lseek().
Referenced by xpn_fopencookie().
xpn_simple_fclose()
int xpn_simple_fclose (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
'TODO'.
Parameters
fp 'TODO'.
Returns
'TODO'.
Definition at line 174 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_fflush()
int xpn_simple_fflush (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
xpn_simple_fopen()
FILE * xpn_simple_fopen (const char * filename, const char * mode)
'TODO'.
'TODO'.
Parameters
filename 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 129 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_fread()
size_t xpn_simple_fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
'TODO'.
'TODO'.
Parameters
ptr 'TODO'.
size 'TODO'.
nmemb 'TODO'.
stream 'TODO'.
Returns
'TODO'.
Definition at line 201 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_fseek()
int xpn_simple_fseek (FILE * stream, long offset, int whence)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
xpn_simple_ftell()
long xpn_simple_ftell (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 247 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_fwrite()
size_t xpn_simple_fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
'TODO'.
'TODO'.
Parameters
ptr 'TODO'.
size 'TODO'.
nmemb 'TODO'.
stream 'TODO'.
Returns
'TODO'.
Definition at line 206 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_lseek()
off_t xpn_simple_lseek (int fd, off_t offset, int flag)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
flag 'TODO'.
Returns
'TODO'.
Definition at line 833 of file xpn_rw.c.
References errno, xpn_filedesc::offset, st, xpn_file_table, and xpn_simple_fstat().
Referenced by xpn_lseek(), xpn_seeker(), xpn_simple_fseek(), and xpn_simple_rewind().
xpn_simple_read()
ssize_t xpn_simple_read (int fd, void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 45 of file xpn_rw.c.
References errno, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, xpn_file_table, xpn_pread(), xpn_sread(), and XpnShowFileTable().
Referenced by xpn_read(), xpn_reader(), xpn_simple_fgetc(), and xpn_simple_fread().
xpn_simple_write()
ssize_t xpn_simple_write (int fd, const void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 74 of file xpn_rw.c.
References errno, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, xpn_file_table, xpn_pwrite(), xpn_swrite(), and XpnShowFileTable().
Referenced by xpn_simple_fwrite(), xpn_write(), and xpn_writer().
xpn_sread()
ssize_t xpn_sread (int fd, const void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 103 of file xpn_rw.c.
References xpn_filedesc::block_size, errno, xpn_filedesc::id, nfi_ops::nfi_read, O_WRONLY, xpn_filedesc::offset, op_xpn_read, nfi_server::ops, xpn_filedesc::path, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, XPN_DIR, xpn_file_table, XPN_HEADER_SIZE, XPN_MAX_FILE, XpnGetBlock(), XpnGetFh(), XpnGetServers(), and XpnShowFileTable().
Referenced by xpn_simple_read().
xpn_swrite()
ssize_t xpn_swrite (int fd, const void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 473 of file xpn_rw.c.
References xpn_filedesc::block_size, xpn_filedesc::id, nfi_ops::nfi_write, O_RDONLY, xpn_filedesc::offset, op_xpn_write, nfi_server::ops, xpn_filedesc::path, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DIR, xpn_file_table, XPN_HEADER_SIZE, XPN_MAX_FILE, XpnGetBlock(), XpnGetFh(), and XpnGetServers().
Referenced by xpn_simple_write().
xpn_writer()
ssize_t xpn_writer (void * cookie, const char * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
cookie 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 63 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
References xpn_simple_write().
Referenced by xpn_fopencookie().