xpn_init.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_init.h
Functions
int xpn_destroy_servers (struct xpn_partition *part)
'TODO'.
int xpn_simple_destroy (void)
'TODO'.
int xpn_init_partition (__attribute__((__unused__)) char *partname)
int xpn_simple_init (void)
'TODO'.
Variables
struct xpn_partition xpn_parttable [XPN_MAX_PART]
pthread_mutex_t xpn_init_mutex = PTHREAD_MUTEX_INITIALIZER
int xpn_debug = 0
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_init.c.
Function Documentation
xpn_destroy_servers()
int xpn_destroy_servers (struct xpn_partition * part)
'TODO'.
'TODO'.
Parameters
part 'TODO'.
Returns
'TODO'.
Definition at line 53 of file xpn_init.c.
References xpn_partition::data_nserv, xpn_partition::data_serv, xpn_partition::meta_nserv, xpn_partition::meta_serv, nfi_ops::nfi_disconnect, and nfi_server::ops.
Referenced by xpn_init_partition(), and xpn_simple_destroy().
xpn_init_partition()
int xpn_init_partition (__attribute__((__unused__)) char * partname)
Definition at line 124 of file xpn_init.c.
References xpn_partition::data_nserv, xpn_partition::data_serv, conf_connect_st::fd, xpn_partition::id, xpn_partition::initialized, XPN_DATA_SERVER, XPN_DEBUG, xpn_debug, XPN_DEBUG_BEGIN, XPN_DEBUG_END, xpn_destroy_servers(), xpn_err(), xpn_init_cwd(), xpn_init_file_table(), xpn_init_mutex, XPN_MAX_PART, xpn_parttable, XPNERR_CONF, XpnGetIdPartition(), XpnGetInfoPartition(), XpnGetNextPartition(), XpnGetNumServersPartition(), XpnGetServer(), XpnPartitionClose(), and XpnPartitionOpen().
Referenced by xpn_simple_init().
xpn_simple_destroy()
int xpn_simple_destroy (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 94 of file xpn_init.c.
References xpn_partition::id, nfi_worker_destroy(), XPN_DEBUG_BEGIN, XPN_DEBUG_END, xpn_destroy_file_table(), xpn_destroy_servers(), and xpn_parttable.
Referenced by xpn_destroy().
xpn_simple_init()
int xpn_simple_init (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 303 of file xpn_init.c.
References xpn_init_partition().
Referenced by xpn_init().
Variable Documentation
xpn_debug
int xpn_debug = 0
Definition at line 39 of file xpn_init.c.
Referenced by xpn_init_partition().
xpn_init_mutex
pthread_mutex_t xpn_init_mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 38 of file xpn_init.c.
Referenced by xpn_init_partition().
xpn_parttable
struct xpn_partition xpn_parttable[XPN_MAX_PART]
Definition at line 37 of file xpn_init.c.
Referenced by xpn_init_partition(), xpn_simple_destroy(), XpnCreateMetadata(), XpnGetPartition(), XpnGetServers(), XpnReadMetadata(), XpnSearchPart(), and XpnShowPartitionTable().