xpn_opendir.c File Reference
File to 'TODO'.
#include xpn.h
#include xpn/xpn_simple/xpn_open.h
#include xpn/xpn_simple/xpn_opendir.h
#include xpn/xpn_simple/xpn_policy_opendir.h
Functions
DIR * xpn_simple_opendir (const char *path)
'TODO'.
struct dirent * xpn_simple_readdir (DIR *dirp)
'TODO'.
int xpn_simple_closedir (DIR *dirp)
'TODO'.
void xpn_simple_rewinddir (__attribute__((__unused__)) DIR *dirp)
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_opendir.c.
Function Documentation
xpn_simple_closedir()
int xpn_simple_closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 139 of file xpn_opendir.c.
References xpn_filedesc::data_vfh, xpn_filedesc::links, xpn_filedesc::mdata, xpn_fh::n_nfih, nfi_ops::nfi_closedir, xpn_fh::nfih, nfi_server::ops, xpn_metadata::policy, nfi_fhandle::priv_fh, nfi_fhandle::server, xpn_err(), xpn_file_table, XPN_MAX_FILE, and XPN_OK.
Referenced by xpn_closedir().
xpn_simple_opendir()
DIR * xpn_simple_opendir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 44 of file xpn_opendir.c.
References errno, O_RDONLY, PATH_MAX, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, and xpn_simple_open().
Referenced by xpn_opendir().
xpn_simple_readdir()
struct dirent * xpn_simple_readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 95 of file xpn_opendir.c.
References XPN_DEBUG_BEGIN, XPN_DEBUG_END, xpn_file_table, XPN_MAX_FILE, and XpnGetEntry().
Referenced by xpn_readdir().
xpn_simple_rewinddir()
void xpn_simple_rewinddir (__attribute__((__unused__)) DIR * dirp)
Definition at line 191 of file xpn_opendir.c.
Referenced by xpn_rewinddir().