xpn_init.h File Reference
Header file to 'TODO'.
#include all_system.h
#include base/path_misc.h
#include xpn_policy_init.h
#include xpn_cwd.h
#include xpn_file.h
Macros
#define XPN_MAX_PART 128
Functions
int xpn_init_partition (char *partname)
'TODO'.
int xpn_simple_destroy (void)
'TODO'.
int xpn_simple_init (void)
'TODO'.
Variables
struct xpn_partition xpn_parttable [XPN_MAX_PART]
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_init.h.
Macro Definition Documentation
XPN_MAX_PART
#define XPN_MAX_PART 128
Definition at line 49 of file xpn_init.h.
Function Documentation
xpn_init_partition()
int xpn_init_partition (char * partname)
'TODO'.
'TODO'.
Parameters
partname 'TODO'.
Returns
'TODO'.
xpn_simple_destroy()
int xpn_simple_destroy (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 94 of file xpn_init.c.
References xpn_partition::id, nfi_worker_destroy(), XPN_DEBUG_BEGIN, XPN_DEBUG_END, xpn_destroy_file_table(), xpn_destroy_servers(), and xpn_parttable.
Referenced by xpn_destroy().
xpn_simple_init()
int xpn_simple_init (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 303 of file xpn_init.c.
References xpn_init_partition().
Referenced by xpn_init().
Variable Documentation
xpn_parttable
struct xpn_partition xpn_parttable[XPN_MAX_PART] [extern]
Definition at line 37 of file xpn_init.c.
Referenced by xpn_init_partition(), and xpn_simple_destroy().