xpn_rebuild.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <linux/limits.h>
#include <sys/stat.h>
#include <dirent.h>
#include mpi.h
Macros
#define _LARGEFILE_SOURCE
#define _FILE_OFFSET_BITS 64
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#define HEADER_SIZE 8192
Functions
int copy (char *entry, int is_file, char *dir_name, char *dest_prefix, int blocksize, int rank, int size)
int list (char *dir_name, char *dest_prefix, int blocksize, int rank, int size)
int main (int argc, char *argv[])
Variables
char command [4 *1024]
char src_path [PATH_MAX+5]
char dest_path [PATH_MAX+5]
Macro Definition Documentation
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64
Definition at line 42 of file xpn_rebuild.c.
_LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE
Definition at line 38 of file xpn_rebuild.c.
HEADER_SIZE
#define HEADER_SIZE 8192
Definition at line 46 of file xpn_rebuild.c.
MIN
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
Definition at line 45 of file xpn_rebuild.c.
Function Documentation
copy()
int copy (char * entry, int is_file, char * dir_name, char * dest_prefix, int blocksize, int rank, int size)
Definition at line 54 of file xpn_rebuild.c.
References buf, close(), dest_path, HEADER_SIZE, lseek64(), mkdir(), O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open64(), read(), src_path, and write().
Referenced by list().
list()
int list (char * dir_name, char * dest_prefix, int blocksize, int rank, int size)
Definition at line 158 of file xpn_rebuild.c.
References closedir(), copy(), list(), opendir(), PATH_MAX, and readdir().
Referenced by list(), and main().
main()
int main (int argc, char * argv[])
Definition at line 218 of file xpn_rebuild.c.
References list(), MPI_Finalize(), and MPI_Init().
Variable Documentation
command
char command[4 *1024]
Definition at line 48 of file xpn_rebuild.c.
dest_path
char dest_path[PATH_MAX+5]
Definition at line 50 of file xpn_rebuild.c.
Referenced by copy(), do_cp(), and do_cp_recursive().
src_path
char src_path[PATH_MAX+5]
Definition at line 49 of file xpn_rebuild.c.
Referenced by copy(), do_cp(), and do_cp_recursive().