xpn_bypass.c File Reference
File to 'TODO'.
#include xpn_bypass.h
Functions
int is_xpn_prefix (const char *path)
'TODO'.
const char * skip_xpn_prefix (const char *path)
'TODO'.
void fdstable_realloc (void)
'TODO'.
void fdstable_init (void)
'TODO'.
struct generic_fd fdstable_get (int fd)
'TODO'.
int fdstable_put (struct generic_fd fd)
'TODO'.
int add_xpn_file_to_fdstable (int fd)
'TODO'.
int fdstable_remove (int fd)
'TODO'.
void fdsdirtable_realloc (void)
'TODO'.
void fdsdirtable_init (void)
'TODO'.
int fdsdirtable_get (DIR *dir)
'TODO'.
DIR fdsdirtable_getfd (DIR *dir)
'TODO'.
int fdsdirtable_put (DIR *dir)
'TODO'.
int fdsdirtable_remove (DIR *dir)
'TODO'.
int xpn_adaptor_keepInit (void)
'TODO'.
int open (const char *path, int flags,...)
'TODO'.
int open64 (const char *path, int flags,...)
'TODO'.
int __open_2 (const char *path, int flags,...)
'TODO'.
int creat (const char *path, mode_t mode)
'TODO'.
int ftruncate (int fd, off_t length)
'TODO'.
ssize_t read (int fd, void *buf, size_t nbyte)
'TODO'.
ssize_t write (int fd, const void *buf, size_t nbyte)
'TODO'.
off_t lseek (int fd, off_t offset, int whence)
'TODO'.
off64_t lseek64 (int fd, off64_t offset, int whence)
'TODO'.
int stat_to_stat64 (struct stat64 *buf, struct stat *st)
int __lxstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int __xstat64 (int ver, const char *path, struct stat64 *buf)
'TODO'.
int __fxstat64 (int ver, int fd, struct stat64 *buf)
'TODO'.
int stat64_to_stat (struct stat *buf, struct stat64 *st)
int __lxstat (int ver, const char *path, struct stat *buf)
'TODO'.
int __xstat (int ver, const char *path, struct stat *buf)
'TODO'.
int __fxstat (int ver, int fd, struct stat *buf)
'TODO'.
int close (int fd)
'TODO'.
int rename (const char *old_path, const char *new_path)
'TODO'.
int unlink (const char *path)
'TODO'.
int mkdir (const char *path, mode_t mode)
'TODO'.
DIR * opendir (const char *dirname)
'TODO'.
struct dirent * readdir (DIR *dirp)
'TODO'.
struct dirent64 * readdir64 (DIR *dirp)
'TODO'.
int closedir (DIR *dirp)
'TODO'.
int rmdir (const char *path)
'TODO'.
pid_t fork (void)
'TODO'.
int pipe (int pipefd[2])
int dup (int fd)
'TODO'.
int dup2 (int fd, int fd2)
'TODO'.
void exit (int status)
'TODO'.
int chdir (const char *path)
'TODO'.
int chmod (const char *path, mode_t mode)
'TODO'.
int fchmod (int fd, mode_t mode)
'TODO'.
int chown (const char *path, uid_t owner, gid_t group)
'TODO'.
int fcntl (int fd, int cmd, long arg)
'TODO'.
int access (const char *path, int mode)
'TODO'.
char * realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
char * __realpath_chk (const char *path, char *resolved_path, __attribute__((__unused__)) size_t resolved_len)
int fsync (int fd)
'TODO'.
int MPI_Init (int *argc, char ***argv)
int MPI_Finalize (void)
Variables
static int xpn_adaptor_initCalled = 0
This variable indicates if expand has already been initialized or not.
static int xpn_adaptor_initCalled_getenv = 0
char * xpn_adaptor_partition_prefix = /tmp/expand/
This variable contains the prefix which will be considerated as expand partition.
struct generic_fd * fdstable = NULL
long fdstable_size = 0L
long fdstable_first_free = 0L
DIR ** fdsdirtable = NULL
long fdsdirtable_size = 0L
long fdsdirtable_first_free = 0L
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_bypass.c.
Function Documentation
__fxstat()
int __fxstat (int ver, int fd, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fd 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 1072 of file xpn_bypass.c.
References buf, debug_info, dlsym_fstat(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_fstat().
__fxstat64()
int __fxstat64 (int ver, int fildes, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
fildes 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 960 of file xpn_bypass.c.
References buf, debug_info, dlsym_fxstat64(), FD_XPN, fdstable_get(), generic_fd::real_fd, st, stat_to_stat64(), generic_fd::type, xpn_adaptor_keepInit(), and xpn_fstat().
__lxstat()
int __lxstat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 1016 of file xpn_bypass.c.
References buf, debug_info, dlsym_lstat(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_stat().
__lxstat64()
int __lxstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 888 of file xpn_bypass.c.
References buf, debug_info, dlsym_lxstat64(), is_xpn_prefix(), skip_xpn_prefix(), st, stat_to_stat64(), xpn_adaptor_keepInit(), and xpn_stat().
Referenced by access().
__open_2()
int __open_2 (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 628 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym___open_2(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_open().
__realpath_chk()
char * __realpath_chk (const char * path, char * resolved_path, __attribute__((__unused__)) size_t resolved_len)
Definition at line 1724 of file xpn_bypass.c.
References debug_info, dlsym_realpath(), is_xpn_prefix(), and xpn_adaptor_keepInit().
__xstat()
int __xstat (int ver, const char * path, struct stat * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 1044 of file xpn_bypass.c.
References buf, debug_info, dlsym_stat(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_stat().
__xstat64()
int __xstat64 (int ver, const char * path, struct stat64 * buf)
'TODO'.
'TODO'.
Parameters
ver 'TODO'.
path 'TODO'.
buf 'TODO'.
Returns
'TODO'.
Definition at line 925 of file xpn_bypass.c.
References buf, debug_info, dlsym_xstat64(), is_xpn_prefix(), skip_xpn_prefix(), st, stat_to_stat64(), xpn_adaptor_keepInit(), and xpn_stat().
access()
int access (const char * path, int mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1664 of file xpn_bypass.c.
References __lxstat64(), _STAT_VER, debug_info, dlsym_access(), is_xpn_prefix(), and xpn_adaptor_keepInit().
add_xpn_file_to_fdstable()
int add_xpn_file_to_fdstable (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 226 of file xpn_bypass.c.
References FD_XPN, fdstable_put(), generic_fd::is_file, generic_fd::real_fd, st, generic_fd::type, and xpn_fstat().
Referenced by __open_2(), creat(), open(), and open64().
chdir()
int chdir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1557 of file xpn_bypass.c.
References debug_info, dlsym_chdir(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_chdir().
chmod()
int chmod (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1577 of file xpn_bypass.c.
References debug_info, dlsym_chmod(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_chmod().
chown()
int chown (const char * path, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 1623 of file xpn_bypass.c.
References debug_info, dlsym_chown(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_chown().
close()
int close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 1178 of file xpn_bypass.c.
References debug_info, dlsym_close(), FD_XPN, fdstable_get(), fdstable_remove(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_close().
Referenced by copy(), do_cp(), main(), mpi_server_op_preload(), and tcp_server_comm_close().
closedir()
int closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 1397 of file xpn_bypass.c.
References debug_info, dlsym_closedir(), fdsdirtable_get(), fdsdirtable_remove(), xpn_adaptor_keepInit(), and xpn_closedir().
Referenced by do_cp_recursive(), list(), and list().
creat()
int creat (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 678 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym_creat(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_creat().
Referenced by main().
dup()
int dup (int fildes)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
Returns
'TODO'.
Definition at line 1482 of file xpn_bypass.c.
References debug_info, dlsym_dup(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_dup().
dup2()
int dup2 (int fildes, int fildes2)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
fildes2 'TODO'.
Returns
'TODO'.
Definition at line 1510 of file xpn_bypass.c.
References debug_info, dlsym_dup2(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_dup2().
exit()
void exit (int status)
'TODO'.
'TODO'.
Parameters
status 'TODO'.
Returns
Nothing.
Definition at line 1540 of file xpn_bypass.c.
References debug_info, dlsym_exit(), xpn_adaptor_initCalled, and xpn_destroy().
Referenced by fdsdirtable_realloc(), fdstable_realloc(), and main().
fchmod()
int fchmod (int fildes, mode_t mode)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1597 of file xpn_bypass.c.
References debug_info, dlsym_fchmod(), FD_XPN, fdstable_get(), generic_fd::type, xpn_adaptor_keepInit(), and xpn_fchmod().
fcntl()
int fcntl (int fd, int cmd, long arg)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
cmd 'TODO'.
arg 'TODO'.
Returns
'TODO'.
Definition at line 1643 of file xpn_bypass.c.
References debug_info, dlsym_fcntl(), FD_XPN, fdstable_get(), and generic_fd::type.
fdsdirtable_get()
int fdsdirtable_get (DIR * dir)
'TODO'.
'TODO'.
Parameters
dir 'TODO'.
Returns
'TODO'.
Definition at line 349 of file xpn_bypass.c.
References fdsdirtable, and fdsdirtable_size.
Referenced by closedir(), readdir(), and readdir64().
fdsdirtable_getfd()
DIR fdsdirtable_getfd (DIR * dir)
'TODO'.
'TODO'.
Parameters
dir 'TODO'.
Returns
'TODO'.
Definition at line 370 of file xpn_bypass.c.
References fdstable_get(), and generic_fd::real_fd.
Referenced by readdir(), and readdir64().
fdsdirtable_init()
void fdsdirtable_init (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 336 of file xpn_bypass.c.
References fdsdirtable_realloc().
Referenced by xpn_adaptor_keepInit().
fdsdirtable_put()
int fdsdirtable_put (DIR * dir)
'TODO'.
'TODO'.
Parameters
dir 'TODO'.
Returns
'TODO'.
Definition at line 390 of file xpn_bypass.c.
References FD_XPN, fdsdirtable, fdsdirtable_first_free, fdsdirtable_realloc(), fdsdirtable_size, fdstable_put(), fdstable_size, generic_fd::is_file, generic_fd::real_fd, and generic_fd::type.
Referenced by opendir().
fdsdirtable_realloc()
void fdsdirtable_realloc (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 294 of file xpn_bypass.c.
References exit(), fdsdirtable, fdsdirtable_size, and MAX_DIRS.
Referenced by fdsdirtable_init(), and fdsdirtable_put().
fdsdirtable_remove()
int fdsdirtable_remove (DIR * dir)
'TODO'.
'TODO'.
Parameters
dir 'TODO'.
Returns
'TODO'.
Definition at line 443 of file xpn_bypass.c.
References fdsdirtable, fdsdirtable_first_free, fdsdirtable_size, fdstable_remove(), and PLUSXPN.
Referenced by closedir().
fdstable_get()
struct generic_fd fdstable_get (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 163 of file xpn_bypass.c.
References FD_SYS, fdstable, PLUSXPN, generic_fd::real_fd, and generic_fd::type.
Referenced by __fxstat(), __fxstat64(), close(), dup(), dup2(), fchmod(), fcntl(), fdsdirtable_getfd(), fsync(), ftruncate(), lseek(), lseek64(), read(), and write().
fdstable_init()
void fdstable_init (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 150 of file xpn_bypass.c.
References fdstable_realloc().
Referenced by xpn_adaptor_keepInit().
fdstable_put()
int fdstable_put (struct generic_fd fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 191 of file xpn_bypass.c.
References FD_FREE, fdstable, fdstable_first_free, fdstable_realloc(), fdstable_size, PLUSXPN, and generic_fd::type.
Referenced by add_xpn_file_to_fdstable(), and fdsdirtable_put().
fdstable_realloc()
void fdstable_realloc (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 106 of file xpn_bypass.c.
References exit(), FD_FREE, fdstable, fdstable_size, generic_fd::is_file, MAX_FDS, generic_fd::real_fd, and generic_fd::type.
Referenced by fdstable_init(), and fdstable_put().
fdstable_remove()
int fdstable_remove (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 257 of file xpn_bypass.c.
References FD_FREE, fdstable, fdstable_first_free, generic_fd::is_file, PLUSXPN, generic_fd::real_fd, and generic_fd::type.
Referenced by close(), and fdsdirtable_remove().
fork()
pid_t fork (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 1457 of file xpn_bypass.c.
References debug_info, dlsym_fork(), and xpn_adaptor_initCalled.
fsync()
int fsync (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 1753 of file xpn_bypass.c.
References debug_info, dlsym_fsync(), FD_XPN, fdstable_get(), and generic_fd::type.
Referenced by write_func().
ftruncate()
int ftruncate (int fildes, off_t length)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 706 of file xpn_bypass.c.
References debug_info, dlsym_ftruncate(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_ftruncate().
is_xpn_prefix()
int is_xpn_prefix (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 66 of file xpn_bypass.c.
References xpn_adaptor_partition_prefix.
Referenced by __lxstat(), __lxstat64(), __open_2(), __realpath_chk(), __xstat(), __xstat64(), access(), chdir(), chmod(), chown(), creat(), mkdir(), open(), open64(), opendir(), realpath(), rename(), rmdir(), and unlink().
lseek()
off_t lseek (int fildes, off_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 811 of file xpn_bypass.c.
References debug_info, dlsym_lseek(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_lseek().
Referenced by main().
lseek64()
off64_t lseek64 (int fd, off64_t offset, int whence)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
Definition at line 840 of file xpn_bypass.c.
References debug_info, dlsym_lseek64(), FD_XPN, fdstable_get(), generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_lseek().
Referenced by copy().
mkdir()
int mkdir (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 1269 of file xpn_bypass.c.
References debug_info, dlsym_mkdir(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_mkdir().
Referenced by copy(), and do_cp_recursive().
MPI_Finalize()
int MPI_Finalize (void)
Definition at line 1794 of file xpn_bypass.c.
References xpn_adaptor_initCalled, and xpn_destroy().
Referenced by main(), and mpi_server_comm_destroy().
MPI_Init()
int MPI_Init (int * argc, char *** argv)
Definition at line 1777 of file xpn_bypass.c.
References debug_info, and xpn_adaptor_keepInit().
Referenced by main(), mpi_server_comm_init(), mpi_server_down(), and mpiClient_comm_init().
open()
int open (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 527 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym_open2(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_open().
Referenced by do_cp(), main(), mpi_server_d2xpn(), and tcp_server_d2xpn().
open64()
int open64 (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 577 of file xpn_bypass.c.
References add_xpn_file_to_fdstable(), debug_info, dlsym_open64(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_open().
Referenced by copy().
opendir()
DIR * opendir (const char * dirname)
'TODO'.
'TODO'.
Parameters
dirname 'TODO'.
Returns
'TODO'.
Definition at line 1297 of file xpn_bypass.c.
References debug_info, dlsym_opendir(), fdsdirtable_put(), is_xpn_prefix(), xpn_adaptor_keepInit(), xpn_adaptor_partition_prefix, and xpn_opendir().
Referenced by do_cp_recursive(), list(), and list().
pipe()
int pipe (int pipefd[2])
Definition at line 1474 of file xpn_bypass.c.
References debug_info, and dlsym_pipe().
read()
ssize_t read (int fildes, void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 735 of file xpn_bypass.c.
References buf, debug_info, dlsym_read(), errno, FD_XPN, fdstable_get(), generic_fd::is_file, generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_read().
Referenced by copy(), do_cp(), main(), and tcp_server_comm_read_data().
readdir()
struct dirent * readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 1329 of file xpn_bypass.c.
References debug_info, dlsym_readdir(), fdsdirtable_get(), fdsdirtable_getfd(), xpn_adaptor_keepInit(), and xpn_readdir().
Referenced by do_cp_recursive(), list(), and list().
readdir64()
struct dirent64 * readdir64 (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 1357 of file xpn_bypass.c.
References debug_info, dlsym_readdir64(), fdsdirtable_get(), fdsdirtable_getfd(), xpn_adaptor_keepInit(), and xpn_readdir().
realpath()
char * realpath (const char *restrict path, char *restrict resolved_path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
resolved_path 'TODO'.
Returns
'TODO'.
Definition at line 1702 of file xpn_bypass.c.
References debug_info, dlsym_realpath(), is_xpn_prefix(), and xpn_adaptor_keepInit().
rename()
int rename (const char * old_path, const char * new_path)
'TODO'.
'TODO'.
Parameters
old_path 'TODO'.
new_path 'TODO'.
Returns
'TODO'.
Definition at line 1209 of file xpn_bypass.c.
References debug_info, dlsym_rename(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_rename().
Referenced by ns_unpublish().
rmdir()
int rmdir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1425 of file xpn_bypass.c.
References debug_info, dlsym_rmdir(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_rmdir().
skip_xpn_prefix()
const char * skip_xpn_prefix (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 81 of file xpn_bypass.c.
References xpn_adaptor_partition_prefix.
Referenced by __lxstat(), __lxstat64(), __open_2(), __xstat(), __xstat64(), chdir(), chmod(), chown(), creat(), mkdir(), open(), open64(), rename(), rmdir(), and unlink().
stat64_to_stat()
int stat64_to_stat (struct stat * buf, struct stat64 * st)
Definition at line 997 of file xpn_bypass.c.
References buf, and st.
stat_to_stat64()
int stat_to_stat64 (struct stat64 * buf, struct stat * st)
Definition at line 869 of file xpn_bypass.c.
References buf, and st.
Referenced by __fxstat64(), __lxstat64(), and __xstat64().
unlink()
int unlink (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1240 of file xpn_bypass.c.
References debug_info, dlsym_unlink(), is_xpn_prefix(), skip_xpn_prefix(), xpn_adaptor_keepInit(), and xpn_unlink().
Referenced by main(), and ns_unpublish().
write()
ssize_t write (int fildes, const void * buf, size_t nbyte)
'TODO'.
'TODO'.
Parameters
fildes 'TODO'.
buf 'TODO'.
nbyte 'TODO'.
Returns
'TODO'.
Definition at line 773 of file xpn_bypass.c.
References buf, debug_info, dlsym_write(), errno, FD_XPN, fdstable_get(), generic_fd::is_file, generic_fd::real_fd, generic_fd::type, xpn_adaptor_keepInit(), and xpn_write().
Referenced by copy(), do_cp(), main(), tcp_server_comm_write_data(), and write_func().
xpn_adaptor_keepInit()
int xpn_adaptor_keepInit (void)
'TODO'.
This function checks if expand has already been initialized. If not, it initialize it.
Parameters
None.
Returns
'TODO'.
Definition at line 476 of file xpn_bypass.c.
References debug_info, fdsdirtable_init(), fdstable_init(), xpn_adaptor_initCalled, xpn_adaptor_initCalled_getenv, and xpn_init().
Referenced by __fxstat(), __fxstat64(), __lxstat(), __lxstat64(), __open_2(), __realpath_chk(), __xstat(), __xstat64(), access(), chdir(), chmod(), chown(), close(), closedir(), creat(), dup(), dup2(), fchmod(), ftruncate(), lseek(), lseek64(), mkdir(), MPI_Init(), open(), open64(), opendir(), read(), readdir(), readdir64(), realpath(), rename(), rmdir(), unlink(), and write().
Variable Documentation
fdsdirtable
DIR** fdsdirtable = NULL
Definition at line 280 of file xpn_bypass.c.
Referenced by fdsdirtable_get(), fdsdirtable_put(), fdsdirtable_realloc(), and fdsdirtable_remove().
fdsdirtable_first_free
long fdsdirtable_first_free = 0L
Definition at line 282 of file xpn_bypass.c.
Referenced by fdsdirtable_put(), and fdsdirtable_remove().
fdsdirtable_size
long fdsdirtable_size = 0L
Definition at line 281 of file xpn_bypass.c.
Referenced by fdsdirtable_get(), fdsdirtable_put(), fdsdirtable_realloc(), and fdsdirtable_remove().
fdstable
struct generic_fd* fdstable = NULL
Definition at line 92 of file xpn_bypass.c.
Referenced by fdstable_get(), fdstable_put(), fdstable_realloc(), and fdstable_remove().
fdstable_first_free
long fdstable_first_free = 0L
Definition at line 94 of file xpn_bypass.c.
Referenced by fdstable_put(), and fdstable_remove().
fdstable_size
long fdstable_size = 0L
Definition at line 93 of file xpn_bypass.c.
Referenced by fdsdirtable_put(), fdstable_put(), and fdstable_realloc().
xpn_adaptor_initCalled
int xpn_adaptor_initCalled = 0 [static]
This variable indicates if expand has already been initialized or not.
0 indicates that expand has NOT been initialized yet. 1 indicates that expand has already been initialized.
Definition at line 45 of file xpn_bypass.c.
Referenced by exit(), fork(), MPI_Finalize(), and xpn_adaptor_keepInit().
xpn_adaptor_initCalled_getenv
int xpn_adaptor_initCalled_getenv = 0 [static]
Definition at line 46 of file xpn_bypass.c.
Referenced by xpn_adaptor_keepInit().
xpn_adaptor_partition_prefix
char* xpn_adaptor_partition_prefix = /tmp/expand/
This variable contains the prefix which will be considerated as expand partition.
Definition at line 52 of file xpn_bypass.c.
Referenced by __open_2(), is_xpn_prefix(), open(), open64(), opendir(), and skip_xpn_prefix().