xpn_policy_rw.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_policy_rw.h
Functions
int XpnGetBlock (int fd, off_t offset, off_t *local_offset, int *serv)
Calculates the server and the offset.
void XpnRWBlocksPolicyBlockByBlock (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
The blocks that have to be read/written from/to the servers are selected by round-robin: one block from each server.
void XpnReadBlocksPolicyRAID0_AllInOne (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
The blocks that have to be read from the servers are selected by round-robin (one block from each server), and then, grouped in one operation per server.
void XpnReadBlocksPolicyRAID0_AllInOne_Finish (int fd, void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers, const void *new_buffer)
This is the complementary operation to XpnRWBlocksPolicyRAID0_AllInOne.
void XpnWriteBlocksPolicyRAID0_AllInOne (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers, void *new_buffer)
The blocks that have to be written to the servers are selected by round-robin (one block from each server), and then, grouped in one operation per server.
void XpnReadBlocksPolicyRAID1_AllInOne (__attribute__((__unused__)) int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
The blocks that have to be read from the servers are 1/n of the file from each server (being 'n' the number of servers).
void XpnWriteBlocksPolicyRAID1_BlockByBlock (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
The blocks that have to be read/written from/to the servers are every block from every server.
void XpnWriteBlocksPolicyRAID1_AllInOne (__attribute__((__unused__)) int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
The blocks that have to be written to the servers are every block from every server.
void * XpnReadBlocks (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
Read blocks.
int XpnReadBlocksFinish (int fd, void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers, void *new_buffer)
'TODO'.
void * XpnWriteBlocks (int fd, const void *buffer, size_t size, off_t offset, struct nfi_worker_io ***io_out, int **ion_out, int num_servers)
Write blocks.
int XpnWriteBlocksFinish (int fd, const void *buffer, __attribute__((__unused__)) size_t size, __attribute__((__unused__)) off_t offset, __attribute__((__unused__)) struct nfi_worker_io ***io_out, __attribute__((__unused__)) int **ion_out, __attribute__((__unused__)) int num_servers, void *new_buffer)
ssize_t XpnReadGetTotalBytes (int fd, ssize_t *res_v, int num_servers)
'TODO'.
ssize_t XpnWriteGetTotalBytes (int fd, ssize_t *res_v, int num_servers)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_policy_rw.c.
Function Documentation
XpnGetBlock()
int XpnGetBlock (int fd, off_t global_offset, off_t * local_offset, int * serv)
Calculates the server and the offset.
Calculates the server and the offset in that server of the given offset of a file.
Parameters
fd [in] A file descriptor.
global_offset [in] The original offset.
local_offset [out] The offset in the server.
serv [out] The server in which is located the given offset.
Returns
Returns 0 on success or -1 on error.
Definition at line 41 of file xpn_policy_rw.c.
References xpn_filedesc::block_size, policy::first_node, POLICY_RAID0, POLICY_RAID1, and xpn_file_table.
Referenced by xpn_sread(), xpn_swrite(), XpnReadBlocks(), XpnRWBlocksPolicyBlockByBlock(), and XpnWriteBlocksPolicyRAID1_BlockByBlock().
XpnReadBlocks()
void * XpnReadBlocks (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
Read blocks.
Calculates how the blocks have to be read from the servers. io_out is an operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'. While ion_out[i] is the number of operations in server 'i' (io_out[i]).
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix.
ion_out [out] The length of every row in io_out.
num_servers [in] The number of servers.
Returns
Returns a pointer to a new buffer on success, or NULL on error.
Definition at line 363 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, POLICY_RAID0, POLICY_RAID1, nfi_worker_io::size, xpn_file_table, XpnGetBlock(), XpnReadBlocksPolicyRAID0_AllInOne(), XpnReadBlocksPolicyRAID1_AllInOne(), and XpnRWBlocksPolicyBlockByBlock().
Referenced by xpn_pread().
XpnReadBlocksFinish()
int XpnReadBlocksFinish (int fd, void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers, void * new_buffer)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
io_out 'TODO'.
ion_out 'TODO'.
num_servers 'TODO'.
new_buffer 'TODO'.
Returns
'TODO'.
Definition at line 419 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, POLICY_RAID0, POLICY_RAID1, nfi_worker_io::size, xpn_file_table, and XpnReadBlocksPolicyRAID0_AllInOne_Finish().
Referenced by xpn_pread().
XpnReadBlocksPolicyRAID0_AllInOne()
void XpnReadBlocksPolicyRAID0_AllInOne (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
The blocks that have to be read from the servers are selected by round-robin (one block from each server), and then, grouped in one operation per server.
Using this policy the nfi module will perform at most one read operation per server. This policy requires the execution of XpnReadBlocksPolicyRAID0_AllInOne_Finish when the data have arrived, which will reorder the blocks. This policy is valid for read operations on a RAID0 partition.
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'.
ion_out [out] The length of every row in io_out. ion_out[i] is the number of operations in server 'i' (io_out[i]).
num_servers [in] The number of servers.
Definition at line 138 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, nfi_worker_io::size, and XpnRWBlocksPolicyBlockByBlock().
Referenced by XpnReadBlocks().
XpnReadBlocksPolicyRAID0_AllInOne_Finish()
void XpnReadBlocksPolicyRAID0_AllInOne_Finish (int fd, void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers, const void * new_buffer)
This is the complementary operation to XpnRWBlocksPolicyRAID0_AllInOne.
The blocks that have been read and grouped by XpnReadBlocksPolicyRAID0_AllInOne are now reordered before delivering them to the user. This policy is valid for read operations on a RAID0 partition.
Parameters
fd [in] A file descriptor.
buffer [out] The ordered buffer to be delivered to the user. This buffer will contain the same blocks that new_buffer, but in the right order.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'.
ion_out [out] The length of every row in io_out. ion_out[i] is the number of operations in server 'i' (io_out[i]).
num_servers [in] The number of servers.
new_buffer [in] The disorganized buffer that needs to be ordered.
Definition at line 178 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, nfi_worker_io::size, and XpnRWBlocksPolicyBlockByBlock().
Referenced by XpnReadBlocksFinish().
XpnReadBlocksPolicyRAID1_AllInOne()
void XpnReadBlocksPolicyRAID1_AllInOne (__attribute__((__unused__)) int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
The blocks that have to be read from the servers are 1/n of the file from each server (being 'n' the number of servers).
This policy is only valid for read operations on a RAID1 partition.
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'.
ion_out [out] The length of every row in io_out. ion_out[i] is the number of operations in server 'i' (io_out[i]).
num_servers [in] The number of servers.
Definition at line 258 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, and nfi_worker_io::size.
Referenced by XpnReadBlocks().
XpnReadGetTotalBytes()
ssize_t XpnReadGetTotalBytes (int fd, ssize_t * res_v, int num_servers)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
res_v 'TODO'.
num_servers 'TODO'.
Returns
'TODO'.
Definition at line 502 of file xpn_policy_rw.c.
References POLICY_RAID0, POLICY_RAID1, and xpn_file_table.
Referenced by xpn_pread().
XpnRWBlocksPolicyBlockByBlock()
void XpnRWBlocksPolicyBlockByBlock (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
The blocks that have to be read/written from/to the servers are selected by round-robin: one block from each server.
Using this policy the nfi module will perform one read/write operation for every single block on every server, which is not optimal. This policy is valid for read/write operations on a RAID0 partition, and for read operations on a RAID1 partition.
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'.
ion_out [out] The length of every row in io_out. ion_out[i] is the number of operations in server 'i' (io_out[i]).
num_servers [in] The number of servers.
Definition at line 87 of file xpn_policy_rw.c.
References xpn_filedesc::block_size, nfi_worker_io::buffer, nfi_worker_io::offset, nfi_worker_io::size, xpn_file_table, and XpnGetBlock().
Referenced by XpnReadBlocks(), XpnReadBlocksPolicyRAID0_AllInOne(), XpnReadBlocksPolicyRAID0_AllInOne_Finish(), XpnWriteBlocks(), and XpnWriteBlocksPolicyRAID0_AllInOne().
XpnWriteBlocks()
void * XpnWriteBlocks (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
Write blocks.
Calculates how the blocks have to be written to the servers. io_out is an operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'. While ion_out[i] is the number of operations in server 'i' (io_out[i]).
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix.
ion_out [out] The length of every row in io_out.
num_servers [in] The number of servers.
Returns
Returns 0 on success or -1 on error.
Definition at line 441 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, POLICY_RAID0, POLICY_RAID1, nfi_worker_io::size, xpn_file_table, XpnRWBlocksPolicyBlockByBlock(), XpnWriteBlocksPolicyRAID0_AllInOne(), XpnWriteBlocksPolicyRAID1_AllInOne(), and XpnWriteBlocksPolicyRAID1_BlockByBlock().
Referenced by xpn_pwrite().
XpnWriteBlocksFinish()
int XpnWriteBlocksFinish (int fd, const void * buffer, __attribute__((__unused__)) size_t size, __attribute__((__unused__)) off_t offset, __attribute__((__unused__)) struct nfi_worker_io *** io_out, __attribute__((__unused__)) int ** ion_out, __attribute__((__unused__)) int num_servers, void * new_buffer)
Definition at line 476 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, POLICY_RAID0, POLICY_RAID1, and xpn_file_table.
Referenced by xpn_pwrite().
XpnWriteBlocksPolicyRAID0_AllInOne()
void XpnWriteBlocksPolicyRAID0_AllInOne (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers, void * new_buffer)
The blocks that have to be written to the servers are selected by round-robin (one block from each server), and then, grouped in one operation per server.
Using this policy the nfi module will perform at most one write operation per server. This policy is valid for write operations on a RAID0 partition.
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'.
ion_out [out] The length of every row in io_out. ion_out[i] is the number of operations in server 'i' (io_out[i]).
num_servers [in] The number of servers.
new_buffer [in] The buffer used to send data (it will be modified to store the disorganized blocks before sending).
Definition at line 213 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, nfi_worker_io::size, and XpnRWBlocksPolicyBlockByBlock().
Referenced by XpnWriteBlocks().
XpnWriteBlocksPolicyRAID1_AllInOne()
void XpnWriteBlocksPolicyRAID1_AllInOne (__attribute__((__unused__)) int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
The blocks that have to be written to the servers are every block from every server.
All the blocks are written in one operation per server. This policy is suitable for write operations on a RAID1 partition.
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'.
ion_out [out] The length of every row in io_out. ion_out[i] is the number of operations in server 'i' (io_out[i]).
num_servers [in] The number of servers.
Definition at line 347 of file xpn_policy_rw.c.
References nfi_worker_io::buffer, nfi_worker_io::offset, and nfi_worker_io::size.
Referenced by XpnWriteBlocks().
XpnWriteBlocksPolicyRAID1_BlockByBlock()
void XpnWriteBlocksPolicyRAID1_BlockByBlock (int fd, const void * buffer, size_t size, off_t offset, struct nfi_worker_io *** io_out, int ** ion_out, int num_servers)
The blocks that have to be read/written from/to the servers are every block from every server.
Every block requires one operation. This policy is suitable for write operations on a RAID1 partition.
Parameters
fd [in] A file descriptor.
buffer [in] The original buffer.
size [in] The original size.
offset [in] The original offset.
io_out [out] The operation matrix. io_out[i] (row 'i' in io_out) contains the required operations in server 'i'.
ion_out [out] The length of every row in io_out. ion_out[i] is the number of operations in server 'i' (io_out[i]).
num_servers [in] The number of servers.
Definition at line 296 of file xpn_policy_rw.c.
References xpn_filedesc::block_size, nfi_worker_io::buffer, nfi_worker_io::offset, nfi_worker_io::size, xpn_file_table, and XpnGetBlock().
Referenced by XpnWriteBlocks().
XpnWriteGetTotalBytes()
ssize_t XpnWriteGetTotalBytes (int fd, ssize_t * res_v, int num_servers)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
res_v 'TODO'.
num_servers 'TODO'.
Returns
'TODO'.
Definition at line 523 of file xpn_policy_rw.c.
References POLICY_RAID0, POLICY_RAID1, and xpn_file_table.
Referenced by xpn_pwrite().