xpn_policy_opendir.h File Reference
Header file to 'TODO'.
#include xpn_file.h
#include xpn.h
Functions
int XpnGetEntry (int fd, struct dirent *entry)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_policy_opendir.h.
Function Documentation
XpnGetEntry()
int XpnGetEntry (int fd, struct dirent * entry)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
entry 'TODO'.
Returns
'TODO'.
Definition at line 44 of file xpn_policy_opendir.c.
References xpn_filedesc::data_vfh, xpn_filedesc::id, nfi_ops::nfi_readdir, xpn_fh::nfih, op_xpn_readdir, nfi_server::ops, xpn_filedesc::path, nfi_fhandle::server, XPN_DATA_SERVER, XPN_DEBUG_BEGIN, XPN_DEBUG_END, xpn_file_table, XpnGetFh(), and XpnGetServers().
Referenced by xpn_simple_readdir().