tcp_server_comm.h File Reference
Header file to 'TODO'.
#include all_system.h
#include tcp_server_params.h
#include base/utils.h
#include base/ns.h
#include tcp_server_ops.h
Functions
int tcpClient_comm_init (tcpClient_param_st *params)
'TODO'.
int tcpClient_comm_destroy (tcpClient_param_st *params)
'TODO'.
int tcpClient_comm_connect (tcpClient_param_st *params)
'TODO'.
int tcpClient_comm_disconnect (tcpClient_param_st *params)
'TODO'.
int tcpClient_comm_locality (tcpClient_param_st *params)
'TODO'.
ssize_t tcpClient_write_operation (int fd, char *data, ssize_t size, char *msg_id)
'TODO'.
ssize_t tcpClient_write_data (int fd, char *data, ssize_t size, char *msg_id)
'TODO'.
ssize_t tcpClient_read_data (int fd, char *data, ssize_t size, char *msg_id)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.h.
Function Documentation
tcpClient_comm_connect()
int tcpClient_comm_connect (tcpClient_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 63 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_error, debug_info, ns_lookup(), params, and mpi_server_param_st::srv_name.
Referenced by nfi_tcp_server_connect(), and nfi_tcp_server_reconnect().
tcpClient_comm_destroy()
int tcpClient_comm_destroy (tcpClient_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
tcpClient_comm_disconnect()
int tcpClient_comm_disconnect (tcpClient_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
tcpClient_comm_init()
int tcpClient_comm_init (tcpClient_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
tcpClient_comm_locality()
int tcpClient_comm_locality (tcpClient_param_st * params)
'TODO'.
'TODO'.
Parameters
params 'TODO'.
Returns
'TODO'.
Definition at line 181 of file xpn_client/nfi/nfi_tcp_server/tcp_server_comm.c.
References debug_info, debug_warning, mpi_server_param_st::dirbase, params, PATH_MAX, serv_name, TCP_SERVER_GETNODENAME, tcpClient_read_data(), and tcpClient_write_data().
Referenced by nfi_tcp_server_init().
tcpClient_read_data()
ssize_t tcpClient_read_data (int fd, char * data, ssize_t size, char * msg_id)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
data 'TODO'.
size 'TODO'.
msg_id 'TODO'.
Returns
'TODO'.
tcpClient_write_data()
ssize_t tcpClient_write_data (int fd, char * data, ssize_t size, char * msg_id)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
data 'TODO'.
size 'TODO'.
msg_id 'TODO'.
Returns
'TODO'.
tcpClient_write_operation()
ssize_t tcpClient_write_operation (int fd, char * data, ssize_t size, char * msg_id)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
data 'TODO'.
size 'TODO'.
msg_id 'TODO'.
Returns
'TODO'.