xpn_cp.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <string.h>
#include <errno.h>
Macros
#define BUFFER_SIZE (8192 * 1024)
Functions
int do_cp (char *src_path, char *dest_path)
int do_cp_recursive (char *src_path, char *dest_path)
int main (int argc, char *argv[])
Variables
char buf [BUFFER_SIZE]
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE (8192 * 1024)
Definition at line 35 of file xpn_cp.c.
Function Documentation
do_cp()
int do_cp (char * src_path, char * dest_path)
Definition at line 40 of file xpn_cp.c.
References buf, BUFFER_SIZE, close(), dest_path, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), read(), src_path, and write().
Referenced by do_cp_recursive().
do_cp_recursive()
int do_cp_recursive (char * src_path, char * dest_path)
Definition at line 104 of file xpn_cp.c.
References closedir(), dest_path, do_cp(), do_cp_recursive(), errno, mkdir(), opendir(), PATH_MAX, readdir(), and src_path.
Referenced by do_cp_recursive(), and main().
main()
int main (int argc, char * argv[])
Definition at line 178 of file xpn_cp.c.
References do_cp_recursive().
Variable Documentation
buf
char buf[BUFFER_SIZE]
Definition at line 36 of file xpn_cp.c.
Referenced by __fxstat(), __fxstat64(), __lxstat(), __lxstat64(), __xstat(), __xstat64(), copy(), dlsym_fstat(), dlsym_fstatat(), dlsym_fstatat64(), dlsym_fxstat64(), dlsym_lstat(), dlsym_lxstat64(), dlsym_read(), dlsym_stat(), dlsym_write(), dlsym_xstat64(), do_cp(), main(), mpi_server_down(), read(), stat64_to_stat(), stat_to_stat64(), write(), and xdr_pathconf3resok().