xpn_err.h File Reference
Header file to 'TODO'.
#include xpn.h
#include nfi/nfi_lib.h
Enumerations
enum xpn_err_code {
XPN_OK = 0
, XPNERR_PARAM = 1
, XPNERR_MEMORY = 2
, XPNERR_INVALURL = 3
,
XPNERR_CONF = 4
, XPNERR_INITSERV = 5
, XPNERR_GETATTR = 6
, XPNERR_LOOKUP = 7
,
XPNERR_READ = 8
, XPNERR_WRITE = 9
, XPNERR_CREATE = 10
, XPNERR_REMOVE = 11
,
XPNERR_MKDIR = 12
, XPNERR_READDIR = 13
, XPNERR_STATFS = 14
, XPNERR_PATH_NOEXIST = 15
,
XPNERR_PART_NOEXIST = 16
, XPNERR_NOMEMORY = 17
 }
Functions
int xpn_err (int err)
'TODO'.
Variables
int errno
int xpn_errno
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_err.h.
Enumeration Type Documentation
xpn_err_code
enum xpn_err_code
Enumerator
XPN_OK
XPNERR_PARAM
XPNERR_MEMORY
XPNERR_INVALURL
XPNERR_CONF
XPNERR_INITSERV
XPNERR_GETATTR
XPNERR_LOOKUP
XPNERR_READ
XPNERR_WRITE
XPNERR_CREATE
XPNERR_REMOVE
XPNERR_MKDIR
XPNERR_READDIR
XPNERR_STATFS
XPNERR_PATH_NOEXIST
XPNERR_PART_NOEXIST
XPNERR_NOMEMORY
Definition at line 46 of file xpn_err.h.
Function Documentation
xpn_err()
int xpn_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
'TODO'.
Definition at line 44 of file xpn_err.c.
References errno, and xpn_errno.
Referenced by xpn_init_partition(), xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), xpn_simple_close(), xpn_simple_closedir(), xpn_simple_creat(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_open(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), xpn_simple_stat(), XpnGetAtribFd(), XpnGetAtribPath(), and XpnGetServer().
Variable Documentation
errno
int errno [extern]
xpn_errno
int xpn_errno [extern]
Definition at line 38 of file xpn_err.c.
Referenced by xpn_err().