xpn_dir.h File Reference
Header file to 'TODO'.
#include xpn.h
#include xpn_err.h
#include xpn_policy_init.h
#include xpn_policy_open.h
Functions
int xpn_simple_mkdir (const char *path, mode_t perm)
'TODO'.
int xpn_simple_rmdir (const char *path)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_dir.h.
Function Documentation
xpn_simple_mkdir()
int xpn_simple_mkdir (const char * path, mode_t perm)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
Returns
'TODO'.
Definition at line 41 of file xpn_dir.c.
References nfi_attr::at_mode, xpn_fh::n_nfih, nfi_ops::nfi_close, nfi_worker_do_mkdir(), xpn_fh::nfih, nfiworker_wait(), op_xpn_mkdir, nfi_server::ops, PATH_MAX, nfi_fhandle::priv_fh, nfi_fhandle::server, XPN_DATA_SERVER, xpn_err(), XpnCreateMetadata(), XPNERR_NOMEMORY, XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XPNERR_REMOVE, XpnGetAbsolutePath(), XpnGetPartition(), XpnGetServers(), XpnGetURLServer(), and XpnUpdateMetadata().
Referenced by xpn_mkdir().
xpn_simple_rmdir()
int xpn_simple_rmdir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 230 of file xpn_dir.c.
References nfi_worker_do_rmdir(), nfiworker_wait(), op_xpn_rmdir, PATH_MAX, nfi_server::wrk, XPN_DATA_SERVER, xpn_err(), XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XPNERR_REMOVE, XpnGetAbsolutePath(), XpnGetPartition(), XpnGetServers(), and XpnGetURLServer().
Referenced by xpn_rmdir().