xpn_policy_init.h File Reference
Header file to 'TODO'.
#include xpn_err.h
#include xpn.h
#include xpn_init.h
Data Structures
struct conf_connect_st
Macros
#define XPN_DATA_SERVER 0
#define XPN_META_SERVER 1
#define CONF_DEFAULT CONF_FILE
#define XPN_CONF XPN_CONF
#define XPN_CONF_DEFAULT /etc/xpn/xpn.conf
Enumerations
enum type_conf_connection { CONF_FILE = 0
, CONF_RPC = 1
, CONF_DESC = 2
, CONF_MXML = 3
 }
Functions
struct conf_connect_st * XpnPartitionOpen (void)
'TODO'.
void XpnPartitionClose (struct conf_connect_st *fconf)
'TODO'.
int XpnGetNextPartition (struct conf_connect_st *fconf, char *name)
'TODO'.
int XpnGetIdPartition (struct conf_connect_st *fconf, char *name)
'TODO'.
int XpnGetInfoPartition (struct conf_connect_st *fconf, struct xpn_partition *part)
'TODO'.
int XpnGetNumServersPartition (struct conf_connect_st *fconf, struct xpn_partition *part, int type)
'TODO'.
struct xpn_partition * XpnSearchPart (int pd)
'TODO'.
int XpnGetServer (struct conf_connect_st *fconf, struct xpn_partition *part, struct nfi_server *serv, int type)
'TODO'.
int XpnGetPartition (char *path)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_policy_init.h.
Macro Definition Documentation
CONF_DEFAULT
#define CONF_DEFAULT CONF_FILE
Definition at line 65 of file xpn_policy_init.h.
XPN_CONF
#define XPN_CONF XPN_CONF
Definition at line 125 of file xpn_policy_init.h.
XPN_CONF_DEFAULT
#define XPN_CONF_DEFAULT /etc/xpn/xpn.conf
Definition at line 132 of file xpn_policy_init.h.
XPN_DATA_SERVER
#define XPN_DATA_SERVER 0
Definition at line 59 of file xpn_policy_init.h.
XPN_META_SERVER
#define XPN_META_SERVER 1
Definition at line 60 of file xpn_policy_init.h.
Enumeration Type Documentation
type_conf_connection
enum type_conf_connection
Enumerator
CONF_FILE
CONF_RPC
CONF_DESC
CONF_MXML
Definition at line 51 of file xpn_policy_init.h.
Function Documentation
XpnGetIdPartition()
int XpnGetIdPartition (struct conf_connect_st * fconf, char * name)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
name 'TODO'.
Returns
'TODO'.
XpnGetInfoPartition()
int XpnGetInfoPartition (struct conf_connect_st * fconf, struct xpn_partition * part)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
part 'TODO'.
Returns
'TODO'.
Definition at line 213 of file xpn_policy_init.c.
References xpn_partition::block_size, CONF_FILE, CONF_MXML, conf_connect_st::connect_u, xpn_partition::data_nserv, debug_info, conf_connect_st::f, getSizeFactor(), KB, xpn_partition::meta_nserv, xpn_partition::name, POLICY_RAID0, POLICY_RAID1, xpn_partition::size_threads, xpn_partition::type, and conf_connect_st::type.
Referenced by xpn_init_partition().
XpnGetNextPartition()
int XpnGetNextPartition (struct conf_connect_st * fconf, char * name)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
name 'TODO'.
Returns
'TODO'.
Definition at line 164 of file xpn_policy_init.c.
References CONF_FILE, CONF_MXML, conf_connect_st::connect_u, conf_connect_st::f, and conf_connect_st::type.
Referenced by xpn_init_partition().
XpnGetNumServersPartition()
int XpnGetNumServersPartition (struct conf_connect_st * fconf, struct xpn_partition * part, int type)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
part 'TODO'.
type 'TODO'.
Returns
'TODO'.
Definition at line 379 of file xpn_policy_init.c.
References CONF_FILE, CONF_MXML, xpn_partition::data_nserv, xpn_partition::meta_nserv, conf_connect_st::type, XPN_DATA_SERVER, and XPN_META_SERVER.
Referenced by xpn_init_partition().
XpnGetPartition()
int XpnGetPartition (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 550 of file xpn_policy_init.c.
References getNamePart(), xpn_partition::id, PATH_MAX, XPN_MAX_PART, and xpn_parttable.
Referenced by xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), and XpnGetAtribPath().
XpnGetServer()
int XpnGetServer (struct conf_connect_st * fconf, struct xpn_partition * part, struct nfi_server * serv, int type)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
part 'TODO'.
serv 'TODO'.
type 'TODO'.
Returns
'TODO'.
XpnPartitionClose()
void XpnPartitionClose (struct conf_connect_st * fconf)
'TODO'.
'TODO'.
Parameters
fconf 'TODO'.
Returns
Nothing.
Definition at line 138 of file xpn_policy_init.c.
References CONF_FILE, CONF_MXML, conf_connect_st::connect_u, conf_connect_st::f, and conf_connect_st::type.
Referenced by xpn_init_partition().
XpnPartitionOpen()
struct conf_connect_st * XpnPartitionOpen (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 65 of file xpn_policy_init.c.
References CONF_DEFAULT, CONF_FILE, CONF_MXML, conf_connect_st::connect_u, conf_connect_st::f, param_get(), PATH_MAX, conf_connect_st::type, XPN_CONF, XPN_CONF_DEFAULT, and XPN_DEBUG.
Referenced by xpn_init_partition().
XpnSearchPart()
struct xpn_partition * XpnSearchPart (int pd)
'TODO'.
'TODO'.
Parameters
pd 'TODO'.
Returns
'TODO'.
Definition at line 572 of file xpn_policy_init.c.
References XPN_MAX_PART, and xpn_parttable.
Referenced by XpnSearchSlotFile().