xpn.h File Reference
Header file to 'TODO'.
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <dirent.h>
Functions
char * xpn_getcwd (char *path, size_t size)
'TODO'.
int xpn_chdir (char *path)
'TODO'.
int xpn_mkdir (const char *path, mode_t perm)
'TODO'.
int xpn_rmdir (const char *path)
'TODO'.
int xpn_init (void)
'TODO'.
int xpn_destroy (void)
'TODO'.
int xpn_flush (const char *virtual_path, const char *storage_path)
'TODO'.
int xpn_preload (const char *virtual_path, const char *storage_path)
'TODO'.
int xpn_creat (const char *path, mode_t perm)
'TODO'.
int xpn_open (const char *path, int flags,...)
'TODO'.
int xpn_close (int fd)
'TODO'.
int xpn_unlink (const char *path)
'TODO'.
int xpn_rename (const char *path, const char *newpath)
'TODO'.
int xpn_fstat (int fd, struct stat *sb)
'TODO'.
int xpn_stat (const char *path, struct stat *sb)
'TODO'.
int xpn_chown (const char *path, uid_t owner, gid_t group)
'TODO'.
int xpn_fchown (int fd, uid_t owner, gid_t group)
'TODO'.
int xpn_chmod (const char *path, mode_t mode)
'TODO'.
int xpn_fchmod (int fd, mode_t mode)
'TODO'.
int xpn_truncate (const char *path, off_t length)
'TODO'.
int xpn_ftruncate (int fd, off_t length)
'TODO'.
int xpn_dup (int fd)
'TODO'.
int xpn_dup2 (int fd, int fd2)
'TODO'.
DIR * xpn_opendir (const char *path)
'TODO'.
int xpn_closedir (DIR *dirp)
'TODO'.
struct dirent * xpn_readdir (DIR *dirp)
'TODO'.
void xpn_rewinddir (DIR *dirp)
'TODO'.
ssize_t xpn_read (int fd, void *buffer, size_t size)
'TODO'.
ssize_t xpn_write (int fd, const void *buffer, size_t size)
'TODO'.
ssize_t xpn_pread (int fd, void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_pwrite (int fd, const void *buffer, size_t size, off_t offset)
'TODO'.
off_t xpn_lseek (int fd, off_t offset, int flag)
'TODO'.
FILE * xpn_fopen (const char *filename, const char *mode)
'TODO'.
int xpn_fclose (FILE *stream)
'TODO'.
size_t xpn_fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
'TODO'.
size_t xpn_fread_prefetch (void *ptr, size_t size, size_t nmemb, FILE *stream)
'TODO'.
size_t xpn_fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
'TODO'.
int xpn_fflush (FILE *stream)
'TODO'.
int xpn_fseek (FILE *stream, off_t offset, int whence)
'TODO'.
long xpn_ftell (FILE *stream)
'TODO'.
int xpn_fileno (FILE *stream)
'TODO'.
void xpn_setbuf (FILE *stream, char *buf)
'TODO'.
void xpn_setbuffer (FILE *stream, char *buf, size_t size)
'TODO'.
void xpn_setlinebuf (FILE *stream)
'TODO'.
int xpn_setvbuf (FILE *stream, char *buf, int mode, size_t size)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn.h.
Function Documentation
xpn_chdir()
int xpn_chdir (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 151 of file xpn_unistd.c.
References xpn_simple_chdir().
Referenced by chdir().
xpn_chmod()
int xpn_chmod (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 294 of file xpn_unistd.c.
References xpn_simple_chmod().
Referenced by chmod().
xpn_chown()
int xpn_chown (const char * path, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 276 of file xpn_unistd.c.
References xpn_simple_chown().
Referenced by chown().
xpn_close()
int xpn_close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 98 of file xpn_unistd.c.
References xpn_simple_close().
Referenced by close(), and main().
xpn_closedir()
int xpn_closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 204 of file xpn_unistd.c.
References xpn_simple_closedir().
Referenced by closedir(), and main().
xpn_creat()
int xpn_creat (const char * path, mode_t perm)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
Returns
'TODO'.
Definition at line 68 of file xpn_unistd.c.
References xpn_simple_creat().
Referenced by creat().
xpn_destroy()
int xpn_destroy (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 55 of file xpn_unistd.c.
References xpn_simple_destroy().
Referenced by exit(), main(), and MPI_Finalize().
xpn_dup()
int xpn_dup (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 316 of file xpn_unistd.c.
References xpn_simple_dup().
Referenced by dup().
xpn_dup2()
int xpn_dup2 (int fd, int fd2)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
fd2 'TODO'.
Returns
'TODO'.
Definition at line 325 of file xpn_unistd.c.
References xpn_simple_dup2().
Referenced by dup2().
xpn_fchmod()
int xpn_fchmod (int fd, mode_t mode)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 303 of file xpn_unistd.c.
References xpn_simple_fchmod().
Referenced by fchmod().
xpn_fchown()
int xpn_fchown (int fd, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 285 of file xpn_unistd.c.
References xpn_simple_fchown().
xpn_fclose()
int xpn_fclose (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 50 of file xpn_stdio.c.
References xpn_simple_fclose().
xpn_fflush()
int xpn_fflush (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 69 of file xpn_stdio.c.
References xpn_simple_fflush().
xpn_fileno()
int xpn_fileno (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 130 of file xpn_stdio.c.
References xpn_simple_fileno().
xpn_flush()
int xpn_flush (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 102 of file xpn_stdio.c.
References xpn_simple_flush().
xpn_fopen()
FILE * xpn_fopen (const char * filename, const char * mode)
'TODO'.
'TODO'.
Parameters
filename 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 45 of file xpn_stdio.c.
References xpn_simple_fopen().
xpn_fread()
size_t xpn_fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
'TODO'.
'TODO'.
Parameters
ptr 'TODO'.
size 'TODO'.
nmemb 'TODO'.
stream 'TODO'.
Returns
'TODO'.
xpn_fread_prefetch()
size_t xpn_fread_prefetch (void * ptr, size_t size, size_t nmemb, FILE * stream)
'TODO'.
'TODO'.
Parameters
ptr 'TODO'.
size 'TODO'.
nmemb 'TODO'.
stream 'TODO'.
Returns
'TODO'.
xpn_fseek()
int xpn_fseek (FILE * stream, off_t offset, int whence)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
offset 'TODO'.
whence 'TODO'.
Returns
'TODO'.
xpn_fstat()
int xpn_fstat (int fd, struct stat * sb)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 267 of file xpn_unistd.c.
References xpn_simple_fstat().
Referenced by __fxstat(), __fxstat64(), and add_xpn_file_to_fdstable().
xpn_ftell()
long xpn_ftell (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
'TODO'.
Definition at line 83 of file xpn_stdio.c.
References xpn_simple_ftell().
xpn_ftruncate()
int xpn_ftruncate (int fd, off_t length)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 249 of file xpn_unistd.c.
References xpn_simple_ftruncate().
Referenced by ftruncate().
xpn_fwrite()
size_t xpn_fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
'TODO'.
'TODO'.
Parameters
ptr 'TODO'.
size 'TODO'.
nmemb 'TODO'.
stream 'TODO'.
Returns
'TODO'.
xpn_getcwd()
char * xpn_getcwd (char * path, size_t size)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 142 of file xpn_unistd.c.
References xpn_simple_getcwd().
xpn_init()
int xpn_init (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 46 of file xpn_unistd.c.
References xpn_simple_init().
Referenced by main(), mpi_server_d2xpn(), tcp_server_d2xpn(), and xpn_adaptor_keepInit().
xpn_lseek()
off_t xpn_lseek (int fd, off_t offset, int flag)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
flag 'TODO'.
Returns
'TODO'.
Definition at line 129 of file xpn_unistd.c.
References xpn_simple_lseek().
Referenced by lseek(), and lseek64().
xpn_mkdir()
int xpn_mkdir (const char * path, mode_t perm)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
Returns
'TODO'.
Definition at line 164 of file xpn_unistd.c.
References xpn_simple_mkdir().
Referenced by main(), and mkdir().
xpn_open()
int xpn_open (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 77 of file xpn_unistd.c.
References O_CREAT, and xpn_simple_open().
Referenced by __open_2(), main(), mpi_server_d2xpn(), open(), open64(), and tcp_server_d2xpn().
xpn_opendir()
DIR * xpn_opendir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 186 of file xpn_unistd.c.
References xpn_simple_opendir().
Referenced by main(), and opendir().
xpn_pread()
ssize_t xpn_pread (int fd, void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 209 of file xpn_rw.c.
xpn_preload()
int xpn_preload (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 97 of file xpn_stdio.c.
References xpn_simple_preload().
xpn_pwrite()
ssize_t xpn_pwrite (int fd, const void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 573 of file xpn_rw.c.
xpn_read()
ssize_t xpn_read (int fd, void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 111 of file xpn_unistd.c.
References xpn_simple_read().
Referenced by main(), and read().
xpn_readdir()
struct dirent * xpn_readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 195 of file xpn_unistd.c.
References xpn_simple_readdir().
Referenced by main(), readdir(), and readdir64().
xpn_rename()
int xpn_rename (const char * path, const char * newpath)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
newpath 'TODO'.
Returns
'TODO'.
Definition at line 231 of file xpn_unistd.c.
References xpn_simple_rename().
Referenced by rename().
xpn_rewinddir()
void xpn_rewinddir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
Nothing.
Definition at line 213 of file xpn_unistd.c.
References xpn_simple_rewinddir().
xpn_rmdir()
int xpn_rmdir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 173 of file xpn_unistd.c.
References xpn_simple_rmdir().
Referenced by main(), and rmdir().
xpn_setbuf()
void xpn_setbuf (FILE * stream, char * buf)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
buf 'TODO'.
Returns
Nothing.
xpn_setbuffer()
void xpn_setbuffer (FILE * stream, char * buf, size_t size)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
buf 'TODO'.
size 'TODO'.
Returns
Nothing.
xpn_setlinebuf()
void xpn_setlinebuf (FILE * stream)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
Returns
Nothing.
xpn_setvbuf()
int xpn_setvbuf (FILE * stream, char * buf, int mode, size_t size)
'TODO'.
'TODO'.
Parameters
stream 'TODO'.
buf 'TODO'.
mode 'TODO'.
size 'TODO'.
Returns
'TODO'.
xpn_stat()
int xpn_stat (const char * path, struct stat * sb)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 258 of file xpn_unistd.c.
References xpn_simple_stat().
Referenced by __lxstat(), __lxstat64(), __xstat(), __xstat64(), and main().
xpn_truncate()
int xpn_truncate (const char * path, off_t length)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 240 of file xpn_unistd.c.
References xpn_simple_truncate().
xpn_unlink()
int xpn_unlink (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 222 of file xpn_unistd.c.
References xpn_simple_unlink().
Referenced by main(), and unlink().
xpn_write()
ssize_t xpn_write (int fd, const void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 120 of file xpn_unistd.c.
References xpn_simple_write().
Referenced by main(), write(), and write_func().