xpn_err.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_err.h
Functions
int xpn_err (int err)
'TODO'.
Variables
int errno
int xpn_errno
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_err.c.
Function Documentation
xpn_err()
int xpn_err (int err)
'TODO'.
'TODO'.
Parameters
err 'TODO'.
Returns
'TODO'.
Definition at line 44 of file xpn_err.c.
References errno, and xpn_errno.
Referenced by xpn_init_partition(), xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), xpn_simple_close(), xpn_simple_closedir(), xpn_simple_creat(), xpn_simple_flush(), xpn_simple_mkdir(), xpn_simple_open(), xpn_simple_preload(), xpn_simple_rename(), xpn_simple_rmdir(), xpn_simple_stat(), XpnGetAtribFd(), XpnGetAtribPath(), and XpnGetServer().
Variable Documentation
errno
int errno [extern]
Referenced by xpn_err().
xpn_errno
int xpn_errno
Definition at line 38 of file xpn_err.c.
Referenced by xpn_err().