xpn_open.h File Reference
Header file to 'TODO'.
#include xpn.h
#include xpn_file.h
#include xpn_policy_open.h
#include xpn_policy_cwd.h
#include xpn_init.h
#include xpn_rw.h
#include base/workers.h
Functions
FILE * xpn_fopencookie (const char *path, const char *mode)
'TODO'.
int xpn_simple_open (const char *path, int flags, mode_t mode)
'TODO'.
int xpn_simple_creat (const char *path, mode_t perm)
'TODO'.
FILE * xpn_simple_fopen (const char *filename, const char *mode)
'TODO'.
int xpn_simple_close (int fd)
'TODO'.
int xpn_simple_unlink (const char *path)
'TODO'.
int xpn_simple_rename (const char *path, const char *newpath)
'TODO'.
int xpn_simple_fstat (int fd, struct stat *sb)
'TODO'.
int xpn_simple_fclose (FILE *fp)
'TODO'.
int xpn_simple_stat (const char *path, struct stat *sb)
'TODO'.
int xpn_simple_chown (const char *path, uid_t owner, gid_t group)
'TODO'.
int xpn_simple_fchown (int fd, uid_t owner, gid_t group)
'TODO'.
int xpn_simple_chmod (const char *path, mode_t mode)
'TODO'.
int xpn_simple_fchmod (int fd, mode_t mode)
'TODO'.
int xpn_simple_truncate (const char *path, off_t length)
'TODO'.
int xpn_simple_ftruncate (int fd, off_t length)
'TODO'.
int xpn_simple_dup (int fd)
'TODO'.
int xpn_simple_dup2 (int fd, int fd2)
'TODO'.
int xpn_simple_flush (const char *virtual_path, const char *storage_path)
'TODO'.
int xpn_simple_preload (const char *virtual_path, const char *storage_path)
'TODO'.
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_open.h.
Function Documentation
xpn_fopencookie()
FILE * xpn_fopencookie (const char * path, const char * mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 82 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_chmod()
int xpn_simple_chmod (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
xpn_simple_chown()
int xpn_simple_chown (const char * path, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
xpn_simple_close()
int xpn_simple_close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 931 of file xpn_open.c.
References xpn_filedesc::data_vfh, xpn_filedesc::links, xpn_fh::n_nfih, nfi_ops::nfi_close, xpn_fh::nfih, nfi_server::ops, nfi_fhandle::server, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, xpn_err(), xpn_file_table, XPN_MAX_FILE, and XPN_OK.
Referenced by xpn_cleaner(), xpn_close(), and xpn_simple_fclose().
xpn_simple_creat()
int xpn_simple_creat (const char * path, mode_t perm)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
Returns
'TODO'.
Definition at line 812 of file xpn_open.c.
References PATH_MAX, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_err(), xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), and XPN_OK.
Referenced by xpn_creat().
xpn_simple_dup()
int xpn_simple_dup (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 1351 of file xpn_open.c.
References xpn_filedesc::links, xpn_file_table, and XPN_MAX_FILE.
Referenced by xpn_dup().
xpn_simple_dup2()
int xpn_simple_dup2 (int fd, int fd2)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
fd2 'TODO'.
Returns
'TODO'.
Definition at line 1381 of file xpn_open.c.
References xpn_filedesc::links, xpn_file_table, and XPN_MAX_FILE.
Referenced by xpn_dup2().
xpn_simple_fchmod()
int xpn_simple_fchmod (int fd, mode_t mode)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
mode 'TODO'.
Returns
'TODO'.
xpn_simple_fchown()
int xpn_simple_fchown (int fd, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
xpn_simple_fclose()
int xpn_simple_fclose (FILE * fp)
'TODO'.
'TODO'.
Parameters
fp 'TODO'.
Returns
'TODO'.
Definition at line 174 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_flush()
int xpn_simple_flush (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 724 of file xpn_open.c.
References nfi_worker_do_flush(), nfiworker_wait(), op_xpn_flush, PATH_MAX, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, xpn_err(), nfi_server::xpn_thread, XpnCreateMetadata(), XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetMetadataPos(), XpnGetPartition(), XpnGetServers(), and XpnGetURLServer().
Referenced by xpn_flush().
xpn_simple_fopen()
FILE * xpn_simple_fopen (const char * filename, const char * mode)
'TODO'.
'TODO'.
Parameters
filename 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 129 of file xpn/xpn_simple/xpncore/xpn_stdio.c.
xpn_simple_fstat()
int xpn_simple_fstat (int fd, struct stat * sb)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 1254 of file xpn_open.c.
References errno, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, and XpnGetAtribFd().
Referenced by xpn_fstat(), and xpn_simple_lseek().
xpn_simple_ftruncate()
int xpn_simple_ftruncate (int fd, off_t length)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
length 'TODO'.
Returns
'TODO'.
xpn_simple_open()
int xpn_simple_open (const char * path, int flags, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 860 of file xpn_open.c.
References errno, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, PATH_MAX, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_err(), xpn_internal_creat(), xpn_internal_open(), xpn_internal_remove(), XPN_OK, and xpn_simple_stat().
Referenced by xpn_fopencookie(), xpn_open(), xpn_simple_fopen(), and xpn_simple_opendir().
xpn_simple_preload()
int xpn_simple_preload (const char * virtual_path, const char * storage_path)
'TODO'.
'TODO'.
Parameters
virtual_path 'TODO'.
storage_path 'TODO'.
Returns
'TODO'.
Definition at line 629 of file xpn_open.c.
References nfi_worker_do_preload(), nfiworker_wait(), op_xpn_flush, PATH_MAX, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_ARGS2, XPN_DEBUG_END, xpn_err(), nfi_server::xpn_thread, XpnCreateMetadata(), XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetMetadataPos(), XpnGetPartition(), XpnGetServers(), and XpnGetURLServer().
Referenced by xpn_preload().
xpn_simple_rename()
int xpn_simple_rename (const char * path, const char * newpath)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
newpath 'TODO'.
Returns
'TODO'.
Definition at line 1037 of file xpn_open.c.
References xpn_fh::n_nfih, nfi_ops::nfi_close, nfi_worker_do_rename(), xpn_fh::nfih, nfiworker_wait(), op_xpn_rename, nfi_server::ops, PATH_MAX, nfi_fhandle::priv_fh, nfi_fhandle::server, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, xpn_err(), nfi_server::xpn_thread, XPNERR_NOMEMORY, XPNERR_PARAM, XPNERR_PART_NOEXIST, XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), XpnGetPartition(), XpnGetServers(), XpnGetURLServer(), XpnReadMetadata(), and XpnUpdateMetadata().
Referenced by xpn_rename().
xpn_simple_stat()
int xpn_simple_stat (const char * path, struct stat * sb)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 1274 of file xpn_open.c.
References errno, PATH_MAX, XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, xpn_err(), XPNERR_PATH_NOEXIST, XpnGetAbsolutePath(), and XpnGetAtribPath().
Referenced by xpn_simple_open(), and xpn_stat().
xpn_simple_truncate()
int xpn_simple_truncate (const char * path, off_t length)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
length 'TODO'.
Returns
'TODO'.
xpn_simple_unlink()
int xpn_simple_unlink (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 1025 of file xpn_open.c.
References XPN_DEBUG_BEGIN_ARGS1, XPN_DEBUG_END_ARGS1, and xpn_internal_remove().
Referenced by xpn_unlink().