mpi_server_comm.h File Reference
Header file to 'TODO'.
#include all_system.h
#include mpi_server_params.h
#include base/utils.h
#include base/ns.h
#include mpi_server_ops.h
Functions
int mpiClient_comm_init (mpiClient_param_st *params)
int mpiClient_comm_destroy (mpiClient_param_st *params)
int mpiClient_comm_connect (mpiClient_param_st *params)
int mpiClient_comm_disconnect (mpiClient_param_st *params)
int mpiClient_comm_locality (mpiClient_param_st *params)
ssize_t mpiClient_write_operation (MPI_Comm fd, char *data, ssize_t size, char *msg_id)
ssize_t mpiClient_write_data (MPI_Comm fd, char *data, ssize_t size, char *msg_id)
ssize_t mpiClient_read_data (MPI_Comm fd, char *data, ssize_t size, char *msg_id)
Detailed Description
Header file to 'TODO'.
Header file to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.h.
Function Documentation
mpiClient_comm_connect()
int mpiClient_comm_connect (mpiClient_param_st * params)
Definition at line 144 of file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.c.
References debug_error, debug_info, ns_lookup(), params, mpi_server_param_st::port_name, mpi_server_param_st::rank, and mpi_server_param_st::srv_name.
Referenced by nfi_mpi_server_connect(), and nfi_mpi_server_reconnect().
mpiClient_comm_destroy()
int mpiClient_comm_destroy (mpiClient_param_st * params)
Definition at line 108 of file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.c.
References debug_error, debug_info, params, mpi_server_param_st::rank, and mpi_server_param_st::size.
Referenced by nfi_mpi_server_destroy().
mpiClient_comm_disconnect()
int mpiClient_comm_disconnect (mpiClient_param_st * params)
Definition at line 226 of file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.c.
References debug_error, debug_info, MPI_SERVER_DISCONNECT, params, and mpi_server_param_st::rank.
Referenced by nfi_mpi_server_disconnect().
mpiClient_comm_init()
int mpiClient_comm_init (mpiClient_param_st * params)
Definition at line 40 of file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.c.
References debug_error, debug_info, MPI_Init(), params, mpi_server_param_st::port_name, mpi_server_param_st::rank, and mpi_server_param_st::size.
Referenced by nfi_mpi_server_init().
mpiClient_comm_locality()
int mpiClient_comm_locality (mpiClient_param_st * params)
Definition at line 255 of file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.c.
References debug_info, debug_warning, mpi_server_param_st::dirbase, MPI_SERVER_GETNODENAME, params, PATH_MAX, and serv_name.
Referenced by nfi_mpi_server_init().
mpiClient_read_data()
ssize_t mpiClient_read_data (MPI_Comm fd, char * data, ssize_t size, char * msg_id)
Definition at line 390 of file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.c.
References debug_info, and debug_warning.
Referenced by nfi_mpi_server_doRequest(), nfi_mpi_server_read(), and nfi_mpi_server_write().
mpiClient_write_data()
ssize_t mpiClient_write_data (MPI_Comm fd, char * data, ssize_t size, char * msg_id)
Definition at line 358 of file xpn_client/nfi/nfi_mpi_server/mpi_server_comm.c.
References debug_info, and debug_warning.
Referenced by mpi_server_write_operation(), and nfi_mpi_server_write().
mpiClient_write_operation()
ssize_t mpiClient_write_operation (MPI_Comm fd, char * data, ssize_t size, char * msg_id)