xpn_rw.c File Reference
File to 'TODO'.
#include xpn/xpn_simple/xpn_rw.h
Functions
void XpnShowFileTable ()
'TODO'.
ssize_t xpn_simple_read (int fd, void *buffer, size_t size)
'TODO'.
ssize_t xpn_simple_write (int fd, const void *buffer, size_t size)
'TODO'.
ssize_t xpn_sread (int fd, const void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_pread (int fd, void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_swrite (int fd, const void *buffer, size_t size, off_t offset)
'TODO'.
ssize_t xpn_pwrite (int fd, const void *buffer, size_t size, off_t offset)
'TODO'.
off_t xpn_simple_lseek (int fd, off_t offset, int flag)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_rw.c.
Function Documentation
xpn_pread()
ssize_t xpn_pread (int fd, void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 209 of file xpn_rw.c.
References xpn_filedesc::block_size, nfi_worker_io::buffer, errno, xpn_filedesc::id, nfi_worker_do_read(), nfiworker_wait(), O_WRONLY, nfi_worker_io::offset, xpn_filedesc::offset, op_xpn_read, xpn_filedesc::path, nfi_worker_io::size, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, XPN_DIR, xpn_file_table, XPN_MAX_FILE, nfi_server::xpn_thread, XpnGetFh(), XpnGetMetadataPos(), XpnGetServers(), XpnReadBlocks(), XpnReadBlocksFinish(), XpnReadGetTotalBytes(), and XpnShowFileTable().
Referenced by xpn_simple_read().
xpn_pwrite()
ssize_t xpn_pwrite (int fd, const void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 573 of file xpn_rw.c.
References xpn_filedesc::block_size, nfi_worker_io::buffer, xpn_filedesc::id, nfi_worker_do_write(), nfiworker_wait(), O_RDONLY, nfi_worker_io::offset, xpn_filedesc::offset, op_xpn_write, xpn_filedesc::path, nfi_worker_io::size, nfi_worker::thread, nfi_server::wrk, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, XPN_DIR, xpn_file_table, XPN_MAX_FILE, nfi_server::xpn_thread, XpnGetFh(), XpnGetMetadataPos(), XpnGetServers(), XpnWriteBlocks(), XpnWriteBlocksFinish(), and XpnWriteGetTotalBytes().
Referenced by xpn_simple_write().
xpn_simple_lseek()
off_t xpn_simple_lseek (int fd, off_t offset, int flag)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
flag 'TODO'.
Returns
'TODO'.
Definition at line 833 of file xpn_rw.c.
References errno, xpn_filedesc::offset, st, xpn_file_table, and xpn_simple_fstat().
Referenced by xpn_lseek(), xpn_seeker(), xpn_simple_fseek(), and xpn_simple_rewind().
xpn_simple_read()
ssize_t xpn_simple_read (int fd, void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 45 of file xpn_rw.c.
References errno, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, xpn_file_table, xpn_pread(), xpn_sread(), and XpnShowFileTable().
Referenced by xpn_read(), xpn_reader(), xpn_simple_fgetc(), and xpn_simple_fread().
xpn_simple_write()
ssize_t xpn_simple_write (int fd, const void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 74 of file xpn_rw.c.
References errno, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, xpn_file_table, xpn_pwrite(), xpn_swrite(), and XpnShowFileTable().
Referenced by xpn_simple_fwrite(), xpn_write(), and xpn_writer().
xpn_sread()
ssize_t xpn_sread (int fd, const void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 103 of file xpn_rw.c.
References xpn_filedesc::block_size, errno, xpn_filedesc::id, nfi_ops::nfi_read, O_WRONLY, xpn_filedesc::offset, op_xpn_read, nfi_server::ops, xpn_filedesc::path, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DEBUG_END_CUSTOM, XPN_DIR, xpn_file_table, XPN_HEADER_SIZE, XPN_MAX_FILE, XpnGetBlock(), XpnGetFh(), XpnGetServers(), and XpnShowFileTable().
Referenced by xpn_simple_read().
xpn_swrite()
ssize_t xpn_swrite (int fd, const void * buffer, size_t size, off_t offset)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
offset 'TODO'.
Returns
'TODO'.
Definition at line 473 of file xpn_rw.c.
References xpn_filedesc::block_size, xpn_filedesc::id, nfi_ops::nfi_write, O_RDONLY, xpn_filedesc::offset, op_xpn_write, nfi_server::ops, xpn_filedesc::path, XPN_DATA_SERVER, XPN_DEBUG_BEGIN_CUSTOM, XPN_DIR, xpn_file_table, XPN_HEADER_SIZE, XPN_MAX_FILE, XpnGetBlock(), XpnGetFh(), and XpnGetServers().
Referenced by xpn_simple_write().
XpnShowFileTable()
void XpnShowFileTable (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
Nothing.
Definition at line 59 of file xpn_open.c.
References xpn_filedesc::path, xpn_file_table, and XPN_MAX_FILE.
Referenced by xpn_pread(), xpn_simple_read(), xpn_simple_write(), and xpn_sread().