xpn_unistd.c File Reference
File to 'TODO'.
#include xpn.h
#include xpn_client/xpn/xpn_simple/xpn_simple_lib.h
Functions
int xpn_init (void)
'TODO'.
int xpn_destroy (void)
'TODO'.
int xpn_creat (const char *path, mode_t perm)
'TODO'.
int xpn_open (const char *path, int flags,...)
'TODO'.
int xpn_close (int fd)
'TODO'.
ssize_t xpn_read (int fd, void *buffer, size_t size)
'TODO'.
ssize_t xpn_write (int fd, const void *buffer, size_t size)
'TODO'.
off_t xpn_lseek (int fd, off_t offset, int flag)
'TODO'.
char * xpn_getcwd (char *path, size_t size)
'TODO'.
int xpn_chdir (char *path)
'TODO'.
int xpn_mkdir (const char *path, mode_t perm)
'TODO'.
int xpn_rmdir (const char *path)
'TODO'.
DIR * xpn_opendir (const char *path)
'TODO'.
struct dirent * xpn_readdir (DIR *dirp)
'TODO'.
int xpn_closedir (DIR *dirp)
'TODO'.
void xpn_rewinddir (DIR *dirp)
'TODO'.
int xpn_unlink (const char *path)
'TODO'.
int xpn_rename (const char *path, const char *newpath)
'TODO'.
int xpn_truncate (const char *path, off_t length)
'TODO'.
int xpn_ftruncate (int fd, off_t length)
'TODO'.
int xpn_stat (const char *path, struct stat *sb)
'TODO'.
int xpn_fstat (int fd, struct stat *sb)
'TODO'.
int xpn_chown (const char *path, uid_t owner, gid_t group)
'TODO'.
int xpn_fchown (int fd, uid_t owner, gid_t group)
'TODO'.
int xpn_chmod (const char *path, mode_t mode)
'TODO'.
int xpn_fchmod (int fd, mode_t mode)
'TODO'.
int xpn_dup (int fd)
'TODO'.
int xpn_dup2 (int fd, int fd2)
'TODO'.
Detailed Description
File to 'TODO'.
File to 'TODO'.
Authors
Felix Garcia Carballeira, Diego Camarmas Alonso, Alejandro Calderon Mateos, Luis Miguel Sanchez Garcia, Borja Bergua Guerra
Date
Jul 22, 2021
Bug
Bug No known bugs.
Definition in file xpn_unistd.c.
Function Documentation
xpn_chdir()
int xpn_chdir (char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 151 of file xpn_unistd.c.
References xpn_simple_chdir().
Referenced by chdir().
xpn_chmod()
int xpn_chmod (const char * path, mode_t mode)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 294 of file xpn_unistd.c.
References xpn_simple_chmod().
Referenced by chmod().
xpn_chown()
int xpn_chown (const char * path, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 276 of file xpn_unistd.c.
References xpn_simple_chown().
Referenced by chown().
xpn_close()
int xpn_close (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 98 of file xpn_unistd.c.
References xpn_simple_close().
Referenced by close(), and main().
xpn_closedir()
int xpn_closedir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 204 of file xpn_unistd.c.
References xpn_simple_closedir().
Referenced by closedir(), and main().
xpn_creat()
int xpn_creat (const char * path, mode_t perm)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
Returns
'TODO'.
Definition at line 68 of file xpn_unistd.c.
References xpn_simple_creat().
Referenced by creat().
xpn_destroy()
int xpn_destroy (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 55 of file xpn_unistd.c.
References xpn_simple_destroy().
Referenced by exit(), main(), and MPI_Finalize().
xpn_dup()
int xpn_dup (int fd)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
Returns
'TODO'.
Definition at line 316 of file xpn_unistd.c.
References xpn_simple_dup().
Referenced by dup().
xpn_dup2()
int xpn_dup2 (int fd, int fd2)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
fd2 'TODO'.
Returns
'TODO'.
Definition at line 325 of file xpn_unistd.c.
References xpn_simple_dup2().
Referenced by dup2().
xpn_fchmod()
int xpn_fchmod (int fd, mode_t mode)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
mode 'TODO'.
Returns
'TODO'.
Definition at line 303 of file xpn_unistd.c.
References xpn_simple_fchmod().
Referenced by fchmod().
xpn_fchown()
int xpn_fchown (int fd, uid_t owner, gid_t group)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
owner 'TODO'.
group 'TODO'.
Returns
'TODO'.
Definition at line 285 of file xpn_unistd.c.
References xpn_simple_fchown().
xpn_fstat()
int xpn_fstat (int fd, struct stat * sb)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 267 of file xpn_unistd.c.
References xpn_simple_fstat().
Referenced by __fxstat(), __fxstat64(), and add_xpn_file_to_fdstable().
xpn_ftruncate()
int xpn_ftruncate (int fd, off_t length)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 249 of file xpn_unistd.c.
References xpn_simple_ftruncate().
Referenced by ftruncate().
xpn_getcwd()
char * xpn_getcwd (char * path, size_t size)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 142 of file xpn_unistd.c.
References xpn_simple_getcwd().
xpn_init()
int xpn_init (void)
'TODO'.
'TODO'.
Parameters
None.
Returns
'TODO'.
Definition at line 46 of file xpn_unistd.c.
References xpn_simple_init().
Referenced by main(), mpi_server_d2xpn(), tcp_server_d2xpn(), and xpn_adaptor_keepInit().
xpn_lseek()
off_t xpn_lseek (int fd, off_t offset, int flag)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
offset 'TODO'.
flag 'TODO'.
Returns
'TODO'.
Definition at line 129 of file xpn_unistd.c.
References xpn_simple_lseek().
Referenced by lseek(), and lseek64().
xpn_mkdir()
int xpn_mkdir (const char * path, mode_t perm)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
perm 'TODO'.
Returns
'TODO'.
Definition at line 164 of file xpn_unistd.c.
References xpn_simple_mkdir().
Referenced by main(), and mkdir().
xpn_open()
int xpn_open (const char * path, int flags, ...)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
flags 'TODO'.
Returns
'TODO'.
Definition at line 77 of file xpn_unistd.c.
References O_CREAT, and xpn_simple_open().
Referenced by __open_2(), main(), mpi_server_d2xpn(), open(), open64(), and tcp_server_d2xpn().
xpn_opendir()
DIR * xpn_opendir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 186 of file xpn_unistd.c.
References xpn_simple_opendir().
Referenced by main(), and opendir().
xpn_read()
ssize_t xpn_read (int fd, void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 111 of file xpn_unistd.c.
References xpn_simple_read().
Referenced by main(), and read().
xpn_readdir()
struct dirent * xpn_readdir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
'TODO'.
Definition at line 195 of file xpn_unistd.c.
References xpn_simple_readdir().
Referenced by main(), readdir(), and readdir64().
xpn_rename()
int xpn_rename (const char * path, const char * newpath)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
newpath 'TODO'.
Returns
'TODO'.
Definition at line 231 of file xpn_unistd.c.
References xpn_simple_rename().
Referenced by rename().
xpn_rewinddir()
void xpn_rewinddir (DIR * dirp)
'TODO'.
'TODO'.
Parameters
dirp 'TODO'.
Returns
Nothing.
Definition at line 213 of file xpn_unistd.c.
References xpn_simple_rewinddir().
xpn_rmdir()
int xpn_rmdir (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 173 of file xpn_unistd.c.
References xpn_simple_rmdir().
Referenced by main(), and rmdir().
xpn_stat()
int xpn_stat (const char * path, struct stat * sb)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
sb 'TODO'.
Returns
'TODO'.
Definition at line 258 of file xpn_unistd.c.
References xpn_simple_stat().
Referenced by __lxstat(), __lxstat64(), __xstat(), __xstat64(), and main().
xpn_truncate()
int xpn_truncate (const char * path, off_t length)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
length 'TODO'.
Returns
'TODO'.
Definition at line 240 of file xpn_unistd.c.
References xpn_simple_truncate().
xpn_unlink()
int xpn_unlink (const char * path)
'TODO'.
'TODO'.
Parameters
path 'TODO'.
Returns
'TODO'.
Definition at line 222 of file xpn_unistd.c.
References xpn_simple_unlink().
Referenced by main(), and unlink().
xpn_write()
ssize_t xpn_write (int fd, const void * buffer, size_t size)
'TODO'.
'TODO'.
Parameters
fd 'TODO'.
buffer 'TODO'.
size 'TODO'.
Returns
'TODO'.
Definition at line 120 of file xpn_unistd.c.
References xpn_simple_write().
Referenced by main(), write(), and write_func().