xpncp_th.c File Reference
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include <pthread.h>
#include <stdlib.h>
#include <ctype.h>
#include <fcntl.h>
#include <argp.h>
#include xpn.h
Data Structures
struct write_args
struct buffer_st
struct arguments
Macros
#define BAR_LENGTH 50
#define KB (1024)
#define MB (KB * KB)
Functions
void print_bar ()
void * progression_bar (__attribute__((unused)) void *arg)
void * write_func (void *func_args)
char * help_filter (int key, const char *text, __attribute__((__unused__)) void *input)
static error_t parse_opt (int key, char *arg, struct argp_state *state)
int main (int argc, char *argv[])
Variables
struct stat st
struct timeval t_ini_transfer t_end_transfer t_old_transfer
double transfer_t
double transfer_bw
ssize_t sum
ssize_t sum_old
char bar [BAR_LENGTH+1]
int bar_length
int silent = 0
int very_silent = 0
int debug = 0
struct buffer_st ** array_bufs = NULL
ssize_t next = 0
ssize_t last = 0
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
pthread_cond_t cond = PTHREAD_COND_INITIALIZER
pthread_mutex_t xpn_mutex = PTHREAD_MUTEX_INITIALIZER
const char * argp_program_version = xpncp_th 1.0
const char * argp_program_bug_address = https://github.com/xpn-arcos/xpn
static char doc [] = A copy program for Expand partitions that uses threads
static struct argp_option options []
static struct argp argp = {options, parse_opt, 0, doc, 0, help_filter, 0}
Macro Definition Documentation
BAR_LENGTH
#define BAR_LENGTH 50
Definition at line 32 of file xpncp_th.c.
KB
#define KB (1024)
Definition at line 35 of file xpncp_th.c.
MB
#define MB (KB * KB)
Definition at line 39 of file xpncp_th.c.
Function Documentation
help_filter()
char * help_filter (int key, const char * text, __attribute__((__unused__)) void * input)
Definition at line 192 of file xpncp_th.c.
main()
int main (int argc, char * argv[])
Definition at line 359 of file xpncp_th.c.
References argp, array_bufs, buf, arguments::buffer_size, close(), cond, arguments::debug, debug, arguments::dest, arguments::do_stat, exit(), write_args::fdd, KB, last, MB, mutex, O_CREAT, O_NONBLOCK, O_RDONLY, O_TRUNC, O_WRONLY, open(), write_args::out_transfer_t, print_bar(), progression_bar(), read(), arguments::silent, silent, arguments::source, arguments::st, st, sum, transfer_bw, transfer_t, arguments::very_silent, very_silent, write_func(), xpn_close(), xpn_destroy(), xpn_init(), xpn_mutex, xpn_open(), xpn_read(), xpn_stat(), write_args::xpndest, and write_args::xpnsource.
parse_opt()
static error_t parse_opt (int key, char * arg, struct argp_state * state) [static]
Definition at line 253 of file xpncp_th.c.
References arguments::buffer_size, arguments::debug, arguments::dest, arguments::do_stat, arguments::silent, arguments::source, arguments::st, and arguments::very_silent.
print_bar()
void print_bar (void)
Definition at line 52 of file xpncp_th.c.
References bar, BAR_LENGTH, bar_length, MB, silent, st, sum, sum_old, t_old_transfer, transfer_bw, and transfer_t.
Referenced by main(), and progression_bar().
progression_bar()
void * progression_bar (__attribute__((unused)) void * arg)
Definition at line 79 of file xpncp_th.c.
References bar, BAR_LENGTH, bar_length, print_bar(), sum, sum_old, and very_silent.
Referenced by main().
write_func()
void * write_func (void * func_args)
Definition at line 129 of file xpncp_th.c.
References array_bufs, buffer_st::buffer, buffer_st::buffer_length, cond, debug, write_args::fdd, fsync(), last, mutex, next, write_args::out_transfer_t, st, sum, very_silent, write(), xpn_mutex, xpn_write(), write_args::xpndest, and write_args::xpnsource.
Referenced by main().
Variable Documentation
argp
struct argp argp = {options, parse_opt, 0, doc, 0, help_filter, 0} [static]
Definition at line 357 of file xpncp_th.c.
Referenced by main().
argp_program_bug_address
const char* argp_program_bug_address = https://github.com/xpn-arcos/xpn
Definition at line 189 of file xpncp_th.c.
argp_program_version
const char* argp_program_version = xpncp_th 1.0
Definition at line 188 of file xpncp_th.c.
array_bufs
struct buffer_st** array_bufs = NULL
Definition at line 123 of file xpncp_th.c.
Referenced by main(), and write_func().
bar
char bar[BAR_LENGTH+1]
Definition at line 46 of file xpncp_th.c.
Referenced by print_bar(), and progression_bar().
bar_length
int bar_length
Definition at line 47 of file xpncp_th.c.
Referenced by print_bar(), and progression_bar().
cond
pthread_cond_t cond = PTHREAD_COND_INITIALIZER
Definition at line 126 of file xpncp_th.c.
Referenced by main(), and write_func().
debug
int debug = 0
Definition at line 50 of file xpncp_th.c.
Referenced by main(), and write_func().
doc
char doc[] = A copy program for Expand partitions that uses threads [static]
Definition at line 190 of file xpncp_th.c.
last
ssize_t last = 0
Definition at line 124 of file xpncp_th.c.
Referenced by main(), and write_func().
mutex
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 125 of file xpncp_th.c.
Referenced by main(), and write_func().
next
ssize_t next = 0
Definition at line 124 of file xpncp_th.c.
Referenced by write_func().
options
struct argp_option options[] [static]
Initial value:
= {
        {"buffer-size", 'b', "BUFFER_SIZE", 0, "Buffer size", 0},
        {"file-size", 'i', "FILE_SIZE", 0, "File size", 0},
        {"silent", 's', 0, 0, "Silent", 0},
        {"very-silent", 'S', 0, 0, "Very silent", 0},
        {"debug", 'd', 0, 0, "Debug", 0},
        {0, 0, 0, 0, 0, 0}}
Definition at line 231 of file xpncp_th.c.
silent
int silent = 0
Definition at line 48 of file xpncp_th.c.
Referenced by main(), and print_bar().
st
struct stat st
Definition at line 42 of file xpncp_th.c.
Referenced by main(), print_bar(), and write_func().
sum
ssize_t sum
Definition at line 45 of file xpncp_th.c.
Referenced by main(), print_bar(), progression_bar(), and write_func().
sum_old
ssize_t sum_old
Definition at line 45 of file xpncp_th.c.
Referenced by print_bar(), and progression_bar().
t_old_transfer
struct timeval t_ini_transfer t_end_transfer t_old_transfer
Definition at line 43 of file xpncp_th.c.
Referenced by print_bar().
transfer_bw
double transfer_bw
Definition at line 44 of file xpncp_th.c.
Referenced by main(), and print_bar().
transfer_t
double transfer_t
Definition at line 44 of file xpncp_th.c.
Referenced by main(), and print_bar().
very_silent
int very_silent = 0
Definition at line 49 of file xpncp_th.c.
Referenced by main(), progression_bar(), and write_func().
xpn_mutex
pthread_mutex_t xpn_mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 127 of file xpncp_th.c.
Referenced by main(), and write_func().