xpnwriter.c File Reference
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include <pthread.h>
#include <stdlib.h>
#include <ctype.h>
#include <fcntl.h>
#include xpn.h
Macros
#define BAR_LENGTH 50
#define KB (1024)
#define MB (KB * KB)
Functions
void usage ()
int main (int argc, char *argv[])
Variables
char * program_name
Macro Definition Documentation
BAR_LENGTH
#define BAR_LENGTH 50
Definition at line 31 of file xpnwriter.c.
KB
#define KB (1024)
Definition at line 34 of file xpnwriter.c.
MB
#define MB (KB * KB)
Definition at line 38 of file xpnwriter.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 48 of file xpnwriter.c.
References close(), exit(), KB, O_CREAT, O_TRUNC, O_WRONLY, open(), program_name, usage(), write(), xpn_close(), xpn_destroy(), xpn_init(), xpn_open(), and xpn_write().
usage()
void usage ()
Definition at line 43 of file xpnwriter.c.
References program_name.
Referenced by main().
Variable Documentation
program_name
char* program_name
Definition at line 41 of file xpnwriter.c.
Referenced by main(), usage(), and usage().