<!-- wsdl2h -c -t typemap.dat -o xpnuploader.h xpnuploader.wsdl -->

<?xml version="1.0" encoding="UTF-8"?>
<definitions name="xpnuploader"
 targetNamespace="urn:xpnuploader"
 xmlns:tns="urn:xpnuploader"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:ns1="urn:xpnuploader"
 xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/"
 xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="urn:xpnuploader"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:ns1="urn:xpnuploader"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 </schema>

</types>

<message name="uploadRequest">
 <part name="source" type="xsd:string"/>
 <part name="dest" type="xsd:string"/>
 <part name="partition" type="xsd:string"/>
</message>

<message name="uploadResponse">
 <part name="result" type="xsd:int"/>
</message>

<portType name="xpnuploaderPortType">
 <operation name="upload">
  <documentation>Service definition of function ns1__upload</documentation>
  <input message="tns:uploadRequest"/>
  <output message="tns:uploadResponse"/>
 </operation>
</portType>

<binding name="xpnuploader" type="tns:xpnuploaderPortType">
 <SOAP:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="upload">
  <SOAP:operation style="rpc" soapAction=""/>
  <input>
     <SOAP:body use="encoded" namespace="urn:xpnuploader" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </input>
  <output>
     <SOAP:body use="encoded" namespace="urn:xpnuploader" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </output>
 </operation>
</binding>

<service name="xpnuploader">
 <documentation>gSOAP 2.7.9k generated service definition</documentation>
 <port name="xpnuploader" binding="tns:xpnuploader">
  <SOAP:address location="http://xpn.arcos.inf.uc3m.es/xpnuploaderserver.cgi"/>
 </port>
</service>

</definitions>
