#!/bin/sh

echo ""

echo -n " Makefile.in for XPN sources..."
./bin/MakeBones.sh -m src

echo -n " Makefile.in for Test sources..."
./bin/MakeBones.sh -m test

echo -n " Makefile.in for Utils sources..."
./bin/MakeBones.sh -m utils

