#ifndef _NFI_FTP_ERR_H_
#define _NFI_FTP_ERR_H_

#include "ftp.h"

enum nfi_ftp_err{
	FTPERR_PARAM = 0,
	FTPERR_MEMORY = 1,
	FTPERR_URL = 2,
	FTPERR_SOCKETCONNECTION = 3,
	FTPERR_MOUNT = 4,
	FTPERR_FTPCONNECTION = 5,		
	FTPERR_GETATTR = 6,
	FTPERR_LOOKUP = 7,
	FTPERR_READ = 8,
	FTPERR_WRITE = 9,
	FTPERR_CREATE = 10,
	FTPERR_REMOVE = 11,
	FTPERR_RENAME = 12,
	FTPERR_MKDIR = 13,
	FTPERR_READDIR = 14,
	FTPERR_NOTDIR = 15,
	FTPERR_STATFS = 16,
};


void ftp_err(int err);


#endif
