#ifndef _NFI_IOPROXY_RPC_ERR_H_
#define _NFI_IOPROXY_RPC_ERR_H_


 #ifdef  __cplusplus
    extern "C" {
 #endif


enum nfi_ioproxy-rpc_err{
	IOPROXY_RPCERR_PARAM = 0,
	IOPROXY_RPCERR_MEMORY = 1,
	IOPROXY_RPCERR_URL = 2,
	IOPROXY_RPCERR_MNTCONNECTION = 3,
	IOPROXY_RPCERR_MOUNT = 4,
	IOPROXY_RPCERR_NFSCONNECTION = 5,		
	IOPROXY_RPCERR_GETATTR = 6,
	IOPROXY_RPCERR_LOOKUP = 7,
	IOPROXY_RPCERR_READ = 8,
	IOPROXY_RPCERR_WRITE = 9,
	IOPROXY_RPCERR_CREATE = 10,
	IOPROXY_RPCERR_REMOVE = 11,
	IOPROXY_RPCERR_MKDIR = 12,
	IOPROXY_RPCERR_READDIR = 13,
	IOPROXY_RPCERR_STATFS = 14,
	IOPROXY_RPCERR_NOTDIR = 15,
};


void ioproxy-rpc_err(int err);


 #ifdef  __cplusplus
     }
 #endif


#endif
