# Makefile for the I/O benchmark -- sphere (SGI)

# objects
OBJS = get_mfluid_property.o \
       flash_release.o \
       flash_benchmark_io.o 

OBJS_HDF5_PARALLEL_IO = checkpoint_hdf5_parallel.o \
                        plotfile_hdf5_parallel.o \
                        h5_file_interface.o \
                        h5_parallel_write.o \
                        h5_parallel_write_single.o

# compiler and linker commands
FCOMP   = /soft/apps/packages/mpich-pg-1.2.1-cvs-1/bin/mpif90
CCOMP   = /soft/apps/packages/mpich-pg-1.2.1-cvs-1/bin/mpicc
CPPCOMP = /soft/apps/packages/mpich-pg-1.2.1-cvs-1/bin/mpiCC
LINK    = /soft/apps/packages/mpich-pg-1.2.1-cvs-1/bin/mpif90


# library locations
#HDF5path = /usr/community/hdf5/hdf5-1_4_0/
HDF5path = /soft/apps/packages/hdf5-1.4.0-cvs-1
#ZLIBpath = /usr/community/hdf5/ZLIB
ZLIBpath = /usr

# compiler flags
FFLAGS = -c -fast -r8 \
         -DN_DIM=3 -DMAXBLOCKS=100 -DIONMAX=13

F90FLAGS = 

CFLAGS = -c -O4 -I $(HDF5path)/include/ -DCHIBA


# linker flags
LFLAGS = -o 



# libraries to include
LIB = -L $(HDF5path)/lib -lhdf5 -L$(ZLIBpath)/lib -lz


.SUFFIXES: .f .F .f90 .F90 .c .C .o

.F90.o :
	$(FCOMP) $(FFLAGS) $<

.f.o :
	$(FCOMP) $(FFLAGS) $<

.c.o :
	$(CCOMP) $(CFLAGS) $<

flash_benchmark_io: $(OBJS) \
                    $(OBJS_HDF5_PARALLEL_IO) 
	$(LINK) $(LFLAGS) $@ $(OBJS) $(OBJS_HDF5_PARALLEL_IO) $(LIB)

clean::
	rm -f *.o flash_benchmark_io









